gnucap: STORAGE Class Reference
STORAGE Class Reference
#include <e_storag.h>
Public Member Functions
void precalc_last ()
void tr_begin ()
void tr_restore ()
void dc_advance ()
void tr_advance ()
bool tr_needs_eval () const
TIME_PAIR tr_review ()
double tr_probe_num (const std::string &) const
double tr_c_to_g (double c, double g) const
Public Attributes
method_t _method_u
METHOD _method_a
Protected Member Functions
STORAGE ()
STORAGE (const STORAGE &p)
~STORAGE ()
Protected Attributes
FPOLY1 _i [OPT::_keep_time_steps]
Static Protected Attributes
static METHOD method_select [meNUM_METHODS][meNUM_METHODS]
Private Member Functions
int order () const
double error_factor () const
Detailed Description
Definition at line 34 of file e_storag.h.
Constructor & Destructor Documentation
STORAGE::STORAGE () [inline, explicit, protected]
Definition at line 37 of file e_storag.h.
    :ELEMENT(), _method_u(meUNKNOWN), _method_a(mTRAPGEAR)  {}
STORAGE::STORAGE (const STORAGE & p) [inline, explicit, protected]
Definition at line 39 of file e_storag.h.
    :ELEMENT(p), _method_u(p._method_u), _method_a(p._method_a) {}
STORAGE::~STORAGE () [inline, protected]
Definition at line 41 of file e_storag.h.
{}
Member Function Documentation
void STORAGE::dc_advance () [virtual]
Reimplemented from ELEMENT.
Reimplemented in DEV_SPICE, and anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 88 of file e_storag.cc.
References _i, and OPT::_keep_time_steps.
{
  ELEMENT::dc_advance();
  for (int i = 1;  i < OPT::_keep_time_steps;  ++i) {
    _i[i] = _i[0];
  }
}
double STORAGE::error_factor () const [inline, private, virtual]
Reimplemented from ELEMENT.
Definition at line 64 of file e_storag.h.
{
    const double f[]={1./2., 1./2., 1./12., 1./6., 1./2.};
    return f[_method_a];
  }
int STORAGE::order () const [inline, private, virtual]
Reimplemented from ELEMENT.
Definition at line 58 of file e_storag.h.
References OPT::_keep_time_steps.
{
    const int o[] = {1, 1, 2, 1, 1};
    int ord = o[_method_a];
    assert(ord < OPT::_keep_time_steps);
    return ord;
  }
void STORAGE::precalc_last () [virtual]
Reimplemented from ELEMENT.
Reimplemented in DEV_SPICE, and anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 55 of file e_storag.cc.
References _method_a, _method_u, CARD::is_constant(), OPT::method, method_select, and COMPONENT::set_converged().
Referenced by anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::precalc_last().
{
  ELEMENT::precalc_last();
  set_converged();
  assert(!is_constant()); /* because of integration */
  _method_a = method_select[OPT::method][_method_u];
  //assert(_loss0 == 0.);
  //assert(_loss1 == 0.);
  /* m0 and acg are frequency/time dependent and cannot be set here.
   * If this is a coupled inductor, there is a subckt, which is expanded
   * by the mutual pseudo-element.
   * Assigning the values here becomes unnecessary, but harmless.
   */
}
void STORAGE::tr_advance () [virtual]
Reimplemented from ELEMENT.
Reimplemented in DEV_SPICE, and anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 97 of file e_storag.cc.
References _i, and OPT::_keep_time_steps.
{
  ELEMENT::tr_advance();
  for (int i=OPT::_keep_time_steps-1; i>0; --i) {
    _i[i] = _i[i-1];
  }
}
void STORAGE::tr_begin () [virtual]
Reimplemented from ELEMENT.
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, and anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 72 of file e_storag.cc.
References _i, OPT::_keep_time_steps, ELEMENT::_m0, ELEMENT::_m1, _method_a, _method_u, OPT::method, and method_select.
{
  ELEMENT::tr_begin();
  _method_a = method_select[OPT::method][_method_u];
  for (int i = 0;  i < OPT::_keep_time_steps;  ++i) {
    _i[i] = FPOLY1(0., 0., 0.);
  }
  _m1 = _m0 = CPOLY1(0., 0., 0.);
}
double STORAGE::tr_c_to_g (double c, double g) const
Definition at line 173 of file e_storag.cc.
References ELEMENT::_dt, _method_a, CKT_BASE::_sim, ELEMENT::_time, SIM_DATA::analysis_is_restore(), SIM_DATA::analysis_is_static(), SIM_DATA::analysis_is_tran_dynamic(), incomplete, itested, mEULER, mGEAR, mTRAP, mTRAPEULER, and mTRAPGEAR.
Referenced by anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::do_tr().
{
  if (_sim->analysis_is_static()) {
    assert(_time[0] == 0.);
    return 0.;
  }else if (_sim->analysis_is_restore()) {itested();
    assert(_time[0] > 0);
    return g;
    // no change, fake
  }else{
    assert(_sim->analysis_is_tran_dynamic());
    METHOD method;
    if (_time[1] == 0) {
      method = mEULER; // Bogus current in previous step.  Force Euler.
    }else{
      method = _method_a;
    }
    g = c / _dt;
    switch (method) {
    case mTRAPGEAR: incomplete();
    case mGEAR:  g *= 3./2.;    break;
    case mTRAPEULER: incomplete();
    case mEULER: /* g *= 1 */   break;
    case mTRAP:  g *= 2;        break;
    }
    return g;
  }
}
bool STORAGE::tr_needs_eval () const [virtual]
Reimplemented from ELEMENT.
Reimplemented in DEV_SPICE, and anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP.
Definition at line 112 of file e_storag.cc.
References CKT_BASE::_sim, ELEMENT::_y, OPT::abstol, conchk(), COMPONENT::converged(), SIM_DATA::is_advance_or_first_iteration(), OPT::lcbypass, ELEMENT::tr_input(), and SIM_DATA::uic_now().
{
  //assert(!is_q_for_eval());
  return (!OPT::lcbypass
          || !converged()
          || _sim->is_advance_or_first_iteration()
          || !conchk(_y[0].x, tr_input(), OPT::abstol)
          || _sim->uic_now());
}
double STORAGE::tr_probe_num (const std::string & x) const [virtual]
Reimplemented from ELEMENT.
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, and anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE.
Definition at line 214 of file e_storag.cc.
References _method_a, Umatch(), and untested.
Referenced by anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::tr_probe_num().
{
  if (Umatch(x, "method ")) {untested();
    return static_cast<double>(_method_a);
  }else{
    return ELEMENT::tr_probe_num(x);
  }
}
void STORAGE::tr_restore () [virtual]
Reimplemented from ELEMENT.
Reimplemented in DEV_SPICE.
Definition at line 82 of file e_storag.cc.
References _method_a, _method_u, OPT::method, and method_select.
{
  ELEMENT::tr_restore();
  _method_a = method_select[OPT::method][_method_u];
}
TIME_PAIR STORAGE::tr_review () [virtual]
Reimplemented from ELEMENT.
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, and anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP.
Definition at line 202 of file e_storag.cc.
References _method_a, COMPONENT::_time_by, ELEMENT::_y, mEULER, TIME_PAIR::min_error_estimate(), ELEMENT::tr_review_check_and_convert(), and ELEMENT::tr_review_trunc_error().
{
  COMPONENT::tr_review(); // skip ELEMENT
  if (_method_a == mEULER) {
    // Backward Euler, no step control, take it as it comes
  }else{
    double timestep = tr_review_trunc_error(_y);
    _time_by.min_error_estimate(tr_review_check_and_convert(timestep));
  }
  return _time_by;
}
Member Data Documentation
FPOLY1 STORAGE::_i[OPT::_keep_time_steps] [protected]
Definition at line 72 of file e_storag.h.
Referenced by dc_advance(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_tr(), anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::do_tr(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::do_tr_last(), tr_advance(), and tr_begin().
METHOD STORAGE::_method_a
Definition at line 70 of file e_storag.h.
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_tr(), anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::do_tr(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::do_tr_last(), DEV_SPICE::localize_ckt(), precalc_last(), tr_begin(), tr_c_to_g(), tr_probe_num(), tr_restore(), and tr_review().
method_t STORAGE::_method_u
Definition at line 69 of file e_storag.h.
Referenced by precalc_last(), tr_begin(), and tr_restore().
METHOD STORAGE::method_select [static, protected]
Initial value:
 {
  {mTRAPGEAR,mEULER,mEULER,mTRAP, mTRAP,mGEAR, mGEAR,mTRAPGEAR,mTRAPEULER},
  {mEULER,   mEULER,mEULER,mTRAP, mTRAP,mGEAR, mGEAR,mTRAPGEAR,mTRAPEULER},
  {mEULER,   mEULER,mEULER,mEULER,mTRAP,mEULER,mGEAR,mEULER,   mEULER},
  {mTRAP,    mEULER,mEULER,mTRAP, mTRAP,mGEAR, mGEAR,mTRAPGEAR,mTRAPEULER},
  {mTRAP,    mTRAP, mEULER,mTRAP, mTRAP,mTRAP, mGEAR,mTRAP,    mTRAP},
  {mGEAR,    mEULER,mEULER,mTRAP, mTRAP,mGEAR, mGEAR,mTRAPGEAR,mTRAPEULER},
  {mGEAR,    mGEAR, mEULER,mGEAR, mTRAP,mGEAR, mGEAR,mGEAR,    mGEAR},
  {mTRAPGEAR,mEULER,mEULER,mTRAP, mTRAP,mGEAR, mGEAR,mTRAPGEAR,mTRAPEULER},
  {mTRAPEULER,mEULER,mEULER,mTRAP,mTRAP,mGEAR, mGEAR,mTRAPGEAR,mTRAPEULER}
}
Definition at line 74 of file e_storag.h.
Referenced by precalc_last(), tr_begin(), and tr_restore().
The documentation for this class was generated from the following files:
savant/gnucap/src/e_storag.h
savant/gnucap/src/e_storag.cc