gnucap: EVAL_BM_TABLE Class Reference
EVAL_BM_TABLE Class Reference
Public Member Functions
EVAL_BM_TABLE (int c=0)
~EVAL_BM_TABLE ()
Protected Member Functions
EVAL_BM_TABLE (const EVAL_BM_TABLE &p)
Private Member Functions
bool operator== (const COMMON_COMPONENT &) const
COMMON_COMPONENT * clone () const
void print_common_obsolete_callback (OMSTREAM &, LANGUAGE *) const
void expand (const COMPONENT *)
void tr_eval (ELEMENT *) const
std::string name () const
bool ac_too () const
Detailed Description
Definition at line 34 of file bmm_table.cc.
Constructor & Destructor Documentation
EVAL_BM_TABLE::EVAL_BM_TABLE (const EVAL_BM_TABLE & p) [explicit, protected]
Definition at line 93 of file bmm_table.cc.
Referenced by clone().
  :EVAL_BM_ACTION_BASE(p)
{
}
EVAL_BM_TABLE::EVAL_BM_TABLE (int c = 0) [explicit]
Definition at line 88 of file bmm_table.cc.
  :EVAL_BM_ACTION_BASE(c)
{
}
EVAL_BM_TABLE::~EVAL_BM_TABLE () [inline]
Definition at line 39 of file bmm_table.cc.
{}
Member Function Documentation
bool EVAL_BM_TABLE::ac_too () const [inline, private, virtual]
Implements EVAL_BM_ACTION_BASE.
Definition at line 47 of file bmm_table.cc.
References untested.
{untested();return false;}
COMMON_COMPONENT* EVAL_BM_TABLE::clone () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 42 of file bmm_table.cc.
References EVAL_BM_TABLE().
{return new EVAL_BM_TABLE(*this);}
void EVAL_BM_TABLE::expand (const COMPONENT * d) [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 116 of file bmm_table.cc.
References COMMON_COMPONENT::attach_model(), CARD::long_label(), COMMON_COMPONENT::model(), COMMON_COMPONENT::modelname(), and untested.
{
  EVAL_BM_ACTION_BASE::expand(d);
  attach_model(d);
  const MODEL_TABLE* m = dynamic_cast<const MODEL_TABLE*>(model());
  if (!m) {untested();
    throw Exception_Model_Type_Mismatch(d->long_label(), modelname(), "table");
  }else{
  }
}
std::string EVAL_BM_TABLE::name () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 46 of file bmm_table.cc.
References COMMON_COMPONENT::modelname(), and untested.
{untested();return modelname().c_str();}
bool EVAL_BM_TABLE::operator== (const COMMON_COMPONENT & x) const [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 98 of file bmm_table.cc.
References anonymous_namespace{c_genrat.cc}::p, and untested.
{
  const EVAL_BM_TABLE* p = dynamic_cast<const EVAL_BM_TABLE*>(&x);
  bool rv = p && EVAL_BM_ACTION_BASE::operator==(x);
  if (rv) {
    untested();
  }else{
  }
  return rv;
}
void EVAL_BM_TABLE::print_common_obsolete_callback (OMSTREAM & o, LANGUAGE * lang) const [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 109 of file bmm_table.cc.
References COMMON_COMPONENT::modelname().
{
  assert(lang);
  o << modelname();
  EVAL_BM_ACTION_BASE::print_common_obsolete_callback(o, lang);
}
void EVAL_BM_TABLE::tr_eval (ELEMENT * d) const [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 128 of file bmm_table.cc.
References ELEMENT::_y, COMPONENT::f_is_value(), COMMON_COMPONENT::model(), MODEL_CARD::tr_eval(), and EVAL_BM_ACTION_BASE::tr_final_adjust().
{
  model()->tr_eval(d);
  tr_final_adjust(&(d->_y[0]), d->f_is_value());
}
The documentation for this class was generated from the following file:
savant/gnucap/src/bmm_table.cc