gnucap: SDP_BUILT_IN_MOS2 Class Reference
SDP_BUILT_IN_MOS2 Class Reference
#include <d_mos2.h>
Public Member Functions
SDP_BUILT_IN_MOS2 (const COMMON_COMPONENT *c)
void init (const COMMON_COMPONENT *)
Public Attributes
double relxj
double eta_1
double eta
double eta_2
Detailed Description
Definition at line 34 of file d_mos2.h.
Constructor & Destructor Documentation
SDP_BUILT_IN_MOS2::SDP_BUILT_IN_MOS2 (const COMMON_COMPONENT * c) [inline, explicit]
Definition at line 37 of file d_mos2.h.
References init().
: SDP_BUILT_IN_MOS123(c) {init(c);}
Member Function Documentation
void SDP_BUILT_IN_MOS2::init (const COMMON_COMPONENT * cc) [virtual]
Reimplemented from SDP_BUILT_IN_MOS123.
Definition at line 46 of file d_mos2.cc.
References SDP_BUILT_IN_MOS_BASE::cgate, MODEL_BUILT_IN_MOS2::delta, eta, eta_1, eta_2, SDP_BUILT_IN_MOS_BASE::l_eff, COMMON_COMPONENT::model(), NA(), P_EPS_SI, prechecked_cast, relxj, CARD::scope(), and MODEL_BUILT_IN_MOS123::xj.
Referenced by SDP_BUILT_IN_MOS2().
{
  assert(cc);
  SDP_BUILT_IN_MOS123::init(cc);
  const COMMON_BUILT_IN_MOS* c = prechecked_cast<const COMMON_BUILT_IN_MOS*>(cc);
  assert(c);
  const MODEL_BUILT_IN_MOS2* m = prechecked_cast<const MODEL_BUILT_IN_MOS2*>(c->model());
  assert(m);
  const CARD_LIST* par_scope = m->scope();
  assert(par_scope);
  // adjust: override
  // adjust: raw
  // adjust: calculated
    relxj = ((m->xj != NA && m->xj > 0)
               ? .5 * m->xj / l_eff
               : NA);
    eta_1 = ((cgate != 0)
               ? M_PI_4 * P_EPS_SI * m->delta / cgate * l_eff
               : 0.);
    eta = eta_1 + 1.;
    eta_2 = eta / 2.;
  // code_post
}
Member Data Documentation
double SDP_BUILT_IN_MOS2::eta
Definition at line 42 of file d_mos2.h.
Referenced by init(), and MODEL_BUILT_IN_MOS2::tr_eval().
double SDP_BUILT_IN_MOS2::eta_1
Definition at line 41 of file d_mos2.h.
Referenced by init(), and MODEL_BUILT_IN_MOS2::tr_eval().
double SDP_BUILT_IN_MOS2::eta_2
Definition at line 43 of file d_mos2.h.
Referenced by init(), and MODEL_BUILT_IN_MOS2::tr_eval().
double SDP_BUILT_IN_MOS2::relxj
Definition at line 40 of file d_mos2.h.
Referenced by init(), and MODEL_BUILT_IN_MOS2::tr_eval().
The documentation for this class was generated from the following files:
savant/gnucap/src/d_mos2.h
savant/gnucap/src/d_mos2.cc