gnucap: savant/gnucap/src/l_compar.h File Reference
savant/gnucap/src/l_compar.h File Reference
#include "md.h"
Functions
template<class T >
bool up_order (T a, T b, T c)
template<class T >
bool in_order (T a, T b, T c)
template<class T >
T to_range (T a, T b, T c)
Function Documentation
template<class T > bool in_order (T a, T b, T c) [inline]
Definition at line 36 of file l_compar.h.
References up_order().
Referenced by anonymous_namespace{measure_slewrate.cc}::MEASURE::eval(), PROBE::in_range(), anonymous_namespace{s_dc.cc}::DCOP::next(), and anonymous_namespace{s_ac.cc}::AC::next().
{
  return up_order(a,b,c) || up_order(c,b,a);
}
template<class T > T to_range (T a, T b, T c) [inline]
Definition at line 43 of file l_compar.h.
References min().
Referenced by OPT::set_values().
{
  return std::min(std::max(a,b),c);
}
template<class T > bool up_order (T a, T b, T c) [inline]
Definition at line 29 of file l_compar.h.
Referenced by SIM_DATA::count_iterations(), in_order(), TRANSIENT::next(), SIM_DATA::reset_iteration_counter(), and TRANSIENT::sweep().
{
  return (a<=b) && (b<=c);
}