gnucap: anonymous_namespace{d_vcr.cc}::DEV_VCR Class Reference
anonymous_namespace{d_vcr.cc}::DEV_VCR Class Reference
Public Member Functions
DEV_VCR ()
Private Member Functions
DEV_VCR (const DEV_VCR &p)
char id_letter () const
std::string value_name () const
std::string dev_type () const
int max_nodes () const
int min_nodes () const
int matrix_nodes () const
int net_nodes () const
bool use_obsolete_callback_parse () const
CARD * clone () const
void precalc_last ()
void tr_iwant_matrix ()
void tr_begin ()
bool do_tr ()
void tr_load ()
void tr_unload ()
double tr_involts () const
double tr_involts_limited () const
double tr_amps () const
void ac_iwant_matrix ()
void ac_begin ()
void do_ac ()
void ac_load ()
COMPLEX ac_involts () const
COMPLEX ac_amps () const
std::string port_name (int i) const
Detailed Description
Definition at line 32 of file d_vcr.cc.
Constructor & Destructor Documentation
anonymous_namespace{d_vcr.cc}::DEV_VCR::DEV_VCR (const DEV_VCR & p) [inline, explicit, private]
Definition at line 34 of file d_vcr.cc.
:ELEMENT(p) {}
anonymous_namespace{d_vcr.cc}::DEV_VCR::DEV_VCR () [inline, explicit]
Definition at line 36 of file d_vcr.cc.
:ELEMENT() {}
Member Function Documentation
COMPLEX anonymous_namespace{d_vcr.cc}::DEV_VCR::ac_amps () const [inline, private, virtual]
Reimplemented from ELEMENT.
Definition at line 61 of file d_vcr.cc.
References ELEMENT::ac_amps(), and untested.
{untested(); return ELEMENT::ac_amps();}
void anonymous_namespace{d_vcr.cc}::DEV_VCR::ac_begin () [private, virtual]
Reimplemented from CARD.
Definition at line 112 of file d_vcr.cc.
References trace1, and trace4.
{
  _ev  = _y[0].f0;
  _acg = _m0.c1;
  trace4("vcr-ac_begin", _y[0].f0, _y[0].f1, _m0.c0, _m0.c1);
  trace4("", _ev.real(), _ev.imag(), _acg.real(), _acg.imag());
  trace1("", _loss0);
}
COMPLEX anonymous_namespace{d_vcr.cc}::DEV_VCR::ac_involts () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 60 of file d_vcr.cc.
References IN1, IN2, and untested.
{untested();return _n[IN1]->vac()-_n[IN2]->vac();}
void anonymous_namespace{d_vcr.cc}::DEV_VCR::ac_iwant_matrix () [inline, private, virtual]
Implements ELEMENT.
Definition at line 56 of file d_vcr.cc.
{ac_iwant_matrix_extended();}
void anonymous_namespace{d_vcr.cc}::DEV_VCR::ac_load () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 59 of file d_vcr.cc.
{ac_load_shunt(); ac_load_active();}
CARD* anonymous_namespace{d_vcr.cc}::DEV_VCR::clone () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 46 of file d_vcr.cc.
{return new DEV_VCR(*this);}
std::string anonymous_namespace{d_vcr.cc}::DEV_VCR::dev_type () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 40 of file d_vcr.cc.
{return "vcr";}
void anonymous_namespace{d_vcr.cc}::DEV_VCR::do_ac () [private, virtual]
Reimplemented from CARD.
Definition at line 121 of file d_vcr.cc.
References trace1, and trace4.
{
  if (using_ac_eval()) {
    ac_eval();
    _acg = -_ev * _loss0 * _loss0 * _m0.x;
    trace4("vcr-do_ac(eval)", _y[0].f0, _y[0].f1, _m0.c0, _m0.c1);
    trace4("", _ev.real(), _ev.imag(), _acg.real(), _acg.imag());
    _ev *= _y[0].x;
    trace4("", _ev.real(), _ev.imag(), _loss0, _m0.x);
  }else{
    trace4("vcr-do_ac", _y[0].f0, _y[0].f1, _m0.c0, _m0.c1);
    trace4("", _ev.real(), _ev.imag(), _acg.real(), _acg.imag());
    trace1("", _loss0);
    assert(_ev == _y[0].f0);
    assert(_acg == _m0.c1);
  }
}
bool anonymous_namespace{d_vcr.cc}::DEV_VCR::do_tr () [private, virtual]
Reimplemented from CARD.
Definition at line 89 of file d_vcr.cc.
References converged, error(), LINEAR, OPT::shortckt, and trace3.
{
  _y[0].x = tr_input_limited();
  tr_eval();
  trace3("vcr", _y[0].x, _y[0].f0, _y[0].f1);
  assert(_y[0].f0 != LINEAR);
  if (_y[0].f0 == 0.) {
    error(bDEBUG, long_label() + ": short circuit\n");
    _y[0].f0 = OPT::shortckt;
    set_converged(conv_check());
  }else{
  }
  store_values();
  q_load();
  _loss0 = 1./_y[0].f0;
  _m0.x = tr_outvolts(); // fake
  _m0.c1 = -_y[0].f1 * _loss0 * _loss0 * tr_outvolts();
  _m0.c0 = -_y[0].x * _m0.c1;
  trace3("vcr", _loss0, _m0.c0, _m0.c1);
  return converged();
}
char anonymous_namespace{d_vcr.cc}::DEV_VCR::id_letter () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 38 of file d_vcr.cc.
References itested.
{itested();return '\0';}
int anonymous_namespace{d_vcr.cc}::DEV_VCR::matrix_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 43 of file d_vcr.cc.
{return 4;}
int anonymous_namespace{d_vcr.cc}::DEV_VCR::max_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 41 of file d_vcr.cc.
{return 4;}
int anonymous_namespace{d_vcr.cc}::DEV_VCR::min_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 42 of file d_vcr.cc.
{return 4;}
int anonymous_namespace{d_vcr.cc}::DEV_VCR::net_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 44 of file d_vcr.cc.
{return 4;}
std::string anonymous_namespace{d_vcr.cc}::DEV_VCR::port_name (int i) const [inline, private, virtual]
Implements COMPONENT.
Definition at line 63 of file d_vcr.cc.
References untested.
                                  {untested();
    assert(i >= 0);
    assert(i < 4);
    static std::string names[] = {"p", "n", "ps", "ns"};
    return names[i];
  }
void anonymous_namespace{d_vcr.cc}::DEV_VCR::precalc_last () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 72 of file d_vcr.cc.
References ELEMENT::precalc_last().
{
  ELEMENT::precalc_last();
  assert(!is_constant());
  set_not_converged();
}
double anonymous_namespace{d_vcr.cc}::DEV_VCR::tr_amps () const [inline, private, virtual]
Reimplemented from ELEMENT.
Definition at line 55 of file d_vcr.cc.
References ELEMENT::tr_amps(), and untested.
{untested(); return ELEMENT::tr_amps();}
void anonymous_namespace{d_vcr.cc}::DEV_VCR::tr_begin () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 79 of file d_vcr.cc.
References OPT::shortckt, and ELEMENT::tr_begin().
{
  ELEMENT::tr_begin();
  _loss1 = _loss0 = 1./OPT::shortckt;
  _m0.x  = 0.;
  _m0.c1 = 0.;
  _m0.c0 = 0.;
  _m1 = _m0;
}
double anonymous_namespace{d_vcr.cc}::DEV_VCR::tr_involts () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 53 of file d_vcr.cc.
References dn_diff(), IN1, IN2, and untested.
{untested(); return dn_diff(_n[IN1].v0(), _n[IN2].v0());}
double anonymous_namespace{d_vcr.cc}::DEV_VCR::tr_involts_limited () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 54 of file d_vcr.cc.
References IN1, IN2, and volts_limited().
{return volts_limited(_n[IN1],_n[IN2]);}
void anonymous_namespace{d_vcr.cc}::DEV_VCR::tr_iwant_matrix () [inline, private, virtual]
Implements ELEMENT.
Definition at line 48 of file d_vcr.cc.
{tr_iwant_matrix_extended();}
void anonymous_namespace{d_vcr.cc}::DEV_VCR::tr_load () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 51 of file d_vcr.cc.
{tr_load_shunt(); tr_load_active();}
void anonymous_namespace{d_vcr.cc}::DEV_VCR::tr_unload () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 52 of file d_vcr.cc.
References untested.
{untested(); tr_unload_shunt(); tr_unload_active();}
bool anonymous_namespace{d_vcr.cc}::DEV_VCR::use_obsolete_callback_parse () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 45 of file d_vcr.cc.
{return true;}
std::string anonymous_namespace{d_vcr.cc}::DEV_VCR::value_name () const [inline, private, virtual]
Implements CARD.
Definition at line 39 of file d_vcr.cc.
References itested.
{itested(); return "r";}
The documentation for this class was generated from the following file:
savant/gnucap/src/d_vcr.cc