gnucap: savant/gnucap/src/ap_construct.cc File Reference
savant/gnucap/src/ap_construct.cc File Reference
#include "u_opt.h"
#include "ap.h"
Functions
static std::string getlines (FILE *)
char * getcmd (const char *prompt, char *buffer, int buflen)
Variables
OMSTREAM mout
OMSTREAM mlog
Function Documentation
char* getcmd (const char * prompt, char * buffer, int buflen)
Definition at line 176 of file ap_construct.cc.
References OPT::edit, itested, mout, IO::mstdout, trim(), and untested.
Referenced by anonymous_namespace{c_sweep.cc}::buildfile(), CS::get_line(), and xopen().
{
  assert(prompt);
  assert(buffer);
  if (isatty(fileno(stdin))) {
    // stdin is keyboard
#if defined(HAVE_LIBREADLINE)
    if (OPT::edit) {
      char* line_read = readline(prompt);
      if (!line_read) {itested();
        throw Exception_End_Of_Input("EOF on stdin");
      }else{
      }
      // readline gets a new buffer every time, so copy it to where we want it
      char* end_of_line = (char*)memccpy(buffer, line_read, 0, static_cast<size_t>(buflen-1));
      if (!end_of_line) {
        buffer[buflen-1] = '\0';
      }else{
        *end_of_line = '\0';
      }
      free(line_read);
      if (*buffer) {
        add_history(buffer);
      }else{
      }
    }else
#endif
      {
        IO::mstdout << prompt;  /* prompt & flush buffer */
        if (!fgets(buffer, buflen, stdin)) {untested(); /* read line */
          throw Exception_End_Of_Input("EOF on stdin");
        }else{
        }
      }
    (IO::mstdout - mout) << '\r';       /* reset col counter */
    trim(buffer);
    (mlog + mout) << buffer << '\n';
    return buffer;
  }else{
    // stdin is file
    if (!fgets(buffer, buflen, stdin)) {itested();      /* read line */
      throw Exception_End_Of_Input("EOF on stdin");
    }else{
    }
    trim(buffer);
    (mlog + mout) << buffer << '\n';
    return buffer;
  }
}
static std::string getlines (FILE * fileptr) [static]
Definition at line 227 of file ap_construct.cc.
References BIGBUFLEN, itested, trim(), unreachable, and untested.
Referenced by CS::get_line().
{
  assert(fileptr);
  const int buffer_size = BIGBUFLEN;
  std::string s;
  bool need_to_get_more = true;  // get another line (extend)
  while (need_to_get_more) {
    char buffer[buffer_size+1];
    char* got_something = fgets(buffer, buffer_size, fileptr);
    if (!got_something) { // probably end of file
      need_to_get_more = false;
      if (s == "") {
        throw Exception_End_Of_Input("");
      }else{untested();
      }
    }else{
      trim(buffer);
      size_t count = strlen(buffer);
      if (buffer[count-1] == '\\') {itested();
        buffer[count-1] = '\0';
      }else{
        // look ahead at next line
        //int c = fgetc(fileptr);
        int c;
        while (isspace(c = fgetc(fileptr))) {
          // skip
        }
        if (c == '+') {
          need_to_get_more = true;
        }else if (c == '\n') {unreachable();
          need_to_get_more = true;
          ungetc(c,fileptr);
        }else{
          need_to_get_more = false;
          ungetc(c,fileptr);
        }
      }
      s += buffer;
      s += ' ';
    }
  }
  return s;
}
Variable Documentation
OMSTREAM mlog
Definition at line 35 of file ap_construct.cc.
OMSTREAM mout
Definition at line 34 of file ap_construct.cc.
Referenced by getcmd().