gnucap: MODEL_SEMI_CAPACITOR Class Reference
MODEL_SEMI_CAPACITOR Class Reference
Public Member Functions
MODEL_SEMI_CAPACITOR ()
Public Attributes
PARAMETER< double > _cj
PARAMETER< double > _cjsw
Private Member Functions
MODEL_SEMI_CAPACITOR (const MODEL_SEMI_CAPACITOR &p)
std::string dev_type () const
void precalc_first ()
COMMON_COMPONENT * new_common () const
CARD * clone () const
void set_param_by_index (int, std::string &, int)
bool param_is_printable (int) const
std::string param_name (int) const
std::string param_name (int, int) const
std::string param_value (int) const
int param_count () const
Static Private Attributes
static double const _default_cj = 0.
static double const _default_cjsw = 0.
Detailed Description
Definition at line 113 of file bmm_semi.cc.
Constructor & Destructor Documentation
MODEL_SEMI_CAPACITOR::MODEL_SEMI_CAPACITOR (const MODEL_SEMI_CAPACITOR & p) [explicit, private]
Definition at line 445 of file bmm_semi.cc.
  :MODEL_SEMI_BASE(p),
   _cj(p._cj),
   _cjsw(p._cjsw)
{
}
MODEL_SEMI_CAPACITOR::MODEL_SEMI_CAPACITOR () [explicit]
Definition at line 438 of file bmm_semi.cc.
Referenced by clone().
  :MODEL_SEMI_BASE(),
   _cj(_default_cj),
   _cjsw(_default_cjsw)
{
}
Member Function Documentation
CARD* MODEL_SEMI_CAPACITOR::clone () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 129 of file bmm_semi.cc.
References MODEL_SEMI_CAPACITOR().
{return new MODEL_SEMI_CAPACITOR(*this);}
std::string MODEL_SEMI_CAPACITOR::dev_type () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 125 of file bmm_semi.cc.
{return "c";}
COMMON_COMPONENT* MODEL_SEMI_CAPACITOR::new_common () const [inline, private, virtual]
Reimplemented from MODEL_CARD.
Definition at line 128 of file bmm_semi.cc.
{return new EVAL_BM_SEMI_CAPACITOR;}
int MODEL_SEMI_CAPACITOR::param_count () const [inline, private, virtual]
Reimplemented from MODEL_SEMI_BASE.
Definition at line 135 of file bmm_semi.cc.
References MODEL_SEMI_BASE::param_count().
Referenced by param_is_printable(), param_name(), param_value(), and set_param_by_index().
{return (2 + MODEL_SEMI_BASE::param_count());}
bool MODEL_SEMI_CAPACITOR::param_is_printable (int i) const [private, virtual]
Reimplemented from MODEL_SEMI_BASE.
Definition at line 461 of file bmm_semi.cc.
References param_count().
{
  switch (MODEL_SEMI_CAPACITOR::param_count() - 1 - i) {
  case 0:
  case 1: return true;
  default: return MODEL_SEMI_BASE::param_is_printable(i);
  }
}
std::string MODEL_SEMI_CAPACITOR::param_name (int i) const [private, virtual]
Reimplemented from MODEL_SEMI_BASE.
Definition at line 470 of file bmm_semi.cc.
References param_count().
Referenced by param_name().
{
  switch (MODEL_SEMI_CAPACITOR::param_count() - 1 - i) {
  case 0: return "cj";
  case 1: return "cjsw";
  default: return MODEL_SEMI_BASE::param_name(i);
  }
}
std::string MODEL_SEMI_CAPACITOR::param_name (int i, int j) const [private, virtual]
Reimplemented from MODEL_SEMI_BASE.
Definition at line 479 of file bmm_semi.cc.
References MODEL_SEMI_BASE::param_count(), and param_name().
{
  if (j == 0) {
    return param_name(i);
  }else if (i >= MODEL_SEMI_BASE::param_count()) {
    return "";
  }else{
    return MODEL_SEMI_BASE::param_name(i, j);
  }
}
std::string MODEL_SEMI_CAPACITOR::param_value (int i) const [private, virtual]
Reimplemented from MODEL_SEMI_BASE.
Definition at line 490 of file bmm_semi.cc.
References _cj, _cjsw, param_count(), and PARAMETER< T >::string().
{
  switch (MODEL_SEMI_CAPACITOR::param_count() - 1 - i) {
  case 0: return _cj.string();
  case 1: return _cjsw.string();
  default: return MODEL_SEMI_BASE::param_value(i);
  }
}
void MODEL_SEMI_CAPACITOR::precalc_first () [private, virtual]
Reimplemented from MODEL_SEMI_BASE.
Definition at line 499 of file bmm_semi.cc.
References _cj, _cjsw, _default_cj, _default_cjsw, PARAMETER< T >::e_val(), and CARD::scope().
{
  MODEL_SEMI_BASE::precalc_first();
  const CARD_LIST* s = scope();
  assert(s);
  _cj.e_val(_default_cj, s);
  _cjsw.e_val(_default_cjsw, s);
}
void MODEL_SEMI_CAPACITOR::set_param_by_index (int i, std::string & value, int offset) [private, virtual]
Reimplemented from MODEL_SEMI_BASE.
Definition at line 452 of file bmm_semi.cc.
References _cj, _cjsw, and param_count().
{
  switch (MODEL_SEMI_CAPACITOR::param_count() - 1 - i) {
  case 0: _cj = value; break;
  case 1: _cjsw = value; break;
  default: MODEL_SEMI_BASE::set_param_by_index(i, value, offset); break;
  }
}
Member Data Documentation
PARAMETER<double> MODEL_SEMI_CAPACITOR::_cj
Definition at line 115 of file bmm_semi.cc.
Referenced by param_value(), precalc_first(), EVAL_BM_SEMI_CAPACITOR::precalc_last(), and set_param_by_index().
PARAMETER<double> MODEL_SEMI_CAPACITOR::_cjsw
Definition at line 116 of file bmm_semi.cc.
Referenced by param_value(), precalc_first(), EVAL_BM_SEMI_CAPACITOR::precalc_last(), and set_param_by_index().
double const MODEL_SEMI_CAPACITOR::_default_cj = 0. [static, private]
Definition at line 118 of file bmm_semi.cc.
Referenced by precalc_first().
double const MODEL_SEMI_CAPACITOR::_default_cjsw = 0. [static, private]
Definition at line 119 of file bmm_semi.cc.
Referenced by precalc_first().
The documentation for this class was generated from the following file:
savant/gnucap/src/bmm_semi.cc