gnucap: DEV_SPICE Class Reference
DEV_SPICE Class Reference
Public Member Functions
DEV_SPICE ()
~DEV_SPICE ()
void set_dev_type (const std::string &nt)
std::string dev_type () const
std::string port_name (int i) const
Public Attributes
double _i0 [MATRIX_NODES+OFFSET]
double _i1 [MATRIX_NODES+OFFSET]
double _v1 [MATRIX_NODES+OFFSET]
double * _states [8]
double * _states_1
int _num_states
int _maxEqNum
GENinstance _spice_instance
INSTANCE _inst
char _inst_space
Protected Member Functions
char id_letter () const
bool print_type_in_spice () const
std::string value_name () const
int max_nodes () const
int min_nodes () const
int matrix_nodes () const
int net_nodes () const
int int_nodes () const
CARD * clone () const
void precalc_first ()
void expand ()
void precalc_last ()
void internal_precalc ()
void tr_iwant_matrix ()
void tr_begin ()
void tr_restore ()
void dc_advance ()
void tr_advance ()
void tr_regress ()
bool tr_needs_eval () const
bool do_tr ()
void tr_load ()
TIME_PAIR tr_review ()
void tr_accept ()
void tr_unload ()
double tr_involts () const
double tr_involts_limited () const
double tr_amps () const
double tr_probe_num (const std::string &) const
void ac_iwant_matrix ()
void ac_begin ()
void do_ac ()
void ac_load ()
COMPLEX ac_involts () const
COMPLEX ac_amps () const
XPROBE ac_probe_ext (const std::string &) const
int tail_size () const
Private Member Functions
DEV_SPICE (const DEV_SPICE &p)
void set_param_by_name (std::string Name, std::string Value)
void Set_param_by_name (std::string Name, std::string Value)
void Set_param_by_index (int, std::string &, int)
int param_count_dont_print () const
CKTcircuit * ckt () const
void init_ckt ()
void update_ckt () const
void localize_ckt () const
int * spice_nodes () const
Private Attributes
union {
GENinstance _spice_instance
INSTANCE _inst
char _inst_space
};
std::string _modelname
const MODEL_SPICE * _model
const SPICE_MODEL_DATA * _spice_model
node_t _nodes [MATRIX_NODES]
COMPLEX * _matrix [MATRIX_NODES+OFFSET]
COMPLEX _matrix_core [MATRIX_NODES+OFFSET][MATRIX_NODES+OFFSET]
Static Private Attributes
static int _count = -1
Detailed Description
Definition at line 181 of file spice-wrapper.cc.
Constructor & Destructor Documentation
DEV_SPICE::DEV_SPICE (const DEV_SPICE & p) [explicit, private]
Definition at line 742 of file spice-wrapper.cc.
References _count, OPT::_keep_time_steps, _matrix, _matrix_core, CARD::_n, _nodes, _states, assert_instance, matrix_nodes(), OFFSET, SPICE_INVALID_NODE, and spice_nodes().
  :STORAGE(p),
   _inst(p._inst),
   _modelname(p._modelname),
   _model(p._model),
   _spice_model(p._spice_model),
   _nodes(),
   _matrix(),
   _matrix_core(),
   _i0(),
   _i1(),
   _v1(),
   _states_1(NULL),
   _num_states(p._num_states),
   _maxEqNum(p._maxEqNum)
{
  assert_instance();
  {
    int* node = spice_nodes();
    for (int ii = 0; ii < matrix_nodes(); ++ii) {
      assert(node[ii] == SPICE_INVALID_NODE);
    }
  }
  _n = _nodes;
  for (int ii = 0; ii < matrix_nodes(); ++ii) {
    _n[ii] = p._n[ii];
  }
  for (int ii = 0; ii < matrix_nodes()+OFFSET; ++ii) {
    _matrix[ii] = _matrix_core[ii];
    assert(_matrix[ii]);
  }
  assert(OPT::_keep_time_steps <= 8);
  for (int ii=0; ii<8; ++ii) {
    _states[ii] = NULL;
  }
  ++_count;
  assert_instance();
}
DEV_SPICE::DEV_SPICE () [explicit]
Definition at line 697 of file spice-wrapper.cc.
References _count, _inst_space, OPT::_keep_time_steps, _matrix, _matrix_core, CARD::_n, _nodes, _states, assert_instance, COMPONENT::attach_common(), Default_Params, matrix_nodes(), CARD::n_(), OFFSET, SPICE_INVALID_NODE, and spice_nodes().
Referenced by clone().
  :STORAGE(),
   _inst(),
   _modelname(""),
   _model(NULL),
   _spice_model(NULL),
   _nodes(),
   _matrix(),
   _matrix_core(),
   _i0(),
   _i1(),
   _v1(),
   _states_1(NULL),
   _num_states(0),
   _maxEqNum(0)
{
  attach_common(&Default_Params);
  std::fill_n(&_inst_space, sizeof(INSTANCE), '\0');
  assert_instance();
  {
    int* node = spice_nodes();
    for (int ii = 0; ii < matrix_nodes(); ++ii) {
      node[ii] = SPICE_INVALID_NODE;
    }
  }
  _n = _nodes;
  for (int ii = 0; ii < matrix_nodes(); ++ii) {
    assert(!(_n[ii].n_()));
  }
  for (int ii = 0; ii < matrix_nodes()+OFFSET; ++ii) {
    _matrix[ii] = _matrix_core[ii];
    assert(_matrix[ii]);
  }
  assert(OPT::_keep_time_steps <= 8);
  for (int ii=0; ii<8; ++ii) {
    _states[ii] = NULL;
  }
  ++_count;
  assert_instance();
}
DEV_SPICE::~DEV_SPICE ()
Definition at line 785 of file spice-wrapper.cc.
References _count, OPT::_keep_time_steps, _spice_model, _states, _states_1, and assert_instance.
{
  assert_instance();
  --_count;
  if (_states[0]) {
    // regular instances
    for (int ii=0; ii<OPT::_keep_time_steps; ++ii) {
      assert(_states[ii]);
      delete [] _states[ii];
    }
    assert(_states_1);
    delete [] _states_1;
  }else{
    // prototype
    assert(OPT::_keep_time_steps <= 8);
    for (int ii=0; ii<8; ++ii) {
      assert(!_states[ii]);
    }
    assert(!_states_1);
    assert(!_spice_model);
  }
}
Member Function Documentation
COMPLEX DEV_SPICE::ac_amps () const [inline, protected, virtual]
Reimplemented from ELEMENT.
Definition at line 251 of file spice-wrapper.cc.
References NOT_VALID, and unreachable.
{unreachable();return NOT_VALID;}
void DEV_SPICE::ac_begin () [protected, virtual]
Reimplemented from CARD.
Definition at line 1460 of file spice-wrapper.cc.
References internal_precalc(), and tr_accept().
{
  STORAGE::ac_begin();
  internal_precalc();
  tr_accept();
}
COMPLEX DEV_SPICE::ac_involts () const [inline, protected, virtual]
Implements ELEMENT.
Definition at line 250 of file spice-wrapper.cc.
References NOT_VALID, and unreachable.
{unreachable();return NOT_VALID;}
void DEV_SPICE::ac_iwant_matrix () [inline, protected, virtual]
Implements ELEMENT.
Definition at line 246 of file spice-wrapper.cc.
References ELEMENT::ac_iwant_matrix_extended().
{ac_iwant_matrix_extended();}
void DEV_SPICE::ac_load () [protected, virtual]
Reimplemented from CARD.
Definition at line 1507 of file spice-wrapper.cc.
References _i0, _i1, _matrix, CARD::_n, ELEMENT::ac_load_point(), ELEMENT::ac_load_source_point(), assert_ckt_up_to_date, ckt(), info, MATRIX_NODES, matrix_nodes(), OFFSET, spice_nodes(), trace2, and trace3.
{
  if (info.DEVacLoad) {
    assert_ckt_up_to_date(ckt());
    int ihit[MATRIX_NODES+OFFSET];
    int jhit[MATRIX_NODES+OFFSET];
    std::fill_n(ihit, matrix_nodes()+OFFSET, 0);
    std::fill_n(jhit, matrix_nodes()+OFFSET, 0);
    int* node = spice_nodes();
    for (int ii = 0; ii < matrix_nodes(); ++ii) {
      int ni = node[ii];
      if (ni && !ihit[ni]) {
        ihit[ni] = 1;
        int nii = ni-OFFSET;
        trace3("", ii, ni, nii);
        ac_load_source_point(_n[ii], COMPLEX(_i0[node[ni]], _i1[node[ni]]));
        for (int jj = 0; jj < matrix_nodes(); ++jj) {
          int nj = node[jj];
          if (nj && jhit[nj] != ni) {
            jhit[nj] = ni;
            int njj = nj-OFFSET;
            trace3("", jj, nj, njj);
            trace2("", _matrix[nii][njj].real(), _matrix[nii][njj].imag());
            ac_load_point(_n[ii], _n[jj], _matrix[nii][njj]);
          }else{
            trace2("skip", jj, nj);
          }
        }
      }else{
        trace2("=========skip", ii, ni);
      }
    }
  }else{
    // there is no acLoad function
  }
}
XPROBE DEV_SPICE::ac_probe_ext (const std::string &) const [inline, protected, virtual]
Reimplemented from ELEMENT.
Definition at line 252 of file spice-wrapper.cc.
References itested, mtNONE, and NOT_VALID.
{itested(); return XPROBE(NOT_VALID, mtNONE);}
CKTcircuit* DEV_SPICE::ckt () const [inline, private]
Definition at line 278 of file spice-wrapper.cc.
Referenced by ac_load(), do_ac(), do_tr(), expand(), internal_precalc(), localize_ckt(), precalc_last(), Set_param_by_index(), tr_accept(), tr_probe_num(), tr_review(), and update_ckt().
{return MODEL_SPICE::ckt();}
CARD* DEV_SPICE::clone () const [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 219 of file spice-wrapper.cc.
References DEV_SPICE().
{return new DEV_SPICE(*this);}
void DEV_SPICE::dc_advance () [inline, protected, virtual]
Reimplemented from STORAGE.
Definition at line 229 of file spice-wrapper.cc.
References internal_precalc().
{STORAGE::dc_advance(); internal_precalc();}
std::string DEV_SPICE::dev_type () const [inline, virtual]
Reimplemented from CARD.
Definition at line 256 of file spice-wrapper.cc.
References _modelname.
{return _modelname;}
void DEV_SPICE::do_ac () [protected, virtual]
Reimplemented from CARD.
Definition at line 1467 of file spice-wrapper.cc.
References SPICE_MODEL_DATA::_gen, _i0, _i1, SIM_DATA::_jomega, _matrix, _num_states, CKT_BASE::_sim, _spice_instance, _spice_model, assert_instance, assert_model_localized, assert_model_unlocalized, ckt(), info, localize_ckt(), matrix_nodes(), OFFSET, unreachable, and untested.
{
  if (info.DEVacLoad || info.DEVpzLoad) {
    assert_instance();
    assert(_num_states >= 0);
    assert_model_unlocalized();
    _spice_model->_gen.GENinstances = &_spice_instance;
    assert_model_localized();
    localize_ckt();
    ckt()->CKTmode = MODEAC;
    ckt()->CKTomega = _sim->_jomega.imag();
    // clear for copy out
    ckt()->CKTtroubleElt = NULL;
    std::fill_n(_i0, matrix_nodes()+OFFSET, 0);
    std::fill_n(_i1, matrix_nodes()+OFFSET, 0);
    for (int ii = 0; ii < matrix_nodes()+OFFSET; ++ii) {
      for (int jj = 0; jj < matrix_nodes()+OFFSET; ++jj) {
        _matrix[ii][jj] = 0;
      }
    }
    if (info.DEVpzLoad) {
      info.DEVpzLoad(&(_spice_model->_gen), ckt(), reinterpret_cast<SPcomplex*>(&_sim->_jomega));
    }else if (info.DEVacLoad) {
      info.DEVacLoad(&(_spice_model->_gen), ckt());
    }else{unreachable();
      // nothing
    }
    assert_model_localized();
    _spice_model->_gen.GENinstances = NULL;
    assert_model_unlocalized();
  }else{untested();
    // there is no acLoad function
  }
}
bool DEV_SPICE::do_tr () [protected, virtual]
Reimplemented from CARD.
Definition at line 1175 of file spice-wrapper.cc.
References SPICE_MODEL_DATA::_gen, _i0, _i1, _matrix, CARD::_n, _num_states, CKT_BASE::_sim, _spice_instance, _spice_model, _states, _states_1, ELEMENT::_time, _v1, SIM_DATA::analysis_is_tran_dynamic(), SIM_DATA::analysis_is_tran_restore(), SIM_DATA::analysis_is_tran_static(), assert_instance, assert_model_localized, assert_model_unlocalized, ckt(), SIM_DATA::command_is_dc(), SIM_DATA::command_is_op(), conchk(), COMPONENT::converged(), info, SIM_DATA::is_first_iteration(), SIM_DATA::is_initial_step(), OPT::loadtol, localize_ckt(), matrix_nodes(), OFFSET, COMPONENT::q_load(), OPT::reltol, COMPONENT::set_converged(), SPICE_INVALID_NODE, spice_nodes(), trace3, SIM_DATA::uic_now(), unreachable, and node_t::v0().
{
  assert_instance();
  assert(info.DEVload);
  assert(_num_states >= 0);
  localize_ckt();
  assert_model_unlocalized();
  _spice_model->_gen.GENinstances = &_spice_instance;
  assert_model_localized();
  if (_sim->analysis_is_tran_dynamic()) {
    if ((_time[1] == 0) && _sim->is_first_iteration()) {
      ckt()->CKTmode = MODETRAN | MODEINITTRAN;
    }else{
      ckt()->CKTmode = MODETRAN | MODEINITFLOAT;
    }
  }else{
    if (_sim->analysis_is_tran_static()) {
      ckt()->CKTmode = MODETRANOP;
    }else if (_sim->analysis_is_tran_restore()) {
      ckt()->CKTmode = MODETRAN;
    }else if (_sim->command_is_dc()) {
      ckt()->CKTmode = MODEDCTRANCURVE;
    }else if (_sim->command_is_op()) {
      ckt()->CKTmode = MODEDCOP;
    }else{unreachable();
      ckt()->CKTmode = 0;
    }
    if (_sim->uic_now()) {
      ckt()->CKTmode |= MODEINITFIX;
      ckt()->CKTmode |= MODEUIC;
    }else if (_sim->is_initial_step()) {
      ckt()->CKTmode |= MODEINITJCT;
    }else{
      ckt()->CKTmode |= MODEINITFLOAT;
    }
  }
  { // copy in
    int* node = spice_nodes();
    assert(ckt()->CKTrhsOld == _v1);
    std::fill_n(_v1, matrix_nodes()+OFFSET, 0);
    for (int ii = 0; ii < matrix_nodes(); ++ii) {
      if (node[ii] != SPICE_INVALID_NODE) {
        _v1[node[ii]] = _n[ii].v0();
      }else{
      }
    }
  }
  { // clear for copy out
    ckt()->CKTtroubleElt = NULL;
    ckt()->CKTnoncon = 0;
    assert(ckt()->CKTrhs == _i0);
    std::fill_n(_i0, matrix_nodes()+OFFSET, 0);
    for (int ii = 0; ii < matrix_nodes()+OFFSET; ++ii) {
      for (int jj = 0; jj < matrix_nodes()+OFFSET; ++jj) {
        _matrix[ii][jj].real() = 0;
      }
    }
  }
  // do the work -- it might also do convergence checking, might not
  //-----
  info.DEVload(&(_spice_model->_gen), ckt());
  //-----
  // convergence check -- gnucap method
  set_converged(ckt()->CKTnoncon == 0);
  for (int ii = 0; ii < _num_states; ++ii) {
    set_converged(converged() && conchk(_states[0][ii], _states_1[ii]));
    trace3("", ii, _states_1[ii], _states[0][ii]);
    _states_1[ii] = _states[0][ii];
  }
  for (int ii = 0; converged() && ii < matrix_nodes()+OFFSET; ++ii) {
    set_converged(conchk(_i0[ii], _i1[ii]));
  }
  for (int ii = 0; converged() && ii < matrix_nodes()+OFFSET; ++ii) {
    for (int jj = 0; converged() && jj < matrix_nodes()+OFFSET; ++jj) {
      set_converged(conchk(_matrix[ii][jj].real(), _matrix[ii][jj].imag()));
    }
  }
  // convergence check -- Spice method
  // not sure if it is worth the effort
  if (converged() && info.DEVconvTest) {
    ckt()->CKTnoncon = 0;
    ckt()->CKTrhs = _v1;    // Spice overlaps _i0 with _v1 as CKTrhs
    info.DEVconvTest(&(_spice_model->_gen), ckt());
    set_converged(ckt()->CKTnoncon == 0);
  }else{
    // either no separate test or already failed
  }
  bool needs_load = !converged();
  for (int ii = 0; !needs_load && ii < matrix_nodes()+OFFSET; ++ii) {
    needs_load = !conchk(_i0[ii], _i1[ii], 0, OPT::reltol*OPT::loadtol);
  }
  for (int ii = 0; !needs_load && ii < matrix_nodes()+OFFSET; ++ii) {
    for (int jj = 0; !needs_load && jj < matrix_nodes()+OFFSET; ++jj) {
      needs_load = !conchk(_matrix[ii][jj].real(), _matrix[ii][jj].imag(),
                           0, OPT::reltol*OPT::loadtol);
    }
  }
  if (needs_load) {
    q_load();
  }else{
  }
  assert_model_localized();
  _spice_model->_gen.GENinstances = NULL;
  assert_model_unlocalized();
  return converged();
}
void DEV_SPICE::expand () [protected, virtual]
Reimplemented from COMPONENT.
Definition at line 871 of file spice-wrapper.cc.
References SPICE_MODEL_DATA::_gen, OPT::_keep_time_steps, _matrix, _maxEqNum, _model, _modelname, CARD::_n, _num_states, CKT_BASE::_sim, _spice_instance, MODEL_SPICE::_spice_model, _spice_model, _states, _states_1, assert_instance, assert_model_unlocalized, ckt(), COMPONENT::find_model(), info, init_ckt(), SIM_DATA::is_first_expand(), itested, CARD::long_label(), matrix_nodes(), max_nodes(), min_nodes(), CARD::n_(), net_nodes(), node_t::new_model_node(), OFFSET, node_t::set_to_ground(), CKT_BASE::short_label(), spice_nodes(), SPICE_UNCONNECTED_NODE, trace1, trace2, uDISALLOW, uFLOAT, uGROUND, UNCONNECTED_NODES, and untested.
{
  assert_instance();
  assert(info.DEVsetup);
  STORAGE::expand();
  init_ckt();
  { //-------- fix up external nodes
    int* node = spice_nodes();
    for (int ii = 0; ii < net_nodes(); ++ii) {
      node[ii] = ii+OFFSET;
    }
    if (UNCONNECTED_NODES == uGROUND) {
      for (int ii = net_nodes(); ii < max_nodes(); ++ii) {itested();
        node[ii] = ii+OFFSET;
      }
    }else if (UNCONNECTED_NODES == uFLOAT) {
      for (int ii = net_nodes(); ii < max_nodes(); ++ii) {untested();
        node[ii] = SPICE_UNCONNECTED_NODE;
      }
    }else{
      assert(UNCONNECTED_NODES == uDISALLOW);
      assert(min_nodes() == max_nodes());
      assert(net_nodes() == max_nodes());
    }
    ckt()->CKTmaxEqNum = max_nodes();
    for (int ii = max_nodes(); ii < matrix_nodes(); ++ii) {
      node[ii] = 0;
    }
  }
  { //------- attach model, set up matrix pointers
    _model = dynamic_cast<const MODEL_SPICE*>(find_model(_modelname));
    if (!_model) {
      throw Exception_Model_Type_Mismatch(long_label(), _modelname, DEVICE_TYPE);
    }else{
      SMPmatrix* matrix = reinterpret_cast<SMPmatrix*>(_matrix);
      _num_states = 0;
      _spice_instance.GENmodPtr = &(_model->_spice_model._gen);
      _spice_model = &(_model->_spice_model);
      SPICE_MODEL_DATA spice_model_copy(*_spice_model);
      spice_model_copy._gen.GENinstances = &_spice_instance;
      //-------------
      int ok = info.DEVsetup(matrix, &(spice_model_copy._gen), ckt(), &_num_states);
      // memory pointer setup, and sets _num_states
      // undesired side effects: sets values, messes up model
      //-------------
      assert(ok == OK);
      _maxEqNum = ckt()->CKTmaxEqNum;
      trace1("expand", ckt()->CKTmaxEqNum);
      assert_model_unlocalized();
    }
  }
  //-------- allocate state vectors
  if (!_states[0]) {
    for (int ii=0; ii<OPT::_keep_time_steps; ++ii) {
      assert(!_states[ii]);
      _states[ii] = new double[_num_states];
    }
    _states_1 = new double[_num_states];
  }else{
  }
  for (int ii=0; ii<OPT::_keep_time_steps; ++ii) {
    assert(_states[ii]);
    std::fill_n(_states[ii], _num_states, 0);
  }
  assert(_states_1);
  std::fill_n(_states_1, _num_states, 0);
  //std::fill_n(_i1, matrix_nodes()+OFFSET, 0);
  //std::fill_n(_v1, matrix_nodes()+OFFSET, 0);
  //-------- fix up internal nodes
  if (_sim->is_first_expand()) {
    int start_internal = 0;
    if (UNCONNECTED_NODES == uGROUND) {
      for (int ii = net_nodes(); ii < max_nodes(); ++ii) {itested();
        _n[ii].set_to_ground(this);
      }
      start_internal = max_nodes();
    }else{
      assert(UNCONNECTED_NODES == uDISALLOW || UNCONNECTED_NODES == uFLOAT);
      start_internal = net_nodes();
    }
    assert(start_internal != 0);
    int* node = spice_nodes(); // treat as array
    char fake_name[] = "a";
    for (int ii = start_internal; ii < matrix_nodes(); ++ii) {
      if (node[ii] >= start_internal+OFFSET) {
        // real internal node
        _n[ii].new_model_node('.' + long_label() + '.' + fake_name, this);
        trace1("new int", node[ii]);
        assert(_n[ii].n_());
      }else if (node[ii] >= 0+OFFSET) {
        // collapsed to an external node
        _n[ii] = _n[node[ii]-OFFSET];
        trace1("collapse", node[ii]);
        assert(_n[ii].n_());
      }else{
        // not assigned
        trace1("not used", node[ii]);
        assert(!_n[ii].n_());
      }
      ++(*fake_name);
    }
    for (int ii = 0; ii < matrix_nodes(); ++ii) {
      trace2((_n[ii].n_()) ? (_n[ii].n_()->short_label().c_str()) : ("NULL"), ii, node[ii]);
    }
    // This could be one loop, but doing it this way gives more info.
    for (int ii = 0; ii < min_nodes(); ++ii) {
      assert(_n[ii].n_());
    }
    for (int ii = min_nodes(); ii < net_nodes(); ++ii) {
      assert(_n[ii].n_());
    }
    for (int ii = net_nodes(); ii < max_nodes(); ++ii) {itested();
      //assert(_n[ii].n_());
    }
    for (int ii = max_nodes(); ii < matrix_nodes(); ++ii) {
      assert(_n[ii].n_() || !node[ii]);
    }
  }else{untested();
  }
  assert_model_unlocalized();
  assert_instance();
}
char DEV_SPICE::id_letter () const [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 211 of file spice-wrapper.cc.
References untested.
{untested();return SPICE_LETTER[0];}
void DEV_SPICE::init_ckt () [inline, private]
Definition at line 279 of file spice-wrapper.cc.
Referenced by expand(), and precalc_last().
{MODEL_SPICE::init_ckt();}
int DEV_SPICE::int_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 218 of file spice-wrapper.cc.
{return INTERNAL_NODES;}
void DEV_SPICE::internal_precalc () [protected]
Definition at line 1086 of file spice-wrapper.cc.
References SPICE_MODEL_DATA::_gen, _spice_instance, _spice_model, assert_instance, assert_model_localized, assert_model_unlocalized, ckt(), info, CARD::is_constant(), COMPONENT::set_converged(), and update_ckt().
Referenced by ac_begin(), dc_advance(), tr_begin(), and tr_restore().
{
  update_ckt();
  if (info.DEVtemperature) {
    assert_instance();
    assert_model_unlocalized();
    _spice_model->_gen.GENinstances = &_spice_instance;
    assert_model_localized();
    // ELEMENT::precalc(); .. don't call .. more analysis needed
    //-----
    int ok = info.DEVtemperature(&(_spice_model->_gen), ckt());
    assert(ok == OK);
    //-----
    set_converged();
    _spice_model->_gen.GENinstances = NULL;
    assert(!is_constant());
    assert_instance();
  }else{
  }
  assert_model_unlocalized();
}
void DEV_SPICE::localize_ckt () const [private]
Definition at line 437 of file spice-wrapper.cc.
References ELEMENT::_dt, _i0, _i1, OPT::_keep_time_steps, STORAGE::_method_a, _states, ELEMENT::_time, _v1, assert_ckt_localized, assert_ckt_up_to_date, ckt(), conchk(), mTRAP, NOT_VALID, and untested.
Referenced by do_ac(), do_tr(), tr_accept(), tr_probe_num(), and tr_review().
{
  assert_ckt_up_to_date(ckt());
  ckt()->CKTstat = reinterpret_cast<STATistics*>(const_cast<DEV_SPICE*>(this));
  assert(OPT::_keep_time_steps <= 8);
  for (int ii=0; ii<8; ++ii) {
    ckt()->CKTstates[ii] = _states[ii];
  }
  //assert(ckt()->CKTtime == _time[0]); //BUG// can fail in ac
  ckt()->CKTdelta = _dt;
  for (int ii=0; ii<OPT::_keep_time_steps-1; ++ii) {
    ckt()->CKTdeltaOld[ii] = _time[ii] - _time[ii+1];
  }
  assert(_dt == NOT_VALID || conchk(ckt()->CKTdelta, ckt()->CKTdeltaOld[0]));
  //ckt()->CKTag[0] = tr_c_to_g(1, ckt()->CKTag[0]);
  // defer fixing this -- GEAR not here
  if (_dt == 0) {untested();
    ckt()->CKTag[1] = ckt()->CKTag[0] = 0;
    ckt()->CKTorder = 1;
  }else if (_time[1] != 0 && _method_a == mTRAP) {
    ckt()->CKTag[0] = 2 / _dt;
    ckt()->CKTag[1] = 1;
    ckt()->CKTorder = 2;
  }else{
    ckt()->CKTag[0] =  1 / _dt;
    ckt()->CKTag[1] = -1 / _dt;
    ckt()->CKTorder = 1;
  }
  ckt()->CKTrhs = const_cast<double*>(_i0);
  ckt()->CKTrhsOld = const_cast<double*>(_v1);
  ckt()->CKTirhs = const_cast<double*>(_i1);
  ckt()->CKTmode = 0;
  ckt()->CKTtimePoints = const_cast<double*>(_time);
  assert_ckt_localized(ckt());
}
int DEV_SPICE::matrix_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 216 of file spice-wrapper.cc.
References MATRIX_NODES.
Referenced by ac_load(), DEV_SPICE(), do_ac(), do_tr(), expand(), precalc_last(), tr_load(), tr_needs_eval(), and tr_unload().
{return MATRIX_NODES;}
int DEV_SPICE::max_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 214 of file spice-wrapper.cc.
Referenced by expand(), and precalc_last().
{return MAX_NET_NODES;}
int DEV_SPICE::min_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 215 of file spice-wrapper.cc.
Referenced by expand(), and precalc_last().
{return MIN_NET_NODES;}
int DEV_SPICE::net_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 217 of file spice-wrapper.cc.
References CARD::_net_nodes.
Referenced by expand(), and precalc_last().
{return _net_nodes;}
int DEV_SPICE::param_count_dont_print () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 276 of file spice-wrapper.cc.
References COMPONENT::common().
{return common()->COMMON_COMPONENT::param_count();}
std::string DEV_SPICE::port_name (int i) const [inline, virtual]
Implements COMPONENT.
Definition at line 259 of file spice-wrapper.cc.
References itested.
                                  {itested();
    assert(i >= 0);
    assert(i < MAX_NET_NODES);
    return port_names[i];
  }
void DEV_SPICE::precalc_first () [protected, virtual]
Reimplemented from COMPONENT.
Definition at line 1006 of file spice-wrapper.cc.
References COMMON_SUBCKT::_params, PARAM_LIST::begin(), PARAM_LIST::end(), error(), CARD::long_label(), COMPONENT::mutable_common(), CARD::scope(), Set_param_by_name(), and to_string().
{
  STORAGE::precalc_first();
  // push down parameters into spice data
  COMMON_SUBCKT* c = dynamic_cast<COMMON_SUBCKT*>(mutable_common());
  assert(c);
  for (PARAM_LIST::iterator i = c->_params.begin(); i != c->_params.end(); ++i) {
    if (i->second.has_hard_value()) {
      try {
        Set_param_by_name(i->first, to_string(i->second.e_val(1,scope())));
      }catch (Exception_No_Match&) {
        error(bTRACE, long_label() + ": bad parameter: " + i->first + ", ignoring\n");
      }
    }else{
    }
  }
}
void DEV_SPICE::precalc_last () [protected, virtual]
Reimplemented from STORAGE.
Definition at line 1025 of file spice-wrapper.cc.
References SPICE_MODEL_DATA::_gen, _matrix, _maxEqNum, _model, _num_states, _spice_instance, MODEL_SPICE::_spice_model, _spice_model, assert_instance, assert_model_unlocalized, ckt(), notstd::copy_n(), info, init_ckt(), CARD::is_constant(), itested, MATRIX_NODES, matrix_nodes(), max_nodes(), min_nodes(), net_nodes(), OFFSET, spice_nodes(), SPICE_UNCONNECTED_NODE, trace3, uDISALLOW, uFLOAT, uGROUND, UNCONNECTED_NODES, and untested.
{
  assert(_model);
  assert_instance();
  assert(info.DEVsetup);
  STORAGE::precalc_last();
  init_ckt();
  int* node = spice_nodes(); // treat as array  //
  int  node_stash[MATRIX_NODES];                        //
  notstd::copy_n(node, matrix_nodes(), node_stash);     // save the real nodes
  { //-------- fix up external nodes, again ........
    // put the originals back, so DEVsetup can mess them up the same as last time
    int* node = spice_nodes();
    for (int ii = 0; ii < net_nodes(); ++ii) {
      node[ii] = ii+OFFSET;
    }
    if (UNCONNECTED_NODES == uGROUND) {
      for (int ii = net_nodes(); ii < max_nodes(); ++ii) {itested();
        node[ii] = ii+OFFSET;
      }
    }else if (UNCONNECTED_NODES == uFLOAT) {
      for (int ii = net_nodes(); ii < max_nodes(); ++ii) {untested();
        node[ii] = SPICE_UNCONNECTED_NODE;
      }
    }else{
      assert(UNCONNECTED_NODES == uDISALLOW);
      assert(min_nodes() == max_nodes());
      assert(net_nodes() == max_nodes());
    }
    ckt()->CKTmaxEqNum = max_nodes();
    for (int ii = max_nodes(); ii < matrix_nodes(); ++ii) {
      node[ii] = 0;
    }
  }
  {
    SMPmatrix* matrix = reinterpret_cast<SMPmatrix*>(_matrix);
    int num_states_garbage = 0;
    assert(_spice_model == &(_model->_spice_model));
    SPICE_MODEL_DATA spice_model_copy(*_spice_model);
    spice_model_copy._gen.GENinstances = &_spice_instance;
    int ok = info.DEVsetup(matrix, &(spice_model_copy._gen), ckt(), &num_states_garbage);
    assert(ok == OK);
    assert(num_states_garbage == _num_states);
    trace3("precalc", maxEqNum_stash, ckt()->CKTmaxEqNum, (maxEqNum_stash == ckt()->CKTmaxEqNum));
    assert(_maxEqNum == ckt()->CKTmaxEqNum);
    notstd::copy_n(node_stash, matrix_nodes(), node); // put back real nodes
    // hopefully, the matrix pointers are the same as last time!
  }
  assert(!is_constant());
  assert_model_unlocalized();
  assert_instance();
}
bool DEV_SPICE::print_type_in_spice () const [inline, protected, virtual]
Reimplemented from ELEMENT.
Definition at line 212 of file spice-wrapper.cc.
{return true;}
void DEV_SPICE::set_dev_type (const std::string & nt) [virtual]
Reimplemented from COMPONENT.
Definition at line 810 of file spice-wrapper.cc.
References _modelname.
{
  _modelname = new_type;
}
void DEV_SPICE::Set_param_by_index (int i, std::string & new_value, int offset) [private]
Definition at line 846 of file spice-wrapper.cc.
References _spice_instance, assert_instance, ckt(), info, COMPONENT::set_param_by_index(), and untested.
Referenced by Set_param_by_name().
{
  assert_instance();
  assert(info.DEVpublic.numInstanceParms);
  assert(info.DEVpublic.instanceParms);
  assert(info.DEVparam);
  int num_params = *(info.DEVpublic.numInstanceParms);
  if (i < num_params) {
    IFparm Parms = info.DEVpublic.instanceParms[i];
    IFvalue Value;
    IFVA v(&Value, Parms.dataType);
    v = new_value;
#ifdef JSPICE3
    int ok = info.DEVparam(ckt(), Parms.id, &Value, &_spice_instance, NULL);
#else
    int ok = info.DEVparam(Parms.id, &Value, &_spice_instance, NULL);
#endif
    assert(ok == OK);
  }else{untested();
    STORAGE::set_param_by_index(i-num_params, new_value, offset+num_params);
  }
  assert_instance();
}
void DEV_SPICE::set_param_by_name (std::string Name, std::string Value) [private, virtual]
Reimplemented from COMPONENT.
Definition at line 834 of file spice-wrapper.cc.
References COMMON_SUBCKT::_params, OPT::case_insensitive, COMPONENT::mutable_common(), CARD::scope(), Set_param_by_name(), notstd::to_lower(), and to_string().
{
  if (OPT::case_insensitive) {
    notstd::to_lower(&Name);
  }else{
  }
  COMPONENT::set_param_by_name(Name, Value);
  COMMON_SUBCKT* c = dynamic_cast<COMMON_SUBCKT*>(mutable_common());
  assert(c);
  Set_param_by_name(Name, to_string(c->_params[Name].e_val(1,scope())));
}
void DEV_SPICE::Set_param_by_name (std::string Name, std::string Value) [private]
Definition at line 815 of file spice-wrapper.cc.
References assert_instance, info, COMPONENT::mutable_common(), and Set_param_by_index().
Referenced by precalc_first(), and set_param_by_name().
{
  assert_instance();
  assert(info.DEVpublic.numInstanceParms);
  assert(info.DEVpublic.instanceParms);
  assert(info.DEVparam);
  int num_params = *(info.DEVpublic.numInstanceParms);
  for (int i = 0; i < num_params; ++i) {
    IFparm Parms = info.DEVpublic.instanceParms[i];
    if (Name == Parms.keyword) {
      Set_param_by_index(i, new_value, 0);
      return;
    }else{
    }
  }
  mutable_common()->COMMON_COMPONENT::Set_param_by_name(Name, new_value);
}
int* DEV_SPICE::spice_nodes () const [inline, private]
Definition at line 282 of file spice-wrapper.cc.
References _spice_instance.
Referenced by ac_load(), DEV_SPICE(), do_tr(), expand(), precalc_last(), tr_load(), and tr_needs_eval().
{return &(_spice_instance.GENnode1);}
int DEV_SPICE::tail_size () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 253 of file spice-wrapper.cc.
References TAIL_SIZE.
{return TAIL_SIZE;}
void DEV_SPICE::tr_accept () [protected, virtual]
Reimplemented from COMPONENT.
Definition at line 1376 of file spice-wrapper.cc.
References SPICE_MODEL_DATA::_gen, CKT_BASE::_sim, _spice_instance, _spice_model, _v1, SIM_DATA::analysis_is_ac(), SIM_DATA::analysis_is_dcop(), assert_model_localized, assert_model_unlocalized, ckt(), info, itested, and localize_ckt().
Referenced by ac_begin().
{
  assert_model_unlocalized();
  _spice_model->_gen.GENinstances = &_spice_instance;
  assert_model_localized();
  //STORAGE::tr_accept(); // doesn't do anything
  if (_sim->analysis_is_dcop() || _sim->analysis_is_ac()) {
    localize_ckt();
    // don't copy in
    assert(ckt()->CKTrhsOld == _v1);
    // _v1 already has correct values
    // _n[ii].v0() is not correct -- may have been cleared
    ckt()->CKTmode = MODEINITSMSIG;
    info.DEVload(&(_spice_model->_gen), ckt());
  }else{itested();
  }
  assert_model_localized();
  _spice_model->_gen.GENinstances = NULL;
  assert_model_unlocalized();
}
void DEV_SPICE::tr_advance () [protected, virtual]
Reimplemented from STORAGE.
Definition at line 1112 of file spice-wrapper.cc.
References OPT::_keep_time_steps, _num_states, _states, notstd::copy_n(), and update_ckt().
{
  STORAGE::tr_advance();
  update_ckt();
  double* t = _states[OPT::_keep_time_steps-1];
  for (int ii = OPT::_keep_time_steps-1;  ii > 0;  --ii) {
    _states[ii] = _states[ii-1];
  }
  _states[0] = t;
  notstd::copy_n(_states[1], _num_states, _states[0]);
}
double DEV_SPICE::tr_amps () const [inline, protected, virtual]
Reimplemented from ELEMENT.
Definition at line 243 of file spice-wrapper.cc.
References itested, and NOT_VALID.
{itested();return NOT_VALID;}
void DEV_SPICE::tr_begin () [inline, protected, virtual]
Reimplemented from STORAGE.
Definition at line 227 of file spice-wrapper.cc.
References internal_precalc().
{STORAGE::tr_begin();   internal_precalc();}
double DEV_SPICE::tr_involts () const [inline, protected, virtual]
Implements ELEMENT.
Definition at line 239 of file spice-wrapper.cc.
References NOT_VALID, and unreachable.
{unreachable();return NOT_VALID;}
double DEV_SPICE::tr_involts_limited () const [inline, protected, virtual]
Implements ELEMENT.
Definition at line 241 of file spice-wrapper.cc.
References NOT_VALID, and unreachable.
{unreachable();return NOT_VALID;}
void DEV_SPICE::tr_iwant_matrix () [inline, protected, virtual]
Implements ELEMENT.
Definition at line 226 of file spice-wrapper.cc.
References ELEMENT::tr_iwant_matrix_extended().
{tr_iwant_matrix_extended();}
void DEV_SPICE::tr_load () [protected, virtual]
Reimplemented from CARD.
Definition at line 1293 of file spice-wrapper.cc.
References _i0, _i1, ELEMENT::_loaditer, _matrix, CARD::_n, CKT_BASE::_sim, error(), SIM_DATA::iteration_tag(), CARD::long_label(), MATRIX_NODES, matrix_nodes(), OFFSET, spice_nodes(), ELEMENT::tr_load_point(), ELEMENT::tr_load_source_point(), trace2, trace4, and untested.
Referenced by tr_unload().
{
#ifndef NDEBUG
  if (_loaditer == _sim->iteration_tag()) {untested();
    error(bDANGER, long_label() + " internal error: double load\n");
  }
  _loaditer = _sim->iteration_tag();
#endif
  int ihit[MATRIX_NODES+OFFSET];
  int jhit[MATRIX_NODES+OFFSET];
  std::fill_n(ihit, matrix_nodes()+OFFSET, 0);
  std::fill_n(jhit, matrix_nodes()+OFFSET, 0);
  int* node = spice_nodes();
  for (int ii = 0; ii < matrix_nodes(); ++ii) {
    int ni = node[ii];
    if (ni && !ihit[ni]) {
      ihit[ni] = 1;
      int nii = ni-OFFSET;
      trace4("", ii, ni, _i0[ni], _i1[ni]);
      tr_load_source_point(_n[ii], &(_i0[ni]), &(_i1[ni]));
      for (int jj = 0; jj < matrix_nodes(); ++jj) {
        int nj = node[jj];
        if (nj && jhit[nj] != ni) {
          jhit[nj] = ni;
          int njj = nj-OFFSET;
          trace2("", jj, nj);
          trace2("", _matrix[nii][njj].real(), _matrix[nii][njj].imag());
          tr_load_point(_n[ii], _n[jj], &(_matrix[nii][njj].real()), &(_matrix[nii][njj].imag()));
        }else{
          trace2("skip", jj, nj);
        }
      }
    }else{
      trace2("=========skip", ii, ni);
    }
  }
}
bool DEV_SPICE::tr_needs_eval () const [protected, virtual]
Reimplemented from STORAGE.
Definition at line 1131 of file spice-wrapper.cc.
References CARD::_n, CKT_BASE::_sim, ELEMENT::_time, _v1, OPT::bypasstol, conchk(), COMPONENT::converged(), SIM_DATA::is_advance_iteration(), COMPONENT::is_q_for_eval(), matrix_nodes(), OPT::reltol, SPICE_INVALID_NODE, spice_nodes(), and node_t::v0().
{
  if (is_q_for_eval()) {
    return false;
  }else if (!converged()) {
    return true;
  }else if (_sim->is_advance_iteration()) {
    return true;
  }else if (_time[1] == 0) {
    //BUG// needed for ngspice jfet, but not for spice3f5 jfet
    return true;
  }else{
    int* node = spice_nodes();
    // check the node voltages, reference to ground
    for (int ii=0; ii<matrix_nodes(); ++ii) {
      if ((node[ii] != SPICE_INVALID_NODE)
          && !conchk(_v1[node[ii]], _n[ii].v0(), 0, OPT::reltol*OPT::bypasstol)) {
        return true;
      }else{
      }
    }
    // check the node voltages, reference to each other
    for (int ii=0; ii<matrix_nodes(); ++ii) {
      for (int jj=0; jj<ii; ++jj) {
        if ((node[ii] != SPICE_INVALID_NODE) && (node[jj] != SPICE_INVALID_NODE)
            && !conchk((_v1[node[ii]] - _v1[node[jj]]),
                       (_n[ii].v0() - _n[jj].v0()),
                       0, OPT::reltol*OPT::bypasstol)) {
          return true;
        }else{
        }
      }
    }
    return false;
  }
}
double DEV_SPICE::tr_probe_num (const std::string & x) const [protected, virtual]
Reimplemented from STORAGE.
Definition at line 1401 of file spice-wrapper.cc.
References _num_states, _spice_instance, _states, assert_ckt_up_to_date, assert_instance, ckt(), errMsg, errRtn, incomplete, info, localize_ckt(), min(), Umatch(), and untested.
{
  localize_ckt();
  assert_ckt_up_to_date(ckt());
  assert_instance();
  // all of the "states" in state array
  int num_probe_states = std::min(_num_states, int(sizeof(state_names)/sizeof(std::string)));
  for (int ii=0; ii<num_probe_states && state_names[ii]!=""; ++ii) {
    if (Umatch(x, state_names[ii] + ' ')) {
      return _states[0][ii];
    }else{
    }
  }
  if (info.DEVask) {
    // data that Spice has, through "ask"
    assert(info.DEVpublic.numInstanceParms);
    assert(info.DEVpublic.instanceParms);
    for (int ii=0; ii<(*(info.DEVpublic.numInstanceParms)); ++ii) {
      IFparm Parms = info.DEVpublic.instanceParms[ii];
      int datatype = Parms.dataType;
      if (datatype & IF_ASK && Umatch(x, std::string(Parms.keyword) + ' ')) {
        IFvalue v;
        int ok = info.DEVask(ckt(), &_spice_instance, Parms.id, &v, NULL);
        if (ok == OK) {
          switch (datatype & 0xff) {
          case IF_FLAG:
          case IF_INTEGER:
            return v.iValue;
          case IF_REAL:
            return v.rValue;
          case IF_COMPLEX:
          case IF_STRING:
          default:
            // make believe it is not a match
            incomplete();
            break; // break switch, continue loop
          }
        }else{untested();
          // match, but not useful here.
          assert(errMsg);
          free(errMsg);
          errMsg = NULL;
          assert(errRtn);
          errRtn = NULL;
          // maybe there is more than one match, so continue loop
        }
      }else{
        // really not a match, keep looking
      }
    }
  }else{untested();
    // no DEVask ..  can't do anything.
  }
  return STORAGE::tr_probe_num(x);
}
void DEV_SPICE::tr_regress () [protected, virtual]
Reimplemented from ELEMENT.
Definition at line 1125 of file spice-wrapper.cc.
References update_ckt().
{
  ELEMENT::tr_regress();
  update_ckt();
}
void DEV_SPICE::tr_restore () [inline, protected, virtual]
Reimplemented from STORAGE.
Definition at line 228 of file spice-wrapper.cc.
References internal_precalc().
{STORAGE::tr_restore(); internal_precalc();}
TIME_PAIR DEV_SPICE::tr_review () [protected, virtual]
Reimplemented from STORAGE.
Definition at line 1346 of file spice-wrapper.cc.
References TIME_PAIR::_error_estimate, TIME_PAIR::_event, SPICE_MODEL_DATA::_gen, _spice_instance, _spice_model, COMPONENT::_time_by, assert_instance, assert_model_localized, assert_model_unlocalized, ckt(), info, localize_ckt(), NEVER, and ELEMENT::tr_review_check_and_convert().
{
  // not calling STORAGE::tr_review();
  if (info.DEVtrunc) {
    localize_ckt();
    assert_instance();
    //q_accept();
    assert_model_unlocalized();
    _spice_model->_gen.GENinstances = &_spice_instance;
    assert_model_localized();
    ckt()->CKTtroubleElt = NULL;
    double timestep = NEVER;
    //-----
    info.DEVtrunc(&(_spice_model->_gen), ckt(), &timestep);
    //-----
    _time_by._error_estimate = tr_review_check_and_convert(timestep);
    _time_by._event = NEVER;
    _spice_model->_gen.GENinstances = NULL;
    assert_model_unlocalized();
    return _time_by;
  }else{
    return TIME_PAIR(NEVER,NEVER);
  }
}
void DEV_SPICE::tr_unload () [protected, virtual]
Reimplemented from CARD.
Definition at line 1334 of file spice-wrapper.cc.
References _matrix, CKT_BASE::_sim, incomplete, SIM_DATA::mark_inc_mode_bad(), matrix_nodes(), tr_load(), and untested.
{untested();incomplete();
  for (int ii = 0; ii < matrix_nodes(); ++ii) {untested();
    for (int jj = 0; jj < matrix_nodes(); ++jj) {untested();
      _matrix[ii][jj].real() = 0;
    }
  }
  _sim->mark_inc_mode_bad();
  tr_load();
}
void DEV_SPICE::update_ckt () const [private]
Definition at line 400 of file spice-wrapper.cc.
References SIM_DATA::_jomega, CKT_BASE::_sim, SIM_DATA::_temp_c, SIM_DATA::_time0, assert_ckt_initialized, assert_ckt_up_to_date, ckt(), OPT::gmin, and NOT_VALID.
Referenced by internal_precalc(), tr_advance(), and tr_regress().
{
  assert_ckt_initialized(ckt());
  ckt()->CKTgmin = OPT::gmin;
  ckt()->CKTstat = NULL; // mark as not localized
  ckt()->CKTtime = _sim->_time0;
  ckt()->CKTdelta = NOT_VALID; // localized
  ckt()->CKTtemp = _sim->_temp_c + CONSTCtoK;
  ckt()->CKTmode = 0;
  ckt()->CKTomega = _sim->_jomega.imag();
  assert_ckt_up_to_date(ckt());
}
std::string DEV_SPICE::value_name () const [inline, protected, virtual]
Implements CARD.
Definition at line 213 of file spice-wrapper.cc.
References VALUE_NAME.
{return VALUE_NAME;}
Member Data Documentation
union { ... } [private]
int DEV_SPICE::_count = -1 [static, private]
Definition at line 183 of file spice-wrapper.cc.
Referenced by DEV_SPICE(), and ~DEV_SPICE().
double DEV_SPICE::_i0[MATRIX_NODES+OFFSET]
Definition at line 198 of file spice-wrapper.cc.
Referenced by ac_load(), do_ac(), do_tr(), localize_ckt(), and tr_load().
double DEV_SPICE::_i1[MATRIX_NODES+OFFSET]
Definition at line 199 of file spice-wrapper.cc.
Referenced by ac_load(), do_ac(), do_tr(), localize_ckt(), and tr_load().
INSTANCE DEV_SPICE::_inst
Definition at line 188 of file spice-wrapper.cc.
char DEV_SPICE::_inst_space
Definition at line 189 of file spice-wrapper.cc.
Referenced by DEV_SPICE().
COMPLEX* DEV_SPICE::_matrix[MATRIX_NODES+OFFSET] [private]
Definition at line 195 of file spice-wrapper.cc.
Referenced by ac_load(), DEV_SPICE(), do_ac(), do_tr(), expand(), precalc_last(), tr_load(), and tr_unload().
COMPLEX DEV_SPICE::_matrix_core[MATRIX_NODES+OFFSET][MATRIX_NODES+OFFSET] [private]
Definition at line 196 of file spice-wrapper.cc.
Referenced by DEV_SPICE().
int DEV_SPICE::_maxEqNum
Definition at line 204 of file spice-wrapper.cc.
Referenced by expand(), and precalc_last().
const MODEL_SPICE* DEV_SPICE::_model [private]
Definition at line 192 of file spice-wrapper.cc.
Referenced by expand(), and precalc_last().
std::string DEV_SPICE::_modelname [private]
Definition at line 191 of file spice-wrapper.cc.
Referenced by dev_type(), expand(), and set_dev_type().
node_t DEV_SPICE::_nodes[MATRIX_NODES] [private]
Reimplemented from ELEMENT.
Definition at line 194 of file spice-wrapper.cc.
Referenced by DEV_SPICE().
int DEV_SPICE::_num_states
Definition at line 203 of file spice-wrapper.cc.
Referenced by do_ac(), do_tr(), expand(), precalc_last(), tr_advance(), and tr_probe_num().
GENinstance DEV_SPICE::_spice_instance [mutable]
Definition at line 187 of file spice-wrapper.cc.
Referenced by do_ac(), do_tr(), expand(), internal_precalc(), precalc_last(), Set_param_by_index(), spice_nodes(), tr_accept(), tr_probe_num(), and tr_review().
const SPICE_MODEL_DATA* DEV_SPICE::_spice_model [private]
Definition at line 193 of file spice-wrapper.cc.
Referenced by do_ac(), do_tr(), expand(), internal_precalc(), precalc_last(), tr_accept(), tr_review(), and ~DEV_SPICE().
double* DEV_SPICE::_states[8]
Definition at line 201 of file spice-wrapper.cc.
Referenced by DEV_SPICE(), do_tr(), expand(), localize_ckt(), tr_advance(), tr_probe_num(), and ~DEV_SPICE().
double* DEV_SPICE::_states_1
Definition at line 202 of file spice-wrapper.cc.
Referenced by do_tr(), expand(), and ~DEV_SPICE().
double DEV_SPICE::_v1[MATRIX_NODES+OFFSET]
Definition at line 200 of file spice-wrapper.cc.
Referenced by do_tr(), localize_ckt(), tr_accept(), and tr_needs_eval().
The documentation for this class was generated from the following file:
savant/gnucap/src/spice-wrapper.cc