gnucap: anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH Class Reference
anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH Class Reference
Public Member Functions
EVAL_BM_TANH (int c=0)
~EVAL_BM_TANH ()
Private Member Functions
EVAL_BM_TANH (const EVAL_BM_TANH &p)
bool operator== (const COMMON_COMPONENT &) const
COMMON_COMPONENT * clone () const
void print_common_obsolete_callback (OMSTREAM &, LANGUAGE *) const
void precalc_first (const CARD_LIST *)
void tr_eval (ELEMENT *) const
std::string name () const
bool ac_too () const
bool parse_numlist (CS &)
bool parse_params_obsolete_callback (CS &)
Private Attributes
PARAMETER< double > _gain
PARAMETER< double > _limit
Detailed Description
Definition at line 34 of file bm_tanh.cc.
Constructor & Destructor Documentation
anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::EVAL_BM_TANH (const EVAL_BM_TANH & p) [explicit, private]
Definition at line 63 of file bm_tanh.cc.
  :EVAL_BM_ACTION_BASE(p),
   _gain(p._gain),
   _limit(p._limit)
{
}
anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::EVAL_BM_TANH (int c = 0) [explicit]
Definition at line 56 of file bm_tanh.cc.
  :EVAL_BM_ACTION_BASE(c),
   _gain(NOT_INPUT),
   _limit(NOT_INPUT)
{
}
anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::~EVAL_BM_TANH () [inline]
Definition at line 41 of file bm_tanh.cc.
{}
Member Function Documentation
bool anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::ac_too () const [inline, private, virtual]
Implements EVAL_BM_ACTION_BASE.
Definition at line 50 of file bm_tanh.cc.
References untested.
{untested();return false;}
COMMON_COMPONENT* anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::clone () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 44 of file bm_tanh.cc.
{return new EVAL_BM_TANH(*this);}
std::string anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::name () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 49 of file bm_tanh.cc.
Referenced by print_common_obsolete_callback().
{return "tanh";}
bool anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::operator== (const COMMON_COMPONENT & x) const [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 70 of file bm_tanh.cc.
References _gain, _limit, anonymous_namespace{c_genrat.cc}::p, and untested.
{
  const EVAL_BM_TANH* p = dynamic_cast<const EVAL_BM_TANH*>(&x);
  bool rv = p
    && _gain == p->_gain
    && _limit == p->_limit
    && EVAL_BM_ACTION_BASE::operator==(x);
  if (rv) {
    untested();
  }
  return rv;
}
bool anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::parse_numlist (CS & cmd) [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 120 of file bm_tanh.cc.
References _gain, _limit, CS::cursor(), CS::gotit(), and NOT_VALID.
{
  unsigned here = cmd.cursor();
  PARAMETER<double> gain(NOT_VALID);
  PARAMETER<double> limit(NOT_VALID);
  cmd >> gain >> limit;
  if (cmd.gotit(here)) {
    _gain  = gain;
    _limit = limit;
    return true;
  }else{
    return false;
  }
}
bool anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::parse_params_obsolete_callback (CS & cmd) [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 135 of file bm_tanh.cc.
References _gain, _limit, Get(), and ONE_OF.
{
  return ONE_OF
    || Get(cmd, "gain",  &_gain)
    || Get(cmd, "limit", &_limit)
    || EVAL_BM_ACTION_BASE::parse_params_obsolete_callback(cmd)
    ;
}
void anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::precalc_first (const CARD_LIST * Scope) [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 92 of file bm_tanh.cc.
References _gain, _limit, and PARAMETER< T >::e_val().
{
  assert(Scope);
  EVAL_BM_ACTION_BASE::precalc_first(Scope);
  _gain.e_val(_default_gain, Scope);
  _limit.e_val(_default_limit, Scope);
}
void anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::print_common_obsolete_callback (OMSTREAM & o, LANGUAGE * lang) const [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 83 of file bm_tanh.cc.
References _gain, _limit, name(), and print_pair().
{
  assert(lang);
  o << name();
  print_pair(o, lang, "gain", _gain);
  print_pair(o, lang, "limit", _limit);
  EVAL_BM_ACTION_BASE::print_common_obsolete_callback(o, lang);
}
void anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::tr_eval (ELEMENT * d) const [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 100 of file bm_tanh.cc.
References _gain, _limit, ELEMENT::_y, COMPONENT::f_is_value(), EVAL_BM_ACTION_BASE::ioffset(), LOGBIGBIG, EVAL_BM_ACTION_BASE::tr_final_adjust(), and FPOLY1::x.
{
  double x = ioffset(d->_y[0].x);
  double aa = x * _gain/_limit;
  double f1, f0;
  if (aa > LOGBIGBIG) {
    f1 = 0;
    f0 = _limit;
  }else if (aa < -LOGBIGBIG) {
    f1 = 0;
    f0 = -_limit;
  }else{
    double cosine = cosh(aa);
    f1 = _gain / (cosine*cosine);
    f0 = _limit * tanh(aa);
  }
  d->_y[0] = FPOLY1(x, f0, f1);
  tr_final_adjust(&(d->_y[0]), d->f_is_value());
}
Member Data Documentation
PARAMETER<double> anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::_gain [private]
Definition at line 36 of file bm_tanh.cc.
Referenced by operator==(), parse_numlist(), parse_params_obsolete_callback(), precalc_first(), print_common_obsolete_callback(), and tr_eval().
PARAMETER<double> anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::_limit [private]
Definition at line 37 of file bm_tanh.cc.
Referenced by operator==(), parse_numlist(), parse_params_obsolete_callback(), precalc_first(), print_common_obsolete_callback(), and tr_eval().
The documentation for this class was generated from the following file:
savant/gnucap/src/bm_tanh.cc