gnucap: notstd Namespace Reference
notstd Namespace Reference
Functions
template<class InputIter , class Size , class OutputIter >
void copy_n (InputIter first, Size count, OutputIter result)
template<class InputIterator , class T >
InputIterator find_ptr (InputIterator first, InputIterator last, const T &value)
void to_lower (std::string *s)
void to_upper (std::string *s)
Function Documentation
template<class InputIter , class Size , class OutputIter > void notstd::copy_n (InputIter first, Size count, OutputIter result)
Definition at line 33 of file l_stlextra.h.
Referenced by SIM::advance_time(), ELEMENT::ELEMENT(), BSMATRIX< T >::fbsub(), DEV_SPICE::precalc_last(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::set_parameters(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::set_parameters(), COMPONENT::set_parameters(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::SWITCH_BASE(), and DEV_SPICE::tr_advance().
{
  for ( ; count > 0; --count) {
    *result++ = *first++;
  }
}
template<class InputIterator , class T > InputIterator notstd::find_ptr (InputIterator first, InputIterator last, const T & value)
Definition at line 43 of file l_stlextra.h.
Referenced by CARD_LIST::find_again().
{
  while (first != last && **first != value) {
    ++first;
  }
  return first;
}
void notstd::to_lower (std::string * s) [inline]
Definition at line 51 of file l_stlextra.h.
Referenced by PARAM_LIST::deep_lookup(), NODE_MAP::new_node(), NODE_MAP::operator[](), DISPATCHER< T >::operator[](), PARAM_LIST::parse(), PARAM_LIST::set(), MODEL_SPICE::set_dev_type(), MODEL_SPICE::set_param_by_name(), and DEV_SPICE::set_param_by_name().
{
  assert(s);
  for (std::string::iterator i = s->begin(); i != s->end(); ++i) {
    *i = static_cast<char>(tolower(*i));
  }
}
void notstd::to_upper (std::string * s) [inline]
Definition at line 59 of file l_stlextra.h.
{
  assert(s);
  for (std::string::iterator i = s->begin(); i != s->end(); ++i) {
    *i = static_cast<char>(toupper(*i));
  }
}