gnucap: anonymous_namespace{bm_cond.cc}::EVAL_BM_COND Class Reference
anonymous_namespace{bm_cond.cc}::EVAL_BM_COND Class Reference
Public Member Functions
EVAL_BM_COND (int c=0)
~EVAL_BM_COND ()
Private Member Functions
EVAL_BM_COND (const EVAL_BM_COND &p)
bool operator== (const COMMON_COMPONENT &) const
COMMON_COMPONENT * clone () const
void parse_common_obsolete_callback (CS &)
void print_common_obsolete_callback (OMSTREAM &, LANGUAGE *) const
void precalc_first (const CARD_LIST *)
void expand (const COMPONENT *)
COMMON_COMPONENT * deflate ()
void precalc_last (const CARD_LIST *)
void tr_eval (ELEMENT *d) const
void ac_eval (ELEMENT *d) const
TIME_PAIR tr_review (COMPONENT *d)
void tr_accept (COMPONENT *d)
std::string name () const
Private Attributes
COMMON_COMPONENT * _func [sCOUNT]
bool _set [sCOUNT]
Detailed Description
Definition at line 34 of file bm_cond.cc.
Constructor & Destructor Documentation
anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::EVAL_BM_COND (const EVAL_BM_COND & p) [explicit, private]
Definition at line 72 of file bm_cond.cc.
References _func, _set, COMMON_COMPONENT::attach_common(), and sCOUNT.
  :EVAL_BM_BASE(p)
{
  for (int i=0; i<sCOUNT; ++i) {
    _func[i] = 0;
    attach_common(p._func[i], &(_func[i]));
    _set[i]  = p._set[i];
  }
}
anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::EVAL_BM_COND (int c = 0) [explicit]
Definition at line 65 of file bm_cond.cc.
References _func, _set, and sCOUNT.
  :EVAL_BM_BASE(c)
{
  std::fill_n(_func, sCOUNT, static_cast<COMMON_COMPONENT*>(0));
  std::fill_n(_set, sCOUNT, false);
}
anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::~EVAL_BM_COND ()
Definition at line 82 of file bm_cond.cc.
References _func, COMMON_COMPONENT::detach_common(), and sCOUNT.
{
  for (int i=0; i<sCOUNT; ++i) {
    detach_common(&(_func[i]));
  }
}
Member Function Documentation
void anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::ac_eval (ELEMENT * d) const [inline, private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 55 of file bm_cond.cc.
References s_AC.
        {assert(_func[s_AC]);      _func[s_AC]->ac_eval(d);}
COMMON_COMPONENT* anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::clone () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 44 of file bm_cond.cc.
{return new EVAL_BM_COND(*this);}
COMMON_COMPONENT * anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::deflate () [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 216 of file bm_cond.cc.
References _func, COMMON_COMPONENT::deflate(), s_NONE, and sCOUNT.
{
  for (int i = 1; i < sCOUNT; ++i) {
    if (_func[i] != _func[s_NONE]) {
      // they are not all the same, don't deflate
      return this;
    }
  }
  // they are all the same.  Take one of them.
  return _func[s_NONE]->deflate();
}
void anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::expand (const COMPONENT * d) [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 198 of file bm_cond.cc.
References _func, COMMON_COMPONENT::attach_common(), COMMON_COMPONENT::clone(), COMMON_COMPONENT::deflate(), COMMON_COMPONENT::expand(), sCOUNT, and untested.
{
  EVAL_BM_BASE::expand(d);
  for (int i = 1; i < sCOUNT; ++i) {
    //BUG// makes unnecessary duplicates
    assert(_func[i]);
    COMMON_COMPONENT* new_common = _func[i]->clone();
    new_common->expand(d);
    COMMON_COMPONENT* deflated_common = new_common->deflate();
    if (deflated_common != _func[i]) {
      attach_common(deflated_common, &(_func[i]));
    }else{untested();
    }
  }
}
std::string anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::name () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 61 of file bm_cond.cc.
References itested.
{itested(); return "????";}
bool anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::operator== (const COMMON_COMPONENT & x) const [private, virtual]
Reimplemented from EVAL_BM_BASE.
Definition at line 89 of file bm_cond.cc.
References incomplete, anonymous_namespace{c_genrat.cc}::p, and untested.
{
  const EVAL_BM_COND* p = dynamic_cast<const EVAL_BM_COND*>(&x);
  bool rv = p
    && EVAL_BM_BASE::operator==(x);
  if (rv) {untested();
    incomplete();
  }
  return rv;
}
void anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::parse_common_obsolete_callback (CS & cmd) [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 100 of file bm_cond.cc.
References _func, _set, EVAL_BM_ACTION_BASE::ac_too(), COMMON_COMPONENT::attach_common(), anonymous_namespace{bm_cond.cc}::bm_dispatcher, CS::cursor(), anonymous_namespace{bm_cond.cc}::func_zero, CS::is_end(), itested, CS::match1(), CS::more(), ONE_OF, COMMON_COMPONENT::parse_common_obsolete_callback(), EVAL_BM_ACTION_BASE::parse_func_type(), prechecked_cast, CS::reset(), s_AC, s_DC, s_FOURIER, s_NONE, s_OP, s_TRAN, sCOUNT, Set(), CS::skipbl(), CS::stuck(), CS::umatch(), untested, and CS::warn().
{
  unsigned here = cmd.cursor();
  cmd.reset().skipbl();
  bool is_source = cmd.match1("viVI")
    || (cmd.match1('.') && (cmd.umatch(".vso{urce} ") || cmd.umatch(".iso{urce} ")));
  cmd.reset(here);
  do {
    SIM_MODE mode(s_NONE);
    ONE_OF
      || Set(cmd, "ac",         &mode, s_AC)
      || Set(cmd, "op",         &mode, s_OP)
      || Set(cmd, "dc",         &mode, s_DC)
      || Set(cmd, "tran{sient}",&mode, s_TRAN)
      || Set(cmd, "four{ier}",  &mode, s_FOURIER)
      || Set(cmd, "else",       &mode, s_NONE)
      || Set(cmd, "all",        &mode, s_NONE)
      || (mode = s_NONE)
      ;
    if (_set[mode]) {itested();
      cmd.warn(bWARNING, (mode != s_NONE) ? "duplicate mode" : "what's this?");
    }
    COMMON_COMPONENT* c = EVAL_BM_ACTION_BASE::parse_func_type(cmd);
    if (!c) {
      // no match for func_type
      if (cmd.more()) {
        if (!cmd.match1("\"'{")) {
          // quoted means it is a parameter or expression
          // otherwise assume it's a "model", for now
          // it might not be, but we fix later
          c = bm_dispatcher.clone("eval_bm_model");
        }else{
        }
        if (!c) {
          c = bm_dispatcher.clone("eval_bm_value");
        }else{
        }
      }else{
        // no more
      }
    }else{
      // got bm function
    }
    if (is_source               // Spice compatibility
        && mode == s_NONE       // for sources, no condition implies "DC"
        && !_set[s_DC]
        && dynamic_cast<EVAL_BM_VALUE*>(c)) {
      mode = s_DC;
    }else{
    }
    if (c) {
      c->parse_common_obsolete_callback(cmd); //BUG//callback
    }else{
      c = &func_zero;
    }
    assert(c);
    attach_common(c, &(_func[mode]));
    assert(_func[mode]);
    _set[mode] = true;
    if (cmd.is_end()) {
      break;
    }
  } while (cmd.more() && !cmd.stuck(&here));
  // apply rules to determine states not explicitly specified
  if (!_func[s_OP] && _set[s_DC])    {attach_common(_func[s_DC],  &(_func[s_OP]));}
  if (!_func[s_OP] && _set[s_NONE])  {attach_common(_func[s_NONE],&(_func[s_OP]));}
  if (!_func[s_OP] && _set[s_TRAN])  {untested();attach_common(_func[s_TRAN],&(_func[s_OP]));}
  if (!_func[s_OP])                  {attach_common(&func_zero,  &(_func[s_OP]));}
  if (!_func[s_DC] && _set[s_NONE])  {attach_common(_func[s_NONE],&(_func[s_DC]));}
  if (!_func[s_DC] && _set[s_OP])    {untested();attach_common(_func[s_OP],  &(_func[s_DC]));}
  if (!_func[s_DC] && _set[s_TRAN])  {untested();attach_common(_func[s_TRAN],&(_func[s_DC]));}
  if (!_func[s_DC])                  {attach_common(&func_zero,  &(_func[s_DC]));}
  if (!_func[s_TRAN]&&_set[s_NONE])  {attach_common(_func[s_NONE],&(_func[s_TRAN]));}
  if (!_func[s_TRAN] && _set[s_DC])  {attach_common(_func[s_DC],&(_func[s_TRAN]));}
  if (!_func[s_TRAN] && _set[s_OP])  {untested();attach_common(_func[s_OP],&(_func[s_TRAN]));}
  if (!_func[s_TRAN])                {attach_common(&func_zero,&(_func[s_TRAN]));}
  if (!_func[s_FOURIER])             {attach_common(_func[s_TRAN],&(_func[s_FOURIER]));}
  const EVAL_BM_ACTION_BASE* c = prechecked_cast<const EVAL_BM_ACTION_BASE*>(_func[s_NONE]);
  if (!_func[s_AC] && _set[s_NONE] && (!is_source || c->ac_too()))
                                   {attach_common(_func[s_NONE],&(_func[s_AC]));}
  if (!_func[s_AC])                {attach_common(&func_zero,  &(_func[s_AC]));}
  for (int i = 1; i < sCOUNT; ++i) {
    assert(_func[i]);
  }
}
void anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::precalc_first (const CARD_LIST * Scope) [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 228 of file bm_cond.cc.
References _func, COMMON_COMPONENT::precalc_first(), and sCOUNT.
{
  //BUG// calls the individual precalc more than once
  // wastes time and makes multiple "has no value" warnings
  // when there should be only one
  COMMON_COMPONENT* did_this = NULL;
  for (int i = 1; i < sCOUNT; ++i) {
    assert(_func[i]);
    if (_func[i] != did_this) {
      _func[i]->precalc_first(Scope);
      did_this = _func[i];
    }else{
      // already did
    }
  }
}
void anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::precalc_last (const CARD_LIST * Scope) [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 245 of file bm_cond.cc.
References _func, itested, COMMON_COMPONENT::precalc_last(), and sCOUNT.
{
  //BUG// calls the individual precalc more than once
  // wastes time and makes multiple "has no value" warnings
  // when there should be only one
  COMMON_COMPONENT* did_this = NULL;
  for (int i = 1; i < sCOUNT; ++i) {
    assert(_func[i]);
    if (_func[i] != did_this) {
      _func[i]->precalc_last(Scope);
      did_this = _func[i];
    }else{itested();
      // already did
    }
  }
}
void anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::print_common_obsolete_callback (OMSTREAM & o, LANGUAGE * lang) const [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 262 of file bm_cond.cc.
References _func, _set, COMMON_COMPONENT::print_common_obsolete_callback(), s_NONE, and sCOUNT.
{
  assert(lang);
  bool more = false;
  if (_set[s_NONE]) {
    _func[s_NONE]->print_common_obsolete_callback(o, lang);
    more = true;
  }else{
  }
  for (int i = sCOUNT-1; i != s_NONE; --i) {
    if (_set[i]) {
      if (more) {
        o << ' ';
      }else{
      }
      o << ' ' << static_cast<SIM_MODE>(i) << ' ';
      _func[i]->print_common_obsolete_callback(o, lang);
      more = true;
    }else{
    }
  }
}
void anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::tr_accept (COMPONENT * d) [inline, private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 59 of file bm_cond.cc.
References CKT_BASE::_sim, and SIM_DATA::sim_mode().
        {assert(_func[d->_sim->sim_mode()]); _func[d->_sim->sim_mode()]->tr_accept(d);}
void anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::tr_eval (ELEMENT * d) const [inline, private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 53 of file bm_cond.cc.
References CKT_BASE::_sim, and SIM_DATA::sim_mode().
        {assert(_func[d->_sim->sim_mode()]); _func[d->_sim->sim_mode()]->tr_eval(d);}
TIME_PAIR anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::tr_review (COMPONENT * d) [inline, private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 57 of file bm_cond.cc.
References CKT_BASE::_sim, and SIM_DATA::sim_mode().
        {assert(_func[d->_sim->sim_mode()]); return _func[d->_sim->sim_mode()]->tr_review(d);}
Member Data Documentation
COMMON_COMPONENT* anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::_func[sCOUNT] [private]
Definition at line 36 of file bm_cond.cc.
Referenced by deflate(), EVAL_BM_COND(), expand(), parse_common_obsolete_callback(), precalc_first(), precalc_last(), print_common_obsolete_callback(), and ~EVAL_BM_COND().
bool anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::_set[sCOUNT] [private]
Definition at line 37 of file bm_cond.cc.
Referenced by EVAL_BM_COND(), parse_common_obsolete_callback(), and print_common_obsolete_callback().
The documentation for this class was generated from the following file:
savant/gnucap/src/bm_cond.cc