gnucap: CARD_LIST::fat_iterator Class Reference
CARD_LIST::fat_iterator Class Reference
#include <e_cardlist.h>
Public Member Functions
fat_iterator (const fat_iterator &p)
fat_iterator (CARD_LIST *l, iterator i)
bool is_end () const
CARD * operator* ()
fat_iterator & operator++ ()
fat_iterator operator++ (int)
bool operator== (const fat_iterator &x) const
bool operator!= (const fat_iterator &x) const
iterator iter () const
CARD_LIST * list () const
fat_iterator end () const
void insert (CARD *c)
Private Member Functions
fat_iterator ()
Private Attributes
CARD_LIST * _list
iterator _iter
Detailed Description
Definition at line 50 of file e_cardlist.h.
Constructor & Destructor Documentation
CARD_LIST::fat_iterator::fat_iterator () [inline, explicit, private]
Definition at line 55 of file e_cardlist.h.
References unreachable.
{unreachable();}
CARD_LIST::fat_iterator::fat_iterator (const fat_iterator & p) [inline]
Definition at line 57 of file e_cardlist.h.
                        : _list(p._list), _iter(p._iter) {}
CARD_LIST::fat_iterator::fat_iterator (CARD_LIST * l, iterator i) [inline, explicit]
Definition at line 59 of file e_cardlist.h.
                        : _list(l), _iter(i) {}
Member Function Documentation
fat_iterator CARD_LIST::fat_iterator::end () const [inline]
Definition at line 72 of file e_cardlist.h.
Referenced by findbranch().
{return fat_iterator(_list, _list->end());}
void CARD_LIST::fat_iterator::insert (CARD * c) [inline]
Definition at line 74 of file e_cardlist.h.
{list()->insert(iter(),c);}
bool CARD_LIST::fat_iterator::is_end () const [inline]
Definition at line 61 of file e_cardlist.h.
Referenced by findbranch(), anonymous_namespace{c_list.cc}::list_save(), and anonymous_namespace{s_dc.cc}::DC::setup().
{return _iter == _list->end();}
iterator CARD_LIST::fat_iterator::iter () const [inline]
Definition at line 70 of file e_cardlist.h.
{return _iter;}
CARD_LIST* CARD_LIST::fat_iterator::list () const [inline]
Definition at line 71 of file e_cardlist.h.
{return _list;}
bool CARD_LIST::fat_iterator::operator!= (const fat_iterator & x) const [inline]
Definition at line 68 of file e_cardlist.h.
References _iter, and _list.
                        {assert(_list==x._list); return (_iter!=x._iter);}
CARD* CARD_LIST::fat_iterator::operator* () [inline]
Definition at line 62 of file e_cardlist.h.
{return (is_end()) ? NULL : *_iter;}
fat_iterator& CARD_LIST::fat_iterator::operator++ () [inline]
Definition at line 63 of file e_cardlist.h.
{assert(!is_end()); ++_iter; return *this;}
fat_iterator CARD_LIST::fat_iterator::operator++ (int) [inline]
Definition at line 64 of file e_cardlist.h.
                {assert(!is_end()); fat_iterator t(*this); ++_iter; return t;}
bool CARD_LIST::fat_iterator::operator== (const fat_iterator & x) const [inline]
Definition at line 66 of file e_cardlist.h.
References _iter, _list, and unreachable.
             {unreachable(); assert(_list==x._list); return (_iter==x._iter);}
Member Data Documentation
iterator CARD_LIST::fat_iterator::_iter [private]
Definition at line 53 of file e_cardlist.h.
Referenced by operator!=(), and operator==().
CARD_LIST* CARD_LIST::fat_iterator::_list [private]
Definition at line 52 of file e_cardlist.h.
Referenced by operator!=(), and operator==().
The documentation for this class was generated from the following file:
savant/gnucap/src/e_cardlist.h