gnucap: anonymous_namespace{lang_spice.cc}::CMD_MODEL Class Reference
anonymous_namespace{lang_spice.cc}::CMD_MODEL Class Reference
Private Member Functions
void do_it (CS &cmd, CARD_LIST *Scope)
Detailed Description
Definition at line 809 of file lang_spice.cc.
Member Function Documentation
void anonymous_namespace{lang_spice.cc}::CMD_MODEL::do_it (CS & cmd, CARD_LIST * Scope) [inline, private, virtual]
Implements CMD.
Definition at line 810 of file lang_spice.cc.
References CARD::clone(), CS::cursor(), exists(), anonymous_namespace{lang_spice.cc}::lang_spice, model_dispatcher, CARD::owner(), anonymous_namespace{c_genrat.cc}::p, anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_paramset(), CARD_LIST::push_back(), scan_get(), CS::skip1b(), CS::stuck(), untested, and CS::warn().
  {
    // already got "model"
    std::string my_name, base_name;
    cmd >> my_name;
    unsigned here1 = cmd.cursor();
    cmd >> base_name;
    // "level" kluge ....
    // if there is a "level" keyword, with integer argument,
    // tack that onto the given modelname and look for that
    cmd.skip1b('(');
    int level = 0;
    {
      unsigned here = cmd.cursor();
      scan_get(cmd, "level ", &level);
      if (!cmd.stuck(&here)) {
        char buf[20];
        sprintf(buf, "%u", level);
        base_name += buf;
      }else{
      }
    }
    const MODEL_CARD* p = model_dispatcher[base_name];
    if (p) {
      MODEL_CARD* new_card = dynamic_cast<MODEL_CARD*>(p->clone());
      if (exists(new_card)) {
        assert(!new_card->owner());
        lang_spice.parse_paramset(cmd, new_card);
        Scope->push_back(new_card);
      }else{untested();
        cmd.warn(bDANGER, here1, "model: base has incorrect type");
      }
    }else{
      cmd.warn(bDANGER, here1, "model: \"" + base_name + "\" no match");
    }
  }
The documentation for this class was generated from the following file:
savant/gnucap/src/lang_spice.cc