gnucap: savant/gnucap/src/main.cc File Reference
savant/gnucap/src/main.cc File Reference
#include "e_cardlist.h"
#include "u_lang.h"
#include "ap.h"
#include "patchlev.h"
#include "c_comand.h"
#include "declare.h"
Classes
struct JMP_BUF
Functions
static void sign_on (void)
static void read_startup_files (void)
static void sig_abrt (SIGNALARGS)
static void sig_int (SIGNALARGS)
static void sig_fpe (SIGNALARGS)
static void setup_traps (void)
static void finish (void)
static void process_cmd_line (int argc, const char *argv[])
int main (int argc, const char *argv[])
Variables
struct JMP_BUF env
Function Documentation
static void finish (void) [static]
Definition at line 125 of file main.cc.
References outreset(), and plclose().
Referenced by main(), and process_cmd_line().
{
  plclose();
  outreset();
}
int main (int argc, const char * argv[])
Definition at line 180 of file main.cc.
References CS::_STDIN, CARD_LIST::card_list, CMD::cmdproc(), CMD::command(), env, error(), finish(), CS::get_line(), I_PROMPT, itested, OPT::language, JMP_BUF::p, LANGUAGE::parse_top_item(), process_cmd_line(), rBATCH, read_startup_files(), rINTERACTIVE, setup_traps(), sign_on(), unreachable, and untested.
{
  {
    SET_RUN_MODE xx(rBATCH);
    sign_on();
    if (!sigsetjmp(env.p, true)) {
      try {
        read_startup_files();
        setup_traps();
        process_cmd_line(argc,argv);
      }catch (Exception& e) {untested();
        error(bDANGER, e.message() + '\n');
        finish();               /* error clean up (from longjmp()) */
        CMD::command("quit", &CARD_LIST::card_list);
        unreachable();
        exit(0);
      }
    }else{
      finish();         /* error clean up (from longjmp()) */
      CMD::command("quit", &CARD_LIST::card_list);
      exit(0);
    }
  }
  {itested();
    SET_RUN_MODE xx(rINTERACTIVE);
    CS cmd(CS::_STDIN);
    for (;;) {itested();
      if (!sigsetjmp(env.p, true)) {itested();
        try {
          if (OPT::language) {
            OPT::language->parse_top_item(cmd, &CARD_LIST::card_list);
          }else{
            CMD::cmdproc(cmd.get_line(I_PROMPT), &CARD_LIST::card_list);
          }
        }catch (Exception_End_Of_Input& e) {itested();
          error(bDANGER, e.message() + '\n');
          finish();
          CMD::command("quit", &CARD_LIST::card_list);
          exit(0);
        }catch (Exception& e) {itested();
          error(bDANGER, e.message() + '\n');
          finish();
        }
      }else{itested();
        finish();               /* error clean up (from longjmp()) */
      }
    }
  }
  unreachable();
  return 0;
}
static void process_cmd_line (int argc, const char * argv[]) [static]
Definition at line 131 of file main.cc.
References CS::_STRING, CARD_LIST::card_list, CMD::cmdproc(), CMD::command(), error(), finish(), itested, and untested.
Referenced by main().
{
  for (int ii = 1;  ii < argc;  /*inside*/) {
    try {
      if (strcasecmp(argv[ii], "-i") == 0) {itested();
        ++ii;
        if (ii < argc) {itested();
          CMD::command(std::string("include ") + argv[ii++], &CARD_LIST::card_list);
        }else{untested();
        }
      }else if (strcasecmp(argv[ii], "-c") == 0) {itested();
        ++ii;
        if (ii < argc) {itested();
          CS cmd(CS::_STRING, argv[ii++]); // command line
          CMD::cmdproc(cmd, &CARD_LIST::card_list);
        }else{untested();
        }
      }else if (strcasecmp(argv[ii], "-b") == 0) {
        try {
          ++ii;
          if (ii < argc) {
            CMD::command(std::string("< ") + argv[ii++], &CARD_LIST::card_list);
          }else{untested();
            CMD::command(std::string("< /dev/stdin"), &CARD_LIST::card_list);
          }
        }catch (Exception& e) {
          error(bDANGER, e.message() + '\n');
          finish();
        }
        if (ii >= argc) {
          CMD::command("end", &CARD_LIST::card_list);
        }else{untested();
        }
      }else if (strcasecmp(argv[ii], "-a") == 0) {itested();
        ++ii;
        if (ii < argc) {itested();
          CMD::command(std::string("attach ") + argv[ii++], &CARD_LIST::card_list);
        }else{untested();
        }
      }else{itested();
        CMD::command(std::string("include ") + argv[ii++], &CARD_LIST::card_list);
      }
    }catch (Exception& e) {itested();
      error(bDANGER, e.message() + '\n');
      finish();
    }
  }
}
static void read_startup_files (void) [static]
Definition at line 51 of file main.cc.
References CARD_LIST::card_list, CMD::command(), DEFAULT_LANGUAGE, findfile(), OPT::language, SYSTEMSTARTFILE, SYSTEMSTARTPATH, untested, USERSTARTFILE, and USERSTARTPATH.
Referenced by main().
{
  std::string name = findfile(SYSTEMSTARTFILE, SYSTEMSTARTPATH, R_OK);
  if (name != "") {untested();
    CMD::command("get " + name, &CARD_LIST::card_list);
  }else{
  }
  name = findfile(USERSTARTFILE, USERSTARTPATH, R_OK);
  if (name != "") {untested();
    CMD::command("get " + name, &CARD_LIST::card_list);
  }else{
  }
  CMD::command("clear", &CARD_LIST::card_list);
  if (!OPT::language) {
    CMD::command(std::string("options lang=") + DEFAULT_LANGUAGE, &CARD_LIST::card_list);
  }else{
  }
}
static void setup_traps (void) [static]
Definition at line 111 of file main.cc.
References sig_abrt(), sig_fpe(), and sig_int().
Referenced by main().
{
  signal(SIGFPE,sig_fpe);
  signal(SIGINT,sig_int);
  signal(SIGABRT,sig_abrt);
}
static void sig_abrt (SIGNALARGS) [static]
Definition at line 73 of file main.cc.
References error(), itested, and untested.
Referenced by setup_traps().
  {itested();
    signal(SIGINT,sig_abrt);
    static int count = 10;
    if (--count > 0) {itested();
      error(bDANGER, "\n");
    }else{untested();
      exit(1);
    }
  }
static void sig_fpe (SIGNALARGS) [static]
Definition at line 103 of file main.cc.
References error(), and untested.
Referenced by setup_traps().
  {
    untested();
    signal(SIGFPE,sig_fpe);
    error(bDANGER, "floating point error\n");
  }
static void sig_int (SIGNALARGS) [static]
Definition at line 90 of file main.cc.
References env, IO::error, JMP_BUF::p, rBATCH, ENV::run_mode, and untested.
Referenced by setup_traps().
  {
    signal(SIGINT,sig_int);
    if (ENV::run_mode == rBATCH) {untested();
      exit(1);
    }else{
      IO::error << '\n';
      siglongjmp(env.p,1);
    }
  }
static void sign_on (void) [static]
Definition at line 37 of file main.cc.
References IO::mstdout, and PATCHLEVEL.
Referenced by main().
{
  IO::mstdout <<
    "Gnucap "  PATCHLEVEL  "\n"
    "The Gnu Circuit Analysis Package\n"
    "Never trust any version less than 1.0\n"
    "Copyright 1982-2009, Albert Davis\n"
    "Gnucap comes with ABSOLUTELY NO WARRANTY\n"
    "This is free software, and you are welcome\n"
    "to redistribute it under the terms of \n"
    "the GNU General Public License, version 3 or later.\n"
    "See the file \"COPYING\" for details.\n";
}
Variable Documentation
struct JMP_BUF env
Referenced by main(), and sig_int().