gnucap: anonymous_namespace{c_list.cc}::CMD_SAVE Class Reference
anonymous_namespace{c_list.cc}::CMD_SAVE Class Reference
Public Member Functions
void do_it (CS &cmd, CARD_LIST *Scope)
Detailed Description
Definition at line 115 of file c_list.cc.
Member Function Documentation
void anonymous_namespace{c_list.cc}::CMD_SAVE::do_it (CS & cmd, CARD_LIST * Scope) [inline, virtual]
Implements CMD.
Definition at line 117 of file c_list.cc.
References itested, anonymous_namespace{c_list.cc}::list_save(), outset(), and CS::reset().
  {itested();
    cmd.reset(); /* back up to beginning of input line */
    OMSTREAM out; // = IO::mstdout;
    list_save(cmd, *outset(cmd,&out), Scope);
  }
The documentation for this class was generated from the following file:
savant/gnucap/src/c_list.cc