gnucap: WAVE Class Reference
WAVE Class Reference
#include <m_wave.h>
Public Types
typedef std::deque< DPAIR >
::iterator iterator
typedef std::deque< DPAIR >
::const_iterator const_iterator
Public Member Functions
WAVE (double d=0)
~WAVE ()
WAVE & set_delay (double d)
WAVE & initialize ()
WAVE & push (double t, double v)
FPOLY1 v_out (double t) const
double v_reflect (double t, double v_total) const
WAVE & operator+= (const WAVE &x)
WAVE & operator+= (double x)
WAVE & operator*= (const WAVE &x)
WAVE & operator*= (double x)
const_iterator begin () const
const_iterator end () const
Private Member Functions
WAVE (const WAVE &)
Private Attributes
std::deque< DPAIR > _w
double _delay
Detailed Description
Definition at line 28 of file m_wave.h.
Member Typedef Documentation
typedef std::deque<DPAIR>::const_iterator WAVE::const_iterator
Definition at line 35 of file m_wave.h.
typedef std::deque<DPAIR>::iterator WAVE::iterator
Definition at line 34 of file m_wave.h.
Constructor & Destructor Documentation
WAVE::WAVE (const WAVE &) [inline, explicit, private]
Definition at line 32 of file m_wave.h.
References unreachable.
{unreachable();}
WAVE::WAVE (double d = 0) [inline, explicit]
Definition at line 73 of file m_wave.h.
References initialize().
  :_w(),
   _delay(d)
{
  initialize();
}
WAVE::~WAVE () [inline]
Definition at line 38 of file m_wave.h.
{}
Member Function Documentation
const_iterator WAVE::begin () const [inline]
Definition at line 48 of file m_wave.h.
References _w.
Referenced by anonymous_namespace{measure_average.cc}::MEASURE::eval(), anonymous_namespace{measure_cross.cc}::MEASURE::eval(), anonymous_namespace{measure_rms.cc}::MEASURE::eval(), anonymous_namespace{measure_min.cc}::MEASURE::eval(), anonymous_namespace{measure_max.cc}::MEASURE::eval(), anonymous_namespace{measure_integral.cc}::MEASURE::eval(), and anonymous_namespace{measure_slewrate.cc}::MEASURE::eval().
{return _w.begin();}
const_iterator WAVE::end () const [inline]
Definition at line 49 of file m_wave.h.
References _w.
Referenced by anonymous_namespace{measure_average.cc}::MEASURE::eval(), anonymous_namespace{measure_cross.cc}::MEASURE::eval(), anonymous_namespace{measure_rms.cc}::MEASURE::eval(), anonymous_namespace{measure_min.cc}::MEASURE::eval(), anonymous_namespace{measure_max.cc}::MEASURE::eval(), anonymous_namespace{measure_integral.cc}::MEASURE::eval(), and anonymous_namespace{measure_slewrate.cc}::MEASURE::eval().
{return _w.end();}
WAVE & WAVE::initialize () [inline]
Definition at line 65 of file m_wave.h.
References _w.
Referenced by anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_begin(), and WAVE().
{
  _w.clear();
  return *this;
}
WAVE & WAVE::operator*= (const WAVE & x) [inline]
Definition at line 127 of file m_wave.h.
References _w, FPOLY1::f0, untested, and v_out().
{
  untested();
  for (std::deque<DPAIR>::iterator
         i = _w.begin(); i != _w.end(); ++i) {
    untested();
    (*i).second *= x.v_out((*i).first).f0;
  }
  return *this;
}
WAVE & WAVE::operator*= (double x) [inline]
Definition at line 138 of file m_wave.h.
References _w, and untested.
{
  untested();
  for (std::deque<DPAIR>::iterator
         i = _w.begin(); i != _w.end(); ++i) {
    untested();
    (*i).second *= x;
  }
  return *this;
}
WAVE & WAVE::operator+= (const WAVE & x) [inline]
Definition at line 105 of file m_wave.h.
References _w, FPOLY1::f0, untested, and v_out().
{
  untested();
  for (std::deque<DPAIR>::iterator
         i = _w.begin(); i != _w.end(); ++i) {
    untested();
    (*i).second += x.v_out((*i).first).f0;
  }
  return *this;
}
WAVE & WAVE::operator+= (double x) [inline]
Definition at line 116 of file m_wave.h.
References _w, and untested.
{
  untested();
  for (std::deque<DPAIR>::iterator
         i = _w.begin(); i != _w.end(); ++i) {
    untested();
    (*i).second += x;
  }
  return *this;
}
WAVE & WAVE::push (double t, double v) [inline]
Definition at line 57 of file m_wave.h.
References _delay, and _w.
Referenced by SIM::store_results(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_accept(), and anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_begin().
{
  _w.push_back(DPAIR(t+_delay, v));
  return *this;
}
WAVE & WAVE::set_delay (double d) [inline]
Definition at line 80 of file m_wave.h.
References _delay.
Referenced by anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::precalc_last().
{
  _delay = d;
  return *this;
}
FPOLY1 WAVE::v_out (double t) const [inline]
Definition at line 89 of file m_wave.h.
References _w, and interpolate().
Referenced by anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::dc_advance(), anonymous_namespace{measure_at.cc}::MEASURE::eval(), operator*=(), operator+=(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_advance(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_regress(), and v_reflect().
{
  return interpolate(_w.begin(), _w.end(), t, 0., 0.);
}
double WAVE::v_reflect (double t, double v_total) const [inline]
Definition at line 99 of file m_wave.h.
References dn_diff(), and v_out().
Referenced by anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_accept().
{
  // return (v_total*2 - v_out(t)); // de-noised
  return dn_diff(v_total*2, v_out(t).f0);
}
Member Data Documentation
double WAVE::_delay [private]
Definition at line 31 of file m_wave.h.
Referenced by push(), and set_delay().
std::deque<DPAIR> WAVE::_w [private]
Definition at line 30 of file m_wave.h.
Referenced by begin(), end(), initialize(), operator*=(), operator+=(), push(), and v_out().
The documentation for this class was generated from the following file:
savant/gnucap/src/m_wave.h