gnucap: anonymous_namespace{lang_geda.cc}::LANG_GEDA Class Reference
anonymous_namespace{lang_geda.cc}::LANG_GEDA Class Reference
Public Types
enum MODE { mATTRIBUTE, mCOMMENT }
Public Member Functions
std::string name () const
bool case_insensitive () const
UNITS units () const
std::string arg_front () const
std::string arg_mid () const
std::string arg_back () const
void parse_top_item (CS &, CARD_LIST *)
DEV_COMMENT * parse_comment (CS &, DEV_COMMENT *)
DEV_DOT * parse_command (CS &, DEV_DOT *)
MODEL_CARD * parse_paramset (CS &, MODEL_CARD *)
MODEL_SUBCKT * parse_module (CS &, MODEL_SUBCKT *)
COMPONENT * parse_instance (CS &, COMPONENT *)
std::string find_type_in_string (CS &)
MODEL_SUBCKT * parse_componmod (CS &, MODEL_SUBCKT *)
Public Attributes
enum anonymous_namespace{lang_geda.cc}::LANG_GEDA::MODE _mode
int _no_of_lines
bool _componentmod
std::string _componentname
bool _gotaline
Private Member Functions
void print_paramset (OMSTREAM &, const MODEL_CARD *)
void print_module (OMSTREAM &, const MODEL_SUBCKT *)
void print_instance (OMSTREAM &, const COMPONENT *)
void print_comment (OMSTREAM &, const DEV_COMMENT *)
void print_command (OMSTREAM &o, const DEV_DOT *c)
Detailed Description
Definition at line 41 of file lang_geda.cc.
Member Enumeration Documentation
enum anonymous_namespace{lang_geda.cc}::LANG_GEDA::MODE
Enumerator:
mATTRIBUTE
mCOMMENT
Definition at line 45 of file lang_geda.cc.
{mATTRIBUTE, mCOMMENT} _mode;
Member Function Documentation
std::string anonymous_namespace{lang_geda.cc}::LANG_GEDA::arg_back () const [inline, virtual]
Implements LANGUAGE.
Definition at line 62 of file lang_geda.cc.
{
        return "";  //arbitrary
    }
std::string anonymous_namespace{lang_geda.cc}::LANG_GEDA::arg_front () const [inline, virtual]
Implements LANGUAGE.
Definition at line 56 of file lang_geda.cc.
{
        return " "; //arbitrary
    }
std::string anonymous_namespace{lang_geda.cc}::LANG_GEDA::arg_mid () const [inline, virtual]
Implements LANGUAGE.
Definition at line 59 of file lang_geda.cc.
{
        return "="; //arbitrary
    }
bool anonymous_namespace{lang_geda.cc}::LANG_GEDA::case_insensitive () const [inline, virtual]
Implements LANGUAGE.
Definition at line 52 of file lang_geda.cc.
{return false;}
std::string anonymous_namespace{lang_geda.cc}::LANG_GEDA::find_type_in_string (CS & cmd) [virtual]
Implements LANGUAGE.
Definition at line 630 of file lang_geda.cc.
References CS::cursor(), and CS::reset().
Referenced by anonymous_namespace{lang_geda.cc}::parse_component(), anonymous_namespace{lang_geda.cc}::parse_net(), and anonymous_namespace{lang_geda.cc}::parse_type().
{
    unsigned here = cmd.cursor(); //store cursor position to reset back later
    std::string type;   //stores type : should check device attribute..
    //graphical=["v","L","G","B","V","A","H","T"]
    if (cmd >> "v " || cmd >> "L " || cmd >> "G " || cmd >> "B " || cmd >>"V "
        || cmd >> "A " || cmd >> "H " || cmd >> "T " ){ type="dev_comment";}
    else if (cmd >> "N "){ type="net";}
    else if (cmd >> "U "){ type="bus";}
    else if (cmd >> "P "){ type="pin";}
    else if (cmd >> "C "){
        if(_componentmod){
            type="C";
        }else{
            type=_componentname;
        }
    }
    else if (cmd >> "place "){ type="place";}
    else {
        switch(_mode){
            case mCOMMENT: return "dev_comment";
            default : cmd >> type;
        }
    } //Not matched with the type. What now?
    cmd.reset(here);//Reset cursor back to the position that
                    //has been started with at beginning
    return type;    // returns the type of the string
}
std::string anonymous_namespace{lang_geda.cc}::LANG_GEDA::name () const [inline, virtual]
Implements LANGUAGE.
Definition at line 51 of file lang_geda.cc.
{return "gschem";}
DEV_DOT * anonymous_namespace{lang_geda.cc}::LANG_GEDA::parse_command (CS & cmd, DEV_DOT * x) [virtual]
Implements LANGUAGE.
Definition at line 532 of file lang_geda.cc.
References CARD_LIST::card_list, CMD::cmdproc(), CS::fullstring(), CARD::owner(), CS::reset(), DEV_DOT::set(), CARD::subckt(), and trace0.
{
    trace0("got into parse_command");
    assert(x);
    x->set(cmd.fullstring());
    CARD_LIST* scope = (x->owner()) ? x->owner()->subckt() : &CARD_LIST::card_list;
    cmd.reset();
    CMD::cmdproc(cmd, scope);
    delete x;
    return NULL;
}
DEV_COMMENT * anonymous_namespace{lang_geda.cc}::LANG_GEDA::parse_comment (CS & cmd, DEV_COMMENT * x) [virtual]
Implements LANGUAGE.
Definition at line 505 of file lang_geda.cc.
References CS::fullstring(), and DEV_COMMENT::set().
{
    assert(x);
    x->set(cmd.fullstring());
    std::string dump,no_of_lines="";
    if (cmd >> "T "){
        _mode=mCOMMENT;
        for(int i=0; i<8; ++i){
            cmd >> dump >> " ";
        }
        cmd>>no_of_lines;
        if(no_of_lines==""){
            _no_of_lines=1;
        }else{
            _no_of_lines=atoi(no_of_lines.c_str());
        }
    }else{
        if(_no_of_lines!=0){
            --_no_of_lines;
            if(_no_of_lines==0){
                _mode=mATTRIBUTE;
            }
        }
    }
    return x;
}
MODEL_SUBCKT * anonymous_namespace{lang_geda.cc}::LANG_GEDA::parse_componmod (CS & cmd, MODEL_SUBCKT * x)
Definition at line 557 of file lang_geda.cc.
References anonymous_namespace{lang_geda.cc}::parse_symbol_file(), CS::reset(), CKT_BASE::set_label(), and trace0.
Referenced by anonymous_namespace{lang_geda.cc}::CMD_C::do_it().
{
    trace0("got into parse_componmod");
    assert(x);
    cmd.reset();
    std::string type = find_type_in_string(cmd);
    trace0("found string type");
    assert(type=="C");
    std::string component_x, component_y, mirror, angle, dump,basename;
    bool isgraphical=false;
    cmd>>"C";
    cmd>>component_x>>" ">>component_y>>" ">>dump>>" ">>angle>>" ">>mirror>>" ">>basename;
    trace0("got params");
    //open the basename to get the ports and their placements
    //parse_ports(newcmd,x);
    x->set_label("!_"+basename);
    trace0("set labels");
    std::vector<std::string*> coord=parse_symbol_file(x,basename);
    trace0("parsed symbol file");
    if(coord.size()==0){
        isgraphical=true;
    }
    if (isgraphical==true) {
        return NULL;
    }
    else{
        cmd.reset();
    }
    trace0("got out");
    /*type = "graphical";
    x->set_dev_type(type);
    std::cout<<x->dev_type()<<" is the dev type\n";
    */
    return x;
}
COMPONENT * anonymous_namespace{lang_geda.cc}::LANG_GEDA::parse_instance (CS & cmd, COMPONENT * x) [virtual]
Implements LANGUAGE.
Definition at line 593 of file lang_geda.cc.
References CARD::dev_type(), anonymous_namespace{lang_geda.cc}::parse_component(), anonymous_namespace{lang_geda.cc}::parse_net(), anonymous_namespace{lang_geda.cc}::parse_place(), anonymous_namespace{lang_geda.cc}::parse_type(), CS::reset(), and trace0.
{
    trace0("got into parse_instance");
    cmd.reset();
    parse_type(cmd, x); //parse type will parse the component type and set_dev_type
    if (x->dev_type()=="net") {
    parse_net(cmd,x);
    }else if(x->dev_type()=="place"){
    parse_place(cmd,x);
    }else {
    parse_component(cmd,x);
    }
    //No warnings needed.
    //cmd.check(bWARNING, "what's ins this?");
    return x;
}
MODEL_SUBCKT * anonymous_namespace{lang_geda.cc}::LANG_GEDA::parse_module (CS & cmd, MODEL_SUBCKT * x) [virtual]
Implements LANGUAGE.
Definition at line 551 of file lang_geda.cc.
{
  //To parse heirarchical schematics
  return NULL;
}
MODEL_CARD * anonymous_namespace{lang_geda.cc}::LANG_GEDA::parse_paramset (CS & cmd, MODEL_CARD * x) [virtual]
Implements LANGUAGE.
Definition at line 545 of file lang_geda.cc.
{
    assert(x);
    return NULL;
}
void anonymous_namespace{lang_geda.cc}::LANG_GEDA::parse_top_item (CS & cmd, CARD_LIST * Scope) [virtual]
Reimplemented from LANGUAGE.
Definition at line 663 of file lang_geda.cc.
References CS::get_line(), and trace0.
{
    trace0("got into parse_top_item");
    if(!_gotaline){
        cmd.get_line("gnucap-geda>");
        trace0("false _gotaline");
    }else{
        _gotaline=false;
        trace0("true _gotaline");
    }
    new__instance(cmd, NULL, Scope);
}
void anonymous_namespace{lang_geda.cc}::LANG_GEDA::print_command (OMSTREAM & o, const DEV_DOT * c) [private, virtual]
Implements LANGUAGE.
Definition at line 929 of file lang_geda.cc.
References DEV_DOT::s().
{
  assert(x);
  o << x->s() << '\n';
}
void anonymous_namespace{lang_geda.cc}::LANG_GEDA::print_comment (OMSTREAM & o, const DEV_COMMENT * x) [private, virtual]
Implements LANGUAGE.
Definition at line 923 of file lang_geda.cc.
References DEV_COMMENT::comment().
{
  assert(x);
  o << x->comment() << '\n';
}
void anonymous_namespace{lang_geda.cc}::LANG_GEDA::print_instance (OMSTREAM & o, const COMPONENT * x) [private, virtual]
Implements LANGUAGE.
Definition at line 908 of file lang_geda.cc.
References CARD::dev_type(), anonymous_namespace{lang_geda.cc}::print_component(), anonymous_namespace{lang_geda.cc}::print_net(), and trace0.
{
  trace0("Got into print_instance in geda!");
 // print_type(o, x);
 // print_label(o, x);
  if(x->dev_type()=="net"){
    print_net(o, x);
  }
  else if(x->dev_type()=="place"){
 }else{
    //Component
    print_component(o ,x);
  }
  }
void anonymous_namespace{lang_geda.cc}::LANG_GEDA::print_module (OMSTREAM & o, const MODEL_SUBCKT * x) [private, virtual]
Implements LANGUAGE.
Definition at line 896 of file lang_geda.cc.
References CKT_BASE::short_label(), CARD::subckt(), and trace0.
{
  assert(x);
  //o<<x->short_label();
  //o<<"\n";
  assert(x->subckt());
  if(x->short_label().find("!_")!=std::string::npos){
    trace0("Got a placeholding model");
    return;
  }
}
void anonymous_namespace{lang_geda.cc}::LANG_GEDA::print_paramset (OMSTREAM & o, const MODEL_CARD * x) [private, virtual]
Implements LANGUAGE.
Definition at line 890 of file lang_geda.cc.
References trace0.
{
    trace0("Got into print paramset");
    return;
}
UNITS anonymous_namespace{lang_geda.cc}::LANG_GEDA::units () const [inline, virtual]
Implements LANGUAGE.
Definition at line 53 of file lang_geda.cc.
References uSI.
{return uSI;}
Member Data Documentation
bool anonymous_namespace{lang_geda.cc}::LANG_GEDA::_componentmod [mutable]
Definition at line 47 of file lang_geda.cc.
Referenced by anonymous_namespace{lang_geda.cc}::CMD_GSCHEM::do_it(), anonymous_namespace{lang_geda.cc}::CMD_C::do_it(), and anonymous_namespace{lang_geda.cc}::parse_component().
std::string anonymous_namespace{lang_geda.cc}::LANG_GEDA::_componentname [mutable]
Definition at line 48 of file lang_geda.cc.
Referenced by anonymous_namespace{lang_geda.cc}::CMD_C::do_it().
bool anonymous_namespace{lang_geda.cc}::LANG_GEDA::_gotaline [mutable]
Definition at line 49 of file lang_geda.cc.
Referenced by anonymous_namespace{lang_geda.cc}::CMD_GSCHEM::do_it(), anonymous_namespace{lang_geda.cc}::parse_component(), and anonymous_namespace{lang_geda.cc}::parse_net().
enum anonymous_namespace{lang_geda.cc}::LANG_GEDA::MODE anonymous_namespace{lang_geda.cc}::LANG_GEDA::_mode
Referenced by anonymous_namespace{lang_geda.cc}::CMD_GSCHEM::do_it().
int anonymous_namespace{lang_geda.cc}::LANG_GEDA::_no_of_lines [mutable]
Definition at line 46 of file lang_geda.cc.
Referenced by anonymous_namespace{lang_geda.cc}::CMD_GSCHEM::do_it().
The documentation for this class was generated from the following file:
savant/gnucap/src/lang_geda.cc