gnucap: anonymous_namespace{s_ac.cc}::AC Class Reference
anonymous_namespace{s_ac.cc}::AC Class Reference
Public Member Functions
void do_it (CS &, CARD_LIST *)
AC ()
~AC ()
Private Types
enum {
ONE_PT, LIN_STEP, LIN_PTS, TIMES,
OCTAVE, DECADE
}
Private Member Functions
AC (const AC &)
void sweep ()
void first ()
bool next ()
void solve ()
void clear ()
void setup (CS &)
Private Attributes
PARAMETER< double > _start
PARAMETER< double > _stop
PARAMETER< double > _step_in
double _step
bool _linswp
bool _prevopppoint
enum anonymous_namespace{s_ac.cc}::AC:: { ... } _stepmode
Detailed Description
Definition at line 33 of file s_ac.cc.
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
ONE_PT
LIN_STEP
LIN_PTS
TIMES
OCTAVE
DECADE
Definition at line 64 of file s_ac.cc.
{ONE_PT, LIN_STEP, LIN_PTS, TIMES, OCTAVE, DECADE} _stepmode;
Constructor & Destructor Documentation
anonymous_namespace{s_ac.cc}::AC::AC () [inline, explicit]
Definition at line 37 of file s_ac.cc.
               :
    SIM(),
    _start(),
    _stop(),
    _step_in(),
    _step(0.),
    _linswp(false),
    _prevopppoint(false),
    _stepmode(ONE_PT)
  {}
anonymous_namespace{s_ac.cc}::AC::~AC () [inline]
Definition at line 48 of file s_ac.cc.
{}
anonymous_namespace{s_ac.cc}::AC::AC (const AC &) [inline, explicit, private]
Definition at line 50 of file s_ac.cc.
References incomplete, and unreachable.
:SIM() {unreachable(); incomplete();}
Member Function Documentation
void anonymous_namespace{s_ac.cc}::AC::clear () [private]
void anonymous_namespace{s_ac.cc}::AC::do_it (CS & Cmd, CARD_LIST * Scope) [virtual]
Implements CMD.
Definition at line 68 of file s_ac.cc.
References STATUS::ac, itested, OPT::pivtol, rBATCH, TIMER::reset(), rINTERACTIVE, rPRE_MAIN, rPRESET, rSCRIPT, ENV::run_mode, STATUS::set_up, anonymous_namespace{c_sweep.cc}::setup(), TIMER::start(), status, TIMER::stop(), STATUS::total, and unreachable.
{
  _scope = Scope;
  _sim->set_command_ac();
  reset_timers();
  ::status.ac.reset().start();
  _sim->init();
  _sim->alloc_vectors();
  _sim->_acx.reallocate();
  _sim->_acx.set_min_pivot(OPT::pivtol);
  setup(Cmd);
  ::status.set_up.stop();
  switch (ENV::run_mode) {
  case rPRE_MAIN:       unreachable();  break;
  case rBATCH:          itested();
  case rINTERACTIVE:    itested();
  case rSCRIPT:         sweep();        break;
  case rPRESET:         /*nothing*/     break;
  }
  _sim->_acx.unallocate();
  _sim->unalloc_vectors();
  ::status.ac.stop();
  ::status.total.stop();
}
void anonymous_namespace{s_ac.cc}::AC::first () [private]
Definition at line 251 of file s_ac.cc.
{
  _sim->_freq = _start;
}
bool anonymous_namespace{s_ac.cc}::AC::next () [private]
Definition at line 256 of file s_ac.cc.
References in_order().
{
  double realstop = (_linswp)
    ? _stop - _step/100.
    : _stop / pow(_step,.01);
  if (!in_order(double(_start), _sim->_freq, realstop)) {
    return false;
  }else{
  }
  _sim->_freq = (_linswp)
    ? _sim->_freq + _step
    : _sim->_freq * _step;
  if (in_order(_sim->_freq, double(_start), double(_stop))) {
    return false;
  }else{
    return true;
  }
}
void anonymous_namespace{s_ac.cc}::AC::setup (CS & Cmd) [private, virtual]
Implements SIM.
Definition at line 99 of file s_ac.cc.
References CS::check(), CS::cursor(), Get(), initio(), CS::is_float(), CS::match1(), mOFFSET, CS::more(), IO::mstdout, ONE_OF, outset(), IO::plotout, IO::plotset, OMSTREAM::reset(), CS::stuck(), OPT::temp_c, and untested.
{
  _out = IO::mstdout;
  _out.reset(); //BUG// don't know why this is needed
  //temp_c = OPT::temp_c;
  // Don't set temperature.  Keep whatever was there before,
  // from "op" or whatever.
  bool ploton = IO::plotset  &&  plotlist().size() > 0;
  ONE_OF
    || (Get(Cmd, "*",           &_step_in) && (_stepmode = TIMES))
    || (Get(Cmd, "+",           &_step_in) && (_stepmode = LIN_STEP))
    || (Get(Cmd, "by",          &_step_in) && (_stepmode = LIN_STEP))
    || (Get(Cmd, "step",        &_step_in) && (_stepmode = LIN_STEP))
    || (Get(Cmd, "d{ecade}",    &_step_in) && (_stepmode = DECADE))
    || (Get(Cmd, "ti{mes}",     &_step_in) && (_stepmode = TIMES))
    || (Get(Cmd, "lin",         &_step_in) && (_stepmode = LIN_PTS))
    || (Get(Cmd, "o{ctave}",    &_step_in) && (_stepmode = OCTAVE));
  if (Cmd.match1("'\"({") || Cmd.is_float()) {
    Cmd >> _start;
    if (Cmd.match1("'\"({") || Cmd.is_float()) {
      Cmd >> _stop;
    }else{
      _stop = _start;
    }
    if (Cmd.match1("'\"({") || Cmd.is_float()) {
      _stepmode = LIN_STEP;
      Cmd >> _step_in;
    }else{
    }
  }
  unsigned here = Cmd.cursor();
  do{
    ONE_OF
      || (Get(Cmd, "*",           &_step_in) && (_stepmode = TIMES))
      || (Get(Cmd, "+",           &_step_in) && (_stepmode = LIN_STEP))
      || (Get(Cmd, "by",          &_step_in) && (_stepmode = LIN_STEP))
      || (Get(Cmd, "step",        &_step_in) && (_stepmode = LIN_STEP))
      || (Get(Cmd, "d{ecade}",    &_step_in) && (_stepmode = DECADE))
      || (Get(Cmd, "ti{mes}",     &_step_in) && (_stepmode = TIMES))
      || (Get(Cmd, "lin",         &_step_in) && (_stepmode = LIN_PTS))
      || (Get(Cmd, "o{ctave}",    &_step_in) && (_stepmode = OCTAVE))
      || Get(Cmd, "dt{emp}",      &_sim->_temp_c,  mOFFSET, OPT::temp_c)
      || Get(Cmd, "pl{ot}",       &ploton)
      || Get(Cmd, "pr{evoppoint}",&_prevopppoint)
      || Get(Cmd, "sta{rt}",      &_start)
      || Get(Cmd, "sto{p}",       &_stop)
      || Get(Cmd, "te{mperature}",&_sim->_temp_c)
      || outset(Cmd,&_out)
      ;
  }while (Cmd.more() && !Cmd.stuck(&here));
  Cmd.check(bWARNING, "what's this??");
  _start.e_val(0., _scope);
  _stop.e_val(0., _scope);
  _step_in.e_val(0., _scope);
  _step = _step_in;
  switch (_stepmode) {
  case ONE_PT:
  case LIN_STEP:
    needslinfix = false;
    _linswp = true;
    break;
  case LIN_PTS:untested();
    if (_step <= 2.) {untested();// need to fix step, later
      _step = 2.;               // do it at the end of setup
    }else{untested();           // a kluge, but this is a patch
    }
    needslinfix = true;         // and I am too lazy to do it
    _linswp = true;             // right.
    break;
  case TIMES:untested();
    if (_step == 0.  &&  _start != 0.) {untested();
      _step = _stop / _start;
    }else{untested();
    }
    needslinfix = false;
    _linswp = false;
    break;
  case OCTAVE:
    if (_step == 0.) {untested();
      _step = 1.;
    }else{
    }
    _step = pow(2.00000001, 1./_step);
    needslinfix = false;
    _linswp = false;
    break;
  case DECADE:
    if (_step == 0.) {
      _step = 1.;
    }else{
    }
    _step = pow(10., 1./_step);
    needslinfix = false;
    _linswp = false;
    break;
  };
  if (needslinfix) {untested();         // LIN option is # of points.
    assert(_step >= 2);                 // Must compute step after
    _step=(_stop-_start)/(_step-1.);    // reading start and stop,
    needslinfix = false;                // but step must be read first
  }else{                        // for Spice compatibility
  }
  if (_step==0.) {
    _step = _stop - _start;
    _linswp = true;
  }else{
  }
  IO::plotout = (ploton) ? IO::mstdout : OMSTREAM();
  initio(_out);
}
void anonymous_namespace{s_ac.cc}::AC::solve () [private]
Definition at line 219 of file s_ac.cc.
References CARD_LIST::ac_load(), STATUS::back, CARD_LIST::card_list, CARD_LIST::do_ac(), iTOTAL, STATUS::load, STATUS::lud, TIMER::start(), status, and TIMER::stop().
{
  _sim->_acx.zero();
  std::fill_n(_sim->_ac, _sim->_total_nodes+1, 0.);
  ::status.load.start();
  _sim->count_iterations(iTOTAL);
  CARD_LIST::card_list.do_ac();
  CARD_LIST::card_list.ac_load();
  ::status.load.stop();
  ::status.lud.start();
  _sim->_acx.lu_decomp();
  ::status.lud.stop();
  ::status.back.start();
  _sim->_acx.fbsub(_sim->_ac);
  ::status.back.stop();
}
void anonymous_namespace{s_ac.cc}::AC::sweep () [private, virtual]
Implements SIM.
Definition at line 239 of file s_ac.cc.
References CARD_LIST::ac_begin(), CARD_LIST::card_list, head, and M_TWO_PI.
{
  head(_start, _stop, "Freq");
  first();
  CARD_LIST::card_list.ac_begin();
  do {
    _sim->_jomega = COMPLEX(0., _sim->_freq * M_TWO_PI);
    solve();
    outdata(_sim->_freq);
  } while (next());
}
Member Data Documentation
bool anonymous_namespace{s_ac.cc}::AC::_linswp [private]
Definition at line 62 of file s_ac.cc.
bool anonymous_namespace{s_ac.cc}::AC::_prevopppoint [private]
Definition at line 63 of file s_ac.cc.
PARAMETER<double> anonymous_namespace{s_ac.cc}::AC::_start [private]
Definition at line 58 of file s_ac.cc.
double anonymous_namespace{s_ac.cc}::AC::_step [private]
Definition at line 61 of file s_ac.cc.
PARAMETER<double> anonymous_namespace{s_ac.cc}::AC::_step_in [private]
Definition at line 60 of file s_ac.cc.
enum { ... } anonymous_namespace{s_ac.cc}::AC::_stepmode [private]
PARAMETER<double> anonymous_namespace{s_ac.cc}::AC::_stop [private]
Definition at line 59 of file s_ac.cc.
The documentation for this class was generated from the following file:
savant/gnucap/src/s_ac.cc