gnucap: anonymous_namespace{c_list.cc} Namespace Reference
anonymous_namespace{c_list.cc} Namespace Reference
Classes
class CMD_LIST
class CMD_SAVE
Functions
void list_save (CS &cmd, OMSTREAM out, CARD_LIST *scope)
Variables
anonymous_namespace{c_list.cc}::CMD_LIST p1
DISPATCHER< CMD >::INSTALL d1 & command_dispatcher
anonymous_namespace{c_list.cc}::CMD_SAVE p2
Function Documentation
void anonymous_namespace{c_list.cc}::list_save (CS & cmd, OMSTREAM out, CARD_LIST * scope)
Definition at line 33 of file c_list.cc.
References CARD_LIST::begin(), CARD_LIST::card_list, CS::cursor(), CARD_LIST::end(), findbranch(), head, CARD_LIST::fat_iterator::is_end(), CS::is_end(), itested, OPT::language, CS::match1(), IO::mstdout, CARD_LIST::precalc_first(), LANGUAGE::print_item(), rBATCH, CS::reset(), rINTERACTIVE, rPRE_MAIN, rPRESET, rSCRIPT, ENV::run_mode, CS::skip(), and unreachable.
Referenced by anonymous_namespace{c_list.cc}::CMD_LIST::do_it(), and anonymous_namespace{c_list.cc}::CMD_SAVE::do_it().
{
  CARD_LIST::card_list.precalc_first();
  //out.setfloatwidth(7);
  switch (ENV::run_mode) {
  case rPRE_MAIN:
    unreachable();
    return;
  case rPRESET:
    /* do nothing */
    return;
  case rBATCH:          itested();
  case rINTERACTIVE:    itested();
  case rSCRIPT:
    /* keep going */
    break;
  }
  if (!OPT::language) {
    throw Exception("no language");
  }else{
  }
  (out - IO::mstdout) << head << '\n';
  if (cmd.is_end()) {                   /* no args: list all                */
    for (CARD_LIST::const_iterator ci=scope->begin();ci!=scope->end();++ci) {
      OPT::language->print_item(out, *ci);
    }
  }else{                                /* some args: be selective          */
    unsigned arg1 = cmd.cursor();
    CARD_LIST::fat_iterator ci = (cmd.match1('-'))
      ? CARD_LIST::fat_iterator(scope, scope->begin())
      : findbranch(cmd, scope);
    if (ci.is_end()) {itested();
      throw Exception_CS("can't find", cmd);
    }else{
    }
    if (cmd.match1('-')) {              /* there is a dash:  a range        */
      cmd.skip();
      if (cmd.is_end()) {       /* line ends with dash: all to end  */
        do {
          OPT::language->print_item(out, *ci);
        } while (++ci, !ci.is_end());
      }else{
        CARD_LIST::fat_iterator stop = ci;
        stop = findbranch(cmd, ++stop);
        if (stop.is_end()) {itested();
          throw Exception_CS("can't find", cmd);
        }else{
          do {
            OPT::language->print_item(out, *ci);
          } while (ci++ != stop); // note subtle difference
        }
      }
    }else{                              /* no dash: a list                  */
      do {                              /* each arg                         */
        unsigned next = cmd.cursor();
        do {                            /* all that match this arg          */
          OPT::language->print_item(out, *ci);
          cmd.reset(arg1);
          assert(!ci.is_end());
          ci = findbranch(cmd, ++ci); // next match
        } while (!ci.is_end());
        cmd.reset(arg1 = next);
        ci = findbranch(cmd, scope); // next arg
      } while (!ci.is_end());
    }
  }
}
Variable Documentation
DISPATCHER< CMD >::INSTALL d2 & anonymous_namespace{c_list.cc}::command_dispatcher
Definition at line 113 of file c_list.cc.
anonymous_namespace{c_list.cc}::CMD_LIST anonymous_namespace{c_list.cc}::p1
anonymous_namespace{c_list.cc}::CMD_SAVE anonymous_namespace{c_list.cc}::p2