gnucap: anonymous_namespace{lang_gschem.cc}::CMD_C Class Reference
anonymous_namespace{lang_gschem.cc}::CMD_C Class Reference
Private Member Functions
void do_it (CS &cmd, CARD_LIST *Scope)
Detailed Description
Definition at line 329 of file lang_gschem.cc.
Member Function Documentation
void anonymous_namespace{lang_gschem.cc}::CMD_C::do_it (CS & cmd, CARD_LIST * Scope) [inline, private, virtual]
Implements CMD.
Definition at line 330 of file lang_gschem.cc.
References CS::_STRING, CARD_LIST::is_empty(), anonymous_namespace{lang_gschem.cc}::lang_gschem, LANGUAGE::new__instance(), CARD::owner(), anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_module(), CARD_LIST::push_back(), CKT_BASE::short_label(), CARD::subckt(), and CS::tail().
    {
      MODEL_SUBCKT* new_compon = new MODEL_SUBCKT;
      assert(new_compon);
      assert(!new_compon->owner());
      assert(new_compon->subckt());
      assert(new_compon->subckt()->is_empty());
      lang_gschem.parse_module(cmd, new_compon);
      if(new_compon){
        Scope->push_back(new_compon);
        std::string s=new_compon->short_label()+" "+cmd.tail();
        CS cmd(CS::_STRING,s);
        lang_gschem.new__instance(cmd,NULL,Scope);
      }
    }
The documentation for this class was generated from the following file:
savant/gnucap/src/lang_gschem.cc