gnucap: OMSTREAM Class Reference
OMSTREAM Class Reference
#include <io_.h>
Public Member Functions
OMSTREAM (FILE *f=0)
OMSTREAM & operator= (const OMSTREAM &x)
OMSTREAM & attach (const OMSTREAM &x)
OMSTREAM & attach (FILE *f)
OMSTREAM & detach (const OMSTREAM &x)
OMSTREAM & detach (FILE *f)
OMSTREAM operator- (const OMSTREAM &y)
OMSTREAM operator+ (const OMSTREAM &y)
bool any () const
bool cipher () const
bool pack () const
int format () const
OMSTREAM & setcipher (bool x=true)
OMSTREAM & setpack (bool x=true)
OMSTREAM & setfloatwidth (int d, int w=0)
OMSTREAM & setformat (int f)
OMSTREAM & reset ()
OMSTREAM & tab (unsigned)
OMSTREAM & tab (int p)
OMSTREAM & form (const char *,...)
OMSTREAM & operator<< (char c)
OMSTREAM & operator<< (const char *s)
OMSTREAM & operator<< (double x)
OMSTREAM & operator<< (bool x)
OMSTREAM & operator<< (int x)
OMSTREAM & operator<< (unsigned x)
OMSTREAM & operator<< (const std::string &s)
Private Member Functions
OMSTREAM (int m)
Private Attributes
int _mask
int _fltdig
int _fltwid
int _format
bool _cipher
bool _pack
Static Private Attributes
static unsigned _cpos [MAXHANDLE+1]
Detailed Description
Definition at line 33 of file io_.h.
Constructor & Destructor Documentation
OMSTREAM::OMSTREAM (int m) [inline, private]
Definition at line 43 of file io_.h.
    :_mask(m),_fltdig(7),_fltwid(0),_format(0),_cipher(false),_pack(false) {}
OMSTREAM::OMSTREAM (FILE * f = 0) [inline, explicit]
Definition at line 46 of file io_.h.
    :_mask(0),_fltdig(7),_fltwid(0),_format(0),_cipher(false), _pack(false)
    {_mask = (f) ? 1<<fileno(f) : 0;}
Member Function Documentation
bool OMSTREAM::any () const [inline]
Definition at line 59 of file io_.h.
{return _mask != 0;}
OMSTREAM& OMSTREAM::attach (const OMSTREAM & x) [inline]
Definition at line 50 of file io_.h.
References _mask, and itested.
Referenced by anonymous_namespace{c_file.cc}::CMD_LOG::do_it(), anonymous_namespace{c_file.cc}::CMD_FILE::do_it(), and operator+().
{itested();_mask |= x._mask; return *this;}
OMSTREAM& OMSTREAM::attach (FILE * f) [inline]
Definition at line 51 of file io_.h.
References attach(), and itested.
Referenced by attach().
{itested();return attach(OMSTREAM(f));}
bool OMSTREAM::cipher () const [inline]
Definition at line 60 of file io_.h.
Referenced by initio(), and operator<<().
{return _cipher;}
OMSTREAM& OMSTREAM::detach (const OMSTREAM & x) [inline]
Definition at line 52 of file io_.h.
References _mask.
Referenced by anonymous_namespace{c_file.cc}::CMD_LOG::do_it(), anonymous_namespace{c_file.cc}::CMD_FILE::do_it(), and operator-().
{_mask &= ~(x._mask); return *this;}
OMSTREAM& OMSTREAM::detach (FILE * f) [inline]
Definition at line 53 of file io_.h.
References detach(), and itested.
Referenced by detach().
{itested();return detach(OMSTREAM(f));}
OMSTREAM & OMSTREAM::form (const char * fmt, ...)
Definition at line 78 of file io_out.cc.
References BIGBUFLEN.
Referenced by CMD::cmdproc(), anonymous_namespace{c_status.cc}::CMD_STATUS::do_it(), SIM::head(), PROBELIST::listing(), plotarg(), and TIMER::print().
{
  char buffer[BIGBUFLEN];
  va_list arg_ptr;
  va_start(arg_ptr,fmt);
  vsprintf(buffer,fmt,arg_ptr);
  va_end(arg_ptr);
  *this << buffer;
  return *this;
}
int OMSTREAM::format () const [inline]
Definition at line 62 of file io_.h.
{return _format;}
OMSTREAM OMSTREAM::operator+ (const OMSTREAM & y) [inline]
Definition at line 56 of file io_.h.
References attach().
{OMSTREAM x = *this; return x.attach(y);}
OMSTREAM OMSTREAM::operator- (const OMSTREAM & y) [inline]
Definition at line 55 of file io_.h.
References detach().
{OMSTREAM x = *this; return x.detach(y);}
OMSTREAM & OMSTREAM::operator<< (char c)
Definition at line 160 of file io_out.cc.
References _cpos, _mask, cipher(), error(), itested, MAXHANDLE, pack(), IO::stream, unreachable, and untested.
{
  if (_mask & 1) {
    unreachable();
    _mask &= ~1;
    error(bDANGER, "internal error: out to stdin\n");
  }else{
  }
  static int old = '\0';
  static int cchr = 'w';                /* starting encryption seed         */
                                        /* arbitrary printable character    */
  bool count;
  if (chr=='\t') {itested();
    chr = ' ';
    count = false;
  }else{
    count = true;
  }
  bool suppress = (pack() && old==' ' && chr==' ');
  old = chr;
  if (cipher() && !suppress && isprint(chr)) {untested();
    cchr += static_cast<int>(chr);
    while (!isascii(cchr)  ||  !isprint(cchr)) {untested();
      cchr -= (0x7f-0x20);
    }
    chr = static_cast<char>(cchr);
  }else{
  }
  for (int ii=0, mm=1;   ii<=MAXHANDLE;   ++ii, mm<<=1) {
    if (_mask & mm) {
      assert(IO::stream[ii]);
      if (chr=='\b') {untested();
        --_cpos[ii];
        fflush(IO::stream[ii]);
      }else if (count) {
        ++_cpos[ii];
      }else{itested();
      }
      if (chr=='\n') {
        _cpos[ii] = 0;
        fflush(IO::stream[ii]);
      }else if (chr=='\r') {itested();
        if (_cpos[ii] == 0) {untested();
          suppress = true;
        }else{itested();
          _cpos[ii] = 0;
          fflush(IO::stream[ii]);
        }
      }else{
      }
      if (!suppress) {
        fputc(chr,IO::stream[ii]);
      }else{itested();
      }
    }else{
    }
  }
  return *this;
}
OMSTREAM & OMSTREAM::operator<< (const char * s)
Definition at line 99 of file io_out.cc.
References _cpos, _mask, cipher(), error(), MAXHANDLE, OPT::outwidth, unreachable, and untested.
{
  assert(str);
  if (_mask & 1) {
    unreachable();
    _mask &= ~1;
    error(bDANGER, "internal error: out to stdin\n");
  }else{
  }
  bool newline = false; /* true if any destination is at beginning of line */
  size_t sl = strlen(str);
  /* kluge:  If a string ends with certain characters,
   * require some extra space following it, possibly forcing to next line.
   * Why? to avoid a line break between '=' and its argument.
   */
  if (sl == 0) {
  }else if (strchr("@", str[sl-1])) {
    sl += 16;
  }else if (strchr("=", str[sl-1])) {
    sl += 15;
  }else if (strchr("(", str[sl-1])) {
    sl += 12;
  }else{
  }
  /* auto line break, with a '+' to continue. */
  for (int ii=0, mm=1;   ii<=MAXHANDLE;   ++ii, mm<<=1) {
    if ((_mask & mm)
        && (sl+_cpos[ii]) >= OPT::outwidth
        && _cpos[ii] != 0) {
      OMSTREAM this_file(_mask & mm);
      this_file << '\n' << '+';
    }else{
    }                           /* see if it fits .... */
    if (_cpos[ii]==0) {         /* if not, next line   */
      newline = true;
    }else{
    }
  }
  if (cipher() && newline) {untested();
    *this << '\t';
  }else{
  }
  while (*str && (str[1] || *str != '@')) {
    *this << *str++;
  }
  return *this;
}
OMSTREAM& OMSTREAM::operator<< (double x) [inline]
Definition at line 75 of file io_.h.
References ftos().
    {return (*this)<<ftos(x,_fltwid,_fltdig,_format);}
OMSTREAM& OMSTREAM::operator<< (bool x) [inline]
Definition at line 77 of file io_.h.
{return form("%d", x);}
OMSTREAM& OMSTREAM::operator<< (int x) [inline]
Definition at line 78 of file io_.h.
{return form("%d", x);}
OMSTREAM& OMSTREAM::operator<< (unsigned x) [inline]
Definition at line 79 of file io_.h.
{return form("%u", x);}
OMSTREAM& OMSTREAM::operator<< (const std::string & s) [inline]
Definition at line 80 of file io_.h.
References operator<<().
Referenced by operator<<().
{return operator<<(s.c_str());}
OMSTREAM& OMSTREAM::operator= (const OMSTREAM & x) [inline]
Definition at line 49 of file io_.h.
References _mask.
{_mask = x._mask; return *this;}
bool OMSTREAM::pack () const [inline]
Definition at line 61 of file io_.h.
Referenced by operator<<().
{return _pack;}
OMSTREAM& OMSTREAM::reset () [inline]
Definition at line 67 of file io_.h.
Referenced by TRANSIENT::options(), outreset(), anonymous_namespace{s_ac.cc}::AC::setup(), anonymous_namespace{s_dc.cc}::DC::setup(), and anonymous_namespace{s_dc.cc}::OP::setup().
    {_fltdig=7;_fltwid=0;_format=0; _cipher=_pack=false; return *this;}
OMSTREAM& OMSTREAM::setcipher (bool x = true) [inline]
Definition at line 63 of file io_.h.
References untested.
{untested(); _cipher=x; return *this;}
OMSTREAM& OMSTREAM::setfloatwidth (int d, int w = 0) [inline]
Definition at line 65 of file io_.h.
Referenced by SIM::alarm(), anonymous_namespace{c_genrat.cc}::CMD_::do_it(), PROBELIST::listing(), OPT::print(), SIM::print_results(), and anonymous_namespace{c_modify.cc}::sweep_fix().
{_fltdig=d; _fltwid=w; return *this;}
OMSTREAM& OMSTREAM::setformat (int f) [inline]
Definition at line 66 of file io_.h.
{_format=f; return *this;}
OMSTREAM& OMSTREAM::setpack (bool x = true) [inline]
Definition at line 64 of file io_.h.
References itested.
{itested(); _pack=x;   return *this;}
OMSTREAM & OMSTREAM::tab (unsigned count)
Definition at line 57 of file io_out.cc.
References _cpos, _mask, and MAXHANDLE.
Referenced by calibrate(), plborder(), and CS::warn().
{
  for (int ii=0, mm=1;   ii<=MAXHANDLE;   ++ii, mm<<=1) {
    if (_mask & mm) {
      OMSTREAM this_file(_mask & mm);
      if (_cpos[ii] > count) {
        this_file << '\n';
      }else{
      }
      while (_cpos[ii]<count) {
        this_file << ' ';
      }
    }else{
    }
  }
  return *this;
}
OMSTREAM& OMSTREAM::tab (int p) [inline]
Definition at line 71 of file io_.h.
References tab().
Referenced by tab().
{return tab(static_cast<unsigned>(p));}
Member Data Documentation
bool OMSTREAM::_cipher [private]
Definition at line 40 of file io_.h.
unsigned OMSTREAM::_cpos [static, private]
Definition at line 39 of file io_.h.
Referenced by operator<<(), and tab().
int OMSTREAM::_fltdig [private]
Definition at line 36 of file io_.h.
int OMSTREAM::_fltwid [private]
Definition at line 37 of file io_.h.
int OMSTREAM::_format [private]
Definition at line 38 of file io_.h.
int OMSTREAM::_mask [private]
Definition at line 35 of file io_.h.
Referenced by attach(), detach(), operator<<(), operator=(), and tab().
bool OMSTREAM::_pack [private]
Definition at line 41 of file io_.h.
The documentation for this class was generated from the following files:
savant/gnucap/src/io_.h
savant/gnucap/src/io_out.cc