gnucap: anonymous_namespace{c_file.cc}::CMD_INCLUDE Class Reference
anonymous_namespace{c_file.cc}::CMD_INCLUDE Class Reference
Public Member Functions
void do_it (CS &cmd, CARD_LIST *Scope)
Detailed Description
Definition at line 37 of file c_file.cc.
Member Function Documentation
void anonymous_namespace{c_file.cc}::CMD_INCLUDE::do_it (CS & cmd, CARD_LIST * Scope) [inline, virtual]
Implements CMD.
Definition at line 39 of file c_file.cc.
References CS::_INC_FILE, CS::cursor(), OPT::language, LANGUAGE::parse_top_item(), and CS::warn().
  {
    unsigned here = cmd.cursor();
    try {
      std::string file_name;
      cmd >> file_name;
      CS file(CS::_INC_FILE, file_name);
      for (;;) {
        OPT::language->parse_top_item(file, Scope);
      }
    }catch (Exception_File_Open& e) {
      cmd.warn(bDANGER, here, e.message() + '\n');
    }catch (Exception_End_Of_Input& e) {
      // done
    }
  }
The documentation for this class was generated from the following file:
savant/gnucap/src/c_file.cc