gnucap: savant/gnucap/src/constant.h File Reference
savant/gnucap/src/constant.h File Reference
#include "md.h"
Enumerations
enum { FILE_OK = 0, FILE_BAD = -1 }
Variables
double const M_TWO_PI = M_PI * 2
double const DTOR = M_PI / 180
double const RTOD = 180 / M_PI
double const P_Q = 1.6021918e-19
double const P_C = 2.99792458e8
double const P_K = 1.3806226e-23
double const P_H = 6.6260693e-34
double const P_U0 = M_PI * 4.0e-7
double const P_EPS0 = 8.854214871e-12
double const P_CELSIUS0 = 273.15
double const P_EPS_SI = 11.7*P_EPS0
double const P_EPS_OX = 3.9*P_EPS0
double const P_K_Q = P_K/P_Q
double const CM2M = 1e-2
double const CM2M2 = 1e-4
double const ICM2M = 1e2
double const ICM2M2 = 1e4
double const ICM2M3 = 1e6
double const MICRON2METER = 1e-6
double const MAXDBL = DBL_MAX
double const BIGBIG = (MAXDBL)*(.9247958)
double const NEVER = (MAXDBL)*(.9447958)
double const NOT_INPUT = -(MAXDBL)*(.9547658)
double const NOT_VALID = -(MAXDBL)*(.9647958)
double const LINEAR = -(MAXDBL)*(.9747958)
double const LOGBIGBIG = log(BIGBIG)
double const VOLTMIN = 1.0e-50
double const PWRMIN = 1.0e-100
const char TOKENTERM [] = ",=()[]"
Enumeration Type Documentation
anonymous enum
Enumerator:
FILE_OK
FILE_BAD
Definition at line 107 of file constant.h.
{FILE_OK=0, FILE_BAD=-1};
Variable Documentation
double const BIGBIG = (MAXDBL)*(.9247958)
Definition at line 93 of file constant.h.
Referenced by anonymous_namespace{measure_at.cc}::MEASURE::eval(), anonymous_namespace{measure_integral.cc}::MEASURE::eval(), anonymous_namespace{measure_max.cc}::MEASURE::eval(), anonymous_namespace{measure_min.cc}::MEASURE::eval(), anonymous_namespace{measure_rms.cc}::MEASURE::eval(), anonymous_namespace{measure_average.cc}::MEASURE::eval(), anonymous_namespace{measure_cross.cc}::MEASURE::eval(), anonymous_namespace{measure_slewrate.cc}::MEASURE::eval(), anonymous_namespace{measure_eval.cc}::MEASURE::eval(), ftos(), interpolate(), SIM_DATA::new_event(), TRANSIENT::options(), MODEL_TABLE::precalc_first(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::precalc_last(), anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT::precalc_last(), EVAL_BM_SEMI_RESISTOR::precalc_last(), anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE::tr_eval(), COMPONENT::tr_probe_num(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::tr_review(), anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP::tr_review(), and anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE::tr_review().
double const CM2M = 1e-2
Definition at line 80 of file constant.h.
double const CM2M2 = 1e-4
Definition at line 81 of file constant.h.
double const DTOR = M_PI / 180
Definition at line 54 of file constant.h.
Referenced by EVAL_BM_ACTION_BASE::ac_final_adjust(), and gen().
double const ICM2M = 1e2
Definition at line 82 of file constant.h.
double const ICM2M2 = 1e4
Definition at line 83 of file constant.h.
double const ICM2M3 = 1e6
Definition at line 84 of file constant.h.
double const LINEAR = -(MAXDBL)*(.9747958)
Definition at line 98 of file constant.h.
Referenced by FPOLY1::c0(), anonymous_namespace{d_vcvs.cc}::DEV_VCVS::do_tr(), anonymous_namespace{d_res.cc}::DEV_RESISTANCE::do_tr(), anonymous_namespace{d_vcr.cc}::DEV_VCR::do_tr(), anonymous_namespace{d_vcg.cc}::DEV_VCG::do_tr(), anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE::do_tr(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::do_tr(), anonymous_namespace{d_cccs.cc}::DEV_CCCS::do_tr_last(), anonymous_namespace{d_ccvs.cc}::DEV_CCVS::do_tr_last(), ELEMENT::precalc_last(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::precalc_last(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_advance(), ELEMENT::tr_begin(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_begin(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_begin(), ELEMENT::tr_probe_num(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_regress(), and ELEMENT::tr_review().
double const LOGBIGBIG = log(BIGBIG)
Definition at line 100 of file constant.h.
Referenced by anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::tr_eval().
double const M_TWO_PI = M_PI * 2
Definition at line 35 of file constant.h.
Referenced by fft(), gen(), anonymous_namespace{s_ac.cc}::AC::sweep(), anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM::tr_eval(), anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::tr_eval(), and anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM::tr_review().
double const MAXDBL = DBL_MAX
Definition at line 90 of file constant.h.
Referenced by ELEMENT::ac_probe_ext(), and ELEMENT::tr_probe_num().
double const MICRON2METER = 1e-6
Definition at line 85 of file constant.h.
double const NEVER = (MAXDBL)*(.9447958)
Definition at line 95 of file constant.h.
Referenced by LOGIC_NODE::force_initial_value(), LOGIC_NODE::in_transit(), TRANSIENT::next(), LOGIC_NODE::propagate(), TIME_PAIR::reset(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::tr_review(), anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP::tr_review(), anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM::tr_review(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_review(), CARD::tr_review(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_review(), COMMON_COMPONENT::tr_review(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_review(), DEV_SPICE::tr_review(), ELEMENT::tr_review_check_and_convert(), and ELEMENT::tr_review_trunc_error().
double const NOT_INPUT = -(MAXDBL)*(.9547658)
Definition at line 96 of file constant.h.
Referenced by EVAL_BM_ACTION_BASE::ac_final_adjust(), SPLINE::construct_order_1(), SPLINE::construct_order_2(), SPLINE::construct_order_3(), anonymous_namespace{c_comand.cc}::CMD_TEMP::do_it(), Float::dump(), PARAMETER< T >::e_val(), anonymous_namespace{func_core.cc}::abs::eval(), anonymous_namespace{func_core.cc}::sqrt::eval(), anonymous_namespace{func_core.cc}::log::eval(), anonymous_namespace{func_core.cc}::exp::eval(), anonymous_namespace{func_core.cc}::INT::eval(), anonymous_namespace{func_core.cc}::pow::eval(), anonymous_namespace{func_core.cc}::MAX::eval(), anonymous_namespace{func_core.cc}::MIN::eval(), anonymous_namespace{func_core.cc}::IF::eval(), anonymous_namespace{func_core.cc}::sin::eval(), Expression::eval(), anonymous_namespace{func_core.cc}::sinh::eval(), anonymous_namespace{func_core.cc}::cos::eval(), anonymous_namespace{func_core.cc}::cosh::eval(), anonymous_namespace{func_core.cc}::tan::eval(), anonymous_namespace{func_core.cc}::tanh::eval(), anonymous_namespace{func_core.cc}::na::eval(), anonymous_namespace{func_core.cc}::RANDOM_STUB::eval(), PARAM_LIST::eval_copy(), ftos(), PARAMETER< bool >::has_good_value(), interpolate(), Float::is_NA(), PARAMETER< T >::lookup_solve(), PARAMETER< bool >::operator==(), Float::parse(), MODEL_TABLE::precalc_first(), COMMON_SUBCKT::precalc_first(), anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT::precalc_last(), anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::precalc_last(), EVAL_BM_SEMI_CAPACITOR::precalc_last(), EVAL_BM_SEMI_RESISTOR::precalc_last(), TRANSIENT::setup(), Token_SYMBOL::stack_op(), and anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::tr_eval().
double const NOT_VALID = -(MAXDBL)*(.9647958)
Definition at line 97 of file constant.h.
Referenced by anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::ac_amps(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::ac_amps(), DEV_SPICE::ac_amps(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::ac_involts(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::ac_involts(), DEV_SPICE::ac_involts(), CKT_BASE::ac_probe_ext(), DEV_SPICE::ac_probe_ext(), CKTterr(), SPLINE::construct_order_3(), D1i2F1(), D1i2F12(), D1i3F1(), D1iF12(), D1n2F1(), D1n2F12(), D1n3F1(), D1nF12(), ELEMENT::dc_advance(), DFi2F1(), DFi2F12(), DFi3F1(), DFiF12(), DFn2F1(), DFn2F12(), DFn3F1(), DFnF12(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_tr(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::do_tr_last(), ftos(), interpolate(), DEV_SPICE::localize_ckt(), COMPONENT::mfactor(), NIintegrate(), Nintegrate(), XPROBE::operator()(), anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR::parse_numlist(), anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX::parse_numlist(), anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::parse_numlist(), anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP::parse_numlist(), anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE::parse_numlist(), anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM::parse_numlist(), anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::parse_numlist(), EVAL_BM_VALUE::parse_numlist(), phase(), plotarg(), plottr(), SIM::print_results(), PROBE::probe_node(), SPLINE::SPLINE(), LOGIC_NODE::to_analog(), DEV_SPICE::tr_amps(), ELEMENT::tr_begin(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::tr_involts(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::tr_involts(), DEV_SPICE::tr_involts(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::tr_involts_limited(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::tr_involts_limited(), DEV_SPICE::tr_involts_limited(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_load(), CKT_BASE::tr_probe_num(), COMPONENT::tr_probe_num(), and DEV_SPICE::update_ckt().
double const P_C = 2.99792458e8
Definition at line 60 of file constant.h.
double const P_CELSIUS0 = 273.15
Definition at line 68 of file constant.h.
double const P_EPS0 = 8.854214871e-12
Definition at line 65 of file constant.h.
double const P_EPS_OX = 3.9*P_EPS0
Definition at line 72 of file constant.h.
double const P_EPS_SI = 11.7*P_EPS0
Definition at line 71 of file constant.h.
double const P_H = 6.6260693e-34
Definition at line 63 of file constant.h.
double const P_K = 1.3806226e-23
Definition at line 61 of file constant.h.
double const P_K_Q = P_K/P_Q
Definition at line 73 of file constant.h.
double const P_Q = 1.6021918e-19
Definition at line 58 of file constant.h.
double const P_U0 = M_PI * 4.0e-7
Definition at line 64 of file constant.h.
double const PWRMIN = 1.0e-100
Definition at line 103 of file constant.h.
double const RTOD = 180 / M_PI
Definition at line 55 of file constant.h.
Referenced by phase().
const char TOKENTERM[] = ",=()[]"
Definition at line 105 of file constant.h.
Referenced by PROBELIST::add_list(), findbranch(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_logic_using_obsolete_callback(), COMMON_COMPONENT::parse_modelname(), and PROBELIST::remove_list().
double const VOLTMIN = 1.0e-50
Definition at line 102 of file constant.h.
Referenced by anonymous_namespace{s_fo.cc}::db(), and XPROBE::operator()().