gnucap: ELEMENT Class Reference
ELEMENT Class Reference
#include <e_elemnt.h>
Public Member Functions
double * set__value ()
bool skip_dev_type (CS &)
bool print_type_in_spice () const
void precalc_last ()
void tr_begin ()
void tr_restore ()
void dc_advance ()
void tr_advance ()
void tr_regress ()
bool tr_needs_eval () const
TIME_PAIR tr_review ()
void tr_iwant_matrix ()=0
void ac_iwant_matrix ()=0
double tr_probe_num (const std::string &) const
XPROBE ac_probe_ext (const std::string &) const
double tr_review_trunc_error (const FPOLY1 *q)
double tr_review_check_and_convert (double timestep)
double tr_outvolts () const
double tr_outvolts_limited () const
COMPLEX ac_outvolts () const
virtual double tr_involts () const =0
virtual double tr_input () const
virtual double tr_involts_limited () const =0
virtual double tr_input_limited () const
virtual double tr_amps () const
virtual COMPLEX ac_involts () const =0
virtual COMPLEX ac_amps () const
virtual int order () const
virtual double error_factor () const
int param_count () const
Public Attributes
CPOLY1 _m0
CPOLY1 _m1
double _loss0
double _loss1
COMPLEX _acg
COMPLEX _ev
double _dt
double _time [OPT::_keep_time_steps]
FPOLY1 _y1
FPOLY1 _y [OPT::_keep_time_steps]
Protected Member Functions
ELEMENT ()
ELEMENT (const ELEMENT &p)
~ELEMENT ()
void store_values ()
double dampdiff (double *, const double &)
void tr_load_inode ()
void tr_unload_inode ()
void ac_load_inode ()
void tr_load_shunt ()
void tr_unload_shunt ()
void ac_load_shunt ()
void tr_load_source ()
void tr_unload_source ()
void ac_load_source ()
void tr_load_couple ()
void tr_unload_couple ()
void ac_load_couple ()
void tr_load_passive ()
void tr_unload_passive ()
void ac_load_passive ()
void tr_load_active ()
void tr_unload_active ()
void ac_load_active ()
void tr_load_extended (const node_t &no1, const node_t &no2, const node_t &ni1, const node_t &ni2, double *value, double *old_value)
void ac_load_extended (const node_t &no1, const node_t &no2, const node_t &ni1, const node_t &ni2, COMPLEX value)
void tr_load_source_point (node_t &no1, double *value, double *old_value)
void ac_load_source_point (node_t &no1, COMPLEX new_value)
void tr_load_diagonal_point (const node_t &no1, double *value, double *old_value)
void ac_load_diagonal_point (const node_t &no1, COMPLEX value)
void tr_load_point (const node_t &no1, const node_t &no2, double *value, double *old_value)
void ac_load_point (const node_t &no1, const node_t &no2, COMPLEX value)
bool conv_check () const
bool has_tr_eval () const
bool has_ac_eval () const
bool using_tr_eval () const
bool using_ac_eval () const
void tr_eval ()
void ac_eval ()
void tr_iwant_matrix_passive ()
void tr_iwant_matrix_active ()
void tr_iwant_matrix_extended ()
void ac_iwant_matrix_passive ()
void ac_iwant_matrix_active ()
void ac_iwant_matrix_extended ()
Protected Attributes
int _loaditer
Private Attributes
node_t _nodes [NODES_PER_BRANCH]
Detailed Description
Definition at line 32 of file e_elemnt.h.
Constructor & Destructor Documentation
ELEMENT::ELEMENT () [explicit, protected]
Definition at line 30 of file e_elemnt.cc.
References OPT::_keep_time_steps, CARD::_n, _nodes, _time, _y, and _y1.
  :COMPONENT(),
   _loaditer(0),
   _m0(),
   _m1(),
   _loss0(0.),
   _loss1(0.),
   _acg(0.),
   _ev(0.),
   _dt(0.)
{
  _n = _nodes;
  assert(_y[0].x == 0. && _y[0].f0 == 0. && _y[0].f1 == 0.);
  assert(_y1 == _y[0]);
  std::fill_n(_time, int(OPT::_keep_time_steps), 0.);
}
ELEMENT::ELEMENT (const ELEMENT & p) [explicit, protected]
Definition at line 48 of file e_elemnt.cc.
References OPT::_keep_time_steps, CARD::_n, _nodes, _time, _y, _y1, notstd::copy_n(), CARD::long_label(), NODES_PER_BRANCH, and trace0.
  :COMPONENT(p),
   _loaditer(0),
   _m0(),
   _m1(),
   _loss0(p._loss0),
   _loss1(p._loss1),
   _acg(0.),
   _ev(0.),
   _dt(0.)
{
  trace0(long_label().c_str());
  _n = _nodes;
  if (p._n == p._nodes) {
    for (int ii = 0;  ii < NODES_PER_BRANCH;  ++ii) {
      _n[ii] = p._n[ii];
    }
  }else{
    assert(p._nodes);
    // the constructor for a derived class will take care of it
  }
  assert(_y[0].x == 0. && _y[0].f0 == 0. && _y[0].f1 == 0.);
  assert(_y1 == _y[0]);
  notstd::copy_n(p._time, int(OPT::_keep_time_steps), _time);
}
ELEMENT::~ELEMENT () [inline, protected]
Definition at line 36 of file e_elemnt.h.
{}
Member Function Documentation
COMPLEX ELEMENT::ac_amps () const [virtual]
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, DEV_LOGIC, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vs.cc}::DEV_VS, and anonymous_namespace{d_ccvs.cc}::DEV_CCVS.
Definition at line 349 of file e_elemnt.cc.
References _acg, _loss0, ac_involts(), ac_outvolts(), and COMPONENT::is_source().
Referenced by anonymous_namespace{d_ccvs.cc}::DEV_CCVS::ac_amps(), anonymous_namespace{d_vcr.cc}::DEV_VCR::ac_amps(), and ac_probe_ext().
{
  assert(!is_source());
  return (ac_involts() * _acg + ac_outvolts() * _loss0);
}
void ELEMENT::ac_eval () [inline, protected]
Definition at line 453 of file e_elemnt.h.
References _ev, _y, COMMON_COMPONENT::ac_eval(), COMPONENT::common(), FPOLY1::f1, and has_ac_eval().
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_ac().
{
  if (has_ac_eval()) {
    common()->ac_eval(this);
  }else{
    // can get here if a simple device has probes
    _ev = _y[0].f1;
  }
}
virtual COMPLEX ELEMENT::ac_involts () const [pure virtual]
Implemented in DEV_SPICE, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, and CCSRC_BASE.
Referenced by ac_amps(), and ac_probe_ext().
void ELEMENT::ac_iwant_matrix () [pure virtual]
Reimplemented from COMPONENT.
Implemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_cap.cc}::DEV_VCCAP, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_cccs.cc}::DEV_CCCS, and anonymous_namespace{d_ccvs.cc}::DEV_CCVS.
void ELEMENT::ac_iwant_matrix_active () [protected]
Definition at line 250 of file e_elemnt.cc.
References SIM_DATA::_acx, CARD::_n, CKT_BASE::_sim, IN1, IN2, BSMATRIX< T >::iwant(), OUT1, and OUT2.
{
  //_sim->_acx.iwant(_n[OUT1].m_(),_n[OUT2].m_());
  _sim->_acx.iwant(_n[OUT1].m_(),_n[IN1].m_());
  _sim->_acx.iwant(_n[OUT1].m_(),_n[IN2].m_());
  _sim->_acx.iwant(_n[OUT2].m_(),_n[IN1].m_());
  _sim->_acx.iwant(_n[OUT2].m_(),_n[IN2].m_());
  //_sim->_acx.iwant(_n[IN1].m_(),_n[IN2].m_());
}
void ELEMENT::ac_iwant_matrix_extended () [protected]
Definition at line 260 of file e_elemnt.cc.
References SIM_DATA::_acx, CARD::_n, CKT_BASE::_sim, COMPONENT::ext_nodes(), COMPONENT::int_nodes(), COMPONENT::is_device(), itested, BSMATRIX< T >::iwant(), COMPONENT::matrix_nodes(), and CARD::subckt().
Referenced by DEV_SPICE::ac_iwant_matrix().
{
  assert(is_device());
  assert(!subckt());
  assert(ext_nodes() + int_nodes() == matrix_nodes());
  for (int ii = 0;  ii < matrix_nodes();  ++ii) {
    if (_n[ii].m_() >= 0) {
      for (int jj = 0;  jj < ii ;  ++jj) {
        _sim->_acx.iwant(_n[ii].m_(),_n[jj].m_());
      }
    }else{itested();
      // node 1 is grounded or invalid
    }
  }
}
void ELEMENT::ac_iwant_matrix_passive () [protected]
Definition at line 244 of file e_elemnt.cc.
References SIM_DATA::_acx, CARD::_n, CKT_BASE::_sim, BSMATRIX< T >::iwant(), CARD::long_label(), OUT1, OUT2, and trace2.
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::ac_iwant_matrix().
{
  trace2(long_label().c_str(), _n[OUT1].m_(), _n[OUT2].m_());
  _sim->_acx.iwant(_n[OUT1].m_(),_n[OUT2].m_());
}
void ELEMENT::ac_load_active () [inline, protected]
Definition at line 334 of file e_elemnt.h.
References _acg, SIM_DATA::_acx, CARD::_n, CKT_BASE::_sim, IN1, IN2, BSMATRIX< T >::load_asymmetric(), COMPONENT::mfactor(), OUT1, and OUT2.
{
  _sim->_acx.load_asymmetric(_n[OUT1].m_(), _n[OUT2].m_(),
                      _n[IN1].m_(), _n[IN2].m_(), mfactor() * _acg);
}
void ELEMENT::ac_load_couple () [inline, protected]
Definition at line 289 of file e_elemnt.h.
References _acg, SIM_DATA::_acx, CARD::_n, CKT_BASE::_sim, BSMATRIX< T >::load_couple(), COMPONENT::mfactor(), OUT1, and OUT2.
Referenced by anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::ac_load().
{
  _sim->_acx.load_couple(_n[OUT1].m_(), _n[OUT2].m_(), mfactor() * _acg);
}
void ELEMENT::ac_load_diagonal_point (const node_t & no1, COMPLEX value) [inline, protected]
Definition at line 392 of file e_elemnt.h.
References SIM_DATA::_acx, CKT_BASE::_sim, BSMATRIX< T >::load_diagonal_point(), node_t::m_(), and COMPONENT::mfactor().
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::ac_load().
{
  _sim->_acx.load_diagonal_point(no1.m_(), mfactor() * new_value);
}
void ELEMENT::ac_load_extended (const node_t & no1, const node_t & no2, const node_t & ni1, const node_t & ni2, COMPLEX value) [inline, protected]
Definition at line 352 of file e_elemnt.h.
References SIM_DATA::_acx, CKT_BASE::_sim, BSMATRIX< T >::load_asymmetric(), node_t::m_(), and COMPONENT::mfactor().
Referenced by anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::ac_load(), and anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::ac_load().
{
  _sim->_acx.load_asymmetric(no1.m_(), no2.m_(), ni1.m_(), ni2.m_(), mfactor() * new_value);
}
void ELEMENT::ac_load_inode () [inline, protected]
Definition at line 203 of file e_elemnt.h.
References SIM_DATA::_acx, _loss0, CARD::_n, CKT_BASE::_sim, IN1, BSMATRIX< T >::load_couple(), COMPONENT::mfactor(), OUT1, and OUT2.
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::ac_load().
{
  _sim->_acx.load_couple(_n[OUT1].m_(), _n[IN1].m_(), -mfactor() * _loss0);
  _sim->_acx.load_couple(_n[OUT2].m_(), _n[IN1].m_(),  mfactor() * _loss0);
}
void ELEMENT::ac_load_passive () [inline, protected]
Definition at line 311 of file e_elemnt.h.
References _acg, SIM_DATA::_acx, CARD::_n, CKT_BASE::_sim, BSMATRIX< T >::load_symmetric(), COMPONENT::mfactor(), OUT1, and OUT2.
Referenced by anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::ac_load(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::ac_load(), and anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::ac_load().
{
  _sim->_acx.load_symmetric(_n[OUT1].m_(), _n[OUT2].m_(), mfactor() * _acg);
}
void ELEMENT::ac_load_point (const node_t & no1, const node_t & no2, COMPLEX value) [inline, protected]
Definition at line 408 of file e_elemnt.h.
References SIM_DATA::_acx, CKT_BASE::_sim, itested, BSMATRIX< T >::load_point(), node_t::m_(), and COMPONENT::mfactor().
Referenced by DEV_SPICE::ac_load().
{itested();
  _sim->_acx.load_point(no1.m_(), no2.m_(), mfactor() * new_value);
}
void ELEMENT::ac_load_shunt () [inline, protected]
Definition at line 226 of file e_elemnt.h.
References SIM_DATA::_acx, _loss0, CARD::_n, CKT_BASE::_sim, BSMATRIX< T >::load_symmetric(), COMPONENT::mfactor(), OUT1, and OUT2.
{
  _sim->_acx.load_symmetric(_n[OUT1].m_(), _n[OUT2].m_(), mfactor() * _loss0);
}
void ELEMENT::ac_load_source () [inline, protected]
Definition at line 260 of file e_elemnt.h.
References _acg, CARD::_n, NODE::iac(), itested, COMPONENT::mfactor(), OUT1, and OUT2.
{
  if (_n[OUT2].m_() != 0) {
    _n[OUT2]->iac() += mfactor() * _acg;
  }else{
  }
  if (_n[OUT1].m_() != 0) {
    _n[OUT1]->iac() -= mfactor() * _acg;
  }else{itested();
  }
}
void ELEMENT::ac_load_source_point (node_t & no1, COMPLEX new_value) [inline, protected]
Definition at line 373 of file e_elemnt.h.
References NODE::iac(), itested, node_t::m_(), and COMPONENT::mfactor().
Referenced by DEV_SPICE::ac_load().
{itested();
  if (no1.m_() != 0) {itested();
    no1->iac() += mfactor() * new_value;
  }else{itested();
  }
}
COMPLEX ELEMENT::ac_outvolts () const [inline]
Definition at line 136 of file e_elemnt.h.
References OUT1, and OUT2.
Referenced by ac_amps(), and ac_probe_ext().
{return _n[OUT1]->vac() - _n[OUT2]->vac();}
XPROBE ELEMENT::ac_probe_ext (const std::string & x) const [virtual]
Reimplemented from CKT_BASE.
Reimplemented in DEV_SPICE, and DEV_LOGIC.
Definition at line 355 of file e_elemnt.cc.
References _acg, SIM_DATA::_acx, _ev, _loss0, CARD::_n, CKT_BASE::_sim, ac_amps(), ac_involts(), ac_outvolts(), COMPONENT::is_source(), MAXDBL, COMPONENT::mfactor(), mtREAL, OUT1, OUT2, port_impedance(), Umatch(), untested, and COMPONENT::value().
{
  COMPLEX admittance = (is_source()) ? _loss0 : _acg+_loss0;
  if (Umatch(x, "v{out} ")) {                   /* volts (out) */
    return XPROBE(ac_outvolts());
  }else if (Umatch(x, "vin ")) {                /* volts (in) */
    return XPROBE(ac_involts());
  }else if (Umatch(x, "i ")) {                  /* amps */
    return XPROBE(ac_amps());
  }else if (Umatch(x, "p ")) {                  /* complex "power" */
    return XPROBE(ac_outvolts() * conj(ac_amps()), mtREAL, 10.);
  }else if (Umatch(x, "nv ")) {untested();      /* nominal value */
    return XPROBE(value());
  }else if (Umatch(x, "ev ")) {                 /* effective value */
    return XPROBE(_ev);
  }else if (Umatch(x, "y ")) {untested();               /* admittance */
    return XPROBE(admittance, mtREAL);
  }else if (Umatch(x, "r ")) {                  /* complex "resistance" */
    if (admittance == 0.) {untested();
      return XPROBE(MAXDBL);
    }else{untested();
      return XPROBE(1. / admittance);
    }
  }else if (Umatch(x, "z ")) {                  /* port impedance */
    return XPROBE(port_impedance(_n[OUT1], _n[OUT2], _sim->_acx, mfactor()*admittance));
  }else if (Umatch(x, "zraw ")) {               /* port impedance, raw */
    return XPROBE(port_impedance(_n[OUT1], _n[OUT2], _sim->_acx, COMPLEX(0.)));
  }else{                                        /* bad parameter */
    return COMPONENT::ac_probe_ext(x);
  }
}
bool ELEMENT::conv_check () const [inline, protected]
Definition at line 414 of file e_elemnt.h.
References _y, _y1, conchk(), FPOLY1::f0, FPOLY1::f1, OPT::vntol, and FPOLY1::x.
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_tr(), tr_eval(), and DEV_LOGIC::tr_eval_digital().
{
  return conchk(_y1.f1, _y[0].f1)
    && conchk(_y1.f0, _y[0].f0)
    && conchk(_y1.x,  _y[0].x, OPT::vntol);
}
double ELEMENT::dampdiff (double * v0, const double & v1) [inline, protected]
Definition at line 169 of file e_elemnt.h.
References SIM_DATA::_damp, CKT_BASE::_sim, dn_diff(), SIM_DATA::is_advance_or_first_iteration(), SIM_DATA::is_inc_mode(), and COMPONENT::mfactor().
Referenced by tr_load_active(), tr_load_couple(), tr_load_diagonal_point(), tr_load_extended(), tr_load_inode(), tr_load_passive(), tr_load_point(), tr_load_shunt(), tr_load_source(), and tr_load_source_point().
{
  //double diff = v0 - v1;
  assert(v0);
  assert(*v0 == *v0);
  assert(v1 == v1);
  double diff = dn_diff(*v0, v1);
  assert(diff == diff);
  if (!_sim->is_advance_or_first_iteration()) {
    diff *= _sim->_damp;
    *v0 = v1 + diff;
  }else{
  }
  return mfactor() * ((_sim->is_inc_mode()) ? diff : *v0);
}
void ELEMENT::dc_advance () [virtual]
Reimplemented from CARD.
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, and STORAGE.
Definition at line 136 of file e_elemnt.cc.
References _dt, OPT::_keep_time_steps, CKT_BASE::_sim, _time, SIM_DATA::_time0, and NOT_VALID.
{
  assert(_sim->_time0 == 0.); // DC
  for (int i=OPT::_keep_time_steps-1; i>=0; --i) {
    assert(_time[i] == 0.);
  }
  _dt = NOT_VALID;
}
virtual double ELEMENT::error_factor () const [inline, virtual]
Reimplemented in STORAGE.
Definition at line 147 of file e_elemnt.h.
References OPT::trstepcoef, and OPT::trsteporder.
Referenced by tr_review_trunc_error().
{return OPT::trstepcoef[OPT::trsteporder];}
bool ELEMENT::has_ac_eval () const [inline, protected]
Definition at line 426 of file e_elemnt.h.
References COMPONENT::common(), and COMPONENT::has_common().
Referenced by ac_eval(), and using_ac_eval().
{
  return (has_common() && common()->has_ac_eval());
}
bool ELEMENT::has_tr_eval () const [inline, protected]
Definition at line 421 of file e_elemnt.h.
References COMPONENT::common(), and COMPONENT::has_common().
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_ac(), tr_eval(), and using_tr_eval().
{
  return (has_common() && common()->has_tr_eval());
}
virtual int ELEMENT::order () const [inline, virtual]
Reimplemented in STORAGE.
Definition at line 146 of file e_elemnt.h.
References OPT::trsteporder.
Referenced by tr_review(), tr_review_check_and_convert(), and tr_review_trunc_error().
{return OPT::trsteporder;}
int ELEMENT::param_count () const [inline, virtual]
Reimplemented from COMPONENT.
Definition at line 148 of file e_elemnt.h.
References COMPONENT::param_count().
{return (0 + COMPONENT::param_count());}
void ELEMENT::precalc_last () [virtual]
Reimplemented from COMPONENT.
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, STORAGE, anonymous_namespace{d_cccs.cc}::DEV_CCCS, and anonymous_namespace{d_ccvs.cc}::DEV_CCVS.
Definition at line 80 of file e_elemnt.cc.
References CKT_BASE::_sim, _y, FPOLY1::f0, FPOLY1::f1, SIM_DATA::is_first_expand(), LINEAR, COMPONENT::value(), and FPOLY1::x.
Referenced by anonymous_namespace{s_dc.cc}::DCOP::finish(), anonymous_namespace{d_cccs.cc}::DEV_CCCS::precalc_last(), anonymous_namespace{d_ccvs.cc}::DEV_CCVS::precalc_last(), anonymous_namespace{d_vcvs.cc}::DEV_VCVS::precalc_last(), anonymous_namespace{d_res.cc}::DEV_RESISTANCE::precalc_last(), anonymous_namespace{d_vcr.cc}::DEV_VCR::precalc_last(), anonymous_namespace{d_vs.cc}::DEV_VS::precalc_last(), anonymous_namespace{d_cs.cc}::DEV_CS::precalc_last(), and anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE::precalc_last().
{
  COMPONENT::precalc_last();
  //BUG// This is needed for AC analysis without doing op (or dc or tran ...) first.
  // Something like it should be moved to ac_begin.
  if (_sim->is_first_expand()) {
    _y[0].x  = 0.;
    _y[0].f0 = LINEAR;
    _y[0].f1 = value();
  }else{
  }
}
bool ELEMENT::print_type_in_spice () const [inline, virtual]
Implements COMPONENT.
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_switch.cc}::SWITCH_BASE, and DEV_LOGIC.
Definition at line 45 of file e_elemnt.h.
{return false;}
double* ELEMENT::set__value () [inline]
Definition at line 41 of file e_elemnt.h.
Referenced by anonymous_namespace{s_dc.cc}::DC::setup().
{return _value.pointer_hack();}
bool ELEMENT::skip_dev_type (CS & cmd)
Definition at line 75 of file e_elemnt.cc.
References CARD::dev_type(), and CS::umatch().
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_element_using_obsolete_callback().
{
  return cmd.umatch(dev_type() + ' ');
}
void ELEMENT::store_values () [inline, protected]
Definition at line 38 of file e_elemnt.h.
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_tr(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::do_tr(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::do_tr_last(), and DEV_LOGIC::tr_eval_digital().
{assert(_y[0]==_y[0]); _y1=_y[0];}
void ELEMENT::tr_advance () [virtual]
Reimplemented from CARD.
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, and STORAGE.
Definition at line 147 of file e_elemnt.cc.
References _dt, OPT::_keep_time_steps, CKT_BASE::_sim, _time, SIM_DATA::_time0, and _y.
{
  assert(_time[0] < _sim->_time0); // moving forward
  for (int i=OPT::_keep_time_steps-1; i>0; --i) {
    assert(_time[i] < _time[i-1] || _time[i] == 0.);
    _time[i] = _time[i-1];
    _y[i] = _y[i-1];
  }
  _time[0] = _sim->_time0;
  _dt = _time[0] - _time[1];
}
double ELEMENT::tr_amps () const [virtual]
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, and anonymous_namespace{d_vcr.cc}::DEV_VCR.
Definition at line 277 of file e_elemnt.cc.
References _loss0, _m0, CPOLY1::c0, CPOLY1::c1, fixzero(), tr_involts(), tr_outvolts(), and trace5.
Referenced by anonymous_namespace{d_vcr.cc}::DEV_VCR::tr_amps(), and tr_probe_num().
{
  trace5("", _loss0, tr_outvolts(), _m0.c1, tr_involts(), _m0.c0);
  return fixzero((_loss0 * tr_outvolts() + _m0.c1 * tr_involts() + _m0.c0),
                 _m0.c0);
}
void ELEMENT::tr_begin () [virtual]
Reimplemented from CARD.
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, STORAGE, anonymous_namespace{d_cccs.cc}::DEV_CCCS, and anonymous_namespace{d_ccvs.cc}::DEV_CCVS.
Definition at line 94 of file e_elemnt.cc.
References _dt, OPT::_keep_time_steps, _time, _y, _y1, FPOLY1::f0, FPOLY1::f1, LINEAR, NOT_VALID, COMPONENT::value(), and FPOLY1::x.
Referenced by anonymous_namespace{d_cccs.cc}::DEV_CCCS::tr_begin(), anonymous_namespace{d_ccvs.cc}::DEV_CCVS::tr_begin(), anonymous_namespace{d_vcvs.cc}::DEV_VCVS::tr_begin(), anonymous_namespace{d_res.cc}::DEV_RESISTANCE::tr_begin(), anonymous_namespace{d_vcr.cc}::DEV_VCR::tr_begin(), anonymous_namespace{d_cs.cc}::DEV_CS::tr_begin(), anonymous_namespace{d_vs.cc}::DEV_VS::tr_begin(), anonymous_namespace{d_vcg.cc}::DEV_VCG::tr_begin(), and anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE::tr_begin().
{
  _time[0] = 0.;
  _y[0].x  = 0.;
  _y[0].f0 = LINEAR;
  _y[0].f1 = value();
  _y1 = _y[0];
  for (int i=1; i<OPT::_keep_time_steps; ++i) {
    _time[i] = 0.;
    _y[i] = FPOLY1(0., 0., 0.);
  }
  _dt = NOT_VALID;
}
void ELEMENT::tr_eval () [inline, protected]
Definition at line 441 of file e_elemnt.h.
References _y, COMPONENT::common(), conv_check(), FPOLY1::f0, FPOLY1::f1, has_tr_eval(), COMPONENT::set_converged(), COMMON_COMPONENT::tr_eval(), COMPONENT::value(), and FPOLY1::x.
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_tr().
{
  if (has_tr_eval()) {
    common()->tr_eval(this);
  }else{
    // can get here if a simple device has probes
    _y[0].f1 = value();
    _y[0].f0 = _y[0].x * _y[0].f1;
  }
  set_converged(conv_check());
}
virtual double ELEMENT::tr_input () const [inline, virtual]
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, and CCSRC_BASE.
Definition at line 139 of file e_elemnt.h.
Referenced by STORAGE::tr_needs_eval().
{return tr_involts();}
virtual double ELEMENT::tr_input_limited () const [inline, virtual]
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, and CCSRC_BASE.
Definition at line 141 of file e_elemnt.h.
{return tr_involts_limited();}
virtual double ELEMENT::tr_involts () const [pure virtual]
Implemented in DEV_SPICE, anonymous_namespace{d_cap.cc}::DEV_VCCAP, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, and CCSRC_BASE.
Referenced by tr_amps(), and tr_probe_num().
virtual double ELEMENT::tr_involts_limited () const [pure virtual]
Implemented in DEV_SPICE, anonymous_namespace{d_cap.cc}::DEV_VCCAP, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_vcr.cc}::DEV_VCR, CCSRC_BASE, and anonymous_namespace{d_vcvs.cc}::DEV_VCVS.
void ELEMENT::tr_iwant_matrix () [pure virtual]
Reimplemented from COMPONENT.
Implemented in DEV_SPICE, anonymous_namespace{d_cap.cc}::DEV_VCCAP, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_cccs.cc}::DEV_CCCS, and anonymous_namespace{d_ccvs.cc}::DEV_CCVS.
void ELEMENT::tr_iwant_matrix_active () [protected]
Definition at line 200 of file e_elemnt.cc.
References SIM_DATA::_aa, SIM_DATA::_lu, CARD::_n, CKT_BASE::_sim, IN1, IN2, INVALID_NODE, COMPONENT::is_device(), BSMATRIX< T >::iwant(), COMPONENT::matrix_nodes(), OUT1, OUT2, and CARD::subckt().
{
  assert(matrix_nodes() == 4);
  assert(is_device());
  assert(!subckt());
  assert(_n[OUT1].m_() != INVALID_NODE);
  assert(_n[OUT2].m_() != INVALID_NODE);
  assert(_n[IN1].m_() != INVALID_NODE);
  assert(_n[IN2].m_() != INVALID_NODE);
  //_sim->_aa.iwant(_n[OUT1].m_(),_n[OUT2].m_());
  _sim->_aa.iwant(_n[OUT1].m_(),_n[IN1].m_());
  _sim->_aa.iwant(_n[OUT1].m_(),_n[IN2].m_());
  _sim->_aa.iwant(_n[OUT2].m_(),_n[IN1].m_());
  _sim->_aa.iwant(_n[OUT2].m_(),_n[IN2].m_());
  //_sim->_aa.iwant(_n[IN1].m_(),_n[IN2].m_());
  //_sim->_lu.iwant(_n[OUT1].m_(),_n[OUT2].m_());
  _sim->_lu.iwant(_n[OUT1].m_(),_n[IN1].m_());
  _sim->_lu.iwant(_n[OUT1].m_(),_n[IN2].m_());
  _sim->_lu.iwant(_n[OUT2].m_(),_n[IN1].m_());
  _sim->_lu.iwant(_n[OUT2].m_(),_n[IN2].m_());
  //_sim->_lu.iwant(_n[IN1].m_(),_n[IN2].m_());
}
void ELEMENT::tr_iwant_matrix_extended () [protected]
Definition at line 226 of file e_elemnt.cc.
References SIM_DATA::_aa, SIM_DATA::_lu, CARD::_n, CKT_BASE::_sim, COMPONENT::ext_nodes(), COMPONENT::int_nodes(), COMPONENT::is_device(), itested, BSMATRIX< T >::iwant(), COMPONENT::matrix_nodes(), and CARD::subckt().
Referenced by DEV_SPICE::tr_iwant_matrix().
{
  assert(is_device());
  assert(!subckt());
  assert(ext_nodes() + int_nodes() == matrix_nodes());
  for (int ii = 0;  ii < matrix_nodes();  ++ii) {
    if (_n[ii].m_() >= 0) {
      for (int jj = 0;  jj < ii ;  ++jj) {
        _sim->_aa.iwant(_n[ii].m_(),_n[jj].m_());
        _sim->_lu.iwant(_n[ii].m_(),_n[jj].m_());
      }
    }else{itested();
      // node 1 is grounded or invalid
    }
  }
}
void ELEMENT::tr_iwant_matrix_passive () [protected]
Definition at line 186 of file e_elemnt.cc.
References SIM_DATA::_aa, SIM_DATA::_lu, CARD::_n, CKT_BASE::_sim, INVALID_NODE, COMPONENT::is_device(), BSMATRIX< T >::iwant(), CARD::long_label(), COMPONENT::matrix_nodes(), OUT1, OUT2, and trace2.
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_iwant_matrix(), and DEV_LOGIC::tr_iwant_matrix().
{
  assert(matrix_nodes() == 2);
  assert(is_device());
  //assert(!subckt()); ok for subckt to exist for logic
  trace2(long_label().c_str(), _n[OUT1].m_(), _n[OUT2].m_());
  assert(_n[OUT1].m_() != INVALID_NODE);
  assert(_n[OUT2].m_() != INVALID_NODE);
  _sim->_aa.iwant(_n[OUT1].m_(),_n[OUT2].m_());
  _sim->_lu.iwant(_n[OUT1].m_(),_n[OUT2].m_());
}
void ELEMENT::tr_load_active () [inline, protected]
Definition at line 316 of file e_elemnt.h.
References SIM_DATA::_aa, _m0, _m1, CARD::_n, CKT_BASE::_sim, CPOLY1::c1, dampdiff(), IN1, IN2, BSMATRIX< T >::load_asymmetric(), OUT1, OUT2, and tr_load_source().
Referenced by tr_unload_active().
{
  double d = dampdiff(&_m0.c1, _m1.c1);
  if (d != 0.) {
    _sim->_aa.load_asymmetric(_n[OUT1].m_(), _n[OUT2].m_(),
                       _n[IN1].m_(), _n[IN2].m_(), d);
  }else{
  }
  tr_load_source(); // includes _m1 = _m0
}
void ELEMENT::tr_load_couple () [inline, protected]
Definition at line 272 of file e_elemnt.h.
References SIM_DATA::_aa, _m0, _m1, CARD::_n, CKT_BASE::_sim, CPOLY1::c1, dampdiff(), BSMATRIX< T >::load_couple(), OUT1, and OUT2.
Referenced by anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_load(), and tr_unload_couple().
{
  double d = dampdiff(&_m0.c1, _m1.c1);
  if (d != 0.) {
    _sim->_aa.load_couple(_n[OUT1].m_(), _n[OUT2].m_(), d);
  }else{
  }
  _m1.c1 = _m0.c1;
}
void ELEMENT::tr_load_diagonal_point (const node_t & no1, double * value, double * old_value) [inline, protected]
Definition at line 381 of file e_elemnt.h.
References SIM_DATA::_aa, CKT_BASE::_sim, dampdiff(), BSMATRIX< T >::load_diagonal_point(), and node_t::m_().
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_load().
{
  double d = dampdiff(new_value, *old_value);
  if (d != 0.) {
    _sim->_aa.load_diagonal_point(no1.m_(), d);
  }else{
  }
  *old_value = *new_value;
}
void ELEMENT::tr_load_extended (const node_t & no1, const node_t & no2, const node_t & ni1, const node_t & ni2, double * value, double * old_value) [inline, protected]
Definition at line 340 of file e_elemnt.h.
References SIM_DATA::_aa, CKT_BASE::_sim, dampdiff(), BSMATRIX< T >::load_asymmetric(), and node_t::m_().
Referenced by anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::tr_load(), and anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::tr_load().
{
  double d = dampdiff(new_value, *old_value);
  if (d != 0.) {
    _sim->_aa.load_asymmetric(no1.m_(), no2.m_(), ni1.m_(), ni2.m_(), d);
  }else{
  }
  *old_value = *new_value;
}
void ELEMENT::tr_load_inode () [inline, protected]
Definition at line 185 of file e_elemnt.h.
References SIM_DATA::_aa, _loss0, _loss1, CARD::_n, CKT_BASE::_sim, dampdiff(), IN1, BSMATRIX< T >::load_couple(), OUT1, and OUT2.
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_load(), and tr_unload_inode().
{
  double d = dampdiff(&_loss0, _loss1);
  if (d != 0.) {
    _sim->_aa.load_couple(_n[OUT1].m_(), _n[IN1].m_(), -d);
    _sim->_aa.load_couple(_n[OUT2].m_(), _n[IN1].m_(),  d);
  }else{
  }
  _loss1 = _loss0;
}
void ELEMENT::tr_load_passive () [inline, protected]
Definition at line 294 of file e_elemnt.h.
References SIM_DATA::_aa, _m0, _m1, CARD::_n, CKT_BASE::_sim, CPOLY1::c1, dampdiff(), BSMATRIX< T >::load_symmetric(), OUT1, OUT2, and tr_load_source().
Referenced by anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::tr_load(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_load(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::tr_load(), DEV_LOGIC::tr_load(), and tr_unload_passive().
{
  double d = dampdiff(&_m0.c1, _m1.c1);
  if (d != 0.) {
    _sim->_aa.load_symmetric(_n[OUT1].m_(), _n[OUT2].m_(), d);
  }else{
  }
  tr_load_source(); // includes _m1 = _m0
}
void ELEMENT::tr_load_point (const node_t & no1, const node_t & no2, double * value, double * old_value) [inline, protected]
Definition at line 397 of file e_elemnt.h.
References SIM_DATA::_aa, CKT_BASE::_sim, dampdiff(), BSMATRIX< T >::load_point(), and node_t::m_().
Referenced by DEV_SPICE::tr_load().
{
  double d = dampdiff(new_value, *old_value);
  if (d != 0.) {
    _sim->_aa.load_point(no1.m_(), no2.m_(), d);
  }else{
  }
  *old_value = *new_value;
}
void ELEMENT::tr_load_shunt () [inline, protected]
Definition at line 209 of file e_elemnt.h.
References SIM_DATA::_aa, _loss0, _loss1, CARD::_n, CKT_BASE::_sim, dampdiff(), BSMATRIX< T >::load_symmetric(), OUT1, and OUT2.
Referenced by tr_unload_shunt().
{
  double d = dampdiff(&_loss0, _loss1);
  if (d != 0.) {
    _sim->_aa.load_symmetric(_n[OUT1].m_(), _n[OUT2].m_(), d);
  }else{
  }
  _loss1 = _loss0;
}
void ELEMENT::tr_load_source () [inline, protected]
Definition at line 231 of file e_elemnt.h.
References _loaditer, _m0, _m1, CARD::_n, CKT_BASE::_sim, CPOLY1::c0, dampdiff(), node_t::i(), SIM_DATA::iteration_tag(), OUT1, and OUT2.
Referenced by anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_load(), tr_load_active(), tr_load_passive(), and tr_unload_source().
{
#if !defined(NDEBUG)
  assert(_loaditer != _sim->iteration_tag()); // double load
  _loaditer = _sim->iteration_tag();
#endif
  double d = dampdiff(&_m0.c0, _m1.c0);
  if (d != 0.) {
    if (_n[OUT2].m_() != 0) {
      _n[OUT2].i() += d;
    }else{
    }
    if (_n[OUT1].m_() != 0) {
      _n[OUT1].i() -= d;
    }else{
    }
  }else{
  }
  _m1 = _m0;
}
void ELEMENT::tr_load_source_point (node_t & no1, double * value, double * old_value) [inline, protected]
Definition at line 359 of file e_elemnt.h.
References dampdiff(), node_t::i(), and node_t::m_().
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_load(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_load(), and DEV_SPICE::tr_load().
{
  double d = dampdiff(new_value, *old_value);
  if (d != 0.) {
    if (no1.m_() != 0) {
      no1.i() += d;
    }else{
    }
  }else{
  }
  *old_value = *new_value;
}
bool ELEMENT::tr_needs_eval () const [inline, virtual]
Reimplemented from CARD.
Reimplemented in DEV_SPICE, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, STORAGE, and CCSRC_BASE.
Definition at line 52 of file e_elemnt.h.
References CARD::is_constant().
{/*assert(!is_q_for_eval());*/ return !is_constant();}
double ELEMENT::tr_outvolts () const [inline]
Definition at line 134 of file e_elemnt.h.
References dn_diff(), OUT1, and OUT2.
Referenced by anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::do_tr(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_accept(), tr_amps(), and tr_probe_num().
{return dn_diff(_n[OUT1].v0(), _n[OUT2].v0());}
double ELEMENT::tr_outvolts_limited () const [inline]
Definition at line 135 of file e_elemnt.h.
References OUT1, OUT2, and COMPONENT::volts_limited().
{return volts_limited(_n[OUT1],_n[OUT2]);}
double ELEMENT::tr_probe_num (const std::string & x) const [virtual]
Reimplemented from COMPONENT.
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, DEV_LOGIC, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, and STORAGE.
Definition at line 284 of file e_elemnt.cc.
References _dt, TIME_PAIR::_error_estimate, _loss0, SIM_DATA::_lu, _m0, CARD::_n, CKT_BASE::_sim, _time, COMPONENT::_time_by, _y, CPOLY1::c0, CPOLY1::c1, FPOLY1::f0, CPOLY1::f0(), FPOLY1::f1, itested, LINEAR, MAXDBL, COMPONENT::mfactor(), OUT1, OUT2, anonymous_namespace{c_genrat.cc}::p, port_impedance(), tr_amps(), tr_involts(), tr_outvolts(), Umatch(), untested, COMPONENT::value(), FPOLY1::x, and CPOLY1::x.
{
  if (Umatch(x, "v{out} ")) {
    return tr_outvolts();
  }else if (Umatch(x, "vi{n} ")) {
    return tr_involts();
  }else if (Umatch(x, "i ")) {
    return tr_amps();
  }else if (Umatch(x, "p ")) {
    return tr_amps() * tr_outvolts();
  }else if (Umatch(x, "pd ")) {
    double p = tr_amps() * tr_outvolts();
    return (p > 0.) ? p : 0.;
  }else if (Umatch(x, "ps ")) {
    double p = tr_amps() * tr_outvolts();
    return (p < 0.) ? -p : 0.;
  }else if (Umatch(x, "in{put} ")) {
    return _y[0].x;
  }else if (Umatch(x, "f ")) {
    if (_y[0].f0 == LINEAR) {itested();
      return _y[0].x * _y[0].f1;
    }else{
      return _y[0].f0;
    }
  }else if (Umatch(x, "ev |df ")) {
    return _y[0].f1;
  }else if (Umatch(x, "nv ")) {
    return value();
  }else if (Umatch(x, "eiv ")) {untested();
    return _m0.x;
  }else if (Umatch(x, "y ")) {
    return _m0.c1;
  }else if (Umatch(x, "is{tamp} ")) {
    return _m0.f0();
  }else if (Umatch(x, "iof{fset} ")) {itested();
    return _m0.c0;
  }else if (Umatch(x, "ip{assive} ")) {itested();
    return _m0.c1 * tr_involts();
  }else if (Umatch(x, "il{oss} ")) {untested();
    return _loss0 * tr_outvolts();
  }else if (Umatch(x, "dt ")) {
    return _dt;
  }else if (Umatch(x, "dtr{equired} ")) {
    return ((_time_by._error_estimate - _time[0]) > 0)
      ? _time_by._error_estimate - _time[0]
      : _time_by._error_estimate - _time[1];
  }else if (Umatch(x, "time ")) {untested();
    return _time[0];
  }else if (Umatch(x, "timeo{ld} ")) {untested();
    return _time[1];
  //}else if (Umatch(x, "didt ")) {untested();
    //double i0  = (_m0.c1  * _m0.x  + _m0.c0);
    //double it1 = (mt1.f1 * mt1.x + mt1.c0);
    //return  (i0 - it1) / (_sim->_time0 - _time1);
  }else if (Umatch(x, "r ")) {
    return (_m0.c1!=0.) ? 1/_m0.c1 : MAXDBL;
  }else if (Umatch(x, "z ")) {
    return port_impedance(_n[OUT1], _n[OUT2], _sim->_lu, mfactor()*(_m0.c1+_loss0));
  }else if (Umatch(x, "zraw ")) {
    return port_impedance(_n[OUT1], _n[OUT2], _sim->_lu, 0.);
  }else{
    return COMPONENT::tr_probe_num(x);
  }
}
void ELEMENT::tr_regress () [virtual]
Reimplemented from CARD.
Reimplemented in DEV_SPICE, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_switch.cc}::SWITCH_BASE, and DEV_LOGIC.
Definition at line 161 of file e_elemnt.cc.
References _dt, OPT::_keep_time_steps, CKT_BASE::_sim, _time, and SIM_DATA::_time0.
{
  assert(_time[0] >= _sim->_time0); // moving backwards
  assert(_time[1] <= _sim->_time0); // but not too far backwards
  for (int i=OPT::_keep_time_steps-1; i>0; --i) {
    assert(_time[i] < _time[i-1] || _time[i] == 0.);
  }
  _time[0] = _sim->_time0;
  _dt = _time[0] - _time[1];
}
void ELEMENT::tr_restore () [virtual]
Reimplemented from CARD.
Reimplemented in DEV_SPICE, DEV_LOGIC, and STORAGE.
Definition at line 108 of file e_elemnt.cc.
References OPT::_keep_time_steps, CKT_BASE::_sim, _time, SIM_DATA::_time0, _y, error(), itested, and untested.
{
  if (_time[0] > _sim->_time0) {itested();
    for (int i=0  ; i<OPT::_keep_time_steps-1; ++i) {itested();
      _time[i] = _time[i+1];
      _y[i] = _y[i+1];
    }
    _time[OPT::_keep_time_steps-1] = 0.;
    _y[OPT::_keep_time_steps-1]    = FPOLY1(0., 0., 0.);
  }else if (_time[0] == _sim->_time0) {
  }else{untested();
  }
  //assert(_time[0] == _sim->_time0);
  if (_time[0] != _sim->_time0) {itested();
    error(bDANGER, "//BUG// restore time mismatch.  last=%g, using=%g\n",
          _time[0], _sim->_time0);
    //BUG// happens when continuing after a ^c,
    // when the last step was not printed
    // _time[0] is the non-printed time.  _sim->_time0 is the printed time.
  }else{
  }
  for (int i=OPT::_keep_time_steps-1; i>0; --i) {
    assert(_time[i] < _time[i-1] || _time[i] == 0.);
  }
}
TIME_PAIR ELEMENT::tr_review () [virtual]
Reimplemented from COMPONENT.
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, and STORAGE.
Definition at line 174 of file e_elemnt.cc.
References COMPONENT::_time_by, _y, LINEAR, TIME_PAIR::min_error_estimate(), order(), tr_review_check_and_convert(), and tr_review_trunc_error().
{
  COMPONENT::tr_review();
  if (order() > 0 && _y[0].f0 != LINEAR) {
    double timestep = tr_review_trunc_error(_y);
    double newtime = tr_review_check_and_convert(timestep);
    _time_by.min_error_estimate(newtime);
  }else{
  }
  return _time_by;
}
double ELEMENT::tr_review_check_and_convert (double timestep)
Definition at line 440 of file e_elemnt.cc.
References _dt, SIM_DATA::_dtmin, CKT_BASE::_sim, _time, error(), CARD::long_label(), NEVER, order(), trace3, and OPT::trreject.
Referenced by STORAGE::tr_review(), tr_review(), and DEV_SPICE::tr_review().
{
  double time_future;
  if (timestep == NEVER) {
    time_future = NEVER;
  }else{
    if (timestep < _sim->_dtmin) {
      timestep = _sim->_dtmin;
    }else{
    }
    if (timestep < _dt * OPT::trreject) {
      if (_time[order()] == 0) {
        error(bWARNING, "initial step rejected:" + long_label() + '\n');
        error(bWARNING, "new=%g  old=%g  required=%g\n",
              timestep, _dt, _dt * OPT::trreject);
      }else{
        error(bTRACE, "step rejected:" + long_label() + '\n');
        error(bTRACE, "new=%g  old=%g  required=%g\n",
              timestep, _dt, _dt * OPT::trreject);
      }
      time_future = _time[1] + timestep;
      trace3("reject", timestep, _dt, time_future);
    }else{
      time_future = _time[0] + timestep;
      trace3("accept", timestep, _dt, time_future);
    }
  }
  assert(time_future > 0.);
  assert(time_future > _time[1]);
  return time_future;
}
double ELEMENT::tr_review_trunc_error (const FPOLY1 * q)
Definition at line 388 of file e_elemnt.cc.
References _dt, OPT::_keep_time_steps, _time, OPT::chgtol, derivatives(), error_factor(), FPOLY1::f0, CARD::long_label(), NEVER, order(), OPT::reltol, trace0, trace4, trace5, and OPT::trtol.
Referenced by CKTterr(), STORAGE::tr_review(), and tr_review().
{
  int error_deriv = order()+1;
  double timestep;
  if (_time[0] <= 0.) {
    // DC, I know nothing
    timestep = NEVER;
  }else if (_time[error_deriv] <= 0.) {
    // first few steps, I still know nothing
    // repeat whatever step was used the first time
    timestep = _dt;
  }else{
    for (int i=error_deriv; i>0; --i) {
      assert(_time[i] < _time[i-1]); // || _time[i] == 0.);
    }
    double c[OPT::_keep_time_steps];
    for (int i=0; i<OPT::_keep_time_steps; ++i) {
      c[i] = q[i].f0;
    }
    assert(error_deriv < OPT::_keep_time_steps);
    derivatives(c, OPT::_keep_time_steps, _time);
    // now c[i] is i'th derivative
    assert(OPT::_keep_time_steps >= 5);
    trace0(("ts" + long_label()).c_str());
    trace5("time", _time[0], _time[1], _time[2], _time[3], _time[4]);
    trace5("charge", q[0].f0, q[1].f0, q[2].f0, q[3].f0, q[4].f0);
    trace5("deriv", c[0], c[1], c[2], c[3], c[4]);
    if (c[error_deriv] == 0) {
      timestep = NEVER;
    }else{
      double chargetol = std::max(OPT::chgtol,
        OPT::reltol * std::max(std::abs(q[0].f0), std::abs(q[1].f0)));
      double tol = OPT::trtol * chargetol;
      double denom = error_factor() * std::abs(c[error_deriv]);
      assert(tol > 0.);
      assert(denom > 0.);
      switch (error_deriv) { // pow is slow.
      case 1:   timestep = tol / denom;         break;
      case 2:   timestep = sqrt(tol / denom);   break;
      case 3:   timestep = cbrt(tol / denom);   break;
      default:  timestep = pow((tol / denom), 1./(error_deriv)); break;
      }
      trace4("", chargetol, tol, denom, timestep);
    }
  }
  assert(timestep > 0.);
  return timestep;
}
void ELEMENT::tr_unload_active () [inline, protected]
Definition at line 327 of file e_elemnt.h.
References _m0, CKT_BASE::_sim, CPOLY1::c0, CPOLY1::c1, SIM_DATA::mark_inc_mode_bad(), tr_load_active(), and untested.
Referenced by CCSRC_BASE::tr_unload().
{untested();
  _m0.c0 = _m0.c1 = 0.;
  _sim->mark_inc_mode_bad();
  tr_load_active(); // includes _m1 = _m0
}
void ELEMENT::tr_unload_couple () [inline, protected]
Definition at line 282 of file e_elemnt.h.
References _m0, CKT_BASE::_sim, CPOLY1::c0, CPOLY1::c1, SIM_DATA::mark_inc_mode_bad(), tr_load_couple(), and untested.
Referenced by anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_unload().
{untested();
  _m0.c0 = _m0.c1 = 0.;
  _sim->mark_inc_mode_bad();
  tr_load_couple(); // includes _m1 = _m0
}
void ELEMENT::tr_unload_inode () [inline, protected]
Definition at line 196 of file e_elemnt.h.
References _loss0, CKT_BASE::_sim, SIM_DATA::mark_inc_mode_bad(), tr_load_inode(), and untested.
{untested();
  _loss0 = 0.;
  _sim->mark_inc_mode_bad();
  tr_load_inode();
}
void ELEMENT::tr_unload_passive () [inline, protected]
Definition at line 304 of file e_elemnt.h.
References _m0, CKT_BASE::_sim, CPOLY1::c0, CPOLY1::c1, SIM_DATA::mark_inc_mode_bad(), and tr_load_passive().
Referenced by DEV_LOGIC::tr_unload().
{
  _m0.c0 = _m0.c1 = 0.;
  _sim->mark_inc_mode_bad();
  tr_load_passive(); // includes _m1 = _m0
}
void ELEMENT::tr_unload_shunt () [inline, protected]
Definition at line 219 of file e_elemnt.h.
References _loss0, CKT_BASE::_sim, SIM_DATA::mark_inc_mode_bad(), tr_load_shunt(), and untested.
{untested();
  _loss0 = 0.;
  _sim->mark_inc_mode_bad();
  tr_load_shunt();
}
void ELEMENT::tr_unload_source () [inline, protected]
Definition at line 253 of file e_elemnt.h.
References _m0, CKT_BASE::_sim, CPOLY1::c0, CPOLY1::c1, SIM_DATA::mark_inc_mode_bad(), tr_load_source(), and untested.
{untested();
  _m0.c0 = _m0.c1 = 0.;
  _sim->mark_inc_mode_bad();
  tr_load_source();
}
bool ELEMENT::using_ac_eval () const [inline, protected]
Definition at line 436 of file e_elemnt.h.
References has_ac_eval(), and CKT_BASE::has_probes().
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_ac().
{
  return (has_probes() || has_ac_eval());
}
bool ELEMENT::using_tr_eval () const [inline, protected]
Definition at line 431 of file e_elemnt.h.
References CKT_BASE::has_probes(), and has_tr_eval().
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_tr().
{
  return (has_probes() || has_tr_eval());
}
Member Data Documentation
COMPLEX ELEMENT::_acg
Definition at line 158 of file e_elemnt.h.
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::ac_amps(), ac_amps(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::ac_load(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::ac_load(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::ac_load(), ac_load_active(), ac_load_couple(), ac_load_passive(), ac_load_source(), ac_probe_ext(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_ac(), and anonymous_namespace{d_switch.cc}::SWITCH_BASE::do_ac().
double ELEMENT::_dt
Definition at line 161 of file e_elemnt.h.
Referenced by dc_advance(), DEV_SPICE::localize_ckt(), tr_advance(), tr_begin(), STORAGE::tr_c_to_g(), tr_probe_num(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_probe_num(), tr_regress(), tr_review_check_and_convert(), and tr_review_trunc_error().
COMPLEX ELEMENT::_ev
Definition at line 160 of file e_elemnt.h.
Referenced by anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR::ac_eval(), anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX::ac_eval(), EVAL_BM_ACTION_BASE::ac_eval(), ac_eval(), ac_probe_ext(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_ac(), and anonymous_namespace{d_switch.cc}::SWITCH_BASE::do_ac().
int ELEMENT::_loaditer [protected]
Definition at line 150 of file e_elemnt.h.
Referenced by DEV_SPICE::tr_load(), and tr_load_source().
double ELEMENT::_loss0
Definition at line 156 of file e_elemnt.h.
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::ac_amps(), ac_amps(), ac_load_inode(), ac_load_shunt(), ac_probe_ext(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_ac(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_tr(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::do_tr_last(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::precalc_last(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_amps(), tr_amps(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_begin(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_begin(), tr_load_inode(), tr_load_shunt(), tr_probe_num(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_unload(), tr_unload_inode(), and tr_unload_shunt().
double ELEMENT::_loss1
Definition at line 157 of file e_elemnt.h.
Referenced by anonymous_namespace{d_switch.cc}::SWITCH_BASE::precalc_last(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_begin(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_begin(), tr_load_inode(), and tr_load_shunt().
CPOLY1 ELEMENT::_m0
Definition at line 154 of file e_elemnt.h.
Referenced by anonymous_namespace{d_switch.cc}::SWITCH_BASE::do_ac(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::do_tr(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_tr(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::do_tr(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::do_tr(), anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::do_tr(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::do_tr_last(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::precalc_last(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_advance(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::tr_amps(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_amps(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::tr_amps(), tr_amps(), STORAGE::tr_begin(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_begin(), DEV_LOGIC::tr_eval_digital(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_input(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_input_limited(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_load(), tr_load_active(), tr_load_couple(), tr_load_passive(), tr_load_source(), tr_probe_num(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_regress(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::tr_unload(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_unload(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::tr_unload(), tr_unload_active(), tr_unload_couple(), tr_unload_passive(), and tr_unload_source().
CPOLY1 ELEMENT::_m1
Definition at line 155 of file e_elemnt.h.
Referenced by anonymous_namespace{d_switch.cc}::SWITCH_BASE::precalc_last(), STORAGE::tr_begin(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_begin(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_load(), tr_load_active(), tr_load_couple(), tr_load_passive(), and tr_load_source().
node_t ELEMENT::_nodes[NODES_PER_BRANCH] [private]
Reimplemented in DEV_SPICE.
Definition at line 152 of file e_elemnt.h.
Referenced by ELEMENT().
double ELEMENT::_time[OPT::_keep_time_steps]
Reimplemented in anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G.
Definition at line 163 of file e_elemnt.h.
Referenced by dc_advance(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_tr(), anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::do_tr(), DEV_SPICE::do_tr(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::do_tr_last(), ELEMENT(), DEV_SPICE::localize_ckt(), tr_advance(), tr_begin(), STORAGE::tr_c_to_g(), DEV_SPICE::tr_needs_eval(), tr_probe_num(), tr_regress(), tr_restore(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_review(), tr_review_check_and_convert(), and tr_review_trunc_error().
FPOLY1 ELEMENT::_y[OPT::_keep_time_steps]
Definition at line 165 of file e_elemnt.h.
Referenced by EVAL_BM_ACTION_BASE::ac_eval(), ac_eval(), conv_check(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_ac(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::do_ac(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_tr(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::do_tr(), anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::do_tr(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::do_tr_last(), ELEMENT(), precalc_last(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::precalc_last(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::precalc_last(), tr_advance(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_advance(), tr_begin(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_begin(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_begin(), EVAL_BM_TABLE::tr_eval(), anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::tr_eval(), anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::tr_eval(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::tr_eval(), anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY::tr_eval(), anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT::tr_eval(), MODEL_TABLE::tr_eval(), tr_eval(), DEV_LOGIC::tr_eval_digital(), EVAL_BM_ACTION_BASE::tr_finish_tdv(), STORAGE::tr_needs_eval(), tr_probe_num(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_probe_num(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_regress(), tr_restore(), STORAGE::tr_review(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::tr_review(), and tr_review().
FPOLY1 ELEMENT::_y1
Definition at line 164 of file e_elemnt.h.
Referenced by conv_check(), ELEMENT(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::precalc_last(), tr_begin(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_begin(), and anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_begin().
The documentation for this class was generated from the following files:
savant/gnucap/src/e_elemnt.h
savant/gnucap/src/e_elemnt.cc