gnucap: DEV_BUILT_IN_BJT Class Reference
DEV_BUILT_IN_BJT Class Reference
#include <d_bjt.h>
Public Member Functions
DEV_BUILT_IN_BJT ()
~DEV_BUILT_IN_BJT ()
Static Public Member Functions
static int count ()
Public Attributes
double vbe
double vbc
double vbx
double vcs
double cce
double ccexxx
double go
double gm
double cpi
double cpixxx
double gpi
double cmu
double cmuxxx
double gmu
double ixxxx
double gx
double qbx
double cqbx
double qbc
double cqbc
double qcs
double cqcs
double qbe
double cqbe
double geqcb
double cexbc_0
double cexbc_1
double cexbc_2
double _dt_0
double _dt_1
COMPONENT * _Ice
COMPONENT * _Ipi
COMPONENT * _Imu
COMPONENT * _Cbx
COMPONENT * _Cbc
COMPONENT * _Ccs
COMPONENT * _Cbe
COMPONENT * _Rc
COMPONENT * _Re
COMPONENT * _Yb
COMPONENT * _Cbcp
COMPONENT * _Cbep
COMPONENT * _Cbs
Private Types
enum {
n_c, n_b, n_e, n_s,
n_ic, n_ib, n_ie
}
Private Member Functions
DEV_BUILT_IN_BJT (const DEV_BUILT_IN_BJT &p)
char id_letter () const
bool print_type_in_spice () const
std::string value_name () const
int max_nodes () const
int min_nodes () const
int int_nodes () const
CARD * clone () const
void precalc_first ()
void expand ()
void precalc_last ()
void dc_advance ()
void tr_advance ()
void tr_regress ()
bool tr_needs_eval () const
void tr_queue_eval ()
bool do_tr ()
double tr_probe_num (const std::string &) const
std::string port_name (int i) const
Private Attributes
node_t _nodes [7]
Static Private Attributes
static int _count = -1
Detailed Description
Definition at line 203 of file d_bjt.h.
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
n_c
n_b
n_e
n_s
n_ic
n_ib
n_ie
Definition at line 293 of file d_bjt.h.
{n_c, n_b, n_e, n_s, n_ic, n_ib, n_ie};
Constructor & Destructor Documentation
DEV_BUILT_IN_BJT::DEV_BUILT_IN_BJT (const DEV_BUILT_IN_BJT & p) [explicit, private]
Definition at line 1248 of file d_bjt.cc.
References _count, CARD::_n, _nodes, int_nodes(), and max_nodes().
  :BASE_SUBCKT(p),
   // input parameters,
   // calculated parameters,
   vbe(p.vbe),
   vbc(p.vbc),
   vbx(p.vbx),
   vcs(p.vcs),
   cce(p.cce),
   ccexxx(p.ccexxx),
   go(p.go),
   gm(p.gm),
   cpi(p.cpi),
   cpixxx(p.cpixxx),
   gpi(p.gpi),
   cmu(p.cmu),
   cmuxxx(p.cmuxxx),
   gmu(p.gmu),
   ixxxx(p.ixxxx),
   gx(p.gx),
   qbx(p.qbx),
   cqbx(p.cqbx),
   qbc(p.qbc),
   cqbc(p.cqbc),
   qcs(p.qcs),
   cqcs(p.cqcs),
   qbe(p.qbe),
   cqbe(p.cqbe),
   geqcb(p.geqcb),
   cexbc_0(p.cexbc_0),
   cexbc_1(p.cexbc_1),
   cexbc_2(p.cexbc_2),
   _dt_0(p._dt_0),
   _dt_1(p._dt_1),
   // netlist,
   _Ice(0),
   _Ipi(0),
   _Imu(0),
   _Cbx(0),
   _Cbc(0),
   _Ccs(0),
   _Cbe(0),
   _Rc(0),
   _Re(0),
   _Yb(0),
   _Cbcp(0),
   _Cbep(0),
   _Cbs(0)
{
  _n = _nodes;
  for (int ii = 0; ii < max_nodes() + int_nodes(); ++ii) {
    _n[ii] = p._n[ii];
  }
  ++_count;
  // overrides
}
DEV_BUILT_IN_BJT::DEV_BUILT_IN_BJT () [explicit]
Definition at line 1193 of file d_bjt.cc.
References _count, CARD::_n, _nodes, COMPONENT::attach_common(), and Default_BUILT_IN_BJT.
Referenced by clone().
  :BASE_SUBCKT(),
   // input parameters,
   // calculated parameters,
   vbe(NA),
   vbc(NA),
   vbx(NA),
   vcs(NA),
   cce(NA),
   ccexxx(NA),
   go(NA),
   gm(NA),
   cpi(NA),
   cpixxx(NA),
   gpi(NA),
   cmu(NA),
   cmuxxx(NA),
   gmu(NA),
   ixxxx(0.),
   gx(NA),
   qbx(NA),
   cqbx(NA),
   qbc(NA),
   cqbc(NA),
   qcs(NA),
   cqcs(NA),
   qbe(NA),
   cqbe(NA),
   geqcb(NA),
   cexbc_0(NA),
   cexbc_1(NA),
   cexbc_2(NA),
   _dt_0(NA),
   _dt_1(NA),
   // netlist,
   _Ice(0),
   _Ipi(0),
   _Imu(0),
   _Cbx(0),
   _Cbc(0),
   _Ccs(0),
   _Cbe(0),
   _Rc(0),
   _Re(0),
   _Yb(0),
   _Cbcp(0),
   _Cbep(0),
   _Cbs(0)
{
  _n = _nodes;
  attach_common(&Default_BUILT_IN_BJT);
  ++_count;
  // overrides
}
DEV_BUILT_IN_BJT::~DEV_BUILT_IN_BJT () [inline]
Definition at line 208 of file d_bjt.h.
References _count.
{--_count;}
Member Function Documentation
CARD* DEV_BUILT_IN_BJT::clone () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 219 of file d_bjt.h.
References DEV_BUILT_IN_BJT().
{return new DEV_BUILT_IN_BJT(*this);}
static int DEV_BUILT_IN_BJT::count () [inline, static]
Definition at line 242 of file d_bjt.h.
References _count.
{return _count;}
void DEV_BUILT_IN_BJT::dc_advance () [inline, private, virtual]
Reimplemented from BASE_SUBCKT.
Definition at line 226 of file d_bjt.h.
References COMPONENT::set_not_converged().
{set_not_converged(); BASE_SUBCKT::dc_advance();}
bool DEV_BUILT_IN_BJT::do_tr () [private, virtual]
Reimplemented from BASE_SUBCKT.
Definition at line 1807 of file d_bjt.cc.
References CARD::_n, CKT_BASE::_sim, SIM_DATA::_temp_c, cce, ccexxx, cmu, cmuxxx, COMPONENT::common(), COMPONENT::converged(), cpi, cpixxx, has_good_value(), MODEL_BUILT_IN_BJT::ibe, COMMON_BUILT_IN_BJT::icvbe, COMMON_BUILT_IN_BJT::icvce, SIM_DATA::is_initial_step(), itested, ixxxx, COMMON_COMPONENT::model(), n_b, n_ib, n_ic, n_ie, n_s, COMMON_BUILT_IN_BJT::off, P_CELSIUS0, P_K_Q, pN, pnj_limit(), MODEL_BUILT_IN_BJT::polarity, pP, prechecked_cast, qbc, qbe, qbx, qcs, COMPONENT::set_converged(), CARD::subckt(), MODEL_BUILT_IN_BJT::tr_eval(), SIM_DATA::uic_now(), untested, vbc, vbe, vbx, TDP_BUILT_IN_BJT::Vcrit, vcs, COMPONENT::volts_limited(), and TDP_BUILT_IN_BJT::vt.
{
  const COMMON_BUILT_IN_BJT* c = prechecked_cast<const COMMON_BUILT_IN_BJT*>(common());
  assert(c);
  const MODEL_BUILT_IN_BJT* m = prechecked_cast<const MODEL_BUILT_IN_BJT*>(c->model());
  assert(m);
  const TDP_BUILT_IN_BJT T(this);
  const TDP_BUILT_IN_BJT* t = &T;
  if(_sim->is_initial_step()) { // initial guess
    if (c->off) {
      vbe = 0.;
    }else{
      double vt = (_sim->_temp_c + P_CELSIUS0) * P_K_Q;
      vbe = vt * log(vt / (M_SQRT2 * m->ibe));
    }
    vbc = 0.;
    /* ERROR:  need to initialize VCS, VBX here */
    vcs = vbx = 0.;
  }else{                                // normal gather
    vbe = pnj_limit((m->polarity * volts_limited(_n[n_ib], _n[n_ie])),
                    vbe, t->vt, t->Vcrit);
    vbc = pnj_limit((m->polarity * volts_limited(_n[n_ib], _n[n_ic])),
                    vbc, t->vt, t->Vcrit);
    vbx = m->polarity * volts_limited(_n[n_b], _n[n_ic]);
    vcs = m->polarity * volts_limited(_n[n_s], _n[n_ic]);
  }
  if (_sim->uic_now()) {itested();//736
    if (has_good_value(c->icvbe)) {untested();//737
      vbe = m->polarity * c->icvbe;
    }else{itested();//739
    }
    if (has_good_value(c->icvce)) {untested();//741
      vbc = vbe - m->polarity * c->icvce;
      vbx = vbc;
    }else{itested();//744
    }
  }else{
  }
  m->tr_eval(this);
  switch (m->polarity) {
  case pP:
    cce = -cce;
    ccexxx = -ccexxx;
    cpi = -cpi;
    cpixxx = -cpixxx;
    cmu = -cmu;
    cmuxxx = -cmuxxx;
    assert(ixxxx == 0.);
    qbx = -qbx;
    qbc = -qbc;
    qcs = -qcs;
    qbe = -qbe;
    break;
  case pN:
    // leave it as is
    break;
  }
  assert(subckt());
  set_converged(subckt()->do_tr());
  return converged();
}
void DEV_BUILT_IN_BJT::expand () [private, virtual]
Reimplemented from COMPONENT.
Definition at line 1305 of file d_bjt.cc.
References _Cbc, _Cbcp, _Cbe, _Cbep, _Cbs, _Cbx, _Ccs, _Ice, _Imu, _Ipi, CARD::_n, _Rc, _Re, CKT_BASE::_sim, _Yb, COMMON_BUILT_IN_BJT::area, ccexxx, CARD::clone(), cmuxxx, COMPONENT::common(), cpixxx, OPT::cstray, anonymous_namespace{d_admit.cc}::device_dispatcher, CARD_LIST::erase(), CARD_LIST::expand(), CARD::is_constant(), SIM_DATA::is_first_expand(), ixxxx, CARD::long_label(), COMMON_COMPONENT::model(), CARD::n_(), n_b, n_c, n_e, n_ib, n_ic, n_ie, n_s, node_t::new_model_node(), CARD::new_subckt(), anonymous_namespace{c_genrat.cc}::p, precalc_first(), precalc_last(), prechecked_cast, CARD_LIST::push_front(), qbc, qbe, qbx, qcs, OPT::rstray, COMMON_BUILT_IN_BJT::sdp(), COMPONENT::set_parameters(), CARD_LIST::set_slave(), and CARD::subckt().
{
  BASE_SUBCKT::expand(); // calls common->expand, attached model
  assert(_n);
  assert(common());
  const COMMON_BUILT_IN_BJT* c = static_cast<const COMMON_BUILT_IN_BJT*>(common());
  assert(c);
  assert(c->model());
  const MODEL_BUILT_IN_BJT* m = prechecked_cast<const MODEL_BUILT_IN_BJT*>(c->model());
  assert(m);
  assert(c->sdp());
  const SDP_BUILT_IN_BJT* s = prechecked_cast<const SDP_BUILT_IN_BJT*>(c->sdp());
  assert(s);
  if (!subckt()) {
    new_subckt();
  }else{
  }
  if (_sim->is_first_expand()) {
    precalc_first();
    precalc_last();
    // local nodes
    //assert(!(_n[n_ic].n_()));
    //BUG// this assert fails on a repeat elaboration after a change.
    //not sure of consequences when new_model_node called twice.
    if (!(_n[n_ic].n_())) {
      if (!OPT::rstray || m->rc == 0.) {
        _n[n_ic] = _n[n_c];
      }else{
        _n[n_ic].new_model_node("." + long_label() + ".ic", this);
      }
    }else{
      if (!OPT::rstray || m->rc == 0.) {
        assert(_n[n_ic] == _n[n_c]);
      }else{
        //_n[n_ic].new_model_node("ic." + long_label(), this);
      }
    }
    //assert(!(_n[n_ib].n_()));
    //BUG// this assert fails on a repeat elaboration after a change.
    //not sure of consequences when new_model_node called twice.
    if (!(_n[n_ib].n_())) {
      if (!OPT::rstray || (m->rb == 0. && m->rbm == 0.)) {
        _n[n_ib] = _n[n_b];
      }else{
        _n[n_ib].new_model_node("." + long_label() + ".ib", this);
      }
    }else{
      if (!OPT::rstray || (m->rb == 0. && m->rbm == 0.)) {
        assert(_n[n_ib] == _n[n_b]);
      }else{
        //_n[n_ib].new_model_node("ib." + long_label(), this);
      }
    }
    //assert(!(_n[n_ie].n_()));
    //BUG// this assert fails on a repeat elaboration after a change.
    //not sure of consequences when new_model_node called twice.
    if (!(_n[n_ie].n_())) {
      if (!OPT::rstray || m->re == 0.) {
        _n[n_ie] = _n[n_e];
      }else{
        _n[n_ie].new_model_node("." + long_label() + ".ie", this);
      }
    }else{
      if (!OPT::rstray || m->re == 0.) {
        assert(_n[n_ie] == _n[n_e]);
      }else{
        //_n[n_ie].new_model_node("ie." + long_label(), this);
      }
    }
    // clone subckt elements
    {
      if (!_Ice) {
        const CARD* p = device_dispatcher["cpoly_g"];
        assert(p);
        _Ice = dynamic_cast<COMPONENT*>(p->clone());
        assert(_Ice);
        subckt()->push_front(_Ice);
      }else{
      }
      {
        node_t nodes[] = {_n[n_ic], _n[n_ie], _n[n_ib], _n[n_ie]};
      _Ice->set_parameters("Ice", this, NULL, 0., 3, &ccexxx, 4, nodes);
      }
    }
    {
      if (!_Ipi) {
        const CARD* p = device_dispatcher["cpoly_g"];
        assert(p);
        _Ipi = dynamic_cast<COMPONENT*>(p->clone());
        assert(_Ipi);
        subckt()->push_front(_Ipi);
      }else{
      }
      {
        node_t nodes[] = {_n[n_ib], _n[n_ie]};
      _Ipi->set_parameters("Ipi", this, NULL, 0., 2, &cpixxx, 2, nodes);
      }
    }
    {
      if (!_Imu) {
        const CARD* p = device_dispatcher["cpoly_g"];
        assert(p);
        _Imu = dynamic_cast<COMPONENT*>(p->clone());
        assert(_Imu);
        subckt()->push_front(_Imu);
      }else{
      }
      {
        node_t nodes[] = {_n[n_ib], _n[n_ic]};
      _Imu->set_parameters("Imu", this, NULL, 0., 2, &cmuxxx, 2, nodes);
      }
    }
    {
      if (!_Cbx) {
        const CARD* p = device_dispatcher["fpoly_cap"];
        assert(p);
        _Cbx = dynamic_cast<COMPONENT*>(p->clone());
        assert(_Cbx);
        subckt()->push_front(_Cbx);
      }else{
      }
      {
        node_t nodes[] = {_n[n_b], _n[n_ic]};
      _Cbx->set_parameters("Cbx", this, NULL, 0., 2, &qbx, 2, nodes);
      }
    }
    {
      if (!_Cbc) {
        const CARD* p = device_dispatcher["fpoly_cap"];
        assert(p);
        _Cbc = dynamic_cast<COMPONENT*>(p->clone());
        assert(_Cbc);
        subckt()->push_front(_Cbc);
      }else{
      }
      {
        node_t nodes[] = {_n[n_ib], _n[n_ic]};
      _Cbc->set_parameters("Cbc", this, NULL, 0., 2, &qbc, 2, nodes);
      }
    }
    if (!(_n[n_s].n_())) {
      if (_Ccs) {
        subckt()->erase(_Ccs);
        _Ccs = NULL;
      }else{
      }
    }else{
      if (!_Ccs) {
        const CARD* p = device_dispatcher["fpoly_cap"];
        assert(p);
        _Ccs = dynamic_cast<COMPONENT*>(p->clone());
        assert(_Ccs);
        subckt()->push_front(_Ccs);
      }else{
      }
      {
        node_t nodes[] = {_n[n_s], _n[n_ic]};
      _Ccs->set_parameters("Ccs", this, NULL, 0., 2, &qcs, 2, nodes);
      }
    }
    {
      if (!_Cbe) {
        const CARD* p = device_dispatcher["fpoly_cap"];
        assert(p);
        _Cbe = dynamic_cast<COMPONENT*>(p->clone());
        assert(_Cbe);
        subckt()->push_front(_Cbe);
      }else{
      }
      {
        node_t nodes[] = {_n[n_ib], _n[n_ie], _n[n_ib], _n[n_ic]};
      _Cbe->set_parameters("Cbe", this, NULL, 0., 3, &qbe, 4, nodes);
      }
    }
    if (!OPT::rstray || m->rc == 0.) {
      if (_Rc) {
        subckt()->erase(_Rc);
        _Rc = NULL;
      }else{
      }
    }else{
      if (!_Rc) {
        const CARD* p = device_dispatcher["resistor"];
        assert(p);
        _Rc = dynamic_cast<COMPONENT*>(p->clone());
        assert(_Rc);
        subckt()->push_front(_Rc);
      }else{
      }
      {
        node_t nodes[] = {_n[n_c], _n[n_ic]};
      _Rc->set_parameters("Rc", this, NULL, m->rc / c->area, 0, NULL, 2, nodes);
      }
    }
    if (!OPT::rstray || m->re == 0.) {
      if (_Re) {
        subckt()->erase(_Re);
        _Re = NULL;
      }else{
      }
    }else{
      if (!_Re) {
        const CARD* p = device_dispatcher["resistor"];
        assert(p);
        _Re = dynamic_cast<COMPONENT*>(p->clone());
        assert(_Re);
        subckt()->push_front(_Re);
      }else{
      }
      {
        node_t nodes[] = {_n[n_e], _n[n_ie]};
      _Re->set_parameters("Re", this, NULL, m->re / c->area, 0, NULL, 2, nodes);
      }
    }
    if (!OPT::rstray || (m->rb == 0. && m->rbm == 0.)) {
      if (_Yb) {
        subckt()->erase(_Yb);
        _Yb = NULL;
      }else{
      }
    }else{
      if (!_Yb) {
        const CARD* p = device_dispatcher["cpoly_g"];
        assert(p);
        _Yb = dynamic_cast<COMPONENT*>(p->clone());
        assert(_Yb);
        subckt()->push_front(_Yb);
      }else{
      }
      {
        node_t nodes[] = {_n[n_b], _n[n_ib]};
      _Yb->set_parameters("Yb", this, NULL, 0., 2, &ixxxx, 2, nodes);
      }
    }
    if (!OPT::cstray || m->cbcp == 0.) {
      if (_Cbcp) {
        subckt()->erase(_Cbcp);
        _Cbcp = NULL;
      }else{
      }
    }else{
      if (!_Cbcp) {
        const CARD* p = device_dispatcher["capacitor"];
        assert(p);
        _Cbcp = dynamic_cast<COMPONENT*>(p->clone());
        assert(_Cbcp);
        subckt()->push_front(_Cbcp);
      }else{
      }
      {
        node_t nodes[] = {_n[n_b], _n[n_c]};
      _Cbcp->set_parameters("Cbcp", this, NULL, m->cbcp * c->area, 0, NULL, 2, nodes);
      }
    }
    if (!OPT::cstray || m->cbep == 0.) {
      if (_Cbep) {
        subckt()->erase(_Cbep);
        _Cbep = NULL;
      }else{
      }
    }else{
      if (!_Cbep) {
        const CARD* p = device_dispatcher["capacitor"];
        assert(p);
        _Cbep = dynamic_cast<COMPONENT*>(p->clone());
        assert(_Cbep);
        subckt()->push_front(_Cbep);
      }else{
      }
      {
        node_t nodes[] = {_n[n_b], _n[n_e]};
      _Cbep->set_parameters("Cbep", this, NULL, m->cbep * c->area, 0, NULL, 2, nodes);
      }
    }
    if (!OPT::cstray || ((m->cbsp + m->ccsp) == 0.)) {
      if (_Cbs) {
        subckt()->erase(_Cbs);
        _Cbs = NULL;
      }else{
      }
    }else{
      if (!_Cbs) {
        const CARD* p = device_dispatcher["capacitor"];
        assert(p);
        _Cbs = dynamic_cast<COMPONENT*>(p->clone());
        assert(_Cbs);
        subckt()->push_front(_Cbs);
      }else{
      }
      {
        node_t nodes[] = {_n[n_b], _n[n_s]};
      _Cbs->set_parameters("Cbs", this, NULL, (m->cbsp + m->ccsp) * c->area, 0, NULL, 2, nodes);
      }
    }
  }else{
    //precalc();
  }
  //precalc();
  subckt()->expand();
  //subckt()->precalc();
  assert(!is_constant());
  subckt()->set_slave();
}
char DEV_BUILT_IN_BJT::id_letter () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 210 of file d_bjt.h.
References untested.
{untested();return 'Q';}
int DEV_BUILT_IN_BJT::int_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 218 of file d_bjt.h.
Referenced by DEV_BUILT_IN_BJT().
{return 3;}
int DEV_BUILT_IN_BJT::max_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 214 of file d_bjt.h.
Referenced by DEV_BUILT_IN_BJT().
{return 4;}
int DEV_BUILT_IN_BJT::min_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 215 of file d_bjt.h.
{return 3;}
std::string DEV_BUILT_IN_BJT::port_name (int i) const [inline, private, virtual]
Implements COMPONENT.
Definition at line 295 of file d_bjt.h.
{
    assert(i >= 0);
    assert(i < 4);
    static std::string names[] = {"c", "b", "e", "s", ""};
    return names[i];
  }
void DEV_BUILT_IN_BJT::precalc_first () [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 220 of file d_bjt.h.
References CARD_LIST::precalc_first(), and CARD::subckt().
Referenced by expand().
{COMPONENT::precalc_first(); if(subckt()) subckt()->precalc_first();}
void DEV_BUILT_IN_BJT::precalc_last () [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 222 of file d_bjt.h.
References CARD_LIST::precalc_last(), and CARD::subckt().
Referenced by expand().
{COMPONENT::precalc_last(); assert(subckt()); subckt()->precalc_last();}
bool DEV_BUILT_IN_BJT::print_type_in_spice () const [inline, private, virtual]
Implements COMPONENT.
Definition at line 211 of file d_bjt.h.
{return true;}
void DEV_BUILT_IN_BJT::tr_advance () [inline, private, virtual]
Reimplemented from BASE_SUBCKT.
Definition at line 227 of file d_bjt.h.
References COMPONENT::set_not_converged().
{set_not_converged(); BASE_SUBCKT::tr_advance();}
bool DEV_BUILT_IN_BJT::tr_needs_eval () const [private, virtual]
Reimplemented from BASE_SUBCKT.
Definition at line 1785 of file d_bjt.cc.
References CARD::_n, COMPONENT::common(), conchk(), COMPONENT::converged(), COMPONENT::is_q_for_eval(), COMMON_COMPONENT::model(), n_ib, n_ic, n_ie, n_s, MODEL_BUILT_IN_BJT::polarity, prechecked_cast, untested, vbc, vbe, vcs, and OPT::vntol.
Referenced by tr_queue_eval().
{
  if (is_q_for_eval()) {
    untested();
    return false;
  }else if (!converged()) {
    return true;
  }else{
    const COMMON_BUILT_IN_BJT* c = prechecked_cast<const COMMON_BUILT_IN_BJT*>(common());
    assert(c);
    const MODEL_BUILT_IN_BJT* m=prechecked_cast<const MODEL_BUILT_IN_BJT*>(c->model());
    assert(m);
    polarity_t polarity = m->polarity;
    return !(conchk(vbc, polarity*(_n[n_ib].v0()-_n[n_ic].v0()),
                    OPT::vntol)
             && conchk(vbe, polarity*(_n[n_ib].v0()-_n[n_ie].v0()),
                       OPT::vntol)
             && conchk(vcs, polarity*(_n[n_ic].v0()-_n[n_s].v0()),
                       OPT::vntol));
  }
}
double DEV_BUILT_IN_BJT::tr_probe_num (const std::string & x) const [private, virtual]
Reimplemented from COMPONENT.
Definition at line 1611 of file d_bjt.cc.
References _Cbc, _Cbe, _Cbx, _Ccs, _dt_0, _dt_1, _Ice, _Imu, _Ipi, CARD::_n, _Rc, _Re, _Yb, BIGBIG, cce, ccexxx, cexbc_0, cexbc_1, cexbc_2, cmu, cmuxxx, COMPONENT::common(), COMPONENT::converged(), cpi, cpixxx, cqbc, cqbe, cqbx, cqcs, geqcb, gm, gmu, go, gpi, gx, ixxxx, COMMON_COMPONENT::model(), n_b, n_c, n_e, n_ib, n_ic, n_ie, n_s, NA(), prechecked_cast, CKT_BASE::probe(), qbc, qbe, qbx, qcs, COMMON_BUILT_IN_BJT::sdp(), Umatch(), node_t::v0(), vbc, vbe, vbx, and vcs.
{
  assert(_n);
  const COMMON_BUILT_IN_BJT* c = prechecked_cast<const COMMON_BUILT_IN_BJT*>(common());
  assert(c);
  const MODEL_BUILT_IN_BJT* m = prechecked_cast<const MODEL_BUILT_IN_BJT*>(c->model());
  assert(m);
  const SDP_BUILT_IN_BJT* s = prechecked_cast<const SDP_BUILT_IN_BJT*>(c->sdp());
  assert(s);
  if (Umatch(x, "v ")) {
    return  _n[n_c].v0() - _n[n_e].v0();
  }else if (Umatch(x, "vbei{nt} ")) {
    return  vbe;
  }else if (Umatch(x, "vbci{nt} ")) {
    return  vbc;
  }else if (Umatch(x, "vbxi{nt} ")) {
    return  vbx;
  }else if (Umatch(x, "vcsi{nt} ")) {
    return  vcs;
  }else if (Umatch(x, "vbs ")) {
    return  _n[n_b].v0() - _n[n_s].v0();
  }else if (Umatch(x, "vbe ")) {
    return  _n[n_b].v0() - _n[n_e].v0();
  }else if (Umatch(x, "vbc ")) {
    return  _n[n_b].v0() - _n[n_c].v0();
  }else if (Umatch(x, "vbx ")) {
    return  _n[n_b].v0() - _n[n_ib].v0();
  }else if (Umatch(x, "vcs ")) {
    return  _n[n_c].v0() - _n[n_s].v0();
  }else if (Umatch(x, "vcb ")) {
    return  _n[n_c].v0() - _n[n_b].v0();
  }else if (Umatch(x, "vce ")) {
    return  _n[n_c].v0() - _n[n_e].v0();
  }else if (Umatch(x, "ves ")) {
    return  _n[n_e].v0() - _n[n_s].v0();
  }else if (Umatch(x, "veb ")) {
    return  _n[n_e].v0() - _n[n_b].v0();
  }else if (Umatch(x, "vec ")) {
    return  _n[n_e].v0() - _n[n_c].v0();
  }else if (Umatch(x, "vb ")) {
    return  _n[n_b].v0();
  }else if (Umatch(x, "vc ")) {
    return  _n[n_c].v0();
  }else if (Umatch(x, "ve ")) {
    return  _n[n_e].v0();
  }else if (Umatch(x, "vs ")) {
    return  _n[n_s].v0();
  }else if (Umatch(x, "vbi ")) {
    return  _n[n_ib].v0();
  }else if (Umatch(x, "vci ")) {
    return  _n[n_ic].v0();
  }else if (Umatch(x, "vei ")) {
    return  _n[n_ie].v0();
  }else if (Umatch(x, "i ")) {
    return  cce;
  }else if (Umatch(x, "ice ")) {
    return  cce;
  }else if (Umatch(x, "iceo{ffset} ")) {
    return  ccexxx;
  }else if (Umatch(x, "hoe ")) {
    return  go;
  }else if (Umatch(x, "ro{e} ")) {
    return  (go != 0.) ? 1/go : BIGBIG;
  }else if (Umatch(x, "ipi ")) {
    return  cpi;
  }else if (Umatch(x, "ipio{ffset} ")) {
    return  cpixxx;
  }else if (Umatch(x, "rpi ")) {
    return  (gpi != 0.) ? 1/gpi : BIGBIG;
  }else if (Umatch(x, "hie ")) {
    return  (gpi != 0.) ? 1/gpi : BIGBIG;
  }else if (Umatch(x, "imu ")) {
    return  cmu;
  }else if (Umatch(x, "imuo{ffset} ")) {
    return  cmuxxx;
  }else if (Umatch(x, "rmu ")) {
    return  (gmu != 0.) ? 1/gmu : BIGBIG;
  }else if (Umatch(x, "ib ")) {
    return  cpi + cmu;
  }else if (Umatch(x, "rx ")) {
    return  (gx != NA) ? 1/gx : 0.;
  }else if (Umatch(x, "ic ")) {
    return  cce - cmu;
  }else if (Umatch(x, "ie ")) {
    return  -cce -cpi;
  }else if (Umatch(x, "cbx ")) {
    return  cqbx;
  }else if (Umatch(x, "cbc ")) {
    return  cqbc;
  }else if (Umatch(x, "cmu ")) {
    return  cqbc;
  }else if (Umatch(x, "ccs ")) {
    return  cqcs;
  }else if (Umatch(x, "cbe ")) {
    return  cqbe;
  }else if (Umatch(x, "cpi ")) {
    return  cqbe;
  }else if (Umatch(x, "p ")) {
    return  CARD::probe(_Ice,"P") + CARD::probe(_Ipi,"P") + CARD::probe(_Imu,"P") + CARD::probe(_Rc,"P") + CARD::probe(_Re,"P") + CARD::probe(_Yb,"P") + CARD::probe(_Cbx,"P") + CARD::probe(_Cbc,"P") + CARD::probe(_Ccs,"P") + CARD::probe(_Cbe,"P");
  }else if (Umatch(x, "pd ")) {
    return  CARD::probe(_Ice,"PD") + CARD::probe(_Ipi,"PD") + CARD::probe(_Imu,"PD") + CARD::probe(_Rc,"PD") + CARD::probe(_Re,"PD") + CARD::probe(_Yb,"PD") + CARD::probe(_Cbx,"PD") + CARD::probe(_Cbc,"PD") + CARD::probe(_Ccs,"PD") + CARD::probe(_Cbe,"PD");
  }else if (Umatch(x, "ps ")) {
    return  CARD::probe(_Ice,"PS") + CARD::probe(_Ipi,"PS") + CARD::probe(_Imu,"PS") + CARD::probe(_Rc,"PS") + CARD::probe(_Re,"PS") + CARD::probe(_Yb,"PS") + CARD::probe(_Cbx,"PS") + CARD::probe(_Cbc,"PS") + CARD::probe(_Ccs,"PS") + CARD::probe(_Cbe,"PS");
  }else if (Umatch(x, "status ")) {
    return  static_cast<double>(converged() * 2);
  }else if (Umatch(x, "vbe ")) {
    return vbe;
  }else if (Umatch(x, "vbc ")) {
    return vbc;
  }else if (Umatch(x, "vbx ")) {
    return vbx;
  }else if (Umatch(x, "vcs ")) {
    return vcs;
  }else if (Umatch(x, "cce ")) {
    return cce;
  }else if (Umatch(x, "ccexxx ")) {
    return ccexxx;
  }else if (Umatch(x, "go ")) {
    return go;
  }else if (Umatch(x, "gm ")) {
    return gm;
  }else if (Umatch(x, "cpi ")) {
    return cpi;
  }else if (Umatch(x, "cpixxx ")) {
    return cpixxx;
  }else if (Umatch(x, "gpi ")) {
    return gpi;
  }else if (Umatch(x, "cmu ")) {
    return cmu;
  }else if (Umatch(x, "cmuxxx ")) {
    return cmuxxx;
  }else if (Umatch(x, "gmu ")) {
    return gmu;
  }else if (Umatch(x, "ixxxx ")) {
    return ixxxx;
  }else if (Umatch(x, "gx ")) {
    return gx;
  }else if (Umatch(x, "qbx ")) {
    return qbx;
  }else if (Umatch(x, "cqbx ")) {
    return cqbx;
  }else if (Umatch(x, "qbc ")) {
    return qbc;
  }else if (Umatch(x, "cqbc ")) {
    return cqbc;
  }else if (Umatch(x, "qcs ")) {
    return qcs;
  }else if (Umatch(x, "cqcs ")) {
    return cqcs;
  }else if (Umatch(x, "qbe ")) {
    return qbe;
  }else if (Umatch(x, "cqbe ")) {
    return cqbe;
  }else if (Umatch(x, "geqcb ")) {
    return geqcb;
  }else if (Umatch(x, "cexbc_0 ")) {
    return cexbc_0;
  }else if (Umatch(x, "cexbc_1 ")) {
    return cexbc_1;
  }else if (Umatch(x, "cexbc_2 ")) {
    return cexbc_2;
  }else if (Umatch(x, "_dt_0 ")) {
    return _dt_0;
  }else if (Umatch(x, "_dt_1 ")) {
    return _dt_1;
  }else {
    return BASE_SUBCKT::tr_probe_num(x);
  }
}
void DEV_BUILT_IN_BJT::tr_queue_eval () [inline, private, virtual]
Reimplemented from BASE_SUBCKT.
Definition at line 230 of file d_bjt.h.
References COMPONENT::q_eval(), and tr_needs_eval().
{if(tr_needs_eval()){q_eval();}}
void DEV_BUILT_IN_BJT::tr_regress () [inline, private, virtual]
Reimplemented from BASE_SUBCKT.
Definition at line 228 of file d_bjt.h.
References COMPONENT::set_not_converged().
{set_not_converged(); BASE_SUBCKT::tr_regress();}
std::string DEV_BUILT_IN_BJT::value_name () const [inline, private, virtual]
Implements CARD.
Definition at line 212 of file d_bjt.h.
{return "area";}
Member Data Documentation
COMPONENT* DEV_BUILT_IN_BJT::_Cbc
Definition at line 283 of file d_bjt.h.
Referenced by expand(), and tr_probe_num().
COMPONENT* DEV_BUILT_IN_BJT::_Cbcp
Definition at line 289 of file d_bjt.h.
Referenced by expand().
COMPONENT* DEV_BUILT_IN_BJT::_Cbe
Definition at line 285 of file d_bjt.h.
Referenced by expand(), and tr_probe_num().
COMPONENT* DEV_BUILT_IN_BJT::_Cbep
Definition at line 290 of file d_bjt.h.
Referenced by expand().
COMPONENT* DEV_BUILT_IN_BJT::_Cbs
Definition at line 291 of file d_bjt.h.
Referenced by expand().
COMPONENT* DEV_BUILT_IN_BJT::_Cbx
Definition at line 282 of file d_bjt.h.
Referenced by expand(), and tr_probe_num().
COMPONENT* DEV_BUILT_IN_BJT::_Ccs
Definition at line 284 of file d_bjt.h.
Referenced by expand(), and tr_probe_num().
int DEV_BUILT_IN_BJT::_count = -1 [static, private]
Definition at line 245 of file d_bjt.h.
Referenced by count(), DEV_BUILT_IN_BJT(), and ~DEV_BUILT_IN_BJT().
double DEV_BUILT_IN_BJT::_dt_0
Definition at line 276 of file d_bjt.h.
Referenced by MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::_dt_1
Definition at line 277 of file d_bjt.h.
Referenced by MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
COMPONENT* DEV_BUILT_IN_BJT::_Ice
Definition at line 279 of file d_bjt.h.
Referenced by expand(), and tr_probe_num().
COMPONENT* DEV_BUILT_IN_BJT::_Imu
Definition at line 281 of file d_bjt.h.
Referenced by expand(), and tr_probe_num().
COMPONENT* DEV_BUILT_IN_BJT::_Ipi
Definition at line 280 of file d_bjt.h.
Referenced by expand(), and tr_probe_num().
node_t DEV_BUILT_IN_BJT::_nodes[7] [private]
Definition at line 294 of file d_bjt.h.
Referenced by DEV_BUILT_IN_BJT().
COMPONENT* DEV_BUILT_IN_BJT::_Rc
Definition at line 286 of file d_bjt.h.
Referenced by expand(), and tr_probe_num().
COMPONENT* DEV_BUILT_IN_BJT::_Re
Definition at line 287 of file d_bjt.h.
Referenced by expand(), and tr_probe_num().
COMPONENT* DEV_BUILT_IN_BJT::_Yb
Definition at line 288 of file d_bjt.h.
Referenced by expand(), and tr_probe_num().
double DEV_BUILT_IN_BJT::cce
Definition at line 252 of file d_bjt.h.
Referenced by do_tr(), MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::ccexxx
Definition at line 253 of file d_bjt.h.
Referenced by do_tr(), expand(), MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::cexbc_0
Definition at line 273 of file d_bjt.h.
Referenced by MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::cexbc_1
Definition at line 274 of file d_bjt.h.
Referenced by MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::cexbc_2
Definition at line 275 of file d_bjt.h.
Referenced by MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::cmu
Definition at line 259 of file d_bjt.h.
Referenced by do_tr(), MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::cmuxxx
Definition at line 260 of file d_bjt.h.
Referenced by do_tr(), expand(), MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::cpi
Definition at line 256 of file d_bjt.h.
Referenced by do_tr(), MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::cpixxx
Definition at line 257 of file d_bjt.h.
Referenced by do_tr(), expand(), MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::cqbc
Definition at line 267 of file d_bjt.h.
Referenced by MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::cqbe
Definition at line 271 of file d_bjt.h.
Referenced by MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::cqbx
Definition at line 265 of file d_bjt.h.
Referenced by MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::cqcs
Definition at line 269 of file d_bjt.h.
Referenced by MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::geqcb
Definition at line 272 of file d_bjt.h.
Referenced by MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::gm
Definition at line 255 of file d_bjt.h.
Referenced by MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::gmu
Definition at line 261 of file d_bjt.h.
Referenced by MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::go
Definition at line 254 of file d_bjt.h.
Referenced by MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::gpi
Definition at line 258 of file d_bjt.h.
Referenced by MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::gx
Definition at line 263 of file d_bjt.h.
Referenced by MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::ixxxx
Definition at line 262 of file d_bjt.h.
Referenced by do_tr(), expand(), and tr_probe_num().
double DEV_BUILT_IN_BJT::qbc
Definition at line 266 of file d_bjt.h.
Referenced by do_tr(), expand(), MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::qbe
Definition at line 270 of file d_bjt.h.
Referenced by do_tr(), expand(), MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::qbx
Definition at line 264 of file d_bjt.h.
Referenced by do_tr(), expand(), MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::qcs
Definition at line 268 of file d_bjt.h.
Referenced by do_tr(), expand(), MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::vbc
Definition at line 249 of file d_bjt.h.
Referenced by do_tr(), MODEL_BUILT_IN_BJT::tr_eval(), tr_needs_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::vbe
Definition at line 248 of file d_bjt.h.
Referenced by do_tr(), MODEL_BUILT_IN_BJT::tr_eval(), tr_needs_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::vbx
Definition at line 250 of file d_bjt.h.
Referenced by do_tr(), MODEL_BUILT_IN_BJT::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_BJT::vcs
Definition at line 251 of file d_bjt.h.
Referenced by do_tr(), MODEL_BUILT_IN_BJT::tr_eval(), tr_needs_eval(), and tr_probe_num().
The documentation for this class was generated from the following files:
savant/gnucap/src/d_bjt.h
savant/gnucap/src/d_bjt.cc