gnucap: anonymous_namespace{d_vcvs.cc}::DEV_VCVS Class Reference
anonymous_namespace{d_vcvs.cc}::DEV_VCVS Class Reference
Public Member Functions
DEV_VCVS ()
Private Member Functions
DEV_VCVS (const DEV_VCVS &p)
char id_letter () const
std::string value_name () const
std::string dev_type () const
int max_nodes () const
int min_nodes () const
int matrix_nodes () const
int net_nodes () const
bool use_obsolete_callback_parse () const
CARD * clone () const
void precalc_last ()
void tr_iwant_matrix ()
void tr_begin ()
bool do_tr ()
void tr_load ()
void tr_unload ()
double tr_involts () const
double tr_involts_limited () const
void ac_iwant_matrix ()
void ac_begin ()
void do_ac ()
void ac_load ()
COMPLEX ac_involts () const
std::string port_name (int i) const
Detailed Description
Definition at line 30 of file d_vcvs.cc.
Constructor & Destructor Documentation
anonymous_namespace{d_vcvs.cc}::DEV_VCVS::DEV_VCVS (const DEV_VCVS & p) [inline, explicit, private]
Definition at line 32 of file d_vcvs.cc.
:ELEMENT(p) {}
anonymous_namespace{d_vcvs.cc}::DEV_VCVS::DEV_VCVS () [inline, explicit]
Definition at line 34 of file d_vcvs.cc.
:ELEMENT() {}
Member Function Documentation
void anonymous_namespace{d_vcvs.cc}::DEV_VCVS::ac_begin () [private, virtual]
Reimplemented from CARD.
Definition at line 109 of file d_vcvs.cc.
References OPT::shortckt.
{
  _loss1 = _loss0 = 1./OPT::shortckt;
  _ev = _y[0].f1;
  _acg = -_loss0 * _ev;
}
COMPLEX anonymous_namespace{d_vcvs.cc}::DEV_VCVS::ac_involts () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 57 of file d_vcvs.cc.
References IN1, and IN2.
{return _n[IN1]->vac() - _n[IN2]->vac();}
void anonymous_namespace{d_vcvs.cc}::DEV_VCVS::ac_iwant_matrix () [inline, private, virtual]
Implements ELEMENT.
Definition at line 53 of file d_vcvs.cc.
{ac_iwant_matrix_extended();}
void anonymous_namespace{d_vcvs.cc}::DEV_VCVS::ac_load () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 56 of file d_vcvs.cc.
{ac_load_shunt(); ac_load_active();}
CARD* anonymous_namespace{d_vcvs.cc}::DEV_VCVS::clone () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 44 of file d_vcvs.cc.
{return new DEV_VCVS(*this);}
std::string anonymous_namespace{d_vcvs.cc}::DEV_VCVS::dev_type () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 38 of file d_vcvs.cc.
{return "vcvs";}
void anonymous_namespace{d_vcvs.cc}::DEV_VCVS::do_ac () [private, virtual]
Reimplemented from CARD.
Definition at line 116 of file d_vcvs.cc.
{
  if (using_ac_eval()) {
    ac_eval();
    _acg = -_loss0 * _ev;
  }else{
    assert(_ev == _y[0].f1);
    assert(has_tr_eval() || _ev == double(value()));
  }
}
bool anonymous_namespace{d_vcvs.cc}::DEV_VCVS::do_tr () [private, virtual]
Reimplemented from CARD.
Definition at line 85 of file d_vcvs.cc.
References conchk(), converged, LINEAR, and OPT::shortckt.
{
  if (using_tr_eval()) {
    _y[0].x = _m0.x = tr_involts_limited();
    //_y[0].x = tr_input_limited();
    //assert(_y[0].x == _m0.x);
    tr_eval();
    assert(_y[0].f0 != LINEAR);
    store_values();
    q_load();
    _m0 = CPOLY1(_y[0]);
    _m0 *= -_loss0;
  }else{
    assert(conchk(_loss0, 1./OPT::shortckt));
    assert(_y[0].f0 == LINEAR);
    assert(_y[0].f1 == value());
    assert(conchk(_m0.c1, -_loss0 * _y[0].f1));
    assert(_m0.c0 == 0.);
    assert(_y1 == _y[0]);
    assert(converged());
  }
  return converged();
}
char anonymous_namespace{d_vcvs.cc}::DEV_VCVS::id_letter () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 36 of file d_vcvs.cc.
{return 'E';}
int anonymous_namespace{d_vcvs.cc}::DEV_VCVS::matrix_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 41 of file d_vcvs.cc.
{return 4;}
int anonymous_namespace{d_vcvs.cc}::DEV_VCVS::max_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 39 of file d_vcvs.cc.
{return 4;}
int anonymous_namespace{d_vcvs.cc}::DEV_VCVS::min_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 40 of file d_vcvs.cc.
{return 4;}
int anonymous_namespace{d_vcvs.cc}::DEV_VCVS::net_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 42 of file d_vcvs.cc.
{return 4;}
std::string anonymous_namespace{d_vcvs.cc}::DEV_VCVS::port_name (int i) const [inline, private, virtual]
Implements COMPONENT.
Definition at line 59 of file d_vcvs.cc.
{
    assert(i >= 0);
    assert(i < 4);
    static std::string names[] = {"p", "n", "ps", "ns"};
    return names[i];
  }
void anonymous_namespace{d_vcvs.cc}::DEV_VCVS::precalc_last () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 68 of file d_vcvs.cc.
References ELEMENT::precalc_last().
{
  ELEMENT::precalc_last();
  set_constant(!has_tr_eval());
  set_converged(!has_tr_eval());
}
void anonymous_namespace{d_vcvs.cc}::DEV_VCVS::tr_begin () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 75 of file d_vcvs.cc.
References OPT::shortckt, and ELEMENT::tr_begin().
{
  ELEMENT::tr_begin();
  _loss1 = _loss0 = 1./OPT::shortckt;
  _m0.x  = 0.;
  _m0.c1 = -_loss0 * _y[0].f1;
  _m0.c0 = 0.;
  _m1 = _m0;
}
double anonymous_namespace{d_vcvs.cc}::DEV_VCVS::tr_involts () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 51 of file d_vcvs.cc.
References dn_diff(), IN1, and IN2.
{return dn_diff(_n[IN1].v0(), _n[IN2].v0());}
double anonymous_namespace{d_vcvs.cc}::DEV_VCVS::tr_involts_limited () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 52 of file d_vcvs.cc.
References IN1, IN2, and volts_limited().
{return volts_limited(_n[IN1],_n[IN2]);}
void anonymous_namespace{d_vcvs.cc}::DEV_VCVS::tr_iwant_matrix () [inline, private, virtual]
Implements ELEMENT.
Definition at line 46 of file d_vcvs.cc.
{tr_iwant_matrix_extended();}
void anonymous_namespace{d_vcvs.cc}::DEV_VCVS::tr_load () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 49 of file d_vcvs.cc.
{tr_load_shunt(); tr_load_active();}
void anonymous_namespace{d_vcvs.cc}::DEV_VCVS::tr_unload () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 50 of file d_vcvs.cc.
References untested.
{untested();tr_unload_active();}
bool anonymous_namespace{d_vcvs.cc}::DEV_VCVS::use_obsolete_callback_parse () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 43 of file d_vcvs.cc.
{return true;}
std::string anonymous_namespace{d_vcvs.cc}::DEV_VCVS::value_name () const [inline, private, virtual]
Implements CARD.
Definition at line 37 of file d_vcvs.cc.
{return "gain";}
The documentation for this class was generated from the following file:
savant/gnucap/src/d_vcvs.cc