gnucap: EVAL_BM_SEMI_CAPACITOR Class Reference
EVAL_BM_SEMI_CAPACITOR Class Reference
Public Member Functions
EVAL_BM_SEMI_CAPACITOR (int c=0)
~EVAL_BM_SEMI_CAPACITOR ()
Private Member Functions
EVAL_BM_SEMI_CAPACITOR (const EVAL_BM_SEMI_CAPACITOR &p)
bool operator== (const COMMON_COMPONENT &) const
COMMON_COMPONENT * clone () const
void expand (const COMPONENT *)
void precalc_last (const CARD_LIST *)
Detailed Description
Definition at line 56 of file bmm_semi.cc.
Constructor & Destructor Documentation
EVAL_BM_SEMI_CAPACITOR::EVAL_BM_SEMI_CAPACITOR (const EVAL_BM_SEMI_CAPACITOR & p) [inline, explicit, private]
Definition at line 58 of file bmm_semi.cc.
Referenced by clone().
    :EVAL_BM_SEMI_BASE(p) {}
EVAL_BM_SEMI_CAPACITOR::EVAL_BM_SEMI_CAPACITOR (int c = 0) [inline, explicit]
Definition at line 61 of file bmm_semi.cc.
    :EVAL_BM_SEMI_BASE(c) {}
EVAL_BM_SEMI_CAPACITOR::~EVAL_BM_SEMI_CAPACITOR () [inline]
Definition at line 63 of file bmm_semi.cc.
{}
Member Function Documentation
COMMON_COMPONENT* EVAL_BM_SEMI_CAPACITOR::clone () const [inline, private, virtual]
Implements EVAL_BM_SEMI_BASE.
Definition at line 66 of file bmm_semi.cc.
References EVAL_BM_SEMI_CAPACITOR().
{return new EVAL_BM_SEMI_CAPACITOR(*this);}
void EVAL_BM_SEMI_CAPACITOR::expand (const COMPONENT * d) [private, virtual]
Reimplemented from EVAL_BM_SEMI_BASE.
Definition at line 252 of file bmm_semi.cc.
References CARD::long_label(), COMMON_COMPONENT::model(), COMMON_COMPONENT::modelname(), and unreachable.
{
  EVAL_BM_SEMI_BASE::expand(d);
  const MODEL_SEMI_CAPACITOR* m = dynamic_cast<const MODEL_SEMI_CAPACITOR*>(model());
  if (!m) {
    unreachable();
    throw Exception_Model_Type_Mismatch(d->long_label(), modelname(), "semi-capacitor (C)");
  }else{
  }
}
bool EVAL_BM_SEMI_CAPACITOR::operator== (const COMMON_COMPONENT & x) const [private, virtual]
Reimplemented from EVAL_BM_SEMI_BASE.
Definition at line 239 of file bmm_semi.cc.
References anonymous_namespace{c_genrat.cc}::p, and untested.
{
  const EVAL_BM_SEMI_CAPACITOR*
    p = dynamic_cast<const EVAL_BM_SEMI_CAPACITOR*>(&x);
  bool rv = p
    && EVAL_BM_SEMI_BASE::operator==(x);
  if (rv) {
    untested();
  }else{
  }
  return rv;
}
void EVAL_BM_SEMI_CAPACITOR::precalc_last (const CARD_LIST * Scope) [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 264 of file bmm_semi.cc.
References MODEL_SEMI_CAPACITOR::_cj, MODEL_SEMI_CAPACITOR::_cjsw, MODEL_SEMI_BASE::_defw, EVAL_BM_SEMI_BASE::_length, MODEL_SEMI_BASE::_narrow, MODEL_SEMI_BASE::_tc1, MODEL_SEMI_BASE::_tc2, COMMON_COMPONENT::_temp_c, MODEL_CARD::_tnom_c, EVAL_BM_SEMI_BASE::_value, EVAL_BM_SEMI_BASE::_width, COMMON_COMPONENT::model(), COMMON_COMPONENT::modelname(), NOT_INPUT, prechecked_cast, untested, and width.
{
  assert(Scope);
  EVAL_BM_SEMI_BASE::precalc_last(Scope);
  const MODEL_SEMI_CAPACITOR* m = prechecked_cast<const MODEL_SEMI_CAPACITOR*>(model());
  double width = (_width == NOT_INPUT) ? m->_defw : _width;
  double eff_width = width - m->_narrow;
  double eff_length = _length - m->_narrow;
  _value = m->_cj * eff_length * eff_width + 2. * m->_cjsw * (eff_length + eff_width);
  double tempdiff = (_temp_c - m->_tnom_c);
  _value *= 1 + m->_tc1*tempdiff + m->_tc2*tempdiff*tempdiff;
  if (eff_width <= 0.) {untested();
    throw Exception_Precalc(modelname() + ": effective width is negative or zero\n");
  }else{
  }
  if (eff_length <= 0.) {untested();
    throw Exception_Precalc(modelname() + ": effective length is negative or zero\n");
  }else{
  }
}
The documentation for this class was generated from the following file:
savant/gnucap/src/bmm_semi.cc