gnucap: COMMON_COMPONENT Class Reference
COMMON_COMPONENT Class Reference
#include <e_compon.h>
Public Member Functions
virtual ~COMMON_COMPONENT ()
void attach_model (const COMPONENT *) const
COMMON_COMPONENT & attach (const MODEL_CARD *m)
void set_modelname (const std::string &n)
void parse_modelname (CS &)
virtual COMMON_COMPONENT * clone () const =0
virtual bool use_obsolete_callback_parse () const
virtual bool use_obsolete_callback_print () const
virtual void parse_common_obsolete_callback (CS &)
virtual void print_common_obsolete_callback (OMSTREAM &, LANGUAGE *) const
virtual bool has_parse_params_obsolete_callback () const
virtual bool is_trivial () const
virtual bool param_is_printable (int) const
virtual std::string param_name (int) const
virtual std::string param_name (int, int) const
virtual std::string param_value (int) const
virtual void set_param_by_name (std::string, std::string)
void Set_param_by_name (std::string, std::string)
virtual void set_param_by_index (int, std::string &, int)
virtual int param_count () const
virtual void precalc_first (const CARD_LIST *)
virtual void expand (const COMPONENT *)
virtual COMMON_COMPONENT * deflate ()
virtual void precalc_last (const CARD_LIST *)
virtual void tr_eval (ELEMENT *) const
virtual void ac_eval (ELEMENT *) const
virtual TIME_PAIR tr_review (COMPONENT *)
virtual void tr_accept (COMPONENT *)
virtual bool has_tr_eval () const
virtual bool has_ac_eval () const
virtual bool parse_numlist (CS &)
virtual bool parse_params_obsolete_callback (CS &)
virtual void skip_type_tail (CS &) const
virtual std::string name () const =0
virtual bool operator== (const COMMON_COMPONENT &x) const
bool operator!= (const COMMON_COMPONENT &x) const
std::string modelname () const
const MODEL_CARD * model () const
bool has_model () const
const PARAMETER< double > & mfactor () const
const PARAMETER< double > & value () const
Static Public Member Functions
static void attach_common (COMMON_COMPONENT *c, COMMON_COMPONENT **to)
static void detach_common (COMMON_COMPONENT **from)
Protected Member Functions
COMMON_COMPONENT (const COMMON_COMPONENT &p)
COMMON_COMPONENT (int c)
Protected Attributes
PARAMETER< double > _tnom_c
PARAMETER< double > _dtemp
PARAMETER< double > _temp_c
PARAMETER< double > _mfactor
PARAMETER< double > _value
Private Member Functions
COMMON_COMPONENT & operator= (const COMMON_COMPONENT &)
COMMON_COMPONENT ()
bool parse_param_list (CS &)
Private Attributes
std::string _modelname
const MODEL_CARD * _model
int _attach_count
Detailed Description
Definition at line 58 of file e_compon.h.
Constructor & Destructor Documentation
COMMON_COMPONENT::COMMON_COMPONENT () [inline, explicit, private]
Definition at line 75 of file e_compon.h.
References incomplete, and unreachable.
{unreachable();incomplete();}
COMMON_COMPONENT::COMMON_COMPONENT (const COMMON_COMPONENT & p) [explicit, protected]
Definition at line 29 of file e_compon.cc.
  :_tnom_c(p._tnom_c),
   _dtemp(p._dtemp),
   _temp_c(p._temp_c),
   _mfactor(p._mfactor),
   _value(p._value),
   _modelname(p._modelname),
   _model(p._model),
   _attach_count(0)
{
}
COMMON_COMPONENT::COMMON_COMPONENT (int c) [explicit, protected]
Definition at line 41 of file e_compon.cc.
  :_tnom_c(NOT_INPUT),
   _dtemp(0),
   _temp_c(NOT_INPUT),
   _mfactor(1),
   _value(0),
   _modelname(),
   _model(0),
   _attach_count(c)
{
}
COMMON_COMPONENT::~COMMON_COMPONENT () [virtual]
Definition at line 53 of file e_compon.cc.
References _attach_count, CC_STATIC, and trace1.
{
  trace1("common,destruct", _attach_count);
  assert(_attach_count == 0 || _attach_count == CC_STATIC);
}
Member Function Documentation
void COMMON_COMPONENT::ac_eval (ELEMENT * x) const [virtual]
Reimplemented in EVAL_BM_ACTION_BASE, anonymous_namespace{bm_cond.cc}::EVAL_BM_COND, anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL, anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX, and anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR.
Definition at line 288 of file e_compon.cc.
References _model, MODEL_CARD::ac_eval(), and untested.
Referenced by ELEMENT::ac_eval().
{untested();
  assert(_model);
  _model->ac_eval(x);
}
COMMON_COMPONENT& COMMON_COMPONENT::attach (const MODEL_CARD * m) [inline]
Definition at line 83 of file e_compon.h.
{_model = m; return *this;}
void COMMON_COMPONENT::attach_common (COMMON_COMPONENT * c, COMMON_COMPONENT ** to) [static]
Definition at line 59 of file e_compon.cc.
References _attach_count, detach_common(), trace1, and untested.
Referenced by COMPONENT::attach_common(), CARDSTASH::CARDSTASH(), anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::EVAL_BM_COND(), anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::EVAL_BM_MODEL(), anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::expand(), anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::expand(), CARDSTASH::operator=(), and anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::parse_common_obsolete_callback().
{
  assert(to);
  if (c == *to) {
    // The new and old are the same object.  Do nothing.
  }else if (!c) {untested();
    // There is no new common.  probably a simple element
    detach_common(to);
  }else if (!*to) {
    // No old one, but have a new one.
    ++(c->_attach_count);
    trace1("++1", c->_attach_count);
    *to = c;
  }else if (*c != **to) {
    // They are different, usually by edit.
    detach_common(to);
    ++(c->_attach_count);
    trace1("++2", c->_attach_count);
    *to = c;
  }else if (c->_attach_count == 0) {
    // The new and old are identical.
    // Use the old one.
    // The new one is not used anywhere, so throw it away.
    trace1("delete", c->_attach_count);
    delete c;
  }else{untested();
    // The new and old are identical.
    // Use the old one.
    // The new one is also used somewhere else, so keep it.
  }
}
void COMMON_COMPONENT::attach_model (const COMPONENT * d) const
Definition at line 109 of file e_compon.cc.
References _model, COMPONENT::find_model(), and modelname().
Referenced by anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::expand(), EVAL_BM_TABLE::expand(), and EVAL_BM_SEMI_BASE::expand().
{
  assert(d);
  _model = d->find_model(modelname());
  assert(_model);
}
virtual COMMON_COMPONENT* COMMON_COMPONENT::clone () const [pure virtual]
Implemented in LOGIC_NONE, LOGIC_INV, LOGIC_XNOR, LOGIC_XOR, LOGIC_NOR, LOGIC_OR, LOGIC_NAND, LOGIC_AND, COMMON_SUBCKT, EVAL_BM_VALUE, EVAL_BM_SEMI_RESISTOR, EVAL_BM_SEMI_CAPACITOR, anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN, anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM, anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP, anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE, anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT, anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE, anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY, anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY, anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL, anonymous_namespace{d_switch.cc}::COMMON_SWITCH, EVAL_BM_SEMI_BASE, anonymous_namespace{bm_cond.cc}::EVAL_BM_COND, anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH, EVAL_BM_TABLE, anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL, anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX, and anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR.
Referenced by anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::expand(), COMPONENT::expand(), EVAL_BM_ACTION_BASE::parse_func_type(), COMPONENT::set_dev_type(), COMPONENT::set_param_by_index(), and COMPONENT::set_param_by_name().
virtual COMMON_COMPONENT* COMMON_COMPONENT::deflate () [inline, virtual]
Reimplemented in anonymous_namespace{bm_cond.cc}::EVAL_BM_COND, and anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL.
Definition at line 107 of file e_compon.h.
Referenced by anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::deflate(), anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::deflate(), COMPONENT::deflate_common(), anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::expand(), COMPONENT::expand(), and anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_element_using_obsolete_callback().
{return this;}
void COMMON_COMPONENT::detach_common (COMMON_COMPONENT ** from) [static]
Definition at line 91 of file e_compon.cc.
References trace1.
Referenced by attach_common(), COMPONENT::detach_common(), CARDSTASH::operator=(), CARDSTASH::~CARDSTASH(), and anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::~EVAL_BM_COND().
{
  assert(from);
  if (*from) {
    assert((**from)._attach_count > 0);
    --((**from)._attach_count);
    trace1("--", (**from)._attach_count);
    if ((**from)._attach_count == 0) {
      trace1("delete", (**from)._attach_count);
      delete *from;
    }else{
      trace1("nodelete", (**from)._attach_count);
    }
    *from = NULL;
  }else{
  }
}
virtual void COMMON_COMPONENT::expand (const COMPONENT *) [inline, virtual]
Reimplemented in EVAL_BM_SEMI_RESISTOR, EVAL_BM_SEMI_CAPACITOR, anonymous_namespace{bm_cond.cc}::EVAL_BM_COND, EVAL_BM_SEMI_BASE, anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL, and EVAL_BM_TABLE.
Definition at line 106 of file e_compon.h.
Referenced by anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::expand(), anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::expand(), and COMPONENT::expand().
{}
virtual bool COMMON_COMPONENT::has_ac_eval () const [inline, virtual]
Reimplemented in EVAL_BM_BASE.
Definition at line 115 of file e_compon.h.
References untested.
{untested(); return false;}
bool COMMON_COMPONENT::has_model () const [inline]
Definition at line 127 of file e_compon.h.
Referenced by anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::expand(), and anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::parse_common_obsolete_callback().
{return _model;}
virtual bool COMMON_COMPONENT::has_parse_params_obsolete_callback () const [inline, virtual]
Reimplemented in EVAL_BM_BASE.
Definition at line 93 of file e_compon.h.
Referenced by set_param_by_name(), and Set_param_by_name().
{return false;}
virtual bool COMMON_COMPONENT::has_tr_eval () const [inline, virtual]
Reimplemented in EVAL_BM_BASE.
Definition at line 114 of file e_compon.h.
References untested.
{untested(); return false;}
virtual bool COMMON_COMPONENT::is_trivial () const [inline, virtual]
Reimplemented in EVAL_BM_VALUE.
Definition at line 94 of file e_compon.h.
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_element_using_obsolete_callback().
{return false;}
const PARAMETER<double>& COMMON_COMPONENT::mfactor () const [inline]
Definition at line 128 of file e_compon.h.
Referenced by COMPONENT::obsolete_move_parameters_from_common(), and COMPONENT::precalc_first().
{return _mfactor;}
const MODEL_CARD* COMMON_COMPONENT::model () const [inline]
Definition at line 126 of file e_compon.h.
Referenced by anonymous_namespace{d_switch.cc}::SWITCH_BASE::do_tr(), anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::expand(), EVAL_BM_TABLE::expand(), DEV_LOGIC::expand(), EVAL_BM_SEMI_CAPACITOR::expand(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::expand(), EVAL_BM_SEMI_RESISTOR::expand(), EVAL_BM_SEMI_CAPACITOR::precalc_last(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::precalc_last(), EVAL_BM_SEMI_RESISTOR::precalc_last(), DEV_LOGIC::tr_accept(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_advance(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_begin(), EVAL_BM_TABLE::tr_eval(), DEV_LOGIC::tr_eval_digital(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_regress(), and anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_review().
{assert(_model); return _model;}
std::string COMMON_COMPONENT::modelname () const [inline]
Definition at line 125 of file e_compon.h.
Referenced by attach_model(), BASE_SUBCKT::dev_type(), anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::expand(), EVAL_BM_TABLE::expand(), DEV_LOGIC::expand(), EVAL_BM_SEMI_CAPACITOR::expand(), EVAL_BM_SEMI_RESISTOR::expand(), DEV_SUBCKT::expand(), EVAL_BM_TABLE::name(), EVAL_BM_SEMI_BASE::name(), EVAL_BM_VALUE::precalc_first(), EVAL_BM_SEMI_CAPACITOR::precalc_last(), EVAL_BM_SEMI_RESISTOR::precalc_last(), anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::print_common_obsolete_callback(), EVAL_BM_TABLE::print_common_obsolete_callback(), and EVAL_BM_SEMI_BASE::print_common_obsolete_callback().
{return _modelname;}
virtual std::string COMMON_COMPONENT::name () const [pure virtual]
Implemented in LOGIC_NONE, LOGIC_INV, LOGIC_XNOR, LOGIC_XOR, LOGIC_NOR, LOGIC_OR, LOGIC_NAND, LOGIC_AND, COMMON_SUBCKT, EVAL_BM_VALUE, anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN, anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM, anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE, anonymous_namespace{bm_cond.cc}::EVAL_BM_COND, anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP, anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE, anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT, anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY, anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL, anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY, EVAL_BM_SEMI_BASE, anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH, anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL, anonymous_namespace{d_switch.cc}::COMMON_SWITCH, EVAL_BM_TABLE, anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX, and anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR.
Referenced by DEV_LOGIC::expand().
bool COMMON_COMPONENT::operator!= (const COMMON_COMPONENT & x) const [inline]
Definition at line 124 of file e_compon.h.
{return !(*this == x);}
COMMON_COMPONENT& COMMON_COMPONENT::operator= (const COMMON_COMPONENT &) [inline, private]
Definition at line 73 of file e_compon.h.
References unreachable.
                              {unreachable(); return *this;}
bool COMMON_COMPONENT::operator== (const COMMON_COMPONENT & x) const [virtual]
Reimplemented in COMMON_LOGIC, COMMON_SUBCKT, EVAL_BM_VALUE, EVAL_BM_SEMI_RESISTOR, EVAL_BM_ACTION_BASE, EVAL_BM_SEMI_CAPACITOR, anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN, anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM, anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP, anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE, anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT, anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE, anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY, anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY, anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL, anonymous_namespace{d_switch.cc}::COMMON_SWITCH, EVAL_BM_SEMI_BASE, anonymous_namespace{bm_cond.cc}::EVAL_BM_COND, anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH, EVAL_BM_TABLE, EVAL_BM_BASE, anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL, anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX, and anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR.
Definition at line 294 of file e_compon.cc.
References _dtemp, _mfactor, _model, _modelname, _temp_c, _tnom_c, and _value.
Referenced by anonymous_namespace{d_switch.cc}::COMMON_SWITCH::operator==().
{
  return (_modelname == x._modelname
          && _model == x._model
          && _tnom_c == x._tnom_c
          && _dtemp == x._dtemp
          && _temp_c == x._temp_c
          && _mfactor == x._mfactor
          && _value == x._value);
}
virtual int COMMON_COMPONENT::param_count () const [inline, virtual]
Reimplemented in COMMON_SUBCKT, anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE, and anonymous_namespace{d_switch.cc}::COMMON_SWITCH.
Definition at line 103 of file e_compon.h.
Referenced by anonymous_namespace{d_switch.cc}::COMMON_SWITCH::param_count(), anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::param_count(), COMMON_SUBCKT::param_count(), COMMON_SUBCKT::param_is_printable(), anonymous_namespace{d_switch.cc}::COMMON_SWITCH::param_name(), anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::param_name(), COMMON_SUBCKT::param_name(), COMMON_SUBCKT::param_value(), set_param_by_name(), and Set_param_by_name().
{return 4;}
bool COMMON_COMPONENT::param_is_printable (int i) const [virtual]
Reimplemented in COMMON_SUBCKT, anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE, and anonymous_namespace{d_switch.cc}::COMMON_SWITCH.
Definition at line 234 of file e_compon.cc.
References _dtemp, _mfactor, _temp_c, _tnom_c, and PARAMETER< T >::has_hard_value().
Referenced by anonymous_namespace{d_switch.cc}::COMMON_SWITCH::param_is_printable(), and COMPONENT::param_is_printable().
{
  switch (i) {
  case 0:  return _tnom_c.has_hard_value();
  case 1:  return _dtemp.has_hard_value();
  case 2:  return _temp_c.has_hard_value();
  case 3:  return _mfactor.has_hard_value();
  default: return false;
  }
}
std::string COMMON_COMPONENT::param_name (int i) const [virtual]
Reimplemented in COMMON_SUBCKT, anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE, and anonymous_namespace{d_switch.cc}::COMMON_SWITCH.
Definition at line 245 of file e_compon.cc.
Referenced by anonymous_namespace{d_switch.cc}::COMMON_SWITCH::param_name(), param_name(), COMPONENT::param_name(), set_param_by_name(), and Set_param_by_name().
{
  switch (i) {
  case 0:  return "tnom";
  case 1:  return "dtemp";
  case 2:  return "temp";
  case 3:  return "m";
  default: return "";
  }
}
std::string COMMON_COMPONENT::param_name (int i, int j) const [virtual]
Reimplemented in COMMON_SUBCKT, anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE, and anonymous_namespace{d_switch.cc}::COMMON_SWITCH.
Definition at line 256 of file e_compon.cc.
References param_name().
{
  return (j==0) ? param_name(i) : "";
}
std::string COMMON_COMPONENT::param_value (int i) const [virtual]
Reimplemented in COMMON_SUBCKT, anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE, and anonymous_namespace{d_switch.cc}::COMMON_SWITCH.
Definition at line 261 of file e_compon.cc.
References _dtemp, _mfactor, _temp_c, _tnom_c, and PARAMETER< T >::string().
Referenced by anonymous_namespace{d_switch.cc}::COMMON_SWITCH::param_value(), and COMPONENT::param_value().
{
  switch (i) {
  case 0:  return _tnom_c.string();
  case 1:  return _dtemp.string();
  case 2:  return _temp_c.string();
  case 3:  return _mfactor.string();
  default: return "";
  }
}
void COMMON_COMPONENT::parse_common_obsolete_callback (CS & cmd) [virtual]
Reimplemented in anonymous_namespace{bm_cond.cc}::EVAL_BM_COND, and anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL.
Definition at line 132 of file e_compon.cc.
References CS::cursor(), CS::gotit(), CS::is_alpha(), parse_numlist(), parse_param_list(), CS::skip1b(), untested, and CS::warn().
Referenced by anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::expand(), anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::parse_common_obsolete_callback(), and anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_element_using_obsolete_callback().
{
  if (cmd.skip1b('(')) {
    // start with a paren
    unsigned start = cmd.cursor();
    parse_param_list(cmd);
    if (cmd.gotit(start)) {             // ( params ( ....
      // named args before num list
      if (cmd.skip1b('(')) {            // ( params ( list ) params )
        parse_numlist(cmd);
        if (!cmd.skip1b(')')) {untested();
          cmd.warn(bWARNING, "need )");
        }else{
        }
      }else{                            // ( params list params )
        parse_numlist(cmd);             //BUG//
      }
      parse_param_list(cmd);
      if (!cmd.skip1b(')')) {untested();
        cmd.warn(bWARNING, "need )");
      }else{
      }
    }else{
      // no named args before num list
      // but there's a paren
      // not sure whether it belongs to all args or to num list
      if (cmd.skip1b('(')) {            // ( ( list ) params )
        // two parens
        parse_numlist(cmd);
        if (!cmd.skip1b(')')) {untested();
          cmd.warn(bWARNING, "need )");
        }else{
        }
        parse_param_list(cmd);
        if (!cmd.skip1b(')')) {untested();
          cmd.warn(bWARNING, "need )");
        }else{
        }
      }else{                            // ( list ...
        // only one paren
        parse_numlist(cmd);
        if (cmd.skip1b(')')) {          // ( list ) params
          // assume it belongs to num list
          // and named params follow
          parse_param_list(cmd);
        }else{                          // ( list params )
          // assume it belongs to all args
          parse_param_list(cmd);
          if (!cmd.skip1b(')')) {
            cmd.warn(bWARNING, "need )");
          }else{
          }
        }
      }
    }
  }else{
    // does not start with a paren
    unsigned start = cmd.cursor();
    parse_param_list(cmd);
    if (cmd.gotit(start)) {
      if (cmd.skip1b('(')) {            // params ( list ) params
        parse_numlist(cmd);
        if (!cmd.skip1b(')')) {untested();
          cmd.warn(bWARNING, "need )");
        }else{
        }
      }else if (!(cmd.is_alpha())) {    // params list params
        parse_numlist(cmd);
      }else{                            // params   (only)
      }
    }else{                              // list params
      assert(!(cmd.skip1b('(')));
      parse_numlist(cmd);
    }
    parse_param_list(cmd);
    if (cmd.skip1b(')')) {
      cmd.warn(bWARNING, start, "need (");
    }else{
    }
  }
}
void COMMON_COMPONENT::parse_modelname (CS & cmd)
Definition at line 116 of file e_compon.cc.
References CS::ctos(), set_modelname(), and TOKENTERM.
Referenced by anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::parse_common_obsolete_callback().
{
  set_modelname(cmd.ctos(TOKENTERM));
}
bool COMMON_COMPONENT::parse_numlist (CS &) [virtual]
Reimplemented in EVAL_BM_VALUE, anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN, anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM, anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP, anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE, anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT, anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY, anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL, anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY, anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH, anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX, and anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR.
Definition at line 353 of file e_compon.cc.
Referenced by parse_common_obsolete_callback().
{
  return false;
}
bool COMMON_COMPONENT::parse_param_list (CS & cmd) [private]
Definition at line 122 of file e_compon.cc.
References CS::cursor(), CS::gotit(), CS::more(), parse_params_obsolete_callback(), and CS::stuck().
Referenced by parse_common_obsolete_callback().
{
  unsigned start = cmd.cursor();
  unsigned here = cmd.cursor();
  do{
    parse_params_obsolete_callback(cmd); //BUG//callback
  }while (cmd.more() && !cmd.stuck(&here));
  return cmd.gotit(start);
}
bool COMMON_COMPONENT::parse_params_obsolete_callback (CS & cmd) [virtual]
Reimplemented in EVAL_BM_VALUE, EVAL_BM_ACTION_BASE, anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN, anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM, anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP, anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE, anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT, anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY, anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL, anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY, EVAL_BM_SEMI_BASE, and anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH.
Definition at line 358 of file e_compon.cc.
References _dtemp, _mfactor, _temp_c, _tnom_c, Get(), and ONE_OF.
Referenced by parse_param_list(), and set_param_by_name().
{
  return ONE_OF
    || Get(cmd, "tnom",   &_tnom_c)
    || Get(cmd, "dtemp",  &_dtemp)
    || Get(cmd, "temp",   &_temp_c)
    || Get(cmd, "m",      &_mfactor)
    || Get(cmd, "mfactor",&_mfactor)
    ;
}
void COMMON_COMPONENT::precalc_first (const CARD_LIST * Scope) [virtual]
Reimplemented in COMMON_SUBCKT, EVAL_BM_VALUE, EVAL_BM_ACTION_BASE, anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN, anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE, anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM, anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP, anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE, anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT, anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY, anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY, anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL, anonymous_namespace{bm_cond.cc}::EVAL_BM_COND, EVAL_BM_SEMI_BASE, and anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH.
Definition at line 272 of file e_compon.cc.
References _dtemp, _mfactor, CKT_BASE::_sim, _temp_c, _tnom_c, _value, PARAMETER< T >::e_val(), and OPT::tnom_c.
Referenced by anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::precalc_first(), and COMPONENT::precalc_first().
{
  assert(Scope);
  _tnom_c.e_val(OPT::tnom_c, Scope);
  _dtemp.e_val(0., Scope);
  _temp_c.e_val(CKT_BASE::_sim->_temp_c + _dtemp, Scope);
  _mfactor.e_val(1, Scope);
  _value.e_val(0, Scope);
}
virtual void COMMON_COMPONENT::precalc_last (const CARD_LIST *) [inline, virtual]
Reimplemented in COMMON_SUBCKT, EVAL_BM_SEMI_RESISTOR, EVAL_BM_SEMI_CAPACITOR, anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE, anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT, anonymous_namespace{bm_cond.cc}::EVAL_BM_COND, and anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL.
Definition at line 108 of file e_compon.h.
Referenced by anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::precalc_last(), and COMPONENT::precalc_last().
{}
void COMMON_COMPONENT::print_common_obsolete_callback (OMSTREAM & o, LANGUAGE * lang) const [virtual]
Reimplemented in EVAL_BM_VALUE, EVAL_BM_ACTION_BASE, anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN, anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM, anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP, anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE, anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT, anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY, anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY, anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL, anonymous_namespace{bm_cond.cc}::EVAL_BM_COND, EVAL_BM_SEMI_BASE, anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH, anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL, EVAL_BM_TABLE, anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX, and anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR.
Definition at line 214 of file e_compon.cc.
References _dtemp, _mfactor, _temp_c, _tnom_c, PARAMETER< T >::has_hard_value(), and print_pair().
Referenced by COMPONENT::print_args_obsolete_callback(), anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::print_common_obsolete_callback(), and anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::print_common_obsolete_callback().
{
  assert(lang);
  print_pair(o, lang, "tnom", _tnom_c,  _tnom_c.has_hard_value());
  print_pair(o, lang, "dtemp",_dtemp,   _dtemp.has_hard_value());
  print_pair(o, lang, "temp", _temp_c,  _temp_c.has_hard_value());
  print_pair(o, lang, "m",    _mfactor, _mfactor.has_hard_value());
}
void COMMON_COMPONENT::set_modelname (const std::string & n) [inline]
Definition at line 84 of file e_compon.h.
Referenced by anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::expand(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_logic_using_obsolete_callback(), parse_modelname(), and COMPONENT::set_dev_type().
{_modelname = n;}
void COMMON_COMPONENT::set_param_by_index (int i, std::string & Value, int Offset) [virtual]
Reimplemented in anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE.
Definition at line 223 of file e_compon.cc.
References _dtemp, _mfactor, _temp_c, and _tnom_c.
Referenced by COMPONENT::set_param_by_index(), set_param_by_name(), and Set_param_by_name().
{
  switch (i) {
  case 0:  _tnom_c = Value; break;
  case 1:  _dtemp = Value; break;
  case 2:  _temp_c = Value; break;
  case 3:  _mfactor = Value; break;
  default: throw Exception_Too_Many(i, 3, Offset); break;
  }
}
void COMMON_COMPONENT::set_param_by_name (std::string Name, std::string Value) [virtual]
Reimplemented in COMMON_SUBCKT.
Definition at line 305 of file e_compon.cc.
References CS::_STRING, has_parse_params_obsolete_callback(), itested, param_count(), param_name(), parse_params_obsolete_callback(), set_param_by_index(), Umatch(), and untested.
Referenced by COMPONENT::set_param_by_name().
{
  if (has_parse_params_obsolete_callback()) {untested();
    std::string args(Name + "=" + Value);
    CS cmd(CS::_STRING, args); //obsolete_callback
    bool ok = parse_params_obsolete_callback(cmd); //BUG//callback
    if (!ok) {untested();
      throw Exception_No_Match(Name);
    }else{untested();
    }
  }else{
    //BUG// ugly linear search
    for (int i = param_count() - 1;  i >= 0;  --i) {
      for (int j = 0;  param_name(i,j) != "";  ++j) {
        if (Umatch(Name, param_name(i,j) + ' ')) {
          set_param_by_index(i, Value, 0/*offset*/);
          return; //success
        }else{
          //keep looking
        }
      }
    }
    itested();
    throw Exception_No_Match(Name);
  }
}
void COMMON_COMPONENT::Set_param_by_name (std::string Name, std::string Value)
Definition at line 335 of file e_compon.cc.
References has_parse_params_obsolete_callback(), param_count(), param_name(), set_param_by_index(), and Umatch().
{
  assert(!has_parse_params_obsolete_callback());
  //BUG// ugly linear search
  for (int i = COMMON_COMPONENT::param_count() - 1;  i >= 0;  --i) {
    for (int j = 0;  COMMON_COMPONENT::param_name(i,j) != "";  ++j) {
      if (Umatch(Name, COMMON_COMPONENT::param_name(i,j) + ' ')) {
        COMMON_COMPONENT::set_param_by_index(i, Value, 0/*offset*/);
        return; //success
      }else{
        //keep looking
      }
    }
  }
  throw Exception_No_Match(Name);
}
virtual void COMMON_COMPONENT::skip_type_tail (CS &) const [inline, virtual]
Reimplemented in anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL, and anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY.
Definition at line 119 of file e_compon.h.
Referenced by EVAL_BM_ACTION_BASE::parse_func_type().
{}
virtual void COMMON_COMPONENT::tr_accept (COMPONENT *) [inline, virtual]
Reimplemented in anonymous_namespace{bm_cond.cc}::EVAL_BM_COND.
Definition at line 113 of file e_compon.h.
Referenced by COMPONENT::tr_accept().
{}
void COMMON_COMPONENT::tr_eval (ELEMENT * x) const [virtual]
Reimplemented in EVAL_BM_VALUE, anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN, anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM, anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP, anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT, anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE, anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY, anonymous_namespace{bm_cond.cc}::EVAL_BM_COND, anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL, anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY, EVAL_BM_SEMI_BASE, anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH, anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL, EVAL_BM_TABLE, anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX, and anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR.
Definition at line 282 of file e_compon.cc.
References _model, MODEL_CARD::tr_eval(), and untested.
Referenced by EVAL_BM_ACTION_BASE::ac_eval(), and ELEMENT::tr_eval().
{untested();
  assert(_model);
  _model->tr_eval(x);
}
virtual TIME_PAIR COMMON_COMPONENT::tr_review (COMPONENT *) [inline, virtual]
Reimplemented in anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN, anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM, anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP, anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE, anonymous_namespace{bm_cond.cc}::EVAL_BM_COND, and anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL.
Definition at line 112 of file e_compon.h.
References NEVER.
Referenced by COMPONENT::tr_review().
{return TIME_PAIR(NEVER,NEVER);}
virtual bool COMMON_COMPONENT::use_obsolete_callback_parse () const [inline, virtual]
Reimplemented in EVAL_BM_BASE.
Definition at line 89 of file e_compon.h.
Referenced by COMPONENT::use_obsolete_callback_parse().
{return false;}
virtual bool COMMON_COMPONENT::use_obsolete_callback_print () const [inline, virtual]
Reimplemented in EVAL_BM_BASE.
Definition at line 90 of file e_compon.h.
Referenced by COMPONENT::use_obsolete_callback_print().
{return false;}
const PARAMETER<double>& COMMON_COMPONENT::value () const [inline]
Definition at line 129 of file e_compon.h.
Referenced by COMPONENT::obsolete_move_parameters_from_common().
{return _value;}
Member Data Documentation
int COMMON_COMPONENT::_attach_count [private]
Definition at line 68 of file e_compon.h.
Referenced by attach_common(), and ~COMMON_COMPONENT().
PARAMETER<double> COMMON_COMPONENT::_dtemp [protected]
Definition at line 61 of file e_compon.h.
Referenced by EVAL_BM_VALUE::is_trivial(), operator==(), param_is_printable(), param_value(), parse_params_obsolete_callback(), precalc_first(), print_common_obsolete_callback(), and set_param_by_index().
PARAMETER<double> COMMON_COMPONENT::_mfactor [protected]
Definition at line 63 of file e_compon.h.
Referenced by operator==(), param_is_printable(), param_value(), parse_params_obsolete_callback(), precalc_first(), COMMON_SUBCKT::precalc_first(), print_common_obsolete_callback(), and set_param_by_index().
const MODEL_CARD* COMMON_COMPONENT::_model [mutable, private]
Definition at line 67 of file e_compon.h.
Referenced by ac_eval(), attach_model(), operator==(), and tr_eval().
std::string COMMON_COMPONENT::_modelname [private]
Definition at line 66 of file e_compon.h.
Referenced by operator==().
PARAMETER<double> COMMON_COMPONENT::_temp_c [protected]
Definition at line 62 of file e_compon.h.
Referenced by EVAL_BM_VALUE::is_trivial(), operator==(), param_is_printable(), param_value(), parse_params_obsolete_callback(), precalc_first(), EVAL_BM_SEMI_CAPACITOR::precalc_last(), EVAL_BM_SEMI_RESISTOR::precalc_last(), print_common_obsolete_callback(), set_param_by_index(), and EVAL_BM_ACTION_BASE::temp_adjust().
PARAMETER<double> COMMON_COMPONENT::_tnom_c [protected]
Definition at line 60 of file e_compon.h.
Referenced by EVAL_BM_VALUE::is_trivial(), operator==(), param_is_printable(), param_value(), parse_params_obsolete_callback(), precalc_first(), print_common_obsolete_callback(), set_param_by_index(), and EVAL_BM_ACTION_BASE::temp_adjust().
PARAMETER<double> COMMON_COMPONENT::_value [protected]
Reimplemented in EVAL_BM_SEMI_BASE, and anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX.
Definition at line 64 of file e_compon.h.
Referenced by operator==(), EVAL_BM_VALUE::parse_numlist(), EVAL_BM_VALUE::parse_params_obsolete_callback(), EVAL_BM_VALUE::precalc_first(), precalc_first(), EVAL_BM_VALUE::print_common_obsolete_callback(), and EVAL_BM_VALUE::tr_eval().
The documentation for this class was generated from the following files:
savant/gnucap/src/e_compon.h
savant/gnucap/src/e_compon.cc