gnucap: savant/gnucap/src/e_node.h File Reference
savant/gnucap/src/e_node.h File Reference
#include "u_sim_data.h"
#include "e_base.h"
Classes
class LOGICVAL
class NODE
class LOGIC_NODE
class node_t
Defines
#define qBAD (0)
#define qGOOD (OPT::transits)
Enumerations
enum {
OUT1 = 0, OUT2 = 1, IN1 = 2, IN2 = 3,
NODES_PER_BRANCH = 4, INVALID_NODE = -1
}
enum _LOGICVAL {
lvSTABLE0, lvRISING, lvFALLING, lvSTABLE1,
lvUNKNOWN
}
enum { lvNUM_STATES = lvUNKNOWN+1 }
Functions
INTERFACE double volts_limited (const node_t &n1, const node_t &n2)
Variables
NODE ground_node
Define Documentation
#define qBAD (0)
Definition at line 40 of file e_node.h.
Referenced by LOGIC_NODE::set_bad_quality().
#define qGOOD (OPT::transits)
Definition at line 41 of file e_node.h.
Referenced by LOGIC_NODE::improve_quality(), LOGIC_NODE::set_good_quality(), DEV_LOGIC::want_analog(), and DEV_LOGIC::want_digital().
Enumeration Type Documentation
anonymous enum
Enumerator:
OUT1
OUT2
IN1
IN2
NODES_PER_BRANCH
INVALID_NODE
Definition at line 32 of file e_node.h.
     {
  OUT1 = 0,
  OUT2 = 1,
  IN1 = 2,
  IN2 = 3,
  NODES_PER_BRANCH = 4,
  INVALID_NODE = -1
};
anonymous enum
Enumerator:
lvNUM_STATES
Definition at line 44 of file e_node.h.
{lvNUM_STATES = lvUNKNOWN+1};
enum _LOGICVAL
Enumerator:
lvSTABLE0
lvRISING
lvFALLING
lvSTABLE1
lvUNKNOWN
Definition at line 43 of file e_node.h.
{lvSTABLE0,lvRISING,lvFALLING,lvSTABLE1,lvUNKNOWN};
Function Documentation
INTERFACE double volts_limited (const node_t & n1, const node_t & n2)
Referenced by anonymous_namespace{d_vcvs.cc}::DEV_VCVS::tr_involts_limited(), anonymous_namespace{d_vcr.cc}::DEV_VCR::tr_involts_limited(), anonymous_namespace{d_vcg.cc}::DEV_VCG::tr_involts_limited(), anonymous_namespace{d_cap.cc}::DEV_TRANSCAP::tr_involts_limited(), anonymous_namespace{d_admit.cc}::DEV_VCCS::tr_involts_limited(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_involts_limited(), and anonymous_namespace{d_cap.cc}::DEV_VCCAP::tr_involts_limited().
Variable Documentation
NODE ground_node
Referenced by NODE::ac_probe_ext(), NODE_MAP::NODE_MAP(), and NODE::tr_probe_num().