gnucap: Quoted_String Class Reference
Quoted_String Class Reference
#include <m_base.h>
Public Member Functions
void parse (CS &)
Quoted_String (CS &file)
Quoted_String ()
Detailed Description
Definition at line 282 of file m_base.h.
Constructor & Destructor Documentation
Quoted_String::Quoted_String (CS & file) [inline, explicit]
Definition at line 288 of file m_base.h.
References parse(), and untested.
{untested();parse(file);}
Quoted_String::Quoted_String () [inline, explicit]
Definition at line 289 of file m_base.h.
References untested.
{untested();}
Member Function Documentation
void Quoted_String::parse (CS & File) [virtual]
Reimplemented from String.
Definition at line 70 of file m_base_in.cc.
References String::_data, CS::ctoc(), CS::cursor(), CS::more(), CS::skip1(), CS::skipbl(), untested, and CS::warn().
Referenced by Quoted_String().
{untested();
  File.skipbl();
  unsigned here = File.cursor();
  char quote = File.ctoc();
  _data = "";
  for (;;) {untested();
    if (File.skip1(quote)) {untested();
      break;
    }else if (!File.more()) {untested();
      File.warn(0, "end of file in quoted string");
      File.warn(0, here, "string begins here");
      break;
    }else{untested();
      _data += File.ctoc();
    }
  }
  File.skipbl();
}
The documentation for this class was generated from the following files:
savant/gnucap/src/m_base.h
savant/gnucap/src/m_base_in.cc