gnucap: BASE_SUBCKT Class Reference
BASE_SUBCKT Class Reference
#include <e_subckt.h>
Protected Member Functions
BASE_SUBCKT ()
BASE_SUBCKT (const BASE_SUBCKT &p)
~BASE_SUBCKT ()
std::string dev_type () const
int tail_size () const
int matrix_nodes () const
int net_nodes () const
void tr_begin ()
void tr_restore ()
void dc_advance ()
void tr_advance ()
void tr_regress ()
bool tr_needs_eval () const
void tr_queue_eval ()
bool do_tr ()
void tr_load ()
TIME_PAIR tr_review ()
void tr_accept ()
void tr_unload ()
void ac_begin ()
void do_ac ()
void ac_load ()
Detailed Description
Definition at line 29 of file e_subckt.h.
Constructor & Destructor Documentation
BASE_SUBCKT::BASE_SUBCKT () [inline, explicit, protected]
Definition at line 31 of file e_subckt.h.
    :COMPONENT() {}
BASE_SUBCKT::BASE_SUBCKT (const BASE_SUBCKT & p) [inline, explicit, protected]
Definition at line 33 of file e_subckt.h.
    :COMPONENT(p) {}
BASE_SUBCKT::~BASE_SUBCKT () [inline, protected]
Definition at line 35 of file e_subckt.h.
{}
Member Function Documentation
void BASE_SUBCKT::ac_begin () [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 64 of file e_subckt.h.
References CARD_LIST::ac_begin(), and CARD::subckt().
{assert(subckt()); subckt()->ac_begin();}
void BASE_SUBCKT::ac_load () [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 66 of file e_subckt.h.
References CARD_LIST::ac_load(), and CARD::subckt().
{assert(subckt()); subckt()->ac_load();}
void BASE_SUBCKT::dc_advance () [inline, protected, virtual]
Reimplemented from CARD.
Reimplemented in DEV_BUILT_IN_BJT, and DEV_BUILT_IN_MOS.
Definition at line 52 of file e_subckt.h.
References CARD_LIST::dc_advance(), and CARD::subckt().
{assert(subckt()); subckt()->dc_advance();}
std::string BASE_SUBCKT::dev_type () const [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 38 of file e_subckt.h.
References COMPONENT::common(), and COMMON_COMPONENT::modelname().
{assert(common()); return common()->modelname();}
void BASE_SUBCKT::do_ac () [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 65 of file e_subckt.h.
References CARD_LIST::do_ac(), and CARD::subckt().
{assert(subckt()); subckt()->do_ac();}
bool BASE_SUBCKT::do_tr () [inline, protected, virtual]
Reimplemented from CARD.
Reimplemented in DEV_BUILT_IN_BJT, and DEV_BUILT_IN_MOS.
Definition at line 58 of file e_subckt.h.
References COMPONENT::converged(), do_tr(), COMPONENT::set_converged(), and CARD::subckt().
Referenced by do_tr().
        {assert(subckt());set_converged(subckt()->do_tr());return converged();}
int BASE_SUBCKT::matrix_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Reimplemented in DEV_SUBCKT.
Definition at line 43 of file e_subckt.h.
{return 0;}
int BASE_SUBCKT::net_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Reimplemented in DEV_BUILT_IN_DIODE, DEV_BUILT_IN_MOS, and DEV_SUBCKT.
Definition at line 44 of file e_subckt.h.
References CARD::_net_nodes.
{return _net_nodes;}
int BASE_SUBCKT::tail_size () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 39 of file e_subckt.h.
{return 1;}
void BASE_SUBCKT::tr_accept () [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 62 of file e_subckt.h.
References CARD::subckt(), and CARD_LIST::tr_accept().
{assert(subckt()); subckt()->tr_accept();}
void BASE_SUBCKT::tr_advance () [inline, protected, virtual]
Reimplemented from CARD.
Reimplemented in DEV_BUILT_IN_BJT, and DEV_BUILT_IN_MOS.
Definition at line 53 of file e_subckt.h.
References CARD::subckt(), and CARD_LIST::tr_advance().
{assert(subckt()); subckt()->tr_advance();}
void BASE_SUBCKT::tr_begin () [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 50 of file e_subckt.h.
References CARD::subckt(), and CARD_LIST::tr_begin().
{assert(subckt()); subckt()->tr_begin();}
void BASE_SUBCKT::tr_load () [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 60 of file e_subckt.h.
References CARD::subckt(), and CARD_LIST::tr_load().
{assert(subckt()); subckt()->tr_load();}
bool BASE_SUBCKT::tr_needs_eval () const [inline, protected, virtual]
Reimplemented from CARD.
Reimplemented in DEV_BUILT_IN_BJT, and DEV_BUILT_IN_MOS.
Definition at line 55 of file e_subckt.h.
References CARD::subckt(), and CARD_LIST::tr_needs_eval().
        {assert(subckt()); return subckt()->tr_needs_eval();}
void BASE_SUBCKT::tr_queue_eval () [inline, protected, virtual]
Reimplemented from COMPONENT.
Reimplemented in DEV_BUILT_IN_BJT, and DEV_BUILT_IN_MOS.
Definition at line 57 of file e_subckt.h.
References CARD::subckt(), and CARD_LIST::tr_queue_eval().
{assert(subckt()); subckt()->tr_queue_eval();}
void BASE_SUBCKT::tr_regress () [inline, protected, virtual]
Reimplemented from CARD.
Reimplemented in DEV_BUILT_IN_BJT, and DEV_BUILT_IN_MOS.
Definition at line 54 of file e_subckt.h.
References CARD::subckt(), and CARD_LIST::tr_regress().
{assert(subckt()); subckt()->tr_regress();}
void BASE_SUBCKT::tr_restore () [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 51 of file e_subckt.h.
References CARD::subckt(), and CARD_LIST::tr_restore().
{assert(subckt()); subckt()->tr_restore();}
TIME_PAIR BASE_SUBCKT::tr_review () [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 61 of file e_subckt.h.
References COMPONENT::_time_by, CARD::subckt(), and CARD_LIST::tr_review().
{assert(subckt()); return _time_by = subckt()->tr_review();}
void BASE_SUBCKT::tr_unload () [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 63 of file e_subckt.h.
References CARD::subckt(), and CARD_LIST::tr_unload().
{assert(subckt()); subckt()->tr_unload();}
The documentation for this class was generated from the following file:
savant/gnucap/src/e_subckt.h