gnucap: DEV_BUILT_IN_DIODE Class Reference
DEV_BUILT_IN_DIODE Class Reference
#include <d_diode.h>
Public Member Functions
DEV_BUILT_IN_DIODE ()
~DEV_BUILT_IN_DIODE ()
Static Public Member Functions
static int count ()
Public Attributes
region_t _region
double _gd
double _isat
COMPONENT * _Cj
COMPONENT * _Yj
COMPONENT * _Rs
Private Types
enum { n_a, n_c, n_ia }
Private Member Functions
DEV_BUILT_IN_DIODE (const DEV_BUILT_IN_DIODE &p)
char id_letter () const
bool print_type_in_spice () const
std::string value_name () const
int max_nodes () const
int min_nodes () const
int net_nodes () const
int int_nodes () const
CARD * clone () const
void precalc_first ()
void expand ()
void precalc_last ()
double tr_probe_num (const std::string &) const
std::string port_name (int i) const
Private Attributes
node_t _nodes [3]
Static Private Attributes
static int _count = -1
Detailed Description
Definition at line 177 of file d_diode.h.
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
n_a
n_c
n_ia
Definition at line 230 of file d_diode.h.
{n_a, n_c, n_ia};
Constructor & Destructor Documentation
DEV_BUILT_IN_DIODE::DEV_BUILT_IN_DIODE (const DEV_BUILT_IN_DIODE & p) [explicit, private]
Definition at line 890 of file d_diode.cc.
References _count, CARD::_n, _nodes, int_nodes(), and max_nodes().
  :BASE_SUBCKT(p),
   // input parameters,
   // calculated parameters,
   _region(p._region),
   _gd(p._gd),
   _isat(p._isat),
   // netlist,
   _Cj(0),
   _Yj(0),
   _Rs(0)
{
  _n = _nodes;
  for (int ii = 0; ii < max_nodes() + int_nodes(); ++ii) {
    _n[ii] = p._n[ii];
  }
  ++_count;
  // overrides
}
DEV_BUILT_IN_DIODE::DEV_BUILT_IN_DIODE () [explicit]
Definition at line 872 of file d_diode.cc.
References _count, CARD::_n, _nodes, COMPONENT::attach_common(), and Default_BUILT_IN_DIODE.
Referenced by clone().
  :BASE_SUBCKT(),
   // input parameters,
   // calculated parameters,
   _region(UNKNOWN),
   _gd(NA),
   _isat(NA),
   // netlist,
   _Cj(0),
   _Yj(0),
   _Rs(0)
{
  _n = _nodes;
  attach_common(&Default_BUILT_IN_DIODE);
  ++_count;
  // overrides
}
DEV_BUILT_IN_DIODE::~DEV_BUILT_IN_DIODE () [inline]
Definition at line 182 of file d_diode.h.
References _count.
{--_count;}
Member Function Documentation
CARD* DEV_BUILT_IN_DIODE::clone () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 193 of file d_diode.h.
References DEV_BUILT_IN_DIODE().
{return new DEV_BUILT_IN_DIODE(*this);}
static int DEV_BUILT_IN_DIODE::count () [inline, static]
Definition at line 216 of file d_diode.h.
References _count.
{return _count;}
void DEV_BUILT_IN_DIODE::expand () [private, virtual]
Reimplemented from COMPONENT.
Definition at line 910 of file d_diode.cc.
References _Cj, CARD::_n, _Rs, CKT_BASE::_sim, _Yj, COMMON_BUILT_IN_DIODE::cj_adjusted, COMMON_BUILT_IN_DIODE::cjsw_adjusted, CARD::clone(), COMPONENT::common(), anonymous_namespace{d_admit.cc}::device_dispatcher, CARD_LIST::erase(), Eval_Cj, Eval_Yj, CARD_LIST::expand(), CARD::is_constant(), SIM_DATA::is_first_expand(), CARD::long_label(), COMMON_COMPONENT::model(), CARD::n_(), n_a, n_c, n_ia, node_t::new_model_node(), CARD::new_subckt(), anonymous_namespace{c_genrat.cc}::p, precalc_first(), precalc_last(), prechecked_cast, CARD_LIST::push_front(), COMMON_BUILT_IN_DIODE::rs_adjusted, OPT::rstray, COMMON_BUILT_IN_DIODE::sdp(), COMPONENT::set_parameters(), and CARD::subckt().
{
  BASE_SUBCKT::expand(); // calls common->expand, attached model
  assert(_n);
  assert(common());
  const COMMON_BUILT_IN_DIODE* c = static_cast<const COMMON_BUILT_IN_DIODE*>(common());
  assert(c);
  assert(c->model());
  const MODEL_BUILT_IN_DIODE* m = prechecked_cast<const MODEL_BUILT_IN_DIODE*>(c->model());
  assert(m);
  assert(c->sdp());
  const SDP_BUILT_IN_DIODE* s = prechecked_cast<const SDP_BUILT_IN_DIODE*>(c->sdp());
  assert(s);
  if (!subckt()) {
    new_subckt();
  }else{
  }
  if (_sim->is_first_expand()) {
    precalc_first();
    precalc_last();
    // local nodes
    //assert(!(_n[n_ia].n_()));
    //BUG// this assert fails on a repeat elaboration after a change.
    //not sure of consequences when new_model_node called twice.
    if (!(_n[n_ia].n_())) {
      if (!OPT::rstray || c->rs_adjusted==0.) {
        _n[n_ia] = _n[n_a];
      }else{
        _n[n_ia].new_model_node("." + long_label() + ".ia", this);
      }
    }else{
      if (!OPT::rstray || c->rs_adjusted==0.) {
        assert(_n[n_ia] == _n[n_a]);
      }else{
        //_n[n_ia].new_model_node("ia." + long_label(), this);
      }
    }
    // clone subckt elements
    if (c->cj_adjusted == 0. && c->cjsw_adjusted == 0. && m->tt == 0.) {
      if (_Cj) {
        subckt()->erase(_Cj);
        _Cj = NULL;
      }else{
      }
    }else{
      if (!_Cj) {
        const CARD* p = device_dispatcher["capacitor"];
        assert(p);
        _Cj = dynamic_cast<COMPONENT*>(p->clone());
        assert(_Cj);
        subckt()->push_front(_Cj);
      }else{
      }
      {
        node_t nodes[] = {_n[n_ia], _n[n_c]};
      _Cj->set_parameters("Cj", this, &Eval_Cj, 0., 0, NULL, 2, nodes);
      }
    }
    {
      if (!_Yj) {
        const CARD* p = device_dispatcher["admittance"];
        assert(p);
        _Yj = dynamic_cast<COMPONENT*>(p->clone());
        assert(_Yj);
        subckt()->push_front(_Yj);
      }else{
      }
      {
        node_t nodes[] = {_n[n_ia], _n[n_c]};
      _Yj->set_parameters("Yj", this, &Eval_Yj, 0., 0, NULL, 2, nodes);
      }
    }
    if (!OPT::rstray || c->rs_adjusted==0.) {
      if (_Rs) {
        subckt()->erase(_Rs);
        _Rs = NULL;
      }else{
      }
    }else{
      if (!_Rs) {
        const CARD* p = device_dispatcher["resistor"];
        assert(p);
        _Rs = dynamic_cast<COMPONENT*>(p->clone());
        assert(_Rs);
        subckt()->push_front(_Rs);
      }else{
      }
      {
        node_t nodes[] = {_n[n_a], _n[n_ia]};
      _Rs->set_parameters("Rs", this, NULL, c->rs_adjusted, 0, NULL, 2, nodes);
      }
    }
  }else{
    //precalc();
  }
  //precalc();
  subckt()->expand();
  //subckt()->precalc();
  assert(!is_constant());
}
char DEV_BUILT_IN_DIODE::id_letter () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 184 of file d_diode.h.
References untested.
{untested();return 'D';}
int DEV_BUILT_IN_DIODE::int_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 192 of file d_diode.h.
Referenced by DEV_BUILT_IN_DIODE().
{return 1;}
int DEV_BUILT_IN_DIODE::max_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 188 of file d_diode.h.
Referenced by DEV_BUILT_IN_DIODE().
{return 2;}
int DEV_BUILT_IN_DIODE::min_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 189 of file d_diode.h.
{return 2;}
int DEV_BUILT_IN_DIODE::net_nodes () const [inline, private, virtual]
Reimplemented from BASE_SUBCKT.
Definition at line 191 of file d_diode.h.
{return 2;}
std::string DEV_BUILT_IN_DIODE::port_name (int i) const [inline, private, virtual]
Implements COMPONENT.
Definition at line 232 of file d_diode.h.
{
    assert(i >= 0);
    assert(i < 2);
    static std::string names[] = {"a", "c", ""};
    return names[i];
  }
void DEV_BUILT_IN_DIODE::precalc_first () [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 194 of file d_diode.h.
References CARD_LIST::precalc_first(), and CARD::subckt().
Referenced by expand().
{COMPONENT::precalc_first(); if(subckt()) subckt()->precalc_first();}
void DEV_BUILT_IN_DIODE::precalc_last () [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 196 of file d_diode.h.
References CARD_LIST::precalc_last(), and CARD::subckt().
Referenced by expand().
{COMPONENT::precalc_last(); assert(subckt()); subckt()->precalc_last();}
bool DEV_BUILT_IN_DIODE::print_type_in_spice () const [inline, private, virtual]
Implements COMPONENT.
Definition at line 185 of file d_diode.h.
{return true;}
double DEV_BUILT_IN_DIODE::tr_probe_num (const std::string & x) const [private, virtual]
Reimplemented from COMPONENT.
Definition at line 1013 of file d_diode.cc.
References _Cj, _gd, _isat, SIM_DATA::_lu, CARD::_n, _region, _Rs, CKT_BASE::_sim, _Yj, COMPONENT::common(), COMPONENT::mfactor(), COMMON_COMPONENT::model(), n_a, n_c, n_ia, port_impedance(), prechecked_cast, CKT_BASE::probe(), COMMON_BUILT_IN_DIODE::sdp(), Umatch(), and node_t::v0().
{
  assert(_n);
  const COMMON_BUILT_IN_DIODE* c = prechecked_cast<const COMMON_BUILT_IN_DIODE*>(common());
  assert(c);
  const MODEL_BUILT_IN_DIODE* m = prechecked_cast<const MODEL_BUILT_IN_DIODE*>(c->model());
  assert(m);
  const SDP_BUILT_IN_DIODE* s = prechecked_cast<const SDP_BUILT_IN_DIODE*>(c->sdp());
  assert(s);
  if (Umatch(x, "v{d} ")) {
    return  _n[n_a].v0() - _n[n_c].v0();
  }else if (Umatch(x, "i{d} ")) {
    return  CARD::probe(_Yj,"I") + CARD::probe(_Cj,"I");
  }else if (Umatch(x, "vj ")) {
    return  _n[n_ia].v0() - _n[n_c].v0();
  }else if (Umatch(x, "vsr ")) {
    return  _n[n_a].v0() - _n[n_ia].v0();
  }else if (Umatch(x, "vrs ")) {
    return  _n[n_a].v0() - _n[n_ia].v0();
  }else if (Umatch(x, "ij ")) {
    return  CARD::probe(_Yj,"I");
  }else if (Umatch(x, "ic ")) {
    return  CARD::probe(_Cj,"I");
  }else if (Umatch(x, "capcur ")) {
    return  CARD::probe(_Cj,"I");
  }else if (Umatch(x, "p ")) {
    return  CARD::probe(_Yj,"P") + CARD::probe(_Cj,"P") + CARD::probe(_Rs,"P");
  }else if (Umatch(x, "pd ")) {
    return  CARD::probe(_Yj,"PD") + CARD::probe(_Cj,"PD") + CARD::probe(_Rs,"PD");
  }else if (Umatch(x, "ps ")) {
    return  CARD::probe(_Yj,"PS") + CARD::probe(_Cj,"PS") + CARD::probe(_Rs,"PS");
  }else if (Umatch(x, "pj ")) {
    return  CARD::probe(_Yj,"P");
  }else if (Umatch(x, "pc ")) {
    return  CARD::probe(_Cj,"P");
  }else if (Umatch(x, "c{apacitance} ")) {
    return  CARD::probe(_Cj,"Capacitance");
  }else if (Umatch(x, "cd ")) {
    return  CARD::probe(_Cj,"Capacitance");
  }else if (Umatch(x, "charge ")) {
    return  CARD::probe(_Cj,"Charge");
  }else if (Umatch(x, "r{eq} ")) {
    return  CARD::probe(_Yj,"R") + CARD::probe(_Rs,"R");
  }else if (Umatch(x, "g{eq} ")) {
    return  (( CARD::probe(_Yj,"R") + CARD::probe(_Rs,"R") ) != 0) ? (1./( CARD::probe(_Yj,"R") + CARD::probe(_Rs,"R") )) : CARD::probe(_Yj,"Y");
  }else if (Umatch(x, "gd ")) {
    return  CARD::probe(_Yj,"Y");
  }else if (Umatch(x, "y ")) {
    return  ( CARD::probe(_Rs,"R") != 0. && ( CARD::probe(_Yj,"Y") + CARD::probe(_Cj,"Y") ) != 0) ? 1./((1./( CARD::probe(_Yj,"Y") + CARD::probe(_Cj,"Y") )) + CARD::probe(_Rs,"R") ) : CARD::probe(_Yj,"Y") + CARD::probe(_Cj,"Y");
  }else if (Umatch(x, "z ")) {
    return  port_impedance( _n[n_a] , _n[n_c] ,_sim->_lu,mfactor()*tr_probe_num("Y"));
  }else if (Umatch(x, "zraw ")) {
    return  port_impedance( _n[n_a] , _n[n_c] , _sim->_lu, 0.);
  }else if (Umatch(x, "region ")) {
    return  static_cast<double>(_region);
  }else if (Umatch(x, "_region ")) {
    return _region;
  }else if (Umatch(x, "_gd ")) {
    return _gd;
  }else if (Umatch(x, "_isat ")) {
    return _isat;
  }else {
    return BASE_SUBCKT::tr_probe_num(x);
  }
}
std::string DEV_BUILT_IN_DIODE::value_name () const [inline, private, virtual]
Implements CARD.
Definition at line 186 of file d_diode.h.
{return "area";}
Member Data Documentation
COMPONENT* DEV_BUILT_IN_DIODE::_Cj
Definition at line 226 of file d_diode.h.
Referenced by expand(), and tr_probe_num().
int DEV_BUILT_IN_DIODE::_count = -1 [static, private]
Definition at line 219 of file d_diode.h.
Referenced by count(), DEV_BUILT_IN_DIODE(), and ~DEV_BUILT_IN_DIODE().
double DEV_BUILT_IN_DIODE::_gd
Definition at line 223 of file d_diode.h.
Referenced by EVAL_BUILT_IN_DIODE_Cj::tr_eval(), EVAL_BUILT_IN_DIODE_Yj::tr_eval(), and tr_probe_num().
double DEV_BUILT_IN_DIODE::_isat
Definition at line 224 of file d_diode.h.
Referenced by EVAL_BUILT_IN_DIODE_Yj::tr_eval(), and tr_probe_num().
node_t DEV_BUILT_IN_DIODE::_nodes[3] [private]
Definition at line 231 of file d_diode.h.
Referenced by DEV_BUILT_IN_DIODE().
region_t DEV_BUILT_IN_DIODE::_region
Definition at line 222 of file d_diode.h.
Referenced by EVAL_BUILT_IN_DIODE_Yj::tr_eval(), and tr_probe_num().
COMPONENT* DEV_BUILT_IN_DIODE::_Rs
Definition at line 228 of file d_diode.h.
Referenced by expand(), and tr_probe_num().
COMPONENT* DEV_BUILT_IN_DIODE::_Yj
Definition at line 227 of file d_diode.h.
Referenced by expand(), and tr_probe_num().
The documentation for this class was generated from the following files:
savant/gnucap/src/d_diode.h
savant/gnucap/src/d_diode.cc