gnucap: savant/gnucap/src/l_pmatch.cc File Reference
savant/gnucap/src/l_pmatch.cc File Reference
#include "ap.h"
#include "l_lib.h"
Functions
bool Umatch (const std::string &str1, const std::string &str2)
Function Documentation
bool Umatch (const std::string & str1, const std::string & str2)
Definition at line 35 of file l_pmatch.cc.
References CS::_STRING, and CS::umatch().
Referenced by ELEMENT::ac_probe_ext(), NODE::ac_probe_ext(), CKT_BASE::ac_probe_num(), anonymous_namespace{c_sweep.cc}::buildfile(), LANGUAGE::find_proto(), PROBE::probe_node(), CARD::set_dev_type(), COMMON_COMPONENT::set_param_by_name(), COMMON_COMPONENT::Set_param_by_name(), CARD::set_param_by_name(), STORAGE::tr_probe_num(), anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::tr_probe_num(), ELEMENT::tr_probe_num(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_probe_num(), DEV_SUBCKT::tr_probe_num(), NODE::tr_probe_num(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_probe_num(), LOGIC_NODE::tr_probe_num(), COMPONENT::tr_probe_num(), DEV_SPICE::tr_probe_num(), and xopen().
{
  CS cmd(CS::_STRING, str1); //call to CS member on string
  if (cmd.umatch(str2)) {
    return true;
  }else{
    return 0;
  }
}