gnucap: savant/gnucap/src/d_mos.cc File Reference
savant/gnucap/src/d_mos.cc File Reference
#include "u_limit.h"
#include "e_storag.h"
#include "d_mos_base.h"
#include "globals.h"
#include "e_elemnt.h"
#include "d_mos.h"
Namespaces
namespace DEV_BUILT_IN_MOS_DISPATCHER
Functions
const double NA (NOT_INPUT)
const double INF (BIGBIG)
Variables
static COMMON_BUILT_IN_MOS Default_BUILT_IN_MOS (CC_STATIC)
static DEV_BUILT_IN_MOS DEV_BUILT_IN_MOS_DISPATCHER::p0
static DISPATCHER< CARD >
::INSTALL d0 & DEV_BUILT_IN_MOS_DISPATCHER::device_dispatcher
static EVAL_BUILT_IN_MOS_Cgb Eval_Cgb (CC_STATIC)
static EVAL_BUILT_IN_MOS_Cgd Eval_Cgd (CC_STATIC)
static EVAL_BUILT_IN_MOS_Cgs Eval_Cgs (CC_STATIC)
Function Documentation
const double INF (BIGBIG)
const double NA (NOT_INPUT)
Variable Documentation
COMMON_BUILT_IN_MOS Default_BUILT_IN_MOS(CC_STATIC) [static]
Referenced by DEV_BUILT_IN_MOS::DEV_BUILT_IN_MOS().
EVAL_BUILT_IN_MOS_Cgb Eval_Cgb(CC_STATIC) [static]
Referenced by DEV_BUILT_IN_MOS::expand().
EVAL_BUILT_IN_MOS_Cgd Eval_Cgd(CC_STATIC) [static]
Referenced by DEV_BUILT_IN_MOS::expand().
EVAL_BUILT_IN_MOS_Cgs Eval_Cgs(CC_STATIC) [static]
Referenced by DEV_BUILT_IN_MOS::expand().