gnucap: anonymous_namespace{lang_verilog.cc} Namespace Reference
anonymous_namespace{lang_verilog.cc} Namespace Reference
Classes
class LANG_VERILOG
class CMD_PARAMSET
class CMD_MODULE
class CMD_VERILOG
Functions
DISPATCHER< LANGUAGE >::INSTALL d & language_dispatcher (),&lang_verilog
static void parse_type (CS &cmd, CARD *x)
static void parse_args_paramset (CS &cmd, MODEL_CARD *x)
static void parse_args_instance (CS &cmd, CARD *x)
static void parse_label (CS &cmd, CARD *x)
static void parse_ports (CS &cmd, COMPONENT *x)
static void print_type (OMSTREAM &o, const COMPONENT *x)
static void print_label (OMSTREAM &o, const COMPONENT *x)
static void print_ports_long (OMSTREAM &o, const COMPONENT *x)
static void print_ports_short (OMSTREAM &o, const COMPONENT *x)
Variables
anonymous_namespace{lang_verilog.cc}::LANG_VERILOG lang_verilog
anonymous_namespace{lang_verilog.cc}::CMD_PARAMSET p1
DISPATCHER< CMD >::INSTALL d1 & command_dispatcher
anonymous_namespace{lang_verilog.cc}::CMD_MODULE p2
anonymous_namespace{lang_verilog.cc}::CMD_VERILOG p8
Function Documentation
DISPATCHER<LANGUAGE>::INSTALL d& anonymous_namespace{lang_verilog.cc}::language_dispatcher ()
static void anonymous_namespace{lang_verilog.cc}::parse_args_instance (CS & cmd, CARD * x) [static]
Definition at line 115 of file lang_verilog.cc.
References CS::ctos(), CS::cursor(), CS::is_alnum(), CARD::long_label(), CS::match1(), CARD::param_count(), CARD::set_param_by_index(), CARD::set_param_by_name(), untested, and CS::warn().
Referenced by anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_instance().
{
  assert(x);
  if (cmd >> "#(") {
    if (cmd.match1('.')) {
      // by name
      while (cmd >> '.') {
        unsigned here = cmd.cursor();
        std::string name  = cmd.ctos("(", "", "");
        std::string value = cmd.ctos(",)", "(", ")");
        cmd >> ',';
        try{
          x->set_param_by_name(name, value);
        }catch (Exception_No_Match&) {untested();
          cmd.warn(bDANGER, here, x->long_label() + ": bad parameter " + name + " ignored");
        }
      }
    }else{
      // by order
      int index = 1;
      while (cmd.is_alnum()) {
        unsigned here = cmd.cursor();
        try{
          std::string value = cmd.ctos(",)", "", "");
          x->set_param_by_index(x->param_count() - index++, value, 0/*offset*/);
        }catch (Exception_Too_Many& e) {untested();
          cmd.warn(bDANGER, here, e.message());
        }
      }
    }
    cmd >> ')';
  }else{
    // no args
  }
}
static void anonymous_namespace{lang_verilog.cc}::parse_args_paramset (CS & cmd, MODEL_CARD * x) [static]
Definition at line 99 of file lang_verilog.cc.
References CS::cursor(), CARD::long_label(), CARD::set_param_by_name(), untested, and CS::warn().
Referenced by anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_paramset().
{
  assert(x);
  while (cmd >> '.') {
    unsigned here = cmd.cursor();
    std::string name, value;
    try{
      cmd >> name >> '=' >> value >> ';';
      x->set_param_by_name(name, value);
    }catch (Exception_No_Match&) {untested();
      cmd.warn(bDANGER, here, x->long_label() + ": bad parameter " + name + " ignored");
    }
  }
}
static void anonymous_namespace{lang_verilog.cc}::parse_label (CS & cmd, CARD * x) [static]
Definition at line 152 of file lang_verilog.cc.
References CKT_BASE::set_label().
{
  assert(x);
  std::string my_name;
  cmd >> my_name;
  x->set_label(my_name);
}
static void anonymous_namespace{lang_verilog.cc}::parse_ports (CS & cmd, COMPONENT * x) [static]
Definition at line 160 of file lang_verilog.cc.
References CS::cursor(), CS::is_alnum(), COMPONENT::set_port_by_index(), COMPONENT::set_port_by_name(), untested, and CS::warn().
{
  assert(x);
  if (cmd >> '(') {
    if (cmd.is_alnum()) {
      // by order
      int index = 0;
      while (cmd.is_alnum()) {
        unsigned here = cmd.cursor();
        try{
          std::string value;
          cmd >> value;
          x->set_port_by_index(index++, value);
        }catch (Exception_Too_Many& e) {untested();
          cmd.warn(bDANGER, here, e.message());
        }
      }
    }else{
      // by name
      while (cmd >> '.') {
        unsigned here = cmd.cursor();
        try{
          std::string name, value;
          cmd >> name >> '(' >> value >> ')' >> ',';
          x->set_port_by_name(name, value);
        }catch (Exception_No_Match&) {untested();
          cmd.warn(bDANGER, here, "mismatch, ignored");
        }
      }
    }
    cmd >> ')';
  }else{untested();
    cmd.warn(bDANGER, "'(' required");
  }
}
static void anonymous_namespace{lang_verilog.cc}::parse_type (CS & cmd, CARD * x) [static]
Definition at line 91 of file lang_verilog.cc.
References CARD::set_dev_type().
{
  assert(x);
  std::string new_type;
  cmd >> new_type;
  x->set_dev_type(new_type);
}
static void anonymous_namespace{lang_verilog.cc}::print_label (OMSTREAM & o, const COMPONENT * x) [static]
Definition at line 346 of file lang_verilog.cc.
References CKT_BASE::short_label().
{
  assert(x);
  o << x->short_label();
}
static void anonymous_namespace{lang_verilog.cc}::print_ports_long (OMSTREAM & o, const COMPONENT * x) [static]
Definition at line 352 of file lang_verilog.cc.
References COMPONENT::current_port_exists(), COMPONENT::current_port_name(), COMPONENT::current_port_value(), COMPONENT::port_exists(), COMPONENT::port_name(), and COMPONENT::port_value().
Referenced by anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_instance().
{
  // print in long form ...    .name(value)
  assert(x);
  o << " (";
  std::string sep = ".";
  for (int ii = 0;  x->port_exists(ii);  ++ii) {
    o << sep << x->port_name(ii) << '(' << x->port_value(ii) << ')';
    sep = ",.";
  }
  for (int ii = 0;  x->current_port_exists(ii);  ++ii) {
    o << sep << x->current_port_name(ii) << '(' << x->current_port_value(ii) << ')';
    sep = ",.";
  }
  o << ")";
}
static void anonymous_namespace{lang_verilog.cc}::print_ports_short (OMSTREAM & o, const COMPONENT * x) [static]
Definition at line 370 of file lang_verilog.cc.
References COMPONENT::current_port_exists(), COMPONENT::current_port_value(), COMPONENT::port_exists(), and COMPONENT::port_value().
Referenced by anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_module().
{
  // print in short form ...   value only
  assert(x);
  o << " (";
  std::string sep = "";
  for (int ii = 0;  x->port_exists(ii);  ++ii) {
    o << sep << x->port_value(ii);
    sep = ",";
  }
  for (int ii = 0;  x->current_port_exists(ii);  ++ii) {
    o << sep << x->current_port_value(ii);
    sep = ",";
  }
  o << ")";
}
static void anonymous_namespace{lang_verilog.cc}::print_type (OMSTREAM & o, const COMPONENT * x) [static]
Definition at line 340 of file lang_verilog.cc.
References CARD::dev_type().
{
  assert(x);
  o << x->dev_type();
}
Variable Documentation
DISPATCHER< CMD >::INSTALL d8 & anonymous_namespace{lang_verilog.cc}::command_dispatcher
Definition at line 474 of file lang_verilog.cc.
anonymous_namespace{lang_verilog.cc}::LANG_VERILOG anonymous_namespace{lang_verilog.cc}::lang_verilog
Referenced by anonymous_namespace{lang_verilog.cc}::CMD_PARAMSET::do_it(), and anonymous_namespace{lang_verilog.cc}::CMD_MODULE::do_it().
anonymous_namespace{lang_verilog.cc}::CMD_PARAMSET anonymous_namespace{lang_verilog.cc}::p1
anonymous_namespace{lang_verilog.cc}::CMD_MODULE anonymous_namespace{lang_verilog.cc}::p2
anonymous_namespace{lang_verilog.cc}::CMD_VERILOG anonymous_namespace{lang_verilog.cc}::p8