gnucap: anonymous_namespace{s_dc.cc}::DC Class Reference
anonymous_namespace{s_dc.cc}::DC Class Reference
Public Member Functions
DC ()
~DC ()
void do_it (CS &, CARD_LIST *)
Private Member Functions
void setup (CS &)
DC (const DC &)
Detailed Description
Definition at line 71 of file s_dc.cc.
Constructor & Destructor Documentation
anonymous_namespace{s_dc.cc}::DC::DC () [inline, explicit]
Definition at line 73 of file s_dc.cc.
: DCOP() {}
anonymous_namespace{s_dc.cc}::DC::~DC () [inline]
Definition at line 74 of file s_dc.cc.
{}
anonymous_namespace{s_dc.cc}::DC::DC (const DC &) [inline, explicit, private]
Definition at line 78 of file s_dc.cc.
References incomplete, and unreachable.
: DCOP() {unreachable(); incomplete();}
Member Function Documentation
void anonymous_namespace{s_dc.cc}::DC::do_it (CS & Cmd, CARD_LIST * Scope) [virtual]
Implements CMD.
Definition at line 92 of file s_dc.cc.
References STATUS::dc, p_INIT_DC, TIMER::reset(), TIMER::start(), status, and TIMER::stop().
{
  _scope = Scope;
  _sim->_time0 = 0.;
  _sim->set_command_dc();
  _sim->_phase = p_INIT_DC;
  ::status.dc.reset().start();
  _sim->_temp_c = temp_c_in;
  command_base(Cmd);
  ::status.dc.stop();
}
void anonymous_namespace{s_dc.cc}::DC::setup (CS & Cmd) [private, virtual]
Implements SIM.
Definition at line 192 of file s_dc.cc.
References anonymous_namespace{s_dc.cc}::DCOP::_cont, SIM_DATA::_freq, SIM_DATA::_genout, anonymous_namespace{s_dc.cc}::DCOP::_n_sweeps, SIM::_out, SIM::_scope, CKT_BASE::_sim, anonymous_namespace{s_dc.cc}::DCOP::_start, anonymous_namespace{s_dc.cc}::DCOP::_stash, anonymous_namespace{s_dc.cc}::DCOP::_step, anonymous_namespace{s_dc.cc}::DCOP::_stop, anonymous_namespace{s_dc.cc}::DCOP::_sweepval, SIM_DATA::_temp_c, anonymous_namespace{s_dc.cc}::DCOP::_trace, anonymous_namespace{s_dc.cc}::DCOP::_zap, CARD_LIST::card_list, CS::check(), anonymous_namespace{s_dc.cc}::DCOP::DCNEST, PARAMETER< T >::e_val(), exists(), findbranch(), anonymous_namespace{s_dc.cc}::DCOP::fix_args(), CKT_BASE::inc_probes(), initio(), CARD_LIST::fat_iterator::is_end(), CS::is_float(), CS::match1(), CS::more(), IO::mstdout, anonymous_namespace{s_dc.cc}::DCOP::options(), SIM::plotlist(), IO::plotout, IO::plotset, OMSTREAM::reset(), ELEMENT::set__value(), CARD::set_constant(), COMPONENT::set_value(), PROBELIST::size(), OPT::temp_c, anonymous_namespace{s_dc.cc}::DCOP::temp_c_in, SIM::tNONE, and untested.
{
  _cont = false;
  _trace = tNONE;
  _out = IO::mstdout;
  _out.reset(); //BUG// don't know why this is needed */
  bool ploton = IO::plotset  &&  plotlist().size() > 0;
  if (Cmd.more()) {
    for (_n_sweeps = 0; Cmd.more() && _n_sweeps < DCNEST; ++_n_sweeps) {
      CARD_LIST::fat_iterator ci = findbranch(Cmd, &CARD_LIST::card_list);
      if (!ci.is_end()) {                       // sweep a component
        if (ELEMENT* c = dynamic_cast<ELEMENT*>(*ci)) {
          _zap[_n_sweeps] = c;
        }else{untested();
          throw Exception("dc/op: can't sweep " + (**ci).long_label() + '\n');
        }
      }else if (Cmd.is_float()) {               // sweep the generator
        _zap[_n_sweeps] = NULL;
      }else{
        // leave as it was .. repeat Cmd with no args
      }
      if (Cmd.match1("'\"({") || Cmd.is_float()) {      // set up parameters
        _start[_n_sweeps] = "NA";
        _stop[_n_sweeps] = "NA";
        Cmd >> _start[_n_sweeps] >> _stop[_n_sweeps];
        _step[_n_sweeps] = 0.;
      }else{
        // leave it as it was .. repeat Cmd with no args
      }
      _sim->_genout = 0.;
      temp_c_in = OPT::temp_c;
      _sim->_temp_c = temp_c_in;
      options(Cmd,_n_sweeps);
    }
  }else{
  }
  Cmd.check(bWARNING, "what's this?");
  IO::plotout = (ploton) ? IO::mstdout : OMSTREAM();
  initio(_out);
  assert(_n_sweeps > 0);
  for (int ii = 0;  ii < _n_sweeps;  ++ii) {
    _start[ii].e_val(0., _scope);
    fix_args(ii);
    if (exists(_zap[ii])) { // component
      _stash[ii] = _zap[ii];                    // stash the std value
      _zap[ii]->inc_probes();                   // we need to keep track of it
      _zap[ii]->set_value(_zap[ii]->value(),0); // zap out extensions
      _zap[ii]->set_constant(false);            // so it will be updated
      _sweepval[ii] = _zap[ii]->set__value();   // point to value to patch
    }else{ // generator
      _sweepval[ii] = &_sim->_genout;                   // point to value to patch
    }
  }
  _sim->_freq = 0;
}
The documentation for this class was generated from the following file:
savant/gnucap/src/s_dc.cc