gnucap: CARD Class Reference
CARD Class Reference
#include <e_card.h>
Public Member Functions
CARD * find_in_my_scope (const std::string &name)
const CARD * find_in_my_scope (const std::string &name) const
const CARD * find_in_parent_scope (const std::string &name) const
const CARD * find_looking_out (const std::string &name) const
virtual ~CARD ()
virtual CARD * clone () const
virtual CARD * clone_instance () const
virtual void precalc_first ()
virtual void expand_first ()
virtual void expand ()
virtual void expand_last ()
virtual void precalc_last ()
virtual void map_nodes ()
virtual void tr_iwant_matrix ()
virtual void tr_begin ()
virtual void tr_restore ()
virtual void dc_advance ()
virtual void tr_advance ()
virtual void tr_regress ()
virtual bool tr_needs_eval () const
virtual void tr_queue_eval ()
virtual bool do_tr ()
virtual bool do_tr_last ()
virtual void tr_load ()
virtual TIME_PAIR tr_review ()
virtual void tr_accept ()
virtual void tr_unload ()
virtual void ac_iwant_matrix ()
virtual void ac_begin ()
virtual void do_ac ()
virtual void ac_load ()
virtual char id_letter () const
virtual int net_nodes () const
virtual bool is_device () const
virtual void set_slave ()
bool evaluated () const
void set_constant (bool c)
bool is_constant () const
virtual CARD_LIST * scope ()
virtual const CARD_LIST * scope () const
virtual bool makes_own_scope () const
CARD * owner ()
const CARD * owner () const
void set_owner (CARD *o)
CARD_LIST * subckt ()
const CARD_LIST * subckt () const
void new_subckt ()
void new_subckt (const CARD *model, CARD *owner, const CARD_LIST *scope, PARAM_LIST *p)
void renew_subckt (const CARD *model, CARD *owner, const CARD_LIST *scope, PARAM_LIST *p)
virtual std::string dev_type () const
virtual void set_dev_type (const std::string &)
const std::string long_label () const
node_t & n_ (int i) const
int connects_to (const node_t &node) const
virtual void set_param_by_name (std::string, std::string)
virtual void set_param_by_index (int i, std::string &, int offset)
virtual int param_count_dont_print () const
virtual int param_count () const
virtual bool param_is_printable (int) const
virtual std::string param_name (int) const
virtual std::string param_name (int i, int j) const
virtual std::string param_value (int) const
virtual std::string value_name () const =0
virtual bool use_obsolete_callback_parse () const
virtual bool use_obsolete_callback_print () const
virtual void print_args_obsolete_callback (OMSTREAM &, LANGUAGE *) const
Public Attributes
int _net_nodes
Protected Member Functions
CARD ()
CARD (const CARD &)
Protected Attributes
node_t * _n
Private Attributes
int _evaliter
CARD_LIST * _subckt
CARD * _owner
bool _constant
Detailed Description
Definition at line 39 of file e_card.h.
Constructor & Destructor Documentation
CARD::CARD () [explicit, protected]
Definition at line 32 of file e_card.cc.
  :CKT_BASE(),
   _evaliter(-100),
   _subckt(0),
   _owner(0),
   _constant(false),
   _n(0),
   _net_nodes(0)
{
}
CARD::CARD (const CARD & p) [explicit, protected]
Definition at line 43 of file e_card.cc.
  :CKT_BASE(p),
   _evaliter(-100),
   _subckt(0), //BUG// isn't this supposed to copy????
   _owner(0),
   _constant(p._constant),
   _n(0),
   _net_nodes(p._net_nodes)
{
}
CARD::~CARD () [virtual]
Definition at line 54 of file e_card.cc.
References _subckt.
{
  delete _subckt;
}
Member Function Documentation
virtual void CARD::ac_begin () [inline, virtual]
Reimplemented in DEV_SPICE, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, BASE_SUBCKT, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_cccs.cc}::DEV_CCCS, and anonymous_namespace{d_ccvs.cc}::DEV_CCVS.
Definition at line 90 of file e_card.h.
{}
virtual void CARD::ac_iwant_matrix () [inline, virtual]
Reimplemented in DEV_SPICE, COMPONENT, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_cap.cc}::DEV_VCCAP, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, ELEMENT, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_cccs.cc}::DEV_CCCS, and anonymous_namespace{d_ccvs.cc}::DEV_CCVS.
Definition at line 89 of file e_card.h.
{}
virtual void CARD::ac_load () [inline, virtual]
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, BASE_SUBCKT, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_cccs.cc}::DEV_CCCS, and anonymous_namespace{d_ccvs.cc}::DEV_CCVS.
Definition at line 92 of file e_card.h.
{}
virtual CARD* CARD::clone () const [inline, virtual]
Reimplemented in DEV_SPICE, anonymous_namespace{d_switch.cc}::MODEL_SWITCH, MODEL_SPICE, MODEL_SEMI_RESISTOR, anonymous_namespace{d_switch.cc}::DEV_CSWITCH, MODEL_SEMI_CAPACITOR, anonymous_namespace{d_cap.cc}::DEV_VCCAP, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, MODEL_LOGIC, anonymous_namespace{d_switch.cc}::DEV_VSWITCH, anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, DEV_SUBCKT, anonymous_namespace{d_switch.cc}::SWITCH_BASE, MODEL_TABLE, DEV_LOGIC, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_net.cc}::DEV_NET, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, MODEL_SUBCKT, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_cccs.cc}::DEV_CCCS, anonymous_namespace{d_ccvs.cc}::DEV_CCVS, DEV_COMMENT, and DEV_DOT.
Definition at line 61 of file e_card.h.
References unreachable.
Referenced by anonymous_namespace{lang_spectre.cc}::CMD_MODEL::do_it(), anonymous_namespace{lang_verilog.cc}::CMD_PARAMSET::do_it(), anonymous_namespace{lang_spice.cc}::CMD_MODEL::do_it(), and CARD_LIST::shallow_copy().
{unreachable(); return NULL;}
virtual CARD* CARD::clone_instance () const [inline, virtual]
Reimplemented in MODEL_CARD, and MODEL_SUBCKT.
Definition at line 62 of file e_card.h.
Referenced by LANGUAGE::new__instance().
{return clone();}
int CARD::connects_to (const node_t & node) const
Definition at line 73 of file e_card.cc.
References _n, is_device(), node_t::n_(), net_nodes(), and untested.
{
  untested();
  int count = 0;
  if (is_device()) {
    for (int ii = 0;  ii < net_nodes();  ++ii) {
      untested();
      if (node.n_() == _n[ii].n_()) {
        ++count;
      }else{untested();
      }
    }
  }else{untested();
  }
  return count;
}
virtual void CARD::dc_advance () [inline, virtual]
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, BASE_SUBCKT, ELEMENT, and STORAGE.
Definition at line 76 of file e_card.h.
{}
virtual std::string CARD::dev_type () const [inline, virtual]
Reimplemented in DEV_SPICE, anonymous_namespace{d_switch.cc}::MODEL_SWITCH, MODEL_SPICE, MODEL_SEMI_RESISTOR, MODEL_SEMI_CAPACITOR, anonymous_namespace{d_cap.cc}::DEV_VCCAP, MODEL_LOGIC, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, MODEL_TABLE, anonymous_namespace{d_switch.cc}::SWITCH_BASE, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, DEV_LOGIC, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_net.cc}::DEV_NET, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, MODEL_SUBCKT, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_cccs.cc}::DEV_CCCS, anonymous_namespace{d_ccvs.cc}::DEV_CCVS, DEV_COMMENT, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_vs.cc}::DEV_VS, BASE_SUBCKT, and DEV_DOT.
Definition at line 121 of file e_card.h.
References unreachable.
Referenced by anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_instance(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_paramset(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_paramset(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_paramset(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_type(), anonymous_namespace{lang_spectre.cc}::print_type(), anonymous_namespace{lang_verilog.cc}::print_type(), set_dev_type(), COMPONENT::set_dev_type(), and ELEMENT::skip_dev_type().
{unreachable(); return "";}
virtual void CARD::do_ac () [inline, virtual]
Reimplemented in DEV_SPICE, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, BASE_SUBCKT, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_cccs.cc}::DEV_CCCS, and anonymous_namespace{d_ccvs.cc}::DEV_CCVS.
Definition at line 91 of file e_card.h.
Referenced by anonymous_namespace{d_cccs.cc}::DEV_CCCS::do_ac(), and anonymous_namespace{d_ccvs.cc}::DEV_CCVS::do_ac().
{}
virtual bool CARD::do_tr () [inline, virtual]
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_cap.cc}::DEV_VCCAP, anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, BASE_SUBCKT, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_cccs.cc}::DEV_CCCS, and anonymous_namespace{d_ccvs.cc}::DEV_CCVS.
Definition at line 81 of file e_card.h.
{return true;}
virtual bool CARD::do_tr_last () [inline, virtual]
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_cccs.cc}::DEV_CCCS, and anonymous_namespace{d_ccvs.cc}::DEV_CCVS.
Definition at line 82 of file e_card.h.
{return true;}
bool CARD::evaluated () const
Definition at line 253 of file e_card.cc.
References _evaliter, CKT_BASE::_sim, and SIM_DATA::iteration_tag().
{
  if (_evaliter == _sim->iteration_tag()) {
    return true;
  }else{
    _evaliter = _sim->iteration_tag();
    return false;
  }
}
virtual void CARD::expand () [inline, virtual]
Reimplemented in DEV_SPICE, COMPONENT, anonymous_namespace{d_switch.cc}::DEV_CSWITCH, DEV_SUBCKT, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, and MODEL_SUBCKT.
Definition at line 67 of file e_card.h.
{}
virtual void CARD::expand_first () [inline, virtual]
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 66 of file e_card.h.
{}
virtual void CARD::expand_last () [inline, virtual]
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, and CCSRC_BASE.
Definition at line 68 of file e_card.h.
{}
CARD * CARD::find_in_my_scope (const std::string & name)
Definition at line 113 of file e_card.cc.
References CARD_LIST::find_(), long_label(), owner(), and scope().
Referenced by anonymous_namespace{d_switch.cc}::DEV_CSWITCH::expand(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::expand_first(), CCSRC_BASE::expand_last(), and COMPONENT::find_model().
{
  assert(name != "");
  assert(scope());
  CARD_LIST::iterator i = scope()->find_(name);
  if (i == scope()->end()) {
    throw Exception_Cant_Find(long_label(), name,
                              ((owner()) ? owner()->long_label() : "(root)"));
  }else{
  }
  return *i;
}
const CARD * CARD::find_in_my_scope (const std::string & name) const
Definition at line 132 of file e_card.cc.
References CARD_LIST::find_(), long_label(), owner(), and scope().
{
  assert(name != "");
  assert(scope());
  CARD_LIST::const_iterator i = scope()->find_(name);
  if (i == scope()->end()) {
    throw Exception_Cant_Find(long_label(), name,
                              ((owner()) ? owner()->long_label() : "(root)"));
  }else{
  }
  return *i;
}
const CARD * CARD::find_in_parent_scope (const std::string & name) const
Definition at line 152 of file e_card.cc.
References CARD_LIST::end(), CARD_LIST::find_(), long_label(), CARD_LIST::parent(), and scope().
Referenced by find_looking_out().
{
  assert(name != "");
  const CARD_LIST* p_scope = (scope()->parent()) ? scope()->parent() : scope();
  CARD_LIST::const_iterator i = p_scope->find_(name);
  if (i == p_scope->end()) {
    throw Exception_Cant_Find(long_label(), name);
  }else{
  }
  return *i;
}
const CARD * CARD::find_looking_out (const std::string & name) const
Definition at line 169 of file e_card.cc.
References CARD_LIST::card_list, CARD_LIST::find_(), find_in_parent_scope(), find_looking_out(), itested, makes_own_scope(), and owner().
Referenced by DEV_LOGIC::expand(), DEV_SUBCKT::expand(), find_looking_out(), and LANGUAGE::find_proto().
{
  try {
    return find_in_parent_scope(name);
  }catch (Exception_Cant_Find&) {
    if (owner()) {
      return owner()->find_looking_out(name);
    }else if (makes_own_scope()) {
      // probably a subckt or "module"
      CARD_LIST::const_iterator i = CARD_LIST::card_list.find_(name);
      if (i != CARD_LIST::card_list.end()) {itested();
        return *i;
      }else{
        throw;
      }
    }else{
      throw;
    }
  }
}
virtual char CARD::id_letter () const [inline, virtual]
Reimplemented in DEV_SPICE, anonymous_namespace{d_switch.cc}::DEV_CSWITCH, anonymous_namespace{d_cap.cc}::DEV_VCCAP, anonymous_namespace{d_switch.cc}::DEV_VSWITCH, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, DEV_SUBCKT, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, MODEL_CARD, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, DEV_LOGIC, anonymous_namespace{d_net.cc}::DEV_NET, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, MODEL_SUBCKT, DEV_COMMENT, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_cccs.cc}::DEV_CCCS, anonymous_namespace{d_ccvs.cc}::DEV_CCVS, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_vs.cc}::DEV_VS, and DEV_DOT.
Definition at line 95 of file e_card.h.
References unreachable.
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_type().
{unreachable(); return '\0';}
bool CARD::is_constant () const [inline]
Definition at line 102 of file e_card.h.
Referenced by DEV_LOGIC::expand(), DEV_SPICE::internal_precalc(), DEV_SUBCKT::precalc_first(), STORAGE::precalc_last(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::precalc_last(), DEV_SUBCKT::precalc_last(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::precalc_last(), DEV_SPICE::precalc_last(), CARD_LIST::tr_load(), and ELEMENT::tr_needs_eval().
{return _constant;}
virtual bool CARD::is_device () const [inline, virtual]
Reimplemented in COMPONENT, and MODEL_SUBCKT.
Definition at line 97 of file e_card.h.
Referenced by PROBELIST::add_branches(), connects_to(), and anonymous_namespace{c_modify.cc}::faultbranch().
{return false;}
const std::string CARD::long_label () const [virtual]
Reimplemented from CKT_BASE.
Reimplemented in SIM.
Definition at line 59 of file e_card.cc.
References exists(), owner(), and CKT_BASE::short_label().
Referenced by DEV_LOGIC::ac_begin(), ELEMENT::ac_iwant_matrix_passive(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::do_ac(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_tr(), ELEMENT::ELEMENT(), anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::expand(), EVAL_BM_TABLE::expand(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::expand(), DEV_LOGIC::expand(), EVAL_BM_SEMI_CAPACITOR::expand(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::expand(), EVAL_BM_SEMI_RESISTOR::expand(), DEV_SUBCKT::expand(), anonymous_namespace{d_switch.cc}::DEV_CSWITCH::expand(), DEV_SPICE::expand(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::expand_first(), CCSRC_BASE::expand_last(), anonymous_namespace{c_modify.cc}::faultbranch(), find_in_my_scope(), find_in_parent_scope(), COMPONENT::find_model(), node_t::map_subckt_node(), CARD_LIST::map_subckt_nodes(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_args(), anonymous_namespace{lang_spectre.cc}::parse_args(), anonymous_namespace{lang_verilog.cc}::parse_args_instance(), anonymous_namespace{lang_verilog.cc}::parse_args_paramset(), anonymous_namespace{lang_gschem.cc}::parse_net(), MODEL_TABLE::precalc_first(), COMPONENT::precalc_first(), DEV_SPICE::precalc_first(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::precalc_last(), COMPONENT::precalc_last(), anonymous_namespace{c_modify.cc}::sweep_fix(), LOGIC_NODE::to_analog(), LOGIC_NODE::to_logic(), DEV_LOGIC::tr_accept(), ELEMENT::tr_iwant_matrix_passive(), DEV_SPICE::tr_load(), ELEMENT::tr_review_check_and_convert(), and ELEMENT::tr_review_trunc_error().
{
  std::string buffer(short_label());
  for (const CARD* brh = owner(); exists(brh); brh = brh->owner()) {
    buffer = brh->short_label() + '.' + buffer;
  }
  return buffer;
}
virtual bool CARD::makes_own_scope () const [inline, virtual]
Reimplemented in MODEL_SUBCKT.
Definition at line 107 of file e_card.h.
Referenced by find_looking_out().
{return false;}
virtual void CARD::map_nodes () [inline, virtual]
Reimplemented in COMPONENT, and MODEL_SUBCKT.
Definition at line 70 of file e_card.h.
{}
node_t & CARD::n_ (int i) const
Definition at line 219 of file e_card.cc.
References _n.
Referenced by DEV_SPICE::DEV_SPICE(), DEV_SPICE::expand(), CCSRC_BASE::expand_last(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::expand_last(), and CARD_LIST::map_subckt_nodes().
{
  return _n[i];
}
virtual int CARD::net_nodes () const [inline, virtual]
Reimplemented in COMPONENT, DEV_SPICE, anonymous_namespace{d_switch.cc}::DEV_CSWITCH, anonymous_namespace{d_cap.cc}::DEV_VCCAP, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_switch.cc}::DEV_VSWITCH, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, DEV_SUBCKT, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_net.cc}::DEV_NET, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, MODEL_SUBCKT, anonymous_namespace{d_vcr.cc}::DEV_VCR, BASE_SUBCKT, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_vs.cc}::DEV_VS, and CCSRC_BASE.
Definition at line 96 of file e_card.h.
References untested.
Referenced by connects_to(), CARD_LIST::map_subckt_nodes(), and COMPONENT::port_exists().
{untested();return 0;}
void CARD::new_subckt ()
Definition at line 195 of file e_card.cc.
References _subckt.
Referenced by MODEL_SUBCKT::MODEL_SUBCKT(), and renew_subckt().
{
  delete _subckt;
  _subckt = new CARD_LIST;
}
void CARD::new_subckt (const CARD * model, CARD * owner, const CARD_LIST * scope, PARAM_LIST * p)
Definition at line 201 of file e_card.cc.
References _subckt.
{
  delete _subckt;
  _subckt = new CARD_LIST(Model, Owner, Scope, Params);
}
CARD* CARD::owner () [inline]
Definition at line 109 of file e_card.h.
Referenced by anonymous_namespace{lang_gschem.cc}::CMD_C::do_it(), anonymous_namespace{lang_spectre.cc}::CMD_MODEL::do_it(), anonymous_namespace{lang_spectre.cc}::CMD_SUBCKT::do_it(), anonymous_namespace{lang_verilog.cc}::CMD_PARAMSET::do_it(), anonymous_namespace{lang_verilog.cc}::CMD_MODULE::do_it(), anonymous_namespace{lang_spice.cc}::CMD_MODEL::do_it(), anonymous_namespace{lang_spice.cc}::CMD_SUBCKT::do_it(), find_in_my_scope(), find_looking_out(), COMPONENT::find_model(), long_label(), COMPONENT::mfactor(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_command(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_command(), anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_command(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_command(), COMPONENT::precalc_first(), and scope().
{return _owner;}
const CARD* CARD::owner () const [inline]
Definition at line 110 of file e_card.h.
{return _owner;}
virtual int CARD::param_count () const [inline, virtual]
Reimplemented in COMPONENT, anonymous_namespace{d_switch.cc}::MODEL_SWITCH, MODEL_SPICE, MODEL_SEMI_RESISTOR, ELEMENT, MODEL_SEMI_CAPACITOR, MODEL_LOGIC, MODEL_SEMI_BASE, MODEL_CARD, and anonymous_namespace{d_net.cc}::DEV_NET.
Definition at line 138 of file e_card.h.
Referenced by MODEL_CARD::param_count(), COMPONENT::param_count(), MODEL_CARD::param_name(), COMPONENT::param_name(), anonymous_namespace{lang_verilog.cc}::parse_args_instance(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_args(), and set_param_by_name().
{return 0;}
virtual int CARD::param_count_dont_print () const [inline, virtual]
Reimplemented in DEV_SPICE, MODEL_SPICE, and DEV_SUBCKT.
Definition at line 137 of file e_card.h.
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_args().
{return 0;}
virtual bool CARD::param_is_printable (int) const [inline, virtual]
Reimplemented in COMPONENT, anonymous_namespace{d_switch.cc}::MODEL_SWITCH, MODEL_SPICE, MODEL_SEMI_RESISTOR, MODEL_SEMI_CAPACITOR, MODEL_LOGIC, MODEL_SEMI_BASE, MODEL_CARD, and anonymous_namespace{d_net.cc}::DEV_NET.
Definition at line 139 of file e_card.h.
References untested.
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_args().
{untested(); return false;}
virtual std::string CARD::param_name (int) const [inline, virtual]
Reimplemented in COMPONENT, anonymous_namespace{d_switch.cc}::MODEL_SWITCH, MODEL_SPICE, MODEL_SEMI_RESISTOR, MODEL_SEMI_CAPACITOR, MODEL_LOGIC, MODEL_SEMI_BASE, MODEL_CARD, and anonymous_namespace{d_net.cc}::DEV_NET.
Definition at line 140 of file e_card.h.
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_args(), and set_param_by_name().
{return "";}
virtual std::string CARD::param_name (int i, int j) const [inline, virtual]
Reimplemented in COMPONENT, anonymous_namespace{d_switch.cc}::MODEL_SWITCH, MODEL_SPICE, MODEL_SEMI_RESISTOR, MODEL_SEMI_CAPACITOR, MODEL_LOGIC, MODEL_SEMI_BASE, MODEL_CARD, and anonymous_namespace{d_net.cc}::DEV_NET.
Definition at line 141 of file e_card.h.
References param_name().
Referenced by param_name().
{return (j==0) ? param_name(i) : "";}
virtual std::string CARD::param_value (int) const [inline, virtual]
Reimplemented in COMPONENT, anonymous_namespace{d_switch.cc}::MODEL_SWITCH, MODEL_SPICE, MODEL_SEMI_RESISTOR, MODEL_SEMI_CAPACITOR, MODEL_LOGIC, MODEL_SEMI_BASE, MODEL_CARD, and anonymous_namespace{d_net.cc}::DEV_NET.
Definition at line 142 of file e_card.h.
References untested.
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_args().
{untested(); return "";}
virtual void CARD::precalc_first () [inline, virtual]
Reimplemented in DEV_SPICE, COMPONENT, anonymous_namespace{d_switch.cc}::MODEL_SWITCH, MODEL_SEMI_RESISTOR, MODEL_SEMI_CAPACITOR, MODEL_LOGIC, MODEL_SEMI_BASE, DEV_SUBCKT, MODEL_TABLE, DEV_LOGIC, MODEL_CARD, and MODEL_SUBCKT.
Definition at line 65 of file e_card.h.
{}
virtual void CARD::precalc_last () [inline, virtual]
Reimplemented in DEV_SPICE, COMPONENT, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, DEV_SUBCKT, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, MODEL_SUBCKT, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_vcr.cc}::DEV_VCR, ELEMENT, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, STORAGE, anonymous_namespace{d_cccs.cc}::DEV_CCCS, and anonymous_namespace{d_ccvs.cc}::DEV_CCVS.
Definition at line 69 of file e_card.h.
{}
virtual void CARD::print_args_obsolete_callback (OMSTREAM & , LANGUAGE *) const [inline, virtual]
Reimplemented in COMPONENT, and MODEL_TABLE.
Definition at line 148 of file e_card.h.
References unreachable.
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_args(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_args(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_args().
{unreachable();}
void CARD::renew_subckt (const CARD * model, CARD * owner, const CARD_LIST * scope, PARAM_LIST * p)
Definition at line 208 of file e_card.cc.
References CKT_BASE::_sim, CARD_LIST::attach_params(), SIM_DATA::is_first_expand(), new_subckt(), scope(), subckt(), and untested.
Referenced by DEV_LOGIC::expand(), and DEV_SUBCKT::expand().
{
  if (_sim->is_first_expand()) {
    new_subckt(Model, Owner, Scope, Params);
  }else{untested();
    assert(subckt());
    subckt()->attach_params(Params, scope());
  }
}
CARD_LIST * CARD::scope () [virtual]
Reimplemented in MODEL_SUBCKT.
Definition at line 90 of file e_card.cc.
References CARD_LIST::card_list, owner(), and subckt().
Referenced by DEV_LOGIC::expand(), DEV_SUBCKT::expand(), find_in_my_scope(), find_in_parent_scope(), node_t::new_node(), MODEL_CARD::precalc_first(), MODEL_TABLE::precalc_first(), DEV_SUBCKT::precalc_first(), MODEL_SEMI_BASE::precalc_first(), MODEL_LOGIC::precalc_first(), MODEL_SEMI_CAPACITOR::precalc_first(), MODEL_SEMI_RESISTOR::precalc_first(), anonymous_namespace{d_switch.cc}::MODEL_SWITCH::precalc_first(), COMPONENT::precalc_first(), DEV_SPICE::precalc_first(), DEV_SUBCKT::precalc_last(), COMPONENT::precalc_last(), renew_subckt(), MODEL_SPICE::set_param_by_name(), DEV_SPICE::set_param_by_name(), and node_t::set_to_ground().
{
  if (owner()) {
    return owner()->subckt();   // normal element, owner determines scope
  }else{
    return &(CARD_LIST::card_list);     // root circuit
  }
}
const CARD_LIST * CARD::scope () const [virtual]
Reimplemented in MODEL_SUBCKT.
Definition at line 99 of file e_card.cc.
References CARD_LIST::card_list, owner(), and subckt().
{
  if (owner()) {
    return owner()->subckt();   // normal element, owner determines scope
  }else{
    return &(CARD_LIST::card_list);     // root circuit
  }
}
void CARD::set_constant (bool c) [inline]
Definition at line 101 of file e_card.h.
Referenced by DEV_COMMENT::DEV_COMMENT(), DEV_DOT::DEV_DOT(), and anonymous_namespace{s_dc.cc}::DC::setup().
{_constant = c;}
void CARD::set_dev_type (const std::string & New_Type) [virtual]
Reimplemented in DEV_SPICE, COMPONENT, anonymous_namespace{d_switch.cc}::MODEL_SWITCH, and MODEL_SPICE.
Definition at line 244 of file e_card.cc.
References dev_type(), itested, and Umatch().
Referenced by anonymous_namespace{lang_gschem.cc}::parse_component(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_type(), anonymous_namespace{lang_spectre.cc}::parse_type(), anonymous_namespace{lang_gschem.cc}::parse_type(), and anonymous_namespace{lang_verilog.cc}::parse_type().
{
  if (!Umatch(New_Type, dev_type() + ' ')) {itested();
    //throw Exception_Cant_Set_Type(dev_type(), New_Type);
  }else{
    // it matches -- ok.
  }
}
void CARD::set_owner (CARD * o) [inline]
Definition at line 111 of file e_card.h.
Referenced by LANGUAGE::new__instance(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::set_parameters(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::set_parameters(), and COMPONENT::set_parameters().
{assert(!_owner||_owner==o); _owner=o;}
virtual void CARD::set_param_by_index (int i, std::string & , int offset) [inline, virtual]
Reimplemented in COMPONENT, MODEL_SPICE, anonymous_namespace{d_switch.cc}::MODEL_SWITCH, MODEL_SEMI_RESISTOR, MODEL_SEMI_CAPACITOR, MODEL_LOGIC, MODEL_SEMI_BASE, and MODEL_CARD.
Definition at line 135 of file e_card.h.
References untested.
Referenced by anonymous_namespace{lang_verilog.cc}::parse_args_instance(), and set_param_by_name().
                                {untested(); throw Exception_Too_Many(i, 0, offset);}
void CARD::set_param_by_name (std::string Name, std::string Value) [virtual]
Reimplemented in DEV_SPICE, COMPONENT, MODEL_SPICE, and anonymous_namespace{d_net.cc}::DEV_NET.
Definition at line 224 of file e_card.cc.
References param_count(), param_name(), set_param_by_index(), and Umatch().
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_args(), anonymous_namespace{lang_spectre.cc}::parse_args(), anonymous_namespace{lang_verilog.cc}::parse_args_instance(), anonymous_namespace{lang_verilog.cc}::parse_args_paramset(), anonymous_namespace{lang_gschem.cc}::parse_component(), and anonymous_namespace{lang_gschem.cc}::parse_net().
{
  //BUG// ugly linear search
  for (int i = param_count() - 1;  i >= 0;  --i) {
    for (int j = 0;  param_name(i,j) != "";  ++j) { // multiple names
      if (Umatch(Name, param_name(i,j) + ' ')) {
        set_param_by_index(i, Value, 0/*offset*/);
        return; //success
      }else{
        //keep looking
      }
    }
  }
  throw Exception_No_Match(Name);
}
virtual void CARD::set_slave () [inline, virtual]
Reimplemented in COMPONENT.
Definition at line 98 of file e_card.h.
References untested.
{untested(); assert(!subckt());}
CARD_LIST* CARD::subckt () [inline]
Definition at line 114 of file e_card.h.
Referenced by BASE_SUBCKT::ac_begin(), DEV_LOGIC::ac_begin(), DEV_LOGIC::ac_iwant_matrix(), COMPONENT::ac_iwant_matrix(), ELEMENT::ac_iwant_matrix_extended(), BASE_SUBCKT::ac_load(), DEV_LOGIC::ac_load(), PROBELIST::add_branches(), CARD_LIST::CARD_LIST(), BASE_SUBCKT::dc_advance(), DEV_LOGIC::dc_advance(), BASE_SUBCKT::do_ac(), DEV_LOGIC::do_ac(), anonymous_namespace{lang_gschem.cc}::CMD_C::do_it(), anonymous_namespace{lang_spectre.cc}::CMD_SUBCKT::do_it(), anonymous_namespace{lang_verilog.cc}::CMD_MODULE::do_it(), anonymous_namespace{lang_spice.cc}::CMD_SUBCKT::do_it(), BASE_SUBCKT::do_tr(), DEV_LOGIC::do_tr(), DEV_LOGIC::expand(), DEV_SUBCKT::expand(), CCSRC_BASE::expand_last(), anonymous_namespace{c_modify.cc}::faultbranch(), COMPONENT::map_nodes(), CARD_LIST::map_subckt_nodes(), MODEL_SUBCKT::MODEL_SUBCKT(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_command(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_command(), anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_command(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_command(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_module(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_module(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_module(), DEV_LOGIC::precalc_first(), DEV_SUBCKT::precalc_first(), DEV_LOGIC::precalc_last(), DEV_SUBCKT::precalc_last(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_module(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_module(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_module(), renew_subckt(), MODEL_SUBCKT::scope(), scope(), COMPONENT::set_slave(), BASE_SUBCKT::tr_accept(), BASE_SUBCKT::tr_advance(), DEV_LOGIC::tr_advance(), BASE_SUBCKT::tr_begin(), DEV_LOGIC::tr_begin(), DEV_LOGIC::tr_iwant_matrix(), COMPONENT::tr_iwant_matrix(), ELEMENT::tr_iwant_matrix_active(), ELEMENT::tr_iwant_matrix_extended(), BASE_SUBCKT::tr_load(), DEV_LOGIC::tr_load(), BASE_SUBCKT::tr_needs_eval(), DEV_LOGIC::tr_needs_eval(), DEV_SUBCKT::tr_probe_num(), BASE_SUBCKT::tr_queue_eval(), DEV_LOGIC::tr_queue_eval(), BASE_SUBCKT::tr_regress(), DEV_LOGIC::tr_regress(), BASE_SUBCKT::tr_restore(), DEV_LOGIC::tr_restore(), BASE_SUBCKT::tr_review(), DEV_LOGIC::tr_review(), BASE_SUBCKT::tr_unload(), DEV_LOGIC::tr_unload(), DEV_LOGIC::want_analog(), and DEV_LOGIC::want_digital().
{return _subckt;}
const CARD_LIST* CARD::subckt () const [inline]
Definition at line 115 of file e_card.h.
{return _subckt;}
virtual void CARD::tr_accept () [inline, virtual]
Reimplemented in DEV_SPICE, COMPONENT, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, DEV_LOGIC, and BASE_SUBCKT.
Definition at line 85 of file e_card.h.
{}
virtual void CARD::tr_advance () [inline, virtual]
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, BASE_SUBCKT, ELEMENT, and STORAGE.
Definition at line 77 of file e_card.h.
{}
virtual void CARD::tr_begin () [inline, virtual]
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vs.cc}::DEV_VS, BASE_SUBCKT, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, ELEMENT, STORAGE, anonymous_namespace{d_cccs.cc}::DEV_CCCS, and anonymous_namespace{d_ccvs.cc}::DEV_CCVS.
Definition at line 74 of file e_card.h.
{}
virtual void CARD::tr_iwant_matrix () [inline, virtual]
Reimplemented in DEV_SPICE, COMPONENT, anonymous_namespace{d_cap.cc}::DEV_VCCAP, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, ELEMENT, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_cccs.cc}::DEV_CCCS, and anonymous_namespace{d_ccvs.cc}::DEV_CCVS.
Definition at line 73 of file e_card.h.
{}
virtual void CARD::tr_load () [inline, virtual]
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, BASE_SUBCKT, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_cccs.cc}::DEV_CCCS, and anonymous_namespace{d_ccvs.cc}::DEV_CCVS.
Definition at line 83 of file e_card.h.
Referenced by CARD_LIST::tr_load().
{}
virtual bool CARD::tr_needs_eval () const [inline, virtual]
Reimplemented in DEV_SPICE, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, BASE_SUBCKT, ELEMENT, STORAGE, and CCSRC_BASE.
Definition at line 79 of file e_card.h.
Referenced by COMPONENT::tr_queue_eval().
{return false;}
virtual void CARD::tr_queue_eval () [inline, virtual]
Reimplemented in COMPONENT, DEV_LOGIC, and BASE_SUBCKT.
Definition at line 80 of file e_card.h.
{}
virtual void CARD::tr_regress () [inline, virtual]
Reimplemented in DEV_SPICE, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, BASE_SUBCKT, and ELEMENT.
Definition at line 78 of file e_card.h.
{}
virtual void CARD::tr_restore () [inline, virtual]
Reimplemented in DEV_SPICE, DEV_LOGIC, BASE_SUBCKT, ELEMENT, and STORAGE.
Definition at line 75 of file e_card.h.
{}
TIME_PAIR CARD::tr_review () [virtual]
Reimplemented in DEV_SPICE, COMPONENT, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, ELEMENT, BASE_SUBCKT, and STORAGE.
Definition at line 190 of file e_card.cc.
References NEVER.
{
  return TIME_PAIR(NEVER,NEVER);
}
virtual void CARD::tr_unload () [inline, virtual]
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, BASE_SUBCKT, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, and CCSRC_BASE.
Definition at line 86 of file e_card.h.
References untested.
{untested();}
virtual bool CARD::use_obsolete_callback_parse () const [inline, virtual]
Reimplemented in COMPONENT, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, MODEL_TABLE, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_cccs.cc}::DEV_CCCS, and anonymous_namespace{d_ccvs.cc}::DEV_CCVS.
Definition at line 146 of file e_card.h.
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_args().
{return false;}
virtual bool CARD::use_obsolete_callback_print () const [inline, virtual]
Reimplemented in COMPONENT, and MODEL_TABLE.
Definition at line 147 of file e_card.h.
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_args(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_args(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_args().
{return false;}
virtual std::string CARD::value_name () const [pure virtual]
Implemented in DEV_SPICE, anonymous_namespace{d_cap.cc}::DEV_VCCAP, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, DEV_SUBCKT, anonymous_namespace{d_switch.cc}::SWITCH_BASE, MODEL_CARD, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, DEV_LOGIC, anonymous_namespace{d_net.cc}::DEV_NET, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, MODEL_SUBCKT, DEV_COMMENT, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_cccs.cc}::DEV_CCCS, anonymous_namespace{d_ccvs.cc}::DEV_CCVS, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_vs.cc}::DEV_VS, DEV_DOT, and CMD.
Referenced by COMPONENT::param_name(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_args(), and anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_args().
Member Data Documentation
bool CARD::_constant [private]
Definition at line 44 of file e_card.h.
int CARD::_evaliter [mutable, private]
Definition at line 41 of file e_card.h.
Referenced by evaluated().
node_t* CARD::_n [protected]
Definition at line 46 of file e_card.h.
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::ac_amps(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::ac_iwant_matrix(), ELEMENT::ac_iwant_matrix_active(), ELEMENT::ac_iwant_matrix_extended(), ELEMENT::ac_iwant_matrix_passive(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::ac_load(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::ac_load(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::ac_load(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::ac_load(), DEV_SPICE::ac_load(), ELEMENT::ac_load_active(), ELEMENT::ac_load_couple(), ELEMENT::ac_load_inode(), ELEMENT::ac_load_passive(), ELEMENT::ac_load_shunt(), ELEMENT::ac_load_source(), ELEMENT::ac_probe_ext(), DEV_LOGIC::ac_probe_ext(), connects_to(), DEV_LOGIC::dc_advance(), DEV_LOGIC::DEV_LOGIC(), DEV_SPICE::DEV_SPICE(), DEV_SUBCKT::DEV_SUBCKT(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::do_tr(), anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::do_tr(), DEV_SPICE::do_tr(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::do_tr_last(), ELEMENT::ELEMENT(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::expand(), DEV_SPICE::expand(), CCSRC_BASE::expand_last(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::expand_last(), COMPONENT::map_nodes(), MODEL_SUBCKT::MODEL_SUBCKT(), n_(), COMPONENT::node_is_connected(), COMPONENT::node_is_grounded(), COMPONENT::port_value(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::set_parameters(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::set_parameters(), COMPONENT::set_parameters(), COMPONENT::set_port_by_index(), COMPONENT::set_port_to_ground(), DEV_LOGIC::tr_accept(), DEV_LOGIC::tr_advance(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::tr_amps(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_amps(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::tr_amps(), DEV_LOGIC::tr_begin(), DEV_LOGIC::tr_eval_digital(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_input(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_input_limited(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_iwant_matrix(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_iwant_matrix(), ELEMENT::tr_iwant_matrix_active(), ELEMENT::tr_iwant_matrix_extended(), ELEMENT::tr_iwant_matrix_passive(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::tr_load(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_load(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::tr_load(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_load(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_load(), DEV_SPICE::tr_load(), ELEMENT::tr_load_active(), ELEMENT::tr_load_couple(), ELEMENT::tr_load_inode(), ELEMENT::tr_load_passive(), ELEMENT::tr_load_shunt(), ELEMENT::tr_load_source(), DEV_SPICE::tr_needs_eval(), ELEMENT::tr_probe_num(), DEV_LOGIC::tr_probe_num(), COMPONENT::tr_probe_num(), DEV_LOGIC::tr_regress(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_review(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::~DEV_CPOLY_CAP(), and anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::~DEV_CPOLY_G().
int CARD::_net_nodes
Definition at line 48 of file e_card.h.
Referenced by BASE_SUBCKT::net_nodes(), MODEL_SUBCKT::net_nodes(), DEV_LOGIC::net_nodes(), DEV_SUBCKT::net_nodes(), DEV_SPICE::net_nodes(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_element_using_obsolete_callback(), COMPONENT::set_port_by_index(), and COMPONENT::set_port_to_ground().
CARD* CARD::_owner [private]
Definition at line 43 of file e_card.h.
CARD_LIST* CARD::_subckt [private]
Definition at line 42 of file e_card.h.
Referenced by new_subckt(), and ~CARD().
The documentation for this class was generated from the following files:
savant/gnucap/src/e_card.h
savant/gnucap/src/e_card.cc