gnucap: COMPONENT Class Reference
COMPONENT Class Reference
#include <e_compon.h>
Public Member Functions
void precalc_first ()
void expand ()
void precalc_last ()
void tr_iwant_matrix ()
void tr_queue_eval ()
TIME_PAIR tr_review ()
void tr_accept ()
double tr_probe_num (const std::string &) const
void ac_iwant_matrix ()
bool is_device () const
void set_slave ()
void map_nodes ()
virtual const std::string current_probe_name () const
bool converged () const
void set_converged (bool s=true)
void set_not_converged ()
double mfactor () const
bool is_q_for_eval () const
void mark_q_for_eval ()
void mark_always_q_for_eval ()
void q_eval ()
void q_load ()
void q_accept ()
const MODEL_CARD * find_model (const std::string &name) const
void attach_model () const
COMMON_COMPONENT * mutable_common ()
const COMMON_COMPONENT * common () const
bool has_common () const
void attach_common (COMMON_COMPONENT *c)
void detach_common ()
void deflate_common ()
void set_dev_type (const std::string &new_type)
virtual std::string port_name (int) const =0
virtual void set_port_by_name (std::string &name, std::string &value)
virtual void set_port_by_index (int index, std::string &value)
bool port_exists (int i) const
const std::string port_value (int i) const
void set_port_to_ground (int index)
virtual std::string current_port_name (int) const
virtual const std::string current_port_value (int) const
virtual void set_current_port_by_index (int, const std::string &)
bool current_port_exists (int i) const
virtual int max_nodes () const
virtual int min_nodes () const
virtual int num_current_ports () const
virtual int tail_size () const
virtual int net_nodes () const
virtual int ext_nodes () const
virtual int int_nodes () const
virtual int matrix_nodes () const
virtual bool has_inode () const
virtual bool has_iv_probe () const
virtual bool is_source () const
virtual bool f_is_value () const
bool node_is_grounded (int i) const
virtual bool node_is_connected (int i) const
void set_param_by_name (std::string, std::string)
void set_param_by_index (int, std::string &, int)
int param_count () const
bool param_is_printable (int) const
std::string param_name (int) const
std::string param_name (int, int) const
std::string param_value (int) const
virtual void set_parameters (const std::string &Label, CARD *Parent, COMMON_COMPONENT *Common, double Value, int state_count, double state[], int node_count, const node_t nodes[])
void set_value (const PARAMETER< double > &v)
void set_value (double v)
void set_value (const std::string &v)
void set_value (double v, COMMON_COMPONENT *c)
const PARAMETER< double > & value () const
virtual bool print_type_in_spice () const =0
bool use_obsolete_callback_parse () const
bool use_obsolete_callback_print () const
void print_args_obsolete_callback (OMSTREAM &, LANGUAGE *) const
void obsolete_move_parameters_from_common (const COMMON_COMPONENT *)
Static Public Member Functions
static double volts_limited (const node_t &n1, const node_t &n2)
Public Attributes
TIME_PAIR _time_by
Protected Member Functions
COMPONENT ()
COMPONENT (const COMPONENT &p)
~COMPONENT ()
Protected Attributes
PARAMETER< double > _value
PARAMETER< double > _mfactor
Private Attributes
COMMON_COMPONENT * _common
double _mfactor_fixed
bool _converged
int _q_for_eval
Detailed Description
Definition at line 149 of file e_compon.h.
Constructor & Destructor Documentation
COMPONENT::COMPONENT () [explicit, protected]
Definition at line 370 of file e_compon.cc.
References CKT_BASE::_sim, and SIM_DATA::uninit().
  :CARD(),
   _common(0),
   _value(0),
   _mfactor(1),
   _mfactor_fixed(NOT_VALID),
   _converged(false),
   _q_for_eval(-1),
   _time_by()
{
  _sim->uninit();
}
COMPONENT::COMPONENT (const COMPONENT & p) [explicit, protected]
Definition at line 383 of file e_compon.cc.
References _common, CKT_BASE::_sim, attach_common(), and SIM_DATA::uninit().
  :CARD(p),
   _common(0),
   _value(p._value),
   _mfactor(p._mfactor),
   _mfactor_fixed(p._mfactor_fixed),
   _converged(p._converged),
   _q_for_eval(-1),
   _time_by(p._time_by)
{
  _sim->uninit();
  attach_common(p._common);
  assert(_common == p._common);
}
COMPONENT::~COMPONENT () [protected]
Definition at line 398 of file e_compon.cc.
References CKT_BASE::_sim, detach_common(), and SIM_DATA::uninit().
{
  detach_common();
  _sim->uninit();
}
Member Function Documentation
void COMPONENT::ac_iwant_matrix () [virtual]
Reimplemented from CARD.
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_cap.cc}::DEV_VCCAP, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, ELEMENT, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_cccs.cc}::DEV_CCCS, and anonymous_namespace{d_ccvs.cc}::DEV_CCVS.
Definition at line 579 of file e_compon.cc.
References CARD_LIST::ac_iwant_matrix(), is_device(), matrix_nodes(), CARD::subckt(), and untested.
{
  if (is_device()) {
    assert(matrix_nodes() == 0);
    if (subckt()) {
      subckt()->ac_iwant_matrix();
    }else{untested();
    }
  }else{
  }
}
void COMPONENT::attach_common (COMMON_COMPONENT * c) [inline]
Definition at line 218 of file e_compon.h.
References COMMON_COMPONENT::attach_common().
Referenced by COMPONENT(), deflate_common(), DEV_LOGIC::DEV_LOGIC(), DEV_SPICE::DEV_SPICE(), DEV_SUBCKT::DEV_SUBCKT(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::DEV_TRANSLINE(), expand(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_element_using_obsolete_callback(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_logic_using_obsolete_callback(), set_dev_type(), set_param_by_index(), set_param_by_name(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::set_parameters(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::set_parameters(), set_parameters(), set_value(), and anonymous_namespace{d_switch.cc}::SWITCH_BASE::SWITCH_BASE().
{COMMON_COMPONENT::attach_common(c,&_common);}
void COMPONENT::attach_model () const [inline]
Definition at line 212 of file e_compon.h.
Referenced by DEV_LOGIC::expand(), and anonymous_namespace{d_switch.cc}::SWITCH_BASE::expand().
{assert(has_common()); _common->attach_model(this);}
const COMMON_COMPONENT* COMPONENT::common () const [inline]
Definition at line 216 of file e_compon.h.
Referenced by ELEMENT::ac_eval(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::dc_advance(), deflate_common(), BASE_SUBCKT::dev_type(), DEV_LOGIC::dev_type(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::do_ac(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::do_tr(), DEV_LOGIC::expand(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::expand(), expand(), ELEMENT::has_ac_eval(), ELEMENT::has_tr_eval(), DEV_SUBCKT::param_count_dont_print(), DEV_SPICE::param_count_dont_print(), param_is_printable(), param_name(), param_value(), precalc_first(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::precalc_last(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::precalc_last(), print_args_obsolete_callback(), set_dev_type(), set_param_by_index(), set_param_by_name(), DEV_LOGIC::tr_accept(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_advance(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_advance(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_begin(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_begin(), ELEMENT::tr_eval(), DEV_LOGIC::tr_eval_digital(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_load(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_regress(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_regress(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_review(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_review(), use_obsolete_callback_parse(), and use_obsolete_callback_print().
{return _common;}
bool COMPONENT::converged () const [inline]
Definition at line 188 of file e_compon.h.
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_tr(), BASE_SUBCKT::do_tr(), DEV_LOGIC::do_tr(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::do_tr(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::do_tr(), DEV_SPICE::do_tr(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::do_tr_con_chk_and_q(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::do_tr_con_chk_and_q(), DEV_LOGIC::tr_eval_digital(), STORAGE::tr_needs_eval(), and DEV_SPICE::tr_needs_eval().
{return _converged;}
bool COMPONENT::current_port_exists (int i) const [inline]
Definition at line 236 of file e_compon.h.
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_ports(), anonymous_namespace{lang_spectre.cc}::print_ports(), anonymous_namespace{lang_verilog.cc}::print_ports_long(), and anonymous_namespace{lang_verilog.cc}::print_ports_short().
{return i < num_current_ports();}
virtual std::string COMPONENT::current_port_name (int) const [inline, virtual]
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_switch.cc}::DEV_CSWITCH, anonymous_namespace{d_ccvs.cc}::DEV_CCVS, and anonymous_namespace{d_cccs.cc}::DEV_CCCS.
Definition at line 233 of file e_compon.h.
Referenced by anonymous_namespace{lang_verilog.cc}::print_ports_long().
{return "";}
const std::string COMPONENT::current_port_value (int) const [virtual]
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_switch.cc}::DEV_CSWITCH, and CCSRC_BASE.
Definition at line 718 of file e_compon.cc.
References unreachable, and untested.
Referenced by anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::current_port_value(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_ports(), anonymous_namespace{lang_spectre.cc}::print_ports(), anonymous_namespace{lang_verilog.cc}::print_ports_long(), and anonymous_namespace{lang_verilog.cc}::print_ports_short().
{untested();
  unreachable();
  static std::string s;
  return s;
}
virtual const std::string COMPONENT::current_probe_name () const [inline, virtual]
Definition at line 186 of file e_compon.h.
References untested.
{untested(); return "";}
void COMPONENT::deflate_common ()
Definition at line 483 of file e_compon.cc.
References attach_common(), common(), COMMON_COMPONENT::deflate(), has_common(), mutable_common(), unreachable, and untested.
{untested();
  unreachable();
  if (has_common()) {untested();
    COMMON_COMPONENT* deflated_common = mutable_common()->deflate();
    if (deflated_common != common()) {untested();
      attach_common(deflated_common);
    }else{untested();
    }
  }else{untested();
    unreachable();
  }
}
void COMPONENT::detach_common () [inline]
Definition at line 219 of file e_compon.h.
References COMMON_COMPONENT::detach_common().
Referenced by set_value(), and ~COMPONENT().
{COMMON_COMPONENT::detach_common(&_common);}
void COMPONENT::expand () [virtual]
Reimplemented from CARD.
Reimplemented in DEV_SPICE, anonymous_namespace{d_switch.cc}::DEV_CSWITCH, DEV_SUBCKT, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, and MODEL_SUBCKT.
Definition at line 497 of file e_compon.cc.
References attach_common(), COMMON_COMPONENT::clone(), common(), COMMON_COMPONENT::deflate(), COMMON_COMPONENT::expand(), has_common(), and untested.
{
  CARD::expand();
  if (has_common()) {
    COMMON_COMPONENT* new_common = common()->clone();
    new_common->expand(this);
    COMMON_COMPONENT* deflated_common = new_common->deflate();
    if (deflated_common != common()) {
      attach_common(deflated_common);
    }else{untested();
    }
  }else{
  }
}
virtual int COMPONENT::ext_nodes () const [inline, virtual]
Reimplemented in anonymous_namespace{d_switch.cc}::DEV_CSWITCH, and CCSRC_BASE.
Definition at line 244 of file e_compon.h.
Referenced by ELEMENT::ac_iwant_matrix_extended(), map_nodes(), and ELEMENT::tr_iwant_matrix_extended().
{return max_nodes();}
virtual bool COMPONENT::f_is_value () const [inline, virtual]
Reimplemented in anonymous_namespace{d_cap.cc}::DEV_VCCAP, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, anonymous_namespace{d_cs.cc}::DEV_CS, and anonymous_namespace{d_vs.cc}::DEV_VS.
Definition at line 251 of file e_compon.h.
Referenced by EVAL_BM_TABLE::tr_eval(), anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::tr_eval(), anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::tr_eval(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::tr_eval(), anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY::tr_eval(), and anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT::tr_eval().
{return false;}
const MODEL_CARD * COMPONENT::find_model (const std::string & name) const
Definition at line 744 of file e_compon.cc.
References error(), CARD::find_in_my_scope(), MODEL_CARD::is_valid(), itested, CARD::long_label(), CARD::owner(), to_string(), unreachable, and untested.
Referenced by COMMON_COMPONENT::attach_model(), and DEV_SPICE::expand().
{
  if (modelname == "") {
    throw Exception(long_label() + ": missing args -- need model name");
    unreachable();
    return NULL;
  }else{
    const CARD* c = NULL;
    {
      int bin_count = 0;
      for (const CARD* Scope = this; Scope && !c; Scope = Scope->owner()) {
        // start here, looking out
        try {
          c = Scope->find_in_my_scope(modelname);
        }catch (Exception_Cant_Find& e1) {
          // didn't find plain model.  try binned models
          bin_count = 0;
          for (;;) {
            // loop over binned models
            std::string extended_name = modelname + '.' + to_string(++bin_count);
            try {
              c = Scope->find_in_my_scope(extended_name);
            }catch (Exception_Cant_Find& e2) {
              // that's all .. looked at all of them
              c = NULL;
              break;
            }
            const MODEL_CARD* m = dynamic_cast<const MODEL_CARD*>(c);
            if (m && m->is_valid(this)) {
              //matching name and correct bin
              break;
            }else{
              // keep looking
            }
          }
        }
      }
      if (!c) {
        if (bin_count <= 1) {
          throw Exception_Cant_Find(long_label(), modelname);
        }else{
          throw Exception(long_label() + ": no bins match: " + modelname);
        }
        unreachable();
      }else{
      }
    }
    // found something, what is it?
    assert(c);
    const MODEL_CARD* model = dynamic_cast<const MODEL_CARD*>(c);
    if (!model) {untested();
      throw Exception_Type_Mismatch(long_label(), modelname, ".model");
    }else if (!model->is_valid(this)) {itested();
      error(bWARNING, long_label() + ", " + modelname
           + "\nmodel and device parameters are incompatible, using anyway\n");
    }else{
    }
    assert(model);
    return model;
  }
}
bool COMPONENT::has_common () const [inline]
Definition at line 217 of file e_compon.h.
Referenced by deflate_common(), DEV_LOGIC::dev_type(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::expand(), expand(), ELEMENT::has_ac_eval(), ELEMENT::has_tr_eval(), param_is_printable(), param_name(), param_value(), precalc_first(), precalc_last(), print_args_obsolete_callback(), set_param_by_index(), set_param_by_name(), tr_accept(), tr_review(), use_obsolete_callback_parse(), and use_obsolete_callback_print().
{return _common;}
virtual bool COMPONENT::has_inode () const [inline, virtual]
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 248 of file e_compon.h.
Referenced by CCSRC_BASE::expand_last().
{return false;}
virtual bool COMPONENT::has_iv_probe () const [inline, virtual]
Reimplemented in anonymous_namespace{d_cap.cc}::DEV_VCCAP, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, anonymous_namespace{d_net.cc}::DEV_NET, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vs.cc}::DEV_VS, and anonymous_namespace{d_res.cc}::DEV_RESISTANCE.
Definition at line 249 of file e_compon.h.
Referenced by CCSRC_BASE::expand_last().
{return false;}
virtual int COMPONENT::int_nodes () const [inline, virtual]
Reimplemented in DEV_SPICE, and anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 245 of file e_compon.h.
Referenced by ELEMENT::ac_iwant_matrix_extended(), map_nodes(), and ELEMENT::tr_iwant_matrix_extended().
{return 0;}
bool COMPONENT::is_device () const [inline, virtual]
Reimplemented from CARD.
Reimplemented in MODEL_SUBCKT.
Definition at line 183 of file e_compon.h.
Referenced by ac_iwant_matrix(), ELEMENT::ac_iwant_matrix_extended(), map_nodes(), tr_iwant_matrix(), ELEMENT::tr_iwant_matrix_active(), ELEMENT::tr_iwant_matrix_extended(), and ELEMENT::tr_iwant_matrix_passive().
{return true;}
bool COMPONENT::is_q_for_eval () const [inline]
Definition at line 203 of file e_compon.h.
Referenced by q_eval(), CCSRC_BASE::tr_needs_eval(), DEV_LOGIC::tr_needs_eval(), and DEV_SPICE::tr_needs_eval().
{return (_q_for_eval >= _sim->iteration_tag());}
virtual bool COMPONENT::is_source () const [inline, virtual]
Reimplemented in anonymous_namespace{d_cs.cc}::DEV_CS, and anonymous_namespace{d_vs.cc}::DEV_VS.
Definition at line 250 of file e_compon.h.
Referenced by ELEMENT::ac_amps(), ELEMENT::ac_probe_ext(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::tr_eval(), and anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::tr_review().
{return false;}
void COMPONENT::map_nodes () [virtual]
Reimplemented from CARD.
Reimplemented in MODEL_SUBCKT.
Definition at line 549 of file e_compon.cc.
References CARD::_n, ext_nodes(), int_nodes(), is_device(), node_t::map(), CARD_LIST::map_nodes(), max_nodes(), min_nodes(), net_nodes(), and CARD::subckt().
{
  assert(is_device());
  assert(0 <= min_nodes());
  //assert(min_nodes() <= net_nodes());
  assert(net_nodes() <= max_nodes());
  //assert(ext_nodes() + int_nodes() == matrix_nodes());
  for (int ii = 0; ii < ext_nodes()+int_nodes(); ++ii) {
    _n[ii].map();
  }
  if (subckt()) {
    subckt()->map_nodes();
  }else{
  }
}
void COMPONENT::mark_always_q_for_eval () [inline]
Definition at line 205 of file e_compon.h.
Referenced by set_slave().
{_q_for_eval = INT_MAX;}
void COMPONENT::mark_q_for_eval () [inline]
Definition at line 204 of file e_compon.h.
Referenced by q_eval().
{_q_for_eval = _sim->iteration_tag();}
virtual int COMPONENT::matrix_nodes () const [inline, virtual]
Reimplemented in DEV_SPICE, anonymous_namespace{d_cap.cc}::DEV_VCCAP, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, DEV_SUBCKT, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_net.cc}::DEV_NET, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, MODEL_SUBCKT, anonymous_namespace{d_vcr.cc}::DEV_VCR, BASE_SUBCKT, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_vs.cc}::DEV_VS, and CCSRC_BASE.
Definition at line 246 of file e_compon.h.
Referenced by ac_iwant_matrix(), ELEMENT::ac_iwant_matrix_extended(), tr_iwant_matrix(), ELEMENT::tr_iwant_matrix_active(), ELEMENT::tr_iwant_matrix_extended(), and ELEMENT::tr_iwant_matrix_passive().
{return 0;}
virtual int COMPONENT::max_nodes () const [inline, virtual]
Reimplemented in DEV_SPICE, anonymous_namespace{d_switch.cc}::DEV_CSWITCH, anonymous_namespace{d_cap.cc}::DEV_VCCAP, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_switch.cc}::DEV_VSWITCH, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, DEV_SUBCKT, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_net.cc}::DEV_NET, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, MODEL_SUBCKT, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_vs.cc}::DEV_VS, and CCSRC_BASE.
Definition at line 238 of file e_compon.h.
References unreachable.
Referenced by map_nodes(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_element_using_obsolete_callback(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_instance(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_logic_using_obsolete_callback(), set_port_by_index(), set_port_by_name(), and set_port_to_ground().
{unreachable(); return 0;}
double COMPONENT::mfactor () const [inline]
Definition at line 192 of file e_compon.h.
References NOT_VALID, and CARD::owner().
Referenced by anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::ac_load(), ELEMENT::ac_load_active(), ELEMENT::ac_load_couple(), ELEMENT::ac_load_diagonal_point(), ELEMENT::ac_load_extended(), ELEMENT::ac_load_inode(), ELEMENT::ac_load_passive(), ELEMENT::ac_load_point(), ELEMENT::ac_load_shunt(), ELEMENT::ac_load_source(), ELEMENT::ac_load_source_point(), ELEMENT::ac_probe_ext(), ELEMENT::dampdiff(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_load(), and ELEMENT::tr_probe_num().
{
    assert(_mfactor_fixed != NOT_VALID);
    if (const COMPONENT* o = prechecked_cast<const COMPONENT*>(owner())) {
      assert(_mfactor_fixed == o->mfactor() * _mfactor);
    }else{
      assert(_mfactor_fixed == _mfactor);
    }
    return _mfactor_fixed;
  }
virtual int COMPONENT::min_nodes () const [inline, virtual]
Reimplemented in DEV_SPICE, anonymous_namespace{d_switch.cc}::DEV_CSWITCH, anonymous_namespace{d_cap.cc}::DEV_VCCAP, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_switch.cc}::DEV_VSWITCH, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, DEV_SUBCKT, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_net.cc}::DEV_NET, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, MODEL_SUBCKT, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_vs.cc}::DEV_VS, and CCSRC_BASE.
Definition at line 239 of file e_compon.h.
References unreachable.
Referenced by map_nodes(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_element_using_obsolete_callback(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_instance(), and anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_logic_using_obsolete_callback().
{unreachable(); return 0;}
COMMON_COMPONENT* COMPONENT::mutable_common () [inline]
Definition at line 215 of file e_compon.h.
Referenced by deflate_common(), DEV_SUBCKT::expand(), CARDSTASH::operator=(), DEV_SUBCKT::precalc_first(), precalc_first(), DEV_SPICE::precalc_first(), DEV_SUBCKT::precalc_last(), precalc_last(), DEV_SPICE::set_param_by_name(), and DEV_SPICE::Set_param_by_name().
{return _common;}
virtual int COMPONENT::net_nodes () const [inline, virtual]
Reimplemented from CARD.
Reimplemented in DEV_SPICE, anonymous_namespace{d_switch.cc}::DEV_CSWITCH, anonymous_namespace{d_cap.cc}::DEV_VCCAP, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_switch.cc}::DEV_VSWITCH, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, DEV_SUBCKT, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_net.cc}::DEV_NET, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, MODEL_SUBCKT, anonymous_namespace{d_vcr.cc}::DEV_VCR, BASE_SUBCKT, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_vs.cc}::DEV_VS, and CCSRC_BASE.
Definition at line 243 of file e_compon.h.
References untested.
Referenced by map_nodes(), node_is_connected(), node_is_grounded(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_logic_using_obsolete_callback(), port_value(), set_parameters(), and tr_probe_num().
{untested();return 0;} //override
bool COMPONENT::node_is_connected (int i) const [virtual]
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_switch.cc}::DEV_CSWITCH, and CCSRC_BASE.
Definition at line 412 of file e_compon.cc.
References CARD::_n, node_t::is_connected(), and net_nodes().
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_ports().
{
  assert(_n);
  assert(i >= 0);
  assert(i < net_nodes());
  return _n[i].is_connected();
}
bool COMPONENT::node_is_grounded (int i) const
Definition at line 404 of file e_compon.cc.
References CARD::_n, node_t::is_grounded(), and net_nodes().
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_ports().
{
  assert(_n);
  assert(i >= 0);
  assert(i < net_nodes());
  return _n[i].is_grounded();
}
virtual int COMPONENT::num_current_ports () const [inline, virtual]
Reimplemented in anonymous_namespace{d_switch.cc}::DEV_CSWITCH, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, and CCSRC_BASE.
Definition at line 240 of file e_compon.h.
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_element_using_obsolete_callback().
{return 0;}
void COMPONENT::obsolete_move_parameters_from_common (const COMMON_COMPONENT * dc)
Definition at line 862 of file e_compon.cc.
References _mfactor, _value, COMMON_COMPONENT::mfactor(), and COMMON_COMPONENT::value().
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_element_using_obsolete_callback().
{
  assert(dc);
  _value   = dc->value();
  _mfactor = dc->mfactor();
}
int COMPONENT::param_count () const [inline, virtual]
Reimplemented from CARD.
Reimplemented in ELEMENT, and anonymous_namespace{d_net.cc}::DEV_NET.
Definition at line 259 of file e_compon.h.
References CARD::param_count(), and param_count().
Referenced by ELEMENT::param_count(), param_count(), param_is_printable(), param_name(), param_value(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_args(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_args(), and set_param_by_index().
        {return ((has_common()) ? (common()->param_count()) : (2 + CARD::param_count()));}
bool COMPONENT::param_is_printable (int i) const [virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_net.cc}::DEV_NET.
Definition at line 656 of file e_compon.cc.
References _mfactor, common(), has_common(), PARAMETER< T >::has_hard_value(), param_count(), COMMON_COMPONENT::param_is_printable(), and value().
Referenced by anonymous_namespace{d_net.cc}::DEV_NET::param_is_printable(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_args(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_args().
{
  if (has_common()) {
    return common()->param_is_printable(i);
  }else{
    switch (COMPONENT::param_count() - 1 - i) {
    case 0:  return value().has_hard_value();
    case 1:  return _mfactor.has_hard_value();
    default: return CARD::param_is_printable(i);
    }
  }
}
std::string COMPONENT::param_name (int i) const [virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_net.cc}::DEV_NET.
Definition at line 669 of file e_compon.cc.
References common(), has_common(), param_count(), COMMON_COMPONENT::param_name(), and CARD::value_name().
Referenced by param_name(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_args(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_args().
{
  if (has_common()) {
    return common()->param_name(i);
  }else{
    switch (COMPONENT::param_count() - 1 - i) {
    case 0:  return value_name();
    case 1:  return "m";
    default: return CARD::param_name(i);
    }
  }
}
std::string COMPONENT::param_name (int i, int j) const [virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_net.cc}::DEV_NET.
Definition at line 682 of file e_compon.cc.
References common(), has_common(), CARD::param_count(), COMMON_COMPONENT::param_name(), param_name(), and untested.
{
  if (has_common()) {untested();
    return common()->param_name(i,j);
  }else{
    if (j == 0) {
      return param_name(i);
    }else if (i >= CARD::param_count()) {untested();
      return "";
    }else{untested();
      return CARD::param_name(i,j);
    }
  }
}
std::string COMPONENT::param_value (int i) const [virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_net.cc}::DEV_NET.
Definition at line 697 of file e_compon.cc.
References _mfactor, common(), has_common(), param_count(), COMMON_COMPONENT::param_value(), PARAMETER< T >::string(), and value().
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_args(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_args().
{
  if (has_common()) {
    return common()->param_value(i);
  }else{
    switch (COMPONENT::param_count() - 1 - i) {
    case 0:  return value().string();
    case 1:  return _mfactor.string();
    default: return CARD::param_value(i);
    }
  }
}
bool COMPONENT::port_exists (int i) const [inline]
Definition at line 229 of file e_compon.h.
References CARD::net_nodes().
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_ports(), anonymous_namespace{lang_spectre.cc}::print_ports(), anonymous_namespace{lang_verilog.cc}::print_ports_long(), and anonymous_namespace{lang_verilog.cc}::print_ports_short().
{return i < net_nodes();}
virtual std::string COMPONENT::port_name (int) const [pure virtual]
Implemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_switch.cc}::DEV_CSWITCH, anonymous_namespace{d_cap.cc}::DEV_VCCAP, anonymous_namespace{d_switch.cc}::DEV_VSWITCH, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, DEV_LOGIC, DEV_SUBCKT, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vs.cc}::DEV_VS, MODEL_SUBCKT, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_net.cc}::DEV_NET, anonymous_namespace{d_ccvs.cc}::DEV_CCVS, and anonymous_namespace{d_cccs.cc}::DEV_CCCS.
Referenced by anonymous_namespace{lang_verilog.cc}::print_ports_long(), and set_port_by_name().
const std::string COMPONENT::port_value (int i) const
Definition at line 710 of file e_compon.cc.
References CARD::_n, net_nodes(), and node_t::short_label().
Referenced by DEV_SUBCKT::port_name(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_ports(), anonymous_namespace{lang_spectre.cc}::print_ports(), anonymous_namespace{lang_verilog.cc}::print_ports_long(), and anonymous_namespace{lang_verilog.cc}::print_ports_short().
{
  assert(_n);
  assert(i >= 0);
  assert(i < net_nodes());
  return _n[i].short_label();
}
void COMPONENT::precalc_first () [virtual]
Reimplemented from CARD.
Reimplemented in DEV_SPICE, DEV_SUBCKT, DEV_LOGIC, and MODEL_SUBCKT.
Definition at line 512 of file e_compon.cc.
References _mfactor, _mfactor_fixed, _value, common(), PARAMETER< T >::e_val(), error(), has_common(), CARD::long_label(), COMMON_COMPONENT::mfactor(), mutable_common(), CARD::owner(), COMMON_COMPONENT::precalc_first(), CARD::scope(), and trace1.
Referenced by anonymous_namespace{s_dc.cc}::DCOP::finish().
{
  CARD::precalc_first();
  if (has_common()) {
    try {
      mutable_common()->precalc_first(scope());
    }catch (Exception_Precalc& e) {
      error(bWARNING, long_label() + ": " + e.message());
    }
    _mfactor = common()->mfactor();
  }else{
  }
  _mfactor.e_val(1, scope());
  _value.e_val(0.,scope());
  trace1(long_label().c_str(), double(_mfactor));
  if (const COMPONENT* o = prechecked_cast<const COMPONENT*>(owner())) {
    _mfactor_fixed = o->mfactor() * _mfactor;
  }else{
    _mfactor_fixed =  _mfactor;
  }
  trace1(long_label().c_str(), _mfactor_fixed);
}
void COMPONENT::precalc_last () [virtual]
Reimplemented from CARD.
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, DEV_SUBCKT, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, MODEL_SUBCKT, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_vcr.cc}::DEV_VCR, ELEMENT, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, STORAGE, anonymous_namespace{d_cccs.cc}::DEV_CCCS, and anonymous_namespace{d_ccvs.cc}::DEV_CCVS.
Definition at line 536 of file e_compon.cc.
References error(), has_common(), CARD::long_label(), mutable_common(), COMMON_COMPONENT::precalc_last(), and CARD::scope().
{
  CARD::precalc_last();
  if (has_common()) {
    try {
      mutable_common()->precalc_last(scope());
    }catch (Exception_Precalc& e) {
      error(bWARNING, long_label() + ": " + e.message());
    }
  }else{
  }
}
void COMPONENT::print_args_obsolete_callback (OMSTREAM & o, LANGUAGE * lang) const [virtual]
Reimplemented from CARD.
Definition at line 476 of file e_compon.cc.
References common(), has_common(), and COMMON_COMPONENT::print_common_obsolete_callback().
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_args(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_args().
{
  assert(lang);
  assert(has_common());
  common()->print_common_obsolete_callback(o, lang);
}
virtual bool COMPONENT::print_type_in_spice () const [pure virtual]
Implemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, DEV_SUBCKT, anonymous_namespace{d_switch.cc}::SWITCH_BASE, anonymous_namespace{d_net.cc}::DEV_NET, DEV_LOGIC, ELEMENT, and MODEL_SUBCKT.
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_instance(), and anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_type().
void COMPONENT::q_accept () [inline]
Definition at line 208 of file e_compon.h.
Referenced by DEV_LOGIC::tr_review(), and anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_review().
{_sim->_acceptq.push_back(this);}
void COMPONENT::q_eval ()
Definition at line 809 of file e_compon.cc.
References SIM_DATA::_evalq_uc, CKT_BASE::_sim, is_q_for_eval(), itested, and mark_q_for_eval().
Referenced by DEV_LOGIC::tr_advance(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_advance(), tr_queue_eval(), and DEV_LOGIC::tr_regress().
{
  if(!is_q_for_eval()) {
    mark_q_for_eval();
    _sim->_evalq_uc->push_back(this);
  }else{itested();
  }
}
void COMPONENT::q_load () [inline]
Definition at line 207 of file e_compon.h.
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_tr(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::do_tr(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::do_tr(), DEV_SPICE::do_tr(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::do_tr_con_chk_and_q(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::do_tr_con_chk_and_q(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::do_tr_last(), and DEV_LOGIC::tr_eval_digital().
{_sim->_loadq.push_back(this);}
void COMPONENT::set_converged (bool s = true) [inline]
Definition at line 189 of file e_compon.h.
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_tr(), BASE_SUBCKT::do_tr(), DEV_LOGIC::do_tr(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::do_tr(), DEV_SPICE::do_tr(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::do_tr_con_chk_and_q(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::do_tr_con_chk_and_q(), DEV_SPICE::internal_precalc(), STORAGE::precalc_last(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::precalc_last(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_advance(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_begin(), ELEMENT::tr_eval(), DEV_LOGIC::tr_eval_digital(), and anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_regress().
{_converged = s;}
virtual void COMPONENT::set_current_port_by_index (int , const std::string &) [inline, virtual]
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 235 of file e_compon.h.
References unreachable.
{unreachable();}
void COMPONENT::set_dev_type (const std::string & new_type) [virtual]
Reimplemented from CARD.
Reimplemented in DEV_SPICE.
Definition at line 461 of file e_compon.cc.
References attach_common(), COMMON_COMPONENT::clone(), common(), CARD::dev_type(), and COMMON_COMPONENT::set_modelname().
{
  if (common()) {
    if (new_type != dev_type()) {
      COMMON_COMPONENT* c = common()->clone();
      assert(c);
      c->set_modelname(new_type);
      attach_common(c);
    }else{
    }
  }else{
    CARD::set_dev_type(new_type);
  }
}
void COMPONENT::set_not_converged () [inline]
Definition at line 190 of file e_compon.h.
Referenced by anonymous_namespace{d_switch.cc}::SWITCH_BASE::do_tr().
{_converged = false;}
void COMPONENT::set_param_by_index (int i, std::string & Value, int offset) [virtual]
Reimplemented from CARD.
Definition at line 640 of file e_compon.cc.
References _mfactor, _value, attach_common(), COMMON_COMPONENT::clone(), common(), has_common(), param_count(), COMMON_COMPONENT::set_param_by_index(), and untested.
Referenced by DEV_SPICE::Set_param_by_index().
{
  if (has_common()) {untested();
    COMMON_COMPONENT* c = common()->clone();
    assert(c);
    c->set_param_by_index(i, Value, offset);
    attach_common(c);
  }else{
    switch (COMPONENT::param_count() - 1 - i) {
    case 0: _value = Value; break;
    case 1: _mfactor = Value; break;
    default: CARD::set_param_by_index(i, Value, offset);
    }
  }
}
void COMPONENT::set_param_by_name (std::string Name, std::string Value) [virtual]
Reimplemented from CARD.
Reimplemented in DEV_SPICE, and anonymous_namespace{d_net.cc}::DEV_NET.
Definition at line 628 of file e_compon.cc.
References attach_common(), COMMON_COMPONENT::clone(), common(), has_common(), and COMMON_COMPONENT::set_param_by_name().
{
  if (has_common()) {
    COMMON_COMPONENT* c = common()->clone();
    assert(c);
    c->set_param_by_name(Name, Value);
    attach_common(c);
  }else{
    CARD::set_param_by_name(Name, Value);
  }
}
void COMPONENT::set_parameters (const std::string & Label, CARD * Parent, COMMON_COMPONENT * Common, double Value, int state_count, double state[], int node_count, const node_t nodes[]) [virtual]
Reimplemented in anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, and anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G.
Definition at line 593 of file e_compon.cc.
References CARD::_n, attach_common(), notstd::copy_n(), net_nodes(), CKT_BASE::set_label(), CARD::set_owner(), and set_value().
Referenced by CCSRC_BASE::set_parameters_cc().
{
  set_label(Label);
  set_owner(Owner);
  set_value(Value);
  attach_common(Common);
  assert(node_count <= net_nodes());
  notstd::copy_n(Nodes, node_count, _n);
}
void COMPONENT::set_port_by_index (int index, std::string & value) [virtual]
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_switch.cc}::DEV_CSWITCH, and CCSRC_BASE.
Definition at line 433 of file e_compon.cc.
References CARD::_n, CARD::_net_nodes, itested, max_nodes(), node_t::new_node(), and untested.
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_ports(), anonymous_namespace{lang_spectre.cc}::parse_ports(), anonymous_namespace{lang_verilog.cc}::parse_ports(), and set_port_by_name().
{
  if (num <= max_nodes()) {
    _n[num].new_node(ext_name, this);
    if (num+1 > _net_nodes) {
      // make the list bigger
      _net_nodes = num+1;
    }else{itested();
      // it's already big enough, probably assigning out of order
    }
  }else{untested();
    throw Exception_Too_Many(num, max_nodes(), 0/*offset*/);
  }
}
void COMPONENT::set_port_by_name (std::string & name, std::string & value) [virtual]
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, and anonymous_namespace{d_switch.cc}::DEV_CSWITCH.
Definition at line 420 of file e_compon.cc.
References itested, max_nodes(), port_name(), set_port_by_index(), and untested.
Referenced by anonymous_namespace{lang_verilog.cc}::parse_ports(), and anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::set_port_by_name().
{itested();
  for (int i=0; i<max_nodes(); ++i) {itested();
    if (int_name == port_name(i)) {itested();
      set_port_by_index(i, ext_name);
      return;
    }else{itested();
    }
  }
  untested();
  throw Exception_No_Match(int_name);
}
void COMPONENT::set_port_to_ground (int index)
Definition at line 448 of file e_compon.cc.
References CARD::_n, CARD::_net_nodes, max_nodes(), node_t::set_to_ground(), and untested.
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_ports().
{untested();
  if (num <= max_nodes()) {untested();
    _n[num].set_to_ground(this);
    if (num+1 > _net_nodes) {untested();
      _net_nodes = num+1;
    }else{untested();
    }
  }else{untested();
    throw Exception_Too_Many(num, max_nodes(), 0/*offset*/);
  }
}
void COMPONENT::set_slave () [virtual]
Reimplemented from CARD.
Definition at line 609 of file e_compon.cc.
References mark_always_q_for_eval(), CARD_LIST::set_slave(), and CARD::subckt().
{
  mark_always_q_for_eval();
  if (subckt()) {
    subckt()->set_slave();
  }else{
  }
}
void COMPONENT::set_value (const PARAMETER< double > & v) [inline]
Definition at line 270 of file e_compon.h.
Referenced by anonymous_namespace{c_modify.cc}::faultbranch(), anonymous_namespace{c_modify.cc}::modify_fault(), CARDSTASH::restore(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::set_parameters(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::set_parameters(), set_parameters(), set_value(), and anonymous_namespace{s_dc.cc}::DC::setup().
{_value = v;}
void COMPONENT::set_value (double v) [inline]
Definition at line 271 of file e_compon.h.
{_value = v;}
void COMPONENT::set_value (const std::string & v) [inline]
Definition at line 272 of file e_compon.h.
References untested.
{untested(); _value = v;}
void COMPONENT::set_value (double v, COMMON_COMPONENT * c)
Definition at line 618 of file e_compon.cc.
References _common, attach_common(), detach_common(), and set_value().
{
  if (c != _common) {
    detach_common();
    attach_common(c);
  }else{
  }
  set_value(v);
}
virtual int COMPONENT::tail_size () const [inline, virtual]
Reimplemented in DEV_SPICE, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, and BASE_SUBCKT.
Definition at line 241 of file e_compon.h.
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_instance(), and anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_logic_using_obsolete_callback().
{return 0;}
void COMPONENT::tr_accept () [virtual]
Reimplemented from CARD.
Reimplemented in DEV_SPICE, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, DEV_LOGIC, and BASE_SUBCKT.
Definition at line 836 of file e_compon.cc.
References _common, has_common(), and COMMON_COMPONENT::tr_accept().
{
  if(has_common()) {
    _common->tr_accept(this);
  }else{
  }
}
void COMPONENT::tr_iwant_matrix () [virtual]
Reimplemented from CARD.
Reimplemented in DEV_SPICE, anonymous_namespace{d_cap.cc}::DEV_VCCAP, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_admit.cc}::DEV_VCCS, anonymous_namespace{d_cap.cc}::DEV_TRANSCAP, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, ELEMENT, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_cccs.cc}::DEV_CCCS, and anonymous_namespace{d_ccvs.cc}::DEV_CCVS.
Definition at line 567 of file e_compon.cc.
References is_device(), matrix_nodes(), CARD::subckt(), CARD_LIST::tr_iwant_matrix(), and untested.
{
  if (is_device()) {
    assert(matrix_nodes() == 0);
    if (subckt()) {
      subckt()->tr_iwant_matrix();
    }else{untested();
    }
  }else{
  }
}
double COMPONENT::tr_probe_num (const std::string & x) const [virtual]
Reimplemented from CKT_BASE.
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, DEV_SUBCKT, DEV_LOGIC, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, ELEMENT, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, and STORAGE.
Definition at line 725 of file e_compon.cc.
References TIME_PAIR::_error_estimate, TIME_PAIR::_event, CARD::_n, CS::_STRING, _time_by, BIGBIG, CS::ctoi(), net_nodes(), NOT_VALID, Umatch(), CS::umatch(), and node_t::v0().
{
  CS cmd(CS::_STRING, x);
  if (cmd.umatch("v")) {
    int nn = cmd.ctoi();
    return (nn > 0 && nn <= net_nodes()) ? _n[nn-1].v0() : NOT_VALID;
  }else if (Umatch(x, "error{time} |next{time} ")) {
    return (_time_by._error_estimate < BIGBIG) ? _time_by._error_estimate : 0;
  }else if (Umatch(x, "timef{uture} ")) {
    return (_time_by._error_estimate < _time_by._event)
      ? _time_by._error_estimate
      : _time_by._event;
  }else if (Umatch(x, "event{time} ")) {
    return (_time_by._event < BIGBIG) ? _time_by._event : 0;
  }else{
    return CARD::tr_probe_num(x);
  }
}
void COMPONENT::tr_queue_eval () [virtual]
Reimplemented from CARD.
Reimplemented in DEV_LOGIC, and BASE_SUBCKT.
Definition at line 818 of file e_compon.cc.
References q_eval(), and CARD::tr_needs_eval().
{
  if(tr_needs_eval()) {
    q_eval();
  }else{
  }
}
TIME_PAIR COMPONENT::tr_review () [virtual]
Reimplemented from CARD.
Reimplemented in DEV_SPICE, anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_trln.cc}::DEV_TRANSLINE, anonymous_namespace{d_switch.cc}::SWITCH_BASE, DEV_LOGIC, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP, ELEMENT, BASE_SUBCKT, and STORAGE.
Definition at line 826 of file e_compon.cc.
References _common, _time_by, has_common(), TIME_PAIR::reset(), and COMMON_COMPONENT::tr_review().
{
  _time_by.reset();
  if(has_common()) {
    return _common->tr_review(this);
  }else{
    return _time_by;
  }
}
bool COMPONENT::use_obsolete_callback_parse () const [virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE, anonymous_namespace{d_admit.cc}::DEV_ADMITTANCE, anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE, anonymous_namespace{d_vcg.cc}::DEV_VCG, anonymous_namespace{d_cs.cc}::DEV_CS, anonymous_namespace{d_vs.cc}::DEV_VS, anonymous_namespace{d_res.cc}::DEV_RESISTANCE, anonymous_namespace{d_vcr.cc}::DEV_VCR, anonymous_namespace{d_vcvs.cc}::DEV_VCVS, anonymous_namespace{d_cccs.cc}::DEV_CCCS, and anonymous_namespace{d_ccvs.cc}::DEV_CCVS.
Definition at line 844 of file e_compon.cc.
References common(), has_common(), and COMMON_COMPONENT::use_obsolete_callback_parse().
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_instance().
{
  if (has_common()) {
    return common()->use_obsolete_callback_parse();
  }else{
    return false;
  }
}
bool COMPONENT::use_obsolete_callback_print () const [virtual]
Reimplemented from CARD.
Definition at line 853 of file e_compon.cc.
References common(), has_common(), and COMMON_COMPONENT::use_obsolete_callback_print().
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_args(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_args().
{
  if (has_common()) {
    return common()->use_obsolete_callback_print();
  }else{
    return false;
  }
}
const PARAMETER<double>& COMPONENT::value () const [inline]
Definition at line 274 of file e_compon.h.
Referenced by ELEMENT::ac_probe_ext(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_ac(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_tr(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::do_tr_last(), CARDSTASH::operator=(), param_is_printable(), param_value(), ELEMENT::precalc_last(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::precalc_last(), ELEMENT::tr_begin(), ELEMENT::tr_eval(), and ELEMENT::tr_probe_num().
{return _value;}
double COMPONENT::volts_limited (const node_t & n1, const node_t & n2) [static]
Definition at line 871 of file e_compon.cc.
References SIM_DATA::_fulldamp, SIM_DATA::_limiting, CKT_BASE::_sim, SIM_DATA::_vmax, SIM_DATA::_vmin, OPT::dampstrategy, dn_diff(), dsRANGE, error(), OPT::picky, untested, and node_t::v0().
Referenced by anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::do_tr(), CCSRC_BASE::tr_involts_limited(), and ELEMENT::tr_outvolts_limited().
{
  bool limiting = false;
  double v1 = n1.v0();
  assert(v1 == v1);
  if (v1 < _sim->_vmin) {
    limiting = true;
    v1 = _sim->_vmin;
  }else if (v1 > _sim->_vmax) {
    limiting = true;
    v1 = _sim->_vmax;
  }
  double v2 = n2.v0();
  assert(v2 == v2);
  if (v2 < _sim->_vmin) {
    limiting = true;
    v2 = _sim->_vmin;
  }else if (v2 > _sim->_vmax) {
    limiting = true;
    v2 = _sim->_vmax;
  }
  if (limiting) {
    _sim->_limiting = true;
    if (OPT::dampstrategy & dsRANGE) {
      _sim->_fulldamp = true;
      error(bTRACE, "range limit damp\n");
    }
    if (OPT::picky <= bTRACE) {untested();
      error(bNOERROR,"node limiting (n1,n2,dif) "
            "was (%g %g %g) now (%g %g %g)\n",
            n1.v0(), n2.v0(), n1.v0() - n2.v0(), v1, v2, v1-v2);
    }
  }
  return dn_diff(v1,v2);
}
Member Data Documentation
COMMON_COMPONENT* COMPONENT::_common [private]
Definition at line 151 of file e_compon.h.
Referenced by COMPONENT(), set_value(), tr_accept(), and tr_review().
bool COMPONENT::_converged [private]
Definition at line 157 of file e_compon.h.
PARAMETER<double> COMPONENT::_mfactor [protected]
Definition at line 154 of file e_compon.h.
Referenced by obsolete_move_parameters_from_common(), param_is_printable(), param_value(), precalc_first(), and set_param_by_index().
double COMPONENT::_mfactor_fixed [private]
Definition at line 156 of file e_compon.h.
Referenced by precalc_first().
int COMPONENT::_q_for_eval [private]
Definition at line 158 of file e_compon.h.
TIME_PAIR COMPONENT::_time_by
Definition at line 160 of file e_compon.h.
Referenced by ELEMENT::tr_probe_num(), tr_probe_num(), STORAGE::tr_review(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::tr_review(), anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE::tr_review(), anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP::tr_review(), ELEMENT::tr_review(), BASE_SUBCKT::tr_review(), anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM::tr_review(), anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::tr_review(), DEV_LOGIC::tr_review(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_review(), tr_review(), and DEV_SPICE::tr_review().
PARAMETER<double> COMPONENT::_value [protected]
Definition at line 153 of file e_compon.h.
Referenced by obsolete_move_parameters_from_common(), precalc_first(), and set_param_by_index().
The documentation for this class was generated from the following files:
savant/gnucap/src/e_compon.h
savant/gnucap/src/e_compon.cc