gnucap: SIM Class Reference
SIM Class Reference
#include <s__.h>
Public Member Functions
~SIM ()
Protected Types
enum TRACE {
tNONE = 0, tUNDER = 1, tALLTIME = 2, tREJECTED = 3,
tITERATION = 4, tVERBOSE = 5
}
Protected Member Functions
SIM ()
void command_base (CS &)
void reset_timers ()
const PROBELIST & alarmlist () const
const PROBELIST & plotlist () const
const PROBELIST & printlist () const
const PROBELIST & storelist () const
virtual void outdata (double)
virtual void head (double, double, const std::string &)
virtual void print_results (double)
virtual void alarm ()
virtual void store_results (double)
bool solve (OPT::ITL, TRACE)
bool solve_with_homotopy (OPT::ITL, TRACE)
void finish_building_evalq ()
void advance_time ()
void set_flags ()
void clear_arrays ()
void evaluate_models ()
void set_damp ()
void load_matrix ()
void solve_equations ()
Protected Attributes
CARD_LIST * _scope
OMSTREAM _out
Private Member Functions
const std::string long_label () const
virtual void setup (CS &)=0
virtual void sweep ()=0
virtual void finish ()
virtual bool is_step_rejected () const
SIM (const SIM &)
Detailed Description
Definition at line 37 of file s__.h.
Member Enumeration Documentation
enum SIM::TRACE [protected]
Enumerator:
tNONE
tUNDER
tALLTIME
tREJECTED
tITERATION
tVERBOSE
Definition at line 40 of file s__.h.
             { // how much diagnostics to show
    tNONE      = 0,     /* no extended diagnostics                      */
    tUNDER     = 1,     /* show underlying analysis, important pts only */
    tALLTIME   = 2,     /* show every time step, including hidden       */
    tREJECTED  = 3,     /* show rejected time steps                     */
    tITERATION = 4,     /* show every iteration, including nonconverged */
    tVERBOSE   = 5      /* show extended diagnostics                    */
  };
Constructor & Destructor Documentation
SIM::SIM (const SIM &) [inline, explicit, private]
Definition at line 61 of file s__.h.
References incomplete, and unreachable.
:CMD(),_scope(NULL) {unreachable(); incomplete();}
SIM::SIM () [inline, explicit, protected]
Definition at line 63 of file s__.h.
: CMD(),_scope(NULL) {}
SIM::~SIM ()
Definition at line 66 of file s__init.cc.
References CKT_BASE::_sim, and SIM_DATA::uninit().
{
  _sim->uninit();
}
Member Function Documentation
void SIM::advance_time (void) [protected]
Definition at line 143 of file s__solve.cc.
References CKT_BASE::_sim, SIM_DATA::_time0, SIM_DATA::_total_nodes, SIM_DATA::_v0, SIM_DATA::_vt1, CARD_LIST::card_list, notstd::copy_n(), CARD_LIST::dc_advance(), CKT_BASE::status(), CARD_LIST::tr_advance(), and CARD_LIST::tr_regress().
Referenced by solve(), and TRANSIENT::sweep().
{
  ::status.advance.start();
  static double last_iter_time;
  if (_sim->_time0 > 0) {
    if (_sim->_time0 > last_iter_time) {        /* moving forward */
      notstd::copy_n(_sim->_v0, _sim->_total_nodes+1, _sim->_vt1);
      CARD_LIST::card_list.tr_advance();
    }else{                              /* moving backward */
      /* don't save voltages.  They're wrong! */
      /* instead, restore a clean start for iteration */
      notstd::copy_n(_sim->_vt1, _sim->_total_nodes+1, _sim->_v0);
      CARD_LIST::card_list.tr_regress();
    }
  }else{
    CARD_LIST::card_list.dc_advance();
  }
  last_iter_time = _sim->_time0;
  ::status.advance.stop();
}
void SIM::alarm (void) [protected, virtual]
Definition at line 115 of file s__out.cc.
References _out, alarmlist(), PROBELIST::end(), OPT::numdgt, anonymous_namespace{c_genrat.cc}::p, and OMSTREAM::setfloatwidth().
Referenced by outdata().
{
  _out.setfloatwidth(OPT::numdgt, OPT::numdgt+6);
  for (PROBELIST::const_iterator
         p=alarmlist().begin();  p!=alarmlist().end();  ++p) {
    if (!p->in_range()) {
      _out << p->label() << '=' << p->value() << '\n';
    }else{
    }
  }
}
const PROBELIST & SIM::alarmlist () const [protected]
Definition at line 34 of file s__out.cc.
References SIM_DATA::_mode, CKT_BASE::_sim, and PROBE_LISTS::alarm.
Referenced by alarm().
{
  return PROBE_LISTS::alarm[_sim->_mode];
}
void SIM::clear_arrays (void) [protected]
Definition at line 192 of file s__solve.cc.
References SIM_DATA::_aa, SIM_DATA::_i, SIM_DATA::_loadq, CKT_BASE::_sim, BSMATRIX< T >::dezero(), OPT::gmin, SIM_DATA::is_inc_mode(), BSMATRIX< T >::size(), and BSMATRIX< T >::zero().
Referenced by solve().
{
  if (!_sim->is_inc_mode()) {                   /* Clear working array */
    _sim->_aa.zero();
    _sim->_aa.dezero(OPT::gmin);                /* gmin fudge */
    std::fill_n(_sim->_i, _sim->_aa.size()+1, 0);
  }
  _sim->_loadq.clear();
}
void SIM::command_base (CS & cmd) [protected]
Definition at line 29 of file s__init.cc.
References SIM_DATA::_aa, SIM_DATA::_lu, SIM_DATA::_mode, SIM_DATA::_nstat, CKT_BASE::_sim, SIM_DATA::alloc_vectors(), SIM_DATA::count_iterations(), BSMATRIX< T >::dezero(), error(), finish(), OPT::gmin, SIM_DATA::init(), iPRINTSTEP, itested, iTOTAL, OPT::pivtol, rBATCH, BSMATRIX< T >::reallocate(), SIM_DATA::reset_iteration_counter(), reset_timers(), rINTERACTIVE, rPRE_MAIN, rPRESET, rSCRIPT, ENV::run_mode, BSMATRIX< T >::set_min_pivot(), setup(), CKT_BASE::status(), sweep(), SIM_DATA::unalloc_vectors(), BSMATRIX< T >::unallocate(), unreachable, and untested.
Referenced by TRANSIENT::do_it().
{  reset_timers();
  _sim->reset_iteration_counter(_sim->_mode);
  _sim->reset_iteration_counter(iPRINTSTEP);
  _sim->init();
  _sim->alloc_vectors();
  _sim->_aa.reallocate();
  _sim->_aa.dezero(OPT::gmin);
  _sim->_aa.set_min_pivot(OPT::pivtol);
  _sim->_lu.reallocate();
  _sim->_lu.dezero(OPT::gmin);
  _sim->_lu.set_min_pivot(OPT::pivtol);
  assert(_sim->_nstat);
  try {
    setup(cmd);
    ::status.set_up.stop();
    switch (ENV::run_mode) {
    case rPRE_MAIN:     unreachable();  break;
    case rBATCH:        itested();
    case rINTERACTIVE:  itested();
    case rSCRIPT:       sweep();        break;
    case rPRESET:       /*nothing*/     break;
    }
   }catch (Exception& e) {untested();
    error(bDANGER, e.message() + '\n');
    _sim->count_iterations(iTOTAL);
    _sim->_lu.unallocate();
    _sim->_aa.unallocate();
  }
  _sim->unalloc_vectors();
  finish();
  ::status.total.stop();
}
void SIM::evaluate_models () [protected]
Definition at line 202 of file s__solve.cc.
References SIM_DATA::_evalq, SIM_DATA::_evalq_uc, SIM_DATA::_late_evalq, CKT_BASE::_sim, OPT::bypass, CARD_LIST::card_list, converged, CARD_LIST::do_tr(), and CKT_BASE::status().
Referenced by solve().
{
  ::status.evaluate.start();
  if (OPT::bypass) {
    converged = true;
    swap(_sim->_evalq, _sim->_evalq_uc);
    while (!_sim->_evalq->empty()) {
      converged &= _sim->_evalq->front()->do_tr();
      _sim->_evalq->pop_front();
    }
  }else{
    _sim->_evalq_uc->clear();
    converged = CARD_LIST::card_list.do_tr();
  }
  while (!_sim->_late_evalq.empty()) { //BUG// encapsulation violation
    converged &= _sim->_late_evalq.front()->do_tr_last();
    _sim->_late_evalq.pop_front();
  }
  ::status.evaluate.stop();
}
virtual void SIM::finish (void) [inline, private, virtual]
Reimplemented in anonymous_namespace{s_dc.cc}::DCOP.
Definition at line 58 of file s__.h.
Referenced by command_base().
{}
void SIM::finish_building_evalq (void) [protected]
Definition at line 136 of file s__solve.cc.
References CARD_LIST::card_list, CKT_BASE::status(), and CARD_LIST::tr_queue_eval().
Referenced by solve().
{
  ::status.queue.start();
  CARD_LIST::card_list.tr_queue_eval();
  ::status.queue.stop();
}
void SIM::head (double start, double stop, const std::string & col1) [protected, virtual]
Definition at line 67 of file s__out.cc.
References _out, CKT_BASE::_sim, SIM_DATA::_waves, PROBELIST::begin(), BIGBUFLEN, PROBELIST::end(), OMSTREAM::form(), min(), OPT::numdgt, anonymous_namespace{c_genrat.cc}::p, plopen(), plotlist(), printlist(), PROBELIST::size(), storelist(), and width.
Referenced by anonymous_namespace{s_dc.cc}::DCOP::sweep(), and TRANSIENT::sweep().
{
  if (_sim->_waves) {
    delete [] _sim->_waves;
  }else{
  }
  _sim->_waves = new WAVE [storelist().size()];
  if (!plopen(start, stop, plotlist())) {
    // ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    int width = std::min(OPT::numdgt+5, BIGBUFLEN-10);
    char format[20];
    //sprintf(format, "%%c%%-%u.%us", width, width);
    sprintf(format, "%%c%%-%us", width);
    _out.form(format, '#', col1.c_str());
    for (PROBELIST::const_iterator
           p=printlist().begin();  p!=printlist().end();  ++p) {
      _out.form(format, ' ', p->label().c_str());
    }
    _out << '\n';
  }else{
  }
}
virtual bool SIM::is_step_rejected () const [inline, private, virtual]
Reimplemented in TRANSIENT.
Definition at line 59 of file s__.h.
Referenced by set_flags().
{return false;}
void SIM::load_matrix () [protected]
Definition at line 237 of file s__solve.cc.
References SIM_DATA::_loadq, CKT_BASE::_sim, CARD_LIST::card_list, SIM_DATA::is_inc_mode(), CKT_BASE::status(), CARD_LIST::tr_load(), and OPT::traceload.
Referenced by solve().
{
  ::status.load.start();
  if (OPT::traceload && _sim->is_inc_mode()) {
    while (!_sim->_loadq.empty()) {
      _sim->_loadq.back()->tr_load();
      _sim->_loadq.pop_back();
    }
  }else{
    _sim->_loadq.clear();
    CARD_LIST::card_list.tr_load();
  }
  ::status.load.stop();
}
const std::string SIM::long_label () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 54 of file s__.h.
References unreachable.
{unreachable(); return "";}
void SIM::outdata (double x) [protected, virtual]
Definition at line 53 of file s__out.cc.
References CKT_BASE::_sim, alarm(), iPRINTSTEP, plotlist(), plottr(), print_results(), SIM_DATA::reset_iteration_counter(), CKT_BASE::status(), and store_results().
Referenced by TRANSIENT::sweep(), and anonymous_namespace{s_dc.cc}::DCOP::sweep_recursive().
{
  ::status.output.start();
  plottr(x, plotlist());
  print_results(x);
  alarm();
  store_results(x);
  _sim->reset_iteration_counter(iPRINTSTEP);
  ::status.hidden_steps = 0;
  ::status.output.stop();
}
const PROBELIST & SIM::plotlist () const [protected]
Definition at line 38 of file s__out.cc.
References SIM_DATA::_mode, CKT_BASE::_sim, and PROBE_LISTS::plot.
Referenced by head(), TRANSIENT::options(), outdata(), anonymous_namespace{s_dc.cc}::DC::setup(), and anonymous_namespace{s_dc.cc}::OP::setup().
{
  return PROBE_LISTS::plot[_sim->_mode];
}
void SIM::print_results (double x) [protected, virtual]
Definition at line 98 of file s__out.cc.
References _out, PROBELIST::end(), NOT_VALID, OPT::numdgt, anonymous_namespace{c_genrat.cc}::p, IO::plotout, printlist(), and OMSTREAM::setfloatwidth().
Referenced by outdata(), and solve().
{
  if (!IO::plotout.any()) {
    _out.setfloatwidth(OPT::numdgt, OPT::numdgt+6);
    assert(x != NOT_VALID);
    _out << x;
    for (PROBELIST::const_iterator
           p=printlist().begin();  p!=printlist().end();  ++p) {
      _out << p->value();
    }
    _out << '\n';
  }else{
  }
}
const PROBELIST & SIM::printlist () const [protected]
Definition at line 42 of file s__out.cc.
References SIM_DATA::_mode, CKT_BASE::_sim, and PROBE_LISTS::print.
Referenced by head(), and print_results().
{
  return PROBE_LISTS::print[_sim->_mode];
}
void SIM::reset_timers () [protected]
Definition at line 71 of file s__init.cc.
References CKT_BASE::status().
Referenced by command_base().
{
  ::status.advance.reset();
  ::status.queue.reset();
  ::status.evaluate.reset();
  ::status.load.reset();
  ::status.lud.reset();
  ::status.back.reset();
  ::status.review.reset();
  ::status.accept.reset();
  ::status.output.reset();
  ::status.aux1.reset();
  ::status.aux2.reset();
  ::status.aux3.reset();
  ::status.set_up.reset().start();
  ::status.total.reset().start();
}
void SIM::set_damp () [protected]
Definition at line 223 of file s__solve.cc.
References SIM_DATA::_damp, SIM_DATA::_fulldamp, CKT_BASE::_sim, converged, OPT::dampmax, OPT::dampmin, OPT::dampstrategy, dsINIT, SIM_DATA::is_first_iteration(), SIM_DATA::is_second_iteration(), and trace1.
Referenced by solve().
{
  if (_sim->is_second_iteration() && !converged && OPT::dampstrategy&dsINIT) {
    _sim->_damp = OPT::dampmin;
  }else if (_sim->is_first_iteration()  ||  converged) {
    _sim->_damp = OPT::dampmax;
  }else if (_sim->_fulldamp) {
    _sim->_damp = OPT::dampmin;
  }else{
    _sim->_damp = OPT::dampmax;
  }
  trace1("", _sim->_damp);
}
void SIM::set_flags () [protected]
Definition at line 170 of file s__solve.cc.
References SIM_DATA::_bypass_ok, SIM_DATA::_damp, SIM_DATA::_fulldamp, SIM_DATA::_limiting, CKT_BASE::_sim, OPT::bypass, OPT::dampmax, SIM_DATA::inc_mode_is_bad(), OPT::incmode, SIM_DATA::is_iteration_number(), is_step_rejected(), OPT::itl, SIM_DATA::set_inc_mode_no(), SIM_DATA::set_inc_mode_yes(), and OPT::TRLOW.
Referenced by solve().
{
  _sim->_limiting = false;
  _sim->_fulldamp = false;
  if (OPT::incmode == false) {
    _sim->set_inc_mode_no();
  }else if (_sim->inc_mode_is_bad()) {
    _sim->set_inc_mode_no();
  }else if (_sim->is_iteration_number(OPT::itl[OPT::TRLOW])) {
    _sim->set_inc_mode_no();
  }else if (_sim->is_iteration_number(0)) {
    // leave it as is
  }else{
    _sim->set_inc_mode_yes();
  }
  _sim->_bypass_ok =
    (is_step_rejected()  ||  _sim->_damp < OPT::dampmax*OPT::dampmax)
    ? false : bool(OPT::bypass);
}
virtual void SIM::setup (CS &) [private, pure virtual]
Implemented in anonymous_namespace{s_dc.cc}::OP, anonymous_namespace{s_dc.cc}::DC, TRANSIENT, anonymous_namespace{s_ac.cc}::AC, and anonymous_namespace{s_fo.cc}::FOURIER.
Referenced by command_base().
bool SIM::solve (OPT::ITL itl, TRACE trace) [protected]
Definition at line 42 of file s__solve.cc.
References SIM_DATA::_damp, SIM_DATA::_limiting, SIM_DATA::_mode, CKT_BASE::_sim, advance_time(), clear_arrays(), converged, SIM_DATA::count_iterations(), OPT::dampmax, error(), evaluate_models(), SIM_DATA::exceeds_iteration_limit(), OPT::fbbypass, finish_building_evalq(), iPRINTSTEP, iSTEP, SIM_DATA::iteration_number(), OPT::itermin, iTOTAL, load_matrix(), print_results(), SIM_DATA::reset_iteration_counter(), set_damp(), set_flags(), SIM_DATA::set_limit(), solve_equations(), and tITERATION.
Referenced by solve_with_homotopy(), and TRANSIENT::sweep().
{
  converged = false;
  int convergedcount = 0;
  _sim->reset_iteration_counter(iSTEP);
  advance_time();
  _sim->_damp = OPT::dampmax;
  do{
    if (trace >= tITERATION) {
      print_results(static_cast<double>(-_sim->iteration_number()));
    }
    set_flags();
    clear_arrays();
    finish_building_evalq();
    _sim->count_iterations(iPRINTSTEP);
    _sim->count_iterations(iSTEP);
    _sim->count_iterations(_sim->_mode);
    _sim->count_iterations(iTOTAL);
    evaluate_models();
    if (converged) {
      if (_sim->_limiting) {
        error(bDEBUG, "converged beyond limit, resetting limit\n");
        _sim->set_limit();
        convergedcount = 0;
      }else{
        ++convergedcount;
      }
    }else{
      convergedcount = 0;
    }
    if (convergedcount <= OPT::itermin) {
      converged = false;
    }
    if (!converged || !OPT::fbbypass || _sim->_damp < .99) {
      set_damp();
      load_matrix();
      solve_equations();
    }
  }while (!converged && !_sim->exceeds_iteration_limit(itl));
  return converged;
}
void SIM::solve_equations () [protected]
Definition at line 252 of file s__solve.cc.
References SIM_DATA::_aa, SIM_DATA::_i, SIM_DATA::_lu, SIM_DATA::_nstat, CKT_BASE::_sim, SIM_DATA::_v0, BSMATRIX< T >::fbsub(), SIM_DATA::is_inc_mode(), BSMATRIX< T >::lu_decomp(), OPT::lubypass, LOGIC_NODE::set_a_iter(), BSMATRIX< T >::size(), CKT_BASE::status(), and untested.
Referenced by solve().
{
  ::status.lud.start();
  _sim->_lu.lu_decomp(_sim->_aa, bool(OPT::lubypass && _sim->is_inc_mode()));
  ::status.lud.stop();
  ::status.back.start();
  _sim->_lu.fbsub(_sim->_v0, _sim->_i, _sim->_v0);
  ::status.back.stop();
  if (_sim->_nstat) {
    // mixed mode
    for (int ii = _sim->_lu.size(); ii >= 1; --ii) {
      _sim->_nstat[ii].set_a_iter();
    }
  }else{
    // pure analog
    untested();
  }
}
bool SIM::solve_with_homotopy (OPT::ITL itl, TRACE trace) [protected]
Definition at line 92 of file s__solve.cc.
References SIM_DATA::_iter, CKT_BASE::_sim, converged, OPT::gmin, iPRINTSTEP, iSTEP, OPT::itermin, OPT::itl, SIM_DATA::set_inc_mode_no(), solve(), OPT::SSTEP, CKT_BASE::status(), and trace2.
Referenced by TRANSIENT::sweep(), and anonymous_namespace{s_dc.cc}::DCOP::sweep_recursive().
{
  solve(itl, trace);
  trace2("plain", ::status.iter[iSTEP], OPT::gmin);
  if (!converged && OPT::itl[OPT::SSTEP] > 0) {
    int save_itermin = OPT::itermin;
    OPT::itermin = 0;
    double save_gmin = OPT::gmin;
    OPT::gmin = 1;
    while (_sim->_iter[iPRINTSTEP] < OPT::itl[OPT::SSTEP] && OPT::gmin > save_gmin) {
      //CARD_LIST::card_list.precalc();
      _sim->set_inc_mode_no();
      solve(itl, trace);
      if (!converged) {
        trace2("fail", _sim->_iter[iSTEP], OPT::gmin);
        OPT::gmin *= 3.5;
      }else{
        trace2("success", _sim->_iter[iSTEP], OPT::gmin);
        OPT::gmin /= 4;
      }
    }
    OPT::itermin = save_itermin;
    OPT::gmin = save_gmin;
    //CARD_LIST::card_list.precalc();
    solve(itl, trace);
    if (!converged) {
      trace2("final fail", _sim->_iter[iSTEP], OPT::gmin);
    }else{
      trace2("final success", _sim->_iter[iSTEP], OPT::gmin);
    }
  }else{
  }
  return converged;
}
void SIM::store_results (double x) [protected, virtual]
Reimplemented in anonymous_namespace{s_fo.cc}::FOURIER.
Definition at line 129 of file s__out.cc.
References CKT_BASE::_sim, SIM_DATA::_waves, PROBELIST::end(), anonymous_namespace{c_genrat.cc}::p, WAVE::push(), and storelist().
Referenced by outdata(), and anonymous_namespace{s_fo.cc}::FOURIER::store_results().
{
  int ii = 0;
  for (PROBELIST::const_iterator
         p=storelist().begin();  p!=storelist().end();  ++p) {
    _sim->_waves[ii++].push(x, p->value());
  }
}
const PROBELIST & SIM::storelist () const [protected]
Definition at line 46 of file s__out.cc.
References SIM_DATA::_mode, CKT_BASE::_sim, and PROBE_LISTS::store.
Referenced by head(), and store_results().
{
  return PROBE_LISTS::store[_sim->_mode];
}
virtual void SIM::sweep () [private, pure virtual]
Implemented in TRANSIENT, anonymous_namespace{s_ac.cc}::AC, and anonymous_namespace{s_dc.cc}::DCOP.
Referenced by command_base().
Member Data Documentation
OMSTREAM SIM::_out [protected]
Definition at line 50 of file s__.h.
Referenced by alarm(), anonymous_namespace{s_dc.cc}::DCOP::DCOP(), head(), anonymous_namespace{s_dc.cc}::DCOP::options(), TRANSIENT::options(), print_results(), anonymous_namespace{s_dc.cc}::DC::setup(), and anonymous_namespace{s_dc.cc}::OP::setup().
CARD_LIST* SIM::_scope [protected]
Definition at line 49 of file s__.h.
Referenced by TRANSIENT::do_it(), anonymous_namespace{s_dc.cc}::DCOP::fix_args(), TRANSIENT::options(), TRANSIENT::setup(), anonymous_namespace{s_dc.cc}::DC::setup(), and anonymous_namespace{s_dc.cc}::OP::setup().
The documentation for this class was generated from the following files:
savant/gnucap/src/s__.h
savant/gnucap/src/s__init.cc
savant/gnucap/src/s__out.cc
savant/gnucap/src/s__solve.cc