gnucap: anonymous_namespace{d_cap.cc}::DEV_VCCAP Class Reference
anonymous_namespace{d_cap.cc}::DEV_VCCAP Class Reference
Public Member Functions
DEV_VCCAP ()
Private Member Functions
DEV_VCCAP (const DEV_VCCAP &p)
char id_letter () const
std::string value_name () const
std::string dev_type () const
int max_nodes () const
int min_nodes () const
int matrix_nodes () const
int net_nodes () const
bool has_iv_probe () const
bool f_is_value () const
CARD * clone () const
void tr_iwant_matrix ()
bool do_tr ()
double tr_involts () const
double tr_involts_limited () const
void ac_iwant_matrix ()
std::string port_name (int i) const
Detailed Description
Definition at line 106 of file d_cap.cc.
Constructor & Destructor Documentation
anonymous_namespace{d_cap.cc}::DEV_VCCAP::DEV_VCCAP (const DEV_VCCAP & p) [inline, explicit, private]
Definition at line 108 of file d_cap.cc.
:DEV_CAPACITANCE(p) {}
anonymous_namespace{d_cap.cc}::DEV_VCCAP::DEV_VCCAP () [inline, explicit]
Definition at line 110 of file d_cap.cc.
:DEV_CAPACITANCE() {}
Member Function Documentation
void anonymous_namespace{d_cap.cc}::DEV_VCCAP::ac_iwant_matrix () [inline, private, virtual]
Reimplemented from anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE.
Definition at line 126 of file d_cap.cc.
{ac_iwant_matrix_extended();}
CARD* anonymous_namespace{d_cap.cc}::DEV_VCCAP::clone () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE.
Definition at line 121 of file d_cap.cc.
{return new DEV_VCCAP(*this);}
std::string anonymous_namespace{d_cap.cc}::DEV_VCCAP::dev_type () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE.
Definition at line 114 of file d_cap.cc.
{return "vccap";}
bool anonymous_namespace{d_cap.cc}::DEV_VCCAP::do_tr () [private, virtual]
Reimplemented from anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE.
Definition at line 188 of file d_cap.cc.
References converged, and differentiate().
{
  _y[0].x = tr_input_limited();
  tr_eval();
  store_values();
  q_load();
  _y[0].x = tr_outvolts();
  _y[0].f1 = _y[0].f0;           // self capacitance
  _y[0].f0 = _y[0].x * _y[0].f1; // charge
  _i[0] = differentiate(_y, _i, _time, _method_a);
  _m0.x  = _i[0].x;
  _m0.c1 = _i[0].f1;
  _m0.c0 = _i[0].f0 - _i[0].x * _i[0].f1;
  return converged();
}
bool anonymous_namespace{d_cap.cc}::DEV_VCCAP::f_is_value () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 120 of file d_cap.cc.
References untested.
{untested();return true;}
bool anonymous_namespace{d_cap.cc}::DEV_VCCAP::has_iv_probe () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE.
Definition at line 119 of file d_cap.cc.
References untested.
{untested(); return false;}
char anonymous_namespace{d_cap.cc}::DEV_VCCAP::id_letter () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE.
Definition at line 112 of file d_cap.cc.
References untested.
{untested();return '\0';}
int anonymous_namespace{d_cap.cc}::DEV_VCCAP::matrix_nodes () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE.
Definition at line 117 of file d_cap.cc.
{return 4;}
int anonymous_namespace{d_cap.cc}::DEV_VCCAP::max_nodes () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE.
Definition at line 115 of file d_cap.cc.
{return 4;}
int anonymous_namespace{d_cap.cc}::DEV_VCCAP::min_nodes () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE.
Definition at line 116 of file d_cap.cc.
{return 4;}
int anonymous_namespace{d_cap.cc}::DEV_VCCAP::net_nodes () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE.
Definition at line 118 of file d_cap.cc.
{return 4;}
std::string anonymous_namespace{d_cap.cc}::DEV_VCCAP::port_name (int i) const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE.
Definition at line 128 of file d_cap.cc.
References untested.
                                  {untested();
    assert(i >= 0);
    assert(i < 4);
    static std::string names[] = {"p", "n", "ps", "ns"};
    return names[i];
  }
double anonymous_namespace{d_cap.cc}::DEV_VCCAP::tr_involts () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE.
Definition at line 124 of file d_cap.cc.
References dn_diff(), IN1, and IN2.
{return dn_diff(_n[IN1].v0(),_n[IN2].v0());}
double anonymous_namespace{d_cap.cc}::DEV_VCCAP::tr_involts_limited () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE.
Definition at line 125 of file d_cap.cc.
References IN1, IN2, and volts_limited().
{return volts_limited(_n[IN1],_n[IN2]);}
void anonymous_namespace{d_cap.cc}::DEV_VCCAP::tr_iwant_matrix () [inline, private, virtual]
Reimplemented from anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE.
Definition at line 122 of file d_cap.cc.
{tr_iwant_matrix_extended();}
std::string anonymous_namespace{d_cap.cc}::DEV_VCCAP::value_name () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE.
Definition at line 113 of file d_cap.cc.
References untested.
{untested(); return "c";}
The documentation for this class was generated from the following file:
savant/gnucap/src/d_cap.cc