gnucap: anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE Class Reference
anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE Class Reference
Public Member Functions
DEV_CAPACITANCE ()
Protected Member Functions
DEV_CAPACITANCE (const DEV_CAPACITANCE &p)
char id_letter () const
std::string value_name () const
std::string dev_type () const
int max_nodes () const
int min_nodes () const
int matrix_nodes () const
int net_nodes () const
bool has_iv_probe () const
bool use_obsolete_callback_parse () const
CARD * clone () const
void tr_iwant_matrix ()
bool do_tr ()
void tr_load ()
void tr_unload ()
double tr_involts () const
double tr_involts_limited () const
double tr_probe_num (const std::string &) const
void ac_iwant_matrix ()
void ac_begin ()
void do_ac ()
void ac_load ()
COMPLEX ac_involts () const
std::string port_name (int i) const
Detailed Description
Definition at line 37 of file d_cap.cc.
Constructor & Destructor Documentation
anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::DEV_CAPACITANCE (const DEV_CAPACITANCE & p) [inline, explicit, protected]
Definition at line 39 of file d_cap.cc.
:STORAGE(p) {}
anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::DEV_CAPACITANCE () [inline, explicit]
Definition at line 41 of file d_cap.cc.
:STORAGE() {}
Member Function Documentation
void anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::ac_begin () [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 61 of file d_cap.cc.
{_ev = _y[0].f1;}
COMPLEX anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::ac_involts () const [inline, protected, virtual]
Implements ELEMENT.
Definition at line 64 of file d_cap.cc.
References itested.
{itested();return ac_outvolts();}
void anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::ac_iwant_matrix () [inline, protected, virtual]
Implements ELEMENT.
Reimplemented in anonymous_namespace{d_cap.cc}::DEV_VCCAP, and anonymous_namespace{d_cap.cc}::DEV_TRANSCAP.
Definition at line 60 of file d_cap.cc.
{ac_iwant_matrix_passive();}
void anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::ac_load () [inline, protected, virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_cap.cc}::DEV_TRANSCAP.
Definition at line 63 of file d_cap.cc.
{ac_load_passive();}
CARD* anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::clone () const [inline, protected, virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_cap.cc}::DEV_VCCAP, and anonymous_namespace{d_cap.cc}::DEV_TRANSCAP.
Definition at line 52 of file d_cap.cc.
{return new DEV_CAPACITANCE(*this);}
std::string anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::dev_type () const [inline, protected, virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_cap.cc}::DEV_VCCAP, and anonymous_namespace{d_cap.cc}::DEV_TRANSCAP.
Definition at line 45 of file d_cap.cc.
{return "capacitor";}
void anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::do_ac () [protected, virtual]
Reimplemented from CARD.
Definition at line 158 of file d_cap.cc.
{
  if (using_ac_eval()) {
    ac_eval();
  }else{
    assert(_ev == _y[0].f1);
    assert(has_tr_eval() || _ev == double(value()));
  }
  _acg = _ev * _sim->_jomega;
}
bool anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::do_tr () [protected, virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_cap.cc}::DEV_VCCAP.
Definition at line 137 of file d_cap.cc.
References converged, differentiate(), and trace3.
{
  if (using_tr_eval()) {
    _y[0].x = tr_input_limited();
    tr_eval();
  }else{
    _y[0].x = tr_input(); // tr_involts();
    assert(_y[0].f1 == value());
    _y[0].f0 = _y[0].x * _y[0].f1;
    assert(converged());
  }
  store_values();
  q_load();
  trace3("q", _y[0].x, _y[0].f0, _y[0].f1);
  _i[0] = differentiate(_y, _i, _time, _method_a);
  trace3("i", _i[0].x, _i[0].f0, _i[0].f1);
  _m0 = CPOLY1(_i[0]);
  return converged();
}
bool anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::has_iv_probe () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Reimplemented in anonymous_namespace{d_cap.cc}::DEV_VCCAP, and anonymous_namespace{d_cap.cc}::DEV_TRANSCAP.
Definition at line 50 of file d_cap.cc.
{return true;}
char anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::id_letter () const [inline, protected, virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_cap.cc}::DEV_VCCAP, and anonymous_namespace{d_cap.cc}::DEV_TRANSCAP.
Definition at line 43 of file d_cap.cc.
{return 'C';}
int anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::matrix_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Reimplemented in anonymous_namespace{d_cap.cc}::DEV_VCCAP, and anonymous_namespace{d_cap.cc}::DEV_TRANSCAP.
Definition at line 48 of file d_cap.cc.
{return 2;}
int anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::max_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Reimplemented in anonymous_namespace{d_cap.cc}::DEV_VCCAP, and anonymous_namespace{d_cap.cc}::DEV_TRANSCAP.
Definition at line 46 of file d_cap.cc.
{return 2;}
int anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::min_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Reimplemented in anonymous_namespace{d_cap.cc}::DEV_VCCAP, and anonymous_namespace{d_cap.cc}::DEV_TRANSCAP.
Definition at line 47 of file d_cap.cc.
{return 2;}
int anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::net_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Reimplemented in anonymous_namespace{d_cap.cc}::DEV_VCCAP, and anonymous_namespace{d_cap.cc}::DEV_TRANSCAP.
Definition at line 49 of file d_cap.cc.
{return 2;}
std::string anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::port_name (int i) const [inline, protected, virtual]
Implements COMPONENT.
Reimplemented in anonymous_namespace{d_cap.cc}::DEV_VCCAP, and anonymous_namespace{d_cap.cc}::DEV_TRANSCAP.
Definition at line 66 of file d_cap.cc.
{
    assert(i >= 0);
    assert(i < 2);
    static std::string names[] = {"p", "n"};
    return names[i];
  }
double anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::tr_involts () const [inline, protected, virtual]
Implements ELEMENT.
Reimplemented in anonymous_namespace{d_cap.cc}::DEV_VCCAP, and anonymous_namespace{d_cap.cc}::DEV_TRANSCAP.
Definition at line 57 of file d_cap.cc.
{return tr_outvolts();}
double anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::tr_involts_limited () const [inline, protected, virtual]
Implements ELEMENT.
Reimplemented in anonymous_namespace{d_cap.cc}::DEV_VCCAP, and anonymous_namespace{d_cap.cc}::DEV_TRANSCAP.
Definition at line 58 of file d_cap.cc.
{return tr_outvolts_limited();}
void anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::tr_iwant_matrix () [inline, protected, virtual]
Implements ELEMENT.
Reimplemented in anonymous_namespace{d_cap.cc}::DEV_VCCAP, and anonymous_namespace{d_cap.cc}::DEV_TRANSCAP.
Definition at line 53 of file d_cap.cc.
{tr_iwant_matrix_passive();}
void anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::tr_load () [inline, protected, virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_cap.cc}::DEV_TRANSCAP.
Definition at line 55 of file d_cap.cc.
{tr_load_passive();}
double anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::tr_probe_num (const std::string & x) const [protected, virtual]
Reimplemented from STORAGE.
Definition at line 169 of file d_cap.cc.
References STORAGE::tr_probe_num(), Umatch(), and untested.
{
  if (Umatch(x, "q{cap} |ch{arge} ")) {
    return _y[0].f0;
  }else if (Umatch(x, "c{apacitance} ")) {
    return _y[0].f1;
  }else if (Umatch(x, "dcdt ")) {untested();
    return (_y[0].f1 - _y[1].f1) / _dt;
  }else if (Umatch(x, "dc ")) {untested();
    return (_y[0].f1 - _y[1].f1);
  }else if (Umatch(x, "dqdt ")) {
    return (_y[0].f0 - _y[1].f0) / _dt;
  }else if (Umatch(x, "dq ")) {
    return (_y[0].f0 - _y[1].f0);
  }else{
    return STORAGE::tr_probe_num(x);
  }
}
void anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::tr_unload () [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 56 of file d_cap.cc.
{tr_unload_passive();}
bool anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::use_obsolete_callback_parse () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 51 of file d_cap.cc.
{return true;}
std::string anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::value_name () const [inline, protected, virtual]
Implements CARD.
Reimplemented in anonymous_namespace{d_cap.cc}::DEV_VCCAP, and anonymous_namespace{d_cap.cc}::DEV_TRANSCAP.
Definition at line 44 of file d_cap.cc.
{return "c";}
The documentation for this class was generated from the following file:
savant/gnucap/src/d_cap.cc