gnucap: SDP_BUILT_IN_MOS123 Class Reference
SDP_BUILT_IN_MOS123 Class Reference
#include <d_mos123.h>
Public Member Functions
SDP_BUILT_IN_MOS123 (const COMMON_COMPONENT *c)
void init (const COMMON_COMPONENT *)
Detailed Description
Definition at line 36 of file d_mos123.h.
Constructor & Destructor Documentation
SDP_BUILT_IN_MOS123::SDP_BUILT_IN_MOS123 (const COMMON_COMPONENT * c) [inline, explicit]
Definition at line 39 of file d_mos123.h.
References init().
: SDP_BUILT_IN_MOS_BASE(c) {init(c);}
Member Function Documentation
void SDP_BUILT_IN_MOS123::init (const COMMON_COMPONENT * cc) [virtual]
Reimplemented from SDP_BUILT_IN_MOS_BASE.
Reimplemented in SDP_BUILT_IN_MOS1, SDP_BUILT_IN_MOS2, SDP_BUILT_IN_MOS3, and SDP_BUILT_IN_MOS6.
Definition at line 35 of file d_mos123.cc.
References SDP_BUILT_IN_MOS_BASE::cgate, MODEL_BUILT_IN_MOS123::cox, SDP_BUILT_IN_MOS_BASE::l_eff, COMMON_COMPONENT::model(), SDP_BUILT_IN_MOS_BASE::phi, MODEL_BUILT_IN_MOS123::phi, prechecked_cast, CARD::scope(), and SDP_BUILT_IN_MOS_BASE::w_eff.
Referenced by SDP_BUILT_IN_MOS123().
{
  assert(cc);
  SDP_BUILT_IN_MOS_BASE::init(cc);
  const COMMON_BUILT_IN_MOS* c = prechecked_cast<const COMMON_BUILT_IN_MOS*>(cc);
  assert(c);
  const MODEL_BUILT_IN_MOS123* m = prechecked_cast<const MODEL_BUILT_IN_MOS123*>(c->model());
  assert(m);
  const CARD_LIST* par_scope = m->scope();
  assert(par_scope);
  // adjust: override
    this->cgate = m->cox * w_eff * l_eff;
    this->phi = m->phi;
  // adjust: raw
  // adjust: calculated
  // code_post
}
The documentation for this class was generated from the following files:
savant/gnucap/src/d_mos123.h
savant/gnucap/src/d_mos123.cc