gnucap: List_Base< T > Class Template Reference
List_Base< T > Class Template Reference
#include <m_base.h>
Public Types
typedef std::list< T * >
::const_iterator const_iterator
Public Member Functions
virtual void parse (CS &f)=0
bool is_empty () const
size_t size () const
const_iterator begin () const
const_iterator end () const
const T * front () const
const T * back () const
T * back ()
void push_back (T *x)
void pop_back ()
Protected Member Functions
virtual void dump (std::ostream &o) const
virtual ~List_Base ()
List_Base ()
List_Base (const List_Base &p)
Private Attributes
std::list< T * > _list
Detailed Description
template<class T>
class List_Base< T >
Definition at line 97 of file m_base.h.
Member Typedef Documentation
template<class T> typedef std::list<T*>::const_iterator List_Base< T >::const_iterator
Definition at line 110 of file m_base.h.
Constructor & Destructor Documentation
template<class T > List_Base< T >::~List_Base () [protected, virtual]
Definition at line 304 of file m_base.h.
{
  for (typename std::list<T*>::iterator
          i = _list.begin(); i != _list.end(); ++i) {
    assert(*i);
    delete *i;
  }
}
template<class T> List_Base< T >::List_Base () [inline, explicit, protected]
Definition at line 107 of file m_base.h.
{}
template<class T> List_Base< T >::List_Base (const List_Base< T > & p) [inline, explicit, protected]
Definition at line 108 of file m_base.h.
: Base(), _list(p._list) {untested();}
Member Function Documentation
template<class T> const T* List_Base< T >::back () const [inline]
Definition at line 116 of file m_base.h.
Referenced by Expression::as_bool(), Expression::eval(), Token_SYMBOL::stack_op(), Token_BINOP::stack_op(), Token_PARLIST::stack_op(), and Token_UNARY::stack_op().
{assert(!is_empty()); return _list.back();}
template<class T> T* List_Base< T >::back () [inline]
Definition at line 117 of file m_base.h.
{assert(!is_empty()); return _list.back();}
template<class T> const_iterator List_Base< T >::begin () const [inline]
Definition at line 113 of file m_base.h.
Referenced by Expression::reduce_copy().
{return _list.begin();}
template<class T > void List_Base< T >::dump (std::ostream & o) const [protected, virtual]
Implements Base.
Reimplemented in Expression.
Definition at line 314 of file m_base.h.
References untested.
{untested();
  for (const_iterator i = begin(); i != end(); ++i) {untested();
    assert(*i);
    Out << **i;
  }
}
template<class T> const_iterator List_Base< T >::end () const [inline]
Definition at line 114 of file m_base.h.
Referenced by Expression::reduce_copy().
{return _list.end();}
template<class T> const T* List_Base< T >::front () const [inline]
Definition at line 115 of file m_base.h.
{untested();assert(!is_empty()); return _list.front();}
template<class T> bool List_Base< T >::is_empty () const [inline]
Definition at line 111 of file m_base.h.
Referenced by Expression::as_bool(), List_Base< Token >::back(), List_Base< Token >::front(), List_Base< Token >::pop_back(), Expression::reduce_copy(), and Token_SYMBOL::stack_op().
{return _list.empty();}
template<class T> virtual void List_Base< T >::parse (CS & f) [pure virtual]
Implements Base.
Implemented in List< T >, and Expression.
Referenced by Expression::Expression().
template<class T> void List_Base< T >::pop_back () [inline]
Definition at line 119 of file m_base.h.
Referenced by Token_SYMBOL::stack_op(), Token_BINOP::stack_op(), Token_PARLIST::stack_op(), and Token_UNARY::stack_op().
{assert(!is_empty()); _list.pop_back();}
template<class T> void List_Base< T >::push_back (T * x) [inline]
Definition at line 118 of file m_base.h.
Referenced by Token_SYMBOL::stack_op(), Token_BINOP::stack_op(), Token_STOP::stack_op(), Token_PARLIST::stack_op(), and Token_UNARY::stack_op().
{assert(x);            _list.push_back(x);}
template<class T> size_t List_Base< T >::size () const [inline]
Definition at line 112 of file m_base.h.
Referenced by Expression::eval().
{return _list.size();}
Member Data Documentation
template<class T> std::list<T*> List_Base< T >::_list [private]
Definition at line 101 of file m_base.h.
Referenced by List_Base< Token >::back(), List_Base< Token >::begin(), List_Base< Token >::end(), List_Base< Token >::front(), List_Base< Token >::is_empty(), List_Base< Token >::pop_back(), List_Base< Token >::push_back(), and List_Base< Token >::size().
The documentation for this class was generated from the following file:
savant/gnucap/src/m_base.h