gnucap: CARD_LIST Class Reference
CARD_LIST Class Reference
#include <e_cardlist.h>
Classes
class fat_iterator
Public Types
typedef std::list< CARD * >
::iterator iterator
typedef std::list< CARD * >
::const_iterator const_iterator
Public Member Functions
bool is_empty () const
const CARD_LIST * parent () const
const LANGUAGE * language () const
iterator begin ()
iterator end ()
iterator find_again (const std::string &short_name, iterator)
iterator find_ (const std::string &short_name)
const_iterator begin () const
const_iterator end () const
const_iterator find_again (const std::string &short_name, const_iterator) const
const_iterator find_ (const std::string &short_name) const
CARD_LIST & push_front (CARD *c)
CARD_LIST & push_back (CARD *c)
CARD_LIST & insert (CARD_LIST::iterator i, CARD *c)
CARD_LIST & erase (iterator i)
CARD_LIST & erase (CARD *c)
CARD_LIST & erase_all ()
CARD_LIST & set_owner (CARD *owner)
CARD_LIST & set_slave ()
CARD_LIST & precalc_first ()
CARD_LIST & expand ()
CARD_LIST & precalc_last ()
CARD_LIST & map_nodes ()
CARD_LIST & tr_iwant_matrix ()
CARD_LIST & tr_begin ()
CARD_LIST & tr_restore ()
CARD_LIST & dc_advance ()
CARD_LIST & tr_advance ()
CARD_LIST & tr_regress ()
bool tr_needs_eval () const
CARD_LIST & tr_queue_eval ()
bool do_tr ()
CARD_LIST & tr_load ()
TIME_PAIR tr_review ()
CARD_LIST & tr_accept ()
CARD_LIST & tr_unload ()
CARD_LIST & ac_iwant_matrix ()
CARD_LIST & ac_begin ()
CARD_LIST & do_ac ()
CARD_LIST & ac_load ()
NODE_MAP * nodes () const
PARAM_LIST * params ()
PARAM_LIST * params () const
void attach_params (PARAM_LIST *p, const CARD_LIST *scope)
void shallow_copy (const CARD_LIST *)
void map_subckt_nodes (const CARD *model, const CARD *owner)
CARD_LIST ()
CARD_LIST (const CARD *model, CARD *owner, const CARD_LIST *scope, PARAM_LIST *p)
~CARD_LIST ()
Static Public Attributes
static CARD_LIST card_list
Private Member Functions
CARD_LIST (const CARD_LIST &)
Private Attributes
const CARD_LIST * _parent
NODE_MAP * _nm
PARAM_LIST * _params
LANGUAGE * _language
std::list< CARD * > _cl
Detailed Description
Definition at line 39 of file e_cardlist.h.
Member Typedef Documentation
typedef std::list<CARD*>::const_iterator CARD_LIST::const_iterator
Definition at line 49 of file e_cardlist.h.
typedef std::list<CARD*>::iterator CARD_LIST::iterator
Definition at line 48 of file e_cardlist.h.
Constructor & Destructor Documentation
CARD_LIST::CARD_LIST () [explicit]
Definition at line 33 of file e_cardlist.cc.
  :_parent(NULL),
   _nm(new NODE_MAP),
   _params(NULL),
   _language(NULL)
{
}
CARD_LIST::CARD_LIST (const CARD * model, CARD * owner, const CARD_LIST * scope, PARAM_LIST * p)
Definition at line 41 of file e_cardlist.cc.
References attach_params(), map_subckt_nodes(), set_owner(), shallow_copy(), and CARD::subckt().
  :_parent(NULL),
   _nm(new NODE_MAP),
   _params(NULL),
   _language(NULL)
{
  assert(model);
  assert(model->subckt());
  assert(owner);
  assert(!p || scope);
  attach_params(p, scope);
  shallow_copy(model->subckt());
  set_owner(owner);
  map_subckt_nodes(model, owner);
}
CARD_LIST::~CARD_LIST ()
Definition at line 59 of file e_cardlist.cc.
References _nm, _params, _parent, and erase_all().
{
  erase_all();
  delete _nm;
  if (!_parent) {
    delete _params;
  }else{
  }
}
CARD_LIST::CARD_LIST (const CARD_LIST &) [inline, explicit, private]
Definition at line 146 of file e_cardlist.h.
References incomplete, and unreachable.
{unreachable(); incomplete();}
Member Function Documentation
CARD_LIST & CARD_LIST::ac_begin ()
Definition at line 394 of file e_cardlist.cc.
References begin(), end(), and trace_func_comp.
Referenced by BASE_SUBCKT::ac_begin(), DEV_LOGIC::ac_begin(), and anonymous_namespace{s_ac.cc}::AC::sweep().
{
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).ac_begin();
  }
  return *this;
}
CARD_LIST & CARD_LIST::ac_iwant_matrix ()
Definition at line 383 of file e_cardlist.cc.
References begin(), end(), and trace_func_comp.
Referenced by DEV_LOGIC::ac_iwant_matrix(), COMPONENT::ac_iwant_matrix(), and SIM_DATA::init().
{
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).ac_iwant_matrix();
  }
  return *this;
}
CARD_LIST & CARD_LIST::ac_load ()
Definition at line 418 of file e_cardlist.cc.
References begin(), end(), and trace_func_comp.
Referenced by BASE_SUBCKT::ac_load(), DEV_LOGIC::ac_load(), and anonymous_namespace{s_ac.cc}::AC::solve().
{
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).ac_load();
  }
  return *this;
}
void CARD_LIST::attach_params (PARAM_LIST * p, const CARD_LIST * scope)
Definition at line 427 of file e_cardlist.cc.
References _params, and PARAM_LIST::eval_copy().
Referenced by CARD_LIST(), DEV_SUBCKT::precalc_first(), DEV_SUBCKT::precalc_last(), and CARD::renew_subckt().
{
  if (p) {
    assert(scope);
    if (_params) {
      delete _params;
      _params = NULL;
    }else{
    }
    _params = new PARAM_LIST;
    _params->eval_copy(*p, scope);
  }else{
  }
}
iterator CARD_LIST::begin () [inline]
Definition at line 83 of file e_cardlist.h.
Referenced by ac_begin(), ac_iwant_matrix(), ac_load(), PROBELIST::add_branches(), dc_advance(), anonymous_namespace{c_delete.cc}::CMD_DELETE::delete_one_name(), do_ac(), do_tr(), expand(), findbranch(), anonymous_namespace{c_list.cc}::list_save(), map_nodes(), map_subckt_nodes(), anonymous_namespace{c_modify.cc}::modify_fault(), precalc_first(), precalc_last(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_module(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_module(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_module(), set_owner(), set_slave(), shallow_copy(), tr_accept(), tr_advance(), tr_begin(), tr_iwant_matrix(), tr_load(), tr_needs_eval(), tr_queue_eval(), tr_regress(), tr_restore(), tr_review(), and tr_unload().
{return _cl.begin();}
const_iterator CARD_LIST::begin () const [inline]
Definition at line 90 of file e_cardlist.h.
{return _cl.begin();}
CARD_LIST & CARD_LIST::dc_advance ()
Definition at line 239 of file e_cardlist.cc.
References begin(), end(), and trace_func_comp.
Referenced by SIM::advance_time(), BASE_SUBCKT::dc_advance(), and DEV_LOGIC::dc_advance().
{
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).dc_advance();
  }
  return *this;
}
CARD_LIST & CARD_LIST::do_ac ()
Definition at line 403 of file e_cardlist.cc.
References begin(), end(), and trace_func_comp.
Referenced by BASE_SUBCKT::do_ac(), DEV_LOGIC::do_ac(), and anonymous_namespace{s_ac.cc}::AC::solve().
{
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    if (!(**ci).evaluated()) {
      (**ci).do_ac();
    }else{
    }
  }
  return *this;
}
bool CARD_LIST::do_tr ()
Definition at line 302 of file e_cardlist.cc.
References begin(), OPT::bypass, end(), and trace_func_comp.
Referenced by SIM::evaluate_models(), and TRANSIENT::sweep().
{
  bool isconverged = true;
  if (OPT::bypass) {
    for (iterator ci=begin(); ci!=end(); ++ci) {
      trace_func_comp();
      if ((**ci).tr_needs_eval()) {
        isconverged &= (**ci).do_tr();
      }else{
      }
    }
  }else{
    for (iterator ci=begin(); ci!=end(); ++ci) {
      trace_func_comp();
      isconverged &= (**ci).do_tr();
    }
  }
  return isconverged;
}
iterator CARD_LIST::end () [inline]
Definition at line 84 of file e_cardlist.h.
Referenced by ac_begin(), ac_iwant_matrix(), ac_load(), PROBELIST::add_branches(), dc_advance(), anonymous_namespace{c_delete.cc}::CMD_DELETE::delete_one_name(), do_ac(), do_tr(), erase(), expand(), find_again(), CARD::find_in_parent_scope(), anonymous_namespace{c_list.cc}::list_save(), map_nodes(), map_subckt_nodes(), precalc_first(), precalc_last(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_module(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_module(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_module(), set_owner(), set_slave(), shallow_copy(), tr_accept(), tr_advance(), tr_begin(), tr_iwant_matrix(), tr_load(), tr_needs_eval(), DEV_SUBCKT::tr_probe_num(), tr_queue_eval(), tr_regress(), tr_restore(), tr_review(), and tr_unload().
{return _cl.end();}
const_iterator CARD_LIST::end () const [inline]
Definition at line 91 of file e_cardlist.h.
{return _cl.end();}
CARD_LIST & CARD_LIST::erase (iterator i)
Definition at line 101 of file e_cardlist.cc.
References _cl, and end().
Referenced by anonymous_namespace{c_delete.cc}::CMD_DELETE::delete_one_name().
{
  assert(ci != end());
  delete *ci;
  _cl.erase(ci);
  return *this;
}
CARD_LIST & CARD_LIST::erase (CARD * c)
Definition at line 109 of file e_cardlist.cc.
References _cl.
{
  delete c;
  _cl.remove(c);
  return *this;
}
CARD_LIST & CARD_LIST::erase_all ()
Definition at line 119 of file e_cardlist.cc.
References _cl.
Referenced by anonymous_namespace{c_delete.cc}::CMD_DELETE::do_it(), and ~CARD_LIST().
{
  while (!_cl.empty()) {
    delete _cl.back();
    _cl.pop_back();
  }
  return *this;
}
CARD_LIST & CARD_LIST::expand ()
Definition at line 153 of file e_cardlist.cc.
References begin(), end(), and trace_func_comp.
Referenced by DEV_LOGIC::expand(), DEV_SUBCKT::expand(), and SIM_DATA::init().
{
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).precalc_first();
  }
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).expand_first();
  }
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).expand();
  }
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).expand_last();
  }
  return *this;
}
iterator CARD_LIST::find_ (const std::string & short_name) [inline]
Definition at line 86 of file e_cardlist.h.
Referenced by PROBELIST::add_branches(), anonymous_namespace{c_delete.cc}::CMD_DELETE::delete_one_name(), CARD::find_in_my_scope(), CARD::find_in_parent_scope(), CARD::find_looking_out(), and LANGUAGE::find_proto().
                                        {return find_again(short_name, begin());}
const_iterator CARD_LIST::find_ (const std::string & short_name) const [inline]
Definition at line 93 of file e_cardlist.h.
                                        {return find_again(short_name, begin());}
CARD_LIST::iterator CARD_LIST::find_again (const std::string & short_name, CARD_LIST::iterator Begin)
Definition at line 89 of file e_cardlist.cc.
References end(), and notstd::find_ptr().
{
  return notstd::find_ptr(Begin, end(), short_name);
}
CARD_LIST::const_iterator CARD_LIST::find_again (const std::string & short_name, CARD_LIST::const_iterator Begin) const
Definition at line 95 of file e_cardlist.cc.
References end(), and notstd::find_ptr().
{
  return notstd::find_ptr(Begin, end(), short_name);
}
CARD_LIST& CARD_LIST::insert (CARD_LIST::iterator i, CARD * c) [inline]
Definition at line 99 of file e_cardlist.h.
References insert().
Referenced by insert().
                                        {_cl.insert(i, c);  return *this;}
bool CARD_LIST::is_empty () const [inline]
Definition at line 78 of file e_cardlist.h.
Referenced by anonymous_namespace{lang_gschem.cc}::CMD_C::do_it(), anonymous_namespace{lang_spectre.cc}::CMD_SUBCKT::do_it(), anonymous_namespace{lang_verilog.cc}::CMD_MODULE::do_it(), anonymous_namespace{lang_spice.cc}::CMD_SUBCKT::do_it(), MODEL_SUBCKT::MODEL_SUBCKT(), and anonymous_namespace{lang_spice.cc}::LANG_SPICE::parse_top_item().
{return _cl.empty();}
const LANGUAGE* CARD_LIST::language () const [inline]
Definition at line 80 of file e_cardlist.h.
References untested.
{untested(); return _language;}
CARD_LIST & CARD_LIST::map_nodes ()
Definition at line 194 of file e_cardlist.cc.
References begin(), end(), and trace_func_comp.
Referenced by SIM_DATA::init(), and COMPONENT::map_nodes().
{
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).map_nodes();
  }
  return *this;
}
void CARD_LIST::map_subckt_nodes (const CARD * model, const CARD * owner)
Definition at line 457 of file e_cardlist.cc.
References CKT_BASE::_sim, begin(), node_t::e_(), end(), NODE_MAP::how_many(), CARD::long_label(), CARD::n_(), CARD::net_nodes(), SIM_DATA::newnode_subckt(), nodes(), CARD::subckt(), node_t::t_(), trace0, trace2, and trace3.
Referenced by CARD_LIST().
{
  assert(model);
  assert(model->subckt());
  assert(model->subckt()->nodes());
  assert(owner);
  //assert(owner->subckt());
  //assert(owner->subckt() == this);
  trace0(model->long_label().c_str());
  trace0(owner->long_label().c_str());
  int num_nodes_in_subckt = model->subckt()->nodes()->how_many();
  int* map = new int[num_nodes_in_subckt+1];
  {
    map[0] = 0;
    // self test: verify that port node numbering is correct
    for (int port = 0; port < model->net_nodes(); ++port) {
      assert(model->n_(port).e_() <= num_nodes_in_subckt);
      //assert(model->n_(port).e_() == port+1);
      trace3("ports", port, model->n_(port).e_(), owner->n_(port).t_());
    }
    {
      // take care of the "port" nodes (external connections)
      // map them to what the calling circuit wants
      int i=0;
      for (i=1; i <= model->net_nodes(); ++i) {
        map[i] = owner->n_(i-1).t_();
        trace3("ports", i, map[i], owner->n_(i-1).t_());
      }
      // get new node numbers, and assign them to the remaining
      for (assert(i==model->net_nodes() + 1); i <= num_nodes_in_subckt; ++i) {
        // for each remaining node in card_list
        map[i] = CKT_BASE::_sim->newnode_subckt();
        trace2("internal", i, map[i]);
      }
    }
  }
  // "map" now contains a translation list,
  // from subckt local numbers to matrix index numbers
  // The node list (_nm) in an instance of a subckt does not exist.
  // Device nodes (type node_t) points to the NODE in the parent.
  // Mapping is done in node_t.
  // scan the list, map the nodes
  for (CARD_LIST::iterator ci = begin(); ci != end(); ++ci) {
    // for each card in card_list
    if ((**ci).is_device()) {
      for (int ii = 0;  ii < (**ci).net_nodes();  ++ii) {
        // for each connection node in card
        (**ci).n_(ii).map_subckt_node(map, owner);
      }
    }else{
      assert(dynamic_cast<MODEL_CARD*>(*ci));
    }
  }
}
NODE_MAP* CARD_LIST::nodes () const [inline]
Definition at line 132 of file e_cardlist.h.
Referenced by PROBELIST::add_all_nodes(), PROBELIST::add_branches(), map_subckt_nodes(), node_t::new_node(), and node_t::set_to_ground().
{assert(_nm); return _nm;}
PARAM_LIST * CARD_LIST::params ()
Definition at line 69 of file e_cardlist.cc.
References _params, and _parent.
Referenced by anonymous_namespace{c_param.cc}::CMD_PARAM::do_it(), anonymous_namespace{c_measure.cc}::CMD_MEASURE::do_it(), DEV_SUBCKT::expand(), PARAMETER< T >::lookup_solve(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_module(), and Token_SYMBOL::stack_op().
{
  if (!_params) {
    assert(!_parent);
    _params = new PARAM_LIST;
  }else{
  }
  return _params;
}
PARAM_LIST * CARD_LIST::params () const
Definition at line 79 of file e_cardlist.cc.
References _params.
{
  if (_params) {
    return _params;
  }else{ //BUG//const
    static PARAM_LIST empty_params;
    return &empty_params;
  }
}
const CARD_LIST* CARD_LIST::parent () const [inline]
Definition at line 79 of file e_cardlist.h.
Referenced by CARD::find_in_parent_scope().
{return _parent;}
CARD_LIST & CARD_LIST::precalc_first ()
Definition at line 174 of file e_cardlist.cc.
References begin(), end(), and trace_func_comp.
Referenced by SIM_DATA::init(), anonymous_namespace{c_list.cc}::list_save(), DEV_LOGIC::precalc_first(), and DEV_SUBCKT::precalc_first().
{
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).precalc_first();
  }
  return *this;
}
CARD_LIST & CARD_LIST::precalc_last ()
Definition at line 183 of file e_cardlist.cc.
References begin(), end(), and trace_func_comp.
Referenced by SIM_DATA::init(), DEV_LOGIC::precalc_last(), and DEV_SUBCKT::precalc_last().
{
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).precalc_last();
  }
  return *this;
}
CARD_LIST& CARD_LIST::push_back (CARD * c) [inline]
Definition at line 98 of file e_cardlist.h.
References push_back().
Referenced by anonymous_namespace{lang_gschem.cc}::CMD_C::do_it(), anonymous_namespace{lang_spectre.cc}::CMD_MODEL::do_it(), anonymous_namespace{lang_spectre.cc}::CMD_SUBCKT::do_it(), anonymous_namespace{lang_verilog.cc}::CMD_PARAMSET::do_it(), anonymous_namespace{lang_verilog.cc}::CMD_MODULE::do_it(), anonymous_namespace{lang_spice.cc}::CMD_MODEL::do_it(), anonymous_namespace{lang_spice.cc}::CMD_SUBCKT::do_it(), LANGUAGE::new__instance(), push_back(), and shallow_copy().
{_cl.push_back(c);  return *this;}
CARD_LIST& CARD_LIST::push_front (CARD * c) [inline]
Definition at line 97 of file e_cardlist.h.
References push_front().
Referenced by push_front().
{_cl.push_front(c); return *this;}
CARD_LIST & CARD_LIST::set_owner (CARD * owner)
Definition at line 128 of file e_cardlist.cc.
References begin(), end(), and trace_func_comp.
Referenced by CARD_LIST().
{
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).set_owner(owner);
  }
  return *this;
}
CARD_LIST & CARD_LIST::set_slave ()
Definition at line 140 of file e_cardlist.cc.
References begin(), end(), and trace_func_comp.
Referenced by COMPONENT::set_slave().
{
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).set_slave();
  }
  return *this;
}
void CARD_LIST::shallow_copy (const CARD_LIST * p)
Definition at line 442 of file e_cardlist.cc.
References _parent, begin(), CARD::clone(), end(), anonymous_namespace{c_genrat.cc}::p, push_back(), and trace_func_comp.
Referenced by CARD_LIST().
{
  assert(p);
  _parent = p;
  for (const_iterator ci = p->begin(); ci != p->end(); ++ci) {
    trace_func_comp();
    if ((**ci).is_device() || dynamic_cast<MODEL_CARD*>(*ci)) {
      CARD* copy = (**ci).clone();
      push_back(copy);
    }else{
    }
  }
}
CARD_LIST & CARD_LIST::tr_accept ()
Definition at line 360 of file e_cardlist.cc.
References begin(), end(), and trace_func_comp.
Referenced by TRANSIENT::accept(), anonymous_namespace{s_dc.cc}::DCOP::sweep_recursive(), and BASE_SUBCKT::tr_accept().
{
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).tr_accept();
  }
  return *this;
}
CARD_LIST & CARD_LIST::tr_advance ()
Definition at line 250 of file e_cardlist.cc.
References begin(), end(), and trace_func_comp.
Referenced by SIM::advance_time(), BASE_SUBCKT::tr_advance(), and DEV_LOGIC::tr_advance().
{
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).tr_advance();
  }
  return *this;
}
CARD_LIST & CARD_LIST::tr_begin ()
Definition at line 217 of file e_cardlist.cc.
References begin(), end(), and trace_func_comp.
Referenced by anonymous_namespace{s_dc.cc}::DCOP::sweep(), TRANSIENT::sweep(), BASE_SUBCKT::tr_begin(), and DEV_LOGIC::tr_begin().
{
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).tr_begin();
  }
  return *this;
}
CARD_LIST & CARD_LIST::tr_iwant_matrix ()
Definition at line 206 of file e_cardlist.cc.
References begin(), end(), and trace_func_comp.
Referenced by SIM_DATA::init(), DEV_LOGIC::tr_iwant_matrix(), and COMPONENT::tr_iwant_matrix().
{
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).tr_iwant_matrix();
  }
  return *this;
}
CARD_LIST & CARD_LIST::tr_load ()
Definition at line 326 of file e_cardlist.cc.
References CKT_BASE::_sim, begin(), end(), CARD::is_constant(), itested, CARD::tr_load(), trace_func_comp, and OPT::traceload.
Referenced by SIM::load_matrix(), BASE_SUBCKT::tr_load(), and DEV_LOGIC::tr_load().
{
  if (CKT_BASE::_sim->is_inc_mode()) {itested();
    assert(!OPT::traceload);
    for (iterator ci=begin(); ci!=end(); ++ci) {itested();
      trace_func_comp();
      CARD* brh = *ci;
      if (!brh->is_constant()) {itested();
        brh->tr_load();
      }else{itested();
      }
    }
  }else{
    for (iterator ci=begin(); ci!=end(); ++ci) {
      trace_func_comp();
      CARD* brh = *ci;
      brh->tr_load();
    }
  }
  return *this;
}
bool CARD_LIST::tr_needs_eval () const
Definition at line 272 of file e_cardlist.cc.
References begin(), end(), itested, trace_func_comp, and untested.
Referenced by BASE_SUBCKT::tr_needs_eval(), and DEV_LOGIC::tr_needs_eval().
{
  for (const_iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    if ((**ci).tr_needs_eval()) {
      return true;
    }else{itested();
    }
  }
  untested();
  return false;
}
CARD_LIST & CARD_LIST::tr_queue_eval ()
Definition at line 287 of file e_cardlist.cc.
References begin(), end(), and trace_func_comp.
Referenced by SIM::finish_building_evalq(), BASE_SUBCKT::tr_queue_eval(), and DEV_LOGIC::tr_queue_eval().
{
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).tr_queue_eval();
  }
  return *this;
}
CARD_LIST & CARD_LIST::tr_regress ()
Definition at line 261 of file e_cardlist.cc.
References begin(), end(), and trace_func_comp.
Referenced by SIM::advance_time(), BASE_SUBCKT::tr_regress(), and DEV_LOGIC::tr_regress().
{
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).tr_regress();
  }
  return *this;
}
CARD_LIST & CARD_LIST::tr_restore ()
Definition at line 228 of file e_cardlist.cc.
References begin(), end(), and trace_func_comp.
Referenced by TRANSIENT::sweep(), BASE_SUBCKT::tr_restore(), and DEV_LOGIC::tr_restore().
{
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).tr_restore();
  }
  return *this;
}
TIME_PAIR CARD_LIST::tr_review ()
Definition at line 348 of file e_cardlist.cc.
References begin(), end(), TIME_PAIR::min(), and trace_func_comp.
Referenced by TRANSIENT::review(), BASE_SUBCKT::tr_review(), and DEV_LOGIC::tr_review().
{
  TIME_PAIR time_by;
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    time_by.min((**ci).tr_review());
  }
  return time_by;
}
CARD_LIST & CARD_LIST::tr_unload ()
Definition at line 372 of file e_cardlist.cc.
References begin(), end(), and trace_func_comp.
Referenced by BASE_SUBCKT::tr_unload(), and DEV_LOGIC::tr_unload().
{
  for (iterator ci=begin(); ci!=end(); ++ci) {
    trace_func_comp();
    (**ci).tr_unload();
  }
  return *this;
}
Member Data Documentation
std::list<CARD*> CARD_LIST::_cl [private]
Definition at line 45 of file e_cardlist.h.
Referenced by erase(), and erase_all().
LANGUAGE* CARD_LIST::_language [private]
Definition at line 44 of file e_cardlist.h.
NODE_MAP* CARD_LIST::_nm [mutable, private]
Definition at line 42 of file e_cardlist.h.
Referenced by ~CARD_LIST().
PARAM_LIST* CARD_LIST::_params [mutable, private]
Definition at line 43 of file e_cardlist.h.
Referenced by attach_params(), params(), and ~CARD_LIST().
const CARD_LIST* CARD_LIST::_parent [private]
Definition at line 41 of file e_cardlist.h.
Referenced by params(), shallow_copy(), and ~CARD_LIST().
CARD_LIST CARD_LIST::card_list [static]
Definition at line 148 of file e_cardlist.h.
Referenced by TRANSIENT::accept(), PROBELIST::add_all_nodes(), PROBELIST::add_list(), SIM::advance_time(), anonymous_namespace{c_attach.cc}::CMD_ATTACH::do_it(), anonymous_namespace{c_attach.cc}::CMD_DETACH::do_it(), anonymous_namespace{c_delete.cc}::CMD_DELETE::do_it(), SIM::evaluate_models(), CARD::find_looking_out(), LANGUAGE::find_proto(), SIM::finish_building_evalq(), SIM_DATA::init(), anonymous_namespace{c_list.cc}::list_save(), SIM::load_matrix(), main(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_command(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_command(), anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_command(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_command(), anonymous_namespace{lang_spice.cc}::LANG_SPICE::parse_top_item(), process_cmd_line(), read_startup_files(), TRANSIENT::review(), CARD::scope(), anonymous_namespace{s_dc.cc}::DC::setup(), anonymous_namespace{s_ac.cc}::AC::solve(), anonymous_namespace{s_dc.cc}::DCOP::sweep(), anonymous_namespace{s_ac.cc}::AC::sweep(), TRANSIENT::sweep(), and anonymous_namespace{s_dc.cc}::DCOP::sweep_recursive().
The documentation for this class was generated from the following files:
savant/gnucap/src/e_cardlist.h
savant/gnucap/src/e_cardlist.cc
savant/gnucap/src/globals.cc