gnucap: EVAL_BUILT_IN_MOS_Cgd Class Reference
EVAL_BUILT_IN_MOS_Cgd Class Reference
#include <d_mos.h>
Public Member Functions
EVAL_BUILT_IN_MOS_Cgd (int c=0)
bool operator== (const COMMON_COMPONENT &x) const
COMMON_COMPONENT * clone () const
std::string name () const
void tr_eval (ELEMENT *d) const
bool has_tr_eval () const
bool has_ac_eval () const
Private Member Functions
EVAL_BUILT_IN_MOS_Cgd (const EVAL_BUILT_IN_MOS_Cgd &p)
Detailed Description
Definition at line 94 of file d_mos.h.
Constructor & Destructor Documentation
EVAL_BUILT_IN_MOS_Cgd::EVAL_BUILT_IN_MOS_Cgd (const EVAL_BUILT_IN_MOS_Cgd & p) [inline, explicit, private]
Definition at line 96 of file d_mos.h.
Referenced by clone().
    :COMMON_COMPONENT(p) {}
EVAL_BUILT_IN_MOS_Cgd::EVAL_BUILT_IN_MOS_Cgd (int c = 0) [inline, explicit]
Definition at line 99 of file d_mos.h.
:COMMON_COMPONENT(c) {}
Member Function Documentation
COMMON_COMPONENT* EVAL_BUILT_IN_MOS_Cgd::clone () const [inline, virtual]
Implements COMMON_COMPONENT.
Definition at line 101 of file d_mos.h.
References EVAL_BUILT_IN_MOS_Cgd().
{return new EVAL_BUILT_IN_MOS_Cgd(*this);}
bool EVAL_BUILT_IN_MOS_Cgd::has_ac_eval () const [inline, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 105 of file d_mos.h.
{return false;}
bool EVAL_BUILT_IN_MOS_Cgd::has_tr_eval () const [inline, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 104 of file d_mos.h.
{return true;}
std::string EVAL_BUILT_IN_MOS_Cgd::name () const [inline, virtual]
Implements COMMON_COMPONENT.
Definition at line 102 of file d_mos.h.
References untested.
{untested(); return "EVAL_BUILT_IN_MOS_Cgd";}
bool EVAL_BUILT_IN_MOS_Cgd::operator== (const COMMON_COMPONENT & x) const [inline, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 100 of file d_mos.h.
{return COMMON_COMPONENT::operator==(x);}
void EVAL_BUILT_IN_MOS_Cgd::tr_eval (ELEMENT * d) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 343 of file d_mos.cc.
References CKT_BASE::_sim, ELEMENT::_y, SIM_DATA::analysis_is_restore(), SIM_DATA::analysis_is_static(), SIM_DATA::analysis_is_tran_dynamic(), SDP_BUILT_IN_MOS_BASE::cgate, MODEL_BUILT_IN_MOS_BASE::cmodel, COMPONENT::common(), FPOLY1::f0, FPOLY1::f1, CARD::long_label(), COMMON_COMPONENT::model(), CARD::owner(), anonymous_namespace{c_genrat.cc}::p, SDP_BUILT_IN_MOS_BASE::phi, prechecked_cast, DEV_BUILT_IN_MOS::reversed, COMMON_BUILT_IN_MOS::sdp(), trace3, COMPONENT::value(), DEV_BUILT_IN_MOS::vbs, DEV_BUILT_IN_MOS::vds, DEV_BUILT_IN_MOS::vdsat, DEV_BUILT_IN_MOS::vgst, and FPOLY1::x.
{
  assert(d);
  DEV_BUILT_IN_MOS* p = prechecked_cast<DEV_BUILT_IN_MOS*>(d->owner());
  assert(p);
  const COMMON_BUILT_IN_MOS* c = prechecked_cast<const COMMON_BUILT_IN_MOS*>(p->common());
  assert(c);
  const SDP_BUILT_IN_MOS_BASE* s = prechecked_cast<const SDP_BUILT_IN_MOS_BASE*>(c->sdp());
  assert(s);
  const MODEL_BUILT_IN_MOS_BASE* m = prechecked_cast<const MODEL_BUILT_IN_MOS_BASE*>(c->model());
  assert(m);
    STORAGE* brh = prechecked_cast<STORAGE*>(d);
    assert(brh);
    double cap = 0;
    if (m->cmodel != 0) {
      assert(p->vdsat >= 0.);
      assert(p->vds >= 0.);
      double vbs    = (m->cmodel == 3) ? 0. : p->vbs;
      double vdbsat = p->vdsat - vbs;
      double vdb    = p->vds   - vbs;
      double ddif   = 2. * vdbsat - vdb;
      if (!p->reversed) { // treat as Cgs
        if (p->vgst >= 0.) {
          if (p->vdsat > p->vds) {              /* linear */
            cap = (2./3.) * s->cgate * (1. - (vdbsat*vdbsat)/(ddif*ddif));
            if (p->vgst <= .1) {
              cap *= 10. * p->vgst;     // smooth discontinuity
            }
          }
        }
      }else{ // treat as Cgs
        if (p->vgst >= -s->phi/2.) {            /* depletion  or active */
          cap = (2./3.) * s->cgate;
          if (p->vdsat > p->vds) {                      /* linear */
            double ndif   = p->vdsat - p->vds;
            cap *= 1. - (ndif*ndif)/(ddif*ddif);
          }
          if (p->vgst <= 0) {
            cap *= 1. + p->vgst / (s->phi);
            cap *= 1. + p->vgst / (s->phi);
          }
        }
      }
    }
    cap += brh->value();                /* else overlap only */
    brh->_y[0].f1 = cap;
    if (d->_sim->analysis_is_tran_dynamic()) {
      cap = (brh->_y[0].f1 + brh->_y[1].f1) / 2;
      brh->_y[0].f0 = (brh->_y[0].x - brh->_y[1].x) * cap + brh->_y[1].f0;
    }else{
      assert(d->_sim->analysis_is_static() || d->_sim->analysis_is_restore());
      brh->_y[0].f0 = brh->_y[0].x * brh->_y[0].f1;
    }
    trace3(brh->long_label().c_str(), brh->_y[0].x, brh->_y[0].f0, brh->_y[0].f1);
}
The documentation for this class was generated from the following files:
savant/gnucap/src/d_mos.h
savant/gnucap/src/d_mos.cc