gnucap: anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G Class Reference
anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G Class Reference
Public Member Functions
DEV_CPOLY_G ()
~DEV_CPOLY_G ()
void set_parameters (const std::string &Label, CARD *Parent, COMMON_COMPONENT *Common, double Value, int state_count, double state[], int node_count, const node_t nodes[])
Protected Member Functions
DEV_CPOLY_G (const DEV_CPOLY_G &p)
char id_letter () const
std::string value_name () const
std::string dev_type () const
int max_nodes () const
int min_nodes () const
int matrix_nodes () const
int net_nodes () const
CARD * clone () const
void tr_iwant_matrix ()
bool do_tr ()
void tr_load ()
void tr_unload ()
double tr_involts () const
double tr_involts_limited () const
double tr_amps () const
void ac_iwant_matrix ()
void ac_load ()
COMPLEX ac_involts () const
COMPLEX ac_amps () const
std::string port_name (int) const
bool do_tr_con_chk_and_q ()
Protected Attributes
double * _values
double * _old_values
int _n_ports
double _time
const double ** _inputs
Detailed Description
Definition at line 36 of file d_poly_g.cc.
Constructor & Destructor Documentation
anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::DEV_CPOLY_G (const DEV_CPOLY_G & p) [explicit, protected]
Definition at line 100 of file d_poly_g.cc.
References _inputs, _n_ports, _old_values, and _values.
  :ELEMENT(p),
   _values(NULL),
   _old_values(NULL),
   _n_ports(p._n_ports),
   _time(NOT_VALID),
   _inputs(NULL)
{
  // not really a copy .. only valid to copy a default
  // too lazy to do it right, and that's all that is being used
  // to do it correctly requires a deep copy
  // just filling in defaults is better than a shallow copy, hence this:
  assert(!p._values);
  assert(!p._old_values);
  assert(p._n_ports == 0);
  assert(!p._inputs);
}
anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::DEV_CPOLY_G () [explicit]
Definition at line 118 of file d_poly_g.cc.
  :ELEMENT(),
   _values(NULL),
   _old_values(NULL),
   _n_ports(0),
   _time(NOT_VALID),
   _inputs(NULL)
{
}
anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::~DEV_CPOLY_G ()
Definition at line 128 of file d_poly_g.cc.
References CARD::_n, _old_values, net_nodes(), and NODES_PER_BRANCH.
{
  delete [] _old_values;
  if (net_nodes() > NODES_PER_BRANCH) {
    delete [] _n;
  }else{
    // it is part of a base class
  }
}
Member Function Documentation
COMPLEX anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::ac_amps () const [inline, protected, virtual]
Reimplemented from ELEMENT.
Definition at line 67 of file d_poly_g.cc.
References itested, and NOT_VALID.
{itested(); return NOT_VALID;}
COMPLEX anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::ac_involts () const [inline, protected, virtual]
Implements ELEMENT.
Definition at line 66 of file d_poly_g.cc.
References itested, and NOT_VALID.
{itested(); return NOT_VALID;}
void anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::ac_iwant_matrix () [inline, protected, virtual]
Implements ELEMENT.
Definition at line 64 of file d_poly_g.cc.
{ac_iwant_matrix_extended();}
void anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::ac_load () [protected, virtual]
Reimplemented from CARD.
Definition at line 210 of file d_poly_g.cc.
References ELEMENT::_acg, CARD::_n, _n_ports, _values, ELEMENT::ac_load_extended(), ELEMENT::ac_load_passive(), OUT1, and OUT2.
{
  _acg = _values[1];
  ac_load_passive();
  for (int i=2; i<=_n_ports; ++i) {
    ac_load_extended(_n[OUT1], _n[OUT2], _n[2*i-2], _n[2*i-1], _values[i]);
  }
}
CARD* anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::clone () const [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 56 of file d_poly_g.cc.
{return new DEV_CPOLY_G(*this);}
std::string anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::dev_type () const [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 51 of file d_poly_g.cc.
References unreachable.
{unreachable(); return "cpoly_g";}
bool anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::do_tr () [protected, virtual]
Reimplemented from CARD.
Definition at line 151 of file d_poly_g.cc.
References ELEMENT::_m0, _values, and do_tr_con_chk_and_q().
{
  assert(_values);
  _m0 = CPOLY1(0., _values[0], _values[1]);
  return do_tr_con_chk_and_q();
}
bool anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::do_tr_con_chk_and_q () [protected]
Definition at line 138 of file d_poly_g.cc.
References _n_ports, _old_values, CKT_BASE::_sim, _time, SIM_DATA::_time0, _values, conchk(), COMPONENT::converged(), COMPONENT::q_load(), and COMPONENT::set_converged().
Referenced by do_tr().
{
  q_load();
  assert(_old_values);
  set_converged(conchk(_time, _sim->_time0));
  _time = _sim->_time0;
  for (int i=0; converged() && i<=_n_ports; ++i) {
    set_converged(conchk(_old_values[i], _values[i]));
  }
  return converged();
}
char anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::id_letter () const [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 49 of file d_poly_g.cc.
References unreachable.
{unreachable(); return '\0';}
int anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::matrix_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 54 of file d_poly_g.cc.
{return _n_ports*2;}
int anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::max_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 52 of file d_poly_g.cc.
{return net_nodes();}
int anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::min_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 53 of file d_poly_g.cc.
{return net_nodes();}
int anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::net_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 55 of file d_poly_g.cc.
Referenced by set_parameters(), and ~DEV_CPOLY_G().
{return _n_ports*2;}
std::string anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::port_name (int) const [inline, protected, virtual]
Implements COMPONENT.
Definition at line 69 of file d_poly_g.cc.
References incomplete, unreachable, and untested.
                                {untested();
    incomplete();
    unreachable();
    return "";
  }
void anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::set_parameters (const std::string & Label, CARD * Parent, COMMON_COMPONENT * Common, double Value, int state_count, double state[], int node_count, const node_t nodes[]) [virtual]
Reimplemented from COMPONENT.
Definition at line 221 of file d_poly_g.cc.
References _inputs, CARD::_n, _n_ports, _old_values, _values, COMPONENT::attach_common(), notstd::copy_n(), net_nodes(), NODES_PER_BRANCH, CKT_BASE::set_label(), CARD::set_owner(), and COMPONENT::set_value().
{
  bool first_time = (net_nodes() == 0);
  set_label(Label);
  set_owner(Owner);
  set_value(Value);
  attach_common(Common);
  if (first_time) {
    _n_ports = n_nodes/2; // sets num_nodes() = _n_ports*2
    assert(_n_ports == n_states-1);
    assert(!_old_values);
    _old_values = new double[n_states];
    if (net_nodes() > NODES_PER_BRANCH) {
      // allocate a bigger node list
      _n = new node_t[net_nodes()];
    }else{
      // use the default node list, already set
    }
  }else{
    assert(_n_ports == n_states-1);
    assert(_old_values);
    assert(net_nodes() == n_nodes);
    // assert could fail if changing the number of nodes after a run
  }
  //_inputs = inputs;
  _inputs = 0;
  _values = states;
  std::fill_n(_values, n_states, 0.);
  std::fill_n(_old_values, n_states, 0.);
  notstd::copy_n(nodes, net_nodes(), _n);
  assert(net_nodes() == _n_ports * 2);
}
double anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::tr_amps () const [protected, virtual]
Reimplemented from ELEMENT.
Definition at line 201 of file d_poly_g.cc.
References ELEMENT::_m0, CARD::_n, _n_ports, _values, CPOLY1::c0, and dn_diff().
{
  double amps = _m0.c0;
  for (int i=1; i<=_n_ports; ++i) {
    amps += dn_diff(_n[2*i-2].v0(),_n[2*i-1].v0()) * _values[i];
  }
  return amps;
}
double anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::tr_involts () const [inline, protected, virtual]
Implements ELEMENT.
Definition at line 61 of file d_poly_g.cc.
References NOT_VALID, and unreachable.
{unreachable(); return NOT_VALID;}
double anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::tr_involts_limited () const [inline, protected, virtual]
Implements ELEMENT.
Definition at line 62 of file d_poly_g.cc.
References NOT_VALID, and unreachable.
{unreachable(); return NOT_VALID;}
void anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::tr_iwant_matrix () [inline, protected, virtual]
Implements ELEMENT.
Definition at line 57 of file d_poly_g.cc.
{tr_iwant_matrix_extended();}
void anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::tr_load () [protected, virtual]
Reimplemented from CARD.
Definition at line 183 of file d_poly_g.cc.
References CARD::_n, _n_ports, _old_values, _values, OUT1, OUT2, ELEMENT::tr_load_extended(), and ELEMENT::tr_load_passive().
Referenced by tr_unload().
{
  tr_load_passive();
  _old_values[0] = _values[0];
  _old_values[1] = _values[1];
  for (int i=2; i<=_n_ports; ++i) {
    tr_load_extended(_n[OUT1], _n[OUT2], _n[2*i-2], _n[2*i-1], &(_values[i]), &(_old_values[i]));
  }
}
void anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::tr_unload () [protected, virtual]
Reimplemented from CARD.
Definition at line 193 of file d_poly_g.cc.
References ELEMENT::_m0, _n_ports, CKT_BASE::_sim, _values, CPOLY1::c0, CPOLY1::c1, SIM_DATA::mark_inc_mode_bad(), and tr_load().
{
  std::fill_n(_values, _n_ports+1, 0.);
  _m0.c0 = _m0.c1 = 0.;
  _sim->mark_inc_mode_bad();
  tr_load();
}
std::string anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::value_name () const [inline, protected, virtual]
Implements CARD.
Definition at line 50 of file d_poly_g.cc.
References incomplete.
{incomplete(); return "";}
Member Data Documentation
const double** anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::_inputs [protected]
Definition at line 42 of file d_poly_g.cc.
Referenced by DEV_CPOLY_G(), and set_parameters().
int anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::_n_ports [protected]
Definition at line 40 of file d_poly_g.cc.
Referenced by ac_load(), DEV_CPOLY_G(), do_tr_con_chk_and_q(), set_parameters(), tr_amps(), tr_load(), and tr_unload().
double* anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::_old_values [protected]
Definition at line 39 of file d_poly_g.cc.
Referenced by DEV_CPOLY_G(), do_tr_con_chk_and_q(), set_parameters(), tr_load(), and ~DEV_CPOLY_G().
double anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::_time [protected]
Reimplemented from ELEMENT.
Definition at line 41 of file d_poly_g.cc.
Referenced by do_tr_con_chk_and_q().
double* anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::_values [protected]
Definition at line 38 of file d_poly_g.cc.
Referenced by ac_load(), DEV_CPOLY_G(), do_tr(), do_tr_con_chk_and_q(), set_parameters(), tr_amps(), tr_load(), and tr_unload().
The documentation for this class was generated from the following file:
savant/gnucap/src/d_poly_g.cc