gnucap: DEV_SUBCKT Class Reference
DEV_SUBCKT Class Reference
#include <d_subckt.h>
Public Member Functions
DEV_SUBCKT ()
~DEV_SUBCKT ()
Static Public Member Functions
static int count ()
Private Member Functions
DEV_SUBCKT (const DEV_SUBCKT &)
char id_letter () const
bool print_type_in_spice () const
std::string value_name () const
int max_nodes () const
int min_nodes () const
int matrix_nodes () const
int net_nodes () const
CARD * clone () const
void precalc_first ()
void expand ()
void precalc_last ()
double tr_probe_num (const std::string &) const
int param_count_dont_print () const
std::string port_name (int i) const
Private Attributes
const MODEL_SUBCKT * _parent
node_t _nodes [PORTS_PER_SUBCKT]
Static Private Attributes
static int _count = -1
Friends
class MODEL_SUBCKT
Detailed Description
Definition at line 70 of file d_subckt.h.
Constructor & Destructor Documentation
DEV_SUBCKT::DEV_SUBCKT (const DEV_SUBCKT & p) [explicit, private]
Definition at line 157 of file d_subckt.cc.
References _count, CARD::_n, _nodes, and max_nodes().
  :BASE_SUBCKT(p),
   _parent(p._parent)
{
  //strcpy(modelname, p.modelname); in common
  for (int ii = 0;  ii < max_nodes();  ++ii) {
    _nodes[ii] = p._nodes[ii];
  }
  _n = _nodes;
  ++_count;
}
DEV_SUBCKT::DEV_SUBCKT () [explicit]
Definition at line 148 of file d_subckt.cc.
References _count, CARD::_n, _nodes, COMPONENT::attach_common(), and Default_SUBCKT.
Referenced by clone().
  :BASE_SUBCKT(),
   _parent(NULL)
{
  attach_common(&Default_SUBCKT);
  _n = _nodes;
  ++_count;
}
DEV_SUBCKT::~DEV_SUBCKT () [inline]
Definition at line 76 of file d_subckt.h.
References _count.
{--_count;}
Member Function Documentation
CARD* DEV_SUBCKT::clone () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 85 of file d_subckt.h.
References DEV_SUBCKT().
Referenced by MODEL_SUBCKT::clone_instance().
{return new DEV_SUBCKT(*this);}
static int DEV_SUBCKT::count () [inline, static]
Definition at line 100 of file d_subckt.h.
References _count.
{return _count;}
void DEV_SUBCKT::expand () [private, virtual]
Reimplemented from COMPONENT.
Definition at line 169 of file d_subckt.cc.
References COMMON_SUBCKT::_params, _parent, PARAM_LIST::_try_again, CARD_LIST::expand(), CARD::find_looking_out(), CARD::long_label(), COMMON_COMPONENT::modelname(), COMPONENT::mutable_common(), CARD_LIST::params(), prechecked_cast, CARD::renew_subckt(), CARD::scope(), PARAM_LIST::set_try_again(), and CARD::subckt().
{
  BASE_SUBCKT::expand();
  COMMON_SUBCKT* c = prechecked_cast<COMMON_SUBCKT*>(mutable_common());
  assert(c);
  const CARD* model = find_looking_out(c->modelname());
  if (!_parent) {
    if(!dynamic_cast<const MODEL_SUBCKT*>(model)) {
      throw Exception_Type_Mismatch(long_label(), c->modelname(), "subckt");
    }else{
      _parent = prechecked_cast<const MODEL_SUBCKT*>(model);
    }
  }else{
    assert(model && model == _parent);
  }
  //assert(!c->_params._try_again);
  assert(model->subckt());
  assert(model->subckt()->params());
  PARAM_LIST* pl = const_cast<PARAM_LIST*>(model->subckt()->params());
  assert(pl);
  c->_params.set_try_again(pl);
  assert(c->_params._try_again);
  renew_subckt(model, this, scope(), &(c->_params));
  subckt()->expand();
}
char DEV_SUBCKT::id_letter () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 78 of file d_subckt.h.
{return 'X';}
int DEV_SUBCKT::matrix_nodes () const [inline, private, virtual]
Reimplemented from BASE_SUBCKT.
Definition at line 83 of file d_subckt.h.
{return 0;}
int DEV_SUBCKT::max_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 81 of file d_subckt.h.
References PORTS_PER_SUBCKT.
Referenced by DEV_SUBCKT().
{return PORTS_PER_SUBCKT;}
int DEV_SUBCKT::min_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 82 of file d_subckt.h.
{return 0;}
int DEV_SUBCKT::net_nodes () const [inline, private, virtual]
Reimplemented from BASE_SUBCKT.
Definition at line 84 of file d_subckt.h.
References CARD::_net_nodes.
{return _net_nodes;}
int DEV_SUBCKT::param_count_dont_print () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 90 of file d_subckt.h.
References COMPONENT::common().
{return common()->COMMON_COMPONENT::param_count();}
std::string DEV_SUBCKT::port_name (int i) const [inline, private, virtual]
Implements COMPONENT.
Definition at line 92 of file d_subckt.h.
References _parent, itested, and COMPONENT::port_value().
                                  {itested();
    if (_parent) {itested();
      return _parent->port_value(i);
    }else{itested();
      return "";
    }
  }
void DEV_SUBCKT::precalc_first () [private, virtual]
Reimplemented from COMPONENT.
Definition at line 196 of file d_subckt.cc.
References COMMON_SUBCKT::_params, CARD_LIST::attach_params(), CARD::is_constant(), COMPONENT::mutable_common(), CARD_LIST::precalc_first(), prechecked_cast, CARD::scope(), and CARD::subckt().
{
  BASE_SUBCKT::precalc_first();
  if (subckt()) {
    COMMON_SUBCKT* c = prechecked_cast<COMMON_SUBCKT*>(mutable_common());
    assert(c);
    subckt()->attach_params(&(c->_params), scope());
    subckt()->precalc_first();
  }else{
  }
  assert(!is_constant()); /* because I have more work to do */
}
void DEV_SUBCKT::precalc_last () [private, virtual]
Reimplemented from COMPONENT.
Definition at line 210 of file d_subckt.cc.
References COMMON_SUBCKT::_params, CARD_LIST::attach_params(), CARD::is_constant(), COMPONENT::mutable_common(), CARD_LIST::precalc_last(), prechecked_cast, CARD::scope(), and CARD::subckt().
{
  BASE_SUBCKT::precalc_last();
  COMMON_SUBCKT* c = prechecked_cast<COMMON_SUBCKT*>(mutable_common());
  assert(c);
  subckt()->attach_params(&(c->_params), scope());
  subckt()->precalc_last();
  assert(!is_constant()); /* because I have more work to do */
}
bool DEV_SUBCKT::print_type_in_spice () const [inline, private, virtual]
Implements COMPONENT.
Definition at line 79 of file d_subckt.h.
{return true;}
double DEV_SUBCKT::tr_probe_num (const std::string & x) const [private, virtual]
Reimplemented from COMPONENT.
Definition at line 222 of file d_subckt.cc.
References CARD_LIST::end(), itested, CKT_BASE::probe(), CARD::subckt(), Umatch(), and untested.
{itested();
  if (Umatch(x, "p ")) {untested();
    double power = 0.;
    assert(subckt());
    for (CARD_LIST::const_iterator
           ci = subckt()->begin(); ci != subckt()->end(); ++ci) {untested();
      power += CARD::probe(*ci,"P");
    }
    return power;
  }else if (Umatch(x, "pd ")) {untested();
    double power = 0.;
    assert(subckt());
    for (CARD_LIST::const_iterator
           ci = subckt()->begin(); ci != subckt()->end(); ++ci) {untested();
      power += CARD::probe(*ci,"PD");
    }
    return power;
  }else if (Umatch(x, "ps ")) {untested();
    double power = 0.;
    assert(subckt());
    for (CARD_LIST::const_iterator
           ci = subckt()->begin(); ci != subckt()->end(); ++ci) {untested();
      power += CARD::probe(*ci,"PS");
    }
    return power;
  }else{itested();
    return COMPONENT::tr_probe_num(x);
  }
  /*NOTREACHED*/
}
std::string DEV_SUBCKT::value_name () const [inline, private, virtual]
Implements CARD.
Definition at line 80 of file d_subckt.h.
{return "#";}
Friends And Related Function Documentation
friend class MODEL_SUBCKT [friend]
Definition at line 71 of file d_subckt.h.
Member Data Documentation
int DEV_SUBCKT::_count = -1 [static, private]
Definition at line 104 of file d_subckt.h.
Referenced by count(), DEV_SUBCKT(), and ~DEV_SUBCKT().
node_t DEV_SUBCKT::_nodes[PORTS_PER_SUBCKT] [private]
Definition at line 103 of file d_subckt.h.
Referenced by DEV_SUBCKT().
const MODEL_SUBCKT* DEV_SUBCKT::_parent [private]
Definition at line 102 of file d_subckt.h.
Referenced by MODEL_SUBCKT::clone_instance(), expand(), and port_name().
The documentation for this class was generated from the following files:
savant/gnucap/src/d_subckt.h
savant/gnucap/src/d_subckt.cc