gnucap: Token_UNARY Class Reference
Token_UNARY Class Reference
#include <m_expression.h>
Public Member Functions
Token_UNARY (const std::string Name)
Token_UNARY (const Token_UNARY &P)
Token * clone () const
Token * op (const Token *t1) const
void stack_op (Expression *) const
Detailed Description
Definition at line 95 of file m_expression.h.
Constructor & Destructor Documentation
Token_UNARY::Token_UNARY (const std::string Name) [inline, explicit]
Definition at line 98 of file m_expression.h.
Referenced by clone().
    : Token(Name, NULL, "") {}
Token_UNARY::Token_UNARY (const Token_UNARY & P) [inline, explicit]
Definition at line 100 of file m_expression.h.
References untested.
: Token(P) {untested();}
Member Function Documentation
Token* Token_UNARY::clone () const [inline, virtual]
Implements Token.
Definition at line 101 of file m_expression.h.
References Token_UNARY(), and untested.
Referenced by stack_op().
{untested();return new Token_UNARY(*this);}
Token * Token_UNARY::op (const Token * t1) const
Definition at line 85 of file m_expression_reduce.cc.
References Token::aRgs(), Token::data(), Base::logic_not(), Base::minus(), Token::name(), Base::plus(), unreachable, and untested.
Referenced by stack_op().
{
  assert(T1);
  assert(dynamic_cast<const Token_CONSTANT*>(T1));
  assert(T1->data());
  const Base* b = 0;
  if (name() == "-") {
    b = (T1->data())->minus();
  }else if (name() == "+") {
    b = (T1->data())->plus();
  }else if (name() == "!") {
    b = (T1->data())->logic_not();
  }else{
    // op (name()) not one of those listed
    unreachable();
    return NULL;
  }
  if (b) {
    if (T1->aRgs() == "") {
    }else{untested();
    }
    return new Token_CONSTANT(b->val_string(), b, (T1->aRgs()));
  }else{untested();
    // can get here if T1 has no data
    return new Token_CONSTANT("false", NULL, "");
  }
}
void Token_UNARY::stack_op (Expression * E) const [virtual]
Reimplemented from Token.
Definition at line 253 of file m_expression_reduce.cc.
References List_Base< T >::back(), clone(), Token::data(), op(), List_Base< T >::pop_back(), List_Base< T >::push_back(), and untested.
{
  assert(E);
  // replace 1 token with 1 (result)
  Token* t1 = E->back();
  E->pop_back();
  if (dynamic_cast<Token_CONSTANT*>(t1)) {
    Token* t = op(t1);
    assert(t);
    if (t->data()) {
      E->push_back(t);
      delete t1;
    }else{untested();
      E->push_back(t1);
      E->push_back(clone());
      delete t;
    }
  }else{untested();
    E->push_back(t1);
    E->push_back(clone());
  }
}
The documentation for this class was generated from the following files:
savant/gnucap/src/m_expression.h
savant/gnucap/src/m_expression_reduce.cc