gnucap: CARDSTASH Class Reference
CARDSTASH Class Reference
#include <u_cardst.h>
Public Member Functions
CARDSTASH ()
CARDSTASH (CARD *b)
CARDSTASH (const CARDSTASH &p)
~CARDSTASH ()
void operator= (CARD *b)
void restore ()
Private Attributes
COMPONENT * _brh
double _value
COMMON_COMPONENT * _c
Detailed Description
Definition at line 29 of file u_cardst.h.
Constructor & Destructor Documentation
CARDSTASH::CARDSTASH () [inline, explicit]
Definition at line 35 of file u_cardst.h.
:_brh(0), _value(0.), _c(0) {}
CARDSTASH::CARDSTASH (CARD * b) [inline, explicit]
Definition at line 64 of file u_cardst.h.
  :_brh(0),
   _value(NOT_VALID),
   _c(0)
{
  *this = b;
}
CARDSTASH::CARDSTASH (const CARDSTASH & p) [inline]
Definition at line 72 of file u_cardst.h.
References _c, and COMMON_COMPONENT::attach_common().
  :_brh(p._brh),
   _value(p._value),
   _c(0)
{
  COMMON_COMPONENT::attach_common(p._c, &_c);
}
CARDSTASH::~CARDSTASH () [inline]
Definition at line 38 of file u_cardst.h.
References _c, and COMMON_COMPONENT::detach_common().
{COMMON_COMPONENT::detach_common(&_c);}
Member Function Documentation
void CARDSTASH::operator= (CARD * b) [inline]
Definition at line 54 of file u_cardst.h.
References _brh, _c, _value, COMMON_COMPONENT::attach_common(), COMMON_COMPONENT::detach_common(), COMPONENT::mutable_common(), prechecked_cast, and COMPONENT::value().
{
  assert(b);
  _brh = prechecked_cast<COMPONENT*>(b);
  assert(_brh);
  _value = _brh->value();
  COMMON_COMPONENT::detach_common(&_c);
  COMMON_COMPONENT::attach_common(_brh->mutable_common(), &_c);
}
void CARDSTASH::restore () [inline]
Definition at line 40 of file u_cardst.h.
References _brh, _c, _value, and COMPONENT::set_value().
Referenced by anonymous_namespace{s_dc.cc}::DCOP::finish().
{assert(_brh); _brh->set_value(_value, _c);}
Member Data Documentation
COMPONENT* CARDSTASH::_brh [private]
Definition at line 31 of file u_cardst.h.
Referenced by operator=(), and restore().
COMMON_COMPONENT* CARDSTASH::_c [private]
Definition at line 33 of file u_cardst.h.
Referenced by CARDSTASH(), operator=(), restore(), and ~CARDSTASH().
double CARDSTASH::_value [private]
Definition at line 32 of file u_cardst.h.
Referenced by operator=(), and restore().
The documentation for this class was generated from the following file:
savant/gnucap/src/u_cardst.h