gnucap: anonymous_namespace{c_system.cc}::CMD_SYSTEM Class Reference
anonymous_namespace{c_system.cc}::CMD_SYSTEM Class Reference
Public Member Functions
void do_it (CS &cmd, CARD_LIST *)
Detailed Description
Definition at line 57 of file c_system.cc.
Member Function Documentation
void anonymous_namespace{c_system.cc}::CMD_SYSTEM::do_it (CS & cmd, CARD_LIST *) [inline, virtual]
Implements CMD.
Definition at line 59 of file c_system.cc.
References itested, CS::more(), SHELL, OS::system(), and CS::tail().
  {itested();
    if (cmd.more()) {itested();
      OS::system(cmd.tail());
    }else{
      OS::system(SHELL);
    }
  }
The documentation for this class was generated from the following file:
savant/gnucap/src/c_system.cc