gnucap: anonymous_namespace{lang_spice.cc}::LANG_SPICE Class Reference
anonymous_namespace{lang_spice.cc}::LANG_SPICE Class Reference
Public Member Functions
std::string name () const
bool case_insensitive () const
UNITS units () const
void parse_top_item (CS &, CARD_LIST *)
Detailed Description
Definition at line 78 of file lang_spice.cc.
Member Function Documentation
bool anonymous_namespace{lang_spice.cc}::LANG_SPICE::case_insensitive () const [inline, virtual]
Implements LANGUAGE.
Definition at line 81 of file lang_spice.cc.
{return true;}
std::string anonymous_namespace{lang_spice.cc}::LANG_SPICE::name () const [inline, virtual]
Implements LANGUAGE.
Definition at line 80 of file lang_spice.cc.
{return "spice";}
void anonymous_namespace{lang_spice.cc}::LANG_SPICE::parse_top_item (CS & cmd, CARD_LIST * Scope) [virtual]
Reimplemented from LANGUAGE.
Definition at line 661 of file lang_spice.cc.
References CARD_LIST::card_list, CS::fullstring(), CS::get_line(), head, CARD_LIST::is_empty(), CS::is_file(), CS::is_first_read(), itested, IO::mstdout, and untested.
{
  if (0 && cmd.is_file()
      && cmd.is_first_read()
      && (Scope == &CARD_LIST::card_list)
      && (Scope->is_empty())
      && (head == "'")) {untested();    //BUG// ugly hack
    cmd.get_line("gnucap-spice-title>");
    head = cmd.fullstring();
    IO::mstdout << head << '\n';
  }else{itested();
    cmd.get_line("gnucap-spice>");
    new__instance(cmd, NULL, Scope);
  }
}
UNITS anonymous_namespace{lang_spice.cc}::LANG_SPICE::units () const [inline, virtual]
Implements LANGUAGE.
Definition at line 82 of file lang_spice.cc.
References uSPICE.
{return uSPICE;}
The documentation for this class was generated from the following file:
savant/gnucap/src/lang_spice.cc