gnucap: anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM Class Reference
anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM Class Reference
Public Types
enum MODE { mDEFAULT, mPARAMSET }
enum { INACTIVE = -1 }
Public Member Functions
std::string name () const
bool case_insensitive () const
UNITS units () const
std::string arg_front () const
std::string arg_mid () const
std::string arg_back () const
void parse_top_item (CS &, CARD_LIST *)
DEV_COMMENT * parse_comment (CS &, DEV_COMMENT *)
DEV_DOT * parse_command (CS &, DEV_DOT *)
MODEL_CARD * parse_paramset (CS &, MODEL_CARD *)
MODEL_SUBCKT * parse_module (CS &, MODEL_SUBCKT *)
COMPONENT * parse_instance (CS &, COMPONENT *)
std::string find_type_in_string (CS &)
Public Attributes
enum anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::MODE _mode
int arg_count
std::vector< CARD * > nets
Private Member Functions
void print_paramset (OMSTREAM &, const MODEL_CARD *)
void print_module (OMSTREAM &, const MODEL_SUBCKT *)
void print_instance (OMSTREAM &, const COMPONENT *)
void print_comment (OMSTREAM &, const DEV_COMMENT *)
void print_command (OMSTREAM &o, const DEV_DOT *c)
void print_args (OMSTREAM &, const MODEL_CARD *)
void print_args (OMSTREAM &, const COMPONENT *)
Detailed Description
Definition at line 31 of file lang_gschem.cc.
Member Enumeration Documentation
anonymous enum
Enumerator:
INACTIVE
Definition at line 37 of file lang_gschem.cc.
{INACTIVE = -1};
enum anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::MODE
Enumerator:
mDEFAULT
mPARAMSET
Definition at line 35 of file lang_gschem.cc.
{mDEFAULT, mPARAMSET} _mode;
Member Function Documentation
std::string anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::arg_back () const [inline, virtual]
Implements LANGUAGE.
Definition at line 50 of file lang_gschem.cc.
{
        return "";  //arbitrary
    }
std::string anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::arg_front () const [inline, virtual]
Implements LANGUAGE.
Definition at line 44 of file lang_gschem.cc.
{
        return " "; //arbitrary
    }
std::string anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::arg_mid () const [inline, virtual]
Implements LANGUAGE.
Definition at line 47 of file lang_gschem.cc.
{
        return "="; //arbitrary
    }
bool anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::case_insensitive () const [inline, virtual]
Implements LANGUAGE.
Definition at line 40 of file lang_gschem.cc.
{return false;}
std::string anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::find_type_in_string (CS & cmd) [virtual]
Implements LANGUAGE.
Definition at line 261 of file lang_gschem.cc.
References CS::cursor(), and CS::reset().
Referenced by anonymous_namespace{lang_gschem.cc}::parse_component(), anonymous_namespace{lang_gschem.cc}::parse_net(), and anonymous_namespace{lang_gschem.cc}::parse_type().
{
    unsigned here = cmd.cursor(); //store cursor position to reset back later
    std::string type;   //stores type : should check device attribute..
    if (cmd >> "v" || cmd >> "L" || cmd >> "G" || cmd >> "B" || cmd >>"V" ||
        cmd >> "A" || cmd >> "H" || cmd >> "T"){ type="dev_comment";}
    else if (cmd >> "N"){ type="net";}
    else if (cmd >> "U"){ type="bus";}
    else if (cmd >> "P"){ type="pin";}
    else if (cmd >> "C"){ type="C";}
    else {  cmd >> type; } //Not matched with the type. What now?
    cmd.reset(here);//Reset cursor back to the position that
                    //has been started with at beginning
    return type;    // returns the type of the string
}
std::string anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::name () const [inline, virtual]
Implements LANGUAGE.
Definition at line 39 of file lang_gschem.cc.
{return "gschem";}
DEV_DOT * anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_command (CS & cmd, DEV_DOT * x) [virtual]
Implements LANGUAGE.
Definition at line 108 of file lang_gschem.cc.
References CARD_LIST::card_list, CMD::cmdproc(), CS::fullstring(), CARD::owner(), CS::reset(), DEV_DOT::set(), and CARD::subckt().
{
  assert(x);
  x->set(cmd.fullstring());
  CARD_LIST* scope = (x->owner()) ? x->owner()->subckt() : &CARD_LIST::card_list;
  cmd.reset();
  CMD::cmdproc(cmd, scope);
  delete x;
  return NULL;
}
DEV_COMMENT * anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_comment (CS & cmd, DEV_COMMENT * x) [virtual]
Implements LANGUAGE.
Definition at line 101 of file lang_gschem.cc.
References CS::fullstring(), and DEV_COMMENT::set().
{
  assert(x);
  x->set(cmd.fullstring());
  return x;
}
COMPONENT * anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_instance (CS & cmd, COMPONENT * x) [virtual]
Implements LANGUAGE.
Definition at line 231 of file lang_gschem.cc.
References CS::check(), CARD::dev_type(), anonymous_namespace{lang_gschem.cc}::parse_net(), anonymous_namespace{lang_gschem.cc}::parse_type(), and CS::reset().
{
  cmd.reset();
  parse_type(cmd, x); //parse type will parse the component type and set_dev_type
  if (x->dev_type()=="net") {
    parse_net(cmd,x);
  }
  cmd.check(bWARNING, "what's ins this?");
  return x;
}
MODEL_SUBCKT * anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_module (CS & cmd, MODEL_SUBCKT * x) [virtual]
Implements LANGUAGE.
Definition at line 127 of file lang_gschem.cc.
References CS::cursor(), CS::reset(), and CKT_BASE::set_label().
Referenced by anonymous_namespace{lang_gschem.cc}::CMD_C::do_it().
{
  assert(x);
  cmd.reset();
  std::string type = find_type_in_string(cmd);
  assert(type=="C");
  std::string component_x, component_y, mirror, angle, dump,basename;
  bool isgraphical=false;
  cmd>>"C";
  unsigned here=cmd.cursor();
  cmd>>component_x>>" ">>component_y>>" ">>dump>>" ">>angle>>" ">>mirror>>" ">>basename;
  //open the basename to get the ports and their placements
  //parse_ports(newcmd,x);
  x->set_label(basename);
  if (isgraphical==true) {
    return NULL;
  }
  else{
    cmd.reset(here);
  }
  return x;
}
MODEL_CARD* anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_paramset (CS & , MODEL_CARD *) [virtual]
Implements LANGUAGE.
void anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_top_item (CS & cmd, CARD_LIST * Scope) [virtual]
Reimplemented from LANGUAGE.
Definition at line 304 of file lang_gschem.cc.
References CS::get_line().
{
  cmd.get_line("gnucap-gschem>");
  new__instance(cmd, NULL, Scope);
  //for(CARD_LIST::const_iterator ci=Scope->begin();ci!= Scope->end();++ci) {
  //  std::cout<<(*ci)->dev_type()<<" "<<(*ci)->param_value(4)<<std::endl;
  //}
}
void anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::print_args (OMSTREAM & , const MODEL_CARD *) [private]
void anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::print_args (OMSTREAM & , const COMPONENT *) [private]
void anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::print_command (OMSTREAM & o, const DEV_DOT * c) [private, virtual]
Implements LANGUAGE.
void anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::print_comment (OMSTREAM & , const DEV_COMMENT *) [private, virtual]
Implements LANGUAGE.
void anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::print_instance (OMSTREAM & , const COMPONENT *) [private, virtual]
Implements LANGUAGE.
void anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::print_module (OMSTREAM & , const MODEL_SUBCKT *) [private, virtual]
Implements LANGUAGE.
void anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::print_paramset (OMSTREAM & , const MODEL_CARD *) [private, virtual]
Implements LANGUAGE.
UNITS anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::units () const [inline, virtual]
Implements LANGUAGE.
Definition at line 41 of file lang_gschem.cc.
References uSI.
{return uSI;}
Member Data Documentation
enum anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::MODE anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::_mode
int anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::arg_count [mutable]
Definition at line 36 of file lang_gschem.cc.
std::vector<CARD*> anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::nets
Definition at line 62 of file lang_gschem.cc.
The documentation for this class was generated from the following file:
savant/gnucap/src/lang_gschem.cc