gnucap: anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP Class Reference
anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP Class Reference
Public Member Functions
DEV_CPOLY_CAP ()
~DEV_CPOLY_CAP ()
void set_parameters (const std::string &Label, CARD *Parent, COMMON_COMPONENT *Common, double Value, int state_count, double state[], int node_count, const node_t nodes[])
Protected Member Functions
DEV_CPOLY_CAP (const DEV_CPOLY_CAP &p)
char id_letter () const
std::string value_name () const
std::string dev_type () const
int max_nodes () const
int min_nodes () const
int matrix_nodes () const
int net_nodes () const
CARD * clone () const
void tr_iwant_matrix ()
bool tr_needs_eval () const
bool do_tr ()
void tr_load ()
TIME_PAIR tr_review ()
void tr_unload ()
double tr_involts () const
double tr_involts_limited () const
double tr_amps () const
void ac_iwant_matrix ()
void ac_load ()
COMPLEX ac_involts () const
COMPLEX ac_amps () const
std::string port_name (int) const
bool do_tr_con_chk_and_q ()
Protected Attributes
double * _vy0
double * _vy1
double * _vi0
double * _vi1
int _n_ports
double _load_time
const double ** _inputs
Detailed Description
Definition at line 36 of file d_poly_cap.cc.
Constructor & Destructor Documentation
anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::DEV_CPOLY_CAP (const DEV_CPOLY_CAP & p) [explicit, protected]
Definition at line 102 of file d_poly_cap.cc.
References _inputs, _n_ports, _vi0, _vi1, _vy0, and _vy1.
  :STORAGE(p),
   _vy0(NULL),
   _vy1(NULL),
   _vi0(NULL),
   _vi1(NULL),
   _n_ports(p._n_ports),
   _load_time(NOT_VALID),
   _inputs(NULL)
{
  // not really a copy .. only valid to copy a default
  // too lazy to do it right, and that's all that is being used
  // to do it correctly requires a deep copy
  // just filling in defaults is better than a shallow copy, hence this:
  assert(!p._vy0);
  assert(!p._vy1);
  assert(!p._vi0);
  assert(!p._vi1);
  assert(p._n_ports == 0);
  assert(!p._inputs);
}
anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::DEV_CPOLY_CAP () [explicit]
Definition at line 124 of file d_poly_cap.cc.
  :STORAGE(),
   _vy0(NULL),
   _vy1(NULL),
   _vi0(NULL),
   _vi1(NULL),
   _n_ports(0),
   _load_time(NOT_VALID),
   _inputs(NULL)
{
}
anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::~DEV_CPOLY_CAP ()
Definition at line 136 of file d_poly_cap.cc.
References CARD::_n, _vi0, _vi1, _vy1, net_nodes(), NODES_PER_BRANCH, and untested.
{
  delete [] _vy1;
  delete [] _vi0;
  delete [] _vi1;
  if (net_nodes() > NODES_PER_BRANCH) {untested();
    delete [] _n;
  }else{
    // it is part of a base class
  }
}
Member Function Documentation
COMPLEX anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::ac_amps () const [inline, protected, virtual]
Reimplemented from ELEMENT.
Definition at line 71 of file d_poly_cap.cc.
References itested, and NOT_VALID.
{itested(); return NOT_VALID;}
COMPLEX anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::ac_involts () const [inline, protected, virtual]
Implements ELEMENT.
Definition at line 70 of file d_poly_cap.cc.
References itested, and NOT_VALID.
{itested(); return NOT_VALID;}
void anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::ac_iwant_matrix () [inline, protected, virtual]
Implements ELEMENT.
Definition at line 68 of file d_poly_cap.cc.
{ac_iwant_matrix_extended();}
void anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::ac_load () [protected, virtual]
Reimplemented from CARD.
Definition at line 233 of file d_poly_cap.cc.
References ELEMENT::_acg, SIM_DATA::_jomega, CARD::_n, _n_ports, CKT_BASE::_sim, _vy0, ELEMENT::ac_load_extended(), ELEMENT::ac_load_passive(), OUT1, and OUT2.
{
  _acg = _vy0[1] * _sim->_jomega;
  ac_load_passive();
  for (int i=2; i<=_n_ports; ++i) {
    ac_load_extended(_n[OUT1], _n[OUT2], _n[2*i-2], _n[2*i-1], _vy0[i] * _sim->_jomega);
  }
}
CARD* anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::clone () const [inline, protected, virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP.
Definition at line 58 of file d_poly_cap.cc.
References unreachable.
{unreachable();return new DEV_CPOLY_CAP(*this);}
std::string anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::dev_type () const [inline, protected, virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP.
Definition at line 53 of file d_poly_cap.cc.
References unreachable.
{unreachable(); return "cpoly_cap";}
bool anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::do_tr () [protected, virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP.
Definition at line 162 of file d_poly_cap.cc.
References ELEMENT::_m0, _vi0, do_tr_con_chk_and_q(), incomplete, and untested.
{untested();
  incomplete();
  _m0 = CPOLY1(0., _vi0[0], _vi0[1]);
  return do_tr_con_chk_and_q();
}
bool anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::do_tr_con_chk_and_q () [protected]
Definition at line 148 of file d_poly_cap.cc.
References _load_time, _n_ports, CKT_BASE::_sim, SIM_DATA::_time0, _vy0, _vy1, conchk(), COMPONENT::converged(), COMPONENT::q_load(), and COMPONENT::set_converged().
Referenced by do_tr(), and anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::do_tr().
{
  q_load();
  assert(_vy1);
  set_converged(conchk(_load_time, _sim->_time0));
  _load_time = _sim->_time0;
  for (int i=0; converged() && i<=_n_ports; ++i) {
    set_converged(conchk(_vy1[i], _vy0[i]));
  }
  set_converged();
  return converged();
}
char anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::id_letter () const [inline, protected, virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP.
Definition at line 51 of file d_poly_cap.cc.
References unreachable.
{unreachable(); return '\0';}
int anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::matrix_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 56 of file d_poly_cap.cc.
{return _n_ports*2;}
int anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::max_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 54 of file d_poly_cap.cc.
{return net_nodes();}
int anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::min_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 55 of file d_poly_cap.cc.
{return net_nodes();}
int anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::net_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 57 of file d_poly_cap.cc.
Referenced by set_parameters(), and ~DEV_CPOLY_CAP().
{return _n_ports*2;}
std::string anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::port_name (int) const [inline, protected, virtual]
Implements COMPONENT.
Definition at line 73 of file d_poly_cap.cc.
References incomplete, unreachable, and untested.
                                {untested();
    incomplete();
    unreachable();
    return "";
  }
void anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::set_parameters (const std::string & Label, CARD * Parent, COMMON_COMPONENT * Common, double Value, int state_count, double state[], int node_count, const node_t nodes[]) [virtual]
Reimplemented from COMPONENT.
Definition at line 244 of file d_poly_cap.cc.
References _inputs, CARD::_n, _n_ports, _vi0, _vi1, _vy0, _vy1, COMPONENT::attach_common(), notstd::copy_n(), itested, net_nodes(), NODES_PER_BRANCH, CKT_BASE::set_label(), CARD::set_owner(), COMPONENT::set_value(), and untested.
{
  bool first_time = (net_nodes() == 0);
  set_label(Label);
  set_owner(Owner);
  set_value(Value);
  attach_common(Common);
  if (first_time) {
    _n_ports = n_nodes/2; // sets num_nodes() = _n_ports*2
    assert(_n_ports == n_states-1);
    assert(!_vy1);
    assert(!_vi0);
    assert(!_vi1);
    _vy1 = new double[n_states];
    _vi0 = new double[n_states];
    _vi1 = new double[n_states];
    if (net_nodes() > NODES_PER_BRANCH) {untested();
      // allocate a bigger node list
      _n = new node_t[net_nodes()];
    }else{
      // use the default node list, already set
    }
  }else{itested();
    assert(_n_ports == n_states-1);
    assert(_vy1);
    assert(_vi0);
    assert(_vi1);
    assert(net_nodes() == n_nodes);
    // assert could fail if changing the number of nodes after a run
  }
  //_inputs = inputs;
  _inputs = 0;
  _vy0 = states;
  std::fill_n(_vy0, n_states, 0.);
  std::fill_n(_vy1, n_states, 0.);
  std::fill_n(_vi0, n_states, 0.);
  std::fill_n(_vi1, n_states, 0.);
  notstd::copy_n(nodes, net_nodes(), _n);
  assert(net_nodes() == _n_ports * 2);
}
double anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::tr_amps () const [protected, virtual]
Reimplemented from ELEMENT.
Definition at line 224 of file d_poly_cap.cc.
References ELEMENT::_m0, CARD::_n, _n_ports, _vi0, CPOLY1::c0, dn_diff(), and untested.
{untested();
  double amps = _m0.c0;
  for (int i=1; i<=_n_ports; ++i) {untested();
    amps += dn_diff(_n[2*i-2].v0(),_n[2*i-1].v0()) * _vi0[i];
  }
  return amps;
}
double anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::tr_involts () const [inline, protected, virtual]
Implements ELEMENT.
Definition at line 65 of file d_poly_cap.cc.
References NOT_VALID, and unreachable.
{unreachable(); return NOT_VALID;}
double anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::tr_involts_limited () const [inline, protected, virtual]
Implements ELEMENT.
Definition at line 66 of file d_poly_cap.cc.
References NOT_VALID, and unreachable.
{unreachable(); return NOT_VALID;}
void anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::tr_iwant_matrix () [inline, protected, virtual]
Implements ELEMENT.
Definition at line 59 of file d_poly_cap.cc.
{tr_iwant_matrix_extended();}
void anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::tr_load () [protected, virtual]
Reimplemented from CARD.
Definition at line 203 of file d_poly_cap.cc.
References CARD::_n, _n_ports, _vi0, _vi1, OUT1, OUT2, ELEMENT::tr_load_extended(), and ELEMENT::tr_load_passive().
Referenced by tr_unload().
{
  for (int i=0; i<=_n_ports; ++i) {
    assert(_vi0[i] == _vi0[i]);
  }
  tr_load_passive();
  _vi1[0] = _vi0[0];
  _vi1[1] = _vi0[1];
  for (int i=2; i<=_n_ports; ++i) {
    tr_load_extended(_n[OUT1], _n[OUT2], _n[2*i-2], _n[2*i-1], &(_vi0[i]), &(_vi1[i]));
  }
}
bool anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::tr_needs_eval () const [inline, protected, virtual]
Reimplemented from STORAGE.
Definition at line 60 of file d_poly_cap.cc.
{/*assert(!is_q_for_eval());*/ return true;}
TIME_PAIR anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::tr_review () [inline, protected, virtual]
Reimplemented from STORAGE.
Definition at line 63 of file d_poly_cap.cc.
References TIME_PAIR::reset().
{return _time_by.reset();}//BUG//review(_i0.f0, _it1.f0);}
void anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::tr_unload () [protected, virtual]
Reimplemented from CARD.
Definition at line 216 of file d_poly_cap.cc.
References ELEMENT::_m0, _n_ports, CKT_BASE::_sim, _vi0, CPOLY1::c0, CPOLY1::c1, SIM_DATA::mark_inc_mode_bad(), tr_load(), and untested.
{untested();
  std::fill_n(_vi0, _n_ports+1, 0.);
  _m0.c0 = _m0.c1 = 0.;
  _sim->mark_inc_mode_bad();
  tr_load();
}
std::string anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::value_name () const [inline, protected, virtual]
Implements CARD.
Definition at line 52 of file d_poly_cap.cc.
References incomplete.
{incomplete(); return "";}
Member Data Documentation
const double** anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::_inputs [protected]
Definition at line 44 of file d_poly_cap.cc.
Referenced by DEV_CPOLY_CAP(), anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::do_tr(), and set_parameters().
double anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::_load_time [protected]
Definition at line 43 of file d_poly_cap.cc.
Referenced by do_tr_con_chk_and_q().
int anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::_n_ports [protected]
Definition at line 42 of file d_poly_cap.cc.
Referenced by ac_load(), DEV_CPOLY_CAP(), anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::do_tr(), do_tr_con_chk_and_q(), set_parameters(), tr_amps(), tr_load(), and tr_unload().
double* anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::_vi0 [protected]
Definition at line 40 of file d_poly_cap.cc.
Referenced by DEV_CPOLY_CAP(), do_tr(), anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::do_tr(), set_parameters(), tr_amps(), tr_load(), tr_unload(), and ~DEV_CPOLY_CAP().
double* anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::_vi1 [protected]
Definition at line 41 of file d_poly_cap.cc.
Referenced by DEV_CPOLY_CAP(), set_parameters(), tr_load(), and ~DEV_CPOLY_CAP().
double* anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::_vy0 [protected]
Definition at line 38 of file d_poly_cap.cc.
Referenced by ac_load(), DEV_CPOLY_CAP(), anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::do_tr(), do_tr_con_chk_and_q(), and set_parameters().
double* anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::_vy1 [protected]
Definition at line 39 of file d_poly_cap.cc.
Referenced by DEV_CPOLY_CAP(), do_tr_con_chk_and_q(), set_parameters(), and ~DEV_CPOLY_CAP().
The documentation for this class was generated from the following file:
savant/gnucap/src/d_poly_cap.cc