gnucap: MODEL_SEMI_BASE Class Reference
MODEL_SEMI_BASE Class Reference
Public Attributes
PARAMETER< double > _narrow
PARAMETER< double > _defw
PARAMETER< double > _tc1
PARAMETER< double > _tc2
Protected Member Functions
MODEL_SEMI_BASE ()
MODEL_SEMI_BASE (const MODEL_SEMI_BASE &p)
void precalc_first ()
void set_param_by_index (int, std::string &, int)
bool param_is_printable (int) const
std::string param_name (int) const
std::string param_name (int, int) const
std::string param_value (int) const
int param_count () const
Static Private Attributes
static double const _default_narrow = 0.
static double const _default_defw = 1e-6
static double const _default_tc1 = 0.
static double const _default_tc2 = 0.
Detailed Description
Definition at line 87 of file bmm_semi.cc.
Constructor & Destructor Documentation
MODEL_SEMI_BASE::MODEL_SEMI_BASE () [explicit, protected]
Definition at line 348 of file bmm_semi.cc.
  :MODEL_CARD(NULL),
   _narrow(_default_narrow),
   _defw(_default_defw),
   _tc1(_default_tc1),
   _tc2(_default_tc2)
{
}
MODEL_SEMI_BASE::MODEL_SEMI_BASE (const MODEL_SEMI_BASE & p) [explicit, protected]
Definition at line 357 of file bmm_semi.cc.
  :MODEL_CARD(p),
   _narrow(p._narrow),
   _defw(p._defw),
   _tc1(p._tc1),
   _tc2(p._tc2)
{
}
Member Function Documentation
int MODEL_SEMI_BASE::param_count () const [inline, protected, virtual]
Reimplemented from MODEL_CARD.
Reimplemented in MODEL_SEMI_RESISTOR, and MODEL_SEMI_CAPACITOR.
Definition at line 110 of file bmm_semi.cc.
References MODEL_CARD::param_count().
Referenced by MODEL_SEMI_CAPACITOR::param_count(), MODEL_SEMI_RESISTOR::param_count(), param_is_printable(), param_name(), MODEL_SEMI_CAPACITOR::param_name(), MODEL_SEMI_RESISTOR::param_name(), param_value(), and set_param_by_index().
{return (4 + MODEL_CARD::param_count());}
bool MODEL_SEMI_BASE::param_is_printable (int i) const [protected, virtual]
Reimplemented from MODEL_CARD.
Reimplemented in MODEL_SEMI_RESISTOR, and MODEL_SEMI_CAPACITOR.
Definition at line 377 of file bmm_semi.cc.
References param_count().
{
  switch (MODEL_SEMI_BASE::param_count() - 1 - i) {
  case 0:
  case 1:
  case 2:
  case 3: return true;
  default: return MODEL_CARD::param_is_printable(i);
  }
}
std::string MODEL_SEMI_BASE::param_name (int i) const [protected, virtual]
Reimplemented from MODEL_CARD.
Reimplemented in MODEL_SEMI_RESISTOR, and MODEL_SEMI_CAPACITOR.
Definition at line 388 of file bmm_semi.cc.
References param_count().
Referenced by param_name().
{
  switch (MODEL_SEMI_BASE::param_count() - 1 - i) {
  case 0: return "narrow";
  case 1: return "defw";
  case 2: return "tc1";
  case 3: return "tc2";
  default: return MODEL_CARD::param_name(i);
  }
}
std::string MODEL_SEMI_BASE::param_name (int i, int j) const [protected, virtual]
Reimplemented from MODEL_CARD.
Reimplemented in MODEL_SEMI_RESISTOR, and MODEL_SEMI_CAPACITOR.
Definition at line 399 of file bmm_semi.cc.
References MODEL_CARD::param_count(), param_name(), and untested.
{
  if (j == 0) {untested();
    return param_name(i);
  }else if (i >= MODEL_CARD::param_count()) {
    return "";
  }else{
    return MODEL_CARD::param_name(i, j);
  }
}
std::string MODEL_SEMI_BASE::param_value (int i) const [protected, virtual]
Reimplemented from MODEL_CARD.
Reimplemented in MODEL_SEMI_RESISTOR, and MODEL_SEMI_CAPACITOR.
Definition at line 410 of file bmm_semi.cc.
References _defw, _narrow, _tc1, _tc2, param_count(), and PARAMETER< T >::string().
{
  switch (MODEL_SEMI_BASE::param_count() - 1 - i) {
  case 0: return _narrow.string();
  case 1: return _defw.string();
  case 2: return _tc1.string();
  case 3: return _tc2.string();
  default: return MODEL_CARD::param_value(i);
  }
}
void MODEL_SEMI_BASE::precalc_first () [protected, virtual]
Reimplemented from MODEL_CARD.
Reimplemented in MODEL_SEMI_RESISTOR, and MODEL_SEMI_CAPACITOR.
Definition at line 421 of file bmm_semi.cc.
References _default_defw, _default_narrow, _default_tc1, _default_tc2, _defw, _narrow, _tc1, _tc2, PARAMETER< T >::e_val(), and CARD::scope().
{
  MODEL_CARD::precalc_first();
  const CARD_LIST* s = scope();
  assert(s);
  _narrow.e_val(_default_narrow, s);
  _defw.e_val(_default_defw, s);
  _tc1.e_val(_default_tc1, s);
  _tc2.e_val(_default_tc2, s);
}
void MODEL_SEMI_BASE::set_param_by_index (int i, std::string & value, int offset) [protected, virtual]
Reimplemented from MODEL_CARD.
Reimplemented in MODEL_SEMI_RESISTOR, and MODEL_SEMI_CAPACITOR.
Definition at line 366 of file bmm_semi.cc.
References _defw, _narrow, _tc1, _tc2, and param_count().
{
  switch (MODEL_SEMI_BASE::param_count() - 1 - i) {
  case 0: _narrow = value; break;
  case 1: _defw = value; break;
  case 2: _tc1 = value; break;
  case 3: _tc2 = value; break;
  default: MODEL_CARD::set_param_by_index(i, value, offset); break;
  }
}
Member Data Documentation
double const MODEL_SEMI_BASE::_default_defw = 1e-6 [static, private]
Definition at line 95 of file bmm_semi.cc.
Referenced by precalc_first().
double const MODEL_SEMI_BASE::_default_narrow = 0. [static, private]
Definition at line 94 of file bmm_semi.cc.
Referenced by precalc_first().
double const MODEL_SEMI_BASE::_default_tc1 = 0. [static, private]
Definition at line 96 of file bmm_semi.cc.
Referenced by precalc_first().
double const MODEL_SEMI_BASE::_default_tc2 = 0. [static, private]
Definition at line 97 of file bmm_semi.cc.
Referenced by precalc_first().
PARAMETER<double> MODEL_SEMI_BASE::_defw
Definition at line 90 of file bmm_semi.cc.
Referenced by param_value(), precalc_first(), EVAL_BM_SEMI_CAPACITOR::precalc_last(), EVAL_BM_SEMI_RESISTOR::precalc_last(), and set_param_by_index().
PARAMETER<double> MODEL_SEMI_BASE::_narrow
Definition at line 89 of file bmm_semi.cc.
Referenced by param_value(), precalc_first(), EVAL_BM_SEMI_CAPACITOR::precalc_last(), EVAL_BM_SEMI_RESISTOR::precalc_last(), and set_param_by_index().
PARAMETER<double> MODEL_SEMI_BASE::_tc1
Definition at line 91 of file bmm_semi.cc.
Referenced by param_value(), precalc_first(), EVAL_BM_SEMI_CAPACITOR::precalc_last(), EVAL_BM_SEMI_RESISTOR::precalc_last(), and set_param_by_index().
PARAMETER<double> MODEL_SEMI_BASE::_tc2
Definition at line 92 of file bmm_semi.cc.
Referenced by param_value(), precalc_first(), EVAL_BM_SEMI_CAPACITOR::precalc_last(), EVAL_BM_SEMI_RESISTOR::precalc_last(), and set_param_by_index().
The documentation for this class was generated from the following file:
savant/gnucap/src/bmm_semi.cc