gnucap: savant/gnucap/src/u_prblst.cc File Reference
savant/gnucap/src/u_prblst.cc File Reference
#include "e_cardlist.h"
#include "e_node.h"
#include "e_card.h"
#include "u_nodemap.h"
#include "ap.h"
#include "u_prblst.h"
Functions
bool operator== (const PROBE &prb, const std::string &par)
bool operator!= (const PROBE &prb, const std::string &par)
bool operator== (const PROBE &prb, const CKT_BASE *brh)
bool operator!= (const PROBE &prb, const CKT_BASE *brh)
Function Documentation
bool operator!= (const PROBE & prb, const std::string & par)
Definition at line 69 of file u_prblst.cc.
References untested.
{untested();
  //return !wmatch(prb.label(), par);
  return !(prb == par);
}
bool operator!= (const PROBE & prb, const CKT_BASE * brh)
Definition at line 108 of file u_prblst.cc.
References PROBE::object(), and untested.
{untested();
  return (prb.object() != brh);
}
bool operator== (const PROBE & prb, const std::string & par)
Definition at line 65 of file u_prblst.cc.
References PROBE::label(), and wmatch().
{
  return wmatch(prb.label(), par);
}
bool operator== (const PROBE & prb, const CKT_BASE * brh)
Definition at line 104 of file u_prblst.cc.
References PROBE::object().
{
  return (prb.object() == brh);
}