gnucap: anonymous_namespace{c_genrat.cc}::CMD_ Class Reference
anonymous_namespace{c_genrat.cc}::CMD_ Class Reference
Public Member Functions
void do_it (CS &cmd, CARD_LIST *)
Detailed Description
Definition at line 44 of file c_genrat.cc.
Member Function Documentation
void anonymous_namespace{c_genrat.cc}::CMD_::do_it (CS & cmd, CARD_LIST *) [inline, virtual]
Implements CMD.
Definition at line 46 of file c_genrat.cc.
References ampl, CS::check(), CS::cursor(), delay, fall, freq, Get(), init_, maxv, minv, CS::more(), mPOSITIVE, IO::mstdout, offset, ONE_OF, period, phaz, rise, OMSTREAM::setfloatwidth(), CS::stuck(), and width.
  {
    OMSTREAM where = (cmd.more())  ?  OMSTREAM()  :  IO::mstdout;
    unsigned here = cmd.cursor();
    do{
      ONE_OF
        || ::Get(cmd, "f{requency}",&freq,   mPOSITIVE)
        || ::Get(cmd, "a{mplitude}",&ampl)
        || ::Get(cmd, "p{hase}",    &phaz)
        || ::Get(cmd, "ma{x}",      &maxv)
        || ::Get(cmd, "mi{n}",      &minv)
        || ::Get(cmd, "o{ffset}",   &offset)
        || ::Get(cmd, "i{nitial}",  &init_)
        || ::Get(cmd, "r{ise}",     &rise,   mPOSITIVE)
        || ::Get(cmd, "f{all}",     &fall,   mPOSITIVE)
        || ::Get(cmd, "d{elay}",    &delay,  mPOSITIVE)
        || ::Get(cmd, "w{idth}",    &width,  mPOSITIVE)
        || ::Get(cmd, "pe{riod}",   &period, mPOSITIVE)
        ;
    }while (cmd.more() && !cmd.stuck(&here));
    cmd.check(bWARNING, "what's this");
    where.setfloatwidth(7);
    where <<   "freq="  << freq;
    where << "  ampl="  << ampl;
    where << "  phase=" << phaz;
    where << "  max="   << maxv;
    where << "  min="   << minv;
    where << "  offset="<< offset;
    where << "  init="  << init_;
    where << "  rise="  << rise;
    where << "  fall="  << fall;
    where << "  delay=" << delay;
    where << "  width=" << width;
    where << "  period="<< period;
    where << "\n";
  }
The documentation for this class was generated from the following file:
savant/gnucap/src/c_genrat.cc