gnucap: MODEL_BUILT_IN_MOS6 Class Reference
MODEL_BUILT_IN_MOS6 Class Reference
#include <d_mos6.h>
Public Member Functions
MODEL_BUILT_IN_MOS6 (const BASE_SUBCKT *)
~MODEL_BUILT_IN_MOS6 ()
std::string dev_type () const
void set_dev_type (const std::string &nt)
CARD * clone () const
void precalc_first ()
void precalc_last ()
SDP_CARD * new_sdp (COMMON_COMPONENT *c) const
void set_param_by_index (int, std::string &, int)
bool param_is_printable (int) const
std::string param_name (int) const
std::string param_name (int, int) const
std::string param_value (int) const
int param_count () const
bool is_valid (const COMPONENT *) const
void tr_eval (COMPONENT *) const
Static Public Member Functions
static int count ()
Public Attributes
PARAMETER< double > kv
PARAMETER< double > nv
PARAMETER< double > kc
PARAMETER< double > nc
PARAMETER< double > nvth
PARAMETER< double > ps
PARAMETER< double > gamma1
PARAMETER< double > sigma
PARAMETER< double > lambda0
PARAMETER< double > lambda1
bool calc_kc
Protected Member Functions
MODEL_BUILT_IN_MOS6 (const MODEL_BUILT_IN_MOS6 &p)
Static Private Attributes
static int _count = 0
Detailed Description
Definition at line 53 of file d_mos6.h.
Constructor & Destructor Documentation
MODEL_BUILT_IN_MOS6::MODEL_BUILT_IN_MOS6 (const MODEL_BUILT_IN_MOS6 & p) [explicit, protected]
Definition at line 111 of file d_mos6.cc.
References _count, rPRE_MAIN, ENV::run_mode, and untested.
Referenced by clone().
  :MODEL_BUILT_IN_MOS123(p),
   kv(p.kv),
   nv(p.nv),
   kc(p.kc),
   nc(p.nc),
   nvth(p.nvth),
   ps(p.ps),
   gamma1(p.gamma1),
   sigma(p.sigma),
   lambda0(p.lambda0),
   lambda1(p.lambda1),
   calc_kc(p.calc_kc)
{
  if (ENV::run_mode != rPRE_MAIN) {
    ++_count;
  }else{untested();//194
  }
}
MODEL_BUILT_IN_MOS6::MODEL_BUILT_IN_MOS6 (const BASE_SUBCKT * p) [explicit]
Definition at line 85 of file d_mos6.cc.
References _count, MODEL_BUILT_IN_MOS123::cox, MODEL_BUILT_IN_MOS123::gamma, LEVEL(), MODEL_BUILT_IN_DIODE::mjsw, MODEL_BUILT_IN_DIODE::mos_level, NA(), MODEL_BUILT_IN_MOS123::phi, rPRE_MAIN, ENV::run_mode, set_default(), and MODEL_BUILT_IN_MOS123::vto.
  :MODEL_BUILT_IN_MOS123(p),
   kv(2.0),
   nv(0.5),
   kc(NA),
   nc(1.0),
   nvth(0.5),
   ps(0.0),
   gamma1(0.0),
   sigma(0.0),
   lambda0(0.0),
   lambda1(0.0),
   calc_kc(false)
{
  if (ENV::run_mode != rPRE_MAIN) {
    ++_count;
  }else{
  }
  set_default(&mjsw, .5);
  set_default(&cox, NA);
  set_default(&vto, NA);
  set_default(&gamma, NA);
  set_default(&phi, NA);
  set_default(&mos_level, LEVEL);
}
MODEL_BUILT_IN_MOS6::~MODEL_BUILT_IN_MOS6 () [inline]
Definition at line 59 of file d_mos6.h.
References _count.
{--_count;}
Member Function Documentation
CARD* MODEL_BUILT_IN_MOS6::clone () const [inline, virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 63 of file d_mos6.h.
References MODEL_BUILT_IN_MOS6().
{return new MODEL_BUILT_IN_MOS6(*this);}
static int MODEL_BUILT_IN_MOS6::count () [inline, static]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 76 of file d_mos6.h.
References _count.
{return _count;}
std::string MODEL_BUILT_IN_MOS6::dev_type () const [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 131 of file d_mos6.cc.
References pN, MODEL_BUILT_IN_MOS_BASE::polarity, pP, and untested.
{
  if (polarity == pN) {
    return "nmos6";
  }else if (polarity == pP) {
    return "pmos6";
  }else{untested();//235
    return MODEL_BUILT_IN_MOS123::dev_type();
  }
}
bool MODEL_BUILT_IN_MOS6::is_valid (const COMPONENT * d) const [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 389 of file d_mos6.cc.
{
  assert(d);
  return MODEL_BUILT_IN_MOS123::is_valid(d);
}
SDP_CARD * MODEL_BUILT_IN_MOS6::new_sdp (COMMON_COMPONENT * c) const [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 240 of file d_mos6.cc.
{
  assert(c);
  if (COMMON_BUILT_IN_MOS* cc = dynamic_cast<COMMON_BUILT_IN_MOS*>(c)) {
    if (cc->_sdp) {
      cc->_sdp->init(cc);
      return cc->_sdp;
    }else{
      delete cc->_sdp;
      return new SDP_BUILT_IN_MOS6(c);
    }
  }else{
    return MODEL_BUILT_IN_MOS123::new_sdp(c);
  }
}
int MODEL_BUILT_IN_MOS6::param_count () const [inline, virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 72 of file d_mos6.h.
References MODEL_BUILT_IN_MOS123::param_count().
Referenced by param_is_printable(), param_name(), param_value(), and set_param_by_index().
{return (18 + MODEL_BUILT_IN_MOS123::param_count());}
bool MODEL_BUILT_IN_MOS6::param_is_printable (int i) const [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 281 of file d_mos6.cc.
References calc_kc, LEVEL(), MODEL_BUILT_IN_DIODE::mos_level, and param_count().
{
  switch (MODEL_BUILT_IN_MOS6::param_count() - 1 - i) {
  case 0:  return (true);
  case 1:  return (true);
  case 2:  return (false);
  case 3:  return (false);
  case 4:  return (false);
  case 5:  return (false);
  case 6:  return (false);
  case 7:  return (mos_level != LEVEL);
  case 8:  return (true);
  case 9:  return (true);
  case 10:  return (!calc_kc);
  case 11:  return (true);
  case 12:  return (true);
  case 13:  return (true);
  case 14:  return (true);
  case 15:  return (true);
  case 16:  return (true);
  case 17:  return (true);
  default: return MODEL_BUILT_IN_MOS123::param_is_printable(i);
  }
}
std::string MODEL_BUILT_IN_MOS6::param_name (int i) const [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 306 of file d_mos6.cc.
References param_count().
Referenced by param_name().
{
  switch (MODEL_BUILT_IN_MOS6::param_count() - 1 - i) {
  case 0:  return "level";
  case 1:  return "lambda";
  case 2:  return "=====";
  case 3:  return "=====";
  case 4:  return "=====";
  case 5:  return "=====";
  case 6:  return "=====";
  case 7:  return "diodelevel";
  case 8:  return "kv";
  case 9:  return "nv";
  case 10:  return "kc";
  case 11:  return "nc";
  case 12:  return "nvth";
  case 13:  return "ps";
  case 14:  return "gamma1";
  case 15:  return "sigma";
  case 16:  return "lambda0";
  case 17:  return "lambda1";
  default: return MODEL_BUILT_IN_MOS123::param_name(i);
  }
}
std::string MODEL_BUILT_IN_MOS6::param_name (int i, int j) const [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 331 of file d_mos6.cc.
References param_count(), and param_name().
{
  if (j == 0) {
    return param_name(i);
  }else if (j == 1) {
    switch (MODEL_BUILT_IN_MOS6::param_count() - 1 - i) {
    case 0:  return "";
    case 1:  return "";
    case 2:  return "";
    case 3:  return "";
    case 4:  return "";
    case 5:  return "";
    case 6:  return "";
    case 7:  return "";
    case 8:  return "";
    case 9:  return "";
    case 10:  return "";
    case 11:  return "";
    case 12:  return "";
    case 13:  return "";
    case 14:  return "";
    case 15:  return "";
    case 16:  return "";
    case 17:  return "";
    default: return MODEL_BUILT_IN_MOS123::param_name(i, j);
    }
  }else if (i < 18) {
    return "";
  }else{
    return MODEL_BUILT_IN_MOS123::param_name(i, j);
  }
}
std::string MODEL_BUILT_IN_MOS6::param_value (int i) const [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 364 of file d_mos6.cc.
References gamma1, kc, kv, lambda0, lambda1, MODEL_BUILT_IN_DIODE::mos_level, nc, nv, nvth, param_count(), ps, sigma, PARAMETER< T >::string(), and unreachable.
{
  switch (MODEL_BUILT_IN_MOS6::param_count() - 1 - i) {
  case 0:  return "6";
  case 1:  return lambda0.string();
  case 2:  unreachable(); return "";
  case 3:  unreachable(); return "";
  case 4:  unreachable(); return "";
  case 5:  unreachable(); return "";
  case 6:  unreachable(); return "";
  case 7:  return mos_level.string();
  case 8:  return kv.string();
  case 9:  return nv.string();
  case 10:  return kc.string();
  case 11:  return nc.string();
  case 12:  return nvth.string();
  case 13:  return ps.string();
  case 14:  return gamma1.string();
  case 15:  return sigma.string();
  case 16:  return lambda0.string();
  case 17:  return lambda1.string();
  default: return MODEL_BUILT_IN_MOS123::param_value(i);
  }
}
void MODEL_BUILT_IN_MOS6::precalc_first () [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 153 of file d_mos6.cc.
References CKT_BASE::_sim, MODEL_BUILT_IN_MOS123::calc_gamma, calc_kc, MODEL_BUILT_IN_MOS123::calc_phi, MODEL_BUILT_IN_MOS123::calc_vto, MODEL_BUILT_IN_MOS123::cox, e_val(), MODEL_BUILT_IN_MOS_BASE::egap, error(), MODEL_BUILT_IN_MOS123::gamma, gamma1, gtMETAL, SIM_DATA::is_first_expand(), kc, kv, lambda0, lambda1, CARD::long_label(), NA(), nc, NI, MODEL_BUILT_IN_MOS123::nss, MODEL_BUILT_IN_MOS123::nsub, nv, nvth, P_EPS_OX, P_EPS_SI, P_K_Q, P_Q, MODEL_BUILT_IN_MOS123::phi, MODEL_BUILT_IN_MOS_BASE::polarity, ps, CARD::scope(), sigma, MODEL_BUILT_IN_MOS_BASE::tnom_k, MODEL_BUILT_IN_MOS123::tox, MODEL_BUILT_IN_MOS123::tpg, untested, MODEL_BUILT_IN_MOS123::uo, and MODEL_BUILT_IN_MOS123::vto.
{
    const CARD_LIST* par_scope = scope();
    assert(par_scope);
    MODEL_BUILT_IN_MOS123::precalc_first();
    e_val(&(this->kv), 2.0, par_scope);
    e_val(&(this->nv), 0.5, par_scope);
    e_val(&(this->kc), NA, par_scope);
    e_val(&(this->nc), 1.0, par_scope);
    e_val(&(this->nvth), 0.5, par_scope);
    e_val(&(this->ps), 0.0, par_scope);
    e_val(&(this->gamma1), 0.0, par_scope);
    e_val(&(this->sigma), 0.0, par_scope);
    e_val(&(this->lambda0), 0.0, par_scope);
    e_val(&(this->lambda1), 0.0, par_scope);
    // final adjust: code_pre
      if (tox != NA) {
        cox = P_EPS_OX / tox;
        if (kc == NA) {
          kc = .5 * uo * cox;
          calc_kc = true;
        }
        if (nsub != NA) {
          if (phi == NA) {
            phi = (2. * P_K_Q) * tnom_k * log(nsub/NI);
            if (phi < .1) {
              untested();
              error(((!_sim->is_first_expand()) ? (bDEBUG) : (bWARNING)),
                    long_label() + ": calculated phi too small, using .1\n");
              phi = .1;
            }
            calc_phi = true;
          }
          if (gamma == NA) {
            gamma = sqrt(2. * P_EPS_SI * P_Q * nsub) / cox;
            calc_gamma = true;
          }
          if (vto == NA) {
            double phi_ms = (tpg == gtMETAL)
              ? polarity * (-.05 - (egap + polarity * phi) / 2.)
              : -(tpg * egap + phi) / 2.;
            double vfb = phi_ms - polarity * P_Q * nss / cox;
            vto = vfb + phi + gamma * sqrt(phi);
            calc_vto = true;
          }
        }
      }
    // final adjust: override
    if (cox == NA) {
      cox = 0.;
    }else{
    }
    if (vto == NA) {
      vto = 0.;
    }else{
    }
    if (gamma == NA) {
      gamma = 0.;
    }else{
    }
    if (phi == NA) {
      phi = .6;
    }else{
    }
    // final adjust: raw
    e_val(&(this->kv), 2.0, par_scope);
    e_val(&(this->nv), 0.5, par_scope);
    e_val(&(this->kc), 5e-5, par_scope);
    e_val(&(this->nc), 1.0, par_scope);
    e_val(&(this->nvth), 0.5, par_scope);
    e_val(&(this->ps), 0.0, par_scope);
    e_val(&(this->gamma1), 0.0, par_scope);
    e_val(&(this->sigma), 0.0, par_scope);
    e_val(&(this->lambda0), 0.0, par_scope);
    e_val(&(this->lambda1), 0.0, par_scope);
    // final adjust: mid
    // final adjust: calculated
    // final adjust: post
    // final adjust: done
}
void MODEL_BUILT_IN_MOS6::precalc_last () [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 235 of file d_mos6.cc.
{
    MODEL_BUILT_IN_MOS123::precalc_last();
}
void MODEL_BUILT_IN_MOS6::set_dev_type (const std::string & nt) [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 142 of file d_mos6.cc.
References pN, MODEL_BUILT_IN_MOS_BASE::polarity, pP, and Umatch().
{
  if (Umatch(new_type, "nmos6 ")) {
    polarity = pN;
  }else if (Umatch(new_type, "pmos6 ")) {
    polarity = pP;
  }else{
    MODEL_BUILT_IN_MOS123::set_dev_type(new_type);
  }
}
void MODEL_BUILT_IN_MOS6::set_param_by_index (int i, std::string & value, int offset) [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 256 of file d_mos6.cc.
References gamma1, kc, kv, lambda0, lambda1, MODEL_BUILT_IN_MOS_BASE::level, MODEL_BUILT_IN_DIODE::mos_level, nc, nv, nvth, param_count(), ps, sigma, and unreachable.
{
  switch (MODEL_BUILT_IN_MOS6::param_count() - 1 - i) {
  case 0: level = value; break; //6
  case 1: lambda0 = value; break;
  case 2: unreachable(); break;
  case 3: unreachable(); break;
  case 4: unreachable(); break;
  case 5: unreachable(); break;
  case 6: unreachable(); break;
  case 7: mos_level = value; break;
  case 8: kv = value; break;
  case 9: nv = value; break;
  case 10: kc = value; break;
  case 11: nc = value; break;
  case 12: nvth = value; break;
  case 13: ps = value; break;
  case 14: gamma1 = value; break;
  case 15: sigma = value; break;
  case 16: lambda0 = value; break;
  case 17: lambda1 = value; break;
  default: MODEL_BUILT_IN_MOS123::set_param_by_index(i, value, offset); break;
  }
}
void MODEL_BUILT_IN_MOS6::tr_eval (COMPONENT * brh) const [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 395 of file d_mos6.cc.
References TDP_BUILT_IN_MOS6::beta, COMPONENT::common(), DEV_BUILT_IN_MOS::cutoff, MODEL_BUILT_IN_MOS123::gamma, gamma1, DEV_BUILT_IN_MOS::gds, DEV_BUILT_IN_MOS::gmbf, DEV_BUILT_IN_MOS::gmbr, DEV_BUILT_IN_MOS::gmf, DEV_BUILT_IN_MOS::gmr, DEV_BUILT_IN_MOS::ids, kv, lambda0, lambda1, CARD::long_label(), nc, nv, TDP_BUILT_IN_MOS6::phi, prechecked_cast, DEV_BUILT_IN_MOS::reverse_if_needed(), DEV_BUILT_IN_MOS::reversed, DEV_BUILT_IN_MOS::saturated, DEV_BUILT_IN_MOS::sbfwd, COMMON_BUILT_IN_MOS::sdp(), sigma, trace1, trace3, trace4, untested, TDP_BUILT_IN_MOS6::vbi, DEV_BUILT_IN_MOS::vbs, DEV_BUILT_IN_MOS::vds, DEV_BUILT_IN_MOS::vdsat, DEV_BUILT_IN_MOS::vgs, DEV_BUILT_IN_MOS::vgst, and DEV_BUILT_IN_MOS::von.
{
  DEV_BUILT_IN_MOS* d = prechecked_cast<DEV_BUILT_IN_MOS*>(brh);
  assert(d);
  const COMMON_BUILT_IN_MOS* c = prechecked_cast<const COMMON_BUILT_IN_MOS*>(d->common());
  assert(c);
  const SDP_BUILT_IN_MOS6* s = prechecked_cast<const SDP_BUILT_IN_MOS6*>(c->sdp());
  assert(s);
  const MODEL_BUILT_IN_MOS6* m = this;
  const TDP_BUILT_IN_MOS6 T(d);
  const TDP_BUILT_IN_MOS6* t = &T;
    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */
    trace1(d->long_label().c_str(), d->evaliter());
    trace3("", d->vds, d->vgs, d->vbs);
    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */
    d->reverse_if_needed();
    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */
    double sarg;
    if (d->vbs <= 0.) {
      d->sbfwd = false;
      sarg = sqrt(t->phi - d->vbs);
    }else{
      d->sbfwd = true;
      sarg = sqrt(t->phi);
      sarg = sarg - d->vbs / (sarg+sarg);
      if (sarg < 0.) {
        untested();
        sarg = 0.;
      }else{
        untested();
      }
    }
    trace3("", t->phi, d->vbs, sarg);
    assert(sarg >= 0.);
    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */
    trace4("", d->vds, t->vbi, m->gamma, m->gamma1);
    d->von = t->vbi + m->gamma * sarg - m->gamma1 * d->vbs;
    // - m->sigma  * d->vds;  // what is this?????
    d->vgst = d->vgs - d->von;
    trace3("", d->vds, d->von, d->vgst);
    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */
    d->cutoff = (d->vgst <= 0.);
    if (d->cutoff) {
      d->vdsat = 0.;
      d->ids = d->gmf = d->gds = d->gmbf = 0.;
      trace4("cut", d->ids, d->gmf, d->gds, d->gmbf);
    }else{
      double vonbm;
      if (d->vbs <= 0.) {
        vonbm = m->gamma1 + m->gamma / (sarg + sarg);
      }else{
        vonbm = m->gamma1 + m->gamma * .5 / sqrt(t->phi);
        untested();
      }
      trace3("", m->nc, m->lambda0, m->lambda1);
      double logvgon = log(d->vgst);
      double idsat = t->beta * exp(logvgon * m->nc);
      double Lambda = m->lambda0 - m->lambda1 * d->vbs;
      trace4("", vonbm, logvgon, idsat, Lambda);
      d->ids = idsat * (1 + Lambda * d->vds);
      d->gmf  = d->ids * m->nc / d->vgst;
      d->gds = d->gmf * m->sigma + idsat * Lambda;
      d->gmbf = d->gmf * vonbm - idsat * m->lambda1 * d->vds;
      d->vdsat = m->kv * exp(logvgon * m->nv);
      trace4("sat", d->ids, d->gmf, d->gds, d->gmbf);
      d->saturated = (d->vdsat <= d->vds);
      if (!d->saturated) {
        double vdst   = d->vds / d->vdsat;
        double vdst2  = (2 - vdst) * vdst;
        double vdstg  = - vdst * m->nv / d->vgst;
        double ivdst1 = d->ids * (2 - vdst - vdst);
        d->ids *= vdst2;
        d->gmf  = d->gmf  * vdst2 + ivdst1 * vdstg;
        d->gds = d->gds * vdst2 + ivdst1 * (1 / d->vdsat + vdstg * m->sigma);
        d->gmbf = d->gmbf * vdst2 + ivdst1 * vdstg * vonbm;
        trace4("lin", d->ids, d->gmf, d->gds, d->gmbf);
      }
    }
    if (d->reversed) {
      d->ids *= -1;
      d->gmr = d->gmf;
      d->gmbr = d->gmbf;
      d->gmf = d->gmbf = 0;
    }else{
      d->gmr = d->gmbr = 0.;
    }
}
Member Data Documentation
int MODEL_BUILT_IN_MOS6::_count = 0 [static, private]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 78 of file d_mos6.h.
Referenced by count(), MODEL_BUILT_IN_MOS6(), and ~MODEL_BUILT_IN_MOS6().
bool MODEL_BUILT_IN_MOS6::calc_kc
Definition at line 91 of file d_mos6.h.
Referenced by param_is_printable(), and precalc_first().
PARAMETER<double> MODEL_BUILT_IN_MOS6::gamma1
Definition at line 86 of file d_mos6.h.
Referenced by param_value(), precalc_first(), set_param_by_index(), and tr_eval().
PARAMETER<double> MODEL_BUILT_IN_MOS6::kc
Definition at line 82 of file d_mos6.h.
Referenced by param_value(), precalc_first(), set_param_by_index(), and TDP_BUILT_IN_MOS6::TDP_BUILT_IN_MOS6().
PARAMETER<double> MODEL_BUILT_IN_MOS6::kv
Definition at line 80 of file d_mos6.h.
Referenced by param_value(), precalc_first(), set_param_by_index(), and tr_eval().
PARAMETER<double> MODEL_BUILT_IN_MOS6::lambda0
Definition at line 88 of file d_mos6.h.
Referenced by param_value(), precalc_first(), set_param_by_index(), and tr_eval().
PARAMETER<double> MODEL_BUILT_IN_MOS6::lambda1
Definition at line 89 of file d_mos6.h.
Referenced by param_value(), precalc_first(), set_param_by_index(), and tr_eval().
PARAMETER<double> MODEL_BUILT_IN_MOS6::nc
Definition at line 83 of file d_mos6.h.
Referenced by param_value(), precalc_first(), set_param_by_index(), and tr_eval().
PARAMETER<double> MODEL_BUILT_IN_MOS6::nv
Definition at line 81 of file d_mos6.h.
Referenced by param_value(), precalc_first(), set_param_by_index(), and tr_eval().
PARAMETER<double> MODEL_BUILT_IN_MOS6::nvth
Definition at line 84 of file d_mos6.h.
Referenced by param_value(), precalc_first(), and set_param_by_index().
PARAMETER<double> MODEL_BUILT_IN_MOS6::ps
Definition at line 85 of file d_mos6.h.
Referenced by param_value(), precalc_first(), and set_param_by_index().
PARAMETER<double> MODEL_BUILT_IN_MOS6::sigma
Definition at line 87 of file d_mos6.h.
Referenced by param_value(), precalc_first(), set_param_by_index(), and tr_eval().
The documentation for this class was generated from the following files:
savant/gnucap/src/d_mos6.h
savant/gnucap/src/d_mos6.cc