gnucap: anonymous_namespace{lang_spice.cc} Namespace Reference
anonymous_namespace{lang_spice.cc} Namespace Reference
Classes
class LANG_SPICE_BASE
class LANG_SPICE
class LANG_ACS
class CMD_MODEL
class CMD_SUBCKT
class CMD_LIB
class CMD_INCLUDE
class CMD_MERGE
class CMD_RUN
class CMD_GET
class CMD_BUILD
class CMD_SPICE
class CMD_ACS
class CMD_ENDC
class CMD_CONTROL
Enumerations
enum Skip_Header { NO_HEADER, SKIP_HEADER }
Functions
DISPATCHER< LANGUAGE >
::INSTALL ds & language_dispatcher (),&lang_spice
static void skip_pre_stuff (CS &cmd)
static int count_ports (CS &cmd, int maxnodes, int minnodes, int leave_tail, int start)
static char fix_case (char c)
static void getmerge (CS &cmd, Skip_Header skip_header, CARD_LIST *Scope)
Variables
anonymous_namespace{lang_spice.cc}::LANG_SPICE lang_spice
anonymous_namespace{lang_spice.cc}::LANG_ACS lang_acs
DEV_COMMENT p0
DISPATCHER< CARD >::INSTALL d0 & device_dispatcher
anonymous_namespace{lang_spice.cc}::CMD_MODEL p1
DISPATCHER< CMD >::INSTALL d1 & command_dispatcher
anonymous_namespace{lang_spice.cc}::CMD_SUBCKT p2
anonymous_namespace{lang_spice.cc}::CMD_LIB p33
anonymous_namespace{lang_spice.cc}::CMD_INCLUDE p3
anonymous_namespace{lang_spice.cc}::CMD_MERGE p4
anonymous_namespace{lang_spice.cc}::CMD_RUN p5
anonymous_namespace{lang_spice.cc}::CMD_GET p6
anonymous_namespace{lang_spice.cc}::CMD_BUILD p7
anonymous_namespace{lang_spice.cc}::CMD_SPICE p8
anonymous_namespace{lang_spice.cc}::CMD_ACS p9
anonymous_namespace{lang_spice.cc}::CMD_ENDC p88
anonymous_namespace{lang_spice.cc}::CMD_CONTROL p99
Enumeration Type Documentation
enum anonymous_namespace{lang_spice.cc}::Skip_Header
Enumerator:
NO_HEADER
SKIP_HEADER
Definition at line 866 of file lang_spice.cc.
{NO_HEADER, SKIP_HEADER};
Function Documentation
static int anonymous_namespace{lang_spice.cc}::count_ports (CS & cmd, int maxnodes, int minnodes, int leave_tail, int start) [static]
Definition at line 115 of file lang_spice.cc.
References CS::cursor(), CS::is_end(), CS::reset(), and CS::skip1b().
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_element_using_obsolete_callback(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_instance(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_logic_using_obsolete_callback(), and anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_module().
{
  assert(start < maxnodes);
  assert(minnodes <= maxnodes);
  int num_nodes = 0;
  std::vector<unsigned> spots;
  int paren = cmd.skip1b('(');
  int i = start;
  // loop over the tokens to try to guess where the nodes end
  // and other stuff begins
  spots.push_back(cmd.cursor());
  for (;;) {
    ++i;
    //cmd.skiparg();
    std::string node_name;
    cmd >> node_name;
    spots.push_back(cmd.cursor());
    if (paren && cmd.skip1b(')')) {
      num_nodes = i;
      break;
    }else if (cmd.is_end()) {
      // found the end, no '='
      if (i <= minnodes) {
        num_nodes = i;
      }else if (i <= minnodes + leave_tail) {
        num_nodes = minnodes;
      }else if (i <= maxnodes + leave_tail) {
        num_nodes = i - leave_tail;
      }else{
        num_nodes = maxnodes;
      }
      break;
    }else if (cmd.skip1b("({})")) {
      // found '(', it's past the end of nodes
      if (i > maxnodes + leave_tail) {
        num_nodes = maxnodes;
      }else{
        num_nodes = i - leave_tail;
      }
      break;
    }else if (cmd.skip1b('=')) {
      // found '=', it's past the end of nodes
      if (i > maxnodes + leave_tail + 1) {
        num_nodes = maxnodes;
      }else{
        num_nodes = i - leave_tail - 1;
      }
      break;
    }else{
    }
  }
  if (num_nodes < start) {
    cmd.reset(spots.back());
    throw Exception("what's this?");
  }else{
  }
  cmd.reset(spots[static_cast<unsigned>(num_nodes-start)]);
  //cmd.warn(bDANGER, "past-nodes?");
  //BUG// assert fails on current controlled sources with (node node dev) syntax
  // it's ok with (node node) dev syntax or node node dev syntax
  assert(num_nodes <= maxnodes);
  return num_nodes;
}
static char anonymous_namespace{lang_spice.cc}::fix_case (char c) [static]
Definition at line 678 of file lang_spice.cc.
References OPT::case_insensitive.
{
  return ((OPT::case_insensitive) ? (static_cast<char>(tolower(c))) : (c));
}
static void anonymous_namespace{lang_spice.cc}::getmerge (CS & cmd, Skip_Header skip_header, CARD_LIST * Scope) [static]
Definition at line 870 of file lang_spice.cc.
References CS::_INC_FILE, CS::check(), CS::cursor(), CS::fullstring(), STATUS::get, Get(), CS::get_line(), head, lang_spice, CS::more(), IO::mstdout, anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::NO_EXIT_ON_BLANK, ONE_OF, anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_module_body(), TIMER::reset(), TIMER::start(), status, TIMER::stop(), CS::stuck(), CS::umatch(), and untested.
Referenced by anonymous_namespace{lang_spice.cc}::CMD_LIB::do_it(), anonymous_namespace{lang_spice.cc}::CMD_INCLUDE::do_it(), anonymous_namespace{lang_spice.cc}::CMD_MERGE::do_it(), anonymous_namespace{lang_spice.cc}::CMD_RUN::do_it(), and anonymous_namespace{lang_spice.cc}::CMD_GET::do_it().
{
  ::status.get.reset().start();
  assert(Scope);
  std::string file_name, section_name;
  cmd >> file_name;
  bool  echoon = false;         /* echo on/off flag (echo as read from file) */
  bool  liston = false;         /* list on/off flag (list actual values) */
  bool  quiet = false;          /* don't echo title */
  unsigned here = cmd.cursor();
  do{
    ONE_OF
      || Get(cmd, "echo",  &echoon)
      || Get(cmd, "list",  &liston)
      || Get(cmd, "quiet", &quiet)
      || Get(cmd, "section", &section_name)
      ;
  }while (cmd.more() && !cmd.stuck(&here));
  if (cmd.more()) {
    cmd >> section_name;
  }else{
  }
  cmd.check(bWARNING, "need section, echo, list, or quiet");
  CS file(CS::_INC_FILE, file_name);
  if (skip_header) { // get and store the header line
    file.get_line(">>>>");
    head = file.fullstring();
    if (!quiet) {
      IO::mstdout << head << '\n';
    }else{untested();
    }
  }else{
  }
  if (section_name == "") {
    lang_spice.parse_module_body(file, NULL, Scope, ">>>>", lang_spice.NO_EXIT_ON_BLANK, ".end ");
  }else{
    try {
      for (;;) {
        file.get_line("lib " + section_name + '>');
        if (file.umatch(".lib " + section_name + ' ')) {
          lang_spice.parse_module_body(file, NULL, Scope, section_name,
                        lang_spice.NO_EXIT_ON_BLANK, ".endl {" + section_name + "}");
        }else{
          // skip it
        }
      }
    }catch (Exception_End_Of_Input& e) {
    }
  }
  ::status.get.stop();
}
DISPATCHER< LANGUAGE >::INSTALL da & anonymous_namespace{lang_spice.cc}::language_dispatcher ()
static void anonymous_namespace{lang_spice.cc}::skip_pre_stuff (CS & cmd) [static]
Definition at line 102 of file lang_spice.cc.
References ANTI_COMMENT, CKT_PROMPT, CS::skipbl(), CS::umatch(), and untested.
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_command(), and anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_module_body().
{
  cmd.skipbl();
  while (cmd.umatch(CKT_PROMPT)) {untested();
    /* skip any number of copies of the prompt */
  }
  cmd.umatch(ANTI_COMMENT); /* skip mark so spice ignores but gnucap reads */
}
Variable Documentation
DISPATCHER< CMD >::INSTALL d99 & anonymous_namespace{lang_spice.cc}::command_dispatcher
Definition at line 850 of file lang_spice.cc.
DISPATCHER<CARD>::INSTALL d0& anonymous_namespace{lang_spice.cc}::device_dispatcher
Definition at line 99 of file lang_spice.cc.
anonymous_namespace{lang_spice.cc}::LANG_ACS anonymous_namespace{lang_spice.cc}::lang_acs
Referenced by anonymous_namespace{lang_spice.cc}::CMD_ENDC::do_it().
anonymous_namespace{lang_spice.cc}::LANG_SPICE anonymous_namespace{lang_spice.cc}::lang_spice
Referenced by anonymous_namespace{lang_spice.cc}::CMD_MODEL::do_it(), anonymous_namespace{lang_spice.cc}::CMD_SUBCKT::do_it(), anonymous_namespace{lang_spice.cc}::CMD_BUILD::do_it(), anonymous_namespace{lang_spice.cc}::CMD_CONTROL::do_it(), and getmerge().
DEV_COMMENT anonymous_namespace{lang_spice.cc}::p0
Definition at line 97 of file lang_spice.cc.
anonymous_namespace{lang_spice.cc}::CMD_MODEL anonymous_namespace{lang_spice.cc}::p1
anonymous_namespace{lang_spice.cc}::CMD_SUBCKT anonymous_namespace{lang_spice.cc}::p2
anonymous_namespace{lang_spice.cc}::CMD_INCLUDE anonymous_namespace{lang_spice.cc}::p3
anonymous_namespace{lang_spice.cc}::CMD_LIB anonymous_namespace{lang_spice.cc}::p33
anonymous_namespace{lang_spice.cc}::CMD_MERGE anonymous_namespace{lang_spice.cc}::p4
anonymous_namespace{lang_spice.cc}::CMD_RUN anonymous_namespace{lang_spice.cc}::p5
anonymous_namespace{lang_spice.cc}::CMD_GET anonymous_namespace{lang_spice.cc}::p6
anonymous_namespace{lang_spice.cc}::CMD_BUILD anonymous_namespace{lang_spice.cc}::p7
anonymous_namespace{lang_spice.cc}::CMD_SPICE anonymous_namespace{lang_spice.cc}::p8
anonymous_namespace{lang_spice.cc}::CMD_ENDC anonymous_namespace{lang_spice.cc}::p88
anonymous_namespace{lang_spice.cc}::CMD_ACS anonymous_namespace{lang_spice.cc}::p9
anonymous_namespace{lang_spice.cc}::CMD_CONTROL anonymous_namespace{lang_spice.cc}::p99