gnucap: anonymous_namespace{c_sweep.cc} Namespace Reference
anonymous_namespace{c_sweep.cc} Namespace Reference
Classes
class CMD_SWEEP
Functions
static void setup (CS &cmd)
static void buildfile (CS &cmd)
static void doit (CARD_LIST *scope)
Variables
static std::string tempfile = STEPFILE
anonymous_namespace{c_sweep.cc}::CMD_SWEEP p
DISPATCHER< CMD >::INSTALL d & command_dispatcher
Function Documentation
static void anonymous_namespace{c_sweep.cc}::buildfile (CS & cmd) [static]
Definition at line 52 of file c_sweep.cc.
References BUFLEN, CS::fullstring(), getcmd(), setup(), and Umatch().
Referenced by anonymous_namespace{c_sweep.cc}::CMD_SWEEP::do_it().
{
  static FILE *fptr;
  setup(cmd);
  if (fptr) {
    fclose(fptr);
  }else{
  }
  fptr = fopen(tempfile.c_str(), "w");
  if (!fptr) {
    throw Exception_File_Open("can't open temporary file:" + tempfile);
  }else{
  }
  fprintf(fptr, "%s\n", cmd.fullstring().c_str());
  for (;;) {
    char buffer[BUFLEN];
    getcmd(">>>", buffer, BUFLEN);
    if (Umatch(buffer,"go ")) {
      break;
    }else{
    }
    fprintf(fptr, "%s\n", buffer);
  }
  fclose(fptr);
  fptr = NULL;
}
static void anonymous_namespace{c_sweep.cc}::doit (CARD_LIST * scope) [static]
Definition at line 81 of file c_sweep.cc.
References CS::_STRING, BUFLEN, CMD::cmdproc(), CS::cursor(), IO::mstdout, setup(), swp_count, swp_nest, swp_steps, CS::umatch(), and CS::warn().
Referenced by anonymous_namespace{c_sweep.cc}::CMD_SWEEP::do_it().
{
  static FILE *fptr;
  for (swp_count[swp_nest]=0; swp_count[swp_nest]<=swp_steps[swp_nest];
       ++swp_count[swp_nest]) {
    if (fptr) {
      fclose(fptr);
    }else{
    }
    fptr = fopen(tempfile.c_str(), "r");
    if (!fptr) {
      throw Exception_File_Open("can't open " + tempfile);
    }else{
    }
    char buffer[BUFLEN];
    fgets(buffer,BUFLEN,fptr);
    {
      CS cmd(CS::_STRING, buffer); //fgets from local file, obsolete
      if (cmd.umatch("sw{eep} ")) {
        setup(cmd);
      }else{
        throw Exception("bad file format: " + tempfile);
      }
      unsigned ind = cmd.cursor();
      strncpy(buffer, "fault                              ", ind);
      buffer[ind-1] = ' ';              /* make sure there is a delimiter   */
    }                                   /* in case the words run together   */
    for (;;) {                          /* may wipe out one letter of fault */
      {
        CS cmd(CS::_STRING, buffer); //fgets from local file, obsolete
        CMD::cmdproc(cmd, scope);
      }
      if (!fgets(buffer,BUFLEN,fptr)) {
        break;
      }else{
      }
      {
        CS cmd(CS::_STRING, buffer); //fgets from local file, obsolete
        if (cmd.umatch("sw{eep} ")) {
          cmd.warn(bDANGER, "command not allowed in sweep");
          buffer[0] = '\'';
        }else{
        }
      }
      IO::mstdout << swp_count[swp_nest]+1 << "> " << buffer;
    }
  }
  fclose(fptr);
  fptr = NULL;
  swp_count[swp_nest] = 0;
}
static void anonymous_namespace{c_sweep.cc}::setup (CS & cmd) [static]
Definition at line 34 of file c_sweep.cc.
References CS::ctoi(), CS::is_digit(), swp_nest, swp_steps, swp_type, and CS::umatch().
Referenced by buildfile(), anonymous_namespace{s_ac.cc}::AC::do_it(), anonymous_namespace{s_fo.cc}::FOURIER::do_it(), and doit().
{
  for (;;) {
    if (cmd.is_digit()) {
      swp_steps[swp_nest] = cmd.ctoi() ;
      swp_steps[swp_nest] = (swp_steps[swp_nest])
        ? swp_steps[swp_nest]-1
        : 0;
    }else if (cmd.umatch("li{near} ")) {
      swp_type[swp_nest] = 0;
    }else if (cmd.umatch("lo{g} ")) {
      swp_type[swp_nest] = 'L';
    }else{
      break;
    }
  }
}
Variable Documentation
DISPATCHER<CMD>::INSTALL d& anonymous_namespace{c_sweep.cc}::command_dispatcher
Definition at line 146 of file c_sweep.cc.
anonymous_namespace{c_sweep.cc}::CMD_SWEEP anonymous_namespace{c_sweep.cc}::p
std::string anonymous_namespace{c_sweep.cc}::tempfile = STEPFILE [static]
Definition at line 32 of file c_sweep.cc.