gnucap: anonymous_namespace{c_status.cc}::CMD_STATUS Class Reference
anonymous_namespace{c_status.cc}::CMD_STATUS Class Reference
Public Member Functions
void do_it (CS &cmd, CARD_LIST *)
Detailed Description
Definition at line 36 of file c_status.cc.
Member Function Documentation
void anonymous_namespace{c_status.cc}::CMD_STATUS::do_it (CS & cmd, CARD_LIST *) [inline, virtual]
Implements CMD.
Definition at line 38 of file c_status.cc.
References STATUS::ac, STATUS::accept, STATUS::advance, STATUS::aux1, STATUS::aux2, STATUS::aux3, STATUS::back, STATUS::compute_overhead(), STATUS::dc, STATUS::evaluate, OMSTREAM::form(), STATUS::four, STATUS::get, itested, iTOTAL, STATUS::load, STATUS::lud, IO::mstdout, STATUS::op, STATUS::order, STATUS::output, STATUS::overhead, STATUS::queue, STATUS::review, s_DC, s_FOURIER, s_OP, s_TRAN, STATUS::set_up, OPT::showall, CKT_BASE::status(), status, status_dispatcher, STATUS::total, STATUS::tran, and CS::umatch().
  {
    IO::mstdout << "Gnucap   System status\n";
    if (!cmd.umatch("n{otime} ")) {
      ::status.compute_overhead();
      IO::mstdout
        << "command ------ last -- total\n"
        << ::status.get
        << ::status.op
        << ::status.dc
        << ::status.tran
        << ::status.four
        << ::status.ac
        << "function ----- last -- total\n"
        << ::status.set_up
        << ::status.order
        << "function ----- last -- total\n"
        << ::status.advance
        << ::status.queue
        << ::status.evaluate
        << ::status.load
        << ::status.lud
        << ::status.back
        << ::status.review
        << ::status.accept
        << ::status.output
        << ::status.overhead;
      if (OPT::showall) {itested();
        IO::mstdout
          << ::status.aux1
          << ::status.aux2
          << ::status.aux3;
      }
      IO::mstdout << ::status.total;
    }
    IO::mstdout
      << "iterations: op=" << _sim->_iter[s_OP]
      << ", dc=" << _sim->_iter[s_DC]
      << ", tran=" << _sim->_iter[s_TRAN]
      << ", fourier=" << _sim->_iter[s_FOURIER]
      << ", total=" << _sim->_iter[iTOTAL]
      << "\n";
    for(DISPATCHER<CKT_BASE>::const_iterator
          i = status_dispatcher.begin();
        i != status_dispatcher.end();
        ++i) {
      CKT_BASE* c = i->second;
      if (c) {
        IO::mstdout << c->status();
      }else{
      }
    }
    IO::mstdout
      << "nodes: user=" << _sim->_user_nodes
      << ", subckt=" << _sim->_subckt_nodes
      << ", model=" << _sim->_model_nodes
      << ", total=" << _sim->_total_nodes
      << "\n";
    IO::mstdout.form("dctran density=%.1f%%, ac density=%.1f%%\n",
                 _sim->_aa.density()*100., _sim->_acx.density()*100.);
  }
The documentation for this class was generated from the following file:
savant/gnucap/src/c_status.cc