gnucap: PROBELIST Class Reference
PROBELIST Class Reference
#include <u_prblst.h>
Public Types
typedef _container::iterator iterator
typedef _container::const_iterator const_iterator
Public Member Functions
PROBELIST ()
~PROBELIST ()
void listing (const std::string &) const
void clear ()
void remove_list (CS &)
void remove_one (CKT_BASE *)
void add_list (CS &)
int size () const
const_iterator begin () const
const_iterator end () const
iterator begin ()
iterator end ()
virtual void open (CS &)
virtual void send (OMSTREAM, double)
virtual void close ()
Private Types
typedef std::vector< PROBE > _container
Private Member Functions
PROBELIST (const PROBELIST &)
void erase (iterator b, iterator e)
void push_new_probe (const std::string &param, const CKT_BASE *object)
bool add_branches (const std::string &, const std::string &, const CARD_LIST *)
void add_all_nodes (const std::string &)
Private Attributes
_container bag
Detailed Description
Definition at line 32 of file u_prblst.h.
Member Typedef Documentation
typedef std::vector<PROBE> PROBELIST::_container [private]
Definition at line 34 of file u_prblst.h.
typedef _container::const_iterator PROBELIST::const_iterator
Definition at line 43 of file u_prblst.h.
typedef _container::iterator PROBELIST::iterator
Definition at line 42 of file u_prblst.h.
Constructor & Destructor Documentation
PROBELIST::PROBELIST (const PROBELIST &) [inline, explicit, private]
Definition at line 37 of file u_prblst.h.
References incomplete, and unreachable.
{unreachable();incomplete();}
PROBELIST::PROBELIST () [inline, explicit]
Definition at line 39 of file u_prblst.h.
{}
PROBELIST::~PROBELIST () [inline]
Definition at line 40 of file u_prblst.h.
{}
Member Function Documentation
void PROBELIST::add_all_nodes (const std::string & what) [private]
Definition at line 194 of file u_prblst.cc.
References begin(), CARD_LIST::card_list, NODE_MAP::end(), CARD_LIST::nodes(), and push_new_probe().
Referenced by add_list().
{
  for (NODE_MAP::const_iterator
       i = CARD_LIST::card_list.nodes()->begin();
       i != CARD_LIST::card_list.nodes()->end();
       ++i) {
    if ((i->first != "0") && (i->first.find('.') == std::string::npos)) {
      NODE* node = i->second;
      assert (node);
      push_new_probe(what, node);
    }else{
    }
  }
}
bool PROBELIST::add_branches (const std::string & device, const std::string & param, const CARD_LIST * scope) [private]
Definition at line 212 of file u_prblst.cc.
References NODE_MAP::begin(), CARD_LIST::begin(), NODE_MAP::end(), CARD_LIST::end(), CARD_LIST::find_(), CARD::is_device(), CARD_LIST::nodes(), push_new_probe(), CKT_BASE::short_label(), CARD::subckt(), and wmatch().
Referenced by add_list().
{
  assert(scope);
  bool found_something = false;
  std::string::size_type dotplace = device.find_first_of(".");
  if (dotplace != std::string::npos) {
    // has a dot, look deeper
    { // forward (Verilog style)
      std::string dev = device.substr(dotplace+1, std::string::npos);
      std::string container = device.substr(0, dotplace);
      for (CARD_LIST::const_iterator
             i = scope->begin();  i != scope->end();  ++i) {
        CARD* card = *i;
        if (card->is_device()
            && card->subckt()
            && wmatch(card->short_label(), container)) {
          found_something |= add_branches(dev, param, card->subckt());
        }else{
        }
      }
    }
    { // reverse (ACS style)
      dotplace = device.find_last_of(".");
      std::string container = device.substr(dotplace+1, std::string::npos);
      std::string dev = device.substr(0, dotplace);
      for (CARD_LIST::const_iterator
             i = scope->begin();  i != scope->end();  ++i) {
        CARD* card = *i;
        if (card->is_device()
            && card->subckt()
            && wmatch(card->short_label(), container)) {
          found_something |= add_branches(dev, param, card->subckt());
        }else{
        }
      }
    }
  }else{
    // no dots, look here
    if (device.find_first_of("*?") != std::string::npos) {
      // there's a wild card.  do linear search for all
      { // nodes
        for (NODE_MAP::const_iterator
             i = scope->nodes()->begin();
             i != scope->nodes()->end();
             ++i) {
          if (i->first != "0") {
            NODE* node = i->second;
            assert (node);
            if (wmatch(node->short_label(), device)) {
              push_new_probe(param, node);
              found_something = true;
            }else{
            }
          }else{
          }
        }
      }
      {// components
        for (CARD_LIST::const_iterator
             i = scope->begin();  i != scope->end();  ++i) {
          CARD* card = *i;
          if (wmatch(card->short_label(), device)) {
            push_new_probe(param, card);
            found_something = true;
          }else{
          }
        }
      }
    }else{
      // no wild card.  do fast search for one
      { // nodes
        NODE* node = (*scope->nodes())[device];
        if (node) {
          push_new_probe(param, node);
          found_something = true;
        }else{
        }
      }
      { //components
        CARD_LIST::const_iterator i = scope->find_(device);
        if (i != scope->end()) {
          push_new_probe(param, *i);
          found_something = true;
        }else{
        }
      }
    }
  }
  return found_something;
}
void PROBELIST::add_list (CS & cmd)
Definition at line 128 of file u_prblst.cc.
References add_all_nodes(), add_branches(), begin(), CARD_LIST::card_list, CS::check(), CS::ctof(), CS::ctos(), CS::cursor(), end(), CS::is_alnum(), itested, CS::match1(), anonymous_namespace{c_genrat.cc}::p, push_new_probe(), CS::reset(), size(), CS::skip1b(), TOKENTERM, CS::umatch(), untested, and CS::warn().
Referenced by anonymous_namespace{c_prbcmd.cc}::do_probe().
{
  int oldcount = size();
  std::string what(cmd.ctos(TOKENTERM));/* parameter */
  if (what.empty()) {untested();
    cmd.warn(bWARNING, "need a probe");
  }else{
  }
  int paren = cmd.skip1b('(');          /* device, node, etc. */
  if (cmd.umatch("nodes ")) {
    // all nodes
    add_all_nodes(what);
  }else if (cmd.umatch("0")) {
    // node 0 means system stuff
    push_new_probe(what, 0);
  }else if (cmd.is_alnum() || cmd.match1("*?")) {
    // branches or named nodes
    unsigned here1 = cmd.cursor();
    bool found_something = add_branches(cmd.ctos(),what,&CARD_LIST::card_list);
    if (!found_something) {
      cmd.warn(bWARNING, here1, "no match");
    }else{
    }
    for (;;) {
      // a list, as in v(r1,r2,r3) or v(1,2,3)
      if (!(cmd.is_alnum() || cmd.match1("*?"))) {
        break;
      }else{
      }
      unsigned here2 = cmd.cursor();
      found_something = add_branches(cmd.ctos(),what,&CARD_LIST::card_list);
      if (!found_something) {itested();
        cmd.reset(here2);
        break;
      }else{
      }
    }
  }else{itested();
    cmd.warn(bDANGER, "need device or node");
  }
  paren -= cmd.skip1b(')');
  if (paren != 0) {itested();
    cmd.warn(bWARNING, "need )");
  }else{
  }
  if (cmd.skip1b('(')) {        /* range for plotting and alarm */
    double lo = cmd.ctof();
    double hi = cmd.ctof();
    for (iterator p = begin() + oldcount;  p != end();  ++p) {
      p->set_limit(lo,hi);
    }
    if (!cmd.skip1b(')')) {untested();
      cmd.check(bWARNING, "need )");
    }else{
    }
  }else{
  }
}
const_iterator PROBELIST::begin () const [inline]
Definition at line 51 of file u_prblst.h.
Referenced by add_all_nodes(), add_list(), clear(), CKT_BASE::find_wave(), SIM::head(), listing(), plhead(), plottr(), remove_list(), and remove_one().
{return bag.begin();}
iterator PROBELIST::begin () [inline]
Definition at line 53 of file u_prblst.h.
{return bag.begin();}
void PROBELIST::clear (void)
Definition at line 56 of file u_prblst.cc.
References begin(), end(), and erase().
Referenced by anonymous_namespace{c_prbcmd.cc}::do_probe().
{
  erase(begin(), end());
}
virtual void PROBELIST::close () [inline, virtual]
Definition at line 58 of file u_prblst.h.
References incomplete.
{incomplete();}
const_iterator PROBELIST::end () const [inline]
Definition at line 52 of file u_prblst.h.
Referenced by add_list(), SIM::alarm(), clear(), CKT_BASE::find_wave(), SIM::head(), listing(), plhead(), plottr(), SIM::print_results(), remove_list(), remove_one(), and SIM::store_results().
{return bag.end();}
iterator PROBELIST::end () [inline]
Definition at line 54 of file u_prblst.h.
{return bag.end();}
void PROBELIST::erase (iterator b, iterator e) [inline, private]
Definition at line 60 of file u_prblst.h.
Referenced by clear(), remove_list(), and remove_one().
{bag.erase(b,e);}
void PROBELIST::listing (const std::string & label) const
Definition at line 42 of file u_prblst.cc.
References begin(), end(), OMSTREAM::form(), IO::mstdout, anonymous_namespace{c_genrat.cc}::p, OMSTREAM::setfloatwidth(), and untested.
Referenced by anonymous_namespace{c_prbcmd.cc}::do_probe().
{
  IO::mstdout.form("%-7s", label.c_str());
  for (const_iterator p = begin();  p != end();  ++p) {
    IO::mstdout << ' ' << p->label();
    if (p->range() != 0.) {untested();
      IO::mstdout.setfloatwidth(5)
        << '(' << p->lo() << ',' << p->hi() << ')';
    }else{
    }
  }
  IO::mstdout << '\n';
}
virtual void PROBELIST::open (CS &) [inline, virtual]
Definition at line 56 of file u_prblst.h.
References incomplete.
{incomplete();}
void PROBELIST::push_new_probe (const std::string & param, const CKT_BASE * object) [private]
Definition at line 189 of file u_prblst.cc.
References bag.
Referenced by add_all_nodes(), add_branches(), and add_list().
{
  bag.push_back(PROBE(param, object));
}
void PROBELIST::remove_list (CS & cmd)
Definition at line 78 of file u_prblst.cc.
References begin(), CS::ctos(), CS::cursor(), end(), erase(), itested, CS::skip1b(), TOKENTERM, untested, and CS::warn().
Referenced by anonymous_namespace{c_prbcmd.cc}::do_probe().
{
  unsigned mark = cmd.cursor();
  std::string parameter(cmd.ctos(TOKENTERM) + '(');
  int paren = cmd.skip1b('(');
  parameter += cmd.ctos(TOKENTERM) + ')';
  paren -= cmd.skip1b(')');
  if (paren != 0) {untested();
    cmd.warn(bWARNING, "need )");
  }else if (parameter.empty()) {untested();
    cmd.warn(bWARNING, "what's this?");
  }else{
  }
  iterator x = remove(begin(), end(), parameter);
  if (x != end()) {
    erase(x, end());
  }else{itested();
    cmd.warn(bWARNING, mark, "probe isn't set -- can't remove");
  }
}
void PROBELIST::remove_one (CKT_BASE * brh)
Definition at line 116 of file u_prblst.cc.
References begin(), end(), and erase().
Referenced by PROBE_LISTS::purge().
{
  assert(brh);
  erase(remove(begin(), end(), brh), end());
}
virtual void PROBELIST::send (OMSTREAM , double) [inline, virtual]
Definition at line 57 of file u_prblst.h.
References incomplete.
{incomplete();}
int PROBELIST::size () const [inline]
Definition at line 50 of file u_prblst.h.
Referenced by add_list(), SIM::head(), TRANSIENT::options(), anonymous_namespace{s_dc.cc}::DC::setup(), and anonymous_namespace{s_dc.cc}::OP::setup().
{return static_cast<int>(bag.size());}
Member Data Documentation
_container PROBELIST::bag [private]
Definition at line 35 of file u_prblst.h.
Referenced by push_new_probe().
The documentation for this class was generated from the following files:
savant/gnucap/src/u_prblst.h
savant/gnucap/src/u_prblst.cc