gnucap: anonymous_namespace{d_trln.cc} Namespace Reference
anonymous_namespace{d_trln.cc} Namespace Reference
Classes
class COMMON_TRANSLINE
class DEV_TRANSLINE
Enumerations
enum { NUM_INIT_COND = 4 }
Functions
const double _default_len (1)
const double _default_R (0)
const double _default_L (NOT_INPUT)
const double _default_G (0)
const double _default_C (NOT_INPUT)
const double _default_z0 (50.)
const double _default_td (NOT_INPUT)
const double _default_f (NOT_INPUT)
const double _default_nl (0.25)
Variables
const double LINLENTOL = .000001
static COMMON_TRANSLINE Default_TRANSLINE (CC_STATIC)
DEV_TRANSLINE p1
DISPATCHER< CARD >::INSTALL d1 & device_dispatcher
Enumeration Type Documentation
anonymous enum
Enumerator:
NUM_INIT_COND
Definition at line 30 of file d_trln.cc.
{NUM_INIT_COND = 4};
Function Documentation
const double anonymous_namespace{d_trln.cc}::_default_C (NOT_INPUT)
Referenced by anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::precalc_first().
const double anonymous_namespace{d_trln.cc}::_default_f (NOT_INPUT)
Referenced by anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::precalc_first().
const double anonymous_namespace{d_trln.cc}::_default_G (0)
Referenced by anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::precalc_first().
const double anonymous_namespace{d_trln.cc}::_default_L (NOT_INPUT)
Referenced by anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::precalc_first().
const double anonymous_namespace{d_trln.cc}::_default_len (1)
Referenced by anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::precalc_first().
const double anonymous_namespace{d_trln.cc}::_default_nl (0. 25)
Referenced by anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::precalc_first().
const double anonymous_namespace{d_trln.cc}::_default_R (0)
Referenced by anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::precalc_first().
const double anonymous_namespace{d_trln.cc}::_default_td (NOT_INPUT)
Referenced by anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::precalc_first().
const double anonymous_namespace{d_trln.cc}::_default_z0 (50.)
Referenced by anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::precalc_first(), and anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::precalc_last().
Variable Documentation
COMMON_TRANSLINE anonymous_namespace{d_trln.cc}::Default_TRANSLINE(CC_STATIC) [static]
Referenced by anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::DEV_TRANSLINE().
DISPATCHER<CARD>::INSTALL d1& anonymous_namespace{d_trln.cc}::device_dispatcher
Definition at line 555 of file d_trln.cc.
const double anonymous_namespace{d_trln.cc}::LINLENTOL = .000001
Definition at line 152 of file d_trln.cc.
Referenced by anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::do_ac().
DEV_TRANSLINE anonymous_namespace{d_trln.cc}::p1
Definition at line 554 of file d_trln.cc.