gnucap: anonymous_namespace{d_trln.cc}::DEV_TRANSLINE Class Reference
anonymous_namespace{d_trln.cc}::DEV_TRANSLINE Class Reference
Public Member Functions
DEV_TRANSLINE ()
Private Member Functions
DEV_TRANSLINE (const DEV_TRANSLINE &p)
char id_letter () const
std::string value_name () const
std::string dev_type () const
int max_nodes () const
int min_nodes () const
int matrix_nodes () const
int net_nodes () const
CARD * clone () const
void precalc_last ()
void tr_iwant_matrix ()
void tr_begin ()
void dc_advance ()
void tr_advance ()
void tr_regress ()
bool tr_needs_eval () const
bool do_tr ()
void tr_load ()
TIME_PAIR tr_review ()
void tr_accept ()
void tr_unload ()
double tr_involts () const
double tr_involts_limited () const
void ac_iwant_matrix ()
void do_ac ()
void ac_load ()
COMPLEX ac_involts () const
std::string port_name (int i) const
void setinitcond (CS &)
Private Attributes
WAVE _forward
WAVE _reflect
double _if0
double _ir0
double _if1
double _ir1
COMPLEX _y11
COMPLEX _y12
Detailed Description
Definition at line 67 of file d_trln.cc.
Constructor & Destructor Documentation
anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::DEV_TRANSLINE (const DEV_TRANSLINE & p) [inline, explicit, private]
Definition at line 78 of file d_trln.cc.
    :ELEMENT(p), _forward(), _reflect(), _if0(0), _ir0(0), _if1(0), _ir1(0) {}
anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::DEV_TRANSLINE () [explicit]
Definition at line 372 of file d_trln.cc.
References COMPONENT::attach_common(), and anonymous_namespace{d_trln.cc}::Default_TRANSLINE.
  :ELEMENT(),
   _forward(), _reflect(),
   _if0(0), _ir0(0), _if1(0), _ir1(0),
   _y11(), _y12()
{
  attach_common(&Default_TRANSLINE);
}
Member Function Documentation
COMPLEX anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::ac_involts () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 137 of file d_trln.cc.
References IN1, IN2, and untested.
{untested();
  return _n[IN1]->vac() - _n[IN2]->vac();
}
void anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::ac_iwant_matrix () [inline, private, virtual]
Implements ELEMENT.
Definition at line 105 of file d_trln.cc.
{ac_iwant_matrix_extended();}
void anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::ac_load () [private, virtual]
Reimplemented from CARD.
Definition at line 542 of file d_trln.cc.
References SIM_DATA::_acx, CARD::_n, CKT_BASE::_sim, _y11, _y12, IN1, IN2, BSMATRIX< T >::load_asymmetric(), BSMATRIX< T >::load_symmetric(), COMPONENT::mfactor(), OUT1, and OUT2.
{
  //BUG// explicit mfactor
  _sim->_acx.load_symmetric(_n[OUT1].m_(), _n[OUT2].m_(), mfactor()*_y11);
  _sim->_acx.load_symmetric(_n[IN1].m_(),  _n[IN2].m_(),  mfactor()*_y11);
  _sim->_acx.load_asymmetric(_n[OUT1].m_(),_n[OUT2].m_(), _n[IN2].m_(),  _n[IN1].m_(),
                             mfactor()*_y12);
  _sim->_acx.load_asymmetric(_n[IN1].m_(), _n[IN2].m_(), _n[OUT2].m_(), _n[OUT1].m_(),
                             mfactor()*_y12);
}
CARD* anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::clone () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 90 of file d_trln.cc.
{return new DEV_TRANSLINE(*this);}
void anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::dc_advance () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 417 of file d_trln.cc.
References _forward, _if0, _ir0, _reflect, CKT_BASE::_sim, SIM_DATA::_time0, COMPONENT::common(), FPOLY1::f0, prechecked_cast, anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::real_z0, and WAVE::v_out().
{
  ELEMENT::dc_advance();
  const COMMON_TRANSLINE* c=prechecked_cast<const COMMON_TRANSLINE*>(common());
  assert(c);
  _if0 = _forward.v_out(_sim->_time0).f0/c->real_z0;
  _ir0 = _reflect.v_out(_sim->_time0).f0/c->real_z0;
}
std::string anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::dev_type () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 85 of file d_trln.cc.
References itested.
{itested(); return "tline";}
void anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::do_ac () [private, virtual]
Reimplemented from CARD.
Definition at line 524 of file d_trln.cc.
References SIM_DATA::_freq, CKT_BASE::_sim, _y11, _y12, COMPONENT::common(), error(), anonymous_namespace{d_trln.cc}::LINLENTOL, CARD::long_label(), prechecked_cast, anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::real_td, and anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::real_z0.
{
  const COMMON_TRANSLINE*c=prechecked_cast<const COMMON_TRANSLINE*>(common());
  assert(c);
  double lenth = _sim->_freq * c->real_td * 4;  /* length in quarter waves */
  double dif = lenth - floor(lenth+.5); /* avoid divide by zero if close to */
  if (std::abs(dif) < LINLENTOL) {      /* resonance by tweeking a little */
    error(bDEBUG,
          long_label() + ": transmission line too close to resonance\n");
    lenth = (dif<0.) ? floor(lenth+.5)-LINLENTOL : floor(lenth+.5)+LINLENTOL;
  }else{
  }
  lenth *= (M_PI_2);    /* now in radians */
  _y12 = COMPLEX(0., -1. / (c->real_z0 * sin(lenth)));
  _y11 = COMPLEX(0., tan(lenth/2) / c->real_z0) + _y12;
}
bool anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::do_tr () [private, virtual]
Reimplemented from CARD.
Definition at line 446 of file d_trln.cc.
References _if0, _if1, _ir0, _ir1, OPT::abstol, conchk(), COMPONENT::converged(), COMPONENT::q_load(), and OPT::reltol.
{
  // code to deal with short lines goes here.
  //if (_if0 != _if1  ||  _ir0 != _ir1) {
  if (!conchk(_if0, _if1, OPT::abstol, OPT::reltol*.01)
       || !conchk(_ir0, _ir1, OPT::abstol, OPT::reltol*.01)) {
    q_load();
  }else{
  }
  assert(converged());
  return true;
}
char anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::id_letter () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 83 of file d_trln.cc.
{return 'T';}
int anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::matrix_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 88 of file d_trln.cc.
{return 4;}
int anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::max_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 86 of file d_trln.cc.
{return 4;}
int anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::min_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 87 of file d_trln.cc.
{return 4;}
int anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::net_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 89 of file d_trln.cc.
{return 4;}
std::string anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::port_name (int i) const [inline, private, virtual]
Implements COMPONENT.
Definition at line 110 of file d_trln.cc.
References itested.
                                  {itested();
    assert(i >= 0);
    assert(i < 4);
    static std::string names[] = {"t1", "b1", "t2", "b2"};
    return names[i];
  }
void anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::precalc_last () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 381 of file d_trln.cc.
References _forward, _reflect, COMPONENT::common(), CARD::is_constant(), prechecked_cast, anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::real_td, COMPONENT::set_converged(), and WAVE::set_delay().
{
  ELEMENT::precalc_last();
  const COMMON_TRANSLINE* c=prechecked_cast<const COMMON_TRANSLINE*>(common());
  assert(c);
  _forward.set_delay(c->real_td);
  _reflect.set_delay(c->real_td);
  set_converged();
  assert(!is_constant());
}
void anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::setinitcond (CS &) [private]
void anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_accept () [private, virtual]
Reimplemented from COMPONENT.
Definition at line 513 of file d_trln.cc.
References _forward, _reflect, CKT_BASE::_sim, SIM_DATA::_time0, WAVE::push(), CKT_BASE::short_label(), tr_involts(), ELEMENT::tr_outvolts(), trace1, and WAVE::v_reflect().
{
  trace1(short_label().c_str(), _sim->_time0);
  _reflect.push(_sim->_time0, _forward.v_reflect(_sim->_time0, tr_outvolts()));
  _forward.push(_sim->_time0, _reflect.v_reflect(_sim->_time0, tr_involts()));
}
void anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_advance () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 425 of file d_trln.cc.
References _forward, _if0, _ir0, _reflect, CKT_BASE::_sim, SIM_DATA::_time0, COMPONENT::common(), FPOLY1::f0, prechecked_cast, anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::real_z0, and WAVE::v_out().
{
  ELEMENT::tr_advance();
  const COMMON_TRANSLINE* c=prechecked_cast<const COMMON_TRANSLINE*>(common());
  assert(c);
  _if0 = _forward.v_out(_sim->_time0).f0/c->real_z0;
  _ir0 = _reflect.v_out(_sim->_time0).f0/c->real_z0;
}
void anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_begin () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 402 of file d_trln.cc.
References _forward, _reflect, COMPONENT::common(), WAVE::initialize(), prechecked_cast, WAVE::push(), and anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::real_td.
{
  ELEMENT::tr_begin();
  const COMMON_TRANSLINE* c=prechecked_cast<const COMMON_TRANSLINE*>(common());
  assert(c);
  _forward.initialize().push(0.-c->real_td, 0.).push(0., 0.);
  _reflect.initialize().push(0.-c->real_td, 0.).push(0., 0.);
}
double anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_involts () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 126 of file d_trln.cc.
References dn_diff(), IN1, and IN2.
Referenced by tr_accept().
{
  return dn_diff(_n[IN1].v0(), _n[IN2].v0());
}
double anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_involts_limited () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 131 of file d_trln.cc.
References IN1, IN2, unreachable, and volts_limited().
{
  unreachable();
  return volts_limited(_n[IN1],_n[IN2]);
}
void anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_iwant_matrix () [private, virtual]
Implements ELEMENT.
Definition at line 392 of file d_trln.cc.
References SIM_DATA::_aa, SIM_DATA::_lu, CARD::_n, CKT_BASE::_sim, IN1, IN2, BSMATRIX< T >::iwant(), OUT1, and OUT2.
{
  _sim->_aa.iwant(_n[OUT1].m_(),_n[OUT2].m_());
  _sim->_aa.iwant(_n[IN1].m_(), _n[IN2].m_());
  _sim->_lu.iwant(_n[OUT1].m_(),_n[OUT2].m_());
  _sim->_lu.iwant(_n[IN1].m_(), _n[IN2].m_());
}
void anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_load () [private, virtual]
Reimplemented from CARD.
Definition at line 459 of file d_trln.cc.
References SIM_DATA::_aa, _if0, _if1, _ir0, _ir1, CARD::_n, CKT_BASE::_sim, COMPONENT::common(), dn_diff(), node_t::i(), IN1, IN2, SIM_DATA::is_inc_mode(), BSMATRIX< T >::load_symmetric(), COMPONENT::mfactor(), NOT_VALID, OUT1, OUT2, prechecked_cast, anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::real_z0, and untested.
{
  //BUG// explicit mfactor
  double lvf = NOT_VALID; // load value, forward
  double lvr = NOT_VALID; // load value, reflected
  if (!_sim->is_inc_mode()) {
    const COMMON_TRANSLINE* c = prechecked_cast<const COMMON_TRANSLINE*>(common());
    assert(c);
    _sim->_aa.load_symmetric(_n[OUT1].m_(), _n[OUT2].m_(), mfactor()/c->real_z0);
    _sim->_aa.load_symmetric(_n[IN1].m_(),  _n[IN2].m_(),  mfactor()/c->real_z0);
    lvf = _if0;
    lvr = _ir0;
  }else{
    lvf = dn_diff(_if0, _if1);
    lvr = dn_diff(_ir0, _ir1);
  }
  if (lvf != 0.) {
    if (_n[OUT1].m_() != 0) {
      _n[OUT1].i() += mfactor() * lvf;
    }else{untested();
    }
    if (_n[OUT2].m_() != 0) {untested();
      _n[OUT2].i() -= mfactor() * lvf;
    }else{
    }
  }else{
  }
  if (lvr != 0.) {
    if (_n[IN1].m_() != 0) {
      _n[IN1].i() += mfactor() * lvr;
    }else{untested();
    }
    if (_n[IN2].m_() != 0) {untested();
      _n[IN2].i() -= mfactor() * lvr;
    }else{
    }
  }else{
  }
  _if1 = _if0;
  _ir1 = _ir0;
}
bool anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_needs_eval () const [inline, private, virtual]
Reimplemented from ELEMENT.
Definition at line 120 of file d_trln.cc.
{
  assert(!is_q_for_eval());
  return (_if0!=_if1 || _ir0!=_ir1);
}
void anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_regress () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 433 of file d_trln.cc.
References _forward, _if0, _ir0, _reflect, CKT_BASE::_sim, SIM_DATA::_time0, COMPONENT::common(), FPOLY1::f0, prechecked_cast, anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::real_z0, and WAVE::v_out().
{
  ELEMENT::tr_regress();
  const COMMON_TRANSLINE* c=prechecked_cast<const COMMON_TRANSLINE*>(common());
  assert(c);
  _if0 = _forward.v_out(_sim->_time0).f0/c->real_z0;
  _ir0 = _reflect.v_out(_sim->_time0).f0/c->real_z0;
}
TIME_PAIR anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_review () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 503 of file d_trln.cc.
References CKT_BASE::_sim, SIM_DATA::_time0, COMPONENT::common(), NEVER, prechecked_cast, COMPONENT::q_accept(), and anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::real_td.
{
  q_accept();
  const COMMON_TRANSLINE* c=prechecked_cast<const COMMON_TRANSLINE*>(common());
  assert(c);
  return TIME_PAIR(_sim->_time0 + c->real_td, NEVER); // ok to miss the spikes, for now
}
void anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_unload () [private, virtual]
Reimplemented from CARD.
Definition at line 520 of file d_trln.cc.
References untested.
{untested();
}
std::string anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::value_name () const [inline, private, virtual]
Implements CARD.
Definition at line 84 of file d_trln.cc.
{return "#";}
Member Data Documentation
WAVE anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::_forward [private]
Definition at line 69 of file d_trln.cc.
Referenced by dc_advance(), precalc_last(), tr_accept(), tr_advance(), tr_begin(), and tr_regress().
double anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::_if0 [private]
Definition at line 71 of file d_trln.cc.
Referenced by dc_advance(), do_tr(), tr_advance(), tr_load(), and tr_regress().
double anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::_if1 [private]
Definition at line 73 of file d_trln.cc.
Referenced by do_tr(), and tr_load().
double anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::_ir0 [private]
Definition at line 72 of file d_trln.cc.
Referenced by dc_advance(), do_tr(), tr_advance(), tr_load(), and tr_regress().
double anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::_ir1 [private]
Definition at line 74 of file d_trln.cc.
Referenced by do_tr(), and tr_load().
WAVE anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::_reflect [private]
Definition at line 70 of file d_trln.cc.
Referenced by dc_advance(), precalc_last(), tr_accept(), tr_advance(), tr_begin(), and tr_regress().
COMPLEX anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::_y11 [private]
Definition at line 75 of file d_trln.cc.
Referenced by ac_load(), and do_ac().
COMPLEX anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::_y12 [private]
Definition at line 76 of file d_trln.cc.
Referenced by ac_load(), and do_ac().
The documentation for this class was generated from the following file:
savant/gnucap/src/d_trln.cc