gnucap: savant/gnucap/src/io_error.cc File Reference
savant/gnucap/src/io_error.cc File Reference
#include "ap.h"
#include "u_opt.h"
Functions
void error (int, const char *,...)
void error (int, const std::string &)
Function Documentation
void error (int badness, const char * fmt, ...)
Definition at line 66 of file io_error.cc.
References BIGBUFLEN, IO::error, and OPT::picky.
Referenced by DEV_LOGIC::ac_begin(), EVAL_BM_ACTION_BASE::ac_final_adjust(), CMD::cmdproc(), SIM::command_base(), anonymous_namespace{d_res.cc}::DEV_RESISTANCE::do_ac(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::do_ac(), anonymous_namespace{s_fo.cc}::FOURIER::do_it(), anonymous_namespace{c_file.cc}::CMD_LOG::do_it(), anonymous_namespace{c_file.cc}::CMD_FILE::do_it(), anonymous_namespace{d_vcr.cc}::DEV_VCR::do_tr(), anonymous_namespace{d_res.cc}::DEV_RESISTANCE::do_tr(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_tr(), PARAMETER< T >::e_val(), anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::expand(), DEV_LOGIC::expand(), anonymous_namespace{c_modify.cc}::faultbranch(), COMPONENT::find_model(), IFerror(), DISPATCHER< T >::install(), internalerror(), BSMATRIX< T >::lu_decomp(), main(), SIM_DATA::map__nodes(), TRANSIENT::next(), OMSTREAM::operator<<(), MODEL_TABLE::precalc_first(), COMPONENT::precalc_first(), DEV_SPICE::precalc_first(), anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::precalc_last(), COMPONENT::precalc_last(), process_cmd_line(), LOGIC_NODE::set_event(), SIM_DATA::set_limit(), sig_abrt(), sig_fpe(), SIM::solve(), SPLINE::SPLINE(), TRANSIENT::sweep(), anonymous_namespace{s_dc.cc}::DCOP::sweep_recursive(), LOGIC_NODE::to_analog(), LOGIC_NODE::to_logic(), DEV_LOGIC::tr_accept(), anonymous_namespace{d_res.cc}::DEV_RESISTANCE::tr_begin(), DEV_SPICE::tr_load(), ELEMENT::tr_restore(), ELEMENT::tr_review_check_and_convert(), DISPATCHER< T >::uninstall(), COMPONENT::volts_limited(), and xopen().
{
  if (badness >= OPT::picky) {
    char buffer[BIGBUFLEN] = "";
    va_list arg_ptr;
    va_start(arg_ptr,fmt);
    vsprintf(buffer,fmt,arg_ptr);
    va_end(arg_ptr);
    IO::error << buffer;
  }else{
  }
}
void error (int badness, const std::string & message)
Definition at line 79 of file io_error.cc.
References IO::error, and OPT::picky.
{
  if (badness >= OPT::picky) {
    IO::error << message;
  }else{
  }
}