gnucap: anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP Class Reference
anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP Class Reference
Public Member Functions
DEV_FPOLY_CAP ()
Private Member Functions
DEV_FPOLY_CAP (const DEV_FPOLY_CAP &p)
char id_letter () const
std::string dev_type () const
CARD * clone () const
bool do_tr ()
Detailed Description
Definition at line 88 of file d_poly_cap.cc.
Constructor & Destructor Documentation
anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::DEV_FPOLY_CAP (const DEV_FPOLY_CAP & p) [inline, explicit, private]
Definition at line 90 of file d_poly_cap.cc.
    :DEV_CPOLY_CAP(p) {}
anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::DEV_FPOLY_CAP () [inline, explicit]
Definition at line 93 of file d_poly_cap.cc.
:DEV_CPOLY_CAP() {}
Member Function Documentation
CARD* anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::clone () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP.
Definition at line 97 of file d_poly_cap.cc.
{return new DEV_FPOLY_CAP(*this);}
std::string anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::dev_type () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP.
Definition at line 96 of file d_poly_cap.cc.
References unreachable.
{unreachable(); return "fpoly_cap";}
bool anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::do_tr () [private, virtual]
Reimplemented from anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP.
Definition at line 169 of file d_poly_cap.cc.
References STORAGE::_i, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::_inputs, ELEMENT::_m0, STORAGE::_method_a, CARD::_n, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::_n_ports, ELEMENT::_time, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::_vi0, anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::_vy0, ELEMENT::_y, differentiate(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::do_tr_con_chk_and_q(), FPOLY1::f0, FPOLY1::f1, STORAGE::tr_c_to_g(), ELEMENT::tr_outvolts(), untested, COMPONENT::volts_limited(), and FPOLY1::x.
{
  assert((_time[0] == 0) || (_vy0[0] == _vy0[0]));
  _y[0].x  = tr_outvolts();
  _y[0].f0 = _vy0[0];
  _y[0].f1 = _vy0[1];
  _i[0] = differentiate(_y, _i, _time, _method_a);
  _vi0[0] = _i[0].f0;
  _vi0[1] = _i[0].f1;
  assert(_vi0[0] == _vi0[0]);
  if (_inputs) {untested();
    for (int i=1; i<=_n_ports; ++i) {untested();
      _vi0[i] = tr_c_to_g(_vy0[i], _vi0[i]);
      _vi0[0] -= *(_inputs[i]) * _vi0[i];
    }
  }else{
    for (int i=1; i<=_n_ports; ++i) {
      _vi0[i] = tr_c_to_g(_vy0[i], _vi0[i]);
      _vi0[0] -= volts_limited(_n[2*i-2],_n[2*i-1]) * _vi0[i];
      assert(_vi0[i] == _vi0[i]);
      assert(_vi0[0] == _vi0[0]);
    }
  }
  for (int i=0; i<=_n_ports; ++i) {
    assert(_vi0[i] == _vi0[i]);
  }
  _m0 = CPOLY1(0., _vi0[0], _vi0[1]);
  return do_tr_con_chk_and_q();
}
char anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::id_letter () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP.
Definition at line 95 of file d_poly_cap.cc.
References unreachable.
{unreachable(); return '\0';}
The documentation for this class was generated from the following file:
savant/gnucap/src/d_poly_cap.cc