gnucap: LANGUAGE Class Reference
LANGUAGE Class Reference
#include <u_lang.h>
Public Member Functions
const CARD * find_proto (const std::string &, const CARD *)
void new__instance (CS &cmd, MODEL_SUBCKT *owner, CARD_LIST *Scope)
virtual ~LANGUAGE ()
virtual std::string name () const =0
virtual bool case_insensitive () const =0
virtual UNITS units () const =0
virtual std::string arg_front () const =0
virtual std::string arg_mid () const =0
virtual std::string arg_back () const =0
virtual void parse_top_item (CS &, CARD_LIST *)
virtual CARD * parse_item (CS &, CARD *)
virtual DEV_COMMENT * parse_comment (CS &, DEV_COMMENT *)=0
virtual DEV_DOT * parse_command (CS &, DEV_DOT *)=0
virtual MODEL_CARD * parse_paramset (CS &, MODEL_CARD *)=0
virtual MODEL_SUBCKT * parse_module (CS &, MODEL_SUBCKT *)=0
virtual COMPONENT * parse_instance (CS &, COMPONENT *)=0
virtual std::string find_type_in_string (CS &)=0
virtual void print_item (OMSTREAM &, const CARD *)
Private Member Functions
virtual void print_paramset (OMSTREAM &, const MODEL_CARD *)=0
virtual void print_module (OMSTREAM &, const MODEL_SUBCKT *)=0
virtual void print_instance (OMSTREAM &, const COMPONENT *)=0
virtual void print_comment (OMSTREAM &, const DEV_COMMENT *)=0
virtual void print_command (OMSTREAM &, const DEV_DOT *)=0
Detailed Description
Definition at line 34 of file u_lang.h.
Constructor & Destructor Documentation
virtual LANGUAGE::~LANGUAGE () [inline, virtual]
Definition at line 41 of file u_lang.h.
{}
Member Function Documentation
virtual std::string LANGUAGE::arg_back () const [pure virtual]
Implemented in anonymous_namespace{lang_geda.cc}::LANG_GSCHEM, anonymous_namespace{lang_verilog.cc}::LANG_VERILOG, anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE, and anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE.
Referenced by print_pair().
virtual std::string LANGUAGE::arg_front () const [pure virtual]
Implemented in anonymous_namespace{lang_geda.cc}::LANG_GSCHEM, anonymous_namespace{lang_verilog.cc}::LANG_VERILOG, anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE, and anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE.
Referenced by print_pair().
virtual std::string LANGUAGE::arg_mid () const [pure virtual]
Implemented in anonymous_namespace{lang_geda.cc}::LANG_GSCHEM, anonymous_namespace{lang_verilog.cc}::LANG_VERILOG, anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE, and anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE.
Referenced by print_pair().
virtual bool LANGUAGE::case_insensitive () const [pure virtual]
Implemented in anonymous_namespace{lang_spice.cc}::LANG_ACS, anonymous_namespace{lang_spice.cc}::LANG_SPICE, anonymous_namespace{lang_geda.cc}::LANG_GSCHEM, anonymous_namespace{lang_verilog.cc}::LANG_VERILOG, and anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE.
Referenced by OPT::set_values().
const CARD * LANGUAGE::find_proto (const std::string & Name, const CARD * Scope)
Definition at line 35 of file u_lang.cc.
References CARD_LIST::card_list, anonymous_namespace{c_attach.cc}::command_dispatcher, anonymous_namespace{d_admit.cc}::device_dispatcher, CARD_LIST::find_(), CARD::find_looking_out(), itested, model_dispatcher, anonymous_namespace{c_genrat.cc}::p, Umatch(), and untested.
Referenced by anonymous_namespace{lang_spectre.cc}::CMD_MODEL::do_it(), anonymous_namespace{lang_verilog.cc}::CMD_PARAMSET::do_it(), and new__instance().
{
  const CARD* p = NULL;
  if (Scope) {
    try {
      p = Scope->find_looking_out(Name);
    }catch (Exception_Cant_Find& e) {
      assert(!p);
    }
  }else{
    CARD_LIST::const_iterator i = CARD_LIST::card_list.find_(Name);
    if (i != CARD_LIST::card_list.end()) {
      p = *i;
    }else{
      assert(!p);
    }
  }
  if (p) {itested();
    return p;
  }else if ((p = command_dispatcher[Name])) {
    return new DEV_DOT; //BUG// memory leak
  }else if ((p = device_dispatcher[Name])) {
    return p;
  }else if ((p = model_dispatcher[Name])) {
    return p;
  }else{
    assert(!p);
    std::string s;
    /* */if (Umatch(Name, "b{uild} "))      {itested();  s = "build";}
    else if (Umatch(Name, "del{ete} "))     {            s = "delete";}
    else if (Umatch(Name, "fo{urier} "))    {            s = "fourier";}
    else if (Umatch(Name, "gen{erator} "))  {            s = "generator";}
    else if (Umatch(Name, "inc{lude} "))    {itested();  s = "include";}
    else if (Umatch(Name, "l{ist} "))       {            s = "list";}
    else if (Umatch(Name, "m{odify} "))     {            s = "modify";}
    else if (Umatch(Name, "opt{ions} "))    {            s = "options";}
    else if (Umatch(Name, "par{ameter} "))  {            s = "param";}
    else if (Umatch(Name, "pr{int} "))      {            s = "print";}
    else if (Umatch(Name, "q{uit} "))       {            s = "quit";}
    else if (Umatch(Name, "st{atus} "))     {            s = "status";}
    else if (Umatch(Name, "te{mperature} ")){untested(); s = "temperature";}
    else if (Umatch(Name, "tr{ansient} "))  {            s = "transient";}
    else if (Umatch(Name, "!"))             {untested(); s = "system";}
    else if (Umatch(Name, "<"))             {untested(); s = "<";}
    else if (Umatch(Name, ">"))             {untested(); s = ">";}
    else{ /* no shortcut available */
      s = Name;
    }
    if ((command_dispatcher[s])) {
      return new DEV_DOT; //BUG// we will look it up twice, //BUG// memory leak
    }else{
      return NULL;
    }
  }
}
virtual std::string LANGUAGE::find_type_in_string (CS &) [pure virtual]
Implemented in anonymous_namespace{lang_verilog.cc}::LANG_VERILOG, anonymous_namespace{lang_geda.cc}::LANG_GSCHEM, anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE, and anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE.
Referenced by new__instance(), anonymous_namespace{lang_geda.cc}::parse_pin(), anonymous_namespace{lang_spectre.cc}::parse_ports(), and anonymous_namespace{lang_geda.cc}::parse_symbol_file().
virtual std::string LANGUAGE::name () const [pure virtual]
Implemented in anonymous_namespace{lang_spice.cc}::LANG_ACS, anonymous_namespace{lang_spice.cc}::LANG_SPICE, anonymous_namespace{lang_geda.cc}::LANG_GSCHEM, anonymous_namespace{lang_verilog.cc}::LANG_VERILOG, and anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE.
Referenced by operator<<().
void LANGUAGE::new__instance (CS & cmd, MODEL_SUBCKT * owner, CARD_LIST * Scope)
Definition at line 92 of file u_lang.cc.
References CARD::clone_instance(), find_proto(), find_type_in_string(), CS::is_end(), parse_item(), CARD_LIST::push_back(), CARD::set_owner(), and CS::warn().
Referenced by anonymous_namespace{lang_geda.cc}::create_place(), anonymous_namespace{lang_geda.cc}::CMD_C::do_it(), and anonymous_namespace{lang_geda.cc}::parse_net().
{
  if (cmd.is_end()) {
    // nothing
  }else{
    std::string type = find_type_in_string(cmd);
    if (const CARD* proto = find_proto(type, owner)) {
      CARD* new_instance = proto->clone_instance();
      assert(new_instance);
      new_instance->set_owner(owner);
      CARD* x = parse_item(cmd, new_instance);
      if (x) {
        assert(Scope);
        Scope->push_back(x);
      }else{
      }
    }else{
      cmd.warn(bDANGER, type + ": no match");
    }
  }
}
virtual DEV_DOT* LANGUAGE::parse_command (CS & , DEV_DOT *) [pure virtual]
Implemented in anonymous_namespace{lang_verilog.cc}::LANG_VERILOG, anonymous_namespace{lang_geda.cc}::LANG_GSCHEM, anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE, and anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE.
Referenced by parse_item().
virtual DEV_COMMENT* LANGUAGE::parse_comment (CS & , DEV_COMMENT *) [pure virtual]
Implemented in anonymous_namespace{lang_verilog.cc}::LANG_VERILOG, anonymous_namespace{lang_geda.cc}::LANG_GSCHEM, anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE, and anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE.
Referenced by parse_item().
virtual COMPONENT* LANGUAGE::parse_instance (CS & , COMPONENT *) [pure virtual]
Implemented in anonymous_namespace{lang_verilog.cc}::LANG_VERILOG, anonymous_namespace{lang_geda.cc}::LANG_GSCHEM, anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE, and anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE.
Referenced by parse_item().
CARD * LANGUAGE::parse_item (CS & cmd, CARD * c) [virtual]
Definition at line 114 of file u_lang.cc.
References incomplete, parse_command(), parse_comment(), parse_instance(), parse_module(), parse_paramset(), unreachable, and untested.
Referenced by new__instance().
{
  // See Stroustrup 15.4.5
  // If you can think of a better way, tell me.
  // It must be in the LANGUAGE class, not CARD.
  if (dynamic_cast<MODEL_SUBCKT*>(c)) {
    return parse_module(cmd, prechecked_cast<MODEL_SUBCKT*>(c));
  }else if (dynamic_cast<COMPONENT*>(c)) {
    return parse_instance(cmd, prechecked_cast<COMPONENT*>(c));
  }else if (dynamic_cast<MODEL_CARD*>(c)) {
    return parse_paramset(cmd, prechecked_cast<MODEL_CARD*>(c));
  }else if (dynamic_cast< DEV_COMMENT*>(c)) {
    return parse_comment(cmd, prechecked_cast<DEV_COMMENT*>(c));
  }else if (dynamic_cast<DEV_DOT*>(c)) {
    return parse_command(cmd, prechecked_cast<DEV_DOT*>(c));
  }else{untested();
    incomplete();
    unreachable();
    return NULL;
  }
}
virtual MODEL_SUBCKT* LANGUAGE::parse_module (CS & , MODEL_SUBCKT *) [pure virtual]
Implemented in anonymous_namespace{lang_verilog.cc}::LANG_VERILOG, anonymous_namespace{lang_geda.cc}::LANG_GSCHEM, anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE, and anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE.
Referenced by parse_item().
virtual MODEL_CARD* LANGUAGE::parse_paramset (CS & , MODEL_CARD *) [pure virtual]
Implemented in anonymous_namespace{lang_verilog.cc}::LANG_VERILOG, anonymous_namespace{lang_geda.cc}::LANG_GSCHEM, anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE, and anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE.
Referenced by parse_item().
void LANGUAGE::parse_top_item (CS & cmd, CARD_LIST * Scope) [virtual]
Reimplemented in anonymous_namespace{lang_spice.cc}::LANG_SPICE, anonymous_namespace{lang_verilog.cc}::LANG_VERILOG, anonymous_namespace{lang_geda.cc}::LANG_GSCHEM, and anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE.
Definition at line 29 of file u_lang.cc.
References CMD::cmdproc(), CS::get_line(), and I_PROMPT.
Referenced by anonymous_namespace{c_file.cc}::CMD_INCLUDE::do_it(), and main().
{
  cmd.get_line(I_PROMPT);
  CMD::cmdproc(cmd, Scope);
}
virtual void LANGUAGE::print_command (OMSTREAM & , const DEV_DOT *) [private, pure virtual]
Implemented in anonymous_namespace{lang_verilog.cc}::LANG_VERILOG, anonymous_namespace{lang_geda.cc}::LANG_GSCHEM, anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE, and anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE.
Referenced by print_item().
virtual void LANGUAGE::print_comment (OMSTREAM & , const DEV_COMMENT *) [private, pure virtual]
Implemented in anonymous_namespace{lang_verilog.cc}::LANG_VERILOG, anonymous_namespace{lang_geda.cc}::LANG_GSCHEM, anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE, and anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE.
Referenced by print_item().
virtual void LANGUAGE::print_instance (OMSTREAM & , const COMPONENT *) [private, pure virtual]
Implemented in anonymous_namespace{lang_verilog.cc}::LANG_VERILOG, anonymous_namespace{lang_geda.cc}::LANG_GSCHEM, anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE, and anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE.
Referenced by print_item().
void LANGUAGE::print_item (OMSTREAM & o, const CARD * c) [virtual]
Definition at line 137 of file u_lang.cc.
References incomplete, print_command(), print_comment(), print_instance(), print_module(), print_paramset(), unreachable, and untested.
Referenced by anonymous_namespace{c_list.cc}::list_save().
{
  // See Stroustrup 15.4.5
  // If you can think of a better way, tell me.
  // It must be in the LANGUAGE class, not CARD.
  assert(c);
  assert(dynamic_cast<const CARD*>(c));
  if (dynamic_cast<const MODEL_SUBCKT*>(c)) {
    print_module(o, prechecked_cast<const MODEL_SUBCKT*>(c));
  }else if (dynamic_cast<const COMPONENT*>(c)) {
    print_instance(o, prechecked_cast<const COMPONENT*>(c));
  }else if (dynamic_cast<const MODEL_CARD*>(c)) {
    print_paramset(o, prechecked_cast<const MODEL_CARD*>(c));
  }else if (dynamic_cast<const DEV_COMMENT*>(c)) {
    print_comment(o, prechecked_cast<const DEV_COMMENT*>(c));
  }else if (dynamic_cast<const DEV_DOT*>(c)) {
    print_command(o, prechecked_cast<const DEV_DOT*>(c));
  }else{untested();
    incomplete();
    unreachable();
  }
}
virtual void LANGUAGE::print_module (OMSTREAM & , const MODEL_SUBCKT *) [private, pure virtual]
Implemented in anonymous_namespace{lang_verilog.cc}::LANG_VERILOG, anonymous_namespace{lang_geda.cc}::LANG_GSCHEM, anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE, and anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE.
Referenced by print_item().
virtual void LANGUAGE::print_paramset (OMSTREAM & , const MODEL_CARD *) [private, pure virtual]
Implemented in anonymous_namespace{lang_verilog.cc}::LANG_VERILOG, anonymous_namespace{lang_geda.cc}::LANG_GSCHEM, anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE, and anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE.
Referenced by print_item().
virtual UNITS LANGUAGE::units () const [pure virtual]
Implemented in anonymous_namespace{lang_spice.cc}::LANG_ACS, anonymous_namespace{lang_spice.cc}::LANG_SPICE, anonymous_namespace{lang_geda.cc}::LANG_GSCHEM, anonymous_namespace{lang_verilog.cc}::LANG_VERILOG, and anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE.
Referenced by OPT::set_values().
The documentation for this class was generated from the following files:
savant/gnucap/src/u_lang.h
savant/gnucap/src/u_lang.cc