gnucap: String Class Reference
String Class Reference
#include <m_base.h>
Public Member Functions
void parse (CS &)
String (CS &file)
String ()
String (const std::string &s)
operator const std::string & () const
std::string val_string () const
bool to_bool () const
Base * minus () const
Base * plus () const
Base * less (const String *X) const
Base * greater (const String *X) const
Base * leq (const String *X) const
Base * geq (const String *X) const
Base * not_equal (const String *X) const
Base * equal (const String *X) const
Base * add (const String *X) const
Base * multiply (const String *) const
Base * subtract (const String *) const
Base * r_subtract (const String *) const
Base * divide (const String *) const
Base * r_divide (const String *) const
Base * less (const Base *X) const
Base * greater (const Base *X) const
Base * leq (const Base *X) const
Base * geq (const Base *X) const
Base * not_equal (const Base *X) const
Base * equal (const Base *X) const
Base * add (const Base *X) const
Base * multiply (const Base *X) const
Base * subtract (const Base *X) const
Base * r_subtract (const Base *X) const
Base * divide (const Base *X) const
Base * r_divide (const Base *X) const
Base * less (const Float *) const
Base * greater (const Float *) const
Base * leq (const Float *) const
Base * geq (const Float *) const
Base * not_equal (const Float *) const
Base * equal (const Float *) const
Base * add (const Float *) const
Base * multiply (const Float *) const
Base * subtract (const Float *) const
Base * r_subtract (const Float *) const
Base * divide (const Float *) const
Base * r_divide (const Float *) const
Protected Attributes
std::string _data
Private Member Functions
void dump (std::ostream &o) const
Detailed Description
Definition at line 212 of file m_base.h.
Constructor & Destructor Documentation
String::String (CS & file) [inline, explicit]
Definition at line 222 of file m_base.h.
References parse(), and untested.
{untested();parse(file);}
String::String () [inline, explicit]
Definition at line 223 of file m_base.h.
Referenced by add().
{}
String::String (const std::string & s) [inline, explicit]
Definition at line 224 of file m_base.h.
:_data(s) {}
Member Function Documentation
Base* String::add (const String * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 238 of file m_base.h.
References _data, String(), and untested.
{untested();assert(X); return new String(_data + X->_data);}
Base* String::add (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 251 of file m_base.h.
References Base::add(), and untested.
{untested();return ((X) ? (X->add(this))       : (NULL));}
Base* String::add (const Float *) const [inline, virtual]
Reimplemented from Base.
Definition at line 264 of file m_base.h.
References untested.
{untested();return NULL;}
Base* String::divide (const String *) const [inline, virtual]
Reimplemented from Base.
Definition at line 242 of file m_base.h.
References untested.
{untested(); return NULL;}
Base* String::divide (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 255 of file m_base.h.
References Base::r_divide().
{           return ((X) ? (X->r_divide(this))  : (NULL));}
Base* String::divide (const Float *) const [inline, virtual]
Reimplemented from Base.
Definition at line 268 of file m_base.h.
References untested.
{untested();return NULL;}
void String::dump (std::ostream & o) const [inline, private, virtual]
Implements Base.
Definition at line 220 of file m_base.h.
References _data, and untested.
{untested();o << _data;}
Base* String::equal (const String * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 237 of file m_base.h.
References _data, and untested.
{untested();assert(X); return new Float((_data == X->_data)?1.:0.);}
Base* String::equal (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 250 of file m_base.h.
References Base::equal(), and untested.
{untested();return ((X) ? (X->equal(this))          : (NULL));}
Base* String::equal (const Float *) const [inline, virtual]
Reimplemented from Base.
Definition at line 263 of file m_base.h.
References untested.
{untested();return NULL;}
Base* String::geq (const String * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 235 of file m_base.h.
References _data, and untested.
{untested();assert(X); return new Float((_data >= X->_data)?1.:0.);}
Base* String::geq (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 248 of file m_base.h.
References Base::leq(), and untested.
{untested();return ((X) ? (X->leq(this))       : (NULL));}
Base* String::geq (const Float *) const [inline, virtual]
Reimplemented from Base.
Definition at line 261 of file m_base.h.
References untested.
{untested();return NULL;}
Base* String::greater (const String * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 233 of file m_base.h.
References _data, and untested.
{untested();assert(X); return new Float((_data > X->_data)?1.:0.);}
Base* String::greater (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 246 of file m_base.h.
References Base::less(), and untested.
{untested();return ((X) ? (X->less(this))      : (NULL));}
Base* String::greater (const Float *) const [inline, virtual]
Reimplemented from Base.
Definition at line 259 of file m_base.h.
References untested.
{untested();return NULL;}
Base* String::leq (const String * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 234 of file m_base.h.
References _data, and untested.
{untested();assert(X); return new Float((_data <= X->_data)?1.:0.);}
Base* String::leq (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 247 of file m_base.h.
References Base::geq(), and untested.
{untested();return ((X) ? (X->geq(this))       : (NULL));}
Base* String::leq (const Float *) const [inline, virtual]
Reimplemented from Base.
Definition at line 260 of file m_base.h.
References untested.
{untested();return NULL;}
Base* String::less (const String * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 232 of file m_base.h.
References _data, and untested.
{untested();assert(X); return new Float((_data < X->_data)?1.:0.);}
Base* String::less (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 245 of file m_base.h.
References Base::greater(), and untested.
{untested();return ((X) ? (X->greater(this))   : (NULL));}
Base* String::less (const Float *) const [inline, virtual]
Reimplemented from Base.
Definition at line 258 of file m_base.h.
References untested.
{untested();return NULL;}
Base* String::minus () const [inline, virtual]
Reimplemented from Base.
Definition at line 229 of file m_base.h.
References untested.
{untested(); return NULL;}
Base* String::multiply (const String *) const [inline, virtual]
Reimplemented from Base.
Definition at line 239 of file m_base.h.
References untested.
{untested(); return NULL;}
Base* String::multiply (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 252 of file m_base.h.
References Base::multiply(), and untested.
{untested();return ((X) ? (X->multiply(this))  : (NULL));}
Base* String::multiply (const Float *) const [inline, virtual]
Reimplemented from Base.
Definition at line 265 of file m_base.h.
References untested.
{untested();return NULL;}
Base* String::not_equal (const String * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 236 of file m_base.h.
References _data, and untested.
{untested();assert(X); return new Float((_data != X->_data)?1.:0.);}
Base* String::not_equal (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 249 of file m_base.h.
References Base::not_equal(), and untested.
{untested();return ((X) ? (X->not_equal(this)) : (NULL));}
Base* String::not_equal (const Float *) const [inline, virtual]
Reimplemented from Base.
Definition at line 262 of file m_base.h.
References untested.
{untested();return NULL;}
String::operator const std::string & () const [inline]
Definition at line 225 of file m_base.h.
References _data.
{return _data;}
void String::parse (CS &) [inline, virtual]
Implements Base.
Reimplemented in Tail_String, Quoted_String, and Name_String.
Definition at line 218 of file m_base.h.
References incomplete, and unreachable.
Referenced by String().
{unreachable(); incomplete();}
Base* String::plus () const [inline, virtual]
Reimplemented from Base.
Definition at line 230 of file m_base.h.
References untested.
{untested(); return NULL;}
Base* String::r_divide (const String *) const [inline, virtual]
Reimplemented from Base.
Definition at line 243 of file m_base.h.
References untested.
{untested(); return NULL;}
Base* String::r_divide (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 256 of file m_base.h.
References Base::divide(), and untested.
{untested();return ((X) ? (X->divide(this))    : (NULL));}
Base* String::r_divide (const Float *) const [inline, virtual]
Reimplemented from Base.
Definition at line 269 of file m_base.h.
References untested.
{untested();return NULL;}
Base* String::r_subtract (const String *) const [inline, virtual]
Reimplemented from Base.
Definition at line 241 of file m_base.h.
References untested.
{untested(); return NULL;}
Base* String::r_subtract (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 254 of file m_base.h.
References Base::subtract(), and untested.
{untested();return ((X) ? (X->subtract(this))  : (NULL));}
Base* String::r_subtract (const Float *) const [inline, virtual]
Reimplemented from Base.
Definition at line 267 of file m_base.h.
References untested.
{untested();return NULL;}
Base* String::subtract (const String *) const [inline, virtual]
Reimplemented from Base.
Definition at line 240 of file m_base.h.
References untested.
{untested(); return NULL;}
Base* String::subtract (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 253 of file m_base.h.
References Base::r_subtract(), and untested.
{untested();return ((X) ? (X->r_subtract(this)): (NULL));}
Base* String::subtract (const Float *) const [inline, virtual]
Reimplemented from Base.
Definition at line 266 of file m_base.h.
References untested.
{untested();return NULL;}
bool String::to_bool () const [inline, virtual]
Reimplemented from Base.
Definition at line 227 of file m_base.h.
References _data, and untested.
{untested();return (_data != "");}
std::string String::val_string () const [inline, virtual]
Reimplemented from Base.
Definition at line 226 of file m_base.h.
References _data, and untested.
{untested();return _data;}
Member Data Documentation
std::string String::_data [protected]
Definition at line 216 of file m_base.h.
Referenced by add(), dump(), equal(), geq(), greater(), leq(), less(), not_equal(), operator const std::string &(), Name_String::parse(), Quoted_String::parse(), Tail_String::parse(), to_bool(), and val_string().
The documentation for this class was generated from the following file:
savant/gnucap/src/m_base.h