gnucap: EVAL_BM_SEMI_RESISTOR Class Reference
EVAL_BM_SEMI_RESISTOR Class Reference
Public Member Functions
EVAL_BM_SEMI_RESISTOR (int c=0)
~EVAL_BM_SEMI_RESISTOR ()
Private Member Functions
EVAL_BM_SEMI_RESISTOR (const EVAL_BM_SEMI_RESISTOR &p)
bool operator== (const COMMON_COMPONENT &) const
COMMON_COMPONENT * clone () const
void expand (const COMPONENT *)
void precalc_last (const CARD_LIST *)
Detailed Description
Definition at line 71 of file bmm_semi.cc.
Constructor & Destructor Documentation
EVAL_BM_SEMI_RESISTOR::EVAL_BM_SEMI_RESISTOR (const EVAL_BM_SEMI_RESISTOR & p) [inline, explicit, private]
Definition at line 73 of file bmm_semi.cc.
Referenced by clone().
    :EVAL_BM_SEMI_BASE(p) {}
EVAL_BM_SEMI_RESISTOR::EVAL_BM_SEMI_RESISTOR (int c = 0) [inline, explicit]
Definition at line 76 of file bmm_semi.cc.
    :EVAL_BM_SEMI_BASE(c) {}
EVAL_BM_SEMI_RESISTOR::~EVAL_BM_SEMI_RESISTOR () [inline]
Definition at line 78 of file bmm_semi.cc.
{}
Member Function Documentation
COMMON_COMPONENT* EVAL_BM_SEMI_RESISTOR::clone () const [inline, private, virtual]
Implements EVAL_BM_SEMI_BASE.
Definition at line 81 of file bmm_semi.cc.
References EVAL_BM_SEMI_RESISTOR().
{return new EVAL_BM_SEMI_RESISTOR(*this);}
void EVAL_BM_SEMI_RESISTOR::expand (const COMPONENT * d) [private, virtual]
Reimplemented from EVAL_BM_SEMI_BASE.
Definition at line 301 of file bmm_semi.cc.
References CARD::long_label(), COMMON_COMPONENT::model(), COMMON_COMPONENT::modelname(), and unreachable.
{
  EVAL_BM_SEMI_BASE::expand(d);
  const MODEL_SEMI_RESISTOR* m = dynamic_cast<const MODEL_SEMI_RESISTOR*>(model());
  if (!m) {
    unreachable();
    throw Exception_Model_Type_Mismatch(d->long_label(), modelname(), "semi-resistor (R)");
  }else{
  }
}
bool EVAL_BM_SEMI_RESISTOR::operator== (const COMMON_COMPONENT & x) const [private, virtual]
Reimplemented from EVAL_BM_SEMI_BASE.
Definition at line 288 of file bmm_semi.cc.
References anonymous_namespace{c_genrat.cc}::p, and untested.
{
  const EVAL_BM_SEMI_RESISTOR*
    p = dynamic_cast<const EVAL_BM_SEMI_RESISTOR*>(&x);
  bool rv = p
    && EVAL_BM_SEMI_BASE::operator==(x);
  if (rv) {
    untested();
  }else{
  }
  return rv;
}
void EVAL_BM_SEMI_RESISTOR::precalc_last (const CARD_LIST * Scope) [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 313 of file bmm_semi.cc.
References MODEL_SEMI_BASE::_defw, EVAL_BM_SEMI_BASE::_length, MODEL_SEMI_BASE::_narrow, MODEL_SEMI_RESISTOR::_rsh, MODEL_SEMI_BASE::_tc1, MODEL_SEMI_BASE::_tc2, COMMON_COMPONENT::_temp_c, MODEL_CARD::_tnom_c, EVAL_BM_SEMI_BASE::_value, EVAL_BM_SEMI_BASE::_width, BIGBIG, COMMON_COMPONENT::model(), COMMON_COMPONENT::modelname(), NOT_INPUT, prechecked_cast, untested, and width.
{
  assert(Scope);
  EVAL_BM_SEMI_BASE::precalc_last(Scope);
  const MODEL_SEMI_RESISTOR* m = prechecked_cast<const MODEL_SEMI_RESISTOR*>(model());
  double width = (_width == NOT_INPUT) ? m->_defw : _width;
  double eff_width = width - m->_narrow;
  double eff_length = _length - m->_narrow;
  if (eff_width != 0.) {
    _value = m->_rsh * eff_length / eff_width;
  }else{untested();
    _value = BIGBIG;
  }
  double tempdiff = (_temp_c - m->_tnom_c);
  _value *= 1 + m->_tc1*tempdiff + m->_tc2*tempdiff*tempdiff;
  if (eff_width <= 0.) {untested();
    throw Exception_Precalc(modelname() + ": effective width is negative or zero\n");
  }else{
  }
  if (eff_length <= 0.) {
    throw Exception_Precalc(modelname() + ": effective length is negative or zero\n");
  }else{
  }
}
The documentation for this class was generated from the following file:
savant/gnucap/src/bmm_semi.cc