gnucap: anonymous_namespace{s_fo.cc}::FOURIER Class Reference
anonymous_namespace{s_fo.cc}::FOURIER Class Reference
Public Member Functions
void do_it (CS &, CARD_LIST *)
FOURIER ()
~FOURIER ()
Private Member Functions
FOURIER (const FOURIER &)
std::string status () const
void setup (CS &)
void fftallocate ()
void fftunallocate ()
void foout ()
void fohead (const PROBE &)
void foprint (COMPLEX *)
void store_results (double)
Private Attributes
PARAMETER< double > _fstart
PARAMETER< double > _fstop
PARAMETER< double > _fstep
int _timesteps
COMPLEX ** _fdata
Detailed Description
Definition at line 36 of file s_fo.cc.
Constructor & Destructor Documentation
anonymous_namespace{s_fo.cc}::FOURIER::FOURIER () [inline, explicit]
Definition at line 39 of file s_fo.cc.
                    :
    TRANSIENT(),
    _fstart(0.),
    _fstop(0.),
    _fstep(0.),
    _timesteps(0),
    _fdata(NULL)
  {
  }
anonymous_namespace{s_fo.cc}::FOURIER::~FOURIER () [inline]
Definition at line 48 of file s_fo.cc.
{}
anonymous_namespace{s_fo.cc}::FOURIER::FOURIER (const FOURIER &) [inline, explicit, private]
Definition at line 50 of file s_fo.cc.
References incomplete, and unreachable.
: TRANSIENT() {unreachable(); incomplete();}
Member Function Documentation
void anonymous_namespace{s_fo.cc}::FOURIER::do_it (CS & Cmd, CARD_LIST * Scope) [virtual]
Reimplemented from TRANSIENT.
Definition at line 72 of file s_fo.cc.
References error(), STATUS::four, OPT::gmin, itested, OPT::pivtol, rBATCH, TIMER::reset(), rINTERACTIVE, rPRE_MAIN, rPRESET, rSCRIPT, ENV::run_mode, STATUS::set_up, anonymous_namespace{c_sweep.cc}::setup(), TIMER::start(), status, TIMER::stop(), STATUS::total, unreachable, and untested.
{
  _scope = Scope;
  _sim->set_command_fourier();
  reset_timers();
  ::status.four.reset().start();
  try {
    _sim->init();
    _sim->alloc_vectors();
    _sim->_aa.reallocate();
    _sim->_aa.dezero(OPT::gmin);
    _sim->_aa.set_min_pivot(OPT::pivtol);
    _sim->_lu.reallocate();
    _sim->_lu.dezero(OPT::gmin);
    _sim->_lu.set_min_pivot(OPT::pivtol);
    setup(Cmd);
    fftallocate();
    ::status.set_up.stop();
    switch (ENV::run_mode) {untested();
    case rPRE_MAIN:     unreachable();          break;
    case rBATCH:        untested();
    case rINTERACTIVE:  itested();
    case rSCRIPT:       sweep(); foout();       break;
    case rPRESET:       untested(); /*nothing*/ break;
    }
  }catch (Exception& e) {itested();
    error(bDANGER, e.message() + '\n');
  }
  fftunallocate();
  _sim->unalloc_vectors();
  _sim->_lu.unallocate();
  _sim->_aa.unallocate();
  ::status.four.stop();
  ::status.total.stop();
}
void anonymous_namespace{s_fo.cc}::FOURIER::fftallocate () [private]
Definition at line 316 of file s_fo.cc.
{
  int probes = printlist().size();
  _fdata = new COMPLEX*[probes];
  for (int ii = 0;  ii < probes;  ++ii) {
    _fdata[ii] = new COMPLEX[_timesteps+100];
  }
}
void anonymous_namespace{s_fo.cc}::FOURIER::fftunallocate () [private]
Definition at line 327 of file s_fo.cc.
References itested.
{
  if (_fdata) {
    for (int ii = 0;  ii < printlist().size();  ++ii) {
      delete [] _fdata[ii];
    }
    delete [] _fdata;
    _fdata = NULL;
  }else{itested();
  }
}
void anonymous_namespace{s_fo.cc}::FOURIER::fohead (const PROBE & Prob) [private]
Definition at line 152 of file s_fo.cc.
References PROBE::label().
{
  _out.form("# %-10s", Prob.label().c_str())
    << "--------- actual ---------  -------- relative --------\n"
    << "#freq       "
    << "value        dB      phase  value        dB      phase\n";
}
void anonymous_namespace{s_fo.cc}::FOURIER::foout () [private]
Definition at line 135 of file s_fo.cc.
References fft(), anonymous_namespace{c_genrat.cc}::p, plclear(), and plclose().
{
  plclose();
  plclear();
  int ii = 0;
  for (PROBELIST::const_iterator
         p=printlist().begin();  p!=printlist().end();  ++p) {
    fohead(*p);
    fft(_fdata[ii], _timesteps-1,  0);
    foprint(_fdata[ii]);
    ++ii;
  }
}
void anonymous_namespace{s_fo.cc}::FOURIER::foprint (COMPLEX * Data) [private]
Definition at line 163 of file s_fo.cc.
References anonymous_namespace{s_fo.cc}::db(), anonymous_namespace{s_fo.cc}::find_max(), ftos(), phase(), anonymous_namespace{s_fo.cc}::stepnum(), and untested.
{
  int startstep = stepnum(0., _fstep, _fstart);
  assert(startstep >= 0);
  int stopstep  = stepnum(0., _fstep, _fstop );
  assert(stopstep < _timesteps);
  COMPLEX maxvalue = find_max(Data, std::max(1,startstep), stopstep);
  if (maxvalue == 0.) {untested();
    maxvalue = 1.;
  }else{
  }
  Data[0] /= 2;
  for (int ii = startstep;  ii <= stopstep;  ++ii) {
    double frequency = _fstep * ii;
    assert(ii >= 0);
    assert(ii < _timesteps);
    COMPLEX unscaled = Data[ii];
    COMPLEX scaled = unscaled / maxvalue;
    unscaled *= 2;
    _out.form("%s%s%7.2f %8.3f %s%7.2f %8.3f\n",
             ftos(frequency,    11,5,_out.format()),
        ftos(std::abs(unscaled),11,5,_out.format()),
             db(unscaled),
             phase(unscaled*COMPLEX(0.,1)),
        ftos(std::abs(scaled),  11,5,_out.format()),
             db(scaled),
             phase(scaled) ) ;
  }
}
void anonymous_namespace{s_fo.cc}::FOURIER::setup (CS & Cmd) [private, virtual]
Reimplemented from TRANSIENT.
Definition at line 223 of file s_fo.cc.
References PARAMETER< T >::e_val(), OPT::harmonics, PARAMETER< T >::has_hard_value(), CS::is_float(), CS::is_pfloat(), itested, CS::match1(), min(), anonymous_namespace{s_fo.cc}::to_pow_of_2(), and untested.
{
  _cont = true;
  if (Cmd.match1("'\"({") || Cmd.is_pfloat()) {
    PARAMETER<double> arg1, arg2, arg3;
    Cmd >> arg1;
    if (Cmd.match1("'\"({") || Cmd.is_float()) {
      Cmd >> arg2;
    }else{
    }
    if (Cmd.match1("'\"({") || Cmd.is_float()) {
      Cmd >> arg3;
    }else{
    }
    if (arg3.has_hard_value()) {            /* 3 args: all */
      assert(arg2.has_hard_value());
      assert(arg1.has_hard_value());
      _fstart = arg1;
      _fstop  = arg2;
      _fstep  = arg3;
    }else if (arg2.has_hard_value()) {untested(); /* 2 args: start = 0 */
      assert(arg1.has_hard_value());
      arg1.e_val(0.,_scope);
      arg2.e_val(0.,_scope);
      if (arg1 >= arg2) {untested();        /* 2 args: stop, step */
        _fstart = "NA";                     /*  (stop > step) */
        _fstop  = arg1;
        _fstep  = arg2;
      }else{untested(); /* arg1 < arg2 */    /* 2 args: step, stop */
        _fstart = "NA";
        _fstop  = arg2;
        _fstep  = arg1;
      }
    }else{
      assert(arg1.has_hard_value());
      arg1.e_val(0.,_scope);
      if (arg1 == 0.) {untested();          /* 1 arg: start */
        _fstart = 0.;
        /* _fstop unchanged */
        /* _fstep unchanged */
      }else{untested();                     /* 1 arg: step */
        _fstart = "NA";
        _fstop  = "NA";
        _fstep  = arg1;
      }
    }
  }else{itested();
    /* else (no args) : no change */
  }
  options(Cmd);
  _fstart.e_val(0., _scope);
  _fstep.e_val(0., _scope);
  _fstop.e_val(OPT::harmonics * _fstep, _scope);
  if (_fstep == 0.) {itested();
    throw Exception("frequency step = 0");
  }else{
  }
  if (_fstop == 0.) {untested();
    _fstop = OPT::harmonics * _fstep;
  }else{
  }
  _timesteps = to_pow_of_2(_fstop*2 / _fstep) + 1;
  if (_cold  ||  _sim->_last_time <= 0.) {
    _cont = false;
    _tstart = 0.;
  }else{
    _cont = true;
    _tstart = _sim->_last_time;
  }
  _tstop = _tstart + 1. / _fstep;
  _tstep = 1. / _fstep / (_timesteps-1);
  time1 = _sim->_time0 = _tstart;
  _sim->_freq = _fstep;
  _dtmax = std::min(double(_dtmax_in), _tstep / double(_skip_in));
  if (_dtmin_in.has_hard_value()) {
    _sim->_dtmin = _dtmin_in;
  }else if (_dtratio_in.has_hard_value()) {
    _sim->_dtmin = _dtmax / _dtratio_in;
  }else{
    // use smaller of soft values
    _sim->_dtmin = std::min(double(_dtmin_in), _dtmax/_dtratio_in);
  }
}
std::string anonymous_namespace{s_fo.cc}::FOURIER::status () const [inline, private, virtual]
Reimplemented from TRANSIENT.
Definition at line 51 of file s_fo.cc.
{return "";}
void anonymous_namespace{s_fo.cc}::FOURIER::store_results (double X) [private, virtual]
Reimplemented from SIM.
Definition at line 117 of file s_fo.cc.
References anonymous_namespace{c_genrat.cc}::p, TR::step_cause, SIM::store_results(), and untested.
{
  TRANSIENT::store_results(X);
  if (step_cause() == scUSER) {
    int ii = 0;
    for (PROBELIST::const_iterator
           p=printlist().begin();  p!=printlist().end();  ++p) {
      assert(_stepno < _timesteps);
      _fdata[ii][_stepno] = p->value();
      ++ii;
    }
  }else{untested();
  }
}
Member Data Documentation
COMPLEX** anonymous_namespace{s_fo.cc}::FOURIER::_fdata [private]
Definition at line 64 of file s_fo.cc.
PARAMETER<double> anonymous_namespace{s_fo.cc}::FOURIER::_fstart [private]
Definition at line 60 of file s_fo.cc.
PARAMETER<double> anonymous_namespace{s_fo.cc}::FOURIER::_fstep [private]
Definition at line 62 of file s_fo.cc.
PARAMETER<double> anonymous_namespace{s_fo.cc}::FOURIER::_fstop [private]
Definition at line 61 of file s_fo.cc.
int anonymous_namespace{s_fo.cc}::FOURIER::_timesteps [private]
Definition at line 63 of file s_fo.cc.
The documentation for this class was generated from the following file:
savant/gnucap/src/s_fo.cc