gnucap: anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL Class Reference
anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL Class Reference
Public Member Functions
EVAL_BM_PWL (int c=0)
~EVAL_BM_PWL ()
Private Member Functions
EVAL_BM_PWL (const EVAL_BM_PWL &p)
bool operator== (const COMMON_COMPONENT &) const
COMMON_COMPONENT * clone () const
void print_common_obsolete_callback (OMSTREAM &, LANGUAGE *) const
void precalc_first (const CARD_LIST *)
void precalc_last (const CARD_LIST *)
void tr_eval (ELEMENT *) const
TIME_PAIR tr_review (COMPONENT *)
std::string name () const
bool ac_too () const
bool parse_numlist (CS &)
bool parse_params_obsolete_callback (CS &)
void skip_type_tail (CS &cmd) const
Private Attributes
PARAMETER< double > _delta
PARAMETER< int > _smooth
std::vector< std::pair
< PARAMETER< double >
, PARAMETER< double > > > _raw_table
std::vector< DPAIR > _num_table
Detailed Description
Definition at line 35 of file bm_pwl.cc.
Constructor & Destructor Documentation
anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::EVAL_BM_PWL (const EVAL_BM_PWL & p) [explicit, private]
Definition at line 72 of file bm_pwl.cc.
  :EVAL_BM_ACTION_BASE(p),
   _delta(p._delta),
   _smooth(p._smooth),
   _raw_table(p._raw_table),
   _num_table(p._num_table)
{
}
anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::EVAL_BM_PWL (int c = 0) [explicit]
Definition at line 63 of file bm_pwl.cc.
  :EVAL_BM_ACTION_BASE(c),
   _delta(_default_delta),
   _smooth(_default_smooth),
   _raw_table(),
   _num_table()
{
}
anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::~EVAL_BM_PWL () [inline]
Definition at line 44 of file bm_pwl.cc.
{}
Member Function Documentation
bool anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::ac_too () const [inline, private, virtual]
Implements EVAL_BM_ACTION_BASE.
Definition at line 56 of file bm_pwl.cc.
{return false;}
COMMON_COMPONENT* anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::clone () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 47 of file bm_pwl.cc.
{return new EVAL_BM_PWL(*this);}
std::string anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::name () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 55 of file bm_pwl.cc.
Referenced by print_common_obsolete_callback().
{return "pwl";}
bool anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::operator== (const COMMON_COMPONENT & x) const [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 81 of file bm_pwl.cc.
References _delta, _num_table, _raw_table, _smooth, anonymous_namespace{c_genrat.cc}::p, and untested.
{
  const EVAL_BM_PWL* p = dynamic_cast<const EVAL_BM_PWL*>(&x);
  bool rv = p
    && _delta == p->_delta
    && _smooth == p->_smooth
    && _raw_table == p->_raw_table
    && _num_table == p->_num_table
    && EVAL_BM_ACTION_BASE::operator==(x);
  if (rv) {
    untested();
  }
  return rv;
}
bool anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::parse_numlist (CS & cmd) [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 173 of file bm_pwl.cc.
References _raw_table, CS::cursor(), CS::gotit(), anonymous_namespace{c_genrat.cc}::p, CS::reset(), CS::stuck(), and untested.
{
  unsigned start = cmd.cursor();
  unsigned here = cmd.cursor();
  for (;;) {
    unsigned start_of_pair = here;
    std::pair<PARAMETER<double>, PARAMETER<double> > p;
    //cmd >> key >> value;
    cmd >> p.first; // key
    if (cmd.stuck(&here)) {
      // no more, graceful finish
      break;
    }else{
      cmd >> p.second; // value
      if (cmd.stuck(&here)) {
        // ran out, but already have half of the pair
        // back up one, hoping somebody else knows what to do with it
        cmd.reset(start_of_pair);
        break;
      }else{
        _raw_table.push_back(p);
      }
    }
  }
  if (cmd.gotit(start)) {
  }else{
    untested();
  }
  return cmd.gotit(start);
}
bool anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::parse_params_obsolete_callback (CS & cmd) [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 204 of file bm_pwl.cc.
References _delta, _smooth, Get(), and ONE_OF.
{
  return ONE_OF
    || Get(cmd, "delta",  &_delta)
    || Get(cmd, "smooth", &_smooth)
    || EVAL_BM_ACTION_BASE::parse_params_obsolete_callback(cmd)
    ;
}
void anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::precalc_first (const CARD_LIST * Scope) [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 110 of file bm_pwl.cc.
References _delta, _raw_table, _smooth, PARAMETER< T >::e_val(), and anonymous_namespace{c_genrat.cc}::p.
{
  assert(Scope);
  EVAL_BM_ACTION_BASE::precalc_first(Scope);
  _delta.e_val(_default_delta, Scope);
  _smooth.e_val(_default_smooth, Scope);
  for (std::vector<std::pair<PARAMETER<double>,PARAMETER<double> > >::iterator
         p = _raw_table.begin();  p != _raw_table.end();  ++p) {
    p->first.e_val(0, Scope);
    p->second.e_val(0, Scope);
  }
}
void anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::precalc_last (const CARD_LIST * Scope) [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 124 of file bm_pwl.cc.
References _num_table, _raw_table, BIGBIG, anonymous_namespace{c_genrat.cc}::p, and to_string().
{
  assert(Scope);
  EVAL_BM_ACTION_BASE::precalc_last(Scope);
  double last = -BIGBIG;
  for (std::vector<std::pair<PARAMETER<double>,PARAMETER<double> > >::iterator
         p = _raw_table.begin();  p != _raw_table.end();  ++p) {
    if (last > p->first) {
      throw Exception_Precalc("PWL is out of order: (" + to_string(last)
                              + ", " + to_string(p->first) + ")\n");
    }else{
      DPAIR x(p->first, p->second);
      _num_table.push_back(x);
    }
    last = p->first;
  }
}
void anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::print_common_obsolete_callback (OMSTREAM & o, LANGUAGE * lang) const [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 96 of file bm_pwl.cc.
References _delta, _raw_table, _smooth, PARAMETER< T >::has_hard_value(), name(), anonymous_namespace{c_genrat.cc}::p, and print_pair().
{
  assert(lang);
  o << name() << '(';
  for (std::vector<std::pair<PARAMETER<double>,PARAMETER<double> > >::
         const_iterator p = _raw_table.begin(); p != _raw_table.end(); ++p) {
    o << p->first << ',' << p->second << ' ';
  }
  o << ')';
  print_pair(o, lang, "delta", _delta, _delta.has_hard_value());
  print_pair(o, lang, "smooth",_smooth,_smooth.has_hard_value());
  EVAL_BM_ACTION_BASE::print_common_obsolete_callback(o, lang);
}
void anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::skip_type_tail (CS & cmd) const [inline, private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 59 of file bm_pwl.cc.
References CS::umatch().
{cmd.umatch("(1)");}
void anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::tr_eval (ELEMENT * d) const [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 143 of file bm_pwl.cc.
References _num_table, ELEMENT::_y, COMPONENT::f_is_value(), interpolate(), EVAL_BM_ACTION_BASE::ioffset(), COMPONENT::is_source(), NOT_INPUT, EVAL_BM_ACTION_BASE::tr_final_adjust(), and FPOLY1::x.
{
  double ext = (d->is_source()) ? 0. : NOT_INPUT;
  d->_y[0] = interpolate(_num_table.begin(), _num_table.end(),
                       ioffset(d->_y[0].x), ext, ext);
  tr_final_adjust(&(d->_y[0]), d->f_is_value());
}
TIME_PAIR anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::tr_review (COMPONENT * d) [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 151 of file bm_pwl.cc.
References SIM_DATA::_dtmin, _num_table, CKT_BASE::_sim, COMPONENT::_time_by, ELEMENT::_y, BIGBIG, COMPONENT::is_source(), TIME_PAIR::min_event(), NEVER, prechecked_cast, untested, and FPOLY1::x.
{
  if (d->is_source()) {
    // index (x) is time
    ELEMENT* dd = prechecked_cast<ELEMENT*>(d);
    assert(dd);
    double x = dd->_y[0].x + d->_sim->_dtmin * .01;
    DPAIR here(x, BIGBIG);
    std::vector<DPAIR>::iterator begin = _num_table.begin();
    std::vector<DPAIR>::iterator end   = _num_table.end();
    std::vector<DPAIR>::iterator upper = upper_bound(begin, end, here);
    std::vector<DPAIR>::iterator lower = upper - 1;
    assert(x > lower->first);
    d->_time_by.min_event((x < upper->first) ? upper->first : NEVER);
  }else{untested();
    // index (x) is input
    // It's really needed here too, more work needed
  }
  return d->_time_by;
}
Member Data Documentation
PARAMETER<double> anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::_delta [private]
Definition at line 37 of file bm_pwl.cc.
Referenced by operator==(), parse_params_obsolete_callback(), precalc_first(), and print_common_obsolete_callback().
std::vector<DPAIR> anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::_num_table [private]
Definition at line 40 of file bm_pwl.cc.
Referenced by operator==(), precalc_last(), tr_eval(), and tr_review().
std::vector<std::pair<PARAMETER<double>,PARAMETER<double> > > anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::_raw_table [private]
Definition at line 39 of file bm_pwl.cc.
Referenced by operator==(), parse_numlist(), precalc_first(), precalc_last(), and print_common_obsolete_callback().
PARAMETER<int> anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::_smooth [private]
Definition at line 38 of file bm_pwl.cc.
Referenced by operator==(), parse_params_obsolete_callback(), precalc_first(), and print_common_obsolete_callback().
The documentation for this class was generated from the following file:
savant/gnucap/src/bm_pwl.cc