gnucap: SDP Class Reference
SDP Class Reference
#include <u_sdp.h>
Public Member Functions
SDP (const SDP &p)
~SDP ()
SDP (double Nom)
double operator() (double L, double W, double def, const CARD_LIST *scope) const
double nom () const
void set_nom (double n)
void set_w (double n)
void set_l (double n)
void set_p (double n)
void set_nom (const std::string &n)
void set_w (const std::string &n)
void set_l (const std::string &n)
void set_p (const std::string &n)
bool has_hard_value () const
bool has_good_value () const
bool has_value () const
bool w_has_value () const
bool l_has_value () const
bool p_has_value () const
std::string string () const
std::string w_string () const
std::string l_string () const
std::string p_string () const
Private Member Functions
SDP ()
Private Attributes
PARAMETER< double > _nom
PARAMETER< double > _ld
PARAMETER< double > _wd
PARAMETER< double > _pd
Detailed Description
Definition at line 35 of file u_sdp.h.
Constructor & Destructor Documentation
SDP::SDP () [inline, explicit, private]
Definition at line 43 of file u_sdp.h.
References unreachable.
{unreachable();}
SDP::SDP (const SDP & p) [inline, explicit]
Definition at line 45 of file u_sdp.h.
:_nom(p._nom),_ld(p._ld),_wd(p._wd),_pd(p._pd) {}
SDP::~SDP () [inline]
Definition at line 46 of file u_sdp.h.
{}
SDP::SDP (double Nom) [inline, explicit]
Definition at line 47 of file u_sdp.h.
:_nom(Nom), _ld(0.), _wd(0.), _pd(0.) {}
Member Function Documentation
bool SDP::has_good_value () const [inline]
Definition at line 64 of file u_sdp.h.
References _nom, and PARAMETER< T >::has_good_value().
Referenced by MODEL_BUILT_IN_MOS7::precalc_first().
{return _nom.has_good_value();}
bool SDP::has_hard_value () const [inline]
Definition at line 63 of file u_sdp.h.
References _nom, and PARAMETER< T >::has_hard_value().
{return _nom.has_hard_value();}
bool SDP::has_value () const [inline]
Definition at line 66 of file u_sdp.h.
References _nom, and PARAMETER< T >::has_hard_value().
Referenced by MODEL_BUILT_IN_MOS7::param_is_printable(), and MODEL_BUILT_IN_MOS8::param_is_printable().
{return _nom.has_hard_value();}
bool SDP::l_has_value () const [inline]
Definition at line 68 of file u_sdp.h.
References _ld, and PARAMETER< T >::has_hard_value().
Referenced by MODEL_BUILT_IN_MOS4::param_is_printable(), MODEL_BUILT_IN_MOS5::param_is_printable(), MODEL_BUILT_IN_MOS7::param_is_printable(), and MODEL_BUILT_IN_MOS8::param_is_printable().
{return _ld.has_hard_value();}
std::string SDP::l_string () const [inline]
Definition at line 73 of file u_sdp.h.
References _ld, and PARAMETER< T >::string().
Referenced by MODEL_BUILT_IN_MOS4::param_value(), MODEL_BUILT_IN_MOS5::param_value(), MODEL_BUILT_IN_MOS7::param_value(), and MODEL_BUILT_IN_MOS8::param_value().
{return _ld.string();}
double SDP::nom () const [inline]
Definition at line 53 of file u_sdp.h.
References _nom.
Referenced by SDP_BUILT_IN_MOS7::init(), SDP_BUILT_IN_MOS8::init(), MODEL_BUILT_IN_MOS7::precalc_first(), MODEL_BUILT_IN_MOS8::precalc_first(), TDP_BUILT_IN_MOS7::TDP_BUILT_IN_MOS7(), and TDP_BUILT_IN_MOS8::TDP_BUILT_IN_MOS8().
{return _nom;}
double SDP::operator() (double L, double W, double def, const CARD_LIST * scope) const [inline]
Definition at line 49 of file u_sdp.h.
References _ld, _nom, _pd, _wd, and PARAMETER< T >::e_val().
{
    return _nom.e_val(def,scope) + _ld.e_val(0.,scope)/L
      + _wd.e_val(0.,scope)/W + _pd.e_val(0.,scope)/(W*L);
  }
bool SDP::p_has_value () const [inline]
Definition at line 69 of file u_sdp.h.
References _pd, and PARAMETER< T >::has_hard_value().
Referenced by MODEL_BUILT_IN_MOS4::param_is_printable(), MODEL_BUILT_IN_MOS5::param_is_printable(), MODEL_BUILT_IN_MOS7::param_is_printable(), and MODEL_BUILT_IN_MOS8::param_is_printable().
{return _pd.has_hard_value();}
std::string SDP::p_string () const [inline]
Definition at line 74 of file u_sdp.h.
References _pd, and PARAMETER< T >::string().
Referenced by MODEL_BUILT_IN_MOS4::param_value(), MODEL_BUILT_IN_MOS5::param_value(), MODEL_BUILT_IN_MOS7::param_value(), and MODEL_BUILT_IN_MOS8::param_value().
{return _pd.string();}
void SDP::set_l (double n) [inline]
Definition at line 56 of file u_sdp.h.
References _ld, and untested.
Referenced by MODEL_BUILT_IN_MOS4::set_param_by_index(), MODEL_BUILT_IN_MOS5::set_param_by_index(), MODEL_BUILT_IN_MOS7::set_param_by_index(), and MODEL_BUILT_IN_MOS8::set_param_by_index().
{untested();_ld = n;}
void SDP::set_l (const std::string & n) [inline]
Definition at line 60 of file u_sdp.h.
References _ld.
{_ld = n;}
void SDP::set_nom (double n) [inline]
Definition at line 54 of file u_sdp.h.
References _nom, and untested.
Referenced by MODEL_BUILT_IN_MOS7::precalc_first(), MODEL_BUILT_IN_MOS8::precalc_first(), MODEL_BUILT_IN_MOS4::set_param_by_index(), MODEL_BUILT_IN_MOS5::set_param_by_index(), MODEL_BUILT_IN_MOS7::set_param_by_index(), and MODEL_BUILT_IN_MOS8::set_param_by_index().
{untested();_nom = n;}
void SDP::set_nom (const std::string & n) [inline]
Definition at line 58 of file u_sdp.h.
References _nom.
{_nom = n;}
void SDP::set_p (double n) [inline]
Definition at line 57 of file u_sdp.h.
References _pd, and untested.
Referenced by MODEL_BUILT_IN_MOS4::set_param_by_index(), MODEL_BUILT_IN_MOS5::set_param_by_index(), MODEL_BUILT_IN_MOS7::set_param_by_index(), and MODEL_BUILT_IN_MOS8::set_param_by_index().
{untested();_pd = n;}
void SDP::set_p (const std::string & n) [inline]
Definition at line 61 of file u_sdp.h.
References _pd, and itested.
{itested();_pd = n;}
void SDP::set_w (double n) [inline]
Definition at line 55 of file u_sdp.h.
References _wd, and untested.
Referenced by MODEL_BUILT_IN_MOS4::set_param_by_index(), MODEL_BUILT_IN_MOS5::set_param_by_index(), MODEL_BUILT_IN_MOS7::set_param_by_index(), and MODEL_BUILT_IN_MOS8::set_param_by_index().
{untested();_wd = n;}
void SDP::set_w (const std::string & n) [inline]
Definition at line 59 of file u_sdp.h.
References _wd.
{_wd = n;}
std::string SDP::string () const [inline]
Definition at line 71 of file u_sdp.h.
References _nom, and PARAMETER< T >::string().
Referenced by MODEL_BUILT_IN_MOS4::param_value(), MODEL_BUILT_IN_MOS5::param_value(), MODEL_BUILT_IN_MOS7::param_value(), and MODEL_BUILT_IN_MOS8::param_value().
{return _nom.string();}
bool SDP::w_has_value () const [inline]
Definition at line 67 of file u_sdp.h.
References _wd, and PARAMETER< T >::has_hard_value().
Referenced by MODEL_BUILT_IN_MOS4::param_is_printable(), MODEL_BUILT_IN_MOS5::param_is_printable(), MODEL_BUILT_IN_MOS7::param_is_printable(), and MODEL_BUILT_IN_MOS8::param_is_printable().
{return _wd.has_hard_value();}
std::string SDP::w_string () const [inline]
Definition at line 72 of file u_sdp.h.
References _wd, and PARAMETER< T >::string().
Referenced by MODEL_BUILT_IN_MOS4::param_value(), MODEL_BUILT_IN_MOS5::param_value(), MODEL_BUILT_IN_MOS7::param_value(), and MODEL_BUILT_IN_MOS8::param_value().
{return _wd.string();}
Member Data Documentation
PARAMETER<double> SDP::_ld [private]
Definition at line 39 of file u_sdp.h.
Referenced by l_has_value(), l_string(), operator()(), and set_l().
PARAMETER<double> SDP::_nom [private]
Definition at line 38 of file u_sdp.h.
Referenced by has_good_value(), has_hard_value(), has_value(), nom(), operator()(), set_nom(), and string().
PARAMETER<double> SDP::_pd [private]
Definition at line 41 of file u_sdp.h.
Referenced by operator()(), p_has_value(), p_string(), and set_p().
PARAMETER<double> SDP::_wd [private]
Definition at line 40 of file u_sdp.h.
Referenced by operator()(), set_w(), w_has_value(), and w_string().
The documentation for this class was generated from the following file:
savant/gnucap/src/u_sdp.h