gnucap: PROBE Class Reference
PROBE Class Reference
#include <u_probe.h>
Public Member Functions
PROBE (const std::string &what, const CKT_BASE *brh)
PROBE (const PROBE &p)
~PROBE ()
void set_limit (double Lo, double Hi)
void detach ()
PROBE & operator= (const PROBE &p)
const std::string label () const
double value () const
const CKT_BASE * object () const
double lo () const
double hi () const
double range () const
bool in_range () const
Private Member Functions
double probe_node () const
Private Attributes
std::string _what
const CKT_BASE * _brh
double _lo
double _hi
Detailed Description
Definition at line 31 of file u_probe.h.
Constructor & Destructor Documentation
PROBE::PROBE (const std::string & what, const CKT_BASE * brh) [explicit]
Definition at line 30 of file u_probe.cc.
References _brh, and CKT_BASE::inc_probes().
  :_what(what),
   _brh(brh),
   _lo(0.),
   _hi(0.)
{
  if (_brh) {
    _brh->inc_probes();
  }else{
  }
}
PROBE::PROBE (const PROBE & p)
Definition at line 42 of file u_probe.cc.
References _brh, and CKT_BASE::inc_probes().
  :_what(p._what),
   _brh(p._brh),
   _lo(p._lo),
   _hi(p._hi)
{
  if (_brh) {
    _brh->inc_probes();
  }else{
  }
}
PROBE::~PROBE () [inline]
Definition at line 39 of file u_probe.h.
{detach();}
Member Function Documentation
void PROBE::detach ()
Definition at line 76 of file u_probe.cc.
References _brh, _what, and CKT_BASE::dec_probes().
Referenced by operator=().
{
  if (_brh) {
    _brh->dec_probes();
  }else{
  }
  _what = "";
  _brh = 0;
}
double PROBE::hi () const [inline]
Definition at line 49 of file u_probe.h.
Referenced by calibrate().
{return _hi;}
bool PROBE::in_range () const [inline]
Definition at line 51 of file u_probe.h.
References in_order().
{return in_order(lo(),value(),hi());}
const std::string PROBE::label (void) const
Definition at line 90 of file u_probe.cc.
References _brh, _what, and CKT_BASE::long_label().
Referenced by calibrate(), anonymous_namespace{s_fo.cc}::FOURIER::fohead(), and operator==().
{
  if (_brh) {
    return _what + '(' + _brh->long_label() + ')';
  }else{
    return _what + "(0)";
  }
}
double PROBE::lo () const [inline]
Definition at line 48 of file u_probe.h.
Referenced by calibrate().
{return _lo;}
const CKT_BASE* PROBE::object () const [inline]
Definition at line 47 of file u_probe.h.
Referenced by operator!=(), and operator==().
{return _brh;}
PROBE & PROBE::operator= (const PROBE & p)
Definition at line 57 of file u_probe.cc.
References _brh, _hi, _lo, _what, detach(), CKT_BASE::inc_probes(), and untested.
{
  detach();
  _what = p._what;
  _brh  = p._brh;
  _lo   = p._lo;
  _hi   = p._hi;
  if (_brh) {
    _brh->inc_probes();
  }else{untested();
  }
  return *this;
}
double PROBE::probe_node (void) const [private]
Definition at line 109 of file u_probe.cc.
References SIM_DATA::_bypass_ok, SIM_DATA::_damp, SIM_DATA::_genout, SIM_DATA::_iter, CKT_BASE::_sim, SIM_DATA::_temp_c, SIM_DATA::_time0, _what, OPT::bypass, STATUS::control, STATUS::hidden_steps, iCOUNT, iPRINTSTEP, iSTEP, iTOTAL, NOT_VALID, sCOUNT, status, Umatch(), and untested.
Referenced by value().
{
  if (Umatch(_what, "iter ")) {
    assert(iPRINTSTEP - sCOUNT == 0);
    assert(iSTEP      - sCOUNT == 1);
    assert(iTOTAL     - sCOUNT == 2);
    assert(iCOUNT     - sCOUNT == 3);
    return CKT_BASE::_sim->_iter[sCOUNT];
  }else if (Umatch(_what, "bypass ")) {untested();
    return OPT::bypass + 10*CKT_BASE::_sim->_bypass_ok;
  }else if (Umatch(_what, "control ")) {
    return ::status.control;
  }else if (Umatch(_what, "damp ")) {untested();
    return CKT_BASE::_sim->_damp;
  }else if (Umatch(_what, "gen{erator} ")) {untested();
    return CKT_BASE::_sim->_genout;
  }else if (Umatch(_what, "hidden ")) {untested();
    return ::status.hidden_steps;
  }else if (Umatch(_what, "temp{erature} ")) {untested();
    return CKT_BASE::_sim->_temp_c;
  }else if (Umatch(_what, "time ")) {untested();
    return CKT_BASE::_sim->_time0;
  }else{
    return NOT_VALID;
  }
}
double PROBE::range () const [inline]
Definition at line 50 of file u_probe.h.
Referenced by calibrate().
{return hi()-lo();}
void PROBE::set_limit (double Lo, double Hi) [inline]
Definition at line 41 of file u_probe.h.
{_lo = Lo; _hi = Hi;}
double PROBE::value (void) const
Definition at line 99 of file u_probe.cc.
References _brh, _what, probe_node(), and CKT_BASE::probe_num().
{
  // _brh is either a node or a "branch", which is really any device
  if (_brh) {
    return _brh->probe_num(_what);
  }else{
    return probe_node();
  }
}
Member Data Documentation
const CKT_BASE* PROBE::_brh [private]
Definition at line 34 of file u_probe.h.
Referenced by detach(), label(), operator=(), PROBE(), and value().
double PROBE::_hi [private]
Definition at line 35 of file u_probe.h.
Referenced by operator=().
double PROBE::_lo [private]
Definition at line 35 of file u_probe.h.
Referenced by operator=().
std::string PROBE::_what [private]
Definition at line 33 of file u_probe.h.
Referenced by detach(), label(), operator=(), probe_node(), and value().
The documentation for this class was generated from the following files:
savant/gnucap/src/u_probe.h
savant/gnucap/src/u_probe.cc