gnucap: anonymous_namespace{s_fo.cc} Namespace Reference
anonymous_namespace{s_fo.cc} Namespace Reference
Classes
class FOURIER
Functions
static int to_pow_of_2 (double)
static int stepnum (double, double, double)
static COMPLEX find_max (COMPLEX *, int, int)
static double db (COMPLEX)
Variables
static FOURIER p3
DISPATCHER< CMD >::INSTALL d3 & command_dispatcher
Function Documentation
static double anonymous_namespace{s_fo.cc}::db (COMPLEX Value) [static]
Definition at line 214 of file s_fo.cc.
References VOLTMIN.
Referenced by anonymous_namespace{s_fo.cc}::FOURIER::foprint().
{
  return  20. * log10(std::max(std::abs(Value),VOLTMIN));
}
static COMPLEX anonymous_namespace{s_fo.cc}::find_max (COMPLEX * Data, int Start, int Stop) [static]
Definition at line 202 of file s_fo.cc.
Referenced by anonymous_namespace{s_fo.cc}::FOURIER::foprint().
{
  COMPLEX maxvalue = 0.;
  for (int ii = Start;  ii <= Stop;  ++ii) {
    if (std::abs(Data[ii]) > std::abs(maxvalue)) {
      maxvalue = Data[ii];
    }else{
    }
  }
  return maxvalue;
}
static int anonymous_namespace{s_fo.cc}::stepnum (double Start, double Step, double Here) [static]
Definition at line 195 of file s_fo.cc.
Referenced by anonymous_namespace{s_fo.cc}::FOURIER::foprint().
{
  return int((Here-Start)/Step + .5);
}
static int anonymous_namespace{s_fo.cc}::to_pow_of_2 (double Z) [static]
Definition at line 342 of file s_fo.cc.
Referenced by anonymous_namespace{s_fo.cc}::FOURIER::setup().
{
  int x = static_cast<int>(floor(Z));
  int y;
  for (y = 1; x > 0; x >>= 1) {
    y <<= 1;
  }
  return y;
}
Variable Documentation
DISPATCHER<CMD>::INSTALL d3& anonymous_namespace{s_fo.cc}::command_dispatcher
Definition at line 353 of file s_fo.cc.
FOURIER anonymous_namespace{s_fo.cc}::p3 [static]
Definition at line 352 of file s_fo.cc.