gnucap: SIM_DATA Struct Reference
SIM_DATA Struct Reference
#include <u_sim_data.h>
Public Member Functions
SIM_DATA ()
bool is_first_expand ()
void alloc_hold_vectors ()
void alloc_vectors ()
void unalloc_vectors ()
void init ()
void uninit ()
void set_limit ()
void set_limit (double v)
void clear_limit ()
void keep_voltages ()
void restore_voltages ()
void zero_voltages ()
void map__nodes ()
void order_reverse ()
void order_forward ()
void order_auto ()
int init_node_count (int user, int sub, int mod)
int newnode_subckt ()
int newnode_model ()
bool is_inc_mode ()
bool inc_mode_is_no ()
bool inc_mode_is_bad ()
void set_inc_mode_bad ()
void set_inc_mode_yes ()
void set_inc_mode_no ()
void mark_inc_mode_bad ()
void new_event (double etime)
void set_command_none ()
void set_command_ac ()
void set_command_dc ()
void set_command_op ()
void set_command_tran ()
void set_command_fourier ()
SIM_MODE sim_mode ()
bool command_is_ac ()
bool command_is_dc ()
bool command_is_op ()
bool analysis_is_ac ()
bool analysis_is_dcop ()
bool analysis_is_static ()
bool analysis_is_restore ()
bool analysis_is_tran ()
bool analysis_is_tran_static ()
bool analysis_is_tran_restore ()
bool analysis_is_tran_dynamic ()
void reset_iteration_counter (int i)
void count_iterations (int i)
int iteration_tag () const
int iteration_number () const
bool is_initial_step ()
bool is_advance_iteration () const
bool is_advance_or_first_iteration () const
bool is_first_iteration () const
bool is_second_iteration () const
bool is_iteration_number (int n) const
bool exceeds_iteration_limit (OPT::ITL itlnum) const
bool uic_now ()
Public Attributes
double _time0
double _freq
double _temp_c
double _damp
double _dtmin
double _genout
bool _bypass_ok
bool _fulldamp
double _last_time
bool _freezetime
int _iter [iCOUNT]
int _user_nodes
int _subckt_nodes
int _model_nodes
int _total_nodes
COMPLEX _jomega
bool _limiting
double _vmax
double _vmin
bool _uic
TRI_STATE _inc_mode
SIM_MODE _mode
SIM_PHASE _phase
int * _nm
double * _i
double * _v0
double * _vt1
COMPLEX * _ac
LOGIC_NODE * _nstat
double * _vdc
BSMATRIX< double > _aa
BSMATRIX< double > _lu
BSMATRIX< COMPLEX > _acx
std::priority_queue< double,
std::vector< double > > _eq
std::vector< CARD * > _loadq
std::vector< CARD * > _acceptq
std::deque< CARD * > _evalq1
std::deque< CARD * > _evalq2
std::deque< CARD * > _late_evalq
std::deque< CARD * > * _evalq
std::deque< CARD * > * _evalq_uc
WAVE * _waves
Detailed Description
Definition at line 39 of file u_sim_data.h.
Constructor & Destructor Documentation
SIM_DATA::SIM_DATA () [inline]
Definition at line 83 of file u_sim_data.h.
             {
    _evalq = &_evalq1;
    _evalq_uc = &_evalq2;
  }
Member Function Documentation
void SIM_DATA::alloc_hold_vectors ()
Definition at line 165 of file u_sim_data.cc.
References _nm, _nstat, _total_nodes, _vdc, is_first_expand(), and NODE::set_user_number().
Referenced by init().
{
  assert(is_first_expand());
  assert(!_nstat);
  _nstat = new LOGIC_NODE[_total_nodes+1];
  for (int ii=0;  ii <= _total_nodes;  ++ii) {
    _nstat[_nm[ii]].set_user_number(ii);
  }
  assert(!_vdc);
  _vdc = new double[_total_nodes+1];
  std::fill_n(_vdc, _total_nodes+1, 0);
  assert(_nstat);
  assert(_vdc);
}
void SIM_DATA::alloc_vectors ()
Definition at line 186 of file u_sim_data.cc.
References _ac, _evalq, _evalq1, _evalq2, _evalq_uc, _i, _total_nodes, _v0, and _vt1.
Referenced by SIM::command_base().
{
  assert(_evalq1.empty());
  assert(_evalq2.empty());
  assert(_evalq != _evalq_uc);
  assert(!_ac);
  assert(!_i);
  assert(!_v0);
  assert(!_vt1);
  _ac = new COMPLEX[_total_nodes+1];
  _i   = new double[_total_nodes+1];
  _v0  = new double[_total_nodes+1];
  _vt1 = new double[_total_nodes+1];
  std::fill_n(_ac, _total_nodes+1, 0);
  std::fill_n(_i,  _total_nodes+1, 0);
  std::fill_n(_v0, _total_nodes+1, 0);
  std::fill_n(_vt1,_total_nodes+1, 0);
}
bool SIM_DATA::analysis_is_ac () [inline]
Definition at line 139 of file u_sim_data.h.
References s_AC.
Referenced by CKT_BASE::probe_num(), and DEV_SPICE::tr_accept().
{return _mode == s_AC;}
bool SIM_DATA::analysis_is_dcop () [inline]
Definition at line 140 of file u_sim_data.h.
References s_DC, and s_OP.
Referenced by DEV_SPICE::tr_accept().
{return _mode == s_DC || _mode == s_OP;}
bool SIM_DATA::analysis_is_restore () [inline]
Definition at line 142 of file u_sim_data.h.
References p_RESTORE.
Referenced by LOGIC_NODE::force_initial_value(), LOGIC_NODE::to_logic(), DEV_LOGIC::tr_accept(), STORAGE::tr_c_to_g(), DEV_LOGIC::tr_eval_digital(), and DEV_LOGIC::tr_needs_eval().
{return _phase == p_RESTORE;}
bool SIM_DATA::analysis_is_static () [inline]
Definition at line 141 of file u_sim_data.h.
References p_DC_SWEEP, and p_INIT_DC.
Referenced by anonymous_namespace{d_switch.cc}::SWITCH_BASE::do_tr(), LOGIC_NODE::force_initial_value(), LOGIC_NODE::to_logic(), DEV_LOGIC::tr_accept(), STORAGE::tr_c_to_g(), DEV_LOGIC::tr_eval_digital(), and DEV_LOGIC::tr_needs_eval().
{return _phase == p_INIT_DC || _phase == p_DC_SWEEP;}
bool SIM_DATA::analysis_is_tran () [inline]
Definition at line 143 of file u_sim_data.h.
References s_FOURIER, and s_TRAN.
Referenced by MODEL_SPICE::init_ckt().
{return _mode == s_TRAN || _mode == s_FOURIER;}
bool SIM_DATA::analysis_is_tran_dynamic () [inline]
Definition at line 146 of file u_sim_data.h.
References p_TRAN.
Referenced by DEV_SPICE::do_tr(), TRANSIENT::next(), LOGIC_NODE::set_event(), STORAGE::tr_c_to_g(), and DEV_LOGIC::tr_eval_digital().
{return analysis_is_tran() && _phase == p_TRAN;}
bool SIM_DATA::analysis_is_tran_restore () [inline]
Definition at line 145 of file u_sim_data.h.
References p_RESTORE.
Referenced by DEV_SPICE::do_tr().
{return analysis_is_tran() && _phase == p_RESTORE;}
bool SIM_DATA::analysis_is_tran_static () [inline]
Definition at line 144 of file u_sim_data.h.
References p_INIT_DC.
Referenced by DEV_SPICE::do_tr().
{return analysis_is_tran() && _phase == p_INIT_DC;}
void SIM_DATA::clear_limit ()
Definition at line 49 of file u_sim_data.cc.
References _vmax, _vmin, OPT::vmax, and OPT::vmin.
Referenced by anonymous_namespace{s_dc.cc}::DCOP::sweep(), and TRANSIENT::sweep().
{
  _vmax = OPT::vmax;
  _vmin = OPT::vmin;
}
bool SIM_DATA::command_is_ac () [inline]
Definition at line 134 of file u_sim_data.h.
References s_AC.
Referenced by MODEL_SPICE::init_ckt().
{return _mode == s_AC;}
bool SIM_DATA::command_is_dc () [inline]
Definition at line 135 of file u_sim_data.h.
References s_DC.
Referenced by DEV_SPICE::do_tr(), and MODEL_SPICE::init_ckt().
{return _mode == s_DC;}
bool SIM_DATA::command_is_op () [inline]
Definition at line 136 of file u_sim_data.h.
References s_OP.
Referenced by DEV_SPICE::do_tr(), and MODEL_SPICE::init_ckt().
{return _mode == s_OP;}
void SIM_DATA::count_iterations (int i) [inline]
Definition at line 149 of file u_sim_data.h.
References iCOUNT, and up_order().
Referenced by SIM::command_base(), TRANSIENT::review(), and SIM::solve().
{assert(up_order(0,i,iCOUNT-1)); ++_iter[i];}
bool SIM_DATA::exceeds_iteration_limit (OPT::ITL itlnum) const [inline]
Definition at line 158 of file u_sim_data.h.
References iSTEP, and OPT::itl.
Referenced by TRANSIENT::next(), and SIM::solve().
{return(_iter[iSTEP] > OPT::itl[itlnum]);}
bool SIM_DATA::inc_mode_is_bad () [inline]
Definition at line 110 of file u_sim_data.h.
References tsBAD.
Referenced by SIM::set_flags().
{return _inc_mode == tsBAD;}
bool SIM_DATA::inc_mode_is_no () [inline]
Definition at line 109 of file u_sim_data.h.
References tsNO.
{return _inc_mode == tsNO;}
void SIM_DATA::init ()
Definition at line 136 of file u_sim_data.cc.
References _aa, _acx, _last_time, _lu, _total_nodes, CARD_LIST::ac_iwant_matrix(), alloc_hold_vectors(), CARD_LIST::card_list, CARD_LIST::expand(), init_node_count(), is_first_expand(), map__nodes(), CARD_LIST::map_nodes(), CARD_LIST::precalc_first(), CARD_LIST::precalc_last(), BSMATRIX< T >::reinit(), CARD_LIST::tr_iwant_matrix(), and uninit().
Referenced by SIM::command_base(), and anonymous_namespace{c_prbcmd.cc}::do_probe().
{
  if (is_first_expand()) {
    uninit();
    init_node_count(CARD_LIST::card_list.nodes()->how_many(), 0, 0);
    CARD_LIST::card_list.expand();
    CARD_LIST::card_list.precalc_last();
    map__nodes();
    CARD_LIST::card_list.map_nodes();
    alloc_hold_vectors();
    _aa.reinit(_total_nodes);
    _lu.reinit(_total_nodes);
    _acx.reinit(_total_nodes);
    CARD_LIST::card_list.tr_iwant_matrix();
    CARD_LIST::card_list.ac_iwant_matrix();
    _last_time = 0;
  }else{
    CARD_LIST::card_list.precalc_first();
    CARD_LIST::card_list.precalc_last();
  }
}
int SIM_DATA::init_node_count (int user, int sub, int mod) [inline]
Definition at line 103 of file u_sim_data.h.
Referenced by init().
{
    _user_nodes=user; _subckt_nodes=sub; _model_nodes=mod; return (_total_nodes=user+sub+mod);
  }
bool SIM_DATA::is_advance_iteration () const [inline]
Definition at line 153 of file u_sim_data.h.
References iSTEP.
Referenced by DEV_SPICE::tr_needs_eval().
{return (_iter[iSTEP] == 0);}
bool SIM_DATA::is_advance_or_first_iteration () const [inline]
Definition at line 154 of file u_sim_data.h.
References iSTEP.
Referenced by ELEMENT::dampdiff(), and STORAGE::tr_needs_eval().
{assert(_iter[iSTEP]>=0); return (_iter[iSTEP]<=1);}
bool SIM_DATA::is_first_expand () [inline]
Definition at line 87 of file u_sim_data.h.
Referenced by alloc_hold_vectors(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::expand(), DEV_LOGIC::expand(), DEV_SPICE::expand(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::expand_last(), init(), ELEMENT::precalc_last(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::precalc_last(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::precalc_last(), and CARD::renew_subckt().
{return !_nstat;}
bool SIM_DATA::is_first_iteration () const [inline]
Definition at line 155 of file u_sim_data.h.
References iSTEP.
Referenced by DEV_SPICE::do_tr(), and SIM::set_damp().
{assert(_iter[iSTEP] > 0); return (_iter[iSTEP] == 1);}
bool SIM_DATA::is_inc_mode () [inline]
Definition at line 108 of file u_sim_data.h.
Referenced by SIM::clear_arrays(), ELEMENT::dampdiff(), SIM::load_matrix(), SIM::solve_equations(), and anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_load().
{return _inc_mode;}
bool SIM_DATA::is_initial_step () [inline]
Definition at line 152 of file u_sim_data.h.
Referenced by DEV_SPICE::do_tr().
{return (_iter[_mode] <= 1  && analysis_is_static());}
bool SIM_DATA::is_iteration_number (int n) const [inline]
Definition at line 157 of file u_sim_data.h.
References iSTEP.
Referenced by SIM::set_flags().
{return (_iter[iSTEP] == n);}
bool SIM_DATA::is_second_iteration () const [inline]
Definition at line 156 of file u_sim_data.h.
References iSTEP.
Referenced by SIM::set_damp().
{assert(_iter[iSTEP] > 0); return (_iter[iSTEP] == 2);}
int SIM_DATA::iteration_number () const [inline]
Definition at line 151 of file u_sim_data.h.
References iSTEP.
Referenced by SIM::solve().
{return _iter[iSTEP];}
int SIM_DATA::iteration_tag () const [inline]
Definition at line 150 of file u_sim_data.h.
References iTOTAL.
Referenced by CARD::evaluated(), DEV_LOGIC::tr_accept(), DEV_SPICE::tr_load(), and ELEMENT::tr_load_source().
{return _iter[iTOTAL];}
void SIM_DATA::keep_voltages ()
Definition at line 55 of file u_sim_data.cc.
References _freezetime, _last_time, _time0, _total_nodes, _v0, _vdc, and untested.
Referenced by TRANSIENT::sweep(), and anonymous_namespace{s_dc.cc}::DCOP::sweep_recursive().
{
  if (!_freezetime) {
    for (int ii = 1;  ii <= _total_nodes;  ++ii) {
      _vdc[ii] = _v0[ii];
    }
    _last_time = (_time0 > 0.) ? _time0 : 0.;
  }else{untested();
  }
}
void SIM_DATA::map__nodes ()
Definition at line 85 of file u_sim_data.cc.
References _nm, _total_nodes, error(), oAUTO, oFORWARD, STATUS::order, OPT::order, order_auto(), order_forward(), order_reverse(), oREVERSE, TIMER::reset(), TIMER::start(), status, TIMER::stop(), and untested.
Referenced by init().
{
  _nm = new int[_total_nodes+1];
  ::status.order.reset().start();
  switch (OPT::order) {
    default: untested();
      error(bWARNING, "invalid order spec: %d\n", OPT::order);
    case oAUTO:                order_auto();    break;
    case oREVERSE: untested(); order_reverse(); break;
    case oFORWARD: untested(); order_forward(); break;
  }
  ::status.order.stop();
}
void SIM_DATA::mark_inc_mode_bad () [inline]
Definition at line 114 of file u_sim_data.h.
References tsBAD, tsNO, and tsYES.
Referenced by TRANSIENT::next(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::tr_unload(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_unload(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::tr_unload(), DEV_SPICE::tr_unload(), ELEMENT::tr_unload_active(), ELEMENT::tr_unload_couple(), ELEMENT::tr_unload_inode(), ELEMENT::tr_unload_passive(), ELEMENT::tr_unload_shunt(), and ELEMENT::tr_unload_source().
{
    switch (_inc_mode) {
    case tsYES: _inc_mode = tsBAD; break;
    case tsBAD: break;
    case tsNO:  break;
    }
  }
void SIM_DATA::new_event (double etime) [inline]
Definition at line 121 of file u_sim_data.h.
References BIGBIG.
Referenced by DEV_LOGIC::tr_accept().
{
    if (etime <= BIGBIG) {
      _eq.push(etime);
    }else{
    }
  }
int SIM_DATA::newnode_model () [inline]
Definition at line 107 of file u_sim_data.h.
Referenced by node_t::new_model_node().
{++_model_nodes;  return ++_total_nodes;}
int SIM_DATA::newnode_subckt () [inline]
Definition at line 106 of file u_sim_data.h.
Referenced by CARD_LIST::map_subckt_nodes().
{++_subckt_nodes; return ++_total_nodes;}
void SIM_DATA::order_auto ()
Definition at line 124 of file u_sim_data.cc.
References _nm, and _total_nodes.
Referenced by map__nodes().
{
  _nm[0] = 0;
  for (int node = 1;  node <= _total_nodes;  ++node) {
    _nm[node] = _total_nodes - node + 1;
  }
}
void SIM_DATA::order_forward ()
Definition at line 113 of file u_sim_data.cc.
References _nm, _total_nodes, and untested.
Referenced by map__nodes().
{untested();
  _nm[0] = 0;
  for (int node = 1;  node <= _total_nodes;  ++node) {untested();
    _nm[node] = node;
  }
}
void SIM_DATA::order_reverse ()
Definition at line 102 of file u_sim_data.cc.
References _nm, _total_nodes, and untested.
Referenced by map__nodes().
{untested();
  _nm[0] = 0;
  for (int node = 1;  node <= _total_nodes;  ++node) {untested();
    _nm[node] = _total_nodes - node + 1;
  }
}
void SIM_DATA::reset_iteration_counter (int i) [inline]
Definition at line 148 of file u_sim_data.h.
References iCOUNT, and up_order().
Referenced by SIM::command_base(), SIM::outdata(), and SIM::solve().
{assert(up_order(0,i,iCOUNT-1)); _iter[i] = 0;}
void SIM_DATA::restore_voltages ()
Definition at line 66 of file u_sim_data.cc.
References _total_nodes, _v0, _vdc, and _vt1.
Referenced by anonymous_namespace{s_dc.cc}::DCOP::sweep(), and TRANSIENT::sweep().
{
  for (int ii = 1;  ii <= _total_nodes;  ++ii) {
    _vt1[ii] = _v0[ii] = _vdc[ii];
  }
}
void SIM_DATA::set_command_ac () [inline]
Definition at line 128 of file u_sim_data.h.
References s_AC.
{_mode = s_AC;}
void SIM_DATA::set_command_dc () [inline]
Definition at line 129 of file u_sim_data.h.
References s_DC.
{_mode = s_DC;}
void SIM_DATA::set_command_fourier () [inline]
Definition at line 132 of file u_sim_data.h.
References s_FOURIER.
{_mode = s_FOURIER;}
void SIM_DATA::set_command_none () [inline]
Definition at line 127 of file u_sim_data.h.
References s_NONE.
Referenced by anonymous_namespace{c_prbcmd.cc}::do_probe().
{_mode = s_NONE;}
void SIM_DATA::set_command_op () [inline]
Definition at line 130 of file u_sim_data.h.
References s_OP.
{_mode = s_OP;}
void SIM_DATA::set_command_tran () [inline]
Definition at line 131 of file u_sim_data.h.
References s_TRAN.
Referenced by TRANSIENT::do_it().
{_mode = s_TRAN;}
void SIM_DATA::set_inc_mode_bad () [inline]
Definition at line 111 of file u_sim_data.h.
References tsBAD.
Referenced by anonymous_namespace{s_dc.cc}::DCOP::sweep(), and TRANSIENT::sweep().
{_inc_mode = tsBAD;}
void SIM_DATA::set_inc_mode_no () [inline]
Definition at line 113 of file u_sim_data.h.
References tsNO.
Referenced by SIM::set_flags(), and SIM::solve_with_homotopy().
{_inc_mode = tsNO;}
void SIM_DATA::set_inc_mode_yes () [inline]
Definition at line 112 of file u_sim_data.h.
References tsYES.
Referenced by SIM::set_flags().
{_inc_mode = tsYES;}
void SIM_DATA::set_limit ()
Definition at line 30 of file u_sim_data.cc.
References _total_nodes, and _v0.
Referenced by TRANSIENT::accept(), SIM::solve(), and anonymous_namespace{s_dc.cc}::DCOP::sweep_recursive().
{
  for (int ii = 1;  ii <= _total_nodes;  ++ii) {
    set_limit(_v0[ii]);
  }
}
void SIM_DATA::set_limit (double v)
Definition at line 37 of file u_sim_data.cc.
References _vmax, _vmin, and error().
{
  if (v+.4 > _vmax) {
    _vmax = v+.5;
    error(bTRACE, "new max = %g, new limit = %g\n", v, _vmax);
  }
  if (v-.4 < _vmin) {
    _vmin = v-.5;
    error(bTRACE, "new min = %g, new limit = %g\n", v, _vmin);
  }
}
SIM_MODE SIM_DATA::sim_mode () [inline]
Definition at line 133 of file u_sim_data.h.
Referenced by anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::tr_accept(), anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::tr_eval(), and anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::tr_review().
{return _mode;}
bool SIM_DATA::uic_now () [inline]
Definition at line 159 of file u_sim_data.h.
Referenced by DEV_SPICE::do_tr(), TRANSIENT::sweep(), and STORAGE::tr_needs_eval().
{return _uic && analysis_is_static() && _time0==0.;}
void SIM_DATA::unalloc_vectors ()
Definition at line 207 of file u_sim_data.cc.
References _ac, _evalq1, _evalq2, _i, _v0, and _vt1.
Referenced by SIM::command_base().
{
  _evalq1.clear();
  _evalq2.clear();
  delete [] _i;
  _i = NULL;
  delete [] _v0;
  _v0 = NULL;
  delete [] _vt1;
  _vt1 = NULL;
  delete [] _ac;
  _ac = NULL;
}
void SIM_DATA::uninit ()
Definition at line 225 of file u_sim_data.cc.
References _aa, _acx, _lu, _nm, _nstat, _vdc, BSMATRIX< T >::reinit(), and BSMATRIX< T >::size().
Referenced by COMPONENT::COMPONENT(), init(), MODEL_CARD::MODEL_CARD(), anonymous_namespace{c_modify.cc}::modify_fault(), COMPONENT::~COMPONENT(), MODEL_CARD::~MODEL_CARD(), and SIM::~SIM().
{
  if (_vdc) {
    _acx.reinit(0);
    _lu.reinit(0);
    _aa.reinit(0);
    delete [] _vdc;
    _vdc = NULL;
    delete [] _nstat;
    _nstat = NULL;
    delete [] _nm;
    _nm = NULL;
  }else{
    assert(_acx.size() == 0);
    assert(_lu.size() == 0);
    assert(_aa.size() == 0);
    assert(!_nstat);
    assert(!_nm);
  }
}
void SIM_DATA::zero_voltages ()
Definition at line 73 of file u_sim_data.cc.
References _i, _total_nodes, _v0, _vdc, and _vt1.
Referenced by TRANSIENT::sweep().
{
  for (int ii = 1;  ii <= _total_nodes;  ++ii) {
    _vt1[ii] = _v0[ii] = _vdc[ii] = _i[ii] = 0.;
  }
}
Member Data Documentation
BSMATRIX<double> SIM_DATA::_aa
Definition at line 71 of file u_sim_data.h.
Referenced by SIM::clear_arrays(), SIM::command_base(), init(), SIM::solve_equations(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_iwant_matrix(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_iwant_matrix(), ELEMENT::tr_iwant_matrix_active(), ELEMENT::tr_iwant_matrix_extended(), ELEMENT::tr_iwant_matrix_passive(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_load(), ELEMENT::tr_load_active(), ELEMENT::tr_load_couple(), ELEMENT::tr_load_diagonal_point(), ELEMENT::tr_load_extended(), ELEMENT::tr_load_inode(), ELEMENT::tr_load_passive(), ELEMENT::tr_load_point(), ELEMENT::tr_load_shunt(), NODE::tr_probe_num(), and uninit().
COMPLEX* SIM_DATA::_ac
Definition at line 68 of file u_sim_data.h.
Referenced by alloc_vectors(), NODE::iac(), unalloc_vectors(), NODE::vac(), and node_t::vac().
std::vector<CARD*> SIM_DATA::_acceptq
Definition at line 76 of file u_sim_data.h.
Referenced by TRANSIENT::accept(), and TRANSIENT::reject().
BSMATRIX<COMPLEX> SIM_DATA::_acx
Definition at line 73 of file u_sim_data.h.
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::ac_iwant_matrix(), ELEMENT::ac_iwant_matrix_active(), ELEMENT::ac_iwant_matrix_extended(), ELEMENT::ac_iwant_matrix_passive(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::ac_load(), ELEMENT::ac_load_active(), ELEMENT::ac_load_couple(), ELEMENT::ac_load_diagonal_point(), ELEMENT::ac_load_extended(), ELEMENT::ac_load_inode(), ELEMENT::ac_load_passive(), ELEMENT::ac_load_point(), ELEMENT::ac_load_shunt(), ELEMENT::ac_probe_ext(), NODE::ac_probe_ext(), init(), and uninit().
bool SIM_DATA::_bypass_ok
Definition at line 46 of file u_sim_data.h.
Referenced by PROBE::probe_node(), SIM::set_flags(), anonymous_namespace{s_dc.cc}::DCOP::sweep(), TRANSIENT::sweep(), and DEV_LOGIC::tr_accept().
double SIM_DATA::_damp
Definition at line 43 of file u_sim_data.h.
Referenced by ELEMENT::dampdiff(), PROBE::probe_node(), SIM::set_damp(), SIM::set_flags(), and SIM::solve().
double SIM_DATA::_dtmin
Definition at line 44 of file u_sim_data.h.
Referenced by TRANSIENT::next(), TRANSIENT::review(), TRANSIENT::setup(), TRANSIENT::sweep(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::tr_review(), anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE::tr_review(), anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP::tr_review(), anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM::tr_review(), anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::tr_review(), and ELEMENT::tr_review_check_and_convert().
std::priority_queue<double, std::vector<double> > SIM_DATA::_eq
Definition at line 74 of file u_sim_data.h.
Referenced by TRANSIENT::first(), and TRANSIENT::next().
std::deque<CARD*>* SIM_DATA::_evalq
Definition at line 80 of file u_sim_data.h.
Referenced by alloc_vectors(), and SIM::evaluate_models().
std::deque<CARD*> SIM_DATA::_evalq1
Definition at line 77 of file u_sim_data.h.
Referenced by alloc_vectors(), and unalloc_vectors().
std::deque<CARD*> SIM_DATA::_evalq2
Definition at line 78 of file u_sim_data.h.
Referenced by alloc_vectors(), and unalloc_vectors().
std::deque<CARD*>* SIM_DATA::_evalq_uc
Definition at line 81 of file u_sim_data.h.
Referenced by alloc_vectors(), SIM::evaluate_models(), and COMPONENT::q_eval().
bool SIM_DATA::_freezetime
Definition at line 49 of file u_sim_data.h.
Referenced by keep_voltages().
double SIM_DATA::_freq
Definition at line 41 of file u_sim_data.h.
Referenced by EVAL_BM_ACTION_BASE::ac_final_adjust(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::do_ac(), TRANSIENT::setup(), anonymous_namespace{s_dc.cc}::DC::setup(), anonymous_namespace{s_dc.cc}::OP::setup(), and anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::tr_eval().
bool SIM_DATA::_fulldamp
Definition at line 47 of file u_sim_data.h.
Referenced by SIM::set_damp(), SIM::set_flags(), and COMPONENT::volts_limited().
double SIM_DATA::_genout
Definition at line 45 of file u_sim_data.h.
Referenced by anonymous_namespace{s_dc.cc}::DCOP::DCOP(), PROBE::probe_node(), anonymous_namespace{s_dc.cc}::DC::setup(), anonymous_namespace{s_dc.cc}::OP::setup(), TRANSIENT::sweep(), and anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR::tr_eval().
double* SIM_DATA::_i
Definition at line 64 of file u_sim_data.h.
Referenced by alloc_vectors(), SIM::clear_arrays(), node_t::i(), SIM::solve_equations(), unalloc_vectors(), and zero_voltages().
TRI_STATE SIM_DATA::_inc_mode
Definition at line 60 of file u_sim_data.h.
int SIM_DATA::_iter[iCOUNT]
Definition at line 50 of file u_sim_data.h.
Referenced by PROBE::probe_node(), and SIM::solve_with_homotopy().
COMPLEX SIM_DATA::_jomega
Definition at line 55 of file u_sim_data.h.
Referenced by anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::ac_load(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_ac(), DEV_SPICE::do_ac(), and DEV_SPICE::update_ckt().
double SIM_DATA::_last_time
Definition at line 48 of file u_sim_data.h.
Referenced by init(), keep_voltages(), and TRANSIENT::setup().
std::deque<CARD*> SIM_DATA::_late_evalq
Definition at line 79 of file u_sim_data.h.
Referenced by SIM::evaluate_models(), and TRANSIENT::sweep().
bool SIM_DATA::_limiting
Definition at line 56 of file u_sim_data.h.
Referenced by SIM::set_flags(), SIM::solve(), and COMPONENT::volts_limited().
std::vector<CARD*> SIM_DATA::_loadq
Definition at line 75 of file u_sim_data.h.
Referenced by SIM::clear_arrays(), and SIM::load_matrix().
BSMATRIX<double> SIM_DATA::_lu
Definition at line 72 of file u_sim_data.h.
Referenced by SIM::command_base(), init(), SIM::solve_equations(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_iwant_matrix(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_iwant_matrix(), ELEMENT::tr_iwant_matrix_active(), ELEMENT::tr_iwant_matrix_extended(), ELEMENT::tr_iwant_matrix_passive(), ELEMENT::tr_probe_num(), NODE::tr_probe_num(), and uninit().
SIM_MODE SIM_DATA::_mode
Definition at line 61 of file u_sim_data.h.
Referenced by SIM::alarmlist(), SIM::command_base(), CKT_BASE::find_wave(), SIM::plotlist(), SIM::printlist(), SIM::solve(), and SIM::storelist().
int SIM_DATA::_model_nodes
Definition at line 53 of file u_sim_data.h.
int* SIM_DATA::_nm
Definition at line 63 of file u_sim_data.h.
Referenced by alloc_hold_vectors(), map__nodes(), NODE::matrix_number(), order_auto(), order_forward(), order_reverse(), node_t::to_internal(), and uninit().
LOGIC_NODE* SIM_DATA::_nstat
Definition at line 69 of file u_sim_data.h.
Referenced by alloc_hold_vectors(), SIM::command_base(), node_t::data(), SIM::solve_equations(), NODE::tr_probe_num(), and uninit().
SIM_PHASE SIM_DATA::_phase
Definition at line 62 of file u_sim_data.h.
Referenced by anonymous_namespace{s_dc.cc}::DCOP::first(), anonymous_namespace{s_dc.cc}::DCOP::next(), and TRANSIENT::sweep().
int SIM_DATA::_subckt_nodes
Definition at line 52 of file u_sim_data.h.
double SIM_DATA::_temp_c
Definition at line 42 of file u_sim_data.h.
Referenced by MODEL_SPICE::init_ckt(), TRANSIENT::options(), PROBE::probe_node(), anonymous_namespace{s_dc.cc}::DC::setup(), anonymous_namespace{s_dc.cc}::OP::setup(), anonymous_namespace{s_dc.cc}::DCOP::sweep_recursive(), and DEV_SPICE::update_ckt().
double SIM_DATA::_time0
Definition at line 40 of file u_sim_data.h.
Referenced by SIM::advance_time(), ELEMENT::dc_advance(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::dc_advance(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::do_tr_con_chk_and_q(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::do_tr_con_chk_and_q(), TRANSIENT::first(), LOGIC_NODE::force_initial_value(), gen(), MODEL_SPICE::init_ckt(), keep_voltages(), TRANSIENT::next(), PROBE::probe_node(), TRANSIENT::review(), LOGIC_NODE::set_event(), TRANSIENT::setup(), TRANSIENT::sweep(), LOGIC_NODE::to_analog(), LOGIC_NODE::to_logic(), DEV_LOGIC::tr_accept(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_accept(), ELEMENT::tr_advance(), DEV_LOGIC::tr_advance(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_advance(), anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP::tr_eval(), anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE::tr_eval(), anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM::tr_eval(), anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::tr_eval(), ELEMENT::tr_regress(), DEV_LOGIC::tr_regress(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_regress(), ELEMENT::tr_restore(), anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE::tr_review(), anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP::tr_review(), anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM::tr_review(), anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::tr_review(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_review(), and DEV_SPICE::update_ckt().
int SIM_DATA::_total_nodes
Definition at line 54 of file u_sim_data.h.
Referenced by SIM::advance_time(), alloc_hold_vectors(), alloc_vectors(), NODE::iac(), init(), keep_voltages(), map__nodes(), node_t::node_is_valid(), order_auto(), order_forward(), order_reverse(), restore_voltages(), set_limit(), NODE::v0(), NODE::vac(), NODE::vt1(), and zero_voltages().
bool SIM_DATA::_uic
Definition at line 59 of file u_sim_data.h.
Referenced by anonymous_namespace{s_dc.cc}::DCOP::DCOP(), anonymous_namespace{s_dc.cc}::DCOP::options(), and TRANSIENT::options().
int SIM_DATA::_user_nodes
Definition at line 51 of file u_sim_data.h.
double* SIM_DATA::_v0
Definition at line 65 of file u_sim_data.h.
Referenced by SIM::advance_time(), alloc_vectors(), keep_voltages(), restore_voltages(), set_limit(), SIM::solve_equations(), unalloc_vectors(), NODE::v0(), node_t::v0(), and zero_voltages().
double* SIM_DATA::_vdc
Definition at line 70 of file u_sim_data.h.
Referenced by alloc_hold_vectors(), keep_voltages(), restore_voltages(), uninit(), and zero_voltages().
double SIM_DATA::_vmax
Definition at line 57 of file u_sim_data.h.
Referenced by clear_limit(), set_limit(), and COMPONENT::volts_limited().
double SIM_DATA::_vmin
Definition at line 58 of file u_sim_data.h.
Referenced by clear_limit(), set_limit(), and COMPONENT::volts_limited().
double* SIM_DATA::_vt1
Definition at line 66 of file u_sim_data.h.
Referenced by SIM::advance_time(), alloc_vectors(), restore_voltages(), unalloc_vectors(), NODE::vt1(), and zero_voltages().
WAVE* SIM_DATA::_waves
Definition at line 82 of file u_sim_data.h.
Referenced by CKT_BASE::find_wave(), SIM::head(), and SIM::store_results().
The documentation for this struct was generated from the following files:
savant/gnucap/src/u_sim_data.h
savant/gnucap/src/u_sim_data.cc