gnucap: OS Namespace Reference
OS Namespace Reference
Functions
void system (const std::string &s)
void chdir (const std::string &s)
void remove (const std::string &s)
bool access_ok (const std::string &file, int mode)
std::string getcwd ()
std::string getenv (const std::string &s)
Function Documentation
bool OS::access_ok (const std::string & file, int mode) [inline]
Definition at line 57 of file l_lib.h.
Referenced by findfile().
{
    return (::access(file.c_str(), mode) == 0/*file_ok*/);
  }
void OS::chdir (const std::string & s) [inline]
Definition at line 49 of file l_lib.h.
References itested.
Referenced by anonymous_namespace{c_system.cc}::CMD_CHDIR::do_it().
                                        {itested();
    ::chdir(s.c_str());
  }
std::string OS::getcwd () [inline]
Definition at line 61 of file l_lib.h.
References BUFLEN, itested, and untested.
Referenced by anonymous_namespace{c_system.cc}::CMD_CHDIR::do_it().
                            {itested();
    char buf[BUFLEN+1];
    char* cwd = ::getcwd(buf,BUFLEN);
    if (cwd) {itested();
      return cwd;
    }else{untested();
      return "";
    }
  }
std::string OS::getenv (const std::string & s) [inline]
Definition at line 71 of file l_lib.h.
References itested.
Referenced by anonymous_namespace{c_system.cc}::CMD_EDIT::do_it().
{
    char* ev = ::getenv(s.c_str());
    if (ev) {
      return ev;
    }else{itested();
      return "";
    }
  }
void OS::remove (const std::string & s) [inline]
Definition at line 53 of file l_lib.h.
References itested.
Referenced by anonymous_namespace{c_system.cc}::CMD_EDIT::do_it().
                                         {itested();
    ::remove(s.c_str());
  }
void OS::system (const std::string & s) [inline]
Definition at line 45 of file l_lib.h.
References itested.
Referenced by anonymous_namespace{c_system.cc}::CMD_EDIT::do_it(), and anonymous_namespace{c_system.cc}::CMD_SYSTEM::do_it().
                                         {itested();
    ::system(s.c_str());
  }