gnucap: MODEL_CARD Class Reference
MODEL_CARD Class Reference
#include <e_model.h>
Public Member Functions
MODEL_CARD (const COMPONENT *p)
~MODEL_CARD ()
char id_letter () const
CARD * clone_instance () const
void precalc_first ()
void set_param_by_index (int, std::string &, int)
bool param_is_printable (int) const
std::string value_name () const
std::string param_name (int) const
std::string param_name (int, int) const
std::string param_value (int) const
int param_count () const
virtual void tr_eval (COMPONENT *) const
virtual void ac_eval (COMPONENT *) const
virtual COMMON_COMPONENT * new_common () const
virtual SDP_CARD * new_sdp (COMMON_COMPONENT *) const
virtual bool parse_params_obsolete_callback (CS &)
virtual bool is_valid (const COMPONENT *) const
const CARD * component_proto () const
Public Attributes
PARAMETER< double > _tnom_c
Protected Member Functions
MODEL_CARD (const MODEL_CARD &p)
Protected Attributes
const CARD * _component_proto
Detailed Description
Definition at line 43 of file e_model.h.
Constructor & Destructor Documentation
MODEL_CARD::MODEL_CARD (const MODEL_CARD & p) [explicit, protected]
Definition at line 36 of file e_model.cc.
References CKT_BASE::_sim, and SIM_DATA::uninit().
  :CARD(p),
   _component_proto(p._component_proto),
   _tnom_c(p._tnom_c)
{
  _sim->uninit();
}
MODEL_CARD::MODEL_CARD (const COMPONENT * p) [explicit]
Definition at line 28 of file e_model.cc.
References CKT_BASE::_sim, and SIM_DATA::uninit().
  :CARD(),
   _component_proto(p),
   _tnom_c(NOT_INPUT)
{
  _sim->uninit();
}
MODEL_CARD::~MODEL_CARD ()
Definition at line 44 of file e_model.cc.
References CKT_BASE::_sim, and SIM_DATA::uninit().
{
  _sim->uninit(); // disconnect models from devices
}
Member Function Documentation
virtual void MODEL_CARD::ac_eval (COMPONENT *) const [inline, virtual]
Definition at line 64 of file e_model.h.
References unreachable.
Referenced by COMMON_COMPONENT::ac_eval().
{unreachable();}
CARD* MODEL_CARD::clone_instance () const [inline, virtual]
Reimplemented from CARD.
Definition at line 52 of file e_model.h.
References itested.
                {itested(); assert(_component_proto); return _component_proto->clone();}
const CARD* MODEL_CARD::component_proto () const [inline]
Definition at line 69 of file e_model.h.
References itested.
{itested(); return _component_proto;}
char MODEL_CARD::id_letter () const [inline, virtual]
Reimplemented from CARD.
Definition at line 51 of file e_model.h.
References untested.
{untested();return '\0';}
virtual bool MODEL_CARD::is_valid (const COMPONENT *) const [inline, virtual]
Reimplemented in MODEL_BUILT_IN_MOS8, MODEL_BUILT_IN_MOS7, MODEL_SPICE, MODEL_BUILT_IN_MOS5, MODEL_BUILT_IN_MOS4, MODEL_BUILT_IN_BJT, MODEL_BUILT_IN_MOS_BASE, MODEL_BUILT_IN_MOS2, MODEL_BUILT_IN_DIODE, MODEL_BUILT_IN_MOS3, MODEL_BUILT_IN_MOS1, MODEL_BUILT_IN_MOS6, and MODEL_BUILT_IN_MOS123.
Definition at line 68 of file e_model.h.
Referenced by COMPONENT::find_model().
{return true;}
virtual COMMON_COMPONENT* MODEL_CARD::new_common () const [inline, virtual]
Reimplemented in MODEL_SEMI_RESISTOR, MODEL_SEMI_CAPACITOR, and MODEL_TABLE.
Definition at line 65 of file e_model.h.
Referenced by anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::expand().
{return 0;}
virtual SDP_CARD* MODEL_CARD::new_sdp (COMMON_COMPONENT *) const [inline, virtual]
Reimplemented in MODEL_BUILT_IN_MOS8, MODEL_BUILT_IN_MOS7, MODEL_BUILT_IN_MOS5, MODEL_BUILT_IN_MOS4, MODEL_BUILT_IN_BJT, MODEL_BUILT_IN_MOS_BASE, MODEL_BUILT_IN_MOS2, MODEL_BUILT_IN_DIODE, MODEL_BUILT_IN_MOS3, MODEL_BUILT_IN_MOS1, MODEL_BUILT_IN_MOS6, and MODEL_BUILT_IN_MOS123.
Definition at line 66 of file e_model.h.
References unreachable.
{unreachable();return 0;};
int MODEL_CARD::param_count () const [inline, virtual]
Reimplemented from CARD.
Reimplemented in MODEL_BUILT_IN_MOS8, MODEL_BUILT_IN_MOS7, anonymous_namespace{d_switch.cc}::MODEL_SWITCH, MODEL_SPICE, MODEL_SEMI_RESISTOR, MODEL_SEMI_CAPACITOR, MODEL_BUILT_IN_MOS5, MODEL_LOGIC, MODEL_SEMI_BASE, MODEL_BUILT_IN_MOS4, MODEL_BUILT_IN_BJT, MODEL_BUILT_IN_MOS_BASE, MODEL_BUILT_IN_MOS2, MODEL_BUILT_IN_DIODE, MODEL_BUILT_IN_MOS3, MODEL_BUILT_IN_MOS1, MODEL_BUILT_IN_MOS6, and MODEL_BUILT_IN_MOS123.
Definition at line 61 of file e_model.h.
References CARD::param_count().
Referenced by MODEL_SEMI_BASE::param_count(), MODEL_LOGIC::param_count(), anonymous_namespace{d_switch.cc}::MODEL_SWITCH::param_count(), MODEL_SPICE::param_count(), param_is_printable(), MODEL_SPICE::param_is_printable(), param_name(), MODEL_SEMI_BASE::param_name(), MODEL_LOGIC::param_name(), MODEL_SPICE::param_name(), anonymous_namespace{d_switch.cc}::MODEL_SWITCH::param_name(), param_value(), MODEL_SPICE::param_value(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_args(), anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::print_args(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_args(), and set_param_by_index().
{return (1 + CARD::param_count());}
bool MODEL_CARD::param_is_printable (int i) const [virtual]
Reimplemented from CARD.
Reimplemented in MODEL_BUILT_IN_MOS8, MODEL_BUILT_IN_MOS7, anonymous_namespace{d_switch.cc}::MODEL_SWITCH, MODEL_SPICE, MODEL_SEMI_RESISTOR, MODEL_SEMI_CAPACITOR, MODEL_BUILT_IN_MOS5, MODEL_LOGIC, MODEL_SEMI_BASE, MODEL_BUILT_IN_MOS4, MODEL_BUILT_IN_BJT, MODEL_BUILT_IN_MOS_BASE, MODEL_BUILT_IN_MOS2, MODEL_BUILT_IN_DIODE, MODEL_BUILT_IN_MOS3, MODEL_BUILT_IN_MOS1, MODEL_BUILT_IN_MOS6, and MODEL_BUILT_IN_MOS123.
Definition at line 57 of file e_model.cc.
References param_count().
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_args(), anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::print_args(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_args().
{
  switch (MODEL_CARD::param_count() - 1 - i) {
  case 0: return true;
  default: return CARD::param_is_printable(i);
  }
}
std::string MODEL_CARD::param_name (int i) const [virtual]
Reimplemented from CARD.
Reimplemented in MODEL_BUILT_IN_MOS8, MODEL_BUILT_IN_MOS7, anonymous_namespace{d_switch.cc}::MODEL_SWITCH, MODEL_SPICE, MODEL_SEMI_RESISTOR, MODEL_SEMI_CAPACITOR, MODEL_BUILT_IN_MOS5, MODEL_LOGIC, MODEL_SEMI_BASE, MODEL_BUILT_IN_MOS4, MODEL_BUILT_IN_BJT, MODEL_BUILT_IN_MOS_BASE, MODEL_BUILT_IN_MOS2, MODEL_BUILT_IN_DIODE, MODEL_BUILT_IN_MOS3, MODEL_BUILT_IN_MOS1, MODEL_BUILT_IN_MOS6, and MODEL_BUILT_IN_MOS123.
Definition at line 65 of file e_model.cc.
References param_count().
Referenced by param_name(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_args(), anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::print_args(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_args().
{
  switch (MODEL_CARD::param_count() - 1 - i) {
  case 0: return "tnom\0";
  default: return CARD::param_name(i);
  }
}
std::string MODEL_CARD::param_name (int i, int j) const [virtual]
Reimplemented from CARD.
Reimplemented in MODEL_BUILT_IN_MOS8, MODEL_BUILT_IN_MOS7, anonymous_namespace{d_switch.cc}::MODEL_SWITCH, MODEL_SPICE, MODEL_SEMI_RESISTOR, MODEL_SEMI_CAPACITOR, MODEL_BUILT_IN_MOS5, MODEL_LOGIC, MODEL_SEMI_BASE, MODEL_BUILT_IN_MOS4, MODEL_BUILT_IN_BJT, MODEL_BUILT_IN_MOS_BASE, MODEL_BUILT_IN_MOS2, MODEL_BUILT_IN_DIODE, MODEL_BUILT_IN_MOS3, MODEL_BUILT_IN_MOS1, MODEL_BUILT_IN_MOS6, and MODEL_BUILT_IN_MOS123.
Definition at line 73 of file e_model.cc.
References CARD::param_count(), and param_name().
{
  if (j == 0) {
    return param_name(i);
  }else if (i >= CARD::param_count()) {
    return "";
  }else{
    return MODEL_CARD::param_name(i, j);
  }
}
std::string MODEL_CARD::param_value (int i) const [virtual]
Reimplemented from CARD.
Reimplemented in MODEL_BUILT_IN_MOS8, MODEL_BUILT_IN_MOS7, anonymous_namespace{d_switch.cc}::MODEL_SWITCH, MODEL_SPICE, MODEL_SEMI_RESISTOR, MODEL_SEMI_CAPACITOR, MODEL_BUILT_IN_MOS5, MODEL_LOGIC, MODEL_SEMI_BASE, MODEL_BUILT_IN_MOS4, MODEL_BUILT_IN_BJT, MODEL_BUILT_IN_MOS_BASE, MODEL_BUILT_IN_MOS2, MODEL_BUILT_IN_DIODE, MODEL_BUILT_IN_MOS3, MODEL_BUILT_IN_MOS1, MODEL_BUILT_IN_MOS6, and MODEL_BUILT_IN_MOS123.
Definition at line 84 of file e_model.cc.
References _tnom_c, param_count(), and PARAMETER< T >::string().
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_args(), anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::print_args(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_args().
{
  switch (MODEL_CARD::param_count() - 1 - i) {
  case 0: return _tnom_c.string();
  default: return CARD::param_value(i);
  }
}
virtual bool MODEL_CARD::parse_params_obsolete_callback (CS &) [inline, virtual]
Reimplemented in MODEL_TABLE.
Definition at line 67 of file e_model.h.
References unreachable.
{unreachable(); return false;}
void MODEL_CARD::precalc_first () [virtual]
Reimplemented from CARD.
Reimplemented in MODEL_BUILT_IN_MOS8, MODEL_BUILT_IN_MOS7, anonymous_namespace{d_switch.cc}::MODEL_SWITCH, MODEL_SEMI_RESISTOR, MODEL_SEMI_CAPACITOR, MODEL_BUILT_IN_MOS5, MODEL_LOGIC, MODEL_SEMI_BASE, MODEL_BUILT_IN_MOS4, MODEL_BUILT_IN_BJT, MODEL_BUILT_IN_MOS_BASE, MODEL_BUILT_IN_MOS2, MODEL_TABLE, MODEL_BUILT_IN_DIODE, MODEL_BUILT_IN_MOS3, MODEL_BUILT_IN_MOS1, MODEL_BUILT_IN_MOS6, and MODEL_BUILT_IN_MOS123.
Definition at line 92 of file e_model.cc.
References _tnom_c, PARAMETER< T >::e_val(), CARD::scope(), and OPT::tnom_c.
{
  CARD::precalc_first();
  _tnom_c.e_val(OPT::tnom_c, scope());
}
void MODEL_CARD::set_param_by_index (int i, std::string & value, int offset) [virtual]
Reimplemented from CARD.
Reimplemented in MODEL_BUILT_IN_MOS8, MODEL_BUILT_IN_MOS7, MODEL_SPICE, anonymous_namespace{d_switch.cc}::MODEL_SWITCH, MODEL_SEMI_RESISTOR, MODEL_SEMI_CAPACITOR, MODEL_BUILT_IN_MOS5, MODEL_LOGIC, MODEL_SEMI_BASE, MODEL_BUILT_IN_MOS4, MODEL_BUILT_IN_BJT, MODEL_BUILT_IN_MOS_BASE, MODEL_BUILT_IN_MOS2, MODEL_BUILT_IN_DIODE, MODEL_BUILT_IN_MOS3, MODEL_BUILT_IN_MOS1, MODEL_BUILT_IN_MOS6, and MODEL_BUILT_IN_MOS123.
Definition at line 49 of file e_model.cc.
References _tnom_c, and param_count().
{
  switch (MODEL_CARD::param_count() - 1 - i) {
  case 0: _tnom_c = value; break;
  default: CARD::set_param_by_index(i, value, offset); break;
  }
}
virtual void MODEL_CARD::tr_eval (COMPONENT *) const [inline, virtual]
Reimplemented in MODEL_BUILT_IN_MOS8, MODEL_BUILT_IN_MOS7, MODEL_BUILT_IN_MOS5, MODEL_BUILT_IN_MOS4, MODEL_BUILT_IN_BJT, MODEL_BUILT_IN_MOS_BASE, MODEL_BUILT_IN_MOS2, MODEL_TABLE, MODEL_BUILT_IN_DIODE, MODEL_BUILT_IN_MOS3, MODEL_BUILT_IN_MOS1, MODEL_BUILT_IN_MOS6, and MODEL_BUILT_IN_MOS123.
Definition at line 63 of file e_model.h.
References unreachable.
Referenced by EVAL_BM_TABLE::tr_eval(), and COMMON_COMPONENT::tr_eval().
{unreachable();}
std::string MODEL_CARD::value_name () const [inline, virtual]
Implements CARD.
Definition at line 57 of file e_model.h.
{return "";}
Member Data Documentation
const CARD* MODEL_CARD::_component_proto [protected]
Definition at line 71 of file e_model.h.
PARAMETER<double> MODEL_CARD::_tnom_c
Definition at line 73 of file e_model.h.
Referenced by MODEL_BUILT_IN_DIODE::MODEL_BUILT_IN_DIODE(), MODEL_BUILT_IN_MOS_BASE::MODEL_BUILT_IN_MOS_BASE(), param_value(), MODEL_BUILT_IN_DIODE::param_value(), MODEL_BUILT_IN_MOS_BASE::param_value(), precalc_first(), MODEL_BUILT_IN_MOS_BASE::precalc_first(), MODEL_BUILT_IN_BJT::precalc_first(), EVAL_BM_SEMI_CAPACITOR::precalc_last(), EVAL_BM_SEMI_RESISTOR::precalc_last(), set_param_by_index(), MODEL_BUILT_IN_DIODE::set_param_by_index(), MODEL_BUILT_IN_MOS_BASE::set_param_by_index(), and EVAL_BUILT_IN_DIODE_Yj::tr_eval().
The documentation for this class was generated from the following files:
savant/gnucap/src/e_model.h
savant/gnucap/src/e_model.cc