gnucap: savant/gnucap/src/e_cardlist.h File Reference
savant/gnucap/src/e_cardlist.h File Reference
#include "md.h"
Classes
class CARD_LIST
class CARD_LIST::fat_iterator
Functions
INTERFACE CARD_LIST::fat_iterator findbranch (CS &, CARD_LIST::fat_iterator)
CARD_LIST::fat_iterator findbranch (CS &cmd, CARD_LIST *cl)
Function Documentation
INTERFACE CARD_LIST::fat_iterator findbranch (CS & , CARD_LIST::fat_iterator)
Definition at line 39 of file findbr.cc.
References CS::_STRING, BUFLEN, CS::ctostr(), CS::cursor(), CARD_LIST::fat_iterator::end(), findbranch(), CARD_LIST::fat_iterator::is_end(), itested, CS::reset(), TOKENTERM, untested, and wmatch().
Referenced by findbranch(), anonymous_namespace{c_list.cc}::list_save(), anonymous_namespace{c_modify.cc}::modify_fault(), and anonymous_namespace{s_dc.cc}::DC::setup().
{
  unsigned save = cmd.cursor();
  char labelwanted[BUFLEN+1];
  cmd.ctostr(labelwanted, BUFLEN, TOKENTERM);
  if (!labelwanted[0]) {                // nothing to look for
    cmd.reset(save);
    return here.end();
  }else{
  }
  char* local_part;         // part before last dot, the thing inside
  char* last_part;          // part after last dot, top level
  {
    char* dot = strrchr(labelwanted,'.');
    if (dot) {itested();                    // split the string into 2 parts at the last dot
      *dot = '\0';          // before is the new "local_part", shortened
      last_part = dot + 1;  // after is the "last_part".
      local_part = labelwanted;
    }else{
      last_part = labelwanted;
      local_part = NULL;
    }
  }
  for (;;) {
    if (here.is_end()) {
      // at the end of the list - done, fails.
      cmd.reset(save);
      return here;
    }else if (wmatch((**here).short_label(), last_part)) {
      // last_part matches
      if (!local_part) {
        // requested a simple name, found it .. done.
        return here;
      }else{untested();
        // there are dots, so look inside subckt
        untested();
        if ((**here).subckt()) {untested();
          untested();
          // has a subckt, and its name matches, doing fine
          CS want(CS::_STRING, local_part); // recursion
          CARD_LIST::fat_iterator subbrh=findbranch(want,(**here).subckt());
          if (!subbrh.is_end()) {untested();
            // found it in a subckt
            return subbrh;
          }else{untested();
            // didn't find anything in this subckt
            // keep looking for another with the same name
            // why?
            ++here;
          }
        }else{untested();
          // no subckt
          // keep looking for something with this name that has a subckt
          // why?
          untested();
          ++here;
        }
      }
    }else{
      // label doesn't match
      // keep looking for one that does.  (linear search)
      ++here;
    }
  }
}
CARD_LIST::fat_iterator findbranch (CS & cmd, CARD_LIST * cl) [inline]
Definition at line 153 of file e_cardlist.h.
References CARD_LIST::begin(), and findbranch().
{
  assert(cl);
  return findbranch(cmd, CARD_LIST::fat_iterator(cl, cl->begin()));
}