gnucap: EVAL_BM_ACTION_BASE Class Reference
EVAL_BM_ACTION_BASE Class Reference
#include <bm.h>
Public Member Functions
bool operator== (const COMMON_COMPONENT &) const
void print_common_obsolete_callback (OMSTREAM &, LANGUAGE *) const
void precalc_first (const CARD_LIST *)
void ac_eval (ELEMENT *) const
virtual bool ac_too () const =0
bool has_ext_args () const
Static Public Member Functions
static COMMON_COMPONENT * parse_func_type (CS &)
Protected Member Functions
EVAL_BM_ACTION_BASE (int c=0)
EVAL_BM_ACTION_BASE (const EVAL_BM_ACTION_BASE &p)
~EVAL_BM_ACTION_BASE ()
double temp_adjust () const
void tr_final_adjust (FPOLY1 *y, bool f_is_value) const
void tr_finish_tdv (ELEMENT *d, double val) const
void ac_final_adjust (COMPLEX *y) const
void ac_final_adjust_with_temp (COMPLEX *y) const
double uic (double x) const
double ioffset (double x) const
bool parse_params_obsolete_callback (CS &)
Protected Attributes
PARAMETER< double > _bandwidth
PARAMETER< double > _delay
PARAMETER< double > _phase
PARAMETER< double > _ooffset
PARAMETER< double > _ioffset
PARAMETER< double > _scale
PARAMETER< double > _tc1
PARAMETER< double > _tc2
PARAMETER< double > _ic
Detailed Description
Definition at line 48 of file bm.h.
Constructor & Destructor Documentation
EVAL_BM_ACTION_BASE::EVAL_BM_ACTION_BASE (int c = 0) [explicit, protected]
Definition at line 40 of file bm.cc.
  :EVAL_BM_BASE(c),
   _bandwidth(_default_bandwidth),
   _delay(_default_delay),
   _phase(_default_phase),
   _ooffset(_default_ooffset),
   _ioffset(_default_ioffset),
   _scale(_default_scale),
   _tc1(_default_tc1),
   _tc2(_default_tc2),
   _ic(_default_ic)
{
}
EVAL_BM_ACTION_BASE::EVAL_BM_ACTION_BASE (const EVAL_BM_ACTION_BASE & p) [explicit, protected]
Definition at line 54 of file bm.cc.
  :EVAL_BM_BASE(p),
   _bandwidth(p._bandwidth),
   _delay(p._delay),
   _phase(p._phase),
   _ooffset(p._ooffset),
   _ioffset(p._ioffset),
   _scale(p._scale),
   _tc1(p._tc1),
   _tc2(p._tc2),
   _ic(p._ic)
{
}
EVAL_BM_ACTION_BASE::~EVAL_BM_ACTION_BASE () [inline, protected]
Definition at line 62 of file bm.h.
{}
Member Function Documentation
void EVAL_BM_ACTION_BASE::ac_eval (ELEMENT * d) const [virtual]
Reimplemented from COMMON_COMPONENT.
Reimplemented in anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL, anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX, and anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR.
Definition at line 173 of file bm.cc.
References ELEMENT::_ev, ELEMENT::_y, ac_final_adjust(), FPOLY1::f1, and COMMON_COMPONENT::tr_eval().
{
  tr_eval(d);
  d->_ev = d->_y[0].f1;
  ac_final_adjust(&(d->_ev));
}
void EVAL_BM_ACTION_BASE::ac_final_adjust (COMPLEX * y) const [protected]
Definition at line 91 of file bm.cc.
References _bandwidth, _delay, SIM_DATA::_freq, _phase, CKT_BASE::_sim, DTOR, error(), itested, NOT_INPUT, and untested.
Referenced by ac_eval(), and ac_final_adjust_with_temp().
{
  if (_bandwidth != NOT_INPUT && _bandwidth != 0.) {untested();
    assert(y->imag() == 0);
    double ratio = CKT_BASE::_sim->_freq / _bandwidth;
    double coeff = y->real() / (1.+(ratio*ratio));
    *y = COMPLEX(coeff, -coeff * ratio);
  }else{
  }
  if (_phase != 0.) {itested();
    *y *= std::polar(1., _phase*DTOR);
  }else{
  }
  if (_delay != 0.) {untested();
    double ratio = CKT_BASE::_sim->_freq * _delay;
    if (ratio > 100000.) {untested();
      error(bPICKY, "delay too long\n");
      ratio = 0.;
    }else{untested();
    }
    *y *= std::polar(1., -360.0 * DTOR * ratio);
  }else{
  }
}
void EVAL_BM_ACTION_BASE::ac_final_adjust_with_temp (COMPLEX * y) const [protected]
Definition at line 118 of file bm.cc.
References ac_final_adjust(), and temp_adjust().
Referenced by anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR::ac_eval(), and anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX::ac_eval().
{
  *y *= temp_adjust();
  ac_final_adjust(y);
}
virtual bool EVAL_BM_ACTION_BASE::ac_too () const [pure virtual]
Implemented in EVAL_BM_VALUE, anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN, anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM, anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP, anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE, anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT, anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY, anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL, anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY, EVAL_BM_SEMI_BASE, anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH, anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL, EVAL_BM_TABLE, anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX, and anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR.
Referenced by anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::parse_common_obsolete_callback().
bool EVAL_BM_ACTION_BASE::has_ext_args () const
Definition at line 196 of file bm.cc.
References _bandwidth, _delay, _ic, _ioffset, _ooffset, _phase, _scale, _tc1, _tc2, and PARAMETER< T >::has_hard_value().
{
  return  (_bandwidth.has_hard_value()
           || _delay.has_hard_value()
           || _phase.has_hard_value()
           || _ooffset.has_hard_value()
           || _ioffset.has_hard_value()
           || _scale.has_hard_value()
           || _tc1.has_hard_value()
           || _tc2.has_hard_value()
           || _ic.has_hard_value());
}
double EVAL_BM_ACTION_BASE::ioffset (double x) const [inline, protected]
Definition at line 69 of file bm.h.
Referenced by anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::tr_eval(), anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::tr_eval(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::tr_eval(), anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY::tr_eval(), anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::tr_eval(), tr_finish_tdv(), and anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::tr_review().
{return uic(x) + _ioffset;}
bool EVAL_BM_ACTION_BASE::operator== (const COMMON_COMPONENT & x) const [virtual]
Reimplemented from EVAL_BM_BASE.
Reimplemented in EVAL_BM_VALUE, EVAL_BM_SEMI_RESISTOR, EVAL_BM_SEMI_CAPACITOR, anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN, anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM, anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP, anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE, anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT, anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY, anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY, anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL, EVAL_BM_SEMI_BASE, anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH, EVAL_BM_TABLE, anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL, anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX, and anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR.
Definition at line 124 of file bm.cc.
References _bandwidth, _delay, _ic, _ioffset, _ooffset, _phase, _scale, _tc1, _tc2, anonymous_namespace{c_genrat.cc}::p, and untested.
{
  const EVAL_BM_ACTION_BASE* p = dynamic_cast<const EVAL_BM_ACTION_BASE*>(&x);
  bool rv = p
    && _bandwidth == p->_bandwidth
    && _delay == p->_delay
    && _phase == p->_phase
    && _ooffset == p->_ooffset
    && _ioffset == p->_ioffset
    && _scale == p->_scale
    && _tc1 == p->_tc1
    && _tc2 == p->_tc2
    && _ic == p->_ic
    && EVAL_BM_BASE::operator==(x);
  if (rv) {untested();
  }else{
  }
  return rv;
}
COMMON_COMPONENT * EVAL_BM_ACTION_BASE::parse_func_type (CS & cmd) [static]
Definition at line 209 of file bm.cc.
References anonymous_namespace{bm_complex.cc}::bm_dispatcher, COMMON_COMPONENT::clone(), CS::is_float(), CS::match1(), anonymous_namespace{c_genrat.cc}::p, CS::skip1b(), and COMMON_COMPONENT::skip_type_tail().
Referenced by anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::parse_common_obsolete_callback(), and anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_element_using_obsolete_callback().
{
  const COMMON_COMPONENT* p =
    (cmd.is_float() || cmd.match1('_') || cmd.skip1b('='))
    ? bm_dispatcher["eval_bm_value"]
    : bm_dispatcher[cmd];
  if (p) {
    p->skip_type_tail(cmd);
    return p->clone();
  }else{
    return NULL;
  }
}
bool EVAL_BM_ACTION_BASE::parse_params_obsolete_callback (CS & cmd) [protected, virtual]
Reimplemented from COMMON_COMPONENT.
Reimplemented in EVAL_BM_VALUE, anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN, anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM, anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP, anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE, anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT, anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY, anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL, anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY, EVAL_BM_SEMI_BASE, and anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH.
Definition at line 180 of file bm.cc.
References _bandwidth, _delay, _ic, _ioffset, _ooffset, _phase, _scale, _tc1, _tc2, Get(), and ONE_OF.
{
  return ONE_OF
    || Get(cmd, "bandwidth",&_bandwidth)
    || Get(cmd, "delay",    &_delay)
    || Get(cmd, "phase",    &_phase)
    || Get(cmd, "ioffset",  &_ioffset)
    || Get(cmd, "ooffset",  &_ooffset)
    || Get(cmd, "scale",    &_scale)
    || Get(cmd, "tc1",      &_tc1)
    || Get(cmd, "tc2",      &_tc2)
    || Get(cmd, "ic",       &_ic)
    || COMMON_COMPONENT::parse_params_obsolete_callback(cmd);
    ;
}
void EVAL_BM_ACTION_BASE::precalc_first (const CARD_LIST * Scope) [virtual]
Reimplemented from COMMON_COMPONENT.
Reimplemented in EVAL_BM_VALUE, anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN, anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM, anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP, anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE, anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT, anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY, anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY, anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL, EVAL_BM_SEMI_BASE, and anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH.
Definition at line 158 of file bm.cc.
References _bandwidth, _default_bandwidth(), _default_delay(), _default_ic(), _default_ioffset(), _default_ooffset(), _default_phase(), _default_scale(), _default_tc1(), _default_tc2(), _delay, _ic, _ioffset, _ooffset, _phase, _scale, _tc1, _tc2, and PARAMETER< T >::e_val().
{
  assert(Scope);
  COMMON_COMPONENT::precalc_first(Scope);
  _bandwidth.e_val(_default_bandwidth, Scope);
  _delay.e_val(_default_delay, Scope);
  _phase.e_val(_default_phase, Scope);
  _ooffset.e_val(_default_ooffset, Scope);
  _ioffset.e_val(_default_ioffset, Scope);
  _scale.e_val(_default_scale, Scope);
  _tc1.e_val(_default_tc1, Scope);
  _tc2.e_val(_default_tc2, Scope);
  _ic.e_val(_default_ic, Scope);
}
void EVAL_BM_ACTION_BASE::print_common_obsolete_callback (OMSTREAM & o, LANGUAGE * lang) const [virtual]
Reimplemented from COMMON_COMPONENT.
Reimplemented in EVAL_BM_VALUE, anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN, anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM, anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP, anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE, anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT, anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY, anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY, anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL, EVAL_BM_SEMI_BASE, anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH, anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL, EVAL_BM_TABLE, anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX, and anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR.
Definition at line 144 of file bm.cc.
References _bandwidth, _delay, _ic, _ioffset, _ooffset, _phase, _scale, _tc1, _tc2, PARAMETER< T >::has_hard_value(), and print_pair().
{
  print_pair(o, lang, "bandwidth",_bandwidth,_bandwidth.has_hard_value());
  print_pair(o, lang, "delay",    _delay,    _delay.has_hard_value());
  print_pair(o, lang, "phase",    _phase,    _phase.has_hard_value());
  print_pair(o, lang, "ioffset",  _ioffset,  _ioffset.has_hard_value());
  print_pair(o, lang, "ooffset",  _ooffset,  _ooffset.has_hard_value());
  print_pair(o, lang, "scale",    _scale,    _scale.has_hard_value());
  print_pair(o, lang, "tc1",      _tc1,      _tc1.has_hard_value());
  print_pair(o, lang, "tc2",      _tc2,      _tc2.has_hard_value());
  print_pair(o, lang, "ic",       _ic,       _ic.has_hard_value());
  COMMON_COMPONENT::print_common_obsolete_callback(o, lang);
}
double EVAL_BM_ACTION_BASE::temp_adjust () const [protected]
Definition at line 68 of file bm.cc.
References _scale, _tc1, _tc2, COMMON_COMPONENT::_temp_c, and COMMON_COMPONENT::_tnom_c.
Referenced by ac_final_adjust_with_temp(), and tr_final_adjust().
{
  double tempdiff = _temp_c - _tnom_c;
  return (_scale * (1 + _tc1*tempdiff + _tc2*tempdiff*tempdiff));
}
void EVAL_BM_ACTION_BASE::tr_final_adjust (FPOLY1 * y, bool f_is_value) const [protected]
Definition at line 74 of file bm.cc.
References _ooffset, FPOLY1::f0, FPOLY1::f1, and temp_adjust().
Referenced by EVAL_BM_TABLE::tr_eval(), anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::tr_eval(), anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::tr_eval(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::tr_eval(), anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY::tr_eval(), anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT::tr_eval(), and tr_finish_tdv().
{
  if (f_is_value) {
    y->f1 = y->f0;
    y->f0 = 0.;
  }else{
  }
  *y *= temp_adjust();
  y->f0 += _ooffset;
}
void EVAL_BM_ACTION_BASE::tr_finish_tdv (ELEMENT * d, double val) const [protected]
Definition at line 85 of file bm.cc.
References ELEMENT::_y, ioffset(), tr_final_adjust(), and FPOLY1::x.
Referenced by anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR::tr_eval(), anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX::tr_eval(), EVAL_BM_SEMI_BASE::tr_eval(), anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP::tr_eval(), anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE::tr_eval(), anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM::tr_eval(), anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::tr_eval(), and EVAL_BM_VALUE::tr_eval().
{
  d->_y[0] = FPOLY1(CPOLY1(ioffset(d->_y[0].x), 0., val));
  tr_final_adjust(&(d->_y[0]), false);
}
double EVAL_BM_ACTION_BASE::uic (double x) const [inline, protected]
Definition at line 68 of file bm.h.
References CKT_BASE::_sim.
{return (CKT_BASE::_sim->uic_now()) ? _ic : x;}
Member Data Documentation
PARAMETER<double> EVAL_BM_ACTION_BASE::_bandwidth [protected]
Definition at line 50 of file bm.h.
Referenced by ac_final_adjust(), has_ext_args(), EVAL_BM_VALUE::is_trivial(), operator==(), parse_params_obsolete_callback(), precalc_first(), and print_common_obsolete_callback().
PARAMETER<double> EVAL_BM_ACTION_BASE::_delay [protected]
Reimplemented in anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN, and anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE.
Definition at line 51 of file bm.h.
Referenced by ac_final_adjust(), has_ext_args(), EVAL_BM_VALUE::is_trivial(), operator==(), parse_params_obsolete_callback(), precalc_first(), and print_common_obsolete_callback().
PARAMETER<double> EVAL_BM_ACTION_BASE::_ic [protected]
Definition at line 58 of file bm.h.
Referenced by has_ext_args(), EVAL_BM_VALUE::is_trivial(), operator==(), parse_params_obsolete_callback(), precalc_first(), and print_common_obsolete_callback().
PARAMETER<double> EVAL_BM_ACTION_BASE::_ioffset [protected]
Definition at line 54 of file bm.h.
Referenced by has_ext_args(), EVAL_BM_VALUE::is_trivial(), operator==(), parse_params_obsolete_callback(), precalc_first(), and print_common_obsolete_callback().
PARAMETER<double> EVAL_BM_ACTION_BASE::_ooffset [protected]
Definition at line 53 of file bm.h.
Referenced by has_ext_args(), EVAL_BM_VALUE::is_trivial(), operator==(), parse_params_obsolete_callback(), precalc_first(), print_common_obsolete_callback(), and tr_final_adjust().
PARAMETER<double> EVAL_BM_ACTION_BASE::_phase [protected]
Definition at line 52 of file bm.h.
Referenced by ac_final_adjust(), has_ext_args(), EVAL_BM_VALUE::is_trivial(), operator==(), parse_params_obsolete_callback(), precalc_first(), and print_common_obsolete_callback().
PARAMETER<double> EVAL_BM_ACTION_BASE::_scale [protected]
Definition at line 55 of file bm.h.
Referenced by has_ext_args(), EVAL_BM_VALUE::is_trivial(), operator==(), anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR::parse_numlist(), parse_params_obsolete_callback(), precalc_first(), print_common_obsolete_callback(), and temp_adjust().
PARAMETER<double> EVAL_BM_ACTION_BASE::_tc1 [protected]
Definition at line 56 of file bm.h.
Referenced by has_ext_args(), EVAL_BM_VALUE::is_trivial(), operator==(), parse_params_obsolete_callback(), precalc_first(), print_common_obsolete_callback(), and temp_adjust().
PARAMETER<double> EVAL_BM_ACTION_BASE::_tc2 [protected]
Definition at line 57 of file bm.h.
Referenced by has_ext_args(), EVAL_BM_VALUE::is_trivial(), operator==(), parse_params_obsolete_callback(), precalc_first(), print_common_obsolete_callback(), and temp_adjust().
The documentation for this class was generated from the following files:
savant/gnucap/src/bm.h
savant/gnucap/src/bm.cc