gnucap: LOGIC_OR Class Reference
LOGIC_OR Class Reference
#include <d_logic.h>
Public Member Functions
LOGIC_OR (int c=0)
LOGICVAL logic_eval (const node_t *n) const
virtual std::string name () const
Private Member Functions
LOGIC_OR (const LOGIC_OR &p)
COMMON_COMPONENT * clone () const
Detailed Description
Definition at line 196 of file d_logic.h.
Constructor & Destructor Documentation
LOGIC_OR::LOGIC_OR (const LOGIC_OR & p) [inline, explicit, private]
Definition at line 198 of file d_logic.h.
References COMMON_LOGIC::_count, and untested.
Referenced by clone().
:COMMON_LOGIC(p){untested();++_count;}
LOGIC_OR::LOGIC_OR (int c = 0) [inline, explicit]
Definition at line 201 of file d_logic.h.
References untested.
:COMMON_LOGIC(c) {untested();}
Member Function Documentation
COMMON_COMPONENT* LOGIC_OR::clone () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 199 of file d_logic.h.
References LOGIC_OR(), and untested.
{untested(); return new LOGIC_OR(*this);}
LOGICVAL LOGIC_OR::logic_eval (const node_t * n) const [inline, virtual]
Implements COMMON_LOGIC.
Definition at line 202 of file d_logic.h.
References COMMON_LOGIC::incount, LOGIC_NODE::lv(), and untested.
                                            {untested();
    LOGICVAL out(n[0]->lv());
    for (int ii=1; ii<incount; ++ii) {untested();
      out |= n[ii]->lv();
    }
    return out;
  }
virtual std::string LOGIC_OR::name () const [inline, virtual]
Implements COMMON_COMPONENT.
Definition at line 209 of file d_logic.h.
References itested.
{itested();return "or";}
The documentation for this class was generated from the following file:
savant/gnucap/src/d_logic.h