gnucap: anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY Class Reference
anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY Class Reference
Public Member Functions
EVAL_BM_POLY (int c=0)
~EVAL_BM_POLY ()
Private Member Functions
EVAL_BM_POLY (const EVAL_BM_POLY &p)
bool operator== (const COMMON_COMPONENT &) const
COMMON_COMPONENT * clone () const
void print_common_obsolete_callback (OMSTREAM &, LANGUAGE *) const
void precalc_first (const CARD_LIST *)
void tr_eval (ELEMENT *) const
std::string name () const
bool ac_too () const
bool parse_numlist (CS &)
bool parse_params_obsolete_callback (CS &)
void skip_type_tail (CS &cmd) const
Private Attributes
PARAMETER< double > _min
PARAMETER< double > _max
PARAMETER< bool > _abs
std::vector< PARAMETER< double > > _c
Detailed Description
Definition at line 35 of file bm_poly.cc.
Constructor & Destructor Documentation
anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::EVAL_BM_POLY (const EVAL_BM_POLY & p) [explicit, private]
Definition at line 68 of file bm_poly.cc.
  :EVAL_BM_ACTION_BASE(p),
   _min(p._min),
   _max(p._max),
   _abs(p._abs),
   _c(p._c)
{
}
anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::EVAL_BM_POLY (int c = 0) [explicit]
Definition at line 60 of file bm_poly.cc.
  :EVAL_BM_ACTION_BASE(c),
   _min(_default_min),
   _max(_default_max),
   _abs(_default_abs)
{
}
anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::~EVAL_BM_POLY () [inline]
Definition at line 44 of file bm_poly.cc.
{}
Member Function Documentation
bool anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::ac_too () const [inline, private, virtual]
Implements EVAL_BM_ACTION_BASE.
Definition at line 53 of file bm_poly.cc.
References untested.
{untested();return false;}
COMMON_COMPONENT* anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::clone () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 47 of file bm_poly.cc.
{return new EVAL_BM_POLY(*this);}
std::string anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::name () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 52 of file bm_poly.cc.
Referenced by print_common_obsolete_callback().
{return "poly";}
bool anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::operator== (const COMMON_COMPONENT & x) const [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 77 of file bm_poly.cc.
References _abs, _c, _max, _min, incomplete, anonymous_namespace{c_genrat.cc}::p, and untested.
{
  const EVAL_BM_POLY* p = dynamic_cast<const EVAL_BM_POLY*>(&x);
  bool rv = p
    && _min == p->_min
    && _max == p->_max
    && _abs == p->_abs
    && _c == p->_c
    && EVAL_BM_ACTION_BASE::operator==(x);
  if (rv) {
    incomplete();
    untested();
  }
  return rv;
}
bool anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::parse_numlist (CS & cmd) [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 151 of file bm_poly.cc.
References _c, CS::cursor(), CS::gotit(), CS::match1(), CS::reset(), CS::stuck(), and untested.
{
  unsigned start = cmd.cursor();
  unsigned here = cmd.cursor();
  for (;;) {
    unsigned old_here = here;
    PARAMETER<double> val;
    cmd >> val;
    if (cmd.stuck(&here)) {
      // no more, graceful finish
      break;
    }else{
      if (cmd.match1('=')) {
        // got one that doesn't belong, back up
        cmd.reset(old_here);
        break;
      }else{
        _c.push_back(val);
      }
    }
  }
  if (cmd.gotit(start)) {
  }else{
    untested();
  }
  return cmd.gotit(start);
}
bool anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::parse_params_obsolete_callback (CS & cmd) [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 179 of file bm_poly.cc.
References _abs, _max, _min, Get(), and ONE_OF.
{
  return ONE_OF
    || Get(cmd, "min", &_min)
    || Get(cmd, "max", &_max)
    || Get(cmd, "abs", &_abs)
    || EVAL_BM_ACTION_BASE::parse_params_obsolete_callback(cmd)
    ;
}
void anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::precalc_first (const CARD_LIST * Scope) [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 108 of file bm_poly.cc.
References _abs, _c, _max, _min, PARAMETER< T >::e_val(), and anonymous_namespace{c_genrat.cc}::p.
{
  assert(Scope);
  EVAL_BM_ACTION_BASE::precalc_first(Scope);
  for (std::vector<PARAMETER<double> >::const_iterator
         p = _c.begin();  p != _c.end();  ++p) {
    (*p).e_val(0, Scope);
  }
  _min.e_val(_default_min, Scope);
  _max.e_val(_default_max, Scope);
  _abs.e_val(_default_abs, Scope);
}
void anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::print_common_obsolete_callback (OMSTREAM & o, LANGUAGE * lang) const [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 93 of file bm_poly.cc.
References _abs, _c, _max, _min, PARAMETER< T >::has_hard_value(), name(), anonymous_namespace{c_genrat.cc}::p, and print_pair().
{
  assert(lang);
  o << name() << '(';
  for (std::vector<PARAMETER<double> >::const_iterator
         p = _c.begin();  p != _c.end();  ++p) {
    o << *p << ' ';
  }
  o << ')';
  print_pair(o, lang, "min", _min, _min.has_hard_value());
  print_pair(o, lang, "max", _max, _max.has_hard_value());
  print_pair(o, lang, "abs", _abs, _abs.has_hard_value());
  EVAL_BM_ACTION_BASE::print_common_obsolete_callback(o, lang);
}
void anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::skip_type_tail (CS & cmd) const [inline, private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 56 of file bm_poly.cc.
References CS::umatch().
{cmd.umatch("(1)");}
void anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::tr_eval (ELEMENT * d) const [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 121 of file bm_poly.cc.
References _abs, _c, _max, _min, ELEMENT::_y, COMPONENT::f_is_value(), EVAL_BM_ACTION_BASE::ioffset(), EVAL_BM_ACTION_BASE::tr_final_adjust(), and FPOLY1::x.
{
  double x = ioffset(d->_y[0].x);
  double f0 = 0.;
  double f1 = 0.;
  for (size_t i=_c.size()-1; i>0; --i) {
    f0 += _c[i];
    f0 *= x;
    f1 *= x;
    f1 += _c[i]*int(i);
  }
  f0 += _c[0];
  if (_abs && f0 < 0) {
    f0 = -f0;
    f1 = -f1;
  }
  if (f0 > _max) {
    f0 = _max;
    f1 = 0;
  }else if (f0 < _min) {
    f0 = _min;
    f1 = 0;
  }
  d->_y[0] = FPOLY1(x, f0, f1);
  tr_final_adjust(&(d->_y[0]), d->f_is_value());
}
Member Data Documentation
PARAMETER<bool> anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::_abs [private]
Definition at line 39 of file bm_poly.cc.
Referenced by operator==(), parse_params_obsolete_callback(), precalc_first(), print_common_obsolete_callback(), and tr_eval().
std::vector<PARAMETER<double> > anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::_c [private]
Definition at line 40 of file bm_poly.cc.
Referenced by operator==(), parse_numlist(), precalc_first(), print_common_obsolete_callback(), and tr_eval().
PARAMETER<double> anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::_max [private]
Definition at line 38 of file bm_poly.cc.
Referenced by operator==(), parse_params_obsolete_callback(), precalc_first(), print_common_obsolete_callback(), and tr_eval().
PARAMETER<double> anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::_min [private]
Definition at line 37 of file bm_poly.cc.
Referenced by operator==(), parse_params_obsolete_callback(), precalc_first(), print_common_obsolete_callback(), and tr_eval().
The documentation for this class was generated from the following file:
savant/gnucap/src/bm_poly.cc