gnucap: savant/gnucap/src/bm.cc File Reference
savant/gnucap/src/bm.cc File Reference
#include "u_lang.h"
#include "e_elemnt.h"
#include "bm.h"
Functions
const double _default_bandwidth (NOT_INPUT)
const double _default_delay (0.)
const double _default_phase (0.)
const double _default_ooffset (0.)
const double _default_ioffset (0.)
const double _default_scale (1.)
const double _default_tc1 (0.)
const double _default_tc2 (0.)
const double _default_ic (0.)
Function Documentation
const double _default_bandwidth (NOT_INPUT)
Referenced by EVAL_BM_ACTION_BASE::precalc_first().
const double _default_delay (0.)
Referenced by EVAL_BM_ACTION_BASE::precalc_first().
const double _default_ic (0.)
Referenced by EVAL_BM_ACTION_BASE::precalc_first().
const double _default_ioffset (0.)
Referenced by EVAL_BM_ACTION_BASE::precalc_first().
const double _default_ooffset (0.)
Referenced by EVAL_BM_ACTION_BASE::precalc_first().
const double _default_phase (0.)
Referenced by EVAL_BM_ACTION_BASE::precalc_first().
const double _default_scale (1.)
Referenced by EVAL_BM_ACTION_BASE::precalc_first().
const double _default_tc1 (0.)
Referenced by EVAL_BM_ACTION_BASE::precalc_first().
const double _default_tc2 (0.)
Referenced by EVAL_BM_ACTION_BASE::precalc_first().