gnucap: savant/gnucap/src/ap.h File Reference
savant/gnucap/src/ap.h File Reference
#include "md.h"
Classes
class CS
Enumerations
enum AP_MOD {
mNONE, mSCALE, mOFFSET, mINVERT,
mPOSITIVE, mOCTAL, mHEX
}
Functions
char * getcmd (const char *, char *, int)
INTERFACE bool Get (CS &cmd, const std::string &, bool *)
INTERFACE bool Get (CS &cmd, const std::string &, int *, AP_MOD=mNONE, int=0)
INTERFACE bool Get (CS &cmd, const std::string &, double *, AP_MOD, double=0.)
template<class T >
bool Get (CS &cmd, const std::string &key, T *val)
template<class T >
bool scan_get (CS &cmd, const std::string &key, T *val)
template<class T >
bool Set (CS &cmd, const std::string &key, T *val, T newval)
template<class T >
CS & operator>> (CS &cmd, T &val)
Variables
const bool ONE_OF = false
Enumeration Type Documentation
enum AP_MOD
Enumerator:
mNONE
mSCALE
mOFFSET
mINVERT
mPOSITIVE
mOCTAL
mHEX
Definition at line 31 of file ap.h.
           {
  mNONE,        /* nothing special */
  mSCALE,       /* scale it after reading */
  mOFFSET,      /* add an offset */
  mINVERT,      /* save 1 / the number */
  mPOSITIVE,    /* store absolute value */
  mOCTAL,       /* read the number in octal */
  mHEX          /* read the number in hex */
};
Function Documentation
INTERFACE bool Get (CS & cmd, const std::string & , bool *)
Definition at line 30 of file ap_get.cc.
References itested, CS::skip1b(), and CS::umatch().
Referenced by anonymous_namespace{c_genrat.cc}::CMD_::do_it(), anonymous_namespace{measure_at.cc}::MEASURE::eval(), anonymous_namespace{measure_average.cc}::MEASURE::eval(), anonymous_namespace{measure_cross.cc}::MEASURE::eval(), anonymous_namespace{measure_integral.cc}::MEASURE::eval(), anonymous_namespace{measure_max.cc}::MEASURE::eval(), anonymous_namespace{measure_min.cc}::MEASURE::eval(), anonymous_namespace{measure_rms.cc}::MEASURE::eval(), anonymous_namespace{measure_slewrate.cc}::MEASURE::eval(), anonymous_namespace{lang_spice.cc}::getmerge(), anonymous_namespace{s_dc.cc}::DCOP::options(), TRANSIENT::options(), anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::parse_params_obsolete_callback(), EVAL_BM_SEMI_BASE::parse_params_obsolete_callback(), anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::parse_params_obsolete_callback(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::parse_params_obsolete_callback(), anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY::parse_params_obsolete_callback(), anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT::parse_params_obsolete_callback(), anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE::parse_params_obsolete_callback(), anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP::parse_params_obsolete_callback(), anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM::parse_params_obsolete_callback(), anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::parse_params_obsolete_callback(), MODEL_TABLE::parse_params_obsolete_callback(), EVAL_BM_ACTION_BASE::parse_params_obsolete_callback(), EVAL_BM_VALUE::parse_params_obsolete_callback(), COMMON_COMPONENT::parse_params_obsolete_callback(), OPT::set_values(), and anonymous_namespace{s_ac.cc}::AC::setup().
{
  if (cmd.umatch(key + ' ')) {
    if (cmd.skip1b('=')) {itested();
      cmd >> *val;
    }else{
      *val = true;
    }
    return true;
  }else if (cmd.umatch("no" + key)) {
    *val = false;
    return true;
  }else{
    return false;
  }
}
INTERFACE bool Get (CS & cmd, const std::string & , int * , AP_MOD = mNONE, int = 0)
Definition at line 47 of file ap_get.cc.
References CS::ctof(), CS::ctoo(), CS::ctox(), mHEX, mINVERT, mNONE, mOCTAL, mOFFSET, mPOSITIVE, mSCALE, CS::umatch(), and untested.
{
  if (cmd.umatch(key + " {=}")) {
    switch(mod) {
    case mNONE:                 *val = int(cmd.ctof());         break;
    case mSCALE:    untested(); *val = int(cmd.ctof())*scale;   break;
    case mOFFSET:   untested(); *val = int(cmd.ctof())+scale;   break;
    case mINVERT:   untested(); *val = 1 / int(cmd.ctof());     break;
    case mPOSITIVE: untested(); *val = std::abs(int(cmd.ctof())); break;
    case mOCTAL:                *val = cmd.ctoo();              break;
    case mHEX:      untested(); *val = cmd.ctox();              break;
    }
    return true;
  }else{
    return false;
  }
}
INTERFACE bool Get (CS & cmd, const std::string & , double * , AP_MOD , double = 0.)
Definition at line 65 of file ap_get.cc.
References CS::ctof(), CS::ctoo(), CS::ctox(), mHEX, mINVERT, mNONE, mOCTAL, mOFFSET, mPOSITIVE, mSCALE, CS::umatch(), and untested.
{
  if (cmd.umatch(key + " {=}")) {
    switch(mod) {
    case mNONE:     untested(); *val = cmd.ctof();              break;
    case mSCALE:    untested(); *val = cmd.ctof()*scale;        break;
    case mOFFSET:   untested(); *val = cmd.ctof()+scale;        break;
    case mINVERT:   untested(); *val = 1 / cmd.ctof();          break;
    case mPOSITIVE:             *val = std::abs(cmd.ctof());    break;
    case mOCTAL:    untested(); *val = cmd.ctoo();              break;
    case mHEX:      untested(); *val = cmd.ctox();              break;
    }
    return true;
  }else{
    return false;
  }
}
template<class T > bool Get (CS & cmd, const std::string & key, T * val)
Definition at line 170 of file ap.h.
References CS::umatch().
{
  if (cmd.umatch(key + " {=}")) {
    cmd >> *val;
    return true;
  }else{
    return false;
  }
}
char* getcmd (const char * , char * , int)
Definition at line 176 of file ap_construct.cc.
References OPT::edit, itested, mout, IO::mstdout, trim(), and untested.
Referenced by anonymous_namespace{c_sweep.cc}::buildfile(), CS::get_line(), and xopen().
{
  assert(prompt);
  assert(buffer);
  if (isatty(fileno(stdin))) {
    // stdin is keyboard
#if defined(HAVE_LIBREADLINE)
    if (OPT::edit) {
      char* line_read = readline(prompt);
      if (!line_read) {itested();
        throw Exception_End_Of_Input("EOF on stdin");
      }else{
      }
      // readline gets a new buffer every time, so copy it to where we want it
      char* end_of_line = (char*)memccpy(buffer, line_read, 0, static_cast<size_t>(buflen-1));
      if (!end_of_line) {
        buffer[buflen-1] = '\0';
      }else{
        *end_of_line = '\0';
      }
      free(line_read);
      if (*buffer) {
        add_history(buffer);
      }else{
      }
    }else
#endif
      {
        IO::mstdout << prompt;  /* prompt & flush buffer */
        if (!fgets(buffer, buflen, stdin)) {untested(); /* read line */
          throw Exception_End_Of_Input("EOF on stdin");
        }else{
        }
      }
    (IO::mstdout - mout) << '\r';       /* reset col counter */
    trim(buffer);
    (mlog + mout) << buffer << '\n';
    return buffer;
  }else{
    // stdin is file
    if (!fgets(buffer, buflen, stdin)) {itested();      /* read line */
      throw Exception_End_Of_Input("EOF on stdin");
    }else{
    }
    trim(buffer);
    (mlog + mout) << buffer << '\n';
    return buffer;
  }
}
template<class T > CS& operator>> (CS & cmd, T & val) [inline]
Definition at line 203 of file ap.h.
{
  val.parse(cmd);
  return cmd;
}
template<class T > bool scan_get (CS & cmd, const std::string & key, T * val) [inline]
Definition at line 181 of file ap.h.
References CS::scan().
Referenced by anonymous_namespace{lang_spice.cc}::CMD_MODEL::do_it().
{
  if (cmd.scan(key)) {
    cmd >> '=' >> *val;
    return true;
  }else{
    return false;
  }
}
template<class T > bool Set (CS & cmd, const std::string & key, T * val, T newval) [inline]
Definition at line 192 of file ap.h.
References CS::umatch().
Referenced by CS::ctob(), anonymous_namespace{c_prbcmd.cc}::do_probe(), anonymous_namespace{measure_cross.cc}::MEASURE::eval(), anonymous_namespace{measure_max.cc}::MEASURE::eval(), anonymous_namespace{measure_min.cc}::MEASURE::eval(), anonymous_namespace{measure_slewrate.cc}::MEASURE::eval(), anonymous_namespace{s_dc.cc}::DCOP::options(), TRANSIENT::options(), anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::parse_common_obsolete_callback(), and OPT::set_values().
{
  if (cmd.umatch(key + ' ')) {
    *val = newval;
    return true;
  }else{
    return false;
  }
}
Variable Documentation
const bool ONE_OF = false
Definition at line 41 of file ap.h.
Referenced by CS::ctob(), anonymous_namespace{c_genrat.cc}::CMD_::do_it(), anonymous_namespace{c_prbcmd.cc}::do_probe(), anonymous_namespace{measure_at.cc}::MEASURE::eval(), anonymous_namespace{measure_average.cc}::MEASURE::eval(), anonymous_namespace{measure_cross.cc}::MEASURE::eval(), anonymous_namespace{measure_integral.cc}::MEASURE::eval(), anonymous_namespace{measure_max.cc}::MEASURE::eval(), anonymous_namespace{measure_min.cc}::MEASURE::eval(), anonymous_namespace{measure_rms.cc}::MEASURE::eval(), anonymous_namespace{measure_slewrate.cc}::MEASURE::eval(), anonymous_namespace{lang_spice.cc}::getmerge(), anonymous_namespace{s_dc.cc}::DCOP::options(), TRANSIENT::options(), anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::parse_common_obsolete_callback(), anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::parse_params_obsolete_callback(), EVAL_BM_SEMI_BASE::parse_params_obsolete_callback(), anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::parse_params_obsolete_callback(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::parse_params_obsolete_callback(), anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY::parse_params_obsolete_callback(), anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT::parse_params_obsolete_callback(), anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP::parse_params_obsolete_callback(), anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE::parse_params_obsolete_callback(), anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM::parse_params_obsolete_callback(), anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::parse_params_obsolete_callback(), EVAL_BM_ACTION_BASE::parse_params_obsolete_callback(), EVAL_BM_VALUE::parse_params_obsolete_callback(), COMMON_COMPONENT::parse_params_obsolete_callback(), OPT::set_values(), and anonymous_namespace{s_ac.cc}::AC::setup().