gnucap: Base Class Reference
Base Class Reference
#include <m_base.h>
Public Member Functions
virtual void parse (CS &)=0
virtual void dump (std::ostream &o) const =0
virtual ~Base ()
virtual std::string val_string () const
virtual bool to_bool () const
virtual Base * minus () const
virtual Base * plus () const
virtual Base * less (const Base *) const
virtual Base * less (const Float *) const
virtual Base * less (const String *) const
virtual Base * greater (const Base *) const
virtual Base * greater (const Float *) const
virtual Base * greater (const String *) const
virtual Base * leq (const Base *) const
virtual Base * leq (const Float *) const
virtual Base * leq (const String *) const
virtual Base * geq (const Base *) const
virtual Base * geq (const Float *) const
virtual Base * geq (const String *) const
virtual Base * not_equal (const Base *) const
virtual Base * not_equal (const Float *) const
virtual Base * not_equal (const String *) const
virtual Base * equal (const Base *) const
virtual Base * equal (const Float *) const
virtual Base * equal (const String *) const
virtual Base * add (const Base *) const
virtual Base * add (const Float *) const
virtual Base * add (const String *) const
virtual Base * multiply (const Base *) const
virtual Base * multiply (const Float *) const
virtual Base * multiply (const String *) const
virtual Base * subtract (const Base *) const
virtual Base * subtract (const Float *) const
virtual Base * subtract (const String *) const
virtual Base * r_subtract (const Base *) const
virtual Base * r_subtract (const Float *) const
virtual Base * r_subtract (const String *) const
virtual Base * divide (const Base *) const
virtual Base * divide (const Float *) const
virtual Base * divide (const String *) const
virtual Base * r_divide (const Base *) const
virtual Base * r_divide (const Float *) const
virtual Base * r_divide (const String *) const
Base * logic_not () const
Base * logic_or (const Base *X) const
Base * logic_and (const Base *X) const
Protected Member Functions
Base ()
Private Member Functions
Base (const Base &)
Detailed Description
Definition at line 33 of file m_base.h.
Constructor & Destructor Documentation
Base::Base (const Base &) [inline, explicit, private]
Definition at line 36 of file m_base.h.
References unreachable.
{unreachable();}
Base::Base () [inline, explicit, protected]
Definition at line 40 of file m_base.h.
{}
virtual Base::~Base () [inline, virtual]
Definition at line 44 of file m_base.h.
{}
Member Function Documentation
virtual Base* Base::add (const Base *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 69 of file m_base.h.
References untested.
Referenced by Float::add(), String::add(), and Token_BINOP::op().
{untested(); return NULL;}
virtual Base* Base::add (const Float *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 70 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual Base* Base::add (const String *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 71 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual Base* Base::divide (const Base *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 81 of file m_base.h.
References untested.
Referenced by Token_BINOP::op(), Float::r_divide(), and String::r_divide().
{untested(); return NULL;}
virtual Base* Base::divide (const Float *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 82 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual Base* Base::divide (const String *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 83 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual void Base::dump (std::ostream & o) const [pure virtual]
Implemented in String, Float, Expression, List_Base< T >, List_Base< Token >, and Token.
Referenced by operator<<().
virtual Base* Base::equal (const Base *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 66 of file m_base.h.
References untested.
Referenced by Float::equal(), String::equal(), and Token_BINOP::op().
{untested(); return NULL;}
virtual Base* Base::equal (const Float *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 67 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual Base* Base::equal (const String *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 68 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual Base* Base::geq (const Base *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 60 of file m_base.h.
References untested.
Referenced by Float::leq(), String::leq(), and Token_BINOP::op().
{untested(); return NULL;}
virtual Base* Base::geq (const Float *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 61 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual Base* Base::geq (const String *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 62 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual Base* Base::greater (const Base *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 54 of file m_base.h.
References untested.
Referenced by Float::less(), String::less(), and Token_BINOP::op().
{untested(); return NULL;}
virtual Base* Base::greater (const Float *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 55 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual Base* Base::greater (const String *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 56 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual Base* Base::leq (const Base *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 57 of file m_base.h.
References untested.
Referenced by Float::geq(), String::geq(), and Token_BINOP::op().
{untested(); return NULL;}
virtual Base* Base::leq (const Float *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 58 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual Base* Base::leq (const String *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 59 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual Base* Base::less (const Base *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 51 of file m_base.h.
References untested.
Referenced by Float::greater(), String::greater(), and Token_BINOP::op().
{untested(); return NULL;}
virtual Base* Base::less (const Float *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 52 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual Base* Base::less (const String *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 53 of file m_base.h.
References untested.
{untested(); return NULL;}
Base * Base::logic_and (const Base * X) const
Definition at line 52 of file m_base_math.cc.
References to_bool().
Referenced by Token_BINOP::op().
{
  if (!to_bool() || !X || !X->to_bool()) {
    return new Float(0.);
  }else{
    return new Float(1.);
  }
}
Base * Base::logic_not () const
Definition at line 34 of file m_base_math.cc.
References to_bool(), and untested.
Referenced by Token_UNARY::op().
{
  if (to_bool()) {
    return new Float(0.);
  }else{untested();
    return new Float(1.);
  }
}
Base * Base::logic_or (const Base * X) const
Definition at line 43 of file m_base_math.cc.
References to_bool().
Referenced by Token_BINOP::op().
{
  if ((to_bool()) || (X && X->to_bool())) {
    return new Float(1.);
  }else{
    return new Float(0.);
  }
}
virtual Base* Base::minus () const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 48 of file m_base.h.
References untested.
Referenced by Token_UNARY::op().
{untested(); return NULL;}
virtual Base* Base::multiply (const Base *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 72 of file m_base.h.
References untested.
Referenced by Float::multiply(), String::multiply(), and Token_BINOP::op().
{untested(); return NULL;}
virtual Base* Base::multiply (const Float *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 73 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual Base* Base::multiply (const String *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 74 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual Base* Base::not_equal (const Base *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 63 of file m_base.h.
References untested.
Referenced by Float::not_equal(), String::not_equal(), and Token_BINOP::op().
{untested(); return NULL;}
virtual Base* Base::not_equal (const Float *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 64 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual Base* Base::not_equal (const String *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 65 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual void Base::parse (CS &) [pure virtual]
Implemented in Tail_String, Quoted_String, Name_String, String, Float, List< T >, Expression, List_Base< T >, List_Base< Token >, and Token.
Referenced by operator>>().
virtual Base* Base::plus () const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 49 of file m_base.h.
References untested.
Referenced by Token_UNARY::op().
{untested(); return NULL;}
virtual Base* Base::r_divide (const Base *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 84 of file m_base.h.
References untested.
Referenced by Float::divide(), and String::divide().
{untested(); return NULL;}
virtual Base* Base::r_divide (const Float *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 85 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual Base* Base::r_divide (const String *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 86 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual Base* Base::r_subtract (const Base *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 78 of file m_base.h.
References untested.
Referenced by Float::subtract(), and String::subtract().
{untested(); return NULL;}
virtual Base* Base::r_subtract (const Float *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 79 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual Base* Base::r_subtract (const String *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 80 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual Base* Base::subtract (const Base *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 75 of file m_base.h.
References untested.
Referenced by Token_BINOP::op(), Float::r_subtract(), and String::r_subtract().
{untested(); return NULL;}
virtual Base* Base::subtract (const Float *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 76 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual Base* Base::subtract (const String *) const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 77 of file m_base.h.
References untested.
{untested(); return NULL;}
virtual bool Base::to_bool () const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 46 of file m_base.h.
References unreachable.
Referenced by logic_and(), logic_not(), and logic_or().
{unreachable(); return false;}
virtual std::string Base::val_string () const [inline, virtual]
Reimplemented in String, and Float.
Definition at line 45 of file m_base.h.
References untested.
{untested(); return "error";}
The documentation for this class was generated from the following files:
savant/gnucap/src/m_base.h
savant/gnucap/src/m_base_math.cc