gnucap: savant/gnucap/src/io_xopen.cc File Reference
savant/gnucap/src/io_xopen.cc File Reference
#include "u_opt.h"
#include "constant.h"
#include "ap.h"
Functions
void xclose (FILE **)
FILE * xopen (CS &, const char *, const char *)
Function Documentation
void xclose (FILE ** fn)
Definition at line 34 of file io_xopen.cc.
Referenced by file_open(), and outreset().
{
  if (*fn) {
    fclose(*fn);
    *fn = NULL;
  }
}
FILE* xopen (CS & cmd, const char * ext, const char * how)
Definition at line 48 of file io_xopen.cc.
References BIGBUFLEN, BUFLEN, OPT::clobber, CS::ctoc(), ENDDIR, error(), FILE_OK, getcmd(), CS::is_end(), itested, MAXHANDLE, CS::skip(), CS::skipbl(), CS::skipcom(), IO::stream, trim(), Umatch(), and untested.
Referenced by anonymous_namespace{c_file.cc}::CMD_LOG::do_it(), anonymous_namespace{c_file.cc}::CMD_FILE::do_it(), and file_open().
{
  char fname[BIGBUFLEN];
  cmd.skipbl();
  if (cmd.is_end()) {untested();
    cmd = getcmd("file name?  ",fname, BIGBUFLEN);
  }
                                        /* copy the name                    */
  cmd.skipbl();                         /* and while we're at it ...        */
  {                                     /* find out if we want to add the   */
    bool defalt = true;                 /* default extension                */
    size_t i;
    for (i = 0;   i < BIGBUFLEN;   ) {
      char c = cmd.ctoc();
      if (!c || isspace(c)) {
        break;
      }
      if (c == '$') {untested();
        sprintf(&(fname[i]), "%ld", static_cast<long>(time(0)));
        i = strlen(fname);
      }else{                            /* we want to add the extension     */
        fname[i++] = c;                 /* if it doesn't already have one,  */
        if (c == '.') {         /* as determined by a '.'           */
          defalt = false;               /* not before the directory         */
        }else if (strchr(ENDDIR,c)) {   /* separator-terminator character   */
          itested();
          defalt = true;                /* '\' or '/' for msdos,            */
        }
      }                                 /* ']' or '/' for vms,              */
    }                                   /* '/' for unix  (in ENDDIR)        */
    cmd.skip(-1);
    if (defalt && ext && *ext && i+strlen(ext)+2 < BIGBUFLEN) {untested();
      fname[i++] = '.';                 /* add the extension (maybe)        */
      strcpy(&fname[i],ext);
    }else{
      fname[i] = '\0';
    }
  }
  trim(fname);
  if (strlen(fname)==0) {
    return NULL;
  }
  cmd.skipcom();
  FILE *code = NULL;    /* a file pointer for the file we found */
  if (!OPT::clobber && (*how == 'w') && (access(fname,F_OK) == FILE_OK)) {untested();
    char buffer[BUFLEN];
    std::string msg = std::string(fname) + " exists.  replace? ";
    getcmd(msg.c_str(), buffer, BUFLEN);
    if (Umatch(buffer,"y{es} ")) {untested();   /* should be new file, but          */
      code = fopen(fname,how);          /* file already exists,  ask        */
    }else{untested();
      return NULL;
    }
  }else{
    code = fopen(fname,how);
  }
  if (code && fileno(code)>MAXHANDLE) {untested();
    error(bWARNING, "internal error: files: %d\n", fileno(code));
    fclose(code);
    code = NULL;
  }
  if (code) {
    IO::stream[static_cast<int>(fileno(code))] = code;
  }else{itested();
    error(bWARNING, "can't open %s, %s\n", fname, strerror(errno));
  }
  return code;
}