gnucap: MODEL_TABLE Class Reference
MODEL_TABLE Class Reference
Public Member Functions
MODEL_TABLE ()
~MODEL_TABLE ()
Public Attributes
PARAMETER< int > _order
PARAMETER< double > _below
PARAMETER< double > _above
std::vector< std::pair
< PARAMETER< double >
, PARAMETER< double > > > _table
SPLINE * _spline
Private Member Functions
MODEL_TABLE (const MODEL_TABLE &p)
std::string dev_type () const
void precalc_first ()
COMMON_COMPONENT * new_common () const
CARD * clone () const
bool use_obsolete_callback_print () const
bool use_obsolete_callback_parse () const
void print_args_obsolete_callback (OMSTREAM &, LANGUAGE *) const
bool parse_params_obsolete_callback (CS &)
void tr_eval (COMPONENT *) const
Static Private Attributes
static int const _default_order = 3
static double const _default_below = NOT_INPUT
static double const _default_above = NOT_INPUT
Detailed Description
Definition at line 50 of file bmm_table.cc.
Constructor & Destructor Documentation
MODEL_TABLE::MODEL_TABLE (const MODEL_TABLE & p) [explicit, private]
Definition at line 145 of file bmm_table.cc.
  :MODEL_CARD(p),
   _order(p._order),
   _below(p._below),
   _above(p._above),
   _table(p._table),
   _spline(p._spline)
{
}
MODEL_TABLE::MODEL_TABLE () [explicit]
Definition at line 135 of file bmm_table.cc.
Referenced by clone().
  :MODEL_CARD(NULL),
   _order(_default_order),
   _below(_default_below),
   _above(_default_above),
   _table(),
   _spline(0)
{
}
MODEL_TABLE::~MODEL_TABLE ()
Definition at line 155 of file bmm_table.cc.
References _spline.
{
  delete _spline;
}
Member Function Documentation
CARD* MODEL_TABLE::clone () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 70 of file bmm_table.cc.
References MODEL_TABLE().
{return new MODEL_TABLE(*this);}
std::string MODEL_TABLE::dev_type () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 67 of file bmm_table.cc.
{return "table";}
COMMON_COMPONENT* MODEL_TABLE::new_common () const [inline, private, virtual]
Reimplemented from MODEL_CARD.
Definition at line 69 of file bmm_table.cc.
{return new EVAL_BM_TABLE;}
bool MODEL_TABLE::parse_params_obsolete_callback (CS & cmd) [private, virtual]
Reimplemented from MODEL_CARD.
Definition at line 160 of file bmm_table.cc.
References _above, _below, _order, _table, CS::cursor(), Get(), anonymous_namespace{c_genrat.cc}::p, CS::reset(), CS::skip1b(), CS::stuck(), untested, and CS::warn().
{
  unsigned here1 = cmd.cursor();
  {
    Get(cmd, "order", &_order);
    Get(cmd, "below", &_below);
    Get(cmd, "above", &_above);
    bool got_opening_paren = cmd.skip1b('(');
    unsigned here = cmd.cursor();
    for (;;) {
      unsigned start_of_pair = here;
      std::pair<PARAMETER<double>, PARAMETER<double> > p;
      cmd >> p.first; // key
      if (cmd.stuck(&here)) {
        break;
      }else{
        cmd >> p.second; // value
        if (cmd.stuck(&here)) {
          cmd.reset(start_of_pair);
          break;
        }else{
          _table.push_back(p);
        }
      }
    }
    if (got_opening_paren && !cmd.skip1b(')')) {
      untested();
      cmd.warn(bWARNING, "need )");
    }else if (!got_opening_paren && cmd.skip1b(')')) {
      untested();
      cmd.warn(bWARNING, here, "need (");
    }
  }
  return !(cmd.stuck(&here1));
}
void MODEL_TABLE::precalc_first () [private, virtual]
Reimplemented from MODEL_CARD.
Definition at line 210 of file bmm_table.cc.
References _above, _below, _default_above, _default_below, _default_order, _order, _spline, _table, BIGBIG, PARAMETER< T >::e_val(), error(), PARAMETER< T >::has_hard_value(), CARD::long_label(), NOT_INPUT, anonymous_namespace{c_genrat.cc}::p, CARD::scope(), and untested.
{
  MODEL_CARD::precalc_first();
  const CARD_LIST* par_scope = scope();
  assert(par_scope);
  _order.e_val(_default_order, par_scope);
  _below.e_val(_default_below, par_scope);
  _above.e_val(_default_above, par_scope);
  {
    double last = -BIGBIG;
    for (std::vector<std::pair<PARAMETER<double>,PARAMETER<double> > >::
           iterator p = _table.begin();  p != _table.end();  ++p) {
      p->first.e_val(0, par_scope);
      p->second.e_val(0, par_scope);
      if (last > p->first) {
        untested();
        error(bWARNING, "%s: table is out of order: (%g, %g)\n",
              long_label().c_str(), last, double(p->first));
      }else{
        //std::pair<double,double> x(p->first, p->second);
        //_num_table.push_back(x);
      }
      last = p->first;
    }
  }
  delete _spline;
  double below = _below.has_hard_value() ? _below : NOT_INPUT;
  double above = _above.has_hard_value() ? _above : NOT_INPUT;
  _spline = new SPLINE(_table, below, above, _order);
}
void MODEL_TABLE::print_args_obsolete_callback (OMSTREAM & o, LANGUAGE * lang) const [private, virtual]
Reimplemented from CARD.
Definition at line 196 of file bmm_table.cc.
References _above, _below, _order, _table, PARAMETER< T >::has_hard_value(), anonymous_namespace{c_genrat.cc}::p, and print_pair().
{
  assert(lang);
  print_pair(o, lang, "order", _order);
  print_pair(o, lang, "below", _below, _below.has_hard_value());
  print_pair(o, lang, "above", _above, _above.has_hard_value());
  o << " (";
  for (std::vector<std::pair<PARAMETER<double>,PARAMETER<double> > >::
         const_iterator p = _table.begin();  p != _table.end();  ++p) {
    o << p->first << ',' << p->second << ' ';
  }
  o << ')';
}
void MODEL_TABLE::tr_eval (COMPONENT * brh) const [private, virtual]
Reimplemented from MODEL_CARD.
Definition at line 245 of file bmm_table.cc.
References _spline, ELEMENT::_y, SPLINE::at(), prechecked_cast, and FPOLY1::x.
{
  ELEMENT* d = prechecked_cast<ELEMENT*>(brh);
  assert(d);
  d->_y[0] = _spline->at(d->_y[0].x);
}
bool MODEL_TABLE::use_obsolete_callback_parse () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 73 of file bmm_table.cc.
{return true;}
bool MODEL_TABLE::use_obsolete_callback_print () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 72 of file bmm_table.cc.
{return true;}
Member Data Documentation
PARAMETER<double> MODEL_TABLE::_above
Definition at line 54 of file bmm_table.cc.
Referenced by parse_params_obsolete_callback(), precalc_first(), and print_args_obsolete_callback().
PARAMETER<double> MODEL_TABLE::_below
Definition at line 53 of file bmm_table.cc.
Referenced by parse_params_obsolete_callback(), precalc_first(), and print_args_obsolete_callback().
double const MODEL_TABLE::_default_above = NOT_INPUT [static, private]
Definition at line 60 of file bmm_table.cc.
Referenced by precalc_first().
double const MODEL_TABLE::_default_below = NOT_INPUT [static, private]
Definition at line 59 of file bmm_table.cc.
Referenced by precalc_first().
int const MODEL_TABLE::_default_order = 3 [static, private]
Definition at line 58 of file bmm_table.cc.
Referenced by precalc_first().
PARAMETER<int> MODEL_TABLE::_order
Definition at line 52 of file bmm_table.cc.
Referenced by parse_params_obsolete_callback(), precalc_first(), and print_args_obsolete_callback().
SPLINE* MODEL_TABLE::_spline
Definition at line 56 of file bmm_table.cc.
Referenced by precalc_first(), tr_eval(), and ~MODEL_TABLE().
std::vector<std::pair<PARAMETER<double>,PARAMETER<double> > > MODEL_TABLE::_table
Definition at line 55 of file bmm_table.cc.
Referenced by parse_params_obsolete_callback(), precalc_first(), and print_args_obsolete_callback().
The documentation for this class was generated from the following file:
savant/gnucap/src/bmm_table.cc