gnucap: anonymous_namespace{lang_verilog.cc}::CMD_PARAMSET Class Reference
anonymous_namespace{lang_verilog.cc}::CMD_PARAMSET Class Reference
Private Member Functions
void do_it (CS &cmd, CARD_LIST *Scope)
Detailed Description
Definition at line 449 of file lang_verilog.cc.
Member Function Documentation
void anonymous_namespace{lang_verilog.cc}::CMD_PARAMSET::do_it (CS & cmd, CARD_LIST * Scope) [inline, private, virtual]
Implements CMD.
Definition at line 450 of file lang_verilog.cc.
References CARD::clone(), CS::cursor(), exists(), LANGUAGE::find_proto(), anonymous_namespace{lang_verilog.cc}::lang_verilog, CARD::owner(), anonymous_namespace{c_genrat.cc}::p, anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_paramset(), CARD_LIST::push_back(), and CS::warn().
  {
    // already got "paramset"
    std::string my_name, base_name;
    cmd >> my_name;
    unsigned here = cmd.cursor();
    cmd >> base_name;
    //const MODEL_CARD* p = model_dispatcher[base_name];
    const CARD* p = lang_verilog.find_proto(base_name, NULL);
    if (p) {
      MODEL_CARD* new_card = dynamic_cast<MODEL_CARD*>(p->clone());
      if (exists(new_card)) {
        assert(!new_card->owner());
        lang_verilog.parse_paramset(cmd, new_card);
        Scope->push_back(new_card);
      }else{    //BUG// memory leak
        cmd.warn(bDANGER, here, "paramset: base has incorrect type");
      }
    }else{
      cmd.warn(bDANGER, here, "paramset: no match");
    }
  }
The documentation for this class was generated from the following file:
savant/gnucap/src/lang_verilog.cc