gnucap: anonymous_namespace{d_res.cc}::DEV_RESISTANCE Class Reference
anonymous_namespace{d_res.cc}::DEV_RESISTANCE Class Reference
Public Member Functions
DEV_RESISTANCE ()
Private Member Functions
DEV_RESISTANCE (const DEV_RESISTANCE &p)
char id_letter () const
std::string value_name () const
std::string dev_type () const
int max_nodes () const
int min_nodes () const
int matrix_nodes () const
int net_nodes () const
bool has_iv_probe () const
bool use_obsolete_callback_parse () const
CARD * clone () const
void precalc_last ()
void tr_iwant_matrix ()
void tr_begin ()
bool do_tr ()
void tr_load ()
void tr_unload ()
double tr_involts () const
double tr_input () const
double tr_involts_limited () const
double tr_input_limited () const
void ac_iwant_matrix ()
void ac_begin ()
void do_ac ()
void ac_load ()
COMPLEX ac_involts () const
std::string port_name (int i) const
Detailed Description
Definition at line 31 of file d_res.cc.
Constructor & Destructor Documentation
anonymous_namespace{d_res.cc}::DEV_RESISTANCE::DEV_RESISTANCE (const DEV_RESISTANCE & p) [inline, explicit, private]
Definition at line 33 of file d_res.cc.
:ELEMENT(p) {}
anonymous_namespace{d_res.cc}::DEV_RESISTANCE::DEV_RESISTANCE () [inline, explicit]
Definition at line 35 of file d_res.cc.
:ELEMENT() {}
Member Function Documentation
void anonymous_namespace{d_res.cc}::DEV_RESISTANCE::ac_begin () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 58 of file d_res.cc.
{_ev = _y[0].f1; _acg = 1. / _ev;}
COMPLEX anonymous_namespace{d_res.cc}::DEV_RESISTANCE::ac_involts () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 61 of file d_res.cc.
{return ac_outvolts();}
void anonymous_namespace{d_res.cc}::DEV_RESISTANCE::ac_iwant_matrix () [inline, private, virtual]
Implements ELEMENT.
Definition at line 57 of file d_res.cc.
{ac_iwant_matrix_passive();}
void anonymous_namespace{d_res.cc}::DEV_RESISTANCE::ac_load () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 60 of file d_res.cc.
{ac_load_passive();}
CARD* anonymous_namespace{d_res.cc}::DEV_RESISTANCE::clone () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 46 of file d_res.cc.
{return new DEV_RESISTANCE(*this);}
std::string anonymous_namespace{d_res.cc}::DEV_RESISTANCE::dev_type () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 39 of file d_res.cc.
{return "resistor";}
void anonymous_namespace{d_res.cc}::DEV_RESISTANCE::do_ac () [private, virtual]
Reimplemented from CARD.
Definition at line 122 of file d_res.cc.
References error(), and OPT::shortckt.
{
  if (using_ac_eval()) {
    ac_eval();
    if (_ev == 0.) {
      error(bPICKY, long_label() + ": short circuit\n");
      _ev = OPT::shortckt;
    }else{
    }
    _acg = 1. / _ev;
  }else{
    assert(_ev == _y[0].f1);
    assert(has_tr_eval() || _ev == double(value()) || _ev == OPT::shortckt);
  }
}
bool anonymous_namespace{d_res.cc}::DEV_RESISTANCE::do_tr () [private, virtual]
Reimplemented from CARD.
Definition at line 94 of file d_res.cc.
References conchk(), converged, error(), LINEAR, and OPT::shortckt.
{
  if (using_tr_eval()) {
    _m0.x = tr_involts_limited();
    _y[0].x = tr_input_limited();;
    tr_eval();
    assert(_y[0].f0 != LINEAR);
    if (_y[0].f1 == 0.) {
      error(bPICKY, long_label() + ": short circuit\n");
      _y[0].f1 = OPT::shortckt;
      set_converged(conv_check());
    }else{
    }
    store_values();
    q_load();
    _m0.c1 = 1./_y[0].f1;
    _m0.c0 = _y[0].x - _y[0].f0 / _y[0].f1;
  }else{
    assert(_y[0].f0 == LINEAR);
    assert(_y[0].f1 == value() || _y[0].f1 == OPT::shortckt);
    assert(conchk(_m0.c1, 1./_y[0].f1));
    assert(_m0.c0 == 0.);
    assert(_y1 == _y[0]);
    assert(converged());
  }
  return converged();
}
bool anonymous_namespace{d_res.cc}::DEV_RESISTANCE::has_iv_probe () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 44 of file d_res.cc.
{return true;}
char anonymous_namespace{d_res.cc}::DEV_RESISTANCE::id_letter () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 37 of file d_res.cc.
{return 'R';}
int anonymous_namespace{d_res.cc}::DEV_RESISTANCE::matrix_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 42 of file d_res.cc.
{return 2;}
int anonymous_namespace{d_res.cc}::DEV_RESISTANCE::max_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 40 of file d_res.cc.
{return 2;}
int anonymous_namespace{d_res.cc}::DEV_RESISTANCE::min_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 41 of file d_res.cc.
{return 2;}
int anonymous_namespace{d_res.cc}::DEV_RESISTANCE::net_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 43 of file d_res.cc.
{return 2;}
std::string anonymous_namespace{d_res.cc}::DEV_RESISTANCE::port_name (int i) const [inline, private, virtual]
Implements COMPONENT.
Definition at line 63 of file d_res.cc.
References itested.
                                  {itested();
    assert(i >= 0);
    assert(i < 2);
    static std::string names[] = {"p", "n"};
    return names[i];
  }
void anonymous_namespace{d_res.cc}::DEV_RESISTANCE::precalc_last () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 71 of file d_res.cc.
References ELEMENT::precalc_last().
{
  ELEMENT::precalc_last();
  set_constant(!has_tr_eval());
  set_converged(!has_tr_eval());
}
void anonymous_namespace{d_res.cc}::DEV_RESISTANCE::tr_begin () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 78 of file d_res.cc.
References error(), OPT::shortckt, and ELEMENT::tr_begin().
{
  ELEMENT::tr_begin();
  _y1.f1 = _y[0].f1 = (value() != 0.) ? value() : OPT::shortckt;
  _m0.x  = _y[0].x;
  _m0.c1 = 1./_y[0].f1;
  _m0.c0 = 0.;
  _m1 = _m0;
  assert(_loss0 == 0.);
  assert(_loss1 == 0.);
  if (value() == 0. && !has_common()) {
    error(bPICKY, long_label() + ": short circuit\n");
  }else{
  }
}
double anonymous_namespace{d_res.cc}::DEV_RESISTANCE::tr_input () const [inline, private, virtual]
Reimplemented from ELEMENT.
Definition at line 54 of file d_res.cc.
References untested.
{untested(); return _m0.c0 + _m0.c1 * tr_involts();}
double anonymous_namespace{d_res.cc}::DEV_RESISTANCE::tr_input_limited () const [inline, private, virtual]
Reimplemented from ELEMENT.
Definition at line 56 of file d_res.cc.
{return _m0.c0+_m0.c1*tr_involts_limited();}
double anonymous_namespace{d_res.cc}::DEV_RESISTANCE::tr_involts () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 53 of file d_res.cc.
{return tr_outvolts();}
double anonymous_namespace{d_res.cc}::DEV_RESISTANCE::tr_involts_limited () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 55 of file d_res.cc.
{return tr_outvolts_limited();}
void anonymous_namespace{d_res.cc}::DEV_RESISTANCE::tr_iwant_matrix () [inline, private, virtual]
Implements ELEMENT.
Definition at line 48 of file d_res.cc.
{tr_iwant_matrix_passive();}
void anonymous_namespace{d_res.cc}::DEV_RESISTANCE::tr_load () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 51 of file d_res.cc.
{tr_load_passive();}
void anonymous_namespace{d_res.cc}::DEV_RESISTANCE::tr_unload () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 52 of file d_res.cc.
References untested.
{untested();tr_unload_passive();}
bool anonymous_namespace{d_res.cc}::DEV_RESISTANCE::use_obsolete_callback_parse () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 45 of file d_res.cc.
{return true;}
std::string anonymous_namespace{d_res.cc}::DEV_RESISTANCE::value_name () const [inline, private, virtual]
Implements CARD.
Definition at line 38 of file d_res.cc.
{return "r";}
The documentation for this class was generated from the following file:
savant/gnucap/src/d_res.cc