gnucap: savant/gnucap/src/e_storag.cc File Reference
savant/gnucap/src/e_storag.cc File Reference
#include "e_storag.h"
Functions
FPOLY1 differentiate (const FPOLY1 *q, const FPOLY1 *i, double *time, METHOD method)
Function Documentation
FPOLY1 differentiate (const FPOLY1 * q, const FPOLY1 * i, double * time, METHOD method)
Definition at line 127 of file e_storag.cc.
References OPT::_keep_time_steps, CKT_BASE::_sim, incomplete, mEULER, mGEAR, mTRAP, mTRAPEULER, mTRAPGEAR, and unreachable.
Referenced by anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::do_tr(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_tr(), anonymous_namespace{d_poly_cap.cc}::DEV_FPOLY_CAP::do_tr(), anonymous_namespace{d_cap.cc}::DEV_VCCAP::do_tr(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::do_tr_last(), and NIintegrate().
{
  if (CKT_BASE::_sim->analysis_is_static()) {
    assert(time[0] == 0.);
    return FPOLY1(q[0].x, 0., 0.);
  }else if (CKT_BASE::_sim->analysis_is_restore()) {
    /* leave it alone to restart from a previous solution */
    /* it goes this way to continue a transient analysis */
    assert(time[0] > 0);
    return i[0];
  }else{
    assert(CKT_BASE::_sim->analysis_is_tran_dynamic());
    if (time[1] == 0) {
      method = mEULER;  // Bogus current in previous step.  Force Euler.
    }else{
    }
    double dt = time[0] - time[1];
    assert(dt > 0.);
    switch (method) {
    case mTRAPGEAR:
      incomplete();
    case mGEAR:
      assert(OPT::_keep_time_steps >= 3);
      return FPOLY1(q[0].x,
                    (3./2.) * (q[0].f0 - q[1].f0) / dt
                    - (1./2.) * (q[1].f0 - q[2].f0) / (time[1] - time[2]),
                    q[0].f1 * (3./2.) / dt);
    case mTRAPEULER:
      incomplete();
    case mEULER:
      assert(OPT::_keep_time_steps >= 2);
      return FPOLY1(q[0].x,
                    (q[0].f0 - q[1].f0) / dt,
                    q[0].f1 / dt);
    case mTRAP:
      assert(OPT::_keep_time_steps >= 2);
      return FPOLY1(q[0].x,
                    2 * (q[0].f0 - q[1].f0) / dt - i[1].f0,
                    q[0].f1 * 2 / dt);
    }
    unreachable();
    return FPOLY1();
  }
  unreachable();
}