gnucap: COMMON_BUILT_IN_MOS Class Reference
COMMON_BUILT_IN_MOS Class Reference
#include <d_mos.h>
Public Member Functions
COMMON_BUILT_IN_MOS (const COMMON_BUILT_IN_MOS &p)
COMMON_BUILT_IN_MOS (int c=0)
~COMMON_BUILT_IN_MOS ()
bool operator== (const COMMON_COMPONENT &) const
COMMON_COMPONENT * clone () const
void set_param_by_index (int, std::string &, int)
bool param_is_printable (int) const
std::string param_name (int) const
std::string param_name (int, int) const
std::string param_value (int) const
int param_count () const
void precalc_first (const CARD_LIST *)
void expand (const COMPONENT *)
void precalc_last (const CARD_LIST *)
std::string name () const
const SDP_CARD * sdp () const
bool has_sdp () const
Static Public Member Functions
static int count ()
Public Attributes
PARAMETER< double > l_in
PARAMETER< double > w_in
PARAMETER< double > ad_in
PARAMETER< double > as_in
PARAMETER< double > pd
PARAMETER< double > ps
PARAMETER< double > nrd
PARAMETER< double > nrs
SDP_CARD * _sdp
COMMON_COMPONENT * _db
COMMON_COMPONENT * _sb
Static Private Attributes
static int _count = -1
Detailed Description
Definition at line 41 of file d_mos.h.
Constructor & Destructor Documentation
COMMON_BUILT_IN_MOS::COMMON_BUILT_IN_MOS (const COMMON_BUILT_IN_MOS & p) [explicit]
Definition at line 64 of file d_mos.cc.
References _count.
Referenced by clone().
  :COMMON_COMPONENT(p),
   l_in(p.l_in),
   w_in(p.w_in),
   ad_in(p.ad_in),
   as_in(p.as_in),
   pd(p.pd),
   ps(p.ps),
   nrd(p.nrd),
   nrs(p.nrs),
   _sdp(0),
   _db(0),
   _sb(0)
{
  ++_count;
}
COMMON_BUILT_IN_MOS::COMMON_BUILT_IN_MOS (int c = 0) [explicit]
Definition at line 47 of file d_mos.cc.
References _count.
  :COMMON_COMPONENT(c),
   l_in(OPT::defl),
   w_in(OPT::defw),
   ad_in(OPT::defad),
   as_in(OPT::defas),
   pd(0.0),
   ps(0.0),
   nrd(1.0),
   nrs(1.0),
   _sdp(0),
   _db(0),
   _sb(0)
{
  ++_count;
}
COMMON_BUILT_IN_MOS::~COMMON_BUILT_IN_MOS ()
Definition at line 81 of file d_mos.cc.
References _count, _db, _sb, _sdp, and COMMON_COMPONENT::detach_common().
{
  detach_common(&_db);
  detach_common(&_sb);
  --_count;
  delete _sdp;
}
Member Function Documentation
COMMON_COMPONENT* COMMON_BUILT_IN_MOS::clone () const [inline, virtual]
Implements COMMON_COMPONENT.
Definition at line 48 of file d_mos.h.
References COMMON_BUILT_IN_MOS().
{return new COMMON_BUILT_IN_MOS(*this);}
static int COMMON_BUILT_IN_MOS::count () [inline, static]
Definition at line 61 of file d_mos.h.
References _count.
{return _count;}
void COMMON_BUILT_IN_MOS::expand (const COMPONENT * d) [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 186 of file d_mos.cc.
References _db, _sb, _sdp, SDP_BUILT_IN_MOS_BASE::ad, COMMON_BUILT_IN_DIODE::area, SDP_BUILT_IN_MOS_BASE::as, COMMON_COMPONENT::attach(), COMMON_COMPONENT::attach_common(), COMMON_COMPONENT::attach_model(), MODEL_BUILT_IN_MOS_BASE::cbd, MODEL_BUILT_IN_MOS_BASE::cbs, COMMON_BUILT_IN_DIODE::cj_raw, COMMON_BUILT_IN_DIODE::cjsw_raw, anonymous_namespace{s_fo.cc}::db(), SDP_BUILT_IN_MOS_BASE::idsat, COMMON_BUILT_IN_DIODE::is_raw, SDP_BUILT_IN_MOS_BASE::issat, CARD::long_label(), COMMON_COMPONENT::model(), COMMON_COMPONENT::modelname(), NA(), MODEL_BUILT_IN_MOS_BASE::new_sdp(), COMMON_BUILT_IN_DIODE::off, pd, COMMON_BUILT_IN_DIODE::perim, prechecked_cast, ps, and COMMON_COMPONENT::set_modelname().
{
  COMMON_COMPONENT::expand(d);
  attach_model(d);
  COMMON_BUILT_IN_MOS* c = this;
  const MODEL_BUILT_IN_MOS_BASE* m = dynamic_cast<const MODEL_BUILT_IN_MOS_BASE*>(model());
  if (!m) {
    throw Exception_Model_Type_Mismatch(d->long_label(), modelname(), "mosfet");
  }else{
  }
  // size dependent
  //delete _sdp;
  _sdp = m->new_sdp(this);
  assert(_sdp);
  const SDP_BUILT_IN_MOS_BASE* s = prechecked_cast<const SDP_BUILT_IN_MOS_BASE*>(_sdp);
  assert(s);
  // subcircuit commons, recursive
  COMMON_BUILT_IN_DIODE* db = new COMMON_BUILT_IN_DIODE;
  db->area = double(s->ad);
  db->perim = double(c->pd);
  db->is_raw = double(s->idsat);
  db->cj_raw = double(m->cbd);
  db->cjsw_raw = NA;
  db->off = true;
  db->set_modelname(modelname());
  db->attach(model());
  attach_common(db, &_db);
  COMMON_BUILT_IN_DIODE* sb = new COMMON_BUILT_IN_DIODE;
  sb->area = double(s->as);
  sb->perim = double(c->ps);
  sb->is_raw = double(s->issat);
  sb->cj_raw = double(m->cbs);
  sb->cjsw_raw = NA;
  sb->off = true;
  sb->set_modelname(modelname());
  sb->attach(model());
  attach_common(sb, &_sb);
  assert(c == this);
}
bool COMMON_BUILT_IN_MOS::has_sdp () const [inline]
Definition at line 60 of file d_mos.h.
References _sdp, and untested.
{untested();return _sdp;}
std::string COMMON_BUILT_IN_MOS::name () const [inline, virtual]
Implements COMMON_COMPONENT.
Definition at line 58 of file d_mos.h.
References itested.
{itested();return "mosfet";}
bool COMMON_BUILT_IN_MOS::operator== (const COMMON_COMPONENT & x) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 89 of file d_mos.cc.
References _sdp, ad_in, as_in, l_in, nrd, nrs, anonymous_namespace{c_genrat.cc}::p, pd, ps, and w_in.
{
  const COMMON_BUILT_IN_MOS* p = dynamic_cast<const COMMON_BUILT_IN_MOS*>(&x);
  return (p
    && l_in == p->l_in
    && w_in == p->w_in
    && ad_in == p->ad_in
    && as_in == p->as_in
    && pd == p->pd
    && ps == p->ps
    && nrd == p->nrd
    && nrs == p->nrs
    && _sdp == p->_sdp
    && COMMON_COMPONENT::operator==(x));
}
int COMMON_BUILT_IN_MOS::param_count () const [inline, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 54 of file d_mos.h.
References COMMON_COMPONENT::param_count().
Referenced by param_is_printable(), param_name(), param_value(), and set_param_by_index().
{return (8 + COMMON_COMPONENT::param_count());}
bool COMMON_BUILT_IN_MOS::param_is_printable (int i) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 120 of file d_mos.cc.
References ad_in, as_in, has_hard_value(), nrd, nrs, param_count(), pd, and ps.
{
  switch (COMMON_BUILT_IN_MOS::param_count() - 1 - i) {
  case 0:  return (true);
  case 1:  return (true);
  case 2:  return (has_hard_value(ad_in));
  case 3:  return (has_hard_value(as_in));
  case 4:  return (has_hard_value(pd));
  case 5:  return (has_hard_value(ps));
  case 6:  return (has_hard_value(nrd));
  case 7:  return (has_hard_value(nrs));
  default: return COMMON_COMPONENT::param_is_printable(i);
  }
}
std::string COMMON_BUILT_IN_MOS::param_name (int i) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 135 of file d_mos.cc.
References param_count().
Referenced by param_name().
{
  switch (COMMON_BUILT_IN_MOS::param_count() - 1 - i) {
  case 0:  return "l";
  case 1:  return "w";
  case 2:  return "ad";
  case 3:  return "as";
  case 4:  return "pd";
  case 5:  return "ps";
  case 6:  return "nrd";
  case 7:  return "nrs";
  default: return COMMON_COMPONENT::param_name(i);
  }
}
std::string COMMON_BUILT_IN_MOS::param_name (int i, int j) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 150 of file d_mos.cc.
References param_count(), param_name(), and untested.
{
  if (j == 0) {
    return param_name(i);
  }else if (j == 1) {
    switch (COMMON_BUILT_IN_MOS::param_count() - 1 - i) {
    case 0:  return "";
    case 1:  return "";
    case 2:  return "";
    case 3:  return "";
    case 4:  return "";
    case 5:  return "";
    case 6:  return "";
    case 7:  return "";
    default: return "";
    }
  }else{untested();//281
    return COMMON_COMPONENT::param_name(i, j);
  }
}
std::string COMMON_BUILT_IN_MOS::param_value (int i) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 171 of file d_mos.cc.
References ad_in, as_in, l_in, nrd, nrs, param_count(), pd, ps, PARAMETER< T >::string(), and w_in.
{
  switch (COMMON_BUILT_IN_MOS::param_count() - 1 - i) {
  case 0:  return l_in.string();
  case 1:  return w_in.string();
  case 2:  return ad_in.string();
  case 3:  return as_in.string();
  case 4:  return pd.string();
  case 5:  return ps.string();
  case 6:  return nrd.string();
  case 7:  return nrs.string();
  default: return COMMON_COMPONENT::param_value(i);
  }
}
void COMMON_BUILT_IN_MOS::precalc_first (const CARD_LIST * par_scope) [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 229 of file d_mos.cc.
References ad_in, as_in, OPT::defad, OPT::defas, OPT::defl, OPT::defw, e_val(), l_in, nrd, nrs, pd, ps, and w_in.
{
  assert(par_scope);
  COMMON_COMPONENT::precalc_first(par_scope);
    e_val(&(this->l_in), OPT::defl, par_scope);
    e_val(&(this->w_in), OPT::defw, par_scope);
    e_val(&(this->ad_in), OPT::defad, par_scope);
    e_val(&(this->as_in), OPT::defas, par_scope);
    e_val(&(this->pd), 0.0, par_scope);
    e_val(&(this->ps), 0.0, par_scope);
    e_val(&(this->nrd), 1.0, par_scope);
    e_val(&(this->nrs), 1.0, par_scope);
}
void COMMON_BUILT_IN_MOS::precalc_last (const CARD_LIST * par_scope) [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 243 of file d_mos.cc.
References _db, _sb, _sdp, SDP_BUILT_IN_MOS_BASE::ad, ad_in, COMMON_BUILT_IN_DIODE::area, SDP_BUILT_IN_MOS_BASE::as, as_in, COMMON_COMPONENT::attach(), COMMON_COMPONENT::attach_common(), MODEL_BUILT_IN_MOS_BASE::cbd, MODEL_BUILT_IN_MOS_BASE::cbs, COMMON_BUILT_IN_DIODE::cj_raw, COMMON_BUILT_IN_DIODE::cjsw_raw, anonymous_namespace{s_fo.cc}::db(), OPT::defad, OPT::defas, OPT::defl, OPT::defw, e_val(), SDP_BUILT_IN_MOS_BASE::idsat, COMMON_BUILT_IN_DIODE::is_raw, SDP_BUILT_IN_MOS_BASE::issat, l_in, COMMON_COMPONENT::model(), COMMON_COMPONENT::modelname(), NA(), MODEL_BUILT_IN_MOS_BASE::new_sdp(), nrd, nrs, COMMON_BUILT_IN_DIODE::off, pd, COMMON_BUILT_IN_DIODE::perim, prechecked_cast, ps, COMMON_COMPONENT::set_modelname(), and w_in.
{
  assert(par_scope);
  COMMON_COMPONENT::precalc_last(par_scope);
  COMMON_BUILT_IN_MOS* c = this;
  const MODEL_BUILT_IN_MOS_BASE* m = prechecked_cast<const MODEL_BUILT_IN_MOS_BASE*>(model());
    // final adjust: code_pre
    // final adjust: override
    // final adjust: raw
    e_val(&(this->l_in), OPT::defl, par_scope);
    e_val(&(this->w_in), OPT::defw, par_scope);
    e_val(&(this->ad_in), OPT::defad, par_scope);
    e_val(&(this->as_in), OPT::defas, par_scope);
    e_val(&(this->pd), 0.0, par_scope);
    e_val(&(this->ps), 0.0, par_scope);
    e_val(&(this->nrd), 1.0, par_scope);
    e_val(&(this->nrs), 1.0, par_scope);
    // final adjust: mid
    // final adjust: calculated
    // final adjust: post
    // final adjust: done
  // size dependent
  //delete _sdp;
  _sdp = m->new_sdp(this);
  assert(_sdp);
  const SDP_BUILT_IN_MOS_BASE* s = prechecked_cast<const SDP_BUILT_IN_MOS_BASE*>(_sdp);
  assert(s);
  // subcircuit commons, recursive
  COMMON_BUILT_IN_DIODE* db = new COMMON_BUILT_IN_DIODE;
  db->area = double(s->ad);
  db->perim = double(c->pd);
  db->is_raw = double(s->idsat);
  db->cj_raw = double(m->cbd);
  db->cjsw_raw = NA;
  db->off = true;
  db->set_modelname(modelname());
  db->attach(model());
  attach_common(db, &_db);
  COMMON_BUILT_IN_DIODE* sb = new COMMON_BUILT_IN_DIODE;
  sb->area = double(s->as);
  sb->perim = double(c->ps);
  sb->is_raw = double(s->issat);
  sb->cj_raw = double(m->cbs);
  sb->cjsw_raw = NA;
  sb->off = true;
  sb->set_modelname(modelname());
  sb->attach(model());
  attach_common(sb, &_sb);
  assert(c == this);
}
const SDP_CARD* COMMON_BUILT_IN_MOS::sdp () const [inline]
Definition at line 59 of file d_mos.h.
References _sdp.
Referenced by DEV_BUILT_IN_MOS::expand(), TDP_BUILT_IN_MOS1::TDP_BUILT_IN_MOS1(), TDP_BUILT_IN_MOS2::TDP_BUILT_IN_MOS2(), TDP_BUILT_IN_MOS3::TDP_BUILT_IN_MOS3(), TDP_BUILT_IN_MOS6::TDP_BUILT_IN_MOS6(), TDP_BUILT_IN_MOS7::TDP_BUILT_IN_MOS7(), TDP_BUILT_IN_MOS8::TDP_BUILT_IN_MOS8(), MODEL_BUILT_IN_MOS6::tr_eval(), MODEL_BUILT_IN_MOS1::tr_eval(), MODEL_BUILT_IN_MOS3::tr_eval(), MODEL_BUILT_IN_MOS2::tr_eval(), EVAL_BUILT_IN_MOS_Cgb::tr_eval(), MODEL_BUILT_IN_MOS4::tr_eval(), EVAL_BUILT_IN_MOS_Cgd::tr_eval(), EVAL_BUILT_IN_MOS_Cgs::tr_eval(), MODEL_BUILT_IN_MOS5::tr_eval(), MODEL_BUILT_IN_MOS7::tr_eval(), MODEL_BUILT_IN_MOS8::tr_eval(), and DEV_BUILT_IN_MOS::tr_probe_num().
{return _sdp;}
void COMMON_BUILT_IN_MOS::set_param_by_index (int I, std::string & Value, int Offset) [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 105 of file d_mos.cc.
References ad_in, as_in, l_in, nrd, nrs, param_count(), pd, ps, and w_in.
{
  switch (COMMON_BUILT_IN_MOS::param_count() - 1 - I) {
  case 0:  l_in = Value; break;
  case 1:  w_in = Value; break;
  case 2:  ad_in = Value; break;
  case 3:  as_in = Value; break;
  case 4:  pd = Value; break;
  case 5:  ps = Value; break;
  case 6:  nrd = Value; break;
  case 7:  nrs = Value; break;
  default: COMMON_COMPONENT::set_param_by_index(I, Value, Offset);
  }
}
Member Data Documentation
int COMMON_BUILT_IN_MOS::_count = -1 [static, private]
Definition at line 63 of file d_mos.h.
Referenced by COMMON_BUILT_IN_MOS(), count(), and ~COMMON_BUILT_IN_MOS().
COMMON_COMPONENT* COMMON_BUILT_IN_MOS::_db
Definition at line 76 of file d_mos.h.
Referenced by expand(), DEV_BUILT_IN_MOS::expand(), precalc_last(), and ~COMMON_BUILT_IN_MOS().
COMMON_COMPONENT* COMMON_BUILT_IN_MOS::_sb
Definition at line 77 of file d_mos.h.
Referenced by expand(), DEV_BUILT_IN_MOS::expand(), precalc_last(), and ~COMMON_BUILT_IN_MOS().
SDP_CARD* COMMON_BUILT_IN_MOS::_sdp
Definition at line 74 of file d_mos.h.
Referenced by expand(), has_sdp(), operator==(), precalc_last(), sdp(), and ~COMMON_BUILT_IN_MOS().
PARAMETER<double> COMMON_BUILT_IN_MOS::ad_in
Definition at line 67 of file d_mos.h.
Referenced by SDP_BUILT_IN_MOS_BASE::init(), operator==(), param_is_printable(), param_value(), precalc_first(), precalc_last(), and set_param_by_index().
PARAMETER<double> COMMON_BUILT_IN_MOS::as_in
Definition at line 68 of file d_mos.h.
Referenced by SDP_BUILT_IN_MOS_BASE::init(), operator==(), param_is_printable(), param_value(), precalc_first(), precalc_last(), and set_param_by_index().
PARAMETER<double> COMMON_BUILT_IN_MOS::l_in
Definition at line 65 of file d_mos.h.
Referenced by SDP_BUILT_IN_MOS_BASE::init(), SDP_BUILT_IN_MOS7::init(), SDP_BUILT_IN_MOS8::init(), MODEL_BUILT_IN_MOS_BASE::is_valid(), operator==(), param_value(), precalc_first(), precalc_last(), and set_param_by_index().
PARAMETER<double> COMMON_BUILT_IN_MOS::nrd
Definition at line 71 of file d_mos.h.
Referenced by SDP_BUILT_IN_MOS_BASE::init(), operator==(), param_is_printable(), param_value(), precalc_first(), precalc_last(), and set_param_by_index().
PARAMETER<double> COMMON_BUILT_IN_MOS::nrs
Definition at line 72 of file d_mos.h.
Referenced by SDP_BUILT_IN_MOS_BASE::init(), operator==(), param_is_printable(), param_value(), precalc_first(), precalc_last(), and set_param_by_index().
PARAMETER<double> COMMON_BUILT_IN_MOS::pd
Definition at line 69 of file d_mos.h.
Referenced by expand(), operator==(), param_is_printable(), param_value(), precalc_first(), precalc_last(), and set_param_by_index().
PARAMETER<double> COMMON_BUILT_IN_MOS::ps
Definition at line 70 of file d_mos.h.
Referenced by expand(), operator==(), param_is_printable(), param_value(), precalc_first(), precalc_last(), and set_param_by_index().
PARAMETER<double> COMMON_BUILT_IN_MOS::w_in
Definition at line 66 of file d_mos.h.
Referenced by SDP_BUILT_IN_MOS_BASE::init(), SDP_BUILT_IN_MOS7::init(), SDP_BUILT_IN_MOS8::init(), MODEL_BUILT_IN_MOS_BASE::is_valid(), operator==(), param_value(), precalc_first(), precalc_last(), and set_param_by_index().
The documentation for this class was generated from the following files:
savant/gnucap/src/d_mos.h
savant/gnucap/src/d_mos.cc