gnucap: anonymous_namespace{lang_spice.cc}::CMD_RUN Class Reference
anonymous_namespace{lang_spice.cc}::CMD_RUN Class Reference
Public Member Functions
void do_it (CS &cmd, CARD_LIST *Scope)
Detailed Description
Definition at line 983 of file lang_spice.cc.
Member Function Documentation
void anonymous_namespace{lang_spice.cc}::CMD_RUN::do_it (CS & cmd, CARD_LIST * Scope) [inline, virtual]
Implements CMD.
Definition at line 985 of file lang_spice.cc.
References anonymous_namespace{lang_spice.cc}::getmerge(), CS::match1(), rSCRIPT, CS::skip(), anonymous_namespace{lang_spice.cc}::SKIP_HEADER, CS::skipbl(), and untested.
  {
    while (cmd.match1('<')) {untested();
      command("clear", Scope);
      cmd.skip();
      cmd.skipbl();
    }
    SET_RUN_MODE xx(rSCRIPT);
    getmerge(cmd, SKIP_HEADER, Scope);
  }
The documentation for this class was generated from the following file:
savant/gnucap/src/lang_spice.cc