gnucap: anonymous_namespace{lang_gschem.cc} Namespace Reference
anonymous_namespace{lang_gschem.cc} Namespace Reference
Classes
class LANG_GSCHEM
class CMD_GSCHEM
class CMD_C
Functions
DISPATCHER< LANGUAGE >::INSTALL d & language_dispatcher (),&lang_gschem
static void parse_type (CS &cmd, CARD *x)
static void parse_label (CS &cmd, CARD *x)
static void parse_net (CS &cmd, CARD *x)
static void parse_component (CS &cmd, CARD *x)
Variables
anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM lang_gschem
anonymous_namespace{lang_gschem.cc}::CMD_GSCHEM p8
DISPATCHER< CMD >::INSTALL d8 & command_dispatcher
anonymous_namespace{lang_gschem.cc}::CMD_C p2
Function Documentation
DISPATCHER<LANGUAGE>::INSTALL d& anonymous_namespace{lang_gschem.cc}::language_dispatcher ()
static void anonymous_namespace{lang_gschem.cc}::parse_component (CS & cmd, CARD * x) [static]
Definition at line 190 of file lang_gschem.cc.
References CS::_STDIN, CS::ctos(), anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::find_type_in_string(), CS::get_line(), lang_gschem, CARD::set_dev_type(), and CARD::set_param_by_name().
{
    assert(x);
    std::string component_x, component_y, mirror, angle, dump,basename;
    std::string type=lang_gschem.find_type_in_string(cmd);
    cmd>>type;
    std::vector<std::string> paramname;
    std::vector<std::string> paramvalue;
    cmd>>component_x>>" ">>component_y>>" ">>dump>>" ">>angle>>" ">>mirror>>" ">>basename;
    //To get port names and values from symbol?
    //Then set params below
    x->set_param_by_name("x",component_x);
    x->set_param_by_name("y",component_y);
    x->set_param_by_name("angle",angle);
    x->set_param_by_name("mirror",mirror);
    x->set_param_by_name("basename",basename);
    CS new_cmd(CS::_STDIN);
    new_cmd.get_line("gnucap-gschem- "+basename+">");
    new_cmd>>"{";
    for (;;) {
        new_cmd.get_line("gnucap-gschem- "+basename+">");
        if (new_cmd >> "}") {
            break;
        }else{
            if(new_cmd>>"T"){
                new_cmd>>dump;
            }
            else {
                std::string _paramname=new_cmd.ctos("=","",""),_paramvalue;
                new_cmd>>"=">>_paramvalue;
                paramname.push_back (_paramname);
                paramvalue.push_back(_paramvalue);
                if(_paramname=="device"){
                    x->set_dev_type(_paramvalue);
                }else{
                    x->set_param_by_name(_paramname,_paramvalue);
                }
            }
        }
    }
}
static void anonymous_namespace{lang_gschem.cc}::parse_label (CS & cmd, CARD * x) [static]
Definition at line 92 of file lang_gschem.cc.
References CKT_BASE::set_label().
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_instance(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_instance(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_instance(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_module(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_module(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_module(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_paramset(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_paramset(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_paramset().
{
  assert(x);
  std::string my_name;
  cmd >> my_name;
  x->set_label(my_name);
}
static void anonymous_namespace{lang_gschem.cc}::parse_net (CS & cmd, CARD * x) [static]
Definition at line 156 of file lang_gschem.cc.
References CS::cursor(), anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::find_type_in_string(), lang_gschem, CARD::long_label(), CARD::set_param_by_name(), and untested.
Referenced by anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_instance().
{
    assert(x);
    assert(lang_gschem.find_type_in_string(cmd)=="net");
    cmd>>"N";     //Got N
    std::string x0,y0,x1,y1,color;
    unsigned here=cmd.cursor();
    std::string paramnames[5]={"x0","x1","y0","y1","color"};
    std::string paramvalue[5];
    int i=0;
    bool gotthenet=true;
    while (i<5) {
        if (cmd.is_alnum()){
            cmd>>" ">>paramvalue[i];
            try{
                x->set_param_by_name(paramnames[i],paramvalue[i]);
            }catch (Exception_No_Match&) {untested();
                cmd.warn(bDANGER, here, x->long_label() + ": bad parameter "+ paramvalue[i] + "ignored");
            }
        }else{
            gotthenet=false;
            cmd.warn(bDANGER, here, x->long_label() +": Not correct format for net");
            break;
        }
        ++i;
    }
}
static void anonymous_namespace{lang_gschem.cc}::parse_type (CS & cmd, CARD * x) [static]
Definition at line 84 of file lang_gschem.cc.
References anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::find_type_in_string(), lang_gschem, and CARD::set_dev_type().
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_instance(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_instance(), anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_instance(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_instance(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_paramset(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_paramset(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_paramset().
{
  assert(x);
  std::string new_type;
  new_type=lang_gschem.find_type_in_string(cmd);
  x->set_dev_type(new_type);
}
Variable Documentation
DISPATCHER< CMD >::INSTALL d2 & anonymous_namespace{lang_gschem.cc}::command_dispatcher
Definition at line 326 of file lang_gschem.cc.
anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM anonymous_namespace{lang_gschem.cc}::lang_gschem
Referenced by anonymous_namespace{lang_gschem.cc}::CMD_C::do_it(), parse_component(), parse_net(), and parse_type().
anonymous_namespace{lang_gschem.cc}::CMD_C anonymous_namespace{lang_gschem.cc}::p2
anonymous_namespace{lang_gschem.cc}::CMD_GSCHEM anonymous_namespace{lang_gschem.cc}::p8