gnucap: anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE Class Reference
anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE Class Reference
Public Member Functions
std::string name () const
bool case_insensitive () const
UNITS units () const
std::string arg_front () const
std::string arg_mid () const
std::string arg_back () const
void parse_top_item (CS &, CARD_LIST *)
DEV_COMMENT * parse_comment (CS &, DEV_COMMENT *)
DEV_DOT * parse_command (CS &, DEV_DOT *)
MODEL_CARD * parse_paramset (CS &, MODEL_CARD *)
MODEL_SUBCKT * parse_module (CS &, MODEL_SUBCKT *)
COMPONENT * parse_instance (CS &, COMPONENT *)
std::string find_type_in_string (CS &)
Private Member Functions
void print_paramset (OMSTREAM &, const MODEL_CARD *)
void print_module (OMSTREAM &, const MODEL_SUBCKT *)
void print_instance (OMSTREAM &, const COMPONENT *)
void print_comment (OMSTREAM &, const DEV_COMMENT *)
void print_command (OMSTREAM &o, const DEV_DOT *c)
void print_args (OMSTREAM &, const CARD *)
Detailed Description
Definition at line 31 of file lang_spectre.cc.
Member Function Documentation
std::string anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::arg_back () const [inline, virtual]
Implements LANGUAGE.
Definition at line 40 of file lang_spectre.cc.
{return "";}
std::string anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::arg_front () const [inline, virtual]
Implements LANGUAGE.
Definition at line 38 of file lang_spectre.cc.
{return " ";}
std::string anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::arg_mid () const [inline, virtual]
Implements LANGUAGE.
Definition at line 39 of file lang_spectre.cc.
{return "=";}
bool anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::case_insensitive () const [inline, virtual]
Implements LANGUAGE.
Definition at line 34 of file lang_spectre.cc.
{return false;}
std::string anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::find_type_in_string (CS & cmd) [virtual]
Implements LANGUAGE.
Definition at line 220 of file lang_spectre.cc.
References CS::cursor(), itested, CS::match1(), CS::reset(), CS::scan(), CS::skiparg(), CS::skipbl(), and CS::trimmed_last_match().
{
  // known to be not always correct
  cmd.reset().skipbl();
  unsigned here = 0;
  std::string type;
  if ((cmd >> "*|//")) {itested();
    assert(here == 0);
    type = "dev_comment";
  }else if ((cmd >> "model |simulator |parameters |subckt ")) {
    // type is first, it's a control statement
    type = cmd.trimmed_last_match();
  }else if (cmd.reset().skiparg().match1("(") && cmd.scan(")")) {
    // node list surrounded by parens
    // type follows
    here = cmd.cursor();
    cmd.reset(here);
    cmd >> type;
  }else if (cmd.reset().scan("=")) {itested();
    // back up two, by starting over
    cmd.reset().skiparg();
    unsigned here1 = cmd.cursor();
    cmd.skiparg();
    unsigned here2 = cmd.cursor();
    cmd.skiparg();
    unsigned here3 = cmd.cursor();
    while (here2 != here3 && !cmd.match1('=')) {
      cmd.skiparg();
      here1 = here2;
      here2 = here3;
      here3 = cmd.cursor();
    }
    here = here1;
    cmd.reset(here);
    cmd >> type;
  }else{
    // type is second
    cmd.reset().skiparg();
    here = cmd.cursor();
    cmd.reset(here);
    cmd >> type;
  }
  cmd.reset(here);
  return type;
}
std::string anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::name () const [inline, virtual]
Implements LANGUAGE.
Definition at line 33 of file lang_spectre.cc.
{return "spectre";}
DEV_DOT * anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_command (CS & cmd, DEV_DOT * x) [virtual]
Implements LANGUAGE.
Definition at line 143 of file lang_spectre.cc.
References CS::_STRING, CARD_LIST::card_list, CMD::cmdproc(), CS::cursor(), CS::fullstring(), CARD::owner(), CS::reset(), DEV_DOT::set(), CS::skipbl(), CARD::subckt(), and CS::tail().
{
  assert(x);
  x->set(cmd.fullstring());
  CARD_LIST* scope = (x->owner()) ? x->owner()->subckt() : &CARD_LIST::card_list;
  cmd.reset().skipbl();
  if ((cmd >> "model |simulator |parameters |subckt ")) {
    cmd.reset();
    CMD::cmdproc(cmd, scope);
  }else{
    std::string label;
    cmd >> label;
    if (label != "-") {
      unsigned here = cmd.cursor();
      std::string command;
      cmd >> command;
      cmd.reset(here);
      std::string file_name = label + '.' + command;
      std::string s = cmd.tail() + " > " + file_name;
      CS augmented_cmd(CS::_STRING, s);
      CMD::cmdproc(augmented_cmd, scope);
    }else{
      CMD::cmdproc(cmd, scope);
    }
  }
  delete x;
  return NULL;
}
DEV_COMMENT * anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_comment (CS & cmd, DEV_COMMENT * x) [virtual]
Implements LANGUAGE.
Definition at line 136 of file lang_spectre.cc.
References CS::fullstring(), and DEV_COMMENT::set().
{
  assert(x);
  x->set(cmd.fullstring());
  return x;
}
COMPONENT * anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_instance (CS & cmd, COMPONENT * x) [virtual]
Implements LANGUAGE.
Definition at line 209 of file lang_spectre.cc.
References CS::check(), anonymous_namespace{lang_spectre.cc}::parse_args(), anonymous_namespace{lang_gschem.cc}::parse_label(), anonymous_namespace{lang_spectre.cc}::parse_ports(), anonymous_namespace{lang_gschem.cc}::parse_type(), and CS::reset().
{
  cmd.reset();
  parse_label(cmd, x);
  parse_ports(cmd, x);
  parse_type(cmd, x);
  parse_args(cmd, x);
  cmd.check(bWARNING, "what's this?");
  return x;
}
MODEL_SUBCKT * anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_module (CS & cmd, MODEL_SUBCKT * x) [virtual]
Implements LANGUAGE.
Definition at line 186 of file lang_spectre.cc.
References CS::get_line(), anonymous_namespace{lang_gschem.cc}::parse_label(), anonymous_namespace{lang_spectre.cc}::parse_ports(), CS::reset(), CS::skipbl(), and CARD::subckt().
Referenced by anonymous_namespace{lang_spectre.cc}::CMD_SUBCKT::do_it().
{
  assert(x);
  // header
  cmd.reset().skipbl();
  cmd >> "subckt ";
  parse_label(cmd, x);
  parse_ports(cmd, x);
  // body
  for (;;) {
    cmd.get_line("spectre-subckt>");
    if (cmd >> "ends ") {
      break;
    }else{
      new__instance(cmd, x, x->subckt());
    }
  }
  return x;
}
MODEL_CARD * anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_paramset (CS & cmd, MODEL_CARD * x) [virtual]
Implements LANGUAGE.
Definition at line 174 of file lang_spectre.cc.
References CS::check(), anonymous_namespace{lang_spectre.cc}::parse_args(), anonymous_namespace{lang_gschem.cc}::parse_label(), anonymous_namespace{lang_gschem.cc}::parse_type(), CS::reset(), and CS::skipbl().
Referenced by anonymous_namespace{lang_spectre.cc}::CMD_MODEL::do_it().
{
  assert(x);
  cmd.reset().skipbl();
  cmd >> "model ";
  parse_label(cmd, x);
  parse_type(cmd, x);
  parse_args(cmd, x);
  cmd.check(bWARNING, "what's this?");
  return x;
}
void anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_top_item (CS & cmd, CARD_LIST * Scope) [virtual]
Reimplemented from LANGUAGE.
Definition at line 267 of file lang_spectre.cc.
References CS::get_line().
{
  cmd.get_line("gnucap-spectre>");
  new__instance(cmd, NULL, Scope);
}
void anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_args (OMSTREAM & o, const CARD * x) [private]
Definition at line 274 of file lang_spectre.cc.
References CARD::param_count(), CARD::param_is_printable(), CARD::param_name(), CARD::param_value(), CARD::print_args_obsolete_callback(), and CARD::use_obsolete_callback_print().
{
  assert(x);
  o << ' ';
  if (x->use_obsolete_callback_print()) {
    x->print_args_obsolete_callback(o, this);  //BUG//callback//
  }else{
    for (int ii = x->param_count() - 1;  ii >= 0;  --ii) {
      if (x->param_is_printable(ii)) {
        std::string arg = " " + x->param_name(ii) + "=" + x->param_value(ii);
        o << arg;
      }else{
      }
    }
  }
}
void anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_command (OMSTREAM & o, const DEV_DOT * c) [private, virtual]
Implements LANGUAGE.
Definition at line 361 of file lang_spectre.cc.
References DEV_DOT::s().
{
  assert(x);
  o << x->s() << '\n';
}
void anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_comment (OMSTREAM & o, const DEV_COMMENT * x) [private, virtual]
Implements LANGUAGE.
Definition at line 355 of file lang_spectre.cc.
References DEV_COMMENT::comment().
{
  assert(x);
  o << x->comment() << '\n';
}
void anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_instance (OMSTREAM & o, const COMPONENT * x) [private, virtual]
Implements LANGUAGE.
Definition at line 346 of file lang_spectre.cc.
References anonymous_namespace{lang_spectre.cc}::print_label(), anonymous_namespace{lang_spectre.cc}::print_ports(), and anonymous_namespace{lang_spectre.cc}::print_type().
{
  print_label(o, x);
  print_ports(o, x);
  print_type(o, x);
  print_args(o, x);
  o << "\n";
}
void anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_module (OMSTREAM & o, const MODEL_SUBCKT * x) [private, virtual]
Implements LANGUAGE.
Definition at line 329 of file lang_spectre.cc.
References CARD_LIST::begin(), CARD_LIST::end(), anonymous_namespace{lang_spectre.cc}::print_ports(), CKT_BASE::short_label(), and CARD::subckt().
{
  assert(x);
  assert(x->subckt());
  o << "subckt " <<  x->short_label();
  print_ports(o, x);
  o << "\n";
  for (CARD_LIST::const_iterator
         ci = x->subckt()->begin(); ci != x->subckt()->end(); ++ci) {
    print_item(o, *ci);
  }
  o << "ends " << x->short_label() << "\n\n";
}
void anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_paramset (OMSTREAM & o, const MODEL_CARD * x) [private, virtual]
Implements LANGUAGE.
Definition at line 321 of file lang_spectre.cc.
References CARD::dev_type(), and CKT_BASE::short_label().
{
  assert(x);
  o << "model " << x->short_label() << ' ' << x->dev_type() << ' ';
  print_args(o, x);
  o << "\n\n";
}
UNITS anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::units () const [inline, virtual]
Implements LANGUAGE.
Definition at line 35 of file lang_spectre.cc.
References uSI.
{return uSI;}
The documentation for this class was generated from the following file:
savant/gnucap/src/lang_spectre.cc