gnucap: anonymous_namespace{d_cccs.cc}::DEV_CCCS Class Reference
anonymous_namespace{d_cccs.cc}::DEV_CCCS Class Reference
Public Member Functions
DEV_CCCS ()
Private Member Functions
DEV_CCCS (const DEV_CCCS &p)
char id_letter () const
std::string value_name () const
std::string dev_type () const
bool use_obsolete_callback_parse () const
CARD * clone () const
void precalc_last ()
void tr_iwant_matrix ()
void tr_begin ()
bool do_tr ()
bool do_tr_last ()
void tr_load ()
void ac_iwant_matrix ()
void ac_begin ()
void do_ac ()
void ac_load ()
std::string port_name (int i) const
std::string current_port_name (int i) const
Detailed Description
Definition at line 31 of file d_cccs.cc.
Constructor & Destructor Documentation
anonymous_namespace{d_cccs.cc}::DEV_CCCS::DEV_CCCS (const DEV_CCCS & p) [inline, explicit, private]
Definition at line 33 of file d_cccs.cc.
:CCSRC_BASE(p) {}
anonymous_namespace{d_cccs.cc}::DEV_CCCS::DEV_CCCS () [inline, explicit]
Definition at line 35 of file d_cccs.cc.
:CCSRC_BASE() {}
Member Function Documentation
void anonymous_namespace{d_cccs.cc}::DEV_CCCS::ac_begin () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 49 of file d_cccs.cc.
{_ev = _y[0].f1;}
void anonymous_namespace{d_cccs.cc}::DEV_CCCS::ac_iwant_matrix () [inline, private, virtual]
Implements ELEMENT.
Definition at line 48 of file d_cccs.cc.
{ac_iwant_matrix_active();}
void anonymous_namespace{d_cccs.cc}::DEV_CCCS::ac_load () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 51 of file d_cccs.cc.
{ac_load_active();}
CARD* anonymous_namespace{d_cccs.cc}::DEV_CCCS::clone () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 41 of file d_cccs.cc.
{return new DEV_CCCS(*this);}
std::string anonymous_namespace{d_cccs.cc}::DEV_CCCS::current_port_name (int i) const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 59 of file d_cccs.cc.
References untested.
                                          {untested();
    assert(i >= 0);
    assert(i < 1);
    static std::string names[] = {"in"};
    return names[i];
  }
std::string anonymous_namespace{d_cccs.cc}::DEV_CCCS::dev_type () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 39 of file d_cccs.cc.
{return "cccs";}
void anonymous_namespace{d_cccs.cc}::DEV_CCCS::do_ac () [private, virtual]
Reimplemented from CARD.
Definition at line 113 of file d_cccs.cc.
References CARD::do_ac(), unreachable, and untested.
{
  assert(_input);
  if (!_input->evaluated()) {   /* patch for forward reference */
    ELEMENT* input = const_cast<ELEMENT*>(_input);
    input->do_ac();             /* make sure sense elt is evaluated first */
  }else{
  }
  if (using_ac_eval()) {
    ac_eval();
  }else{
    assert(_ev == _y[0].f1);
    assert(has_tr_eval() || _ev == double(value()));
  }
  if (_input->is_source()) {    /* if the sense elt is a fixed source.. */
    _acg = _ev * _input->_acg;  /* then part of this one can be modeled */
    ac_load_source();           /* as a fixed source. ...               */
    _acg = _ev * _input->_loss0;/* so load it in 2 pieces               */
  }else if (_input->has_inode()) {untested();
    _acg = _ev;
  }else if (_input->has_iv_probe()) {
    _acg = _ev * _input->_acg;
  }else{unreachable();
  }
}
bool anonymous_namespace{d_cccs.cc}::DEV_CCCS::do_tr () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 45 of file d_cccs.cc.
{_sim->_late_evalq.push_back(this); return true;}
bool anonymous_namespace{d_cccs.cc}::DEV_CCCS::do_tr_last () [private, virtual]
Reimplemented from CARD.
Definition at line 86 of file d_cccs.cc.
References converged, LINEAR, unreachable, and untested.
{
  assert(_input);
  if (using_tr_eval()) {
    _m0.x = tr_involts_limited();
    _y[0].x = tr_input_limited();
    tr_eval();
    assert(_y[0].f0 != LINEAR);
    _m0 = CPOLY1(_y[0]);
  }else{
    assert(_y[0].f0 == LINEAR);
    assert(_y[0].f1 == value());
    _m0.c0 = 0.;
    assert(converged());
  }
  if (_input->has_inode()) {untested();
    // nothing
  }else if (_input->has_iv_probe()) {
    _m0.c0 += _y[0].f1 * _input->_m0.c0;
    _m0.c1  = _y[0].f1 * (_input->_loss0 + _input->_m0.c1);
  }else{unreachable();
  }
  store_values();
  q_load();
  return converged();
}
char anonymous_namespace{d_cccs.cc}::DEV_CCCS::id_letter () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 37 of file d_cccs.cc.
{return 'F';}
std::string anonymous_namespace{d_cccs.cc}::DEV_CCCS::port_name (int i) const [inline, private, virtual]
Implements COMPONENT.
Definition at line 53 of file d_cccs.cc.
References untested.
                                  {untested();
    assert(i >= 0);
    assert(i < 2);
    static std::string names[] = {"sink", "src"};
    return names[i];
  }
void anonymous_namespace{d_cccs.cc}::DEV_CCCS::precalc_last () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 68 of file d_cccs.cc.
References ELEMENT::precalc_last().
{
  CCSRC_BASE::precalc_last();
  set_converged();
  assert(!is_constant()); /* because of incomplete analysis */
}
void anonymous_namespace{d_cccs.cc}::DEV_CCCS::tr_begin () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 75 of file d_cccs.cc.
References ELEMENT::tr_begin().
{
  CCSRC_BASE::tr_begin();
  _m0.x  = _y[0].x;
  _m0.c1 = _y[0].f1;
  _m0.c0 = 0.;
  _m1 = _m0;
  assert(_loss0 == 0.);
  assert(_loss1 == 0.);
}
void anonymous_namespace{d_cccs.cc}::DEV_CCCS::tr_iwant_matrix () [inline, private, virtual]
Implements ELEMENT.
Definition at line 43 of file d_cccs.cc.
{tr_iwant_matrix_active();}
void anonymous_namespace{d_cccs.cc}::DEV_CCCS::tr_load () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 47 of file d_cccs.cc.
{tr_load_active();}
bool anonymous_namespace{d_cccs.cc}::DEV_CCCS::use_obsolete_callback_parse () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 40 of file d_cccs.cc.
{return true;}
std::string anonymous_namespace{d_cccs.cc}::DEV_CCCS::value_name () const [inline, private, virtual]
Implements CARD.
Definition at line 38 of file d_cccs.cc.
{return "gain";}
The documentation for this class was generated from the following file:
savant/gnucap/src/d_cccs.cc