gnucap: anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR Class Reference
anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR Class Reference
Public Member Functions
EVAL_BM_GENERATOR (int c=0)
~EVAL_BM_GENERATOR ()
Private Member Functions
EVAL_BM_GENERATOR (const EVAL_BM_GENERATOR &p)
bool operator== (const COMMON_COMPONENT &) const
COMMON_COMPONENT * clone () const
void print_common_obsolete_callback (OMSTREAM &, LANGUAGE *) const
void tr_eval (ELEMENT *) const
void ac_eval (ELEMENT *) const
std::string name () const
bool ac_too () const
bool parse_numlist (CS &)
Detailed Description
Definition at line 31 of file bm_generator.cc.
Constructor & Destructor Documentation
anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR::EVAL_BM_GENERATOR (const EVAL_BM_GENERATOR & p) [explicit, private]
Definition at line 54 of file bm_generator.cc.
  :EVAL_BM_ACTION_BASE(p)
{
}
anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR::EVAL_BM_GENERATOR (int c = 0) [explicit]
Definition at line 49 of file bm_generator.cc.
  :EVAL_BM_ACTION_BASE(c)
{
}
anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR::~EVAL_BM_GENERATOR () [inline]
Definition at line 36 of file bm_generator.cc.
{}
Member Function Documentation
void anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR::ac_eval (ELEMENT * d) const [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 83 of file bm_generator.cc.
References ELEMENT::_ev, and EVAL_BM_ACTION_BASE::ac_final_adjust_with_temp().
{
  d->_ev = 1;
  ac_final_adjust_with_temp(&(d->_ev));
}
bool anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR::ac_too () const [inline, private, virtual]
Implements EVAL_BM_ACTION_BASE.
Definition at line 44 of file bm_generator.cc.
{return true;}
COMMON_COMPONENT* anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR::clone () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 39 of file bm_generator.cc.
{return new EVAL_BM_GENERATOR(*this);}
std::string anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR::name () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 43 of file bm_generator.cc.
Referenced by print_common_obsolete_callback().
{return "generator";}
bool anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR::operator== (const COMMON_COMPONENT & x) const [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 59 of file bm_generator.cc.
References incomplete, anonymous_namespace{c_genrat.cc}::p, and untested.
{
  const EVAL_BM_GENERATOR* p = dynamic_cast<const EVAL_BM_GENERATOR*>(&x);
  bool rv = p
    && EVAL_BM_ACTION_BASE::operator==(x);
  if (rv) {
    incomplete();
    untested();
  }
  return rv;
}
bool anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR::parse_numlist (CS & cmd) [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 89 of file bm_generator.cc.
References EVAL_BM_ACTION_BASE::_scale, CS::cursor(), CS::gotit(), and NOT_VALID.
{
  unsigned here = cmd.cursor();
  PARAMETER<double> new_value(NOT_VALID);
  cmd >> new_value;
  if (cmd.gotit(here)) {
    _scale = new_value;
    return true;
  }else{
    return false;
  }
}
void anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR::print_common_obsolete_callback (OMSTREAM & o, LANGUAGE * lang) const [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 71 of file bm_generator.cc.
References name().
{
  assert(lang);
  o << name();
  EVAL_BM_ACTION_BASE::print_common_obsolete_callback(o, lang);
}
void anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR::tr_eval (ELEMENT * d) const [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 78 of file bm_generator.cc.
References SIM_DATA::_genout, CKT_BASE::_sim, and EVAL_BM_ACTION_BASE::tr_finish_tdv().
{
  tr_finish_tdv(d, d->_sim->_genout);
}
The documentation for this class was generated from the following file:
savant/gnucap/src/bm_generator.cc