gnucap: Token_SYMBOL Class Reference
Token_SYMBOL Class Reference
#include <m_expression.h>
Public Member Functions
Token_SYMBOL (const std::string Name, const std::string Args)
Token_SYMBOL (const Token_SYMBOL &P)
Token * clone () const
void stack_op (Expression *) const
Detailed Description
Definition at line 58 of file m_expression.h.
Constructor & Destructor Documentation
Token_SYMBOL::Token_SYMBOL (const std::string Name, const std::string Args) [inline, explicit]
Definition at line 61 of file m_expression.h.
Referenced by clone().
    : Token(Name, NULL, Args) {}
Token_SYMBOL::Token_SYMBOL (const Token_SYMBOL & P) [inline, explicit]
Definition at line 63 of file m_expression.h.
References untested.
: Token(P) {untested();}
Member Function Documentation
Token* Token_SYMBOL::clone () const [inline, virtual]
Implements Token.
Definition at line 64 of file m_expression.h.
References Token_SYMBOL(), and untested.
Referenced by stack_op().
{untested();return new Token_SYMBOL(*this);}
void Token_SYMBOL::stack_op (Expression * E) const [virtual]
Reimplemented from Token.
Definition at line 114 of file m_expression_reduce.cc.
References Expression::_scope, CS::_STRING, List_Base< T >::back(), clone(), PARAMETER< T >::e_val(), anonymous_namespace{func_core.cc}::function_dispatcher, PARAMETER< T >::has_hard_value(), List_Base< T >::is_empty(), Token::name(), NOT_INPUT, anonymous_namespace{c_genrat.cc}::p, CARD_LIST::params(), List_Base< T >::pop_back(), List_Base< T >::push_back(), unreachable, and Float::val_string().
{
  assert(E);
  // replace single token with its value
  if (!E->is_empty() && dynamic_cast<const Token_PARLIST*>(E->back())) {
    // has parameters (table or function)
    if (FUNCTION* f = function_dispatcher[name()]) {
      const Token* T1 = E->back(); // arglist
      E->pop_back();
      CS cmd(CS::_STRING, T1->name());
      std::string value = f->eval(cmd, E->_scope);
      const Float* v = new Float(value);
      E->push_back(new Token_CONSTANT(value, v, ""));
      delete T1;
    }else{
      throw Exception_No_Match(name()); //BUG// memory leak
      unreachable();
      E->push_back(clone());
    }
  }else{
    // has no parameters (scalar)
    if (strchr("0123456789.", name()[0])) {
      // a number
      Float* n = new Float(name());
      E->push_back(new Token_CONSTANT(name(), n, ""));
    }else{
      // a name
      PARAMETER<double> p = (*(E->_scope->params()))[name()];
      if (p.has_hard_value()) {
        // can find value - push value
        double v = p.e_val(NOT_INPUT, E->_scope);
        Float* n = new Float(v);
        E->push_back(new Token_CONSTANT(n->val_string(), n, ""));
      }else{
        // no value - push name (and accept incomplete solution later)
        String* s = new String(name());
        E->push_back(new Token_CONSTANT(name(), s, ""));
      }
    }
  }
}
The documentation for this class was generated from the following files:
savant/gnucap/src/m_expression.h
savant/gnucap/src/m_expression_reduce.cc