gnucap: anonymous_namespace{d_switch.cc}::SWITCH_BASE Class Reference
anonymous_namespace{d_switch.cc}::SWITCH_BASE Class Reference
Protected Member Functions
SWITCH_BASE ()
SWITCH_BASE (const SWITCH_BASE &p)
std::string value_name () const
std::string dev_type () const
bool print_type_in_spice () const
int tail_size () const
int max_nodes () const =0
int min_nodes () const =0
int matrix_nodes () const
int net_nodes () const =0
CARD * clone () const =0
void expand ()
void precalc_last ()
void tr_iwant_matrix ()
void tr_begin ()
void dc_advance ()
void tr_advance ()
void tr_regress ()
bool tr_needs_eval () const
bool do_tr ()
void tr_load ()
TIME_PAIR tr_review ()
void tr_unload ()
double tr_involts () const
double tr_involts_limited () const
void ac_iwant_matrix ()
void ac_begin ()
void do_ac ()
void ac_load ()
COMPLEX ac_involts () const
Protected Attributes
const ELEMENT * _input
Private Attributes
double _in [OPT::_keep_time_steps]
state_t _state [OPT::_keep_time_steps]
Detailed Description
Definition at line 59 of file d_switch.cc.
Constructor & Destructor Documentation
anonymous_namespace{d_switch.cc}::SWITCH_BASE::SWITCH_BASE () [explicit, protected]
Definition at line 379 of file d_switch.cc.
References _in, OPT::_keep_time_steps, _state, anonymous_namespace{d_switch.cc}::_UNKNOWN, COMPONENT::attach_common(), and anonymous_namespace{d_switch.cc}::Default_SWITCH.
  :ELEMENT(),
   _input(NULL)
{
  attach_common(&Default_SWITCH);
  std::fill_n(_in, int(OPT::_keep_time_steps), 0.);
  std::fill_n(_state, int(OPT::_keep_time_steps), _UNKNOWN);
}
anonymous_namespace{d_switch.cc}::SWITCH_BASE::SWITCH_BASE (const SWITCH_BASE & p) [explicit, protected]
Definition at line 388 of file d_switch.cc.
References _in, OPT::_keep_time_steps, _state, and notstd::copy_n().
  :ELEMENT(p),
   _input(NULL)
{
  notstd::copy_n(p._in, int(OPT::_keep_time_steps), _in);
  notstd::copy_n(p._state, int(OPT::_keep_time_steps), _state);
}
Member Function Documentation
void anonymous_namespace{d_switch.cc}::SWITCH_BASE::ac_begin () [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 88 of file d_switch.cc.
{_ev = _y[0].f1; _acg = _m0.c1;}
COMPLEX anonymous_namespace{d_switch.cc}::SWITCH_BASE::ac_involts () const [inline, protected, virtual]
Implements ELEMENT.
Definition at line 91 of file d_switch.cc.
References untested.
{untested(); return ac_outvolts();}
void anonymous_namespace{d_switch.cc}::SWITCH_BASE::ac_iwant_matrix () [inline, protected, virtual]
Implements ELEMENT.
Definition at line 87 of file d_switch.cc.
{ac_iwant_matrix_passive();}
void anonymous_namespace{d_switch.cc}::SWITCH_BASE::ac_load () [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 90 of file d_switch.cc.
{ac_load_passive();}
CARD* anonymous_namespace{d_switch.cc}::SWITCH_BASE::clone () const [protected, pure virtual]
Reimplemented from CARD.
Implemented in anonymous_namespace{d_switch.cc}::DEV_CSWITCH, and anonymous_namespace{d_switch.cc}::DEV_VSWITCH.
void anonymous_namespace{d_switch.cc}::SWITCH_BASE::dc_advance () [protected, virtual]
Reimplemented from ELEMENT.
Definition at line 457 of file d_switch.cc.
References _state.
{
  ELEMENT::dc_advance();
  _state[1] = _state[0];
}
std::string anonymous_namespace{d_switch.cc}::SWITCH_BASE::dev_type () const [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 65 of file d_switch.cc.
{assert(common()); return common()->modelname().c_str();}
void anonymous_namespace{d_switch.cc}::SWITCH_BASE::do_ac () [protected, virtual]
Reimplemented from CARD.
Definition at line 598 of file d_switch.cc.
References ELEMENT::_acg, ELEMENT::_ev, ELEMENT::_m0, ELEMENT::_y, and CPOLY1::c1.
{
  assert(_ev  == _y[0].f1);
  assert(_acg == _m0.c1);
}
bool anonymous_namespace{d_switch.cc}::SWITCH_BASE::do_tr () [protected, virtual]
Reimplemented from CARD.
Definition at line 514 of file d_switch.cc.
References _input, ELEMENT::_m0, CARD::_n, anonymous_namespace{d_switch.cc}::_OFF, anonymous_namespace{d_switch.cc}::_ON, CKT_BASE::_sim, _state, ELEMENT::_y, SIM_DATA::analysis_is_static(), CPOLY1::c0, CPOLY1::c1, COMPONENT::common(), COMPONENT::converged(), FPOLY1::f1, IN1, IN2, LINEAR, COMMON_COMPONENT::model(), prechecked_cast, CKT_BASE::probe(), COMPONENT::q_load(), anonymous_namespace{d_switch.cc}::MODEL_SWITCH::roff, anonymous_namespace{d_switch.cc}::MODEL_SWITCH::ron, COMPONENT::set_converged(), COMPONENT::set_not_converged(), ELEMENT::store_values(), trace3, trace4, node_t::v0(), anonymous_namespace{d_switch.cc}::MODEL_SWITCH::von, and FPOLY1::x.
{
  const COMMON_SWITCH* c = prechecked_cast<const COMMON_SWITCH*>(common());
  assert(c);
  const MODEL_SWITCH* m = prechecked_cast<const MODEL_SWITCH*>(c->model());
  assert(m);
  if (_sim->analysis_is_static()) {
    _y[0].x = (_input)                  /* _y[0].x is controlling value */
      ? CARD::probe(_input,"I")         /* current controlled */
      : _n[IN1].v0() - _n[IN2].v0();    /* voltage controlled */
    state_t new_state;
    if (_y[0].x > m->von) {
      new_state = _ON;
    }else if (_y[0].x < m->voff) {
      new_state = _OFF;
    }else{
      new_state = _state[1];
    }
    if (new_state != _state[0]) {
      _y[0].f1 = (new_state == _ON) ? m->ron : m->roff; /* unknown is off */
      _state[0] = new_state;
      _m0.c1 = 1./_y[0].f1;
      trace4("change", new_state, old_state, _y[0].f1, _m0.c1);
      q_load();
      store_values();
      set_not_converged();
    }else{
      trace3("no change", new_state, _y[0].f1, _m0.c1);
      set_converged();
    }
  }else{
    // Above isn't necessary because it was done in tr_advance,
    // and doesn't iterate.
    // I believe it is not necessary on restart, because it is stored.
    if (_state[0] != _state[1]) {
      q_load();
      store_values();
    }else{
      // gets here only on "nobypass"
    }
    assert(converged());
  }
  assert(_y[0].f1 == ((_state[0] == _ON) ? m->ron : m->roff));
  assert(_y[0].f0 == LINEAR);
  //assert(_m0.c1 == 1./_y[0].f1);
  assert(_m0.c0 == 0.);
  return converged();
}
void anonymous_namespace{d_switch.cc}::SWITCH_BASE::expand () [protected, virtual]
Reimplemented from COMPONENT.
Reimplemented in anonymous_namespace{d_switch.cc}::DEV_CSWITCH.
Definition at line 396 of file d_switch.cc.
References COMPONENT::attach_model(), COMPONENT::common(), COMPONENT::has_common(), CARD::long_label(), and COMMON_COMPONENT::model().
{
  ELEMENT::expand();
  attach_model();
  const COMMON_SWITCH* c = dynamic_cast<const COMMON_SWITCH*>(common());
  assert(c);
  const MODEL_SWITCH* m = dynamic_cast<const MODEL_SWITCH*>(c->model());
  if (!m) {
    assert(has_common());
    throw Exception_Model_Type_Mismatch(long_label(), common()->modelname(),
                                        "switch (SW or CSW)");
  }else{
  }
}
int anonymous_namespace{d_switch.cc}::SWITCH_BASE::matrix_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 70 of file d_switch.cc.
{return 2;}
int anonymous_namespace{d_switch.cc}::SWITCH_BASE::max_nodes () const [protected, pure virtual]
Reimplemented from COMPONENT.
Implemented in anonymous_namespace{d_switch.cc}::DEV_CSWITCH, and anonymous_namespace{d_switch.cc}::DEV_VSWITCH.
int anonymous_namespace{d_switch.cc}::SWITCH_BASE::min_nodes () const [protected, pure virtual]
Reimplemented from COMPONENT.
Implemented in anonymous_namespace{d_switch.cc}::DEV_CSWITCH, and anonymous_namespace{d_switch.cc}::DEV_VSWITCH.
int anonymous_namespace{d_switch.cc}::SWITCH_BASE::net_nodes () const [protected, pure virtual]
Reimplemented from COMPONENT.
Implemented in anonymous_namespace{d_switch.cc}::DEV_CSWITCH, and anonymous_namespace{d_switch.cc}::DEV_VSWITCH.
void anonymous_namespace{d_switch.cc}::SWITCH_BASE::precalc_last () [protected, virtual]
Reimplemented from ELEMENT.
Definition at line 412 of file d_switch.cc.
References anonymous_namespace{d_switch.cc}::COMMON_SWITCH::_ic, ELEMENT::_loss0, ELEMENT::_loss1, ELEMENT::_m0, ELEMENT::_m1, anonymous_namespace{d_switch.cc}::_ON, CKT_BASE::_sim, _state, ELEMENT::_y, ELEMENT::_y1, CPOLY1::c0, CPOLY1::c1, COMPONENT::common(), FPOLY1::f1, CARD::is_constant(), SIM_DATA::is_first_expand(), COMMON_COMPONENT::model(), prechecked_cast, anonymous_namespace{d_switch.cc}::MODEL_SWITCH::roff, and anonymous_namespace{d_switch.cc}::MODEL_SWITCH::ron.
{
  ELEMENT::precalc_last();
  if (_sim->is_first_expand()) {
    const COMMON_SWITCH* c = prechecked_cast<const COMMON_SWITCH*>(common());
    assert(c);
    const MODEL_SWITCH* m = prechecked_cast<const MODEL_SWITCH*>(c->model());
    assert(m);
    _y1.f1 = _y[0].f1 = (c->_ic == _ON) ? m->ron : m->roff;     // override, unknown is off
    assert(!is_constant()); // depends on input
    // converged?????
    _m0.c1 = 1./_y[0].f1;
    _m0.c0 = 0.;
    _m1 = _m0;
    _state[1] = _state[0] = c->_ic;
  }else{
  }
  assert(_loss0 == 0.);
  assert(_loss1 == 0.);
}
bool anonymous_namespace{d_switch.cc}::SWITCH_BASE::print_type_in_spice () const [inline, protected, virtual]
Reimplemented from ELEMENT.
Definition at line 66 of file d_switch.cc.
{return true;}
int anonymous_namespace{d_switch.cc}::SWITCH_BASE::tail_size () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 67 of file d_switch.cc.
{return 1;}
void anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_advance () [protected, virtual]
Reimplemented from ELEMENT.
Definition at line 463 of file d_switch.cc.
References _in, ELEMENT::_m0, anonymous_namespace{d_switch.cc}::_OFF, anonymous_namespace{d_switch.cc}::_ON, _state, ELEMENT::_y, CPOLY1::c0, CPOLY1::c1, COMPONENT::common(), conchk(), FPOLY1::f1, LINEAR, COMMON_COMPONENT::model(), prechecked_cast, COMPONENT::q_eval(), anonymous_namespace{d_switch.cc}::MODEL_SWITCH::roff, anonymous_namespace{d_switch.cc}::MODEL_SWITCH::ron, COMPONENT::set_converged(), trace4, anonymous_namespace{d_switch.cc}::MODEL_SWITCH::von, and FPOLY1::x.
{
  ELEMENT::tr_advance();
  const COMMON_SWITCH* c = prechecked_cast<const COMMON_SWITCH*>(common());
  assert(c);
  const MODEL_SWITCH* m = prechecked_cast<const MODEL_SWITCH*>(c->model());
  assert(m);
   _state[1] = _state[0];
  _y[0].x = _in[1] = _in[0];
  if (_y[0].x >= m->von) {
    _state[0] = _ON;
  }else if (_y[0].x <= m->voff) {
    _state[0] = _OFF;
  }else{
    _state[0] = _state[1];
  }
  if (_state[1] != _state[0]) {
    _y[0].f1 = (_state[0] == _ON) ? m->ron : m->roff;   /* unknown is off */
    _m0.c1 = 1./_y[0].f1;
    q_eval();
  }else{
  }
  assert(_y[0].f1 == ((_state[0] == _ON) ? m->ron : m->roff));
  assert(_y[0].f0 == LINEAR);
  trace4("", _m0.c1, 1./_y[0].f1, ((_m0.c1) - (1./_y[0].f1)), ((_m0.c1) / (1./_y[0].f1)));
  assert(conchk(_m0.c1, 1./_y[0].f1));
  assert(_m0.c0 == 0.);
  set_converged();
}
void anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_begin () [protected, virtual]
Reimplemented from ELEMENT.
Definition at line 437 of file d_switch.cc.
References anonymous_namespace{d_switch.cc}::COMMON_SWITCH::_ic, ELEMENT::_loss0, ELEMENT::_loss1, ELEMENT::_m0, ELEMENT::_m1, anonymous_namespace{d_switch.cc}::_ON, _state, ELEMENT::_y, ELEMENT::_y1, CPOLY1::c0, CPOLY1::c1, COMPONENT::common(), FPOLY1::f1, LINEAR, COMMON_COMPONENT::model(), prechecked_cast, anonymous_namespace{d_switch.cc}::MODEL_SWITCH::roff, anonymous_namespace{d_switch.cc}::MODEL_SWITCH::ron, and COMPONENT::set_converged().
{
  ELEMENT::tr_begin();
  const COMMON_SWITCH* c = prechecked_cast<const COMMON_SWITCH*>(common());
  assert(c);
  const MODEL_SWITCH* m = prechecked_cast<const MODEL_SWITCH*>(c->model());
  assert(m);
  assert(_loss0 == 0.);
  assert(_loss1 == 0.);
  assert(_y[0].f0 == LINEAR);
  _y1.f1 = _y[0].f1 = ((c->_ic == _ON) ? m->ron : m->roff);  /* unknown is off */
  _m0.c1 = 1./_y[0].f1;
  assert(_m0.c0 == 0.);
  _m1 = _m0;
  _state[1] = _state[0] = c->_ic;
  set_converged();
}
double anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_involts () const [inline, protected, virtual]
Implements ELEMENT.
Definition at line 85 of file d_switch.cc.
References untested.
{untested(); return tr_outvolts();}
double anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_involts_limited () const [inline, protected, virtual]
Implements ELEMENT.
Definition at line 86 of file d_switch.cc.
References unreachable.
{unreachable(); return tr_outvolts_limited();}
void anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_iwant_matrix () [inline, protected, virtual]
Implements ELEMENT.
Definition at line 75 of file d_switch.cc.
{tr_iwant_matrix_passive();}
void anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_load () [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 82 of file d_switch.cc.
{tr_load_passive();}
bool anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_needs_eval () const [inline, protected, virtual]
Reimplemented from ELEMENT.
Definition at line 80 of file d_switch.cc.
{return _sim->analysis_is_static();} // also q by tr_advance
void anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_regress () [protected, virtual]
Reimplemented from ELEMENT.
Definition at line 498 of file d_switch.cc.
References ELEMENT::_m0, anonymous_namespace{d_switch.cc}::_ON, _state, ELEMENT::_y, CPOLY1::c0, CPOLY1::c1, COMPONENT::common(), FPOLY1::f1, LINEAR, COMMON_COMPONENT::model(), prechecked_cast, anonymous_namespace{d_switch.cc}::MODEL_SWITCH::roff, anonymous_namespace{d_switch.cc}::MODEL_SWITCH::ron, and COMPONENT::set_converged().
{
  ELEMENT::tr_regress();
  const COMMON_SWITCH* c = prechecked_cast<const COMMON_SWITCH*>(common());
  assert(c);
  const MODEL_SWITCH* m = prechecked_cast<const MODEL_SWITCH*>(c->model());
  assert(m);
  assert(_y[0].f1 == ((_state[0] == _ON) ? m->ron : m->roff));
  assert(_y[0].f0 == LINEAR);
  assert(_m0.c1 == 1./_y[0].f1);
  assert(_m0.c0 == 0.);
  set_converged();
}
TIME_PAIR anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_review () [protected, virtual]
Reimplemented from ELEMENT.
Definition at line 566 of file d_switch.cc.
References TIME_PAIR::_event, _in, _input, CARD::_n, anonymous_namespace{d_switch.cc}::_OFF, anonymous_namespace{d_switch.cc}::_ON, _state, ELEMENT::_time, COMPONENT::_time_by, COMPONENT::common(), IN1, IN2, TIME_PAIR::min_event(), COMMON_COMPONENT::model(), NEVER, prechecked_cast, CKT_BASE::probe(), node_t::v0(), anonymous_namespace{d_switch.cc}::MODEL_SWITCH::voff, and anonymous_namespace{d_switch.cc}::MODEL_SWITCH::von.
{
  ELEMENT::tr_review();
  const COMMON_SWITCH* c = prechecked_cast<const COMMON_SWITCH*>(common());
  assert(c);
  const MODEL_SWITCH* m = prechecked_cast<const MODEL_SWITCH*>(c->model());
  assert(m);
  _in[0] = (_input)
    ? CARD::probe(_input,"I")
    : _n[IN1].v0() - _n[IN2].v0();
  double old_dt = _time[0] - _time[1];
  double old_dv = _in[0] - _in[1];
  if (_state[0] != _ON  &&  old_dv > 0) {
    double new_dv = m->von - _in[1];
    double new_dt = old_dt * new_dv / old_dv;
    _time_by.min_event(_time[1] + new_dt);
  }else if (_state[0] != _OFF  &&  old_dv < 0) {
    double new_dv = m->voff - _in[1];
    double new_dt = old_dt * new_dv / old_dv;
    _time_by.min_event(_time[1] + new_dt);
  }else{
    assert(_time_by._event == NEVER);
  }
  // _time_by_event is the predicted switch time
  return _time_by;
}
void anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_unload () [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 84 of file d_switch.cc.
References untested.
{untested(); tr_unload_passive();}
std::string anonymous_namespace{d_switch.cc}::SWITCH_BASE::value_name () const [inline, protected, virtual]
Implements CARD.
Definition at line 64 of file d_switch.cc.
{return "";}
Member Data Documentation
double anonymous_namespace{d_switch.cc}::SWITCH_BASE::_in[OPT::_keep_time_steps] [private]
Definition at line 95 of file d_switch.cc.
Referenced by SWITCH_BASE(), tr_advance(), and tr_review().
const ELEMENT* anonymous_namespace{d_switch.cc}::SWITCH_BASE::_input [protected]
Definition at line 93 of file d_switch.cc.
Referenced by do_tr(), anonymous_namespace{d_switch.cc}::DEV_CSWITCH::expand(), and tr_review().
state_t anonymous_namespace{d_switch.cc}::SWITCH_BASE::_state[OPT::_keep_time_steps] [private]
Definition at line 96 of file d_switch.cc.
Referenced by dc_advance(), do_tr(), precalc_last(), SWITCH_BASE(), tr_advance(), tr_begin(), tr_regress(), and tr_review().
The documentation for this class was generated from the following file:
savant/gnucap/src/d_switch.cc