gnucap: MODEL_SUBCKT Class Reference
MODEL_SUBCKT Class Reference
#include <d_subckt.h>
Public Member Functions
MODEL_SUBCKT ()
~MODEL_SUBCKT ()
char id_letter () const
CARD * clone_instance () const
bool print_type_in_spice () const
std::string value_name () const
std::string dev_type () const
int max_nodes () const
int min_nodes () const
int matrix_nodes () const
int net_nodes () const
CARD * clone () const
bool is_device () const
void precalc_first ()
void expand ()
void precalc_last ()
bool makes_own_scope () const
void map_nodes ()
CARD_LIST * scope ()
const CARD_LIST * scope () const
std::string port_name (int) const
Static Public Member Functions
static int count ()
Private Member Functions
MODEL_SUBCKT (const MODEL_SUBCKT &p)
Private Attributes
node_t _nodes [PORTS_PER_SUBCKT]
Static Private Attributes
static int _count = -1
Detailed Description
Definition at line 33 of file d_subckt.h.
Constructor & Destructor Documentation
MODEL_SUBCKT::MODEL_SUBCKT (const MODEL_SUBCKT & p) [explicit, private]
Definition at line 124 of file d_subckt.cc.
References _count, CARD::_n, _nodes, CARD_LIST::is_empty(), max_nodes(), CARD::new_subckt(), and CARD::subckt().
  :COMPONENT(p)
{
  for (int ii = 0;  ii < max_nodes();  ++ii) {
    _nodes[ii] = p._nodes[ii];
  }
  _n = _nodes;
  assert(p.subckt()->is_empty()); // incomplete, but enough for now.
  new_subckt();
  ++_count;
}
MODEL_SUBCKT::MODEL_SUBCKT () [explicit]
Definition at line 116 of file d_subckt.cc.
References _count, CARD::_n, _nodes, and CARD::new_subckt().
  :COMPONENT()
{
  _n = _nodes;
  new_subckt();
  ++_count;
}
MODEL_SUBCKT::~MODEL_SUBCKT ()
Definition at line 136 of file d_subckt.cc.
References _count.
{
  --_count;
}
Member Function Documentation
CARD* MODEL_SUBCKT::clone () const [inline, virtual]
Reimplemented from CARD.
Definition at line 49 of file d_subckt.h.
{return new MODEL_SUBCKT(*this);}
CARD * MODEL_SUBCKT::clone_instance () const [virtual]
Reimplemented from CARD.
Definition at line 141 of file d_subckt.cc.
References DEV_SUBCKT::_parent, DEV_SUBCKT::clone(), and itested.
{itested();
  DEV_SUBCKT* new_instance = dynamic_cast<DEV_SUBCKT*>(p1.clone());
  new_instance->_parent = this;
  return new_instance;
}
static int MODEL_SUBCKT::count () [inline, static]
Definition at line 63 of file d_subckt.h.
{return _count;}
std::string MODEL_SUBCKT::dev_type () const [inline, virtual]
Reimplemented from CARD.
Definition at line 44 of file d_subckt.h.
References untested.
{untested(); return "";}
void MODEL_SUBCKT::expand () [inline, virtual]
Reimplemented from COMPONENT.
Definition at line 52 of file d_subckt.h.
{}
char MODEL_SUBCKT::id_letter () const [inline, virtual]
Reimplemented from CARD.
Definition at line 40 of file d_subckt.h.
References untested.
{untested();return '\0';}
bool MODEL_SUBCKT::is_device () const [inline, virtual]
Reimplemented from COMPONENT.
Definition at line 50 of file d_subckt.h.
{return false;}
bool MODEL_SUBCKT::makes_own_scope () const [inline, virtual]
Reimplemented from CARD.
Definition at line 54 of file d_subckt.h.
{return true;}
void MODEL_SUBCKT::map_nodes () [inline, virtual]
Reimplemented from COMPONENT.
Definition at line 55 of file d_subckt.h.
{}
int MODEL_SUBCKT::matrix_nodes () const [inline, virtual]
Reimplemented from COMPONENT.
Definition at line 47 of file d_subckt.h.
References untested.
{untested();return 0;}
int MODEL_SUBCKT::max_nodes () const [inline, virtual]
Reimplemented from COMPONENT.
Definition at line 45 of file d_subckt.h.
References PORTS_PER_SUBCKT.
Referenced by MODEL_SUBCKT(), and anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_module().
{return PORTS_PER_SUBCKT;}
int MODEL_SUBCKT::min_nodes () const [inline, virtual]
Reimplemented from COMPONENT.
Definition at line 46 of file d_subckt.h.
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_module().
{return 0;}
int MODEL_SUBCKT::net_nodes () const [inline, virtual]
Reimplemented from COMPONENT.
Definition at line 48 of file d_subckt.h.
References CARD::_net_nodes.
{return _net_nodes;}
std::string MODEL_SUBCKT::port_name (int) const [inline, virtual]
Implements COMPONENT.
Definition at line 59 of file d_subckt.h.
{
    return "";
  }
void MODEL_SUBCKT::precalc_first () [inline, virtual]
Reimplemented from COMPONENT.
Definition at line 51 of file d_subckt.h.
{}
void MODEL_SUBCKT::precalc_last () [inline, virtual]
Reimplemented from COMPONENT.
Definition at line 53 of file d_subckt.h.
{}
bool MODEL_SUBCKT::print_type_in_spice () const [inline, virtual]
Implements COMPONENT.
Definition at line 42 of file d_subckt.h.
References unreachable.
{unreachable(); return false;}
CARD_LIST* MODEL_SUBCKT::scope () [inline, virtual]
Reimplemented from CARD.
Definition at line 56 of file d_subckt.h.
References CARD::subckt().
{return subckt();}
const CARD_LIST* MODEL_SUBCKT::scope () const [inline, virtual]
Reimplemented from CARD.
Definition at line 57 of file d_subckt.h.
References CARD::subckt().
{return subckt();}
std::string MODEL_SUBCKT::value_name () const [inline, virtual]
Implements CARD.
Definition at line 43 of file d_subckt.h.
References incomplete.
{incomplete(); return "";}
Member Data Documentation
int MODEL_SUBCKT::_count = -1 [static, private]
Definition at line 67 of file d_subckt.h.
Referenced by MODEL_SUBCKT(), and ~MODEL_SUBCKT().
node_t MODEL_SUBCKT::_nodes[PORTS_PER_SUBCKT] [private]
Definition at line 66 of file d_subckt.h.
Referenced by MODEL_SUBCKT().
The documentation for this class was generated from the following files:
savant/gnucap/src/d_subckt.h
savant/gnucap/src/d_subckt.cc