gnucap: anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L Class Reference
anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L Class Reference
Public Member Functions
DEV_MUTUAL_L ()
Private Member Functions
DEV_MUTUAL_L (const DEV_MUTUAL_L &p)
char id_letter () const
bool print_type_in_spice () const
std::string value_name () const
std::string dev_type () const
int max_nodes () const
int min_nodes () const
int matrix_nodes () const
int net_nodes () const
int num_current_ports () const
bool has_iv_probe () const
bool use_obsolete_callback_parse () const
CARD * clone () const
void expand_first ()
void expand_last ()
void precalc_last ()
void tr_iwant_matrix ()
void tr_begin ()
void dc_advance ()
void tr_advance ()
bool do_tr ()
bool do_tr_last ()
void tr_load ()
TIME_PAIR tr_review ()
void tr_unload ()
double tr_input () const
double tr_input_limited () const
double tr_amps () const
double tr_probe_num (const std::string &) const
void ac_iwant_matrix ()
void ac_load ()
COMPLEX ac_amps () const
void set_port_by_name (std::string &Name, std::string &Value)
void set_port_by_index (int Index, std::string &Value)
bool node_is_connected (int i) const
std::string port_name (int) const
std::string current_port_name (int i) const
const std::string current_port_value (int i) const
void set_current_port_by_index (int i, const std::string &s)
Private Attributes
std::string _output_label
DEV_INDUCTANCE * _output
std::string _input_label
DEV_INDUCTANCE * _input
double _lm
double _mf0_c0
double _mf1_c0
double _mr0_c0
double _mr1_c0
FPOLY1 _yf1
FPOLY1 _yf [OPT::_keep_time_steps]
FPOLY1 _if [OPT::_keep_time_steps]
FPOLY1 _yr1
FPOLY1 _yr [OPT::_keep_time_steps]
FPOLY1 _ir [OPT::_keep_time_steps]
Detailed Description
Definition at line 85 of file d_coil.cc.
Constructor & Destructor Documentation
anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::DEV_MUTUAL_L (const DEV_MUTUAL_L & p) [explicit, private]
Definition at line 197 of file d_coil.cc.
References anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::_c_model, _yf, _yf1, _yr, and _yr1.
  :DEV_INDUCTANCE(p),
   _output_label(p._output_label),
   _output(p._output),
   _input_label(p._input_label),
   _input(p._input),
   _lm(p._lm),
   _mf0_c0(0.),
   _mf1_c0(0.),
   _mr0_c0(0.),
   _mr1_c0(0.)
{
  _c_model = true;
  assert(_yf[0].x == 0. && _yf[0].f0 == 0. && _yf[0].f1 == 0.);
  assert(_yf1 == _yf[0]);
  assert(_yr[0].x == 0. && _yr[0].f0 == 0. && _yr[0].f1 == 0.);
  assert(_yr1 == _yr[0]);
}
anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::DEV_MUTUAL_L () [explicit]
Definition at line 178 of file d_coil.cc.
References anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::_c_model, _yf, _yf1, _yr, and _yr1.
  :DEV_INDUCTANCE(),
   _output_label(),
   _output(0),
   _input_label(),
   _input(0),
   _lm(NOT_INPUT),
   _mf0_c0(0.),
   _mf1_c0(0.),
   _mr0_c0(0.),
   _mr1_c0(0.)
{
  _c_model = true;
  assert(_yf[0].x == 0. && _yf[0].f0 == 0. && _yf[0].f1 == 0.);
  assert(_yf1 == _yf[0]);
  assert(_yr[0].x == 0. && _yr[0].f0 == 0. && _yr[0].f1 == 0.);
  assert(_yr1 == _yr[0]);
}
Member Function Documentation
COMPLEX anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::ac_amps () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 138 of file d_coil.cc.
References untested.
{untested(); return _loss0 * ac_outvolts();}
void anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::ac_iwant_matrix () [inline, private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 136 of file d_coil.cc.
{ac_iwant_matrix_passive();}
void anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::ac_load () [private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 521 of file d_coil.cc.
References ELEMENT::ac_load_couple().
{
  ac_load_couple();
}
CARD* anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::clone () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 118 of file d_coil.cc.
{return new DEV_MUTUAL_L(*this);}
std::string anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::current_port_name (int i) const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 155 of file d_coil.cc.
References untested.
                                          {untested();
    assert(i >= 0);
    assert(i < 2);
    static std::string names[] = {"l1", "l2"};
    return names[i];
  }
const std::string anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::current_port_value (int i) const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 161 of file d_coil.cc.
References COMPONENT::current_port_value(), and unreachable.
{
    switch (i) {
    case 0:  return _output_label;
    case 1:  return _input_label;
    default: unreachable(); return COMPONENT::current_port_value(i);
    }
  }
void anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::dc_advance () [private, virtual]
Reimplemented from STORAGE.
Definition at line 316 of file d_coil.cc.
References _if, _ir, and OPT::_keep_time_steps.
{
  STORAGE::dc_advance();
  for (int i = 1;  i < OPT::_keep_time_steps;  ++i) {
    _if[i] = _if[0];
    _ir[i] = _ir[0];
  }
}
std::string anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::dev_type () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 110 of file d_coil.cc.
References untested.
{untested(); return "mutual_inductor";}
bool anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::do_tr () [inline, private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 126 of file d_coil.cc.
{_sim->_late_evalq.push_back(this); return true;}
bool anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::do_tr_last () [private, virtual]
Reimplemented from CARD.
Definition at line 376 of file d_coil.cc.
References STORAGE::_i, _if, _input, _ir, _lm, ELEMENT::_loss0, ELEMENT::_m0, STORAGE::_method_a, _mf0_c0, _mr0_c0, CARD::_n, _output, ELEMENT::_time, ELEMENT::_y, _yf, _yf1, _yr, _yr1, FPOLY1::c0(), CPOLY1::c0, FPOLY1::c1(), CPOLY1::c1, differentiate(), FPOLY1::f0, FPOLY1::f1, NOT_VALID, OUT1, OUT2, COMPONENT::q_load(), ELEMENT::store_values(), trace3, node_t::v0(), COMPONENT::value(), FPOLY1::x, and CPOLY1::x.
{
  double l1 = _output->_y[0].f1;
  double l2 = _input->_y[0].f1;
  _lm = value() * sqrt(l1 * l2);
  _y[0].x = _n[OUT1].v0() - _n[OUT2].v0(); // really current
  _y[0].f1 = -_lm;
  _y[0].f0 = _y[0].x * _y[0].f1;           // flux = I * L
  trace3("", _y[0].x, _y[0].f0, _y[0].f1);
  store_values();
  _i[0] = differentiate(_y, _i, _time, _method_a);  // really voltage, v = df/dt
  trace3("", _i[0].x, _i[0].f0, _i[0].f1);
  _m0.x = NOT_VALID;
  _m0.c1 = -_loss0 * _loss0 * _i[0].c1();
  _m0.c0 = -_loss0 * _loss0 * _i[0].c0();
  trace3("", _m0.x, _m0.c0, _m0.c1);
  _yf[0].x = _n[OUT1].v0();
  _yf[0].f1 = -_lm;
  _yf[0].f0 = _yf[0].x * _yf[0].f1;
  trace3("", _yf[0].x, _yf[0].f0, _yf[0].f1);
  assert(_yf[0]==_yf[0]); // store_values();
  _yf1=_yf[0];            // store_values();
  _if[0] = differentiate(_yf, _if, _time, _method_a);
  trace3("", _if[0].x, _if[0].f0, _if[0].f1);
  _mf0_c0 = -_loss0 * _loss0 * _if[0].c0();
  _yr[0].x = _n[OUT2].v0();
  _yr[0].f1 = -_lm;
  _yr[0].f0 = _yr[0].x * _yr[0].f1;
  trace3("", _yr[0].x, _yr[0].f0, _yr[0].f1);
  assert(_yr[0]==_yr[0]); // store_values();
  _yr1=_yr[0];            // store_values();
  _ir[0] = differentiate(_yr, _ir, _time, _method_a);
  trace3("", _ir[0].x, _ir[0].f0, _ir[0].f1);
  _mr0_c0 = -_loss0 * _loss0 * _ir[0].c0();
  q_load();
  return true;
}
void anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::expand_first () [private, virtual]
Reimplemented from CARD.
Definition at line 229 of file d_coil.cc.
References anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::_c_model, _input, _input_label, _output, _output_label, CARD::find_in_my_scope(), and CARD::long_label().
{
  _output = dynamic_cast<DEV_INDUCTANCE*>(find_in_my_scope(_output_label));
  if (!_output) {
    throw Exception_Type_Mismatch(long_label(), _output_label, "inductor");
  }else{
    _output->_c_model = true;
  }
  _input = dynamic_cast<DEV_INDUCTANCE*>(find_in_my_scope(_input_label));
  if (!_input) {
    throw Exception_Type_Mismatch(long_label(), _input_label, "inductor");
  }else{
    _input->_c_model = true;
  }
}
void anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::expand_last () [private, virtual]
Reimplemented from CARD.
Definition at line 246 of file d_coil.cc.
References _input, CARD::_n, _output, CKT_BASE::_sim, anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::expand(), IN1, SIM_DATA::is_first_expand(), CARD::n_(), OUT1, OUT2, and untested.
{
  STORAGE::expand(); // skip DEV_INDUCTANCE
  if (_sim->is_first_expand()) {
    _n[OUT2] = _input->n_(IN1);
    _n[OUT1] = _output->n_(IN1);
  }else{untested();
  }
}
bool anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::has_iv_probe () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 116 of file d_coil.cc.
References untested.
{untested(); return false;}
char anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::id_letter () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 107 of file d_coil.cc.
{return 'K';}
int anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::matrix_nodes () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 113 of file d_coil.cc.
{return 2;}
int anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::max_nodes () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 111 of file d_coil.cc.
{return 2;}
int anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::min_nodes () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 112 of file d_coil.cc.
{return 2;}
int anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::net_nodes () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 114 of file d_coil.cc.
{return 0;}
bool anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::node_is_connected (int i) const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 144 of file d_coil.cc.
References unreachable.
{
    switch (i) {
    case 0:  return _output_label != "";
    case 1:  return _input_label != "";
    default: unreachable(); return false;
    }
  }
int anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::num_current_ports () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 115 of file d_coil.cc.
{return 2;}
std::string anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::port_name (int) const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 152 of file d_coil.cc.
References untested.
                                {untested();
    return "";
  }
void anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::precalc_last () [private, virtual]
Reimplemented from STORAGE.
Definition at line 256 of file d_coil.cc.
References _input, _lm, _output, CKT_BASE::_sim, ELEMENT::_y, _yf, _yr, FPOLY1::f1, SIM_DATA::is_first_expand(), LINEAR, CARD::long_label(), STORAGE::precalc_last(), trace3, and COMPONENT::value().
{
  _output->precalc_last();
  _input->precalc_last();
  DEV_INDUCTANCE::precalc_last();
  double l1 = _output->value();
  double l2 = _input->value();
  _lm = value() * sqrt(l1 * l2);
  trace3(long_label().c_str(), l1, l2, _lm);
  if (_sim->is_first_expand()) {
    assert(_y[0].x  == 0.);
    assert(_y[0].f0 == LINEAR);
    _y[0].f1 = -_lm; // override
    _yf[0] = _yr[0] = _y[0];
  }else{
  }
}
bool anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::print_type_in_spice () const [inline, private, virtual]
Reimplemented from ELEMENT.
Definition at line 108 of file d_coil.cc.
{return false;}
void anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::set_current_port_by_index (int i, const std::string & s) [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 168 of file d_coil.cc.
References unreachable.
{
    switch (i) {
    case 0:  _output_label = s; break;
    case 1:  _input_label = s;  break;
    default: unreachable();     break;
    }
  }
void anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::set_port_by_index (int Index, std::string & Value) [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 142 of file d_coil.cc.
                {set_current_port_by_index(Index, Value);}
void anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::set_port_by_name (std::string & Name, std::string & Value) [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 140 of file d_coil.cc.
References COMPONENT::set_port_by_name(), and untested.
                {untested(); COMPONENT::set_port_by_name(Name,Value);}
void anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_advance () [private, virtual]
Reimplemented from STORAGE.
Definition at line 326 of file d_coil.cc.
References _if, _ir, OPT::_keep_time_steps, _yf, and _yr.
{
  STORAGE::tr_advance();
  for (int i=OPT::_keep_time_steps-1; i>0; --i) {
    _yf[i] = _yf[i-1];
    _yr[i] = _yr[i-1];
    _if[i] = _if[i-1];
    _ir[i] = _ir[i-1];
  }
}
double anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_amps () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 133 of file d_coil.cc.
References untested.
{untested(); return _loss0 * tr_outvolts();}
void anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_begin () [private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 302 of file d_coil.cc.
References _if, _ir, OPT::_keep_time_steps, _lm, _mf0_c0, _mf1_c0, _mr0_c0, _mr1_c0, ELEMENT::_y, ELEMENT::_y1, FPOLY1::f1, and LINEAR.
{
  DEV_INDUCTANCE::tr_begin();
  assert(_y[0].x  == 0.);
  assert(_y[0].f0 == LINEAR);
  _y[0].f1 = -_lm; // override
  _y1 = _y[0];
  for (int i = 0;  i < OPT::_keep_time_steps;  ++i) {
    _if[i] = _ir[i] = FPOLY1(0., 0., 0.);
  }
  _mf1_c0 = _mf0_c0 = _mr1_c0 = _mr0_c0 = 0.;
}
double anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_input () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 131 of file d_coil.cc.
{return tr_involts();}
double anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_input_limited () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 132 of file d_coil.cc.
References untested.
{untested(); return tr_involts_limited();}
void anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_iwant_matrix () [inline, private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 122 of file d_coil.cc.
{tr_iwant_matrix_passive();}
void anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_load () [private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 429 of file d_coil.cc.
References _mf0_c0, _mf1_c0, _mr0_c0, _mr1_c0, CARD::_n, OUT1, OUT2, ELEMENT::tr_load_couple(), ELEMENT::tr_load_source(), and ELEMENT::tr_load_source_point().
{
  tr_load_couple();
  tr_load_source();
  tr_load_source_point(_n[OUT2], &_mr0_c0, &_mr1_c0);
  tr_load_source_point(_n[OUT1], &_mf0_c0, &_mf1_c0);
}
double anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_probe_num (const std::string & x) const [private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 554 of file d_coil.cc.
References _mf0_c0, _mr0_c0, _yf, _yr, FPOLY1::f0, Umatch(), and untested.
{untested();
  if (Umatch(x, "fflux ")) {untested();
    return _yf[0].f0;
  }else if (Umatch(x, "rflux ")) {untested();
    return _yr[0].f0;
  }else if (Umatch(x, "fiof{fset} ")) {untested();
    return _mf0_c0;
  }else if (Umatch(x, "riof{fset} ")) {untested();
    return _mr0_c0;
  }else{untested();
    return DEV_INDUCTANCE::tr_probe_num(x);
  }
}
TIME_PAIR anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_review () [inline, private, virtual]
Reimplemented from STORAGE.
Definition at line 129 of file d_coil.cc.
References NEVER.
{return TIME_PAIR(NEVER,NEVER);}
void anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_unload () [private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 444 of file d_coil.cc.
References ELEMENT::tr_unload_couple(), and untested.
{untested();
  tr_unload_couple();
}
bool anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::use_obsolete_callback_parse () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 117 of file d_coil.cc.
{return false;}
std::string anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::value_name () const [inline, private, virtual]
Reimplemented from anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE.
Definition at line 109 of file d_coil.cc.
{return "k";}
Member Data Documentation
FPOLY1 anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::_if[OPT::_keep_time_steps] [private]
Definition at line 98 of file d_coil.cc.
Referenced by dc_advance(), do_tr_last(), tr_advance(), and tr_begin().
DEV_INDUCTANCE* anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::_input [private]
Definition at line 90 of file d_coil.cc.
Referenced by do_tr_last(), expand_first(), expand_last(), and precalc_last().
std::string anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::_input_label [private]
Definition at line 89 of file d_coil.cc.
Referenced by expand_first().
FPOLY1 anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::_ir[OPT::_keep_time_steps] [private]
Definition at line 101 of file d_coil.cc.
Referenced by dc_advance(), do_tr_last(), tr_advance(), and tr_begin().
double anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::_lm [private]
Definition at line 91 of file d_coil.cc.
Referenced by do_tr_last(), precalc_last(), and tr_begin().
double anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::_mf0_c0 [private]
Definition at line 92 of file d_coil.cc.
Referenced by do_tr_last(), tr_begin(), tr_load(), and tr_probe_num().
double anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::_mf1_c0 [private]
Definition at line 93 of file d_coil.cc.
Referenced by tr_begin(), and tr_load().
double anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::_mr0_c0 [private]
Definition at line 94 of file d_coil.cc.
Referenced by do_tr_last(), tr_begin(), tr_load(), and tr_probe_num().
double anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::_mr1_c0 [private]
Definition at line 95 of file d_coil.cc.
Referenced by tr_begin(), and tr_load().
DEV_INDUCTANCE* anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::_output [private]
Definition at line 88 of file d_coil.cc.
Referenced by do_tr_last(), expand_first(), expand_last(), and precalc_last().
std::string anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::_output_label [private]
Definition at line 87 of file d_coil.cc.
Referenced by expand_first().
FPOLY1 anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::_yf[OPT::_keep_time_steps] [private]
Definition at line 97 of file d_coil.cc.
Referenced by DEV_MUTUAL_L(), do_tr_last(), precalc_last(), tr_advance(), and tr_probe_num().
FPOLY1 anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::_yf1 [private]
Definition at line 96 of file d_coil.cc.
Referenced by DEV_MUTUAL_L(), and do_tr_last().
FPOLY1 anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::_yr[OPT::_keep_time_steps] [private]
Definition at line 100 of file d_coil.cc.
Referenced by DEV_MUTUAL_L(), do_tr_last(), precalc_last(), tr_advance(), and tr_probe_num().
FPOLY1 anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::_yr1 [private]
Definition at line 99 of file d_coil.cc.
Referenced by DEV_MUTUAL_L(), and do_tr_last().
The documentation for this class was generated from the following file:
savant/gnucap/src/d_coil.cc