gnucap: NODE Class Reference
NODE Class Reference
#include <e_node.h>
Public Member Functions
NODE (const NODE *p)
NODE (const std::string &s, int n)
~NODE ()
int user_number () const
int matrix_number () const
int m_ () const
NODE & set_user_number (int n)
double tr_probe_num (const std::string &) const
XPROBE ac_probe_ext (const std::string &) const
double v0 () const
double vt1 () const
COMPLEX vac () const
COMPLEX & iac ()
Protected Member Functions
NODE ()
Private Member Functions
NODE (const NODE &p)
Private Attributes
int _user_number
Detailed Description
Definition at line 82 of file e_node.h.
Constructor & Destructor Documentation
NODE::NODE () [explicit, protected]
Definition at line 91 of file e_node.cc.
  :CKT_BASE(),
   _user_number(INVALID_NODE)
   //_flat_number(INVALID_NODE)
   //_matrix_number(INVALID_NODE)
{
}
NODE::NODE (const NODE & p) [explicit, private]
Definition at line 101 of file e_node.cc.
References unreachable.
  :CKT_BASE(p),
   _user_number(p._user_number)
   //_flat_number(p._flat_number)
   //_matrix_number(INVALID_NODE)
{
  unreachable();
}
NODE::NODE (const NODE * p) [explicit]
Definition at line 113 of file e_node.cc.
References unreachable.
  :CKT_BASE(*p),
   _user_number(p->_user_number)
   //_flat_number(p->_flat_number)
   //_matrix_number(INVALID_NODE)
{
  unreachable();
}
NODE::NODE (const std::string & s, int n) [explicit]
Definition at line 124 of file e_node.cc.
  :CKT_BASE(s),
   _user_number(n)
   //_flat_number(n)
   //_matrix_number(INVALID_NODE)
{
}
NODE::~NODE () [inline]
Definition at line 94 of file e_node.h.
{}
Member Function Documentation
XPROBE NODE::ac_probe_ext (const std::string & x) const [virtual]
Reimplemented from CKT_BASE.
Definition at line 228 of file e_node.cc.
References SIM_DATA::_acx, CKT_BASE::_sim, ground_node, itested, port_impedance(), Umatch(), and vac().
Referenced by DEV_LOGIC::ac_probe_ext().
{
  if (Umatch(x, "v ")) {
    return XPROBE(vac());
  }else if (Umatch(x, "z ")) {
    return XPROBE(port_impedance(node_t(const_cast<NODE*>(this)),
                                 node_t(&ground_node), _sim->_acx, COMPLEX(0.)));
  }else{itested();
    return CKT_BASE::ac_probe_ext(x);
  }
}
COMPLEX& NODE::iac () [inline]
Definition at line 128 of file e_node.h.
References SIM_DATA::_ac, CKT_BASE::_sim, SIM_DATA::_total_nodes, and m_().
Referenced by ELEMENT::ac_load_source(), and ELEMENT::ac_load_source_point().
                    {
    assert(m_() >= 0);
    assert(m_() <= _sim->_total_nodes);
    return _sim->_ac[m_()];
  }
int NODE::m_ () const [inline]
Definition at line 101 of file e_node.h.
References matrix_number().
Referenced by iac(), tr_probe_num(), v0(), vac(), and vt1().
{return matrix_number();}
int NODE::matrix_number () const [inline]
Definition at line 100 of file e_node.h.
References SIM_DATA::_nm, CKT_BASE::_sim, and _user_number.
Referenced by m_(), and tr_probe_num().
{return _sim->_nm[_user_number];}
NODE& NODE::set_user_number (int n) [inline]
Definition at line 103 of file e_node.h.
References _user_number.
Referenced by SIM_DATA::alloc_hold_vectors().
{_user_number = n; return *this;}
double NODE::tr_probe_num (const std::string & x) const [virtual]
Reimplemented from CKT_BASE.
Reimplemented in LOGIC_NODE.
Definition at line 172 of file e_node.cc.
References SIM_DATA::_aa, SIM_DATA::_lu, SIM_DATA::_nstat, CKT_BASE::_sim, BSMATRIX< T >::d(), ground_node, itested, m_(), matrix_number(), port_impedance(), LOGIC_NODE::tr_probe_num(), Umatch(), v0(), and OPT::vfloor.
{
  if (Umatch(x, "v ")) {
    // return v0(); denoised
    return floor(v0()/OPT::vfloor + .5) * OPT::vfloor;
  }else if (Umatch(x, "z ")) {
    return port_impedance(node_t(const_cast<NODE*>(this)), node_t(&ground_node), _sim->_lu, 0.);
  }else if (Umatch(x, "l{ogic} |la{stchange} |fi{naltime} |di{ter} |ai{ter} |count ")) {
    assert(_sim->_nstat);
    return _sim->_nstat[matrix_number()].tr_probe_num(x);
  }else if (Umatch(x, "mdy ")) {
    // matrix diagonal admittance
    const BSMATRIX<double>&  aaa = _sim->_aa;
    return aaa.d(m_(),m_());
  }else if (Umatch(x, "mdz ")) {
    // matrix diagonal impedance
    const BSMATRIX<double>&  aaa = _sim->_aa;
    return 1/aaa.d(m_(),m_());
  }else if (Umatch(x, "zero ")) {
    // fake probe: 0.0
    return 0.0;
  }else if (Umatch(x, "pdz ")) {
    // fake probe 1/0 .. positive divide by zero = Infinity
    double z1 = tr_probe_num("zero ");
    return 1.0/z1;
  }else if (Umatch(x, "ndz ")) {
    // fake probe -1/0 .. negative divide by zero = -Infinity
    double z1 = tr_probe_num("zero ");
    return -1.0/z1;
  }else if (Umatch(x, "nan ")) {
    // fake probe 0/0 = NaN
    double z1 = tr_probe_num("zero ");
    double z2 = tr_probe_num("zero ");
    return z1/z2;
  }else{itested();
    return CKT_BASE::tr_probe_num(x);
  }
}
int NODE::user_number () const [inline]
Definition at line 97 of file e_node.h.
References _user_number.
Referenced by node_t::new_node().
{return _user_number;}
double NODE::v0 () const [inline]
Definition at line 110 of file e_node.h.
References CKT_BASE::_sim, SIM_DATA::_total_nodes, SIM_DATA::_v0, and m_().
Referenced by LOGIC_NODE::to_logic(), and tr_probe_num().
{
    assert(m_() >= 0);
    assert(m_() <= _sim->_total_nodes);
    return _sim->_v0[m_()];
  }
COMPLEX NODE::vac () const [inline]
Definition at line 120 of file e_node.h.
References SIM_DATA::_ac, CKT_BASE::_sim, SIM_DATA::_total_nodes, and m_().
Referenced by ac_probe_ext().
{
    assert(m_() >= 0);
    assert(m_() <= _sim->_total_nodes);
    return _sim->_ac[m_()];
  }
double NODE::vt1 () const [inline]
Definition at line 115 of file e_node.h.
References CKT_BASE::_sim, SIM_DATA::_total_nodes, SIM_DATA::_vt1, and m_().
Referenced by LOGIC_NODE::to_logic().
{
    assert(m_() >= 0);
    assert(m_() <= _sim->_total_nodes);
    return _sim->_vt1[m_()];
  }
Member Data Documentation
int NODE::_user_number [private]
Definition at line 84 of file e_node.h.
Referenced by matrix_number(), set_user_number(), and user_number().
The documentation for this class was generated from the following files:
savant/gnucap/src/e_node.h
savant/gnucap/src/e_node.cc