gnucap: EVAL_BUILT_IN_DIODE_Yj Class Reference
EVAL_BUILT_IN_DIODE_Yj Class Reference
#include <d_diode.h>
Public Member Functions
EVAL_BUILT_IN_DIODE_Yj (int c=0)
bool operator== (const COMMON_COMPONENT &x) const
COMMON_COMPONENT * clone () const
std::string name () const
void tr_eval (ELEMENT *d) const
bool has_tr_eval () const
bool has_ac_eval () const
Private Member Functions
EVAL_BUILT_IN_DIODE_Yj (const EVAL_BUILT_IN_DIODE_Yj &p)
Detailed Description
Definition at line 163 of file d_diode.h.
Constructor & Destructor Documentation
EVAL_BUILT_IN_DIODE_Yj::EVAL_BUILT_IN_DIODE_Yj (const EVAL_BUILT_IN_DIODE_Yj & p) [inline, explicit, private]
Definition at line 165 of file d_diode.h.
Referenced by clone().
    :COMMON_COMPONENT(p) {}
EVAL_BUILT_IN_DIODE_Yj::EVAL_BUILT_IN_DIODE_Yj (int c = 0) [inline, explicit]
Definition at line 168 of file d_diode.h.
:COMMON_COMPONENT(c) {}
Member Function Documentation
COMMON_COMPONENT* EVAL_BUILT_IN_DIODE_Yj::clone () const [inline, virtual]
Implements COMMON_COMPONENT.
Definition at line 170 of file d_diode.h.
References EVAL_BUILT_IN_DIODE_Yj().
{return new EVAL_BUILT_IN_DIODE_Yj(*this);}
bool EVAL_BUILT_IN_DIODE_Yj::has_ac_eval () const [inline, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 174 of file d_diode.h.
{return false;}
bool EVAL_BUILT_IN_DIODE_Yj::has_tr_eval () const [inline, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 173 of file d_diode.h.
{return true;}
std::string EVAL_BUILT_IN_DIODE_Yj::name () const [inline, virtual]
Implements COMMON_COMPONENT.
Definition at line 171 of file d_diode.h.
References untested.
{untested(); return "EVAL_BUILT_IN_DIODE_Yj";}
bool EVAL_BUILT_IN_DIODE_Yj::operator== (const COMMON_COMPONENT & x) const [inline, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 169 of file d_diode.h.
{return COMMON_COMPONENT::operator==(x);}
void EVAL_BUILT_IN_DIODE_Yj::tr_eval (ELEMENT * d) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 685 of file d_diode.cc.
References SIM_DATA::_fulldamp, DEV_BUILT_IN_DIODE::_gd, DEV_BUILT_IN_DIODE::_isat, DEV_BUILT_IN_DIODE::_region, CKT_BASE::_sim, SIM_DATA::_temp_c, MODEL_CARD::_tnom_c, ELEMENT::_y, ELEMENT::_y1, MODEL_BUILT_IN_DIODE::bv, COMPONENT::common(), OPT::dampstrategy, OPT::diodeflags, dsDEVLIMIT, MODEL_BUILT_IN_DIODE::eg, error(), FPOLY1::f0, FPOLY1::f1, MODEL_BUILT_IN_DIODE::flags, FORWARD, OPT::gmin, COMMON_BUILT_IN_DIODE::gparallel_adjusted, has_good_value(), incomplete, INITOFF, COMMON_BUILT_IN_DIODE::is_adjusted, SIM_DATA::is_initial_step(), CARD::long_label(), COMMON_COMPONENT::model(), MODEL_BUILT_IN_DIODE::mos_level, MODEL_BUILT_IN_DIODE::n_factor, COMMON_BUILT_IN_DIODE::off, CARD::owner(), anonymous_namespace{c_genrat.cc}::p, P_CELSIUS0, P_K_Q, prechecked_cast, REVERSE, COMMON_BUILT_IN_DIODE::sdp(), trace2, trace3, trace4, UNKNOWN, unreachable, untested, USE_OPT, FPOLY1::x, and MODEL_BUILT_IN_DIODE::xti.
{
  assert(d);
  DEV_BUILT_IN_DIODE* p = prechecked_cast<DEV_BUILT_IN_DIODE*>(d->owner());
  assert(p);
  const COMMON_BUILT_IN_DIODE* c = prechecked_cast<const COMMON_BUILT_IN_DIODE*>(p->common());
  assert(c);
  const SDP_BUILT_IN_DIODE* s = prechecked_cast<const SDP_BUILT_IN_DIODE*>(c->sdp());
  assert(s);
  const MODEL_BUILT_IN_DIODE* m = prechecked_cast<const MODEL_BUILT_IN_DIODE*>(c->model());
  assert(m);
    FPOLY1& y = d->_y[0];
    double volts = y.x;
    double amps  = y.f0;
    trace2(d->long_label().c_str(), volts, amps);
    int flags = (m->flags & USE_OPT) ? OPT::diodeflags : m->flags;
    double tempratio = (d->_sim->_temp_c+P_CELSIUS0) / (m->_tnom_c+P_CELSIUS0);
    double vt = P_K_Q * (d->_sim->_temp_c+P_CELSIUS0) * m->n_factor;
    region_t oldregion = p->_region;
    p->_isat = c->is_adjusted * pow(tempratio, m->xti)
      * exp((m->eg/vt) *(tempratio-1));
    trace4("", tempratio, vt, oldregion, p->_isat);
    if (m->mos_level > 0 || flags & 0040) { // Spice style limiting
      double vcrit = vt * log(vt / (M_SQRT2 * p->_isat));
      double vold = d->_y1.f0;
      if((volts > vcrit) && (std::abs(volts - vold) > (vt + vt))) {
        if(vold > 0) {
          double arg = 1 + (volts - vold) / vt;
          if(arg > 0) {
            volts = vold + vt * log(arg);
          }else{
            volts = vcrit;
          }
        }else{
          volts = vt *log(volts/vt);
        }
      }else{
        // leave volts as is
      }
    }
    if (m->mos_level > 0) {
      switch (m->mos_level) {
      case 1:
      case 2:
      case 3:
      case 6:
      case 4:
      case 5:
        if (volts <= 0.) {
          p->_region = REVERSE;
          y.f1 = p->_isat / vt + OPT::gmin;
          y.f0 = y.f1 * volts;
        }else{
          p->_region = FORWARD;
          double ev = exp(volts/vt);
          y.f1 = p->_isat * ev / vt + OPT::gmin;
          y.f0 = p->_isat * (ev - 1) + OPT::gmin * volts;
        }
        break;
      case 7:
      case 8:
        if (volts < .5) {
          p->_region = REVERSE;
          double ev = exp(volts/vt);
          y.f1 = p->_isat * ev / vt + OPT::gmin;
          y.f0 = p->_isat * (ev - 1) + OPT::gmin * volts;
        }else{
          p->_region = FORWARD;
          double ev = exp(.5/vt);
          double t0 = p->_isat * ev / vt;
          y.f1 = t0 + OPT::gmin;
          y.f0 = p->_isat * (ev - 1) + t0 * (volts - .5) + OPT::gmin * volts;
        }
        break;
      default:
        unreachable();
        y.f1 = OPT::gmin;
        y.f0 = volts * y.f1;
      }
    }else if (flags & 0040) { // exact Spice model
      if (volts >= -3*vt) { // forward and weak reversed
        double evd = exp(volts/vt);
        y.f0 = p->_isat * (evd-1);
        y.f1 = p->_isat * evd/vt;
      }else if (has_good_value(m->bv) || volts >= m->bv) {
        double arg = 3 * vt / (volts * M_E); // strong reversed
        arg = arg * arg * arg;
        y.f0 = -p->_isat * (1+arg);
        y.f1 = p->_isat * 3 * arg / volts;
      }else{
        incomplete();
        double evrev = exp(-(m->bv+volts)/vt);
        y.f0 = -p->_isat * evrev;
        y.f1 = p->_isat * evrev / vt;
      }
      y.f0 += OPT::gmin * volts;
      y.f1 += OPT::gmin;
    }else{
       if (c->off  &&  d->_sim->is_initial_step()) { /*initially guess off*/
        p->_region = INITOFF;
        y.f1 = 0.;
        y.f0 = 0.;
        if (flags & 0020) {
          untested();
          y.f1 = OPT::gmin;
        }
        trace2("initoff", y.f0, y.f1);
      }else if (volts <= 0. /* &&  amps < 0.*/) {         /* reverse biased */
        p->_region = REVERSE;                     /* x = volts, f(x) = amps */
        if (flags & 0010) {
          untested();
          y.f1 = y.f0 = 0.;
        }else{
          double expterm = p->_isat * exp(volts/vt);
          y.f0 = expterm - p->_isat;/* i = f(x) = _isat * (exp(volts/vt)-1) */
          y.f1 = expterm / vt;      /* f'(x) = (_isat/vt) * exp(volts/vt)   */
        }
        if (flags & 0002) {     // g = gmin, maintain actual current
          y.f1 += OPT::gmin;    // 3 is a resistor, R=1/gmin
          y.f0 += OPT::gmin * volts;
        }
        if (flags & 0004) {     // 5 is a resistor, R=vt/_isat
          double x = p->_isat / vt;
          y.f1 += x;
          y.f0 += x * volts;
        }
        if (flags & 0001) {
          //y.f0 = y.f1 * volts;        // a resistor, R=1/f1
        }
        trace2("reverse", y.f0, y.f1);
      }else if (volts >= 0.  &&  amps >= 0.) {            /* forward biased */
                                    /* x = amps, f(x) = volts */
        /* derivation: */           /* if f(x) = log(u): f'(x)=(1/u)(du/dx) */
        /* poly1 r; */
        /* r.f0 = vt * log(amps/p->_isat +1.); */
        /* r.f1 = vt / (_isat + amps); */
        /* y.f1 = 1. / r.f1; */
        /* y.f0 = amps - r.f0*y.f1 + volts*y.f1; */
        p->_region = FORWARD;
        y.f1 = (p->_isat + amps) / vt;
        y.f0 = amps - log(amps/p->_isat +1.)*(p->_isat + amps) + volts*y.f1;
        trace2("forward", y.f0, y.f1);
      }else{                        /* non-converged, inconsistent          */
        p->_region = UNKNOWN;       /* volts and amps have different signs  */
        y.f1 = p->_isat/vt;         /* guess that the voltage should be 0   */
        y.f0 = 0.;                  /* (it usually is very close)           */
        if (flags & 0001) {         /* use the correct value there          */
          y.f0 = volts * y.f1;
        }
        trace2("unknown", y.f0, y.f1);
      }
      y.f1 += c->gparallel_adjusted;
      y.f0 += c->gparallel_adjusted * volts;
      if (oldregion != p->_region  &&  OPT::dampstrategy & dsDEVLIMIT) {
        d->_sim->_fulldamp = true;
        error(bTRACE, p->long_label() + ":device limit damp\n");
      }
      if (flags & 0100) {               // twist g to guarantee g >= gmin
        if (y.f1 < OPT::gmin) { // without changing i
          y.f1 = OPT::gmin;
          untested();
        }else{
          untested();
        }
      }
      if (flags & 0200) {               // add a gmin in parallel
        y.f1 += OPT::gmin;
        y.f0 += OPT::gmin * volts;
        untested();
      }
      if (flags & 0400) {               // linearize .. shift I to pass thru 0
        untested();
        y.f0 = y.f1 * volts;
      }
    }
    trace3(d->long_label().c_str(), y.x, y.f0, y.f1);
    p->_gd = y.f1;
}
The documentation for this class was generated from the following files:
savant/gnucap/src/d_diode.h
savant/gnucap/src/d_diode.cc