gnucap: List< T > Class Template Reference
List< T > Class Template Reference
#include <m_base.h>
Public Member Functions
void parse (CS &f)
Protected Member Functions
List ()
Detailed Description
template<class T>
class List< T >
Definition at line 123 of file m_base.h.
Constructor & Destructor Documentation
template<class T > List< T >::List () [inline, explicit, protected]
Definition at line 127 of file m_base.h.
References untested.
{untested();}
Member Function Documentation
template<class T > void List< T >::parse (CS & f) [virtual]
Implements List_Base< T >.
Definition at line 323 of file m_base.h.
References CS::cursor(), CS::match1(), CS::stuck(), untested, and CS::warn().
{untested();
  //skip_comment(File);
  unsigned here = File.cursor();
  for (;;) {untested();
    if (File.match1('[')) {untested();
      break;
    }else{untested();
      T* x = new T(File);
      if (!File.stuck(&here)) {untested();
        push(x);
      }else{untested();
        delete x;
        File.warn(0, "what's this? (List)");
        break;
      }
      //skip_comment(File);
    }
  }
}
The documentation for this class was generated from the following file:
savant/gnucap/src/m_base.h