gnucap: anonymous_namespace{d_ccvs.cc}::DEV_CCVS Class Reference
anonymous_namespace{d_ccvs.cc}::DEV_CCVS Class Reference
Public Member Functions
DEV_CCVS ()
Private Member Functions
DEV_CCVS (const DEV_CCVS &p)
char id_letter () const
std::string value_name () const
std::string dev_type () const
bool use_obsolete_callback_parse () const
CARD * clone () const
void precalc_last ()
void tr_iwant_matrix ()
void tr_begin ()
bool do_tr ()
bool do_tr_last ()
void tr_load ()
void ac_iwant_matrix ()
void ac_begin ()
void do_ac ()
void ac_load ()
COMPLEX ac_amps () const
std::string port_name (int i) const
std::string current_port_name (int i) const
Detailed Description
Definition at line 31 of file d_ccvs.cc.
Constructor & Destructor Documentation
anonymous_namespace{d_ccvs.cc}::DEV_CCVS::DEV_CCVS (const DEV_CCVS & p) [inline, explicit, private]
Definition at line 33 of file d_ccvs.cc.
:CCSRC_BASE(p) {}
anonymous_namespace{d_ccvs.cc}::DEV_CCVS::DEV_CCVS () [inline, explicit]
Definition at line 35 of file d_ccvs.cc.
:CCSRC_BASE() {}
Member Function Documentation
COMPLEX anonymous_namespace{d_ccvs.cc}::DEV_CCVS::ac_amps () const [inline, private, virtual]
Reimplemented from ELEMENT.
Definition at line 52 of file d_ccvs.cc.
References ELEMENT::ac_amps(), and untested.
{untested(); return ELEMENT::ac_amps();}
void anonymous_namespace{d_ccvs.cc}::DEV_CCVS::ac_begin () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 49 of file d_ccvs.cc.
References OPT::shortckt.
{_loss1=_loss0=1./OPT::shortckt; _ev = _y[0].f1;}
void anonymous_namespace{d_ccvs.cc}::DEV_CCVS::ac_iwant_matrix () [inline, private, virtual]
Implements ELEMENT.
Definition at line 48 of file d_ccvs.cc.
{ac_iwant_matrix_extended();}
void anonymous_namespace{d_ccvs.cc}::DEV_CCVS::ac_load () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 51 of file d_ccvs.cc.
{ac_load_active();}
CARD* anonymous_namespace{d_ccvs.cc}::DEV_CCVS::clone () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 41 of file d_ccvs.cc.
{return new DEV_CCVS(*this);}
std::string anonymous_namespace{d_ccvs.cc}::DEV_CCVS::current_port_name (int i) const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 60 of file d_ccvs.cc.
References untested.
                                          {untested();
    assert(i >= 0);
    assert(i < 1);
    static std::string names[] = {"in"};
    return names[i];
  }
std::string anonymous_namespace{d_ccvs.cc}::DEV_CCVS::dev_type () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 39 of file d_ccvs.cc.
{return "ccvs";}
void anonymous_namespace{d_ccvs.cc}::DEV_CCVS::do_ac () [private, virtual]
Reimplemented from CARD.
Definition at line 114 of file d_ccvs.cc.
References CARD::do_ac(), unreachable, and untested.
{
  assert(_input);
  if (!_input->evaluated()) {untested();
    ELEMENT* input = const_cast<ELEMENT*>(_input);
    input->do_ac();         //BUG// premature load of sense element
  }else{
  }
  ac_load_shunt();
  if (using_ac_eval()) {untested();
    ac_eval();
  }else{
    assert(_ev == _y[0].f1);
    assert(has_tr_eval() || _ev == double(value()));
  }
  if (_input->is_source()) {
    _acg = -_loss0 * _ev * _input->_acg;
    ac_load_source();
    _acg = -_loss0 * _ev * _input->_loss0;
  }else if (_input->has_inode()) {untested();
    _acg = -_loss0 * _ev;
  }else if (_input->has_iv_probe()) {
    _acg = -_loss0 * _ev * _input->_acg;
  }else{unreachable();
  }
}
bool anonymous_namespace{d_ccvs.cc}::DEV_CCVS::do_tr () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 45 of file d_ccvs.cc.
{_sim->_late_evalq.push_back(this); return true;}
bool anonymous_namespace{d_ccvs.cc}::DEV_CCVS::do_tr_last () [private, virtual]
Reimplemented from CARD.
Definition at line 86 of file d_ccvs.cc.
References converged, LINEAR, unreachable, and untested.
{
  assert(_input);
  if (using_tr_eval()) {
    _m0.x = tr_involts_limited();
    _y[0].x = tr_input_limited();
    tr_eval();
    assert(_y[0].f0 != LINEAR);
    _m0 = CPOLY1(_y[0]);
  }else{
    assert(_y[0].f0 == LINEAR);
    assert(_y[0].f1 == value());
    _m0.c0 = 0.;
    assert(converged());
  }
  if (_input->has_inode()) {untested();
    // nothing
  }else if (_input->has_iv_probe()) {
    _m0.c0 += _y[0].f1 * _input->_m0.c0;
    _m0.c1  = _y[0].f1 * (_input->_loss0 + _input->_m0.c1);
  }else{unreachable();
  }
  _m0 *= -_loss0;
  store_values();
  q_load();
  return converged();
}
char anonymous_namespace{d_ccvs.cc}::DEV_CCVS::id_letter () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 37 of file d_ccvs.cc.
{return 'H';}
std::string anonymous_namespace{d_ccvs.cc}::DEV_CCVS::port_name (int i) const [inline, private, virtual]
Implements COMPONENT.
Definition at line 54 of file d_ccvs.cc.
References untested.
                                  {untested();
    assert(i >= 0);
    assert(i < 2);
    static std::string names[] = {"p", "n"};
    return names[i];
  }
void anonymous_namespace{d_ccvs.cc}::DEV_CCVS::precalc_last () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 69 of file d_ccvs.cc.
References ELEMENT::precalc_last().
{
  CCSRC_BASE::precalc_last();
  set_converged();
  assert(!is_constant()); /* because of incomplete analysis */
}
void anonymous_namespace{d_ccvs.cc}::DEV_CCVS::tr_begin () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 76 of file d_ccvs.cc.
References OPT::shortckt, and ELEMENT::tr_begin().
{
  CCSRC_BASE::tr_begin();
  _loss1 = _loss0 = 1./OPT::shortckt;
  _m0.x  = _y[0].x;
  _m0.c1 = -_loss0 * value();
  _m0.c0 = 0.;
  _m1 = _m0;
}
void anonymous_namespace{d_ccvs.cc}::DEV_CCVS::tr_iwant_matrix () [inline, private, virtual]
Implements ELEMENT.
Definition at line 43 of file d_ccvs.cc.
{tr_iwant_matrix_extended();}
void anonymous_namespace{d_ccvs.cc}::DEV_CCVS::tr_load () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 47 of file d_ccvs.cc.
{tr_load_shunt(); tr_load_active();}
bool anonymous_namespace{d_ccvs.cc}::DEV_CCVS::use_obsolete_callback_parse () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 40 of file d_ccvs.cc.
{return true;}
std::string anonymous_namespace{d_ccvs.cc}::DEV_CCVS::value_name () const [inline, private, virtual]
Implements CARD.
Definition at line 38 of file d_ccvs.cc.
References untested.
{untested(); return "gain";}
The documentation for this class was generated from the following file:
savant/gnucap/src/d_ccvs.cc