gnucap: savant/gnucap/src/l_trim.cc File Reference
savant/gnucap/src/l_trim.cc File Reference
#include <cstring>
#include <cctype>
Functions
char * trim (char *)
Function Documentation
char* trim (char * string)
Definition at line 30 of file l_trim.cc.
Referenced by ftos(), getcmd(), getlines(), and xopen().
{
  size_t idx = strlen(string);
  while (idx > 0  &&  !isgraph(string[--idx])) {
    string[idx] = '\0' ;
  }
  return string;
}