gnucap: anonymous_namespace{lang_geda.cc} Namespace Reference
anonymous_namespace{lang_geda.cc} Namespace Reference
Classes
class LANG_GEDA
class CMD_GSCHEM
class CMD_C
Functions
DISPATCHER< LANGUAGE >::INSTALL d & language_dispatcher (),&lang_geda
static void parse_type (CS &cmd, CARD *x)
static std::string * parse_pin (CS &cmd, COMPONENT *x, int index, bool ismodel)
static std::string find_file_given_name (std::string basename)
static std::vector< std::string * > parse_symbol_file (COMPONENT *x, std::string basename)
static void parse_place (CS &cmd, COMPONENT *x)
static void create_place (std::string cmdstr, COMPONENT *x)
static std::string findplacewithsameposition (COMPONENT *x, std::string xco, std::string yco)
static std::string * findnodeonthisnet (CARD *x, std::string x0, std::string y0, std::string x1, std::string y1)
static void parse_net (CS &cmd, COMPONENT *x)
static void parse_component (CS &cmd, COMPONENT *x)
static void print_type (OMSTREAM &o, const COMPONENT *x)
static void print_label (OMSTREAM &o, const COMPONENT *x)
static void print_node_xy (OMSTREAM &o, const COMPONENT *x, int _portindex)
static std::string findcomponentposition (std::string *absxy, std::string *pinxy, std::string angle, std::string mirror)
static std::string * find_place (const COMPONENT *x, std::string _portvalue)
static void print_net (OMSTREAM &o, const COMPONENT *x)
static void print_component (OMSTREAM &o, const COMPONENT *x)
Variables
anonymous_namespace{lang_geda.cc}::LANG_GEDA lang_geda
anonymous_namespace{lang_geda.cc}::CMD_GSCHEM p8
DISPATCHER< CMD >::INSTALL d8 & command_dispatcher
anonymous_namespace{lang_geda.cc}::CMD_C p2
Function Documentation
static void anonymous_namespace{lang_geda.cc}::create_place (std::string cmdstr, COMPONENT * x) [static]
Definition at line 245 of file lang_geda.cc.
References CS::_STRING, OPT::language, LANGUAGE::new__instance(), and CARD::scope().
Referenced by parse_component(), and parse_net().
{
    CS place_cmd(CS::_STRING,cmdstr);
    OPT::language->new__instance(place_cmd,NULL,x->scope());
}
static std::string anonymous_namespace{lang_geda.cc}::find_file_given_name (std::string basename) [static]
Definition at line 166 of file lang_geda.cc.
References anonymous_namespace{c_genrat.cc}::p.
Referenced by parse_symbol_file().
{
#ifdef HAVE_GEDA
    const char* geda = s_path_sys_data();
#else
    const char* geda = GEDA_DATA;
#endif
    char gedasym[5+strlen(geda)];
    sprintf(gedasym, "%s/sym", geda);
    char *p[] = {gedasym,NULL};
    FTS* dir=fts_open(p,FTS_NOCHDIR, NULL);
    if(!dir){
        std::cout<<"Not opened\n";
        return "";
    }
    assert(dir);
    FTSENT* node;
    std::string dirname="";
    while(node=fts_read(dir)){
        if(node->fts_info & FTS_F && basename==node->fts_name){
            dirname=node->fts_path;
        }
    }
    if(dirname==""){
        std::cout<<"No symbol file for "+basename<<std::endl;
    }
    return dirname;
}
static std::string* anonymous_namespace{lang_geda.cc}::find_place (const COMPONENT * x, std::string _portvalue) [static]
Definition at line 754 of file lang_geda.cc.
References CARD_LIST::begin(), CARD_LIST::end(), CARD::scope(), and trace0.
Referenced by print_component().
{
    for(CARD_LIST::const_iterator ci=x->scope()->begin(); ci!=x->scope()->end(); ++ci) {
        if((*ci)->dev_type()=="place"){
            if(static_cast<COMPONENT*>(*ci)->port_value(0)==_portvalue){
                trace0("Got the coord");
                std::string*  a= new std::string[2];
                a[0]=(*ci)->param_value(1);
                a[1]=(*ci)->param_value(0);
                trace0("Got out of find_place");
                return a;
            }
        }
    }
    return NULL;
    //To return place coordinates after searching for it.
}
static std::string anonymous_namespace{lang_geda.cc}::findcomponentposition (std::string * absxy, std::string * pinxy, std::string angle, std::string mirror) [static]
Definition at line 704 of file lang_geda.cc.
Referenced by print_component().
{
    char newx[10];
    char newy[10];
    if(mirror=="0"){
        switch(atoi(angle.c_str())){
        case 0:
            sprintf(newx,"%d",atoi(absxy[0].c_str())-atoi(pinxy[0].c_str()));
            sprintf(newy,"%d",atoi(absxy[1].c_str())-atoi(pinxy[1].c_str()));
            break;
        case 90:
            sprintf(newx,"%d",atoi(absxy[0].c_str())+atoi(pinxy[1].c_str()));
            sprintf(newy,"%d",atoi(absxy[1].c_str())-atoi(pinxy[0].c_str()));
            break;
        case 180:
            sprintf(newx,"%d",atoi(absxy[0].c_str())+atoi(pinxy[0].c_str()));
            sprintf(newy,"%d",atoi(absxy[1].c_str())+atoi(pinxy[1].c_str()));
            break;
        case 270:
            sprintf(newx,"%d",atoi(absxy[0].c_str())-atoi(pinxy[1].c_str()));
            sprintf(newy,"%d",atoi(absxy[1].c_str())+atoi(pinxy[0].c_str()));
            break;
        }
    }else if(mirror=="1"){
        switch(atoi(angle.c_str())){
        case 0:
            sprintf(newx,"%d",atoi(absxy[0].c_str())+atoi(pinxy[0].c_str()));
            sprintf(newy,"%d",atoi(absxy[1].c_str())-atoi(pinxy[1].c_str()));
            break;
        case 90:
            sprintf(newx,"%d",atoi(absxy[0].c_str())+atoi(pinxy[1].c_str()));
            sprintf(newy,"%d",atoi(absxy[1].c_str())+atoi(pinxy[0].c_str()));
            break;
        case 180:
            sprintf(newx,"%d",atoi(absxy[0].c_str())-atoi(pinxy[0].c_str()));
            sprintf(newy,"%d",atoi(absxy[1].c_str())+atoi(pinxy[1].c_str()));
            break;
        case 270:
            sprintf(newx,"%d",atoi(absxy[0].c_str())-atoi(pinxy[1].c_str()));
            sprintf(newy,"%d",atoi(absxy[1].c_str())-atoi(pinxy[0].c_str()));
            break;
        }
    }else{
    //not correct mirror!
    }
    std::string sx=newx;
    std::string sy=newy;
    return sx+" "+sy;
}
static std::string* anonymous_namespace{lang_geda.cc}::findnodeonthisnet (CARD * x, std::string x0, std::string y0, std::string x1, std::string y1) [static]
Definition at line 263 of file lang_geda.cc.
References CARD_LIST::begin(), CARD_LIST::end(), CARD::scope(), and trace0.
Referenced by parse_net().
{
    for(CARD_LIST::const_iterator ci = x->scope()->begin(); ci != x->scope()->end(); ++ci) {
        if((*ci)->dev_type()=="place"){
            std::string _x=(*ci)->param_value(1),_y=(*ci)->param_value(0);
            if (y0==y1){
                if(  ( ( (atoi(x1.c_str()) < atoi(_x.c_str())) and (atoi(_x.c_str())<atoi(x0.c_str())) ) || ( (atoi(x0.c_str()) < atoi(_x.c_str())) and (atoi(_x.c_str())<atoi(x1.c_str())) ) ) and _y==y0 and _x!=x0 and _x!=x1){
                    trace0("true0");
                    std::string* coord=new std::string[2];
                    coord[0]=_x;
                    coord[1]=_y;
                    return coord;
                }
                else{
                    return NULL;
                }
            }else if (x0==x1){
                if(  ( ( (atoi(y1.c_str()) < atoi(_y.c_str())) and (atoi(_y.c_str())<atoi(y0.c_str())) ) || ( (atoi(y0.c_str()) < atoi(_y.c_str())) and (atoi(_y.c_str())<atoi(y1.c_str())) ) ) and _x==x0 and _y!=y0 and _y!=y1){
                    trace0("true1");
                    std::string* coord=new std::string[2];
                    coord[0]=_x;
                    coord[1]=_y;
                    return coord;
                }else{
                    return NULL;
                }
            }
            else{
                return NULL;
            }
        }
    }
}
static std::string anonymous_namespace{lang_geda.cc}::findplacewithsameposition (COMPONENT * x, std::string xco, std::string yco) [static]
Definition at line 251 of file lang_geda.cc.
References CARD_LIST::begin(), CARD_LIST::end(), COMPONENT::port_value(), and CARD::scope().
Referenced by parse_component(), and parse_net().
{
    for (CARD_LIST::const_iterator ci = x->scope()->begin(); ci != x->scope()->end(); ++ci) {
        if((*ci)->dev_type()=="place"){
            if(xco==(*ci)->param_value(1) && yco==(*ci)->param_value(0)){
                return static_cast<COMPONENT*>(*ci)->port_value(0);
            }
        }
    }
    return "";
}
DISPATCHER<LANGUAGE>::INSTALL d& anonymous_namespace{lang_geda.cc}::language_dispatcher ()
static void anonymous_namespace{lang_geda.cc}::parse_component (CS & cmd, COMPONENT * x) [static]
Definition at line 389 of file lang_geda.cc.
References anonymous_namespace{lang_geda.cc}::LANG_GEDA::_componentmod, anonymous_namespace{lang_geda.cc}::LANG_GEDA::_gotaline, create_place(), CS::ctos(), anonymous_namespace{lang_geda.cc}::LANG_GEDA::find_type_in_string(), findplacewithsameposition(), CS::fullstring(), CS::get_line(), lang_geda, parse_symbol_file(), CS::reset(), COMPONENT::set_dev_type(), CKT_BASE::set_label(), COMPONENT::set_param_by_name(), COMPONENT::set_port_by_index(), CKT_BASE::short_label(), to_string(), and trace0.
Referenced by anonymous_namespace{lang_geda.cc}::LANG_GEDA::parse_instance().
{
    trace0("got into parse_component");
    assert(x);
    std::string component_x, component_y, mirror, angle, dump,basename;
    std::string type=lang_geda.find_type_in_string(cmd);
    cmd >> type;
    cmd>>component_x>>" ">>component_y>>" ">>dump>>" ">>angle>>" ">>mirror>>" ">>basename;
    //To get port names and values from symbol?
    //Then set params below
    //Search for the file name
    std::vector<std::string*> coordinates=parse_symbol_file(x,basename);
    char    newx[10],newy[10];
    int index=0;
    for (std::vector<std::string*>::const_iterator i=coordinates.begin();i<coordinates.end();++i){
        //to do integer casting, addition and then reconverting to string
        if(mirror=="0"){
            switch(atoi(angle.c_str())){
            case 0:
                sprintf(newx,"%d",atoi(component_x.c_str())+atoi((*i)[0].c_str()));
                sprintf(newy,"%d",atoi(component_y.c_str())+atoi((*i)[1].c_str()));
                break;
            case 90:
                sprintf(newx,"%d",atoi(component_x.c_str())-atoi((*i)[1].c_str()));
                sprintf(newy,"%d",atoi(component_y.c_str())+atoi((*i)[0].c_str()));
                break;
            case 180:
                sprintf(newx,"%d",atoi(component_x.c_str())-atoi((*i)[0].c_str()));
                sprintf(newy,"%d",atoi(component_y.c_str())-atoi((*i)[1].c_str()));
                break;
            case 270:
                sprintf(newx,"%d",atoi(component_x.c_str())+atoi((*i)[1].c_str()));
                sprintf(newy,"%d",atoi(component_y.c_str())-atoi((*i)[0].c_str()));
                break;
            }
        }else if(mirror=="1"){
            switch(atoi(angle.c_str())){
            case 0:
                sprintf(newx,"%d",atoi(component_x.c_str())-atoi((*i)[0].c_str()));
                sprintf(newy,"%d",atoi(component_y.c_str())+atoi((*i)[1].c_str()));
                break;
            case 90:
                sprintf(newx,"%d",atoi(component_x.c_str())-atoi((*i)[1].c_str()));
                sprintf(newy,"%d",atoi(component_y.c_str())-atoi((*i)[0].c_str()));
                break;
            case 180:
                sprintf(newx,"%d",atoi(component_x.c_str())+atoi((*i)[0].c_str()));
                sprintf(newy,"%d",atoi(component_y.c_str())-atoi((*i)[1].c_str()));
                break;
            case 270:
                sprintf(newx,"%d",atoi(component_x.c_str())+atoi((*i)[1].c_str()));
                sprintf(newy,"%d",atoi(component_y.c_str())+atoi((*i)[0].c_str()));
                break;
            }
        }else{
        //not correct mirror!
        }
        //delete (*i);
        //setting new place devices for each node searching for .
        //new__instance(cmd,NULL,Scope); //cmd : can create. Scope? how to get Scope? Yes!
        std::string _portvalue=findplacewithsameposition(x,newx,newy);
        if (_portvalue==""){
            _portvalue="node_"+to_string(rand()%10000);
            create_place("place "+_portvalue+" "+newx+" "+newy,x);
        }
        x->set_port_by_index(index,_portvalue);
        ++index;
    }
    x->set_param_by_name("basename",basename);
    trace0("getting line");
    try{
        cmd.get_line("gnucap-geda>");
    }catch(Exception_End_Of_Input&){
        return;
    }
    trace0("got line");
    std::string temp=(cmd.fullstring()).substr(0,1);
    if(temp!="{"){
        trace0("no {");
        cmd.reset();
        lang_geda._componentmod=true;
        lang_geda._gotaline=true;
        //OPT::language->new__instance(cmd,NULL,x->scope());
        return;
    }
    cmd>>"{";
    trace0("got {");
    for (;;) {
        cmd.get_line("gnucap-geda-"+basename+">");
        if (cmd >> "}") {
            break;
        }else{
            if(cmd>>"T"){
                cmd>>dump;
            }
            else {
                std::string _paramname=cmd.ctos("=","",""),_paramvalue;
                cmd>>"=">>_paramvalue;
                trace0("got the parameter");
                if(_paramname=="device"){
                    x->set_dev_type(_paramvalue);
                }else if (_paramname=="refdes" && _paramvalue!="?"){
                    x->set_label(_paramvalue);
                }else{
                    x->set_param_by_name(_paramname,_paramvalue);
                }
            }
        }
    }
    if(x->short_label()==""){
        x->set_label(basename+to_string(rand()));
    }
    lang_geda._componentmod=true;
    trace0("got out of parse_component");
}
static void anonymous_namespace{lang_geda.cc}::parse_net (CS & cmd, COMPONENT * x) [static]
Definition at line 302 of file lang_geda.cc.
References anonymous_namespace{lang_geda.cc}::LANG_GEDA::_gotaline, CS::_STRING, create_place(), CS::cursor(), anonymous_namespace{lang_geda.cc}::LANG_GEDA::find_type_in_string(), findnodeonthisnet(), findplacewithsameposition(), lang_geda, OPT::language, CARD::long_label(), LANGUAGE::new__instance(), CARD::scope(), CKT_BASE::set_label(), COMPONENT::set_param_by_name(), COMPONENT::set_port_by_index(), to_string(), and trace0.
Referenced by anonymous_namespace{lang_geda.cc}::LANG_GEDA::parse_instance().
{
    trace0("got into parse_net");
    assert(x);
    assert(lang_geda.find_type_in_string(cmd)=="net");
    cmd>>"N";     //Got N
    unsigned here=cmd.cursor();
    // x0 y0 x1 y1 color
    std::string parsedvalue[5];
    int i=0;
    bool gotthenet=true;
    while (i<5) {
        if (cmd.is_alnum()){
            cmd>>" ">>parsedvalue[i];
        }else{
            gotthenet=false;
            cmd.warn(bDANGER, here, x->long_label() +": Not correct format for net");
            break;
        }
        ++i;
    }
    if (gotthenet){
        //lang_geda.nets.push_back(x);
        //To check if any of the previous nodes have same placement.
        x->set_param_by_name("color",parsedvalue[4]);
        x->set_label("net"+to_string(rand()%10000)); //BUG : names may coincide!. Doesn't matter? Or try some initialisation method. (latch like digital)
        std::string _portvalue=findplacewithsameposition(x,parsedvalue[0],parsedvalue[1]);
        if(_portvalue==""){
            _portvalue="node"+to_string(rand()%10000);
            create_place("place "+_portvalue+" "+parsedvalue[0]+" "+parsedvalue[1],x);
        }
        x->set_port_by_index(0,_portvalue);
        _portvalue=findplacewithsameposition(x,parsedvalue[2],parsedvalue[3]);
        if(_portvalue==""){
            _portvalue="node"+to_string(rand()%10000);
            create_place("place "+_portvalue+" "+parsedvalue[2]+" "+parsedvalue[3],x);
        }
        x->set_port_by_index(1,_portvalue);
        std::string* nodeonthisnet=findnodeonthisnet(x,parsedvalue[0],parsedvalue[1],parsedvalue[2],parsedvalue[3]);
        if (!nodeonthisnet)
        {
        }else{
            //create new net from nodeonthisnet to one of edges of net.
            std::string netcmdstr="N "+parsedvalue[0]+" "+parsedvalue[1]+" "+nodeonthisnet[0]+" "+nodeonthisnet[1]+" 5";
            CS net_cmd(CS::_STRING,netcmdstr);
            OPT::language->new__instance(net_cmd,NULL,x->scope());
        }
        //To check if there are any attributes
        try {
            cmd.get_line("gnucap-geda>");
        }catch(Exception_End_Of_Input&){
            return;
        }
        std::string temp=(cmd.fullstring()).substr(0,1);
        std::string _paramvalue,_paramname,dump;
        if(temp!="{"){
            cmd.reset();
            lang_geda._gotaline=true;
            //OPT::language->new__instance(cmd,NULL,x->scope());
            return;
        }
        cmd>>"{";
        for (;;) {
            cmd.get_line("gnucap-geda-net>");
            if (cmd >> "}") {
                break;
            }else{
                if(cmd>>"T"){
                    cmd>>dump;
                }
                else {
                    std::string _paramname=cmd.ctos("=","",""),_paramvalue;
                    cmd>>"=">>_paramvalue;
                    if (_paramname=="netname" && _paramvalue!="?"){
                        x->set_label(_paramvalue);
                    }else{
                        x->set_param_by_name(_paramname,_paramvalue);
                    }
                }
            }
        }
    }
}
static std::string* anonymous_namespace{lang_geda.cc}::parse_pin (CS & cmd, COMPONENT * x, int index, bool ismodel) [static]
Definition at line 98 of file lang_geda.cc.
References CS::ctos(), LANGUAGE::find_type_in_string(), CS::fullstring(), CS::get_line(), OPT::language, to_string(), and trace0.
Referenced by parse_symbol_file().
{
    //assert(x); can parse NULL also
    trace0("Got into parse_pin");
    std::string type=OPT::language->find_type_in_string(cmd),dump;
    assert(type=="pin");
    cmd>>"P";
    std::string* coord = new std::string[3];
    if (!ismodel){
        std::string pinattributes[7];
        for(int i=0;i<7;i++){
            cmd>>" ">>pinattributes[i];
        }
        if (pinattributes[6]=="1"){
            coord[0]=pinattributes[2];
            coord[1]=pinattributes[3];
        }else if (pinattributes[6]=="0"){
            coord[0]=pinattributes[0];
            coord[1]=pinattributes[1];
        }
    }
    else{
        cmd>>dump;
    }
    std::string    _portvalue="_";
    try{
        cmd.get_line("");
    }catch(Exception_End_Of_Input&){
        return NULL;
    }
    std::string temp=(cmd.fullstring()).substr(0,1);
    if(temp!="{"){
        if(ismodel and x){
            _portvalue="port"+_portvalue+to_string(rand()%10000);
            x->set_port_by_index(index,_portvalue);
            return NULL;
        }else{
            return coord;
        }
    }
    cmd>>"{";
    for(;;){
        cmd.get_line("");
        if(cmd>>"}"){
            break;
        }else{
            if (cmd>>"T"){
                cmd>>dump;
            }
            else{
                std::string _pname=cmd.ctos("=","",""),_pvalue;
                cmd>>"=">>_pvalue;
                if(_pname=="pinlabel"){
                    _portvalue=_pvalue+_portvalue;
                }else if (_pname=="pintype"){
                    _portvalue=_portvalue+_pvalue;
                }
            }
        }
    }
    if(ismodel and x){
        x->set_port_by_index(index,_portvalue);
        return NULL;
    }else{
        return coord;
    }
}
static void anonymous_namespace{lang_geda.cc}::parse_place (CS & cmd, COMPONENT * x) [static]
Definition at line 232 of file lang_geda.cc.
References OPT::language, COMPONENT::set_param_by_name(), COMPONENT::set_port_by_index(), and trace0.
Referenced by anonymous_namespace{lang_geda.cc}::LANG_GEDA::parse_instance().
{
    trace0("Got into parse_place");
    assert(x);
    assert(OPT::language->find_type_in_string(cmd)=="place");
    cmd>>"place";
    std::string _portname,_x,_y;
    cmd>>" ">>_portname>>" ">>_x>>" ">>_y;
    x->set_param_by_name("x",_x);
    x->set_param_by_name("y",_y);
    x->set_port_by_index(0,_portname);
}
static std::vector<std::string*> anonymous_namespace{lang_geda.cc}::parse_symbol_file (COMPONENT * x, std::string basename) [static]
Definition at line 195 of file lang_geda.cc.
References CS::_INC_FILE, find_file_given_name(), LANGUAGE::find_type_in_string(), CS::get_line(), OPT::language, parse_pin(), and CKT_BASE::short_label().
Referenced by parse_component(), anonymous_namespace{lang_geda.cc}::LANG_GEDA::parse_componmod(), and print_component().
{
    std::string filename=find_file_given_name(basename),dump;
    CS sym_cmd(CS::_INC_FILE, filename);
    //Now parse the sym_cmd which will get lines
    int index=0;
    std::vector<std::string*> coord;
    while(true){
        try{
            sym_cmd.get_line("");
        }catch (Exception_End_Of_Input&){
            break;
        }
        std::string linetype=OPT::language->find_type_in_string(sym_cmd);
        bool ismodel=false;
        if (x){
            if(x->short_label()=="!_"+basename){
                ismodel=true;
            }
        }
        if (linetype=="pin"){
            coord.push_back(parse_pin(sym_cmd,x,index++,ismodel));
        }else if(linetype=="graphical"){
            sym_cmd>>"graphical=";
            std::string value;
            sym_cmd>>value;
            if(value=="1"){
                return coord;
            }
        }else{
            sym_cmd>>dump;
        }
    }
    return coord;
}
static void anonymous_namespace{lang_geda.cc}::parse_type (CS & cmd, CARD * x) [static]
Definition at line 90 of file lang_geda.cc.
References anonymous_namespace{lang_geda.cc}::LANG_GEDA::find_type_in_string(), lang_geda, and CARD::set_dev_type().
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_instance(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_instance(), anonymous_namespace{lang_geda.cc}::LANG_GEDA::parse_instance(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_instance(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_paramset(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_paramset(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_paramset().
{
      assert(x);
      std::string new_type;
      new_type=lang_geda.find_type_in_string(cmd);
      x->set_dev_type(new_type);
}
static void anonymous_namespace{lang_geda.cc}::print_component (OMSTREAM & o, const COMPONENT * x) [static]
Definition at line 794 of file lang_geda.cc.
References CARD::dev_type(), find_place(), findcomponentposition(), COMPONENT::param_count(), COMPONENT::param_name(), COMPONENT::param_value(), parse_symbol_file(), COMPONENT::port_value(), CKT_BASE::short_label(), and trace0.
Referenced by anonymous_namespace{lang_geda.cc}::LANG_GEDA::print_instance().
{
    assert(x);
    trace0("Got into print_component");
    std::string _x,_y,_angle,_mirror;
    o <<  "C ";
    std::string _basename=x->param_value(x->param_count()-1);
    //go through the symbol file and get the relative pin positions
    std::vector<std::string*> coordinates=parse_symbol_file(NULL, _basename);
    std::vector<std::string*> abscoord;
    for(int ii=0; ii<coordinates.size(); ++ii){
        abscoord.push_back(find_place(x,x->port_value(ii)));
    }
    std::string angle[4]={"0","90","180","270"};
    int index=0;
    std::string xy="";
    bool gottheanglemirror=false;
    for(int ii=0; ii<4 ; ++ii){
        if(not gottheanglemirror){
            _mirror="0";
            _angle=angle[ii];
            xy="";
            gottheanglemirror=true;
            for(int pinind=0; pinind<coordinates.size(); ++pinind){
                if (xy==""){
                    xy=findcomponentposition(abscoord[pinind],coordinates[pinind],_angle,_mirror);
                }else if(xy!=findcomponentposition(abscoord[pinind],coordinates[pinind],_angle,_mirror)){
                        gottheanglemirror=false;
                        break;
                }
            }
            if (gottheanglemirror) {
                o << xy << " " << "1" << " " << _angle << " " << _mirror << " " << _basename<< "\n";
            }
            else{
                _mirror="1";
                xy="";
                gottheanglemirror=true;
                for(int pinind=0; pinind<coordinates.size(); ++pinind){
                    if (xy==""){
                        xy=findcomponentposition(abscoord[pinind],coordinates[pinind],_angle,_mirror);
                    }else if(xy!=findcomponentposition(abscoord[pinind],coordinates[pinind],_angle,_mirror)){
                            gottheanglemirror=false;
                            break;
                    }
                }
                if (gottheanglemirror) {
                    o << xy << " " << "1" << " " << _angle << " " << _mirror << " " << _basename<< "\n";
                }
            }
        }
    }
    //map those with the absolute positions of nodes and place the device
    //such that it is in between the nodes.
    //std::vector<std::string*> coord = parse_symbol_file(static_cast<COMPONENT*>(x) , _basename);
    //Got the x and y
    //To print angle mirror etc, to get from the intelligent positioning
    //*To check if there are any attributes at all first
    //    If not return;
    bool _parameters=false;
    bool _label=false;
    bool _devtype=false;
    if(x->short_label()!=""){
        _label=true;
    }
    if(x->param_count()>6){
            _parameters=true;
    }
    if(x->dev_type()!="" and (x->dev_type()).substr(0,2)!="!_"){
        _devtype=true;
    }
    if (_label or _parameters or _devtype){
        o << "{\n";
        if(_devtype){
            o << "T "<< xy << " 5 10 0 1 0 0 1\n";
            o << "device=" << x->dev_type() << "\n";
        }
        if(_label){
            o << "T "<< xy << " 5 10 0 1 0 0 1\n";
            o << "refdes=" << x->short_label() << "\n";
        }
        if(_parameters){
            for(int i=x->param_count()-1; i>=0 ; --i){
                if (!(x->param_value(i)=="NA( 0.)" or x->param_value(i)=="NA( NA)" or x->param_value(i)=="NA( 27.)" or x->param_name(i)=="basename")){
                    o << "T "<< xy << " 5 10 0 1 0 0 1\n";
                    o << x->param_name(i) << "=" << x->param_value(i) << "\n";
                }
            }
        }
    o << "}\n";
    }
}
static void anonymous_namespace{lang_geda.cc}::print_label (OMSTREAM & o, const COMPONENT * x) [static]
Definition at line 685 of file lang_geda.cc.
References CKT_BASE::short_label().
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_instance(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_instance(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_instance().
{
  assert(x);
  o << x->short_label();
}
static void anonymous_namespace{lang_geda.cc}::print_net (OMSTREAM & o, const COMPONENT * x) [static]
Definition at line 772 of file lang_geda.cc.
References CARD::dev_type(), print_node_xy(), PARAMETER< T >::string(), and COMPONENT::value().
Referenced by anonymous_namespace{lang_geda.cc}::LANG_GEDA::print_instance().
{
    assert(x);
    assert(x->dev_type()=="net");
    o << "N ";
    //print_coordinates(node); //Will search through the CARD_LIST to find the node
    //o<< node0x << node1x
    //o<< node1x << node2x
    print_node_xy(o,x,0);
    print_node_xy(o,x,1);
    if(x->value().string()!=""){
        o  << x->value().string()<<"\n"; //The color
    }else{
        o << "4\n";
    }
}
static void anonymous_namespace{lang_geda.cc}::print_node_xy (OMSTREAM & o, const COMPONENT * x, int _portindex) [static]
Definition at line 691 of file lang_geda.cc.
References CARD_LIST::begin(), CARD_LIST::end(), COMPONENT::port_value(), CARD::scope(), and trace0.
Referenced by print_net().
{
    std::string _nodename=x->port_value(_portindex);
    for(CARD_LIST::const_iterator ci=x->scope()->begin(); ci!=x->scope()->end(); ++ci) {
        if((*ci)->dev_type()=="place"){
            if(static_cast<COMPONENT*>(*ci)->port_value(0)==_nodename){
                trace0("Got some place!");
                o << (*ci)->param_value(1) << " " << (*ci)->param_value(0) << " ";
            }
        }
    }
}
static void anonymous_namespace{lang_geda.cc}::print_type (OMSTREAM & o, const COMPONENT * x) [static]
Definition at line 679 of file lang_geda.cc.
References CARD::dev_type().
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_instance(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_instance(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_instance().
{
  assert(x);
  o << x->dev_type();
}
Variable Documentation
DISPATCHER< CMD >::INSTALL d2 & anonymous_namespace{lang_geda.cc}::command_dispatcher
Definition at line 949 of file lang_geda.cc.
anonymous_namespace{lang_geda.cc}::LANG_GEDA anonymous_namespace{lang_geda.cc}::lang_geda
Referenced by anonymous_namespace{lang_geda.cc}::CMD_GSCHEM::do_it(), anonymous_namespace{lang_geda.cc}::CMD_C::do_it(), parse_component(), parse_net(), and parse_type().
anonymous_namespace{lang_geda.cc}::CMD_C anonymous_namespace{lang_geda.cc}::p2
anonymous_namespace{lang_geda.cc}::CMD_GSCHEM anonymous_namespace{lang_geda.cc}::p8