gnucap: anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL Class Reference
anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL Class Reference
Public Member Functions
EVAL_BM_MODEL (int c=0)
~EVAL_BM_MODEL ()
Private Member Functions
EVAL_BM_MODEL (const EVAL_BM_MODEL &p)
bool operator== (const COMMON_COMPONENT &) const
COMMON_COMPONENT * clone () const
void parse_common_obsolete_callback (CS &)
void print_common_obsolete_callback (OMSTREAM &, LANGUAGE *) const
void expand (const COMPONENT *)
COMMON_COMPONENT * deflate ()
void tr_eval (ELEMENT *d) const
void ac_eval (ELEMENT *d) const
std::string name () const
bool ac_too () const
Private Attributes
std::string _arglist
COMMON_COMPONENT * _func
Detailed Description
Definition at line 31 of file bm_model.cc.
Constructor & Destructor Documentation
anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::EVAL_BM_MODEL (const EVAL_BM_MODEL & p) [explicit, private]
Definition at line 60 of file bm_model.cc.
References _func, and COMMON_COMPONENT::attach_common().
  :EVAL_BM_ACTION_BASE(p),
   _arglist(p._arglist),
   _func(0)
{
  attach_common(p._func, &_func);
}
anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::EVAL_BM_MODEL (int c = 0) [explicit]
Definition at line 53 of file bm_model.cc.
  :EVAL_BM_ACTION_BASE(c),
   _arglist(),
   _func(0)
{
}
anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::~EVAL_BM_MODEL () [inline]
Definition at line 38 of file bm_model.cc.
{detach_common(&_func);}
Member Function Documentation
void anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::ac_eval (ELEMENT * d) const [inline, private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 47 of file bm_model.cc.
{assert(_func); _func->ac_eval(d);}
bool anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::ac_too () const [inline, private, virtual]
Implements EVAL_BM_ACTION_BASE.
Definition at line 49 of file bm_model.cc.
{return true;}
COMMON_COMPONENT* anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::clone () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 41 of file bm_model.cc.
{return new EVAL_BM_MODEL(*this);}
COMMON_COMPONENT* anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::deflate () [inline, private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 45 of file bm_model.cc.
References COMMON_COMPONENT::deflate().
{return (_func) ? _func->deflate() : this;}
void anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::expand (const COMPONENT * d) [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 104 of file bm_model.cc.
References _arglist, _func, CS::_STRING, COMMON_COMPONENT::attach_common(), COMMON_COMPONENT::attach_model(), anonymous_namespace{bm_model.cc}::bm_dispatcher, error(), COMMON_COMPONENT::expand(), COMMON_COMPONENT::has_model(), CARD::long_label(), COMMON_COMPONENT::model(), COMMON_COMPONENT::modelname(), MODEL_CARD::new_common(), COMMON_COMPONENT::parse_common_obsolete_callback(), and COMMON_COMPONENT::set_modelname().
{
  EVAL_BM_ACTION_BASE::expand(d);
  // not sure what kind of model it is yet.
  // see what we find.
  COMMON_COMPONENT* c = NULL;
  try {
    attach_model(d);
    assert(has_model());
    c = dynamic_cast<EVAL_BM_ACTION_BASE*>(model()->new_common());
  }catch (Exception& e) {
    error(bTRACE, e.message() + "++++\n");
    assert(!has_model());
    c = bm_dispatcher.clone("eval_bm_value");
  }
  if (!c) {
    throw Exception(d->long_label() + ": model type mismatch");
    //BUG// memory leak
  }else{
  }
  // now we have one
  // link to the real one
  // later, a "deflate" will push it down to proper place.
  c->set_modelname(modelname());
  CS args(CS::_STRING, _arglist);
  c->parse_common_obsolete_callback(args);
  c->expand(d);
  attach_common(c, &_func);
  assert(_func);
}
std::string anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::name () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 48 of file bm_model.cc.
References itested.
{itested();return modelname();}
bool anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::operator== (const COMMON_COMPONENT & x) const [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 68 of file bm_model.cc.
References _arglist, incomplete, anonymous_namespace{c_genrat.cc}::p, and untested.
{
  const EVAL_BM_MODEL* p = dynamic_cast<const EVAL_BM_MODEL*>(&x);
  bool rv = p
    && _arglist == p->_arglist
    && EVAL_BM_ACTION_BASE::operator==(x);
  if (rv) {
    incomplete();
    untested();
  }
  return rv;
}
void anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::parse_common_obsolete_callback (CS & cmd) [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 81 of file bm_model.cc.
References _arglist, _func, CS::ctos(), COMMON_COMPONENT::has_model(), and COMMON_COMPONENT::parse_modelname().
{
  assert(!_func);
  assert(!has_model());
  parse_modelname(cmd);
  _arglist = cmd.ctos("", "(", ")");
  assert(!_func);
}
void anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::print_common_obsolete_callback (OMSTREAM & o, LANGUAGE * lang) const [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 90 of file bm_model.cc.
References _arglist, _func, COMMON_COMPONENT::modelname(), COMMON_COMPONENT::print_common_obsolete_callback(), and untested.
{
  assert(lang);
  if (_func) {
    _func->print_common_obsolete_callback(o, lang);
  }else{
    o << modelname();
    if (_arglist != "") {untested();
      o << "(" << _arglist << ")";
    }else{
    }
  }
}
void anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::tr_eval (ELEMENT * d) const [inline, private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 46 of file bm_model.cc.
{assert(_func); _func->tr_eval(d);}
Member Data Documentation
std::string anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::_arglist [private]
Definition at line 33 of file bm_model.cc.
Referenced by expand(), operator==(), parse_common_obsolete_callback(), and print_common_obsolete_callback().
COMMON_COMPONENT* anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::_func [private]
Definition at line 34 of file bm_model.cc.
Referenced by EVAL_BM_MODEL(), expand(), parse_common_obsolete_callback(), and print_common_obsolete_callback().
The documentation for this class was generated from the following file:
savant/gnucap/src/bm_model.cc