gnucap: anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE Class Reference
anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE Class Reference
Public Member Functions
DEV_INDUCTANCE ()
char id_letter () const
std::string value_name () const
std::string dev_type () const
int max_nodes () const
int min_nodes () const
int net_nodes () const
int int_nodes () const
int matrix_nodes () const
bool has_inode () const
bool has_iv_probe () const
bool use_obsolete_callback_parse () const
CARD * clone () const
void expand ()
void tr_iwant_matrix ()
void tr_begin ()
bool do_tr ()
void tr_load ()
void tr_unload ()
double tr_involts () const
double tr_input () const
double tr_involts_limited () const
double tr_input_limited () const
double tr_amps () const
double tr_probe_num (const std::string &) const
void ac_iwant_matrix ()
void ac_begin ()
void do_ac ()
void ac_load ()
COMPLEX ac_involts () const
COMPLEX ac_amps () const
std::string port_name (int i) const
Public Attributes
bool _c_model
Protected Member Functions
DEV_INDUCTANCE (const DEV_INDUCTANCE &p)
Detailed Description
Definition at line 35 of file d_coil.cc.
Constructor & Destructor Documentation
anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::DEV_INDUCTANCE (const DEV_INDUCTANCE & p) [inline, explicit, protected]
Definition at line 37 of file d_coil.cc.
    :STORAGE(p), _c_model(p._c_model) {}
anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::DEV_INDUCTANCE () [inline, explicit]
Definition at line 40 of file d_coil.cc.
    :STORAGE(), _c_model(false) {}
Member Function Documentation
COMPLEX anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::ac_amps () const [virtual]
Reimplemented from ELEMENT.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 526 of file d_coil.cc.
References ELEMENT::_acg, _c_model, ELEMENT::_loss0, CARD::_n, ac_involts(), IN1, and node_t::vac().
{
  if (!_c_model) {
    return (ac_involts() * _acg);
  }else{
    return  _loss0 * _n[IN1].vac();
  }
}
void anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::ac_begin () [inline, virtual]
Reimplemented from CARD.
Definition at line 69 of file d_coil.cc.
{_loss1 = _loss0 = ((!_c_model) ? 0. : 1.); _ev = _y[0].f1;}
COMPLEX anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::ac_involts () const [inline, virtual]
Implements ELEMENT.
Definition at line 72 of file d_coil.cc.
Referenced by ac_amps().
{return ac_outvolts();}
void anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::ac_iwant_matrix () [virtual]
Implements ELEMENT.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 476 of file d_coil.cc.
References SIM_DATA::_acx, _c_model, CARD::_n, CKT_BASE::_sim, ELEMENT::ac_iwant_matrix_passive(), IN1, INVALID_NODE, BSMATRIX< T >::iwant(), matrix_nodes(), OUT1, and OUT2.
{
  if (!_c_model) {
    ac_iwant_matrix_passive();
  }else{
    assert(matrix_nodes() == 3);
    assert(_n[OUT1].m_() != INVALID_NODE);
    assert(_n[OUT2].m_() != INVALID_NODE);
    assert(_n[IN1].m_() != INVALID_NODE);
    _sim->_acx.iwant(_n[OUT1].m_(),_n[IN1].m_());
    _sim->_acx.iwant(_n[OUT2].m_(),_n[IN1].m_());
  }
}
void anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::ac_load () [virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 511 of file d_coil.cc.
References ELEMENT::_acg, _c_model, CARD::_n, ELEMENT::ac_load_diagonal_point(), ELEMENT::ac_load_inode(), ELEMENT::ac_load_passive(), and IN1.
{
  if (!_c_model) {
    ac_load_passive();
  }else{
    ac_load_inode();
    ac_load_diagonal_point(_n[IN1], _acg);
  }
}
CARD* anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::clone () const [inline, virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 55 of file d_coil.cc.
{return new DEV_INDUCTANCE(*this);}
std::string anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::dev_type () const [inline, virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 45 of file d_coil.cc.
{return "inductor";}
void anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_ac () [virtual]
Reimplemented from CARD.
Definition at line 492 of file d_coil.cc.
References ELEMENT::_acg, _c_model, ELEMENT::_ev, SIM_DATA::_jomega, ELEMENT::_loss0, CKT_BASE::_sim, ELEMENT::_y, ELEMENT::ac_eval(), ELEMENT::has_tr_eval(), OPT::shortckt, untested, ELEMENT::using_ac_eval(), and COMPONENT::value().
{
  if (using_ac_eval()) {
    ac_eval();
  }else{
    assert(_ev == _y[0].f1);
    assert(dynamic_cast<DEV_MUTUAL_L*>(this) || has_tr_eval() || _ev == double(value()));
  }
  if (!_c_model) {
    if (_ev * _sim->_jomega == 0.) {untested();
      _acg = 1. / OPT::shortckt;
    }else{
      _acg = 1. / (_ev * _sim->_jomega);
    }
  }else{
    _acg =  -_loss0 * _loss0 * _ev * _sim->_jomega;
  }
}
bool anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::do_tr () [virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 338 of file d_coil.cc.
References _c_model, STORAGE::_i, ELEMENT::_loss0, ELEMENT::_m0, STORAGE::_method_a, ELEMENT::_time, ELEMENT::_y, FPOLY1::c0(), CPOLY1::c0, FPOLY1::c1(), CPOLY1::c1, ELEMENT::conv_check(), COMPONENT::converged(), differentiate(), error(), FPOLY1::f0, FPOLY1::f1, CARD::long_label(), NOT_VALID, COMPONENT::q_load(), COMPONENT::set_converged(), OPT::shortckt, ELEMENT::store_values(), ELEMENT::tr_eval(), tr_input(), tr_input_limited(), untested, ELEMENT::using_tr_eval(), COMPONENT::value(), FPOLY1::x, and CPOLY1::x.
{
  if (using_tr_eval()) {
    _y[0].x = tr_input_limited(); // _m0.c0 + _m0.c1 * x;
    tr_eval();
    if ((!_c_model) && (_y[0].f1 == 0.)) {untested();
      error(bDANGER, long_label() + ": short circuit,  L = 0\n");
      _y[0].f1 = OPT::shortckt;
      set_converged(conv_check());
    }else{
    }
  }else{
    _y[0].x = tr_input(); // _m0.c0 + _m0.c1 * x;
    assert(_y[0].f1 == value());
    _y[0].f0 = _y[0].x * _y[0].f1;
    assert(converged());
  }
  store_values();
  q_load();
  // i is really voltage ..
  // _i[0].x = current, _i[0].f0 = voltage, _i[0].f1 = ohms
  _i[0] = differentiate(_y, _i, _time, _method_a);
  if (!_c_model) {
    _m0.x = NOT_VALID;
    _m0.c1 = 1 / ((_i[0].c1()==0) ? OPT::shortckt : _i[0].c1());
    _m0.c0 = -_i[0].c0() * _m0.c1;
  }else{
    //_m0 = -CPOLY1(_i[0]);
    _m0.x = NOT_VALID;
    _m0.c1 = -_loss0 * _loss0 * _i[0].c1();
    _m0.c0 =  _loss0 * _loss0 * _i[0].c0();
  }
  return converged();
}
void anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::expand () [virtual]
Reimplemented from COMPONENT.
Definition at line 216 of file d_coil.cc.
References _c_model, CARD::_n, CKT_BASE::_sim, IN1, SIM_DATA::is_first_expand(), CARD::long_label(), node_t::new_model_node(), node_t::set_to_ground(), and untested.
Referenced by anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::expand_last().
{
  STORAGE::expand();
  if (_sim->is_first_expand()) {
    if (!_c_model) {
      _n[IN1].set_to_ground(this);
    }else{
      _n[IN1].new_model_node(long_label() + ".i", this);
    }
  }else{untested();
  }
}
bool anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::has_inode () const [inline, virtual]
Reimplemented from COMPONENT.
Definition at line 52 of file d_coil.cc.
{return _c_model;}
bool anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::has_iv_probe () const [inline, virtual]
Reimplemented from COMPONENT.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 53 of file d_coil.cc.
{return true;}
char anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::id_letter () const [inline, virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 43 of file d_coil.cc.
{return 'L';}
int anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::int_nodes () const [inline, virtual]
Reimplemented from COMPONENT.
Definition at line 49 of file d_coil.cc.
{return (!_c_model) ? 0 : 1;}
int anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::matrix_nodes () const [inline, virtual]
Reimplemented from COMPONENT.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 50 of file d_coil.cc.
Referenced by ac_iwant_matrix(), and tr_iwant_matrix().
{return net_nodes() + int_nodes();}
int anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::max_nodes () const [inline, virtual]
Reimplemented from COMPONENT.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 46 of file d_coil.cc.
{return 2;}
int anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::min_nodes () const [inline, virtual]
Reimplemented from COMPONENT.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 47 of file d_coil.cc.
{return 2;}
int anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::net_nodes () const [inline, virtual]
Reimplemented from COMPONENT.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 48 of file d_coil.cc.
{return 2;}
std::string anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::port_name (int i) const [inline, virtual]
Implements COMPONENT.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 75 of file d_coil.cc.
References itested.
                                  {itested();
    assert(i >= 0);
    assert(i < 2);
    static std::string names[] = {"p", "n"};
    return names[i];
  }
double anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_amps () const [virtual]
Reimplemented from ELEMENT.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 467 of file d_coil.cc.
References _c_model, ELEMENT::_loss0, ELEMENT::_m0, CARD::_n, CPOLY1::c0, CPOLY1::c1, fixzero(), IN1, tr_involts(), and node_t::v0().
{
  if (!_c_model) {
    return fixzero((_m0.c1 * tr_involts() + _m0.c0), _m0.c0);
  }else{
    return _loss0 * _n[IN1].v0();
  }
}
void anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_begin () [virtual]
Reimplemented from STORAGE.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 296 of file d_coil.cc.
References _c_model, ELEMENT::_loss0, and ELEMENT::_loss1.
{
  STORAGE::tr_begin();
  _loss1 = _loss0 = ((!_c_model) ? 0. : 1.);
}
double anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_input () const [virtual]
Reimplemented from ELEMENT.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 449 of file d_coil.cc.
References _c_model, ELEMENT::_m0, CARD::_n, CPOLY1::c0, CPOLY1::c1, IN1, tr_involts(), and node_t::v0().
Referenced by do_tr().
{
  if (!_c_model) {
    return _m0.c0 + _m0.c1 * tr_involts();
  }else{
    return _n[IN1].v0();
  }
}
double anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_input_limited () const [virtual]
Reimplemented from ELEMENT.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 458 of file d_coil.cc.
References _c_model, ELEMENT::_m0, CARD::_n, CPOLY1::c0, CPOLY1::c1, IN1, tr_involts_limited(), and node_t::v0().
Referenced by do_tr().
{
  if (!_c_model) {
    return _m0.c0 + _m0.c1 * tr_involts_limited();
  }else{
    return _n[IN1].v0();
  }
}
double anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_involts () const [inline, virtual]
Implements ELEMENT.
Definition at line 62 of file d_coil.cc.
Referenced by tr_amps(), and tr_input().
{return tr_outvolts();}
double anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_involts_limited () const [inline, virtual]
Implements ELEMENT.
Definition at line 64 of file d_coil.cc.
Referenced by tr_input_limited().
{return tr_outvolts_limited();}
void anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_iwant_matrix () [virtual]
Implements ELEMENT.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 277 of file d_coil.cc.
References SIM_DATA::_aa, _c_model, SIM_DATA::_lu, CARD::_n, CKT_BASE::_sim, IN1, INVALID_NODE, BSMATRIX< T >::iwant(), matrix_nodes(), OUT1, OUT2, and ELEMENT::tr_iwant_matrix_passive().
{
  if (!_c_model) {
    tr_iwant_matrix_passive();
  }else{
    assert(matrix_nodes() == 3);
    assert(_n[OUT1].m_() != INVALID_NODE);
    assert(_n[OUT2].m_() != INVALID_NODE);
    assert(_n[IN1].m_() != INVALID_NODE);
    _sim->_aa.iwant(_n[OUT1].m_(),_n[IN1].m_());
    _sim->_aa.iwant(_n[OUT2].m_(),_n[IN1].m_());
    _sim->_lu.iwant(_n[OUT1].m_(),_n[IN1].m_());
    _sim->_lu.iwant(_n[OUT2].m_(),_n[IN1].m_());
  }
}
void anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_load () [virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 418 of file d_coil.cc.
References _c_model, ELEMENT::_m0, ELEMENT::_m1, CARD::_n, CPOLY1::c0, CPOLY1::c1, IN1, ELEMENT::tr_load_diagonal_point(), ELEMENT::tr_load_inode(), ELEMENT::tr_load_passive(), and ELEMENT::tr_load_source_point().
Referenced by tr_unload().
{
  if (!_c_model) {
    tr_load_passive();
  }else{
    tr_load_inode();
    tr_load_diagonal_point(_n[IN1], &_m0.c1, &_m1.c1);
    tr_load_source_point(_n[IN1], &_m0.c0, &_m1.c0);
  }
}
double anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_probe_num (const std::string & x) const [virtual]
Reimplemented from STORAGE.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 535 of file d_coil.cc.
References ELEMENT::_dt, ELEMENT::_y, FPOLY1::f0, FPOLY1::f1, Umatch(), and untested.
{
  if (Umatch(x, "flux ")) {untested();
    return _y[0].f0;
  }else if (Umatch(x, "ind{uctance} |l ")) {untested();
    return _y[0].f1;
  }else if (Umatch(x, "dldt ")) {untested();
    return (_y[0].f1 - _y[1].f1) / _dt;
  }else if (Umatch(x, "dl ")) {untested();
    return (_y[0].f1 - _y[1].f1);
  }else if (Umatch(x, "dfdt ")) {untested();
    return (_y[0].f0 - _y[1].f0) / _dt;
  }else if (Umatch(x, "dflux ")) {untested();
    return (_y[0].f0 - _y[1].f0);
  }else{
    return STORAGE::tr_probe_num(x);
  }
}
void anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_unload () [virtual]
Reimplemented from CARD.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 437 of file d_coil.cc.
References ELEMENT::_loss0, ELEMENT::_m0, CKT_BASE::_sim, CPOLY1::c0, CPOLY1::c1, SIM_DATA::mark_inc_mode_bad(), tr_load(), and untested.
{untested();
  _loss0 = _m0.c0 = _m0.c1 = 0.;
  _sim->mark_inc_mode_bad();
  tr_load();
}
bool anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::use_obsolete_callback_parse () const [inline, virtual]
Reimplemented from COMPONENT.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 54 of file d_coil.cc.
{return true;}
std::string anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::value_name () const [inline, virtual]
Implements CARD.
Reimplemented in anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L.
Definition at line 44 of file d_coil.cc.
{return "l";}
Member Data Documentation
bool anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::_c_model
Definition at line 82 of file d_coil.cc.
Referenced by ac_amps(), ac_iwant_matrix(), ac_load(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::DEV_MUTUAL_L(), do_ac(), do_tr(), expand(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::expand_first(), tr_amps(), tr_begin(), tr_input(), tr_input_limited(), tr_iwant_matrix(), and tr_load().
The documentation for this class was generated from the following file:
savant/gnucap/src/d_coil.cc