gnucap: savant/gnucap/src/declare.h File Reference
savant/gnucap/src/declare.h File Reference
#include "md.h"
Functions
INTERFACE void fft (COMPLEX *, int, int)
INTERFACE double gen ()
void plottr (double, const PROBELIST &)
int plopen (double, double, const PROBELIST &)
INTERFACE void plclose ()
INTERFACE void plclear ()
Function Documentation
INTERFACE void fft (COMPLEX * , int , int)
Definition at line 28 of file m_fft.cc.
References M_TWO_PI, and untested.
Referenced by anonymous_namespace{s_fo.cc}::FOURIER::foout().
{
  int s = (inv) ? 1 : -1;
  int nxp, nxp2;
  for (nxp=n;  (nxp2=nxp/2) > 0;  nxp=nxp2) {
    double wpwr = M_TWO_PI / nxp;
    for (int m = 0;  m < nxp2;  ++m) {
      double argg = m * wpwr;
      COMPLEX w(cos(argg), s*sin(argg));
      for (int jj1 = m;  jj1+nxp-m <= n;  jj1 += nxp) {
        int jj2 = jj1 + nxp2;
        COMPLEX t = x[jj1] - x[jj2];
        x[jj1] += x[jj2];
        x[jj2] = t * w;
      }
    }
  }
  /* unscramble */
  {
    int i, j;
    for (/*k =*/ i = j = 0;  i < n-1;  ++i) {
      if (i < j) {
        swap(x[i],x[j]);
      }
      int k;
      for (k = n/2;  k <= j;  k /= 2) {
        j -= k;
      }
      j += k;
    }
  }
  /* fix level */
  if (!inv) {
    for (int i = 0;  i < n;  ++i) {
      x[i] /= n;
    }
  }else{
    untested();
  }
}
INTERFACE double gen ()
Definition at line 87 of file c_genrat.cc.
References CKT_BASE::_sim, SIM_DATA::_time0, ampl, delay, DTOR, fall, freq, init_, M_TWO_PI, maxv, minv, offset, period, phaz, rise, untested, and width.
Referenced by TRANSIENT::sweep().
{
  if (CKT_BASE::_sim->_time0 <= delay) {
    return init_;
  }
  double loctime = CKT_BASE::_sim->_time0 - delay;
  if (period > 0.) {
    untested();
    loctime = fmod(loctime, period);
  }
  double level;
  if (CKT_BASE::_sim->_time0 <= delay + rise) {                 /* initial rise */
    level = (maxv - 0) * (loctime/rise) + 0;
  }else if (loctime <= rise) {                          /* rising       */
    untested();
    level = (maxv - minv) * (loctime/rise) + minv;
  }else if (width==0.  ||  (loctime-=rise) <= width) {  /* pulse on     */
    level = maxv;
  }else if ((loctime-=width) <= fall) {                 /* falling      */
    untested();
    level = (minv - maxv) * (loctime/fall) + maxv;
  }else{                                                /* pulse off    */
    untested();
    level = minv;
  }
  level *= (freq == 0.)
    ? ampl
    : ampl * sin(M_TWO_PI * freq*(CKT_BASE::_sim->_time0-delay) + phaz * DTOR);
  return (CKT_BASE::_sim->_time0 <= delay + rise)
    ? level + (offset - init_) * (loctime/rise) + init_
    : level + offset;
}
void plclear (void)
Definition at line 98 of file plot.cc.
References active, and untested.
Referenced by anonymous_namespace{s_fo.cc}::FOURIER::foout(), and plopen().
{
  if (active) {
    untested();
  }
  active = false;
}
void plclose (void)
Definition at line 86 of file plot.cc.
References active, plborder(), and IO::plotout.
Referenced by CMD::cmdproc(), finish(), and anonymous_namespace{s_fo.cc}::FOURIER::foout().
{
  if (!active) {
    return;
  }
  plborder();
  active = false;
  IO::plotout = OMSTREAM();
}
int plopen (double start, double stop, const PROBELIST & plotlist)
Definition at line 67 of file plot.cc.
References active, plclear(), plhead(), IO::plotout, xstart, and xstop.
Referenced by SIM::head().
{
  if (start == stop) {
    IO::plotout = OMSTREAM();
  }
  if (!IO::plotout.any()) {
    plclear();
    return false;
  }
  xstart  = start;
  xstop   = stop;
  plhead(plotlist);
  assert(active == false);
  active = true;
  return true;
}
void plottr (double xx, const PROBELIST & plotlist)
Definition at line 31 of file plot.cc.
References active, PROBELIST::begin(), PROBELIST::end(), NOT_VALID, plotarg(), xstart, and xstop.
Referenced by SIM::outdata().
{
  if (active) {
    int ii = 0;
    double lo[2] = {0.};
    double hi[2] = {0.};
    double val[2] = {0.};
    for (PROBELIST::const_iterator
         i =  plotlist.begin();
         i != plotlist.end();
         ++i) {
      val[ii] = i->value();
      if (i->range() != 0.) {
        lo[ii] = i->lo();
        hi[ii] = i->hi();
      }else{
        lo[ii] = -5.;
        hi[ii] = 5.;
      }
      ++ii;
      if (ii >= 2) {
        break;
      }
    }
    if (ii <= 1) {
      val[1] = NOT_VALID;
    }
    plotarg(xx, val[0], val[1],
            xstart, lo[0], lo[1],
            xstop,  hi[0], hi[1]);
  }
}