gnucap: COMMON_BUILT_IN_BJT Class Reference
COMMON_BUILT_IN_BJT Class Reference
#include <d_bjt.h>
Public Member Functions
COMMON_BUILT_IN_BJT (const COMMON_BUILT_IN_BJT &p)
COMMON_BUILT_IN_BJT (int c=0)
~COMMON_BUILT_IN_BJT ()
bool operator== (const COMMON_COMPONENT &) const
COMMON_COMPONENT * clone () const
void set_param_by_index (int, std::string &, int)
bool param_is_printable (int) const
std::string param_name (int) const
std::string param_name (int, int) const
std::string param_value (int) const
int param_count () const
void precalc_first (const CARD_LIST *)
void expand (const COMPONENT *)
void precalc_last (const CARD_LIST *)
std::string name () const
const SDP_CARD * sdp () const
bool has_sdp () const
Static Public Member Functions
static int count ()
Public Attributes
PARAMETER< double > area
PARAMETER< bool > off
PARAMETER< double > icvbe
PARAMETER< double > icvce
PARAMETER< double > temp_c
SDP_CARD * _sdp
double oik
double oikr
Static Private Attributes
static int _count = -1
Detailed Description
Definition at line 167 of file d_bjt.h.
Constructor & Destructor Documentation
COMMON_BUILT_IN_BJT::COMMON_BUILT_IN_BJT (const COMMON_BUILT_IN_BJT & p) [explicit]
Definition at line 1023 of file d_bjt.cc.
References _count.
Referenced by clone().
  :COMMON_COMPONENT(p),
   area(p.area),
   off(p.off),
   icvbe(p.icvbe),
   icvce(p.icvce),
   temp_c(p.temp_c),
   _sdp(0),
   oik(p.oik),
   oikr(p.oikr)
{
  ++_count;
}
COMMON_BUILT_IN_BJT::COMMON_BUILT_IN_BJT (int c = 0) [explicit]
Definition at line 1009 of file d_bjt.cc.
References _count.
  :COMMON_COMPONENT(c),
   area(1.),
   off(false),
   icvbe(NA),
   icvce(NA),
   temp_c(NA),
   _sdp(0),
   oik(NA),
   oikr(NA)
{
  ++_count;
}
COMMON_BUILT_IN_BJT::~COMMON_BUILT_IN_BJT ()
Definition at line 1037 of file d_bjt.cc.
References _count, and _sdp.
{
  --_count;
  delete _sdp;
}
Member Function Documentation
COMMON_COMPONENT* COMMON_BUILT_IN_BJT::clone () const [inline, virtual]
Implements COMMON_COMPONENT.
Definition at line 174 of file d_bjt.h.
References COMMON_BUILT_IN_BJT().
{return new COMMON_BUILT_IN_BJT(*this);}
static int COMMON_BUILT_IN_BJT::count () [inline, static]
Definition at line 187 of file d_bjt.h.
References _count.
{return _count;}
void COMMON_BUILT_IN_BJT::expand (const COMPONENT * d) [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 1122 of file d_bjt.cc.
References _sdp, COMMON_COMPONENT::attach_model(), CARD::long_label(), COMMON_COMPONENT::model(), COMMON_COMPONENT::modelname(), MODEL_BUILT_IN_BJT::new_sdp(), and prechecked_cast.
{
  COMMON_COMPONENT::expand(d);
  attach_model(d);
  COMMON_BUILT_IN_BJT* c = this;
  const MODEL_BUILT_IN_BJT* m = dynamic_cast<const MODEL_BUILT_IN_BJT*>(model());
  if (!m) {
    throw Exception_Model_Type_Mismatch(d->long_label(), modelname(), "bjt");
  }else{
  }
  // size dependent
  //delete _sdp;
  _sdp = m->new_sdp(this);
  assert(_sdp);
  const SDP_BUILT_IN_BJT* s = prechecked_cast<const SDP_BUILT_IN_BJT*>(_sdp);
  assert(s);
  // subcircuit commons, recursive
  assert(c == this);
}
bool COMMON_BUILT_IN_BJT::has_sdp () const [inline]
Definition at line 186 of file d_bjt.h.
References _sdp, and untested.
{untested();return _sdp;}
std::string COMMON_BUILT_IN_BJT::name () const [inline, virtual]
Implements COMMON_COMPONENT.
Definition at line 184 of file d_bjt.h.
References itested.
{itested();return "bjt";}
bool COMMON_BUILT_IN_BJT::operator== (const COMMON_COMPONENT & x) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 1043 of file d_bjt.cc.
References _sdp, area, icvbe, icvce, off, anonymous_namespace{c_genrat.cc}::p, and temp_c.
{
  const COMMON_BUILT_IN_BJT* p = dynamic_cast<const COMMON_BUILT_IN_BJT*>(&x);
  return (p
    && area == p->area
    && off == p->off
    && icvbe == p->icvbe
    && icvce == p->icvce
    && temp_c == p->temp_c
    && _sdp == p->_sdp
    && COMMON_COMPONENT::operator==(x));
}
int COMMON_BUILT_IN_BJT::param_count () const [inline, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 180 of file d_bjt.h.
References COMMON_COMPONENT::param_count().
Referenced by param_is_printable(), param_name(), param_value(), and set_param_by_index().
{return (5 + COMMON_COMPONENT::param_count());}
bool COMMON_BUILT_IN_BJT::param_is_printable (int i) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 1068 of file d_bjt.cc.
References icvbe, icvce, NA(), off, param_count(), and temp_c.
{
  switch (COMMON_BUILT_IN_BJT::param_count() - 1 - i) {
  case 0:  return (true);
  case 1:  return (off);
  case 2:  return (icvbe != NA);
  case 3:  return (icvce != NA);
  case 4:  return (temp_c != NA);
  default: return COMMON_COMPONENT::param_is_printable(i);
  }
}
std::string COMMON_BUILT_IN_BJT::param_name (int i) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 1080 of file d_bjt.cc.
References param_count().
Referenced by param_name().
{
  switch (COMMON_BUILT_IN_BJT::param_count() - 1 - i) {
  case 0:  return "area";
  case 1:  return "off";
  case 2:  return "icvbe";
  case 3:  return "icvce";
  case 4:  return "temp";
  default: return COMMON_COMPONENT::param_name(i);
  }
}
std::string COMMON_BUILT_IN_BJT::param_name (int i, int j) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 1092 of file d_bjt.cc.
References param_count(), param_name(), and untested.
{
  if (j == 0) {
    return param_name(i);
  }else if (j == 1) {
    switch (COMMON_BUILT_IN_BJT::param_count() - 1 - i) {
    case 0:  return "";
    case 1:  return "";
    case 2:  return "";
    case 3:  return "";
    case 4:  return "";
    default: return "";
    }
  }else{untested();//281
    return COMMON_COMPONENT::param_name(i, j);
  }
}
std::string COMMON_BUILT_IN_BJT::param_value (int i) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 1110 of file d_bjt.cc.
References area, icvbe, icvce, off, param_count(), PARAMETER< T >::string(), and temp_c.
{
  switch (COMMON_BUILT_IN_BJT::param_count() - 1 - i) {
  case 0:  return area.string();
  case 1:  return off.string();
  case 2:  return icvbe.string();
  case 3:  return icvce.string();
  case 4:  return temp_c.string();
  default: return COMMON_COMPONENT::param_value(i);
  }
}
void COMMON_BUILT_IN_BJT::precalc_first (const CARD_LIST * par_scope) [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 1143 of file d_bjt.cc.
References area, e_val(), icvbe, icvce, NA(), off, and temp_c.
{
  assert(par_scope);
  COMMON_COMPONENT::precalc_first(par_scope);
    e_val(&(this->area), 1., par_scope);
    e_val(&(this->off), false, par_scope);
    e_val(&(this->icvbe), NA, par_scope);
    e_val(&(this->icvce), NA, par_scope);
    e_val(&(this->temp_c), NA, par_scope);
}
void COMMON_BUILT_IN_BJT::precalc_last (const CARD_LIST * par_scope) [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 1154 of file d_bjt.cc.
References _sdp, area, e_val(), icvbe, icvce, MODEL_BUILT_IN_BJT::invrollofff, MODEL_BUILT_IN_BJT::invrolloffr, COMMON_COMPONENT::model(), NA(), MODEL_BUILT_IN_BJT::new_sdp(), off, oik, oikr, prechecked_cast, and temp_c.
{
  assert(par_scope);
  COMMON_COMPONENT::precalc_last(par_scope);
  COMMON_BUILT_IN_BJT* c = this;
  const MODEL_BUILT_IN_BJT* m = prechecked_cast<const MODEL_BUILT_IN_BJT*>(model());
    // final adjust: code_pre
    // final adjust: override
    // final adjust: raw
    e_val(&(this->area), 1., par_scope);
    e_val(&(this->off), false, par_scope);
    e_val(&(this->icvbe), NA, par_scope);
    e_val(&(this->icvce), NA, par_scope);
    e_val(&(this->temp_c), NA, par_scope);
    // final adjust: mid
    // final adjust: calculated
    oik = m->invrollofff / c->area;
    oikr = m->invrolloffr / c->area;
    // final adjust: post
    // final adjust: done
  // size dependent
  //delete _sdp;
  _sdp = m->new_sdp(this);
  assert(_sdp);
  const SDP_BUILT_IN_BJT* s = prechecked_cast<const SDP_BUILT_IN_BJT*>(_sdp);
  assert(s);
  // subcircuit commons, recursive
  assert(c == this);
}
const SDP_CARD* COMMON_BUILT_IN_BJT::sdp () const [inline]
Definition at line 185 of file d_bjt.h.
References _sdp.
Referenced by DEV_BUILT_IN_BJT::expand(), TDP_BUILT_IN_BJT::TDP_BUILT_IN_BJT(), MODEL_BUILT_IN_BJT::tr_eval(), and DEV_BUILT_IN_BJT::tr_probe_num().
{return _sdp;}
void COMMON_BUILT_IN_BJT::set_param_by_index (int I, std::string & Value, int Offset) [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 1056 of file d_bjt.cc.
References area, icvbe, icvce, off, param_count(), and temp_c.
{
  switch (COMMON_BUILT_IN_BJT::param_count() - 1 - I) {
  case 0:  area = Value; break;
  case 1:  off = Value; break;
  case 2:  icvbe = Value; break;
  case 3:  icvce = Value; break;
  case 4:  temp_c = Value; break;
  default: COMMON_COMPONENT::set_param_by_index(I, Value, Offset);
  }
}
Member Data Documentation
int COMMON_BUILT_IN_BJT::_count = -1 [static, private]
Definition at line 189 of file d_bjt.h.
Referenced by COMMON_BUILT_IN_BJT(), count(), and ~COMMON_BUILT_IN_BJT().
SDP_CARD* COMMON_BUILT_IN_BJT::_sdp
Definition at line 197 of file d_bjt.h.
Referenced by expand(), has_sdp(), operator==(), precalc_last(), sdp(), and ~COMMON_BUILT_IN_BJT().
PARAMETER<double> COMMON_BUILT_IN_BJT::area
Definition at line 191 of file d_bjt.h.
Referenced by DEV_BUILT_IN_BJT::expand(), operator==(), param_value(), precalc_first(), precalc_last(), set_param_by_index(), and MODEL_BUILT_IN_BJT::tr_eval().
PARAMETER<double> COMMON_BUILT_IN_BJT::icvbe
Definition at line 193 of file d_bjt.h.
Referenced by DEV_BUILT_IN_BJT::do_tr(), operator==(), param_is_printable(), param_value(), precalc_first(), precalc_last(), and set_param_by_index().
PARAMETER<double> COMMON_BUILT_IN_BJT::icvce
Definition at line 194 of file d_bjt.h.
Referenced by DEV_BUILT_IN_BJT::do_tr(), operator==(), param_is_printable(), param_value(), precalc_first(), precalc_last(), and set_param_by_index().
PARAMETER<bool> COMMON_BUILT_IN_BJT::off
Definition at line 192 of file d_bjt.h.
Referenced by DEV_BUILT_IN_BJT::do_tr(), operator==(), param_is_printable(), param_value(), precalc_first(), precalc_last(), and set_param_by_index().
double COMMON_BUILT_IN_BJT::oik
Definition at line 198 of file d_bjt.h.
Referenced by precalc_last(), and MODEL_BUILT_IN_BJT::tr_eval().
double COMMON_BUILT_IN_BJT::oikr
Definition at line 199 of file d_bjt.h.
Referenced by precalc_last(), and MODEL_BUILT_IN_BJT::tr_eval().
PARAMETER<double> COMMON_BUILT_IN_BJT::temp_c
Definition at line 195 of file d_bjt.h.
Referenced by operator==(), param_is_printable(), param_value(), precalc_first(), precalc_last(), set_param_by_index(), and TDP_BUILT_IN_BJT::TDP_BUILT_IN_BJT().
The documentation for this class was generated from the following files:
savant/gnucap/src/d_bjt.h
savant/gnucap/src/d_bjt.cc