gnucap: EVAL_BM_VALUE Class Reference
EVAL_BM_VALUE Class Reference
#include <bm.h>
Public Member Functions
EVAL_BM_VALUE (int c=0)
~EVAL_BM_VALUE ()
Private Member Functions
EVAL_BM_VALUE (const EVAL_BM_VALUE &p)
bool operator== (const COMMON_COMPONENT &) const
COMMON_COMPONENT * clone () const
void print_common_obsolete_callback (OMSTREAM &, LANGUAGE *) const
bool is_trivial () const
void precalc_first (const CARD_LIST *)
void tr_eval (ELEMENT *) const
std::string name () const
bool ac_too () const
bool parse_numlist (CS &)
bool parse_params_obsolete_callback (CS &)
Detailed Description
Definition at line 86 of file bm.h.
Constructor & Destructor Documentation
EVAL_BM_VALUE::EVAL_BM_VALUE (const EVAL_BM_VALUE & p) [inline, explicit, private]
Definition at line 88 of file bm.h.
Referenced by clone().
:EVAL_BM_ACTION_BASE(p) {}
EVAL_BM_VALUE::EVAL_BM_VALUE (int c = 0) [inline, explicit]
Definition at line 90 of file bm.h.
:EVAL_BM_ACTION_BASE(c) {}
EVAL_BM_VALUE::~EVAL_BM_VALUE () [inline]
Definition at line 91 of file bm.h.
{}
Member Function Documentation
bool EVAL_BM_VALUE::ac_too () const [inline, private, virtual]
Implements EVAL_BM_ACTION_BASE.
Definition at line 101 of file bm.h.
{return false;}
COMMON_COMPONENT* EVAL_BM_VALUE::clone () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 94 of file bm.h.
References EVAL_BM_VALUE().
{return new EVAL_BM_VALUE(*this);}
bool EVAL_BM_VALUE::is_trivial () const [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 43 of file bm_value.cc.
References EVAL_BM_ACTION_BASE::_bandwidth, EVAL_BM_ACTION_BASE::_delay, COMMON_COMPONENT::_dtemp, EVAL_BM_ACTION_BASE::_ic, EVAL_BM_ACTION_BASE::_ioffset, EVAL_BM_ACTION_BASE::_ooffset, EVAL_BM_ACTION_BASE::_phase, EVAL_BM_ACTION_BASE::_scale, EVAL_BM_ACTION_BASE::_tc1, EVAL_BM_ACTION_BASE::_tc2, COMMON_COMPONENT::_temp_c, COMMON_COMPONENT::_tnom_c, and PARAMETER< T >::has_hard_value().
{
  return  !(_bandwidth.has_hard_value()
            || _delay.has_hard_value()
            || _phase.has_hard_value()
            || _ooffset.has_hard_value()
            || _ioffset.has_hard_value()
            || _scale.has_hard_value()
            || _tc1.has_hard_value()
            || _tc2.has_hard_value()
            || _ic.has_hard_value()
            || _tnom_c.has_hard_value()
            || _dtemp.has_hard_value()
            || _temp_c.has_hard_value());
}
std::string EVAL_BM_VALUE::name () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 100 of file bm.h.
References itested.
{itested();return "VALUE";}
bool EVAL_BM_VALUE::operator== (const COMMON_COMPONENT & x) const [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 31 of file bm_value.cc.
References anonymous_namespace{c_genrat.cc}::p.
{
  const EVAL_BM_VALUE* p = dynamic_cast<const EVAL_BM_VALUE*>(&x);
  return  p && EVAL_BM_ACTION_BASE::operator==(x);
}
bool EVAL_BM_VALUE::parse_numlist (CS & cmd) [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 73 of file bm_value.cc.
References COMMON_COMPONENT::_value, CS::cursor(), CS::gotit(), and NOT_VALID.
{
  unsigned here = cmd.cursor();
  PARAMETER<double> new_value(NOT_VALID);
  cmd >> new_value;
  if (cmd.gotit(here)) {
    _value = new_value;
    return true;
  }else{
    return false;
  }
}
bool EVAL_BM_VALUE::parse_params_obsolete_callback (CS & cmd) [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 86 of file bm_value.cc.
References COMMON_COMPONENT::_value, Get(), and ONE_OF.
{
  return ONE_OF
    || Get(cmd, "=", &_value)
    || EVAL_BM_ACTION_BASE::parse_params_obsolete_callback(cmd)
    ;
}
void EVAL_BM_VALUE::precalc_first (const CARD_LIST * Scope) [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 59 of file bm_value.cc.
References COMMON_COMPONENT::_value, and COMMON_COMPONENT::modelname().
{
  if (modelname() != "") {
    _value = modelname();
  }else{
  }
  EVAL_BM_ACTION_BASE::precalc_first(Scope);
}
void EVAL_BM_VALUE::print_common_obsolete_callback (OMSTREAM & o, LANGUAGE * lang) const [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 37 of file bm_value.cc.
References COMMON_COMPONENT::_value.
{
  o << _value;
  EVAL_BM_ACTION_BASE::print_common_obsolete_callback(o, lang);
}
void EVAL_BM_VALUE::tr_eval (ELEMENT * d) const [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 68 of file bm_value.cc.
References COMMON_COMPONENT::_value, and EVAL_BM_ACTION_BASE::tr_finish_tdv().
{
  tr_finish_tdv(d, _value);
}
The documentation for this class was generated from the following files:
savant/gnucap/src/bm.h
savant/gnucap/src/bm_value.cc