gnucap: savant/gnucap/src/u_parameter.cc File Reference
savant/gnucap/src/u_parameter.cc File Reference
#include "l_stlextra.h"
#include "u_parameter.h"
#include "u_lang.h"
Functions
bool Get (CS &cmd, const std::string &key, PARAMETER< bool > *val)
bool Get (CS &cmd, const std::string &key, PARAMETER< int > *val)
Function Documentation
bool Get (CS & cmd, const std::string & key, PARAMETER< bool > * val)
Definition at line 153 of file u_parameter.cc.
References CS::skip1b(), and CS::umatch().
{
  if (cmd.umatch(key + ' ')) {
    if (cmd.skip1b('=')) {
      cmd >> *val;
    }else{
      *val = true;
    }
    return true;
  }else if (cmd.umatch("no" + key)) {
    *val = false;
    return true;
  }else{
    return false;
  }
}
bool Get (CS & cmd, const std::string & key, PARAMETER< int > * val)
Definition at line 170 of file u_parameter.cc.
References CS::ctof(), and CS::umatch().
{
  if (cmd.umatch(key + " {=}")) {
    *val = int(cmd.ctof());
    return true;
  }else{
    return false;
  }
}