gnucap: DEV_COMMENT Class Reference
DEV_COMMENT Class Reference
#include <d_coment.h>
Public Member Functions
DEV_COMMENT ()
void set (const std::string &s)
std::string comment () const
Private Member Functions
DEV_COMMENT (const DEV_COMMENT &p)
char id_letter () const
std::string dev_type () const
CARD * clone () const
std::string value_name () const
Private Attributes
std::string _s
Detailed Description
Definition at line 30 of file d_coment.h.
Constructor & Destructor Documentation
DEV_COMMENT::DEV_COMMENT (const DEV_COMMENT & p) [inline, explicit, private]
Definition at line 33 of file d_coment.h.
References CARD::set_constant().
                                :CARD(p) {set_constant(true);}
DEV_COMMENT::DEV_COMMENT () [inline, explicit]
Definition at line 36 of file d_coment.h.
References CARD::set_constant().
Referenced by clone().
:CARD()  {set_constant(true);}
Member Function Documentation
CARD* DEV_COMMENT::clone () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 40 of file d_coment.h.
References DEV_COMMENT().
{return new DEV_COMMENT(*this);}
std::string DEV_COMMENT::comment () const [inline]
Definition at line 44 of file d_coment.h.
References _s.
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_comment(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_comment(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_comment(), and anonymous_namespace{lang_geda.cc}::LANG_GEDA::print_comment().
{return _s;}
std::string DEV_COMMENT::dev_type () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 39 of file d_coment.h.
References untested.
{untested(); return "comment";}
char DEV_COMMENT::id_letter () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 38 of file d_coment.h.
References untested.
{untested(); return '\0';}
void DEV_COMMENT::set (const std::string & s) [inline]
Definition at line 43 of file d_coment.h.
References _s.
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_comment(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_comment(), anonymous_namespace{lang_geda.cc}::LANG_GEDA::parse_comment(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_comment().
{_s = s;}
std::string DEV_COMMENT::value_name () const [inline, private, virtual]
Implements CARD.
Definition at line 41 of file d_coment.h.
{return "";}
Member Data Documentation
std::string DEV_COMMENT::_s [private]
Definition at line 32 of file d_coment.h.
Referenced by comment(), and set().
The documentation for this class was generated from the following file:
savant/gnucap/src/d_coment.h