gnucap: anonymous_namespace{c_param.cc}::CMD_PARAM Class Reference
anonymous_namespace{c_param.cc}::CMD_PARAM Class Reference
Public Member Functions
void do_it (CS &cmd, CARD_LIST *Scope)
Detailed Description
Definition at line 30 of file c_param.cc.
Member Function Documentation
void anonymous_namespace{c_param.cc}::CMD_PARAM::do_it (CS & cmd, CARD_LIST * Scope) [inline, virtual]
Implements CMD.
Definition at line 32 of file c_param.cc.
References CS::is_end(), OPT::language, IO::mstdout, CARD_LIST::params(), PARAM_LIST::parse(), and PARAM_LIST::print().
  {
    PARAM_LIST* pl = Scope->params();
    if (cmd.is_end()) {
      pl->print(IO::mstdout, OPT::language);
      IO::mstdout << '\n';
    }else{
      pl->parse(cmd);
    }
  }
The documentation for this class was generated from the following file:
savant/gnucap/src/c_param.cc