gnucap: anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX Class Reference
anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX Class Reference
Public Member Functions
EVAL_BM_COMPLEX (int c=0)
~EVAL_BM_COMPLEX ()
Private Member Functions
EVAL_BM_COMPLEX (const EVAL_BM_COMPLEX &p)
bool operator== (const COMMON_COMPONENT &) const
COMMON_COMPONENT * clone () const
void print_common_obsolete_callback (OMSTREAM &, LANGUAGE *) const
void tr_eval (ELEMENT *) const
void ac_eval (ELEMENT *) const
std::string name () const
bool ac_too () const
bool parse_numlist (CS &)
Private Attributes
COMPLEX _value
Detailed Description
Definition at line 31 of file bm_complex.cc.
Constructor & Destructor Documentation
anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX::EVAL_BM_COMPLEX (const EVAL_BM_COMPLEX & p) [explicit, private]
Definition at line 56 of file bm_complex.cc.
  :EVAL_BM_ACTION_BASE(p),
   _value(p._value)
{
}
anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX::EVAL_BM_COMPLEX (int c = 0) [explicit]
Definition at line 50 of file bm_complex.cc.
  :EVAL_BM_ACTION_BASE(c),
   _value(NOT_INPUT)
{
}
anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX::~EVAL_BM_COMPLEX () [inline]
Definition at line 37 of file bm_complex.cc.
{}
Member Function Documentation
void anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX::ac_eval (ELEMENT * d) const [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 87 of file bm_complex.cc.
References ELEMENT::_ev, _value, and EVAL_BM_ACTION_BASE::ac_final_adjust_with_temp().
{
  d->_ev = _value;
  ac_final_adjust_with_temp(&(d->_ev));
}
bool anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX::ac_too () const [inline, private, virtual]
Implements EVAL_BM_ACTION_BASE.
Definition at line 45 of file bm_complex.cc.
References untested.
{untested();return true;}
COMMON_COMPONENT* anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX::clone () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 40 of file bm_complex.cc.
{return new EVAL_BM_COMPLEX(*this);}
std::string anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX::name () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 44 of file bm_complex.cc.
Referenced by print_common_obsolete_callback().
{return "complex";}
bool anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX::operator== (const COMMON_COMPONENT & x) const [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 62 of file bm_complex.cc.
References _value, anonymous_namespace{c_genrat.cc}::p, and untested.
{
  const EVAL_BM_COMPLEX* p = dynamic_cast<const EVAL_BM_COMPLEX*>(&x);
  bool rv = p
    && _value == p->_value
    && EVAL_BM_ACTION_BASE::operator==(x);
  if (rv) {
    untested();
  }
  return rv;
}
bool anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX::parse_numlist (CS & cmd) [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 93 of file bm_complex.cc.
References _value, CS::cursor(), CS::gotit(), NOT_VALID, and untested.
{
  unsigned here = cmd.cursor();
  double real = NOT_VALID;
  double imag = 0.;
  cmd >> real >> imag;
  if (cmd.gotit(here)) {
    _value = COMPLEX(real,imag);
    return true;
  }else{
    untested();
    return false;
  }
}
void anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX::print_common_obsolete_callback (OMSTREAM & o, LANGUAGE * lang) const [private, virtual]
Reimplemented from EVAL_BM_ACTION_BASE.
Definition at line 74 of file bm_complex.cc.
References _value, and name().
{
  assert(lang);
  o << name() << '('
    << _value.real() << ',' << _value.imag() << ')';
  EVAL_BM_ACTION_BASE::print_common_obsolete_callback(o, lang);
}
void anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX::tr_eval (ELEMENT * d) const [private, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 82 of file bm_complex.cc.
References _value, and EVAL_BM_ACTION_BASE::tr_finish_tdv().
{
  tr_finish_tdv(d, _value.real());
}
Member Data Documentation
COMPLEX anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX::_value [private]
Reimplemented from COMMON_COMPONENT.
Definition at line 33 of file bm_complex.cc.
Referenced by ac_eval(), operator==(), parse_numlist(), print_common_obsolete_callback(), and tr_eval().
The documentation for this class was generated from the following file:
savant/gnucap/src/bm_complex.cc