gnucap: anonymous_namespace{lang_spice.cc}::CMD_BUILD Class Reference
anonymous_namespace{lang_spice.cc}::CMD_BUILD Class Reference
Public Member Functions
void do_it (CS &cmd, CARD_LIST *Scope)
Detailed Description
Definition at line 1021 of file lang_spice.cc.
Member Function Documentation
void anonymous_namespace{lang_spice.cc}::CMD_BUILD::do_it (CS & cmd, CARD_LIST * Scope) [inline, virtual]
Implements CMD.
Definition at line 1023 of file lang_spice.cc.
References anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::EXIT_ON_BLANK, STATUS::get, anonymous_namespace{lang_spice.cc}::lang_spice, anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_module_body(), TIMER::reset(), rPRESET, TIMER::start(), status, and TIMER::stop().
  {
    SET_RUN_MODE xx(rPRESET);
    ::status.get.reset().start();
    lang_spice.parse_module_body(cmd, NULL, Scope, ">", lang_spice.EXIT_ON_BLANK, ". ");
    ::status.get.stop();
  }
The documentation for this class was generated from the following file:
savant/gnucap/src/lang_spice.cc