gnucap: Token_STOP Class Reference
Token_STOP Class Reference
#include <m_expression.h>
Public Member Functions
Token_STOP (const std::string Name)
Token_STOP (const Token_STOP &P)
Token * clone () const
void stack_op (Expression *) const
Detailed Description
Definition at line 77 of file m_expression.h.
Constructor & Destructor Documentation
Token_STOP::Token_STOP (const std::string Name) [inline, explicit]
Definition at line 80 of file m_expression.h.
Referenced by clone().
    : Token(Name, NULL, "") {}
Token_STOP::Token_STOP (const Token_STOP & P) [inline, explicit]
Definition at line 82 of file m_expression.h.
: Token(P) {}
Member Function Documentation
Token* Token_STOP::clone () const [inline, virtual]
Implements Token.
Definition at line 83 of file m_expression.h.
References Token_STOP().
Referenced by stack_op().
{return new Token_STOP(*this);}
void Token_STOP::stack_op (Expression * E) const [virtual]
Reimplemented from Token.
Definition at line 222 of file m_expression_reduce.cc.
References clone(), and List_Base< T >::push_back().
{
  assert(E);
  E->push_back(clone());
}
The documentation for this class was generated from the following files:
savant/gnucap/src/m_expression.h
savant/gnucap/src/m_expression_reduce.cc