gnucap: savant/gnucap/src/plot.cc File Reference
savant/gnucap/src/plot.cc File Reference
#include "declare.h"
#include "constant.h"
#include "u_opt.h"
#include "u_prblst.h"
Defines
#define MAXWIDTH 512
#define OUTWIDTH (std::min(static_cast<int>(OPT::outwidth), MAXWIDTH))
#define INDENT 8 /* beware OMSTERAM::form! */
#define CONSSCALE (OUTWIDTH - INDENT - 2) /*console scale size in chr */
Functions
void plottr (double, const PROBELIST &)
int plopen (double, double, const PROBELIST &)
void plclose (void)
void plclear (void)
static void plborder (void)
static void calibrate (const PROBE &)
static int round_to_int (double)
static void plhead (const PROBELIST &)
static int point (double, double, double, int, int, int)
static void plotarg (double, double, double, double, double, double, double, double, double)
Variables
static bool active
static double xstart
static double xstop
static char border [MAXWIDTH+1]
static char emptydata [MAXWIDTH+1]
Define Documentation
#define CONSSCALE (OUTWIDTH - INDENT - 2) /*console scale size in chr */
Definition at line 25 of file plot.cc.
Referenced by calibrate(), plhead(), and plotarg().
#define INDENT 8 /* beware OMSTERAM::form! */
Definition at line 24 of file plot.cc.
Referenced by calibrate(), and plborder().
#define MAXWIDTH 512
Definition at line 22 of file plot.cc.
Referenced by plotarg().
#define OUTWIDTH (std::min(static_cast<int>(OPT::outwidth), MAXWIDTH))
Definition at line 23 of file plot.cc.
Referenced by calibrate().
Function Documentation
static void calibrate (const PROBE & prb) [static]
Definition at line 115 of file plot.cc.
References CONSSCALE, IO::formaat, ftos(), PROBE::hi(), INDENT, PROBE::label(), PROBE::lo(), OUTWIDTH, IO::plotout, PROBE::range(), round_to_int(), OMSTREAM::tab(), untested, and OPT::ydivisions.
Referenced by plhead().
{
  static char nums[20];         /* this label string        */
  static char highs[20];        /* the last label string    */
  int cal;                      /* char position within line                */
  int stop;                     /* location of last label, stop printing    */
  int filled;                   /* how far (characters) have been printed   */
  int numsize;                  /* number of characters in this label       */
  int start;                    /* starting position of this label          */
  double markno;                /* loop counter                             */
  double hi, lo;
  if (prb.range() == 0) {
    hi = 5;
    lo = -5;
  }else{
    hi = prb.hi();
    lo = prb.lo();
  }
  double range = hi - lo;
  strcpy(highs, ftos(hi, 0, 5, IO::formaat));
  highs[8] = '\0';                                        /* trim to 8 chrs */
  /* *strchr(&highs[2],' ') = '\0'; */      /* make the top label, and save */
  stop = OUTWIDTH - static_cast<int>(strlen(highs)) - 1; /* space for it. */
  IO::plotout << prb.label();
  range = hi - lo;
  filled = 0;
  for (markno = 0.;  markno < OPT::ydivisions;  markno++) {
    double number = lo + range * markno/OPT::ydivisions ;
    if (std::abs(number) < std::abs(range)/(10.*CONSSCALE)) {
      number = 0.;
    }                                           /* label to put on this div. */
    strcpy(nums, ftos(number, 0, 5, IO::formaat));
    nums[8] = '\0';                             /* trim to 8 chrs */
    numsize = static_cast<int>(strlen(nums));   /* center it over the mark */
    cal = round_to_int(INDENT + CONSSCALE * (markno/OPT::ydivisions));
    start = cal - (numsize+1)/2;
    if (start > filled  &&  start+numsize < stop) {
      IO::plotout.tab(start) << nums;            /* if it fits, print it */
      filled = start + numsize ;
    }else{untested();
    }
  }
  IO::plotout.tab(stop) << highs << '\n';    /* print the last calibration */
}
static void plborder (void) [static]
Definition at line 108 of file plot.cc.
References border, INDENT, IO::plotout, and OMSTREAM::tab().
Referenced by plclose(), and plhead().
{
  IO::plotout.tab(INDENT) << border << '\n';
}
void plclear (void)
Definition at line 98 of file plot.cc.
References active, and untested.
Referenced by anonymous_namespace{s_fo.cc}::FOURIER::foout(), and plopen().
{
  if (active) {
    untested();
  }
  active = false;
}
void plclose (void)
Definition at line 86 of file plot.cc.
References active, plborder(), and IO::plotout.
Referenced by CMD::cmdproc(), finish(), and anonymous_namespace{s_fo.cc}::FOURIER::foout().
{
  if (!active) {
    return;
  }
  plborder();
  active = false;
  IO::plotout = OMSTREAM();
}
static void plhead (const PROBELIST & plotlist) [static]
Definition at line 171 of file plot.cc.
References PROBELIST::begin(), border, calibrate(), CONSSCALE, emptydata, PROBELIST::end(), plborder(), round_to_int(), and OPT::ydivisions.
Referenced by plopen().
{
  for (PROBELIST::const_iterator
       i =  plotlist.begin();
       i != plotlist.end();
       ++i) {
    calibrate(*i);
  }
  for (int ii = 0;  ii < CONSSCALE; ii++) {             /* build strings */
    border[ii] = '-';
    emptydata[ii] = ' ';
  }
  double incr = static_cast<double>(CONSSCALE) / OPT::ydivisions;
  for (double
       place = 0.;
       place < static_cast<double>(CONSSCALE);
       place += incr) {
    border[round_to_int(place)] = '+';
    emptydata[round_to_int(place)] = '.';               /* tics in emptydata */
  }
  border[CONSSCALE] = '+';                      /* fix ends of the strings */
  border[CONSSCALE+1] = '\0';
  emptydata[CONSSCALE] = emptydata[0] = '|';
  emptydata[CONSSCALE+1] = '\0';
  plborder();                                   /* print the border */
}
int plopen (double start, double stop, const PROBELIST & plotlist)
Definition at line 67 of file plot.cc.
References active, plclear(), plhead(), IO::plotout, xstart, and xstop.
Referenced by SIM::head().
{
  if (start == stop) {
    IO::plotout = OMSTREAM();
  }
  if (!IO::plotout.any()) {
    plclear();
    return false;
  }
  xstart  = start;
  xstop   = stop;
  plhead(plotlist);
  assert(active == false);
  active = true;
  return true;
}
static void plotarg (double xx, double yy, double zz, double , double ylo, double zlo, double , double yhi, double zhi) [static]
Definition at line 229 of file plot.cc.
References CONSSCALE, emptydata, OMSTREAM::form(), IO::formaat, ftos(), MAXWIDTH, NOT_VALID, IO::plotout, and point().
Referenced by plottr().
{
  char adata[MAXWIDTH+1];     /* actual data. copy emptydata, insert */
  char *xxs;                                 /* string representation of xx */
  memcpy(adata, emptydata, MAXWIDTH); /* copy prototype */
  xxs = ftos( xx, 11, 5, IO::formaat );
  if (zz != NOT_VALID) {
    adata[point(zz,zlo,zhi,CONSSCALE,0,1)] = '+';/* zap data into string */
  }
  adata[point(yy,ylo,yhi,CONSSCALE,0,1)] = '*';
  IO::plotout.form( "%-8.8s%s", xxs, adata );
  IO::plotout << '\n';
}
void plottr (double xx, const PROBELIST & plotlist)
Definition at line 31 of file plot.cc.
References active, PROBELIST::begin(), PROBELIST::end(), NOT_VALID, plotarg(), xstart, and xstop.
Referenced by SIM::outdata().
{
  if (active) {
    int ii = 0;
    double lo[2] = {0.};
    double hi[2] = {0.};
    double val[2] = {0.};
    for (PROBELIST::const_iterator
         i =  plotlist.begin();
         i != plotlist.end();
         ++i) {
      val[ii] = i->value();
      if (i->range() != 0.) {
        lo[ii] = i->lo();
        hi[ii] = i->hi();
      }else{
        lo[ii] = -5.;
        hi[ii] = 5.;
      }
      ++ii;
      if (ii >= 2) {
        break;
      }
    }
    if (ii <= 1) {
      val[1] = NOT_VALID;
    }
    plotarg(xx, val[0], val[1],
            xstart, lo[0], lo[1],
            xstop,  hi[0], hi[1]);
  }
}
static int point (double yy, double lo, double hi, int scale, int offset, int linswp) [static]
Definition at line 201 of file plot.cc.
References itested, offset, round_to_int(), and untested.
Referenced by BSMATRIX< T >::allocate(), and plotarg().
{
  int place;
  if (linswp) {
    place = round_to_int( scale*(yy-lo)/(hi-lo));
  }else{untested();
    place = round_to_int( scale*(log(yy/lo))/(log(hi/lo)));
  }
  if (place < 0) {
    place = 0;
  }
  if (place > scale) {itested();
    place = scale;
  }
  return  place + offset;
}
static int round_to_int (double x) [static]
Definition at line 163 of file plot.cc.
Referenced by calibrate(), plhead(), and point().
{
  return static_cast<int>(floor(x+.5));
}
Variable Documentation
bool active [static]
Definition at line 26 of file plot.cc.
Referenced by plclear(), plclose(), plopen(), and plottr().
char border[MAXWIDTH+1] [static]
Definition at line 28 of file plot.cc.
Referenced by plborder(), and plhead().
char emptydata[MAXWIDTH+1] [static]
Definition at line 29 of file plot.cc.
Referenced by plhead(), and plotarg().
double xstart [static]
Definition at line 27 of file plot.cc.
Referenced by plopen(), and plottr().
double xstop [static]
Definition at line 27 of file plot.cc.
Referenced by plopen(), and plottr().