gnucap: savant/gnucap/src/l_denoise.h File Reference
savant/gnucap/src/l_denoise.h File Reference
#include "u_opt.h"
Functions
void fixzero (double *z, double r)
double fixzero (double z, double r)
double dn_diff (double a, double b)
Function Documentation
double dn_diff (double a, double b) [inline]
Definition at line 50 of file l_denoise.h.
References fixzero().
Referenced by ELEMENT::dampdiff(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::tr_amps(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::tr_amps(), anonymous_namespace{d_vcvs.cc}::DEV_VCVS::tr_involts(), CCSRC_BASE::tr_involts(), anonymous_namespace{d_vcr.cc}::DEV_VCR::tr_involts(), anonymous_namespace{d_vcg.cc}::DEV_VCG::tr_involts(), anonymous_namespace{d_cap.cc}::DEV_TRANSCAP::tr_involts(), anonymous_namespace{d_admit.cc}::DEV_VCCS::tr_involts(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_involts(), anonymous_namespace{d_cap.cc}::DEV_VCCAP::tr_involts(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_load(), ELEMENT::tr_outvolts(), anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM::tr_review(), WAVE::v_reflect(), and COMPONENT::volts_limited().
{
  assert(a == a);
  assert(b == b);
  return fixzero(a-b, a);
}
void fixzero (double * z, double r) [inline]
Definition at line 31 of file l_denoise.h.
References OPT::roundofftol.
Referenced by SPLINE::construct_order_3(), dn_diff(), anonymous_namespace{s_dc.cc}::DCOP::next(), TDP_BUILT_IN_MOS2::TDP_BUILT_IN_MOS2(), TDP_BUILT_IN_MOS3::TDP_BUILT_IN_MOS3(), TDP_BUILT_IN_MOS6::TDP_BUILT_IN_MOS6(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_amps(), ELEMENT::tr_amps(), anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::tr_eval(), MODEL_BUILT_IN_MOS2::tr_eval(), MODEL_BUILT_IN_MOS7::tr_eval(), and MODEL_BUILT_IN_MOS8::tr_eval().
{
  assert(z);
  assert(*z == *z);
  assert(r == r);
  if (std::abs(*z) < std::abs(r*OPT::roundofftol)) {
    *z=0.;
  }
}
double fixzero (double z, double r) [inline]
Definition at line 42 of file l_denoise.h.
References OPT::roundofftol.
{
  assert(z == z);
  assert(r == r);
  return (std::abs(z) < std::abs(r*OPT::roundofftol)) ? 0. : z;
}