gnucap: anonymous_namespace{c_modify.cc} Namespace Reference
anonymous_namespace{c_modify.cc} Namespace Reference
Classes
class CMD_MODIFY
class CMD_FAULT
class CMD_RESTORE
class CMD_UNFAULT
Enumerations
enum WHATTODO { FAULT, MODIFY }
Functions
void faultbranch (CARD *brh, double value)
double sweep_fix (CS &cmd, const CARD *brh)
void modify_fault (CS &cmd, WHATTODO command, CARD_LIST *scope)
Variables
std::list< CARDSTASH > faultstack
anonymous_namespace{c_modify.cc}::CMD_MODIFY p1
DISPATCHER< CMD >::INSTALL d1 & command_dispatcher
anonymous_namespace{c_modify.cc}::CMD_FAULT p2
anonymous_namespace{c_modify.cc}::CMD_RESTORE p3
anonymous_namespace{c_modify.cc}::CMD_UNFAULT p4
Enumeration Type Documentation
enum anonymous_namespace{c_modify.cc}::WHATTODO
Enumerator:
FAULT
MODIFY
Definition at line 33 of file c_modify.cc.
{FAULT, MODIFY};
Function Documentation
void anonymous_namespace{c_modify.cc}::faultbranch (CARD * brh, double value)
Definition at line 39 of file c_modify.cc.
References error(), CARD::is_device(), CARD::long_label(), prechecked_cast, COMPONENT::set_value(), CARD::subckt(), and untested.
Referenced by modify_fault().
{
  if (!brh->is_device()) {
    untested();
    error(bWARNING, brh->long_label() + ": not a device, can't fault:\n");
  }else if (brh->subckt()) {
    untested();
    error(bWARNING, brh->long_label() + " has subckt, can't fault:\n");
  }else{
    faultstack.push_back(CARDSTASH(brh));
    ELEMENT* e = prechecked_cast<ELEMENT*>(brh);
    assert(e);
    e->set_value(value, 0);
    //BUG// messy way to do this, loses other attributes
  }
}
void anonymous_namespace{c_modify.cc}::modify_fault (CS & cmd, WHATTODO command, CARD_LIST * scope)
Definition at line 90 of file c_modify.cc.
References CKT_BASE::_sim, CARD_LIST::begin(), CS::check(), CS::ctof(), CS::cursor(), FAULT, faultbranch(), findbranch(), CS::is_alpha(), MODIFY, prechecked_cast, CS::reset(), COMPONENT::set_value(), CS::skip1b(), CS::skiparg(), sweep_fix(), SIM_DATA::uninit(), and untested.
Referenced by anonymous_namespace{c_modify.cc}::CMD_MODIFY::do_it(), and anonymous_namespace{c_modify.cc}::CMD_FAULT::do_it().
{
  CKT_BASE::_sim->uninit();
  while (cmd.is_alpha()) {
    unsigned mark = cmd.cursor();
    unsigned cmax = cmd.cursor();
    CARD_LIST::fat_iterator ci(scope, scope->begin());
    for (;;) {
      cmd.reset(mark);
      ci = findbranch(cmd, ci);
      cmax = std::max(cmax, cmd.cursor());
      if (ci.is_end()) {
        break;
      }
      cmd.skip1b('=');
      CARD* brh = *ci;
      switch (command) {
      case MODIFY:{
        ELEMENT* e = prechecked_cast<ELEMENT*>(brh);
        assert(e);
        e->set_value(cmd.ctof(), 0);
        //BUG// messy way to do this, loses other attributes
      } break;
      case FAULT:{
        faultbranch(brh, sweep_fix(cmd,brh));
      } break;
      }
      cmax = std::max(cmax, cmd.cursor());
      ++ci;
    }
    cmd.reset(cmax);
    if (mark == cmax) {
      untested();
      cmd.check(bWARNING, "what's this?");
      cmd.skiparg();
    }
  }
}
double anonymous_namespace{c_modify.cc}::sweep_fix (CS & cmd, const CARD * brh)
Definition at line 60 of file c_modify.cc.
References CS::ctof(), CS::is_float(), CARD::long_label(), IO::mstdout, offset, OMSTREAM::setfloatwidth(), swp_count, swp_nest, swp_steps, swp_type, and untested.
Referenced by modify_fault().
{
  double start = cmd.ctof();
  double value = start;
  if (swp_steps[swp_nest] != 0   &&   cmd.is_float()) {
    untested();
    double last = cmd.ctof();
    double offset = static_cast<double>(swp_count[swp_nest])
      / static_cast<double>(swp_steps[swp_nest]);
    if (swp_type[swp_nest]=='L') {
      untested();
      if (start == 0.) {
        untested();
        throw Exception("log sweep can't pass zero");
        value = 0;
      }else{
        untested();
        value = start * pow( (last/start), offset );
      }
    }else{
      untested();
      value = start + (last-start) * offset;
    }
    IO::mstdout.setfloatwidth(7)
      << swp_count[swp_nest]+1 << "> sweep " << brh->long_label()
      << " =" << value << '\n';
  }
  return value;
}
Variable Documentation
DISPATCHER< CMD >::INSTALL d4 & anonymous_namespace{c_modify.cc}::command_dispatcher
Definition at line 136 of file c_modify.cc.
std::list<CARDSTASH> anonymous_namespace{c_modify.cc}::faultstack
Definition at line 34 of file c_modify.cc.
anonymous_namespace{c_modify.cc}::CMD_MODIFY anonymous_namespace{c_modify.cc}::p1
anonymous_namespace{c_modify.cc}::CMD_FAULT anonymous_namespace{c_modify.cc}::p2
anonymous_namespace{c_modify.cc}::CMD_RESTORE anonymous_namespace{c_modify.cc}::p3
anonymous_namespace{c_modify.cc}::CMD_UNFAULT anonymous_namespace{c_modify.cc}::p4