gnucap: Float Class Reference
Float Class Reference
#include <m_base.h>
Public Member Functions
Float (const Float &p)
Float (CS &file)
Float (const std::string &s)
Float (double x=NOT_INPUT)
void parse (CS &)
double value () const
operator double () const
std::string val_string () const
bool to_bool () const
Base * minus () const
Base * plus () const
Base * less (const Float *X) const
Base * greater (const Float *X) const
Base * leq (const Float *X) const
Base * geq (const Float *X) const
Base * not_equal (const Float *X) const
Base * equal (const Float *X) const
Base * add (const Float *X) const
Base * multiply (const Float *X) const
Base * subtract (const Float *X) const
Base * r_subtract (const Float *X) const
Base * divide (const Float *X) const
Base * r_divide (const Float *X) const
Base * less (const Base *X) const
Base * greater (const Base *X) const
Base * leq (const Base *X) const
Base * geq (const Base *X) const
Base * not_equal (const Base *X) const
Base * equal (const Base *X) const
Base * add (const Base *X) const
Base * multiply (const Base *X) const
Base * subtract (const Base *X) const
Base * r_subtract (const Base *X) const
Base * divide (const Base *X) const
Base * r_divide (const Base *X) const
Base * less (const String *) const
Base * greater (const String *) const
Base * leq (const String *) const
Base * geq (const String *) const
Base * not_equal (const String *) const
Base * equal (const String *) const
Base * add (const String *) const
Base * multiply (const String *) const
Base * subtract (const String *) const
Base * r_subtract (const String *) const
Base * divide (const String *) const
Base * r_divide (const String *) const
bool is_NA () const
Private Member Functions
void dump (std::ostream &o) const
Private Attributes
double _data
Detailed Description
Definition at line 144 of file m_base.h.
Constructor & Destructor Documentation
Float::Float (const Float & p) [inline]
Definition at line 157 of file m_base.h.
References untested.
Referenced by add(), divide(), equal(), geq(), greater(), leq(), less(), minus(), multiply(), not_equal(), plus(), r_divide(), r_subtract(), and subtract().
:Base(), _data(p._data) {untested();}
Float::Float (CS & file) [inline, explicit]
Definition at line 158 of file m_base.h.
References parse(), and untested.
{untested();parse(file);}
Float::Float (const std::string & s) [inline, explicit]
Definition at line 159 of file m_base.h.
References CS::_STRING, and parse().
{CS cs(CS::_STRING, s); parse(cs);}
Float::Float (double x = NOT_INPUT) [inline]
Definition at line 160 of file m_base.h.
:_data(x) {}
Member Function Documentation
Base* Float::add (const Float * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 176 of file m_base.h.
References _data, and Float().
{assert(X); return new Float(_data + X->_data);}
Base* Float::add (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 189 of file m_base.h.
References Base::add().
{return ((X) ? (X->add(this))       : (NULL));}
Base* Float::add (const String *) const [inline, virtual]
Reimplemented from Base.
Definition at line 202 of file m_base.h.
References untested.
{untested();return NULL;}
Base* Float::divide (const Float * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 180 of file m_base.h.
References _data, Float(), and untested.
{untested();assert(X); return new Float(_data / X->_data);}
Base* Float::divide (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 193 of file m_base.h.
References Base::r_divide().
{return ((X) ? (X->r_divide(this))  : (NULL));}
Base* Float::divide (const String *) const [inline, virtual]
Reimplemented from Base.
Definition at line 206 of file m_base.h.
References untested.
{untested();return NULL;}
void Float::dump (std::ostream & o) const [inline, private, virtual]
Implements Base.
Definition at line 149 of file m_base.h.
References _data, itested, NOT_INPUT, and untested.
                                {itested();
    if (_data==NOT_INPUT) {untested();
      o<<"NA";
    }else{itested();
      o<<_data;
    }
  }
Base* Float::equal (const Float * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 175 of file m_base.h.
References _data, and Float().
{assert(X); return new Float((_data == X->_data)?1.:0.);}
Base* Float::equal (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 188 of file m_base.h.
References Base::equal().
{return ((X) ? (X->equal(this))     : (NULL));}
Base* Float::equal (const String *) const [inline, virtual]
Reimplemented from Base.
Definition at line 201 of file m_base.h.
References untested.
{untested();return NULL;}
Base* Float::geq (const Float * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 173 of file m_base.h.
References _data, and Float().
{assert(X); return new Float((_data >= X->_data)?1.:0.);}
Base* Float::geq (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 186 of file m_base.h.
References Base::leq().
{return ((X) ? (X->leq(this))       : (NULL));}
Base* Float::geq (const String *) const [inline, virtual]
Reimplemented from Base.
Definition at line 199 of file m_base.h.
References untested.
{untested();return NULL;}
Base* Float::greater (const Float * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 171 of file m_base.h.
References _data, and Float().
{assert(X); return new Float((_data > X->_data)?1.:0.);}
Base* Float::greater (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 184 of file m_base.h.
References Base::less().
{return ((X) ? (X->less(this))      : (NULL));}
Base* Float::greater (const String *) const [inline, virtual]
Reimplemented from Base.
Definition at line 197 of file m_base.h.
References untested.
{untested();return NULL;}
bool Float::is_NA () const [inline]
Definition at line 209 of file m_base.h.
References _data, NOT_INPUT, and untested.
{untested();return _data == NOT_INPUT;}
Base* Float::leq (const Float * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 172 of file m_base.h.
References _data, and Float().
{assert(X); return new Float((_data <= X->_data)?1.:0.);}
Base* Float::leq (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 185 of file m_base.h.
References Base::geq().
{return ((X) ? (X->geq(this))       : (NULL));}
Base* Float::leq (const String *) const [inline, virtual]
Reimplemented from Base.
Definition at line 198 of file m_base.h.
References untested.
{untested();return NULL;}
Base* Float::less (const Float * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 170 of file m_base.h.
References _data, and Float().
{assert(X); return new Float((_data < X->_data)?1.:0.);}
Base* Float::less (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 183 of file m_base.h.
References Base::greater().
{return ((X) ? (X->greater(this))   : (NULL));}
Base* Float::less (const String *) const [inline, virtual]
Reimplemented from Base.
Definition at line 196 of file m_base.h.
References untested.
{untested();return NULL;}
Base* Float::minus () const [inline, virtual]
Reimplemented from Base.
Definition at line 167 of file m_base.h.
References _data, and Float().
{return new Float(-_data);}
Base* Float::multiply (const Float * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 177 of file m_base.h.
References _data, and Float().
{assert(X); return new Float(_data * X->_data);}
Base* Float::multiply (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 190 of file m_base.h.
References Base::multiply().
{return ((X) ? (X->multiply(this))  : (NULL));}
Base* Float::multiply (const String *) const [inline, virtual]
Reimplemented from Base.
Definition at line 203 of file m_base.h.
References untested.
{untested();return NULL;}
Base* Float::not_equal (const Float * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 174 of file m_base.h.
References _data, and Float().
{assert(X); return new Float((_data != X->_data)?1.:0.);}
Base* Float::not_equal (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 187 of file m_base.h.
References Base::not_equal().
{return ((X) ? (X->not_equal(this)) : (NULL));}
Base* Float::not_equal (const String *) const [inline, virtual]
Reimplemented from Base.
Definition at line 200 of file m_base.h.
References untested.
{untested();return NULL;}
Float::operator double () const [inline]
Definition at line 163 of file m_base.h.
References _data, and untested.
{untested();return _data;}
void Float::parse (CS & File) [virtual]
Implements Base.
Definition at line 26 of file m_base_in.cc.
References _data, CS::cursor(), NOT_INPUT, CS::stuck(), and untested.
Referenced by Float().
{
  if (File >> "NA") {
    _data = NOT_INPUT;
  }else{
    unsigned here = File.cursor();
    File >> _data;
    if (File.stuck(&here)) {untested();
      _data = NOT_INPUT;
    }else{
    }
  }
}
Base* Float::plus () const [inline, virtual]
Reimplemented from Base.
Definition at line 168 of file m_base.h.
References _data, and Float().
{return new Float(_data);}
Base* Float::r_divide (const Float * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 181 of file m_base.h.
References _data, and Float().
{assert(X); return new Float(X->_data / _data);}
Base* Float::r_divide (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 194 of file m_base.h.
References Base::divide(), and untested.
{untested();return ((X) ? (X->divide(this))    : (NULL));}
Base* Float::r_divide (const String *) const [inline, virtual]
Reimplemented from Base.
Definition at line 207 of file m_base.h.
{           return NULL;}
Base* Float::r_subtract (const Float * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 179 of file m_base.h.
References _data, and Float().
{assert(X); return new Float(X->_data - _data);}
Base* Float::r_subtract (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 192 of file m_base.h.
References Base::subtract(), and untested.
{untested();return ((X) ? (X->subtract(this))  : (NULL));}
Base* Float::r_subtract (const String *) const [inline, virtual]
Reimplemented from Base.
Definition at line 205 of file m_base.h.
References untested.
{untested();return NULL;}
Base* Float::subtract (const Float * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 178 of file m_base.h.
References _data, Float(), and untested.
{untested();assert(X); return new Float(_data - X->_data);}
Base* Float::subtract (const Base * X) const [inline, virtual]
Reimplemented from Base.
Definition at line 191 of file m_base.h.
References Base::r_subtract().
{return ((X) ? (X->r_subtract(this)): (NULL));}
Base* Float::subtract (const String *) const [inline, virtual]
Reimplemented from Base.
Definition at line 204 of file m_base.h.
References untested.
{untested();return NULL;}
bool Float::to_bool () const [inline, virtual]
Reimplemented from Base.
Definition at line 165 of file m_base.h.
References _data.
{return (_data != 0);}
std::string Float::val_string () const [inline, virtual]
Reimplemented from Base.
Definition at line 164 of file m_base.h.
References _data, ftos(), and ftos_EXP.
Referenced by Token_SYMBOL::stack_op().
{return ftos(_data, 0, 15, ftos_EXP);}
double Float::value () const [inline]
Definition at line 162 of file m_base.h.
References _data.
Referenced by Expression::eval().
{return _data;}
Member Data Documentation
double Float::_data [private]
Definition at line 148 of file m_base.h.
Referenced by add(), divide(), dump(), equal(), geq(), greater(), is_NA(), leq(), less(), minus(), multiply(), not_equal(), operator double(), parse(), plus(), r_divide(), r_subtract(), subtract(), to_bool(), val_string(), and value().
The documentation for this class was generated from the following files:
savant/gnucap/src/m_base.h
savant/gnucap/src/m_base_in.cc