gnucap: savant/gnucap/src/l_lib.h File Reference
savant/gnucap/src/l_lib.h File Reference
#include "md.h"
Namespaces
namespace OS
Enumerations
enum { ftos_DEFAULT = 0, ftos_EXP = 1, ftos_SIGN = 2, ftos_FILL = 4 }
Functions
char * trim (char *)
INTERFACE bool Umatch (const std::string &, const std::string &)
INTERFACE bool wmatch (const std::string &s1, const std::string &s2)
INTERFACE std::string to_string (unsigned)
INTERFACE std::string to_string (int)
INTERFACE std::string to_string (double)
INTERFACE char * ftos (double, int, int, int)
void OS::system (const std::string &s)
void OS::chdir (const std::string &s)
void OS::remove (const std::string &s)
bool OS::access_ok (const std::string &file, int mode)
std::string OS::getcwd ()
std::string OS::getenv (const std::string &s)
Enumeration Type Documentation
anonymous enum
Enumerator:
ftos_DEFAULT
ftos_EXP
ftos_SIGN
ftos_FILL
Definition at line 36 of file l_lib.h.
     {                  /* formatting bit-fields */
  ftos_DEFAULT = 0,     /* default formatting, with letters */
  ftos_EXP = 1,         /* use 'e' notation, almost like printf */
  ftos_SIGN = 2,        /* always include sign */
  ftos_FILL = 4         /* fill in trailing zeros */
};
Function Documentation
INTERFACE char* ftos (double , int , int , int)
Definition at line 68 of file l_ftos.cc.
References BIGBIG, ftos_EXP, ftos_FILL, ftos_floor, ftos_SIGN, MAXLENGTH, NOT_INPUT, NOT_VALID, POOLSIZE, trim(), and untested.
Referenced by calibrate(), anonymous_namespace{s_fo.cc}::FOURIER::foprint(), OMSTREAM::operator<<(), plotarg(), to_string(), and Float::val_string().
{
  if (len < 3) {
    untested();
    len = 3;
  }
  if (len > MAXLENGTH-6) {
    untested();
    len = MAXLENGTH-6;
  }
  if (fieldwidth > MAXLENGTH-1) {
    untested();
    fieldwidth = MAXLENGTH-1;
  }
  char *str;
  { /* get a buffer from the pool */
    //BUG// It is possible to have too many buffers active
    // then the extras are overwritten, giving bad output
    // There are no known cases, but it is not checked.
    static char strpool[POOLSIZE][MAXLENGTH];
    static int poolindex = 0;
    ++poolindex;
    if (poolindex >= POOLSIZE) {
      poolindex = 0;
    }
    str = strpool[poolindex];
  }
  { /* build a clean blank string */
    int string_size = std::max(fieldwidth, len+6);
    for (int iii=0; iii<string_size; ++iii) {
      str[iii] = ' ';
    }
    for (int iii=string_size; iii<MAXLENGTH; ++iii) {
      str[iii] = '\0';
    }
  }
#ifdef HAS_NUMERIC_LIMITS
  if (num == std::numeric_limits<double>::infinity()) {
    untested();
    strncpy(str," Over", 5);
  }else if (num == -std::numeric_limits<double>::infinity()) {
    untested();
    strncpy(str,"-Over", 5);
  }else if (num == std::numeric_limits<double>::quiet_NaN()) {
    untested();
    strncpy(str," NaN", 4);
  }else if (num == std::numeric_limits<double>::signaling_NaN()) {
    untested();
    strncpy(str," NaN", 4);
  }else
#endif
  if (num == NOT_VALID) {
    strncpy(str," ??", 3);
  }else if (num == NOT_INPUT) {
    strncpy(str," NA", 3);
  }else if (num >= BIGBIG) {
    strncpy(str," Inf", 4);
  }else if (num <= -BIGBIG) {
    strncpy(str,"-Inf", 4);
  }else if (num != num) {
    strncpy(str," NaN", 4);
  }else{
    if (std::abs(num) < ftos_floor) {   /* hide noise */
      num = 0.;
    }
    int expo = 0;       /* exponent                             */
    int nnn = 0;        /* char counter -- pos in string        */
    if (num == 0.) {
      strcpy(str, " 0.");
      nnn = static_cast<int>(strlen(str)); /* num==0 .. build string 0.000...  */
      while (--len) {
        str[nnn++] = '0';
      }
      assert(expo == 0);
    }else{                              /* num != 0 */
      { // insert sign
        if (num < 0.) {
          str[0] = '-';
          num = -num;
        }else if (fmt & ftos_SIGN) {
          untested();
          str[0] = '+';
        }else{
          assert(str[0] == ' ');
        }
      }
      { // scale to .001 - 1.0.  adjust expo.
        expo = -3;
        while (num < .001) {
          num *= 1000.;
          expo -= 3;
        }
        while (num >= 1.) {
          num *= .001;
          expo += 3;
        }
      }
      { // adjust len to compensate for length of printed exponent
        if ((fmt&ftos_EXP && expo<-9) || expo>10 || expo<-16) {
          --len;                        /* one less digit if 'e' notation */
        }                               /* and exp is 2 digits */
        if (len < 3) {
          untested();
          ++len;
        }
      }
      { // round to correct number of digits
        double rnd = .5 / pow(10., len); /* find amt to add to round */
        if (num < .01) {
          rnd /= 100.;
        }else if (num < .1) {
          rnd /= 10.;
        }
        num += rnd;                     /* add it */
        if (num >= 1.) {
          num *= .001;                  /* created an extra digit: rescale */
          expo += 3;
        }
      }
      { // build mantissa
        nnn = 1;
        if (expo == -3) {               /* .001 is preferable to 1e-3 */
          int flg = 0;                  /* print in fixed point, no exponent*/
          expo = 0;
          str[nnn++] = '0';
          str[nnn++] = '.';
          while (len > 0) {
            num *= 10.;
            int digit = static_cast<int>(floor(num));
            num -= static_cast<double>(digit);
            str[nnn++] = static_cast<char>(digit + '0');
            if ((flg += digit)) {
              --len;
            }
          }
        }else{
          int flg = 0;
          for (int iii=2; len>0; --iii) {/* mantissa                        */
            num *= 10.;                 /* get next digit                   */
            int digit = static_cast<int>(floor(num));
            num -= static_cast<double>(digit);/* subtract off last digit    */
            if ((flg += digit)) {       /* if int part !=0                  */
              str[nnn++]=static_cast<char>(digit+'0');/*(not all zeros so far)*/
              --len;                    /* stuff the digit into the string  */
            }
            if (iii==0) {               /* if we found the dec.pt. and      */
              str[nnn++] = '.';         /*   haven't used up all the space  */
            }                           /* put a dec.pt. in the string      */
          }
        }
      }
    }
    assert(nnn > 0);
    assert(str[nnn] == ' ' || str[nnn] == '\0');
    { // suppress trailing zeros
      if (!(fmt&ftos_FILL)) {
        while (str[--nnn]=='0') {
          str[nnn] = static_cast<char>((nnn < fieldwidth) ? ' ' : '\0');
        }
        ++nnn;
      }else{
        untested();
      }
    }
    { // append exponent
      if (expo == 0) {
        // nothing;
      }else if (fmt&ftos_EXP || expo>10 || expo<-16) {/* exponential format  */
        char c = str[nnn+4];
        sprintf(&str[nnn], ((expo < 100) ? "E%+-3d" : "E%3u"), expo);
        nnn+=4;
        str[nnn++] = c;
      }else{                               /* if letter-scale format        */
        str[nnn++] = "fpnum KMGT"[(expo+15)/3];/* put the appropriate letter*/
      }                         /* note that letter-scale is not valid      */
                                /* for exp==-3 or exp not in -15..+12       */
                                /* this is trapped but letter-scale is also */
                                /* not valid if exp not divisible by 3.     */
                                /* This is not trapped, since it supposedly */
                                /* cant happen.                             */
      if (str[nnn-1] == 'M') {
        str[nnn++] = 'e';       /* Spice kluge "MEG" */
        str[nnn++] = 'g';
      }
    }
  }
  { // clean up trailing blanks
    if (fieldwidth==0) {
      trim(str);
    }
  }
  return str;
}
INTERFACE std::string to_string (unsigned)
Definition at line 49 of file l_ftos.cc.
Referenced by anonymous_namespace{c_system.cc}::CMD_EDIT::do_it(), anonymous_namespace{func_core.cc}::abs::eval(), anonymous_namespace{measure_min.cc}::MEASURE::eval(), anonymous_namespace{measure_rms.cc}::MEASURE::eval(), anonymous_namespace{measure_at.cc}::MEASURE::eval(), anonymous_namespace{measure_average.cc}::MEASURE::eval(), anonymous_namespace{measure_cross.cc}::MEASURE::eval(), anonymous_namespace{measure_integral.cc}::MEASURE::eval(), anonymous_namespace{measure_max.cc}::MEASURE::eval(), anonymous_namespace{measure_slewrate.cc}::MEASURE::eval(), anonymous_namespace{measure_eval.cc}::MEASURE::eval(), anonymous_namespace{func_core.cc}::sqrt::eval(), anonymous_namespace{func_core.cc}::log::eval(), anonymous_namespace{func_core.cc}::exp::eval(), anonymous_namespace{func_core.cc}::INT::eval(), anonymous_namespace{func_core.cc}::pow::eval(), anonymous_namespace{func_core.cc}::MAX::eval(), anonymous_namespace{func_core.cc}::MIN::eval(), anonymous_namespace{func_core.cc}::IF::eval(), anonymous_namespace{func_core.cc}::sin::eval(), anonymous_namespace{func_core.cc}::sinh::eval(), anonymous_namespace{func_core.cc}::cos::eval(), anonymous_namespace{func_core.cc}::cosh::eval(), anonymous_namespace{func_core.cc}::tan::eval(), anonymous_namespace{func_core.cc}::tanh::eval(), anonymous_namespace{func_core.cc}::RANDOM_STUB::eval(), DEV_LOGIC::expand(), COMPONENT::find_model(), DISPATCHER< T >::install(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_ports(), DEV_SPICE::precalc_first(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::precalc_last(), anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT::precalc_last(), MODEL_SPICE::set_param_by_name(), DEV_SPICE::set_param_by_name(), SPLINE::SPLINE(), TRANSIENT::status(), PARAMETER< bool >::string(), and DISPATCHER< T >::uninstall().
{
  char s[100];
  sprintf(s, "%u", n);
  return s;
}
INTERFACE std::string to_string (int)
Definition at line 56 of file l_ftos.cc.
{
  char s[100];
  sprintf(s, "%d", n);
  return s;
}
INTERFACE std::string to_string (double)
Definition at line 63 of file l_ftos.cc.
References ftos().
{
  return ftos(n, 0, 7, 0);
}
char * trim (char * string)
Definition at line 30 of file l_trim.cc.
Referenced by ftos(), getcmd(), getlines(), and xopen().
{
  size_t idx = strlen(string);
  while (idx > 0  &&  !isgraph(string[--idx])) {
    string[idx] = '\0' ;
  }
  return string;
}
INTERFACE bool Umatch (const std::string & , const std::string &)
Definition at line 35 of file l_pmatch.cc.
References CS::_STRING, and CS::umatch().
Referenced by ELEMENT::ac_probe_ext(), NODE::ac_probe_ext(), CKT_BASE::ac_probe_num(), anonymous_namespace{c_sweep.cc}::buildfile(), LANGUAGE::find_proto(), PROBE::probe_node(), CARD::set_dev_type(), COMMON_COMPONENT::set_param_by_name(), COMMON_COMPONENT::Set_param_by_name(), CARD::set_param_by_name(), STORAGE::tr_probe_num(), anonymous_namespace{d_cap.cc}::DEV_CAPACITANCE::tr_probe_num(), ELEMENT::tr_probe_num(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_probe_num(), DEV_SUBCKT::tr_probe_num(), NODE::tr_probe_num(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::tr_probe_num(), LOGIC_NODE::tr_probe_num(), COMPONENT::tr_probe_num(), DEV_SPICE::tr_probe_num(), and xopen().
{
  CS cmd(CS::_STRING, str1); //call to CS member on string
  if (cmd.umatch(str2)) {
    return true;
  }else{
    return 0;
  }
}
INTERFACE bool wmatch (const std::string & s1, const std::string & s2)
Definition at line 62 of file l_wmatch.cc.
References wmatch_by_ptr().
Referenced by PROBELIST::add_branches(), anonymous_namespace{c_delete.cc}::CMD_DELETE::delete_one_name(), CKT_BASE::find_wave(), findbranch(), and operator==().
{
  return wmatch_by_ptr(s1.c_str(), s2.c_str());
}