gnucap: PARAM_LIST Class Reference
PARAM_LIST Class Reference
#include <u_parameter.h>
Public Types
typedef std::map< const
std::string, PARAMETER< double >
>::const_iterator const_iterator
typedef std::map< const
std::string, PARAMETER< double >
>::iterator iterator
Public Member Functions
PARAM_LIST ()
PARAM_LIST (const PARAM_LIST &p)
~PARAM_LIST ()
void parse (CS &cmd)
void print (OMSTREAM &, LANGUAGE *) const
size_t size () const
bool is_empty () const
bool is_printable (int) const
std::string name (int) const
std::string value (int) const
void eval_copy (PARAM_LIST &, const CARD_LIST *)
bool operator== (const PARAM_LIST &p) const
const PARAMETER< double > & deep_lookup (std::string) const
const PARAMETER< double > & operator[] (std::string i) const
void set (std::string, const std::string &)
void set_try_again (PARAM_LIST *t)
iterator begin ()
iterator end ()
Public Attributes
PARAM_LIST * _try_again
Private Attributes
std::map< const std::string,
PARAMETER< double > > _pl
int _index
const_iterator _previous
Detailed Description
Definition at line 192 of file u_parameter.h.
Member Typedef Documentation
typedef std::map<const std::string, PARAMETER<double> >::const_iterator PARAM_LIST::const_iterator
Definition at line 199 of file u_parameter.h.
typedef std::map<const std::string, PARAMETER<double> >::iterator PARAM_LIST::iterator
Definition at line 201 of file u_parameter.h.
Constructor & Destructor Documentation
PARAM_LIST::PARAM_LIST () [inline, explicit]
Definition at line 202 of file u_parameter.h.
:_try_again(NULL) {}
PARAM_LIST::PARAM_LIST (const PARAM_LIST & p) [inline, explicit]
Definition at line 203 of file u_parameter.h.
                                :_pl(p._pl), _try_again(p._try_again) {}
PARAM_LIST::~PARAM_LIST () [inline]
Definition at line 206 of file u_parameter.h.
{}
Member Function Documentation
iterator PARAM_LIST::begin () [inline]
Definition at line 223 of file u_parameter.h.
Referenced by COMMON_SUBCKT::precalc_first(), and DEV_SPICE::precalc_first().
{return _pl.begin();}
const PARAMETER< double > & PARAM_LIST::deep_lookup (std::string Name) const
Definition at line 122 of file u_parameter.cc.
References _pl, _try_again, OPT::case_insensitive, deep_lookup(), PARAMETER< T >::has_hard_value(), and notstd::to_lower().
Referenced by deep_lookup(), PARAMETER< T >::lookup_solve(), and COMMON_SUBCKT::precalc_first().
{
  if (OPT::case_insensitive) {
    notstd::to_lower(&Name);
  }else{
  }
  PARAMETER<double> & rv = _pl[Name];
  if (rv.has_hard_value()) {
    // found a value, return it
    return rv;
  }else if (_try_again) {
    // didn't find one, look in enclosing scope
    return _try_again->deep_lookup(Name);
  }else{
    // no enclosing scope to look in
    // really didn't find it, give up
    // return garbage value (NOT_INPUT)
    return rv;
  }
}
iterator PARAM_LIST::end () [inline]
Definition at line 224 of file u_parameter.h.
Referenced by COMMON_SUBCKT::precalc_first(), and DEV_SPICE::precalc_first().
{return _pl.end();}
void PARAM_LIST::eval_copy (PARAM_LIST & p, const CARD_LIST * scope)
Definition at line 105 of file u_parameter.cc.
References _pl, _try_again, NOT_INPUT, and untested.
Referenced by CARD_LIST::attach_params().
{
  assert(!_try_again);
  _try_again = p._try_again;
  for (iterator i = p._pl.begin(); i != p._pl.end(); ++i) {
    if (i->second.has_hard_value()) {
      if (_pl[i->first].has_hard_value()) {untested();
        _pl[i->first] = i->second.e_val(_pl[i->first], scope);
      }else{
        _pl[i->first] = i->second.e_val(NOT_INPUT, scope);
      }
    }else{
    }
  }
}
bool PARAM_LIST::is_empty () const [inline]
Definition at line 211 of file u_parameter.h.
{return _pl.empty();}
bool PARAM_LIST::is_printable (int i) const
Definition at line 66 of file u_parameter.cc.
References _pl.
Referenced by COMMON_SUBCKT::param_is_printable(), and MODEL_SPICE::param_is_printable().
{
  //BUG// ugly linear search
  int i_try = 0;
  for (const_iterator ii = _pl.begin(); ii != _pl.end(); ++ii) {
    if (i_try++ == i) {
      return ii->second.has_hard_value();
    }else{
    }
  }
  return false;
}
std::string PARAM_LIST::name (int i) const
Definition at line 79 of file u_parameter.cc.
References _pl.
Referenced by COMMON_SUBCKT::param_name(), and MODEL_SPICE::param_name().
{
  //BUG// ugly linear search
  int i_try = 0;
  for (const_iterator ii = _pl.begin(); ii != _pl.end(); ++ii) {
    if (i_try++ == i) {
      return ii->first;
    }else{
    }
  }
  return "";
}
bool PARAM_LIST::operator== (const PARAM_LIST & p) const [inline]
Definition at line 217 of file u_parameter.h.
References _pl.
{return _pl == p._pl;}
const PARAMETER<double>& PARAM_LIST::operator[] (std::string i) const [inline]
Definition at line 219 of file u_parameter.h.
{return deep_lookup(i);}
void PARAM_LIST::parse (CS & cmd)
Definition at line 31 of file u_parameter.cc.
References _pl, OPT::case_insensitive, CS::check(), CS::cursor(), CS::is_alpha(), CS::match1(), CS::more(), CS::stuck(), notstd::to_lower(), and untested.
Referenced by anonymous_namespace{c_param.cc}::CMD_PARAM::do_it(), and anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_module().
{
  (cmd >> "real |integer "); // ignore type
  unsigned here = cmd.cursor();
  for (;;) {
    if (!(cmd.more() && (cmd.is_alpha() || cmd.match1('_')))) {
      break;
    }else{
    }
    std::string Name;
    PARAMETER<double> Value;
    cmd >> Name >> '=' >> Value;
    if (cmd.stuck(&here)) {untested();
      break;
    }else{
    }
    if (OPT::case_insensitive) {
      notstd::to_lower(&Name);
    }else{
    }
    _pl[Name] = Value;
  }
  cmd.check(bDANGER, "syntax error");
}
void PARAM_LIST::print (OMSTREAM & o, LANGUAGE * lang) const
Definition at line 56 of file u_parameter.cc.
References _pl, and print_pair().
Referenced by anonymous_namespace{c_param.cc}::CMD_PARAM::do_it().
{
  for (const_iterator i = _pl.begin(); i != _pl.end(); ++i) {
    if (i->second.has_hard_value()) {
      print_pair(o, lang, i->first, i->second);
    }else{
    }
  }
}
void PARAM_LIST::set (std::string Name, const std::string & Value)
Definition at line 143 of file u_parameter.cc.
References _pl, OPT::case_insensitive, and notstd::to_lower().
Referenced by anonymous_namespace{c_measure.cc}::CMD_MEASURE::do_it(), and MODEL_SPICE::set_param_by_name().
{
  if (OPT::case_insensitive) {
    notstd::to_lower(&Name);
  }else{
  }
  _pl[Name] = Value;
}
void PARAM_LIST::set_try_again (PARAM_LIST * t) [inline]
Definition at line 221 of file u_parameter.h.
Referenced by DEV_SUBCKT::expand().
{_try_again = t;}
size_t PARAM_LIST::size () const [inline]
Definition at line 210 of file u_parameter.h.
Referenced by MODEL_SPICE::param_count().
{return _pl.size();}
std::string PARAM_LIST::value (int i) const
Definition at line 92 of file u_parameter.cc.
References _pl.
Referenced by COMMON_SUBCKT::param_value(), and MODEL_SPICE::param_value().
{
  //BUG// ugly linear search
  int i_try = 0;
  for (const_iterator ii = _pl.begin(); ii != _pl.end(); ++ii) {
    if (i_try++ == i) {
      return ii->second.string();
    }else{
    }
  }
  return "";
}
Member Data Documentation
int PARAM_LIST::_index [mutable, private]
Definition at line 226 of file u_parameter.h.
std::map<const std::string, PARAMETER<double> > PARAM_LIST::_pl [mutable, private]
Definition at line 194 of file u_parameter.h.
Referenced by deep_lookup(), eval_copy(), is_printable(), name(), operator==(), parse(), print(), set(), and value().
const_iterator PARAM_LIST::_previous [mutable, private]
Definition at line 227 of file u_parameter.h.
PARAM_LIST* PARAM_LIST::_try_again
Definition at line 196 of file u_parameter.h.
Referenced by deep_lookup(), eval_copy(), and DEV_SUBCKT::expand().
The documentation for this class was generated from the following files:
savant/gnucap/src/u_parameter.h
savant/gnucap/src/u_parameter.cc