gnucap: savant/gnucap/src/ap_get.cc File Reference
savant/gnucap/src/ap_get.cc File Reference
#include "ap.h"
Functions
bool Get (CS &cmd, const std::string &key, bool *val)
bool Get (CS &cmd, const std::string &key, int *val, AP_MOD mod, int scale)
bool Get (CS &cmd, const std::string &key, double *val, AP_MOD mod, double scale)
Function Documentation
bool Get (CS & cmd, const std::string & key, bool * val)
Definition at line 30 of file ap_get.cc.
References itested, CS::skip1b(), and CS::umatch().
Referenced by anonymous_namespace{c_genrat.cc}::CMD_::do_it(), anonymous_namespace{measure_at.cc}::MEASURE::eval(), anonymous_namespace{measure_average.cc}::MEASURE::eval(), anonymous_namespace{measure_cross.cc}::MEASURE::eval(), anonymous_namespace{measure_integral.cc}::MEASURE::eval(), anonymous_namespace{measure_max.cc}::MEASURE::eval(), anonymous_namespace{measure_min.cc}::MEASURE::eval(), anonymous_namespace{measure_rms.cc}::MEASURE::eval(), anonymous_namespace{measure_slewrate.cc}::MEASURE::eval(), anonymous_namespace{lang_spice.cc}::getmerge(), anonymous_namespace{s_dc.cc}::DCOP::options(), TRANSIENT::options(), anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::parse_params_obsolete_callback(), EVAL_BM_SEMI_BASE::parse_params_obsolete_callback(), anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::parse_params_obsolete_callback(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::parse_params_obsolete_callback(), anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY::parse_params_obsolete_callback(), anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT::parse_params_obsolete_callback(), anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE::parse_params_obsolete_callback(), anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP::parse_params_obsolete_callback(), anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM::parse_params_obsolete_callback(), anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::parse_params_obsolete_callback(), MODEL_TABLE::parse_params_obsolete_callback(), EVAL_BM_ACTION_BASE::parse_params_obsolete_callback(), EVAL_BM_VALUE::parse_params_obsolete_callback(), COMMON_COMPONENT::parse_params_obsolete_callback(), OPT::set_values(), and anonymous_namespace{s_ac.cc}::AC::setup().
{
  if (cmd.umatch(key + ' ')) {
    if (cmd.skip1b('=')) {itested();
      cmd >> *val;
    }else{
      *val = true;
    }
    return true;
  }else if (cmd.umatch("no" + key)) {
    *val = false;
    return true;
  }else{
    return false;
  }
}
bool Get (CS & cmd, const std::string & key, int * val, AP_MOD mod, int scale)
Definition at line 47 of file ap_get.cc.
References CS::ctof(), CS::ctoo(), CS::ctox(), mHEX, mINVERT, mNONE, mOCTAL, mOFFSET, mPOSITIVE, mSCALE, CS::umatch(), and untested.
{
  if (cmd.umatch(key + " {=}")) {
    switch(mod) {
    case mNONE:                 *val = int(cmd.ctof());         break;
    case mSCALE:    untested(); *val = int(cmd.ctof())*scale;   break;
    case mOFFSET:   untested(); *val = int(cmd.ctof())+scale;   break;
    case mINVERT:   untested(); *val = 1 / int(cmd.ctof());     break;
    case mPOSITIVE: untested(); *val = std::abs(int(cmd.ctof())); break;
    case mOCTAL:                *val = cmd.ctoo();              break;
    case mHEX:      untested(); *val = cmd.ctox();              break;
    }
    return true;
  }else{
    return false;
  }
}
bool Get (CS & cmd, const std::string & key, double * val, AP_MOD mod, double scale)
Definition at line 65 of file ap_get.cc.
References CS::ctof(), CS::ctoo(), CS::ctox(), mHEX, mINVERT, mNONE, mOCTAL, mOFFSET, mPOSITIVE, mSCALE, CS::umatch(), and untested.
{
  if (cmd.umatch(key + " {=}")) {
    switch(mod) {
    case mNONE:     untested(); *val = cmd.ctof();              break;
    case mSCALE:    untested(); *val = cmd.ctof()*scale;        break;
    case mOFFSET:   untested(); *val = cmd.ctof()+scale;        break;
    case mINVERT:   untested(); *val = 1 / cmd.ctof();          break;
    case mPOSITIVE:             *val = std::abs(cmd.ctof());    break;
    case mOCTAL:    untested(); *val = cmd.ctoo();              break;
    case mHEX:      untested(); *val = cmd.ctox();              break;
    }
    return true;
  }else{
    return false;
  }
}