gnucap: Tail_String Class Reference
Tail_String Class Reference
#include <m_base.h>
Public Member Functions
void parse (CS &)
Tail_String (CS &file)
Tail_String ()
Detailed Description
Definition at line 292 of file m_base.h.
Constructor & Destructor Documentation
Tail_String::Tail_String (CS & file) [inline, explicit]
Definition at line 297 of file m_base.h.
References parse(), and untested.
{untested();parse(file);}
Tail_String::Tail_String () [inline, explicit]
Definition at line 298 of file m_base.h.
References untested.
{untested();}
Member Function Documentation
void Tail_String::parse (CS & File) [virtual]
Reimplemented from String.
Definition at line 90 of file m_base_in.cc.
References String::_data, CS::skipto1(), CS::tail(), and untested.
Referenced by Tail_String().
{untested(); // c_str
  static char end_marks[] = "\n";
  const char* begin = File.tail().c_str();
  File.skipto1(end_marks);
  const char* end = File.tail().c_str();
  assert(end >= begin);
  while ((--end >= begin) && (isspace(*end))) {untested();
  }
  ++end;
  assert(end >= begin);
  _data = std::string(begin, static_cast<size_t>(end-begin));
}
The documentation for this class was generated from the following files:
savant/gnucap/src/m_base.h
savant/gnucap/src/m_base_in.cc