gnucap: COMMON_SUBCKT Class Reference
COMMON_SUBCKT Class Reference
#include <d_subckt.h>
Public Member Functions
COMMON_SUBCKT (int c=0)
~COMMON_SUBCKT ()
bool operator== (const COMMON_COMPONENT &) const
COMMON_COMPONENT * clone () const
std::string name () const
void set_param_by_name (std::string Name, std::string Value)
bool param_is_printable (int) const
std::string param_name (int) const
std::string param_name (int, int) const
std::string param_value (int) const
int param_count () const
void precalc_first (const CARD_LIST *)
void precalc_last (const CARD_LIST *)
Static Public Member Functions
static int count ()
Public Attributes
PARAM_LIST _params
Private Member Functions
COMMON_SUBCKT (const COMMON_SUBCKT &p)
Static Private Attributes
static int _count = -1
Detailed Description
Definition at line 107 of file d_subckt.h.
Constructor & Destructor Documentation
COMMON_SUBCKT::COMMON_SUBCKT (const COMMON_SUBCKT & p) [inline, explicit, private]
Definition at line 109 of file d_subckt.h.
    :COMMON_COMPONENT(p), _params(p._params) {++_count;}
COMMON_SUBCKT::COMMON_SUBCKT (int c = 0) [inline, explicit]
Definition at line 112 of file d_subckt.h.
:COMMON_COMPONENT(c) {++_count;}
COMMON_SUBCKT::~COMMON_SUBCKT () [inline]
Definition at line 113 of file d_subckt.h.
{--_count;}
Member Function Documentation
COMMON_COMPONENT* COMMON_SUBCKT::clone () const [inline, virtual]
Implements COMMON_COMPONENT.
Definition at line 115 of file d_subckt.h.
{return new COMMON_SUBCKT(*this);}
static int COMMON_SUBCKT::count () [inline, static]
Definition at line 117 of file d_subckt.h.
{return _count;}
std::string COMMON_SUBCKT::name () const [inline, virtual]
Implements COMMON_COMPONENT.
Definition at line 116 of file d_subckt.h.
References itested.
{itested(); return "subckt";}
bool COMMON_SUBCKT::operator== (const COMMON_COMPONENT & x) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 48 of file d_subckt.cc.
References _params, and anonymous_namespace{c_genrat.cc}::p.
{
  const COMMON_SUBCKT* p = dynamic_cast<const COMMON_SUBCKT*>(&x);
  bool rv = p
    && _params == p->_params
    && COMMON_COMPONENT::operator==(x);
  return rv;
}
int COMMON_SUBCKT::param_count () const [inline, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 124 of file d_subckt.h.
References COMMON_COMPONENT::param_count().
Referenced by param_is_printable(), param_name(), and param_value().
        {return (static_cast<int>(_params.size()) + COMMON_COMPONENT::param_count());}
bool COMMON_SUBCKT::param_is_printable (int i) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 57 of file d_subckt.cc.
References _params, PARAM_LIST::is_printable(), COMMON_COMPONENT::param_count(), and param_count().
{
  assert(i < COMMON_SUBCKT::param_count());
  if (i >= COMMON_COMPONENT::param_count()) {
    return _params.is_printable(COMMON_SUBCKT::param_count() - 1 - i);
  }else{
    return COMMON_COMPONENT::param_is_printable(i);
  }
}
std::string COMMON_SUBCKT::param_name (int i) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 67 of file d_subckt.cc.
References _params, PARAM_LIST::name(), COMMON_COMPONENT::param_count(), and param_count().
Referenced by param_name().
{
  assert(i < COMMON_SUBCKT::param_count());
  if (i >= COMMON_COMPONENT::param_count()) {
    return _params.name(COMMON_SUBCKT::param_count() - 1 - i);
  }else{
    return COMMON_COMPONENT::param_name(i);
  }
}
std::string COMMON_SUBCKT::param_name (int i, int j) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 77 of file d_subckt.cc.
References COMMON_COMPONENT::param_count(), param_count(), param_name(), and untested.
{
  assert(i < COMMON_SUBCKT::param_count());
  if (j == 0) {untested();
    return param_name(i);
  }else if (i >= COMMON_COMPONENT::param_count()) {untested();
    return "";
  }else{untested();
    return COMMON_COMPONENT::param_name(i);
  }
}
std::string COMMON_SUBCKT::param_value (int i) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 89 of file d_subckt.cc.
References _params, COMMON_COMPONENT::param_count(), param_count(), and PARAM_LIST::value().
{
  assert(i < COMMON_SUBCKT::param_count());
  if (i >= COMMON_COMPONENT::param_count()) {
    return _params.value(COMMON_SUBCKT::param_count() - 1 - i);
  }else{
    return COMMON_COMPONENT::param_value(i);
  }
}
void COMMON_SUBCKT::precalc_first (const CARD_LIST * Scope) [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 99 of file d_subckt.cc.
References COMMON_COMPONENT::_mfactor, _params, PARAM_LIST::begin(), PARAM_LIST::deep_lookup(), PARAM_LIST::end(), and NOT_INPUT.
{
  assert(Scope);
  COMMON_COMPONENT::precalc_first(Scope);
  for (PARAM_LIST::iterator i = _params.begin(); i != _params.end(); ++i) {
    i->second.e_val(NOT_INPUT,Scope);
  }
  _mfactor = _params.deep_lookup("m");
}
void COMMON_SUBCKT::precalc_last (const CARD_LIST * Scope) [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 110 of file d_subckt.cc.
{
  assert(Scope);
  COMMON_COMPONENT::precalc_last(Scope);
}
void COMMON_SUBCKT::set_param_by_name (std::string Name, std::string Value) [inline, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 119 of file d_subckt.h.
{_params.set(Name, Value);}
Member Data Documentation
int COMMON_SUBCKT::_count = -1 [static, private]
Definition at line 130 of file d_subckt.h.
PARAM_LIST COMMON_SUBCKT::_params
Definition at line 132 of file d_subckt.h.
Referenced by DEV_SUBCKT::expand(), operator==(), param_is_printable(), param_name(), param_value(), DEV_SUBCKT::precalc_first(), precalc_first(), DEV_SPICE::precalc_first(), DEV_SUBCKT::precalc_last(), and DEV_SPICE::set_param_by_name().
The documentation for this class was generated from the following files:
savant/gnucap/src/d_subckt.h
savant/gnucap/src/d_subckt.cc