gnucap: savant/gnucap/src/u_nodemap.cc File Reference
savant/gnucap/src/u_nodemap.cc File Reference
#include "e_node.h"
#include "u_nodemap.h"
Variables
NODE ground_node ("0", 0)
Variable Documentation
NODE ground_node("0", 0)
Referenced by NODE::ac_probe_ext(), NODE_MAP::NODE_MAP(), and NODE::tr_probe_num().