gnucap: LOGICVAL Class Reference
LOGICVAL Class Reference
#include <e_node.h>
Public Member Functions
LOGICVAL ()
LOGICVAL (const LOGICVAL &p)
LOGICVAL (_LOGICVAL p)
~LOGICVAL ()
operator _LOGICVAL () const
LOGICVAL & operator= (_LOGICVAL p)
LOGICVAL & operator= (const LOGICVAL &p)
LOGICVAL & operator&= (LOGICVAL p)
LOGICVAL & operator|= (LOGICVAL p)
LOGICVAL operator^= (LOGICVAL p)
LOGICVAL operator~ () const
bool is_unknown () const
bool lv_future () const
bool lv_old () const
bool is_rising () const
bool is_falling () const
LOGICVAL & set_in_transition (LOGICVAL newval)
Private Attributes
_LOGICVAL _lv
Static Private Attributes
static const _LOGICVAL or_truth [lvNUM_STATES][lvNUM_STATES]
static const _LOGICVAL xor_truth [lvNUM_STATES][lvNUM_STATES]
static const _LOGICVAL and_truth [lvNUM_STATES][lvNUM_STATES]
static const _LOGICVAL not_truth [lvNUM_STATES]
Detailed Description
Definition at line 46 of file e_node.h.
Constructor & Destructor Documentation
LOGICVAL::LOGICVAL () [inline]
Definition at line 54 of file e_node.h.
:_lv(lvUNKNOWN)                 {}
LOGICVAL::LOGICVAL (const LOGICVAL & p) [inline]
Definition at line 55 of file e_node.h.
:_lv(p._lv)     {}
LOGICVAL::LOGICVAL (_LOGICVAL p) [inline]
Definition at line 56 of file e_node.h.
:_lv(p)         {}
LOGICVAL::~LOGICVAL () [inline]
Definition at line 57 of file e_node.h.
{}
Member Function Documentation
bool LOGICVAL::is_falling () const [inline]
Definition at line 77 of file e_node.h.
References lvFALLING.
{return _lv == lvFALLING;}
bool LOGICVAL::is_rising () const [inline]
Definition at line 76 of file e_node.h.
References lvRISING.
{return _lv == lvRISING;}
bool LOGICVAL::is_unknown () const [inline]
Definition at line 72 of file e_node.h.
References lvUNKNOWN.
{return _lv == lvUNKNOWN;}
bool LOGICVAL::lv_future () const [inline]
Definition at line 73 of file e_node.h.
References lvUNKNOWN.
Referenced by DEV_LOGIC::tr_accept().
{assert(_lv!=lvUNKNOWN); return _lv & 1;}
bool LOGICVAL::lv_old () const [inline]
Definition at line 74 of file e_node.h.
References lvUNKNOWN.
Referenced by DEV_LOGIC::tr_accept().
{assert(_lv!=lvUNKNOWN); return _lv & 2;}
LOGICVAL::operator _LOGICVAL () const [inline]
Definition at line 59 of file e_node.h.
{return static_cast<_LOGICVAL>(_lv);}
LOGICVAL& LOGICVAL::operator&= (LOGICVAL p) [inline]
Definition at line 64 of file e_node.h.
References _lv, and untested.
        {untested(); _lv = and_truth[_lv][p._lv]; return *this;}
LOGICVAL& LOGICVAL::operator= (_LOGICVAL p) [inline]
Definition at line 61 of file e_node.h.
References anonymous_namespace{c_genrat.cc}::p.
{_lv=p; return *this;}
LOGICVAL& LOGICVAL::operator= (const LOGICVAL & p) [inline]
Definition at line 62 of file e_node.h.
References _lv.
{_lv=p._lv; return *this;}
LOGICVAL LOGICVAL::operator^= (LOGICVAL p) [inline]
Definition at line 68 of file e_node.h.
References _lv, and untested.
        {untested(); _lv = xor_truth[_lv][p._lv]; return *this;}
LOGICVAL& LOGICVAL::operator|= (LOGICVAL p) [inline]
Definition at line 66 of file e_node.h.
References _lv.
        {_lv = or_truth[_lv][p._lv]; return *this;}
LOGICVAL LOGICVAL::operator~ () const [inline]
Definition at line 70 of file e_node.h.
{return not_truth[_lv];}
LOGICVAL & LOGICVAL::set_in_transition (LOGICVAL newval) [inline]
Definition at line 66 of file e_node.cc.
References _lv, lvUNKNOWN, and prop_truth.
Referenced by LOGIC_NODE::set_event().
{
  _lv = prop_truth[_lv][newval];
  assert(_lv != lvUNKNOWN);
  return *this;
}
Member Data Documentation
_LOGICVAL LOGICVAL::_lv [private]
Definition at line 48 of file e_node.h.
Referenced by operator&=(), operator=(), operator^=(), operator|=(), and set_in_transition().
const _LOGICVAL LOGICVAL::and_truth [static, private]
Initial value:
 {
  {lvSTABLE0, lvSTABLE0, lvSTABLE0, lvSTABLE0, lvSTABLE0},
  {lvSTABLE0, lvRISING,  lvFALLING, lvRISING,  lvUNKNOWN},
  {lvSTABLE0, lvFALLING, lvFALLING, lvFALLING, lvFALLING},
  {lvSTABLE0, lvRISING,  lvFALLING, lvSTABLE1, lvUNKNOWN},
  {lvSTABLE0, lvUNKNOWN, lvFALLING, lvUNKNOWN, lvUNKNOWN}
}
Definition at line 51 of file e_node.h.
const _LOGICVAL LOGICVAL::not_truth [static, private]
Initial value:
 {
  lvSTABLE1, lvFALLING, lvRISING,  lvSTABLE0, lvUNKNOWN
}
Definition at line 52 of file e_node.h.
const _LOGICVAL LOGICVAL::or_truth [static, private]
Initial value:
 {
  {lvSTABLE0, lvRISING,  lvFALLING, lvSTABLE1, lvUNKNOWN},
  {lvRISING,  lvRISING,  lvRISING,  lvSTABLE1, lvRISING},
  {lvFALLING, lvRISING,  lvFALLING, lvSTABLE1, lvUNKNOWN},
  {lvSTABLE1, lvSTABLE1, lvSTABLE1, lvSTABLE1, lvSTABLE1},
  {lvUNKNOWN, lvRISING,  lvUNKNOWN, lvSTABLE1, lvUNKNOWN}
}
Definition at line 49 of file e_node.h.
const _LOGICVAL LOGICVAL::xor_truth [static, private]
Initial value:
 {
  {lvSTABLE0, lvRISING,  lvFALLING, lvSTABLE1, lvUNKNOWN},
  {lvRISING,  lvFALLING, lvRISING,  lvFALLING, lvUNKNOWN},
  {lvFALLING, lvRISING,  lvFALLING, lvRISING,  lvUNKNOWN},
  {lvSTABLE1, lvFALLING, lvRISING,  lvSTABLE0, lvUNKNOWN},
  {lvUNKNOWN, lvUNKNOWN, lvUNKNOWN, lvUNKNOWN, lvUNKNOWN}
}
Definition at line 50 of file e_node.h.
The documentation for this class was generated from the following files:
savant/gnucap/src/e_node.h
savant/gnucap/src/e_node.cc