gnucap: DEV_LOGIC Class Reference
DEV_LOGIC Class Reference
#include <d_logic.h>
Public Types
enum {
OUTNODE = 0, GND_NODE = 1, PWR_NODE = 2, ENABLE = 3,
BEGIN_IN = 4
}
Public Member Functions
DEV_LOGIC ()
DEV_LOGIC (const DEV_LOGIC &p)
~DEV_LOGIC ()
Static Public Member Functions
static int count ()
Private Member Functions
char id_letter () const
std::string value_name () const
bool print_type_in_spice () const
std::string dev_type () const
int tail_size () const
int max_nodes () const
int min_nodes () const
int matrix_nodes () const
int net_nodes () const
CARD * clone () const
void precalc_first ()
void expand ()
void precalc_last ()
void tr_iwant_matrix ()
void tr_begin ()
void tr_restore ()
void dc_advance ()
void tr_advance ()
void tr_regress ()
bool tr_needs_eval () const
void tr_queue_eval ()
bool do_tr ()
void tr_load ()
TIME_PAIR tr_review ()
void tr_accept ()
void tr_unload ()
double tr_involts () const
double tr_involts_limited () const
double tr_probe_num (const std::string &) const
void ac_iwant_matrix ()
void ac_begin ()
void do_ac ()
void ac_load ()
COMPLEX ac_involts () const
COMPLEX ac_amps () const
XPROBE ac_probe_ext (const std::string &) const
std::string port_name (int) const
bool tr_eval_digital ()
bool want_analog () const
bool want_digital () const
Private Attributes
int _lastchangenode
int _quality
std::string _failuremode
smode_t _oldgatemode
smode_t _gatemode
node_t nodes [PORTS_PER_GATE]
Static Private Attributes
static int _count = -1
Detailed Description
Definition at line 32 of file d_logic.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
OUTNODE
GND_NODE
PWR_NODE
ENABLE
BEGIN_IN
Definition at line 34 of file d_logic.h.
{OUTNODE=0,GND_NODE=1,PWR_NODE=2,ENABLE=3,BEGIN_IN=4}; //node labels
Constructor & Destructor Documentation
DEV_LOGIC::DEV_LOGIC () [explicit]
Definition at line 45 of file d_logic.cc.
References _count, CARD::_n, COMPONENT::attach_common(), Default_LOGIC, and nodes.
Referenced by clone().
  :ELEMENT(),
   _lastchangenode(0),
   _quality(qGOOD),
   _failuremode("ok"),
   _oldgatemode(moUNKNOWN),
   _gatemode(moUNKNOWN)
{
  attach_common(&Default_LOGIC);
  _n = nodes;
  ++_count;
}
DEV_LOGIC::DEV_LOGIC (const DEV_LOGIC & p) [explicit]
Definition at line 58 of file d_logic.cc.
References _count, CARD::_n, max_nodes(), nodes, and PORTS_PER_GATE.
  :ELEMENT(p),
   _lastchangenode(0),
   _quality(qGOOD),
   _failuremode("ok"),
   _oldgatemode(moUNKNOWN),
   _gatemode(moUNKNOWN)
{
  assert(max_nodes() == PORTS_PER_GATE);
  for (int ii = 0;  ii < max_nodes();  ++ii) {
    nodes[ii] = p.nodes[ii];
  }
  _n = nodes;
  ++_count;
}
DEV_LOGIC::~DEV_LOGIC () [inline]
Definition at line 46 of file d_logic.h.
References _count.
{--_count;}
Member Function Documentation
COMPLEX DEV_LOGIC::ac_amps () const [inline, private, virtual]
Reimplemented from ELEMENT.
Definition at line 89 of file d_logic.h.
References unreachable.
{unreachable(); return 0.;}
void DEV_LOGIC::ac_begin () [private, virtual]
Reimplemented from CARD.
Definition at line 469 of file d_logic.cc.
References CARD_LIST::ac_begin(), error(), CARD::long_label(), CARD::subckt(), and untested.
{untested();
  if (subckt()) {untested();
    subckt()->ac_begin();
  }else{untested();
    error(bWARNING, long_label() + ": no logic in AC analysis\n");
  }
}
COMPLEX DEV_LOGIC::ac_involts () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 88 of file d_logic.h.
References unreachable.
{unreachable(); return 0.;}
void DEV_LOGIC::ac_iwant_matrix () [private, virtual]
Implements ELEMENT.
Definition at line 461 of file d_logic.cc.
References CARD_LIST::ac_iwant_matrix(), and CARD::subckt().
{
  if (subckt()) {
    subckt()->ac_iwant_matrix();
  }else{
  }
}
void DEV_LOGIC::ac_load () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 87 of file d_logic.h.
References CARD_LIST::ac_load(), CARD::subckt(), and untested.
{untested();  assert(subckt());  subckt()->ac_load();}
XPROBE DEV_LOGIC::ac_probe_ext (const std::string & what) const [private, virtual]
Reimplemented from ELEMENT.
Definition at line 483 of file d_logic.cc.
References CARD::_n, NODE::ac_probe_ext(), OUTNODE, and untested.
{untested();
  return _n[OUTNODE]->ac_probe_ext(what);
}
CARD* DEV_LOGIC::clone () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 58 of file d_logic.h.
References DEV_LOGIC().
{return new DEV_LOGIC(*this);}
static int DEV_LOGIC::count () [inline, static]
Definition at line 97 of file d_logic.h.
References _count.
{return _count;}
void DEV_LOGIC::dc_advance () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 143 of file d_logic.cc.
References _gatemode, CARD::_n, _oldgatemode, CARD_LIST::dc_advance(), moANALOG, moDIGITAL, moMIXED, moUNKNOWN, OUTNODE, LOGIC_NODE::propagate(), LOGIC_NODE::set_mode(), CARD::subckt(), tr_unload(), unreachable, and untested.
{
  ELEMENT::dc_advance();
  if (_gatemode != _oldgatemode) {untested();
    tr_unload();
    _n[OUTNODE]->set_mode(_gatemode);
    _oldgatemode = _gatemode;
  }else{
  }
  switch (_gatemode) {
  case moUNKNOWN: unreachable(); break;
  case moMIXED:   unreachable(); break;
  case moANALOG:
    assert(subckt());
    subckt()->dc_advance();
    break;
  case moDIGITAL:
    if (_n[OUTNODE]->in_transit()) {
      //q_eval(); evalq is not used for DC
      _n[OUTNODE]->propagate();
    }else{
    }
    break;
  }
}
std::string DEV_LOGIC::dev_type () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 51 of file d_logic.h.
References COMPONENT::common(), and COMPONENT::has_common().
                            {assert(has_common());
    return (common()->modelname() + " " + common()->name()).c_str();}
void DEV_LOGIC::do_ac () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 86 of file d_logic.h.
References CARD_LIST::do_ac(), CARD::subckt(), and untested.
{untested();  assert(subckt());  subckt()->do_ac();}
bool DEV_LOGIC::do_tr () [private, virtual]
Reimplemented from CARD.
Definition at line 298 of file d_logic.cc.
References _gatemode, COMPONENT::converged(), moANALOG, moDIGITAL, moMIXED, moUNKNOWN, COMPONENT::set_converged(), CARD::subckt(), tr_eval_digital(), and unreachable.
{
  switch (_gatemode) {
  case moUNKNOWN: unreachable(); break;
  case moMIXED:   unreachable(); break;
  case moDIGITAL: set_converged(tr_eval_digital()); break;
  case moANALOG:  assert(subckt()); set_converged(subckt()->do_tr()); break;
  }
  return converged();
}
void DEV_LOGIC::expand () [private, virtual]
Reimplemented from COMPONENT.
Definition at line 74 of file d_logic.cc.
References _gatemode, CKT_BASE::_sim, COMPONENT::attach_model(), COMPONENT::common(), error(), CARD_LIST::expand(), CARD::find_looking_out(), COMMON_LOGIC::incount, CARD::is_constant(), SIM_DATA::is_first_expand(), CARD::long_label(), OPT::mode, COMMON_COMPONENT::model(), COMMON_COMPONENT::modelname(), COMMON_COMPONENT::name(), prechecked_cast, CARD::renew_subckt(), CARD::scope(), CARD::subckt(), to_string(), and untested.
{
  ELEMENT::expand();
  const COMMON_LOGIC* c = prechecked_cast<const COMMON_LOGIC*>(common());
  assert(c);
  attach_model();
  const MODEL_LOGIC* m = dynamic_cast<const MODEL_LOGIC*>(c->model());
  if (!m) {
    throw Exception_Model_Type_Mismatch(long_label(), c->modelname(), "logic family (LOGIC)");
  }else{
  }
  std::string subckt_name(c->modelname()+c->name()+to_string(c->incount));
  try {
    const CARD* model = find_looking_out(subckt_name);
    if(!dynamic_cast<const MODEL_SUBCKT*>(model)) {untested();
      error(((!_sim->is_first_expand()) ? (bDEBUG) : (bWARNING)),
            long_label() + ": " + subckt_name + " is not a subckt, forcing digital\n");
    }else{
      _gatemode = OPT::mode;
      renew_subckt(model, this, scope(), NULL/*&(c->_params)*/);
      subckt()->expand();
    }
  }catch (Exception_Cant_Find&) {
    error(((!_sim->is_first_expand()) ? (bDEBUG) : (bWARNING)),
          long_label() + ": can't find subckt: " + subckt_name + ", forcing digital\n");
  }
  assert(!is_constant()); /* is a BUG */
}
char DEV_LOGIC::id_letter () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 48 of file d_logic.h.
{return 'U';}
int DEV_LOGIC::matrix_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 56 of file d_logic.h.
{return 2;}
int DEV_LOGIC::max_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 54 of file d_logic.h.
References PORTS_PER_GATE.
Referenced by DEV_LOGIC(), and tr_accept().
{return PORTS_PER_GATE;}
int DEV_LOGIC::min_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 55 of file d_logic.h.
References BEGIN_IN.
{return BEGIN_IN+1;}
int DEV_LOGIC::net_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 57 of file d_logic.h.
References CARD::_net_nodes.
Referenced by tr_accept().
{return _net_nodes;}
std::string DEV_LOGIC::port_name (int) const [inline, private, virtual]
Implements COMPONENT.
Definition at line 92 of file d_logic.h.
References incomplete, and untested.
                                {untested();
    incomplete();
    return "";
  }
void DEV_LOGIC::precalc_first () [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 59 of file d_logic.h.
References CARD_LIST::precalc_first(), and CARD::subckt().
{ELEMENT::precalc_first(); if (subckt()) {subckt()->precalc_first();}}
void DEV_LOGIC::precalc_last () [inline, private, virtual]
Reimplemented from ELEMENT.
Definition at line 61 of file d_logic.h.
References CARD_LIST::precalc_last(), and CARD::subckt().
{ELEMENT::precalc_last(); if (subckt()) {subckt()->precalc_last();}}
bool DEV_LOGIC::print_type_in_spice () const [inline, private, virtual]
Reimplemented from ELEMENT.
Definition at line 50 of file d_logic.h.
{return true;}
int DEV_LOGIC::tail_size () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 53 of file d_logic.h.
{return 2;}
void DEV_LOGIC::tr_accept () [private, virtual]
Reimplemented from COMPONENT.
Definition at line 338 of file d_logic.cc.
References SIM_DATA::_bypass_ok, _failuremode, _gatemode, _lastchangenode, CARD::_n, _oldgatemode, _quality, CKT_BASE::_sim, SIM_DATA::_time0, SIM_DATA::analysis_is_restore(), SIM_DATA::analysis_is_static(), BEGIN_IN, COMPONENT::common(), LOGIC_NODE::d_iter(), MODEL_LOGIC::delay, error(), LOGIC_NODE::failure_mode(), LOGIC_NODE::force_initial_value(), SIM_DATA::iteration_tag(), COMMON_LOGIC::logic_eval(), CARD::long_label(), LOGICVAL::lv_future(), LOGIC_NODE::lv_future(), LOGICVAL::lv_old(), lvFALLING, lvRISING, lvSTABLE0, lvSTABLE1, lvUNKNOWN, max_nodes(), moANALOG, COMMON_COMPONENT::model(), moDIGITAL, net_nodes(), SIM_DATA::new_event(), OUTNODE, PORTS_PER_GATE, prechecked_cast, LOGIC_NODE::quality(), LOGIC_NODE::set_event(), LOGIC_NODE::to_logic(), trace0, trace2, trace3, unreachable, untested, want_analog(), and want_digital().
Referenced by tr_eval_digital().
{
  assert(_gatemode == moDIGITAL || _gatemode == moANALOG);
  const COMMON_LOGIC* c = prechecked_cast<const COMMON_LOGIC*>(common());
  assert(c);
  const MODEL_LOGIC* m = prechecked_cast<const MODEL_LOGIC*>(c->model());
  assert(m);
  /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */
  /* Check quality and get node info to local array. */
  /* side effect --- generate digital values for analog nodes */
  assert(PORTS_PER_GATE == max_nodes());
  {
    _n[OUTNODE]->to_logic(m);
    _quality = _n[OUTNODE]->quality();  /* the worst quality on this device */
    _failuremode = _n[OUTNODE]->failure_mode();    /* what is wrong with it? */
    _lastchangenode = OUTNODE;          /* which node changed most recently */
    int lastchangeiter=_n[OUTNODE]->d_iter();/* iteration # when it changed */
    trace0(long_label().c_str());
    trace2(_n[OUTNODE]->failure_mode().c_str(), OUTNODE, _n[OUTNODE]->quality());
    for (int ii = BEGIN_IN;  ii < net_nodes();  ++ii) {
      _n[ii]->to_logic(m);
      if (_n[ii]->quality() < _quality) {
        _quality = _n[ii]->quality();
        _failuremode = _n[ii]->failure_mode();
      }else{
      }
      if (_n[ii]->d_iter() >= lastchangeiter) {
        lastchangeiter = _n[ii]->d_iter();
        _lastchangenode = ii;
      }else{
      }
      trace2(_n[ii]->failure_mode().c_str(), ii, _n[ii]->quality());
    }
    /* If _lastchangenode == OUTNODE, no new changes, bypass may be ok.
     * Otherwise, an input changed.  Need to evaluate.
     * If all quality are good, can evaluate as digital.
     * Otherwise need to evaluate as analog.
     */
    trace3(_failuremode.c_str(), _lastchangenode, lastchangeiter, _quality);
  }
  /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */
  if (want_analog()) {
    if (_gatemode == moDIGITAL) {untested();
      error(bTRACE, "%s:%u:%g switch to analog, %s\n", long_label().c_str(),
            _sim->iteration_tag(), _sim->_time0, _failuremode.c_str());
      _oldgatemode = _gatemode;
      _gatemode = moANALOG;
    }else{
    }
    assert(_gatemode == moANALOG);
  }else{
    assert(want_digital());
    if (_gatemode == moANALOG) {
      error(bTRACE, "%s:%u:%g switch to digital\n",
            long_label().c_str(), _sim->iteration_tag(), _sim->_time0);
      _oldgatemode = _gatemode;
      _gatemode = moDIGITAL;
    }else{
    }
    assert(_gatemode == moDIGITAL);
    if (_sim->analysis_is_restore()) {untested();
    }else if (_sim->analysis_is_static()) {
    }else{
    }
    if (!_sim->_bypass_ok
        || _lastchangenode != OUTNODE
        || _sim->analysis_is_static()
        || _sim->analysis_is_restore()) {
      LOGICVAL future_state = c->logic_eval(&_n[BEGIN_IN]);
      //                         ^^^^^^^^^^
      if ((_n[OUTNODE]->is_unknown()) &&
          (_sim->analysis_is_static() || _sim->analysis_is_restore())) {
        _n[OUTNODE]->force_initial_value(future_state);
        /* This happens when initial DC is digital.
         * Answers could be wrong if order in netlist is reversed
         */
      }else if (future_state != _n[OUTNODE]->lv()) {
        assert(future_state != lvUNKNOWN);
        switch (future_state) {
        case lvSTABLE0: /*nothing*/             break;
        case lvRISING:  future_state=lvSTABLE0; break;
        case lvFALLING: future_state=lvSTABLE1; break;
        case lvSTABLE1: /*nothing*/             break;
        case lvUNKNOWN: unreachable();          break;
        }
        /* This handling of rising and falling may seem backwards.
         * These states occur when the value has been contaminated
         * by another pending action.  The "old" value is the
         * value without this contamination.
         * This code is planned for replacement as part of VHDL/Verilog
         * conversion, so the kluge stays in for now.
         */
        assert(future_state.lv_old() == future_state.lv_future());
        if (_n[OUTNODE]->lv() == lvUNKNOWN
            || future_state.lv_future() != _n[OUTNODE]->lv_future()) {
          _n[OUTNODE]->set_event(m->delay, future_state);
          _sim->new_event(_n[OUTNODE]->final_time());
          //assert(future_state == _n[OUTNODE].lv_future());
          if (_lastchangenode == OUTNODE) {
            unreachable();
            error(bDANGER, "%s:%u:%g non-event state change\n",
                  long_label().c_str(), _sim->iteration_tag(), _sim->_time0);
          }else{
          }
        }else{
        }
      }else{
      }
    }else{
    }
  }
}
void DEV_LOGIC::tr_advance () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 173 of file d_logic.cc.
References _gatemode, CARD::_n, _oldgatemode, CKT_BASE::_sim, SIM_DATA::_time0, LOGIC_NODE::final_time(), moANALOG, moDIGITAL, moMIXED, moUNKNOWN, OUTNODE, LOGIC_NODE::propagate(), COMPONENT::q_eval(), LOGIC_NODE::set_mode(), CARD::subckt(), CARD_LIST::tr_advance(), tr_unload(), unreachable, and untested.
{
  ELEMENT::tr_advance();
  if (_gatemode != _oldgatemode) {
    tr_unload();
    _n[OUTNODE]->set_mode(_gatemode);
    _oldgatemode = _gatemode;
  }else{
  }
  switch (_gatemode) {
  case moUNKNOWN: unreachable(); break;
  case moMIXED:   unreachable(); break;
  case moANALOG:
    assert(subckt());
    subckt()->tr_advance();
    break;
  case moDIGITAL:
    if (_n[OUTNODE]->in_transit()) {
      q_eval();
      if (_sim->_time0 >= _n[OUTNODE]->final_time()) {
        _n[OUTNODE]->propagate();
      }else{untested();
      }
    }else{
    }
    break;
  }
}
void DEV_LOGIC::tr_begin () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 117 of file d_logic.cc.
References _gatemode, CARD::_n, _oldgatemode, moANALOG, OPT::mode, moDIGITAL, moMIXED, OUTNODE, LOGIC_NODE::set_mode(), CARD::subckt(), and CARD_LIST::tr_begin().
{
  ELEMENT::tr_begin();
  if (!subckt()) {
    _gatemode = moDIGITAL;
    _n[OUTNODE]->set_mode(_gatemode);
    _oldgatemode = _gatemode;
  }else{
    _gatemode = (OPT::mode==moMIXED) ? moANALOG : OPT::mode;
    _n[OUTNODE]->set_mode(_gatemode);
    _oldgatemode = _gatemode;
    subckt()->tr_begin();
  }
}
bool DEV_LOGIC::tr_eval_digital () [private]
Definition at line 268 of file d_logic.cc.
References _gatemode, ELEMENT::_m0, CARD::_n, CKT_BASE::_sim, ELEMENT::_y, SIM_DATA::analysis_is_restore(), SIM_DATA::analysis_is_static(), SIM_DATA::analysis_is_tran_dynamic(), CPOLY1::c0, CPOLY1::c1, COMPONENT::common(), ELEMENT::conv_check(), COMPONENT::converged(), FPOLY1::f0, FPOLY1::f1, COMMON_COMPONENT::model(), moDIGITAL, OUTNODE, prechecked_cast, COMPONENT::q_load(), MODEL_LOGIC::rs, COMPONENT::set_converged(), ELEMENT::store_values(), LOGIC_NODE::to_analog(), tr_accept(), untested, FPOLY1::x, and CPOLY1::x.
Referenced by do_tr().
{
  assert(_gatemode == moDIGITAL);
  if (_sim->analysis_is_restore()) {untested();
  }else if (_sim->analysis_is_static()) {
  }else{
  }
  if (_sim->analysis_is_static() || _sim->analysis_is_restore()) {
    tr_accept();
  }else{
    assert(_sim->analysis_is_tran_dynamic());
  }
  const COMMON_LOGIC* c = prechecked_cast<const COMMON_LOGIC*>(common());
  assert(c);
  const MODEL_LOGIC* m = prechecked_cast<const MODEL_LOGIC*>(c->model());
  assert(m);
  _y[0].x = 0.;
  _y[0].f1 = _n[OUTNODE]->to_analog(m);
  _y[0].f0 = 0.;
  _m0.x = 0.;
  _m0.c1 = 1./m->rs;
  _m0.c0 = _y[0].f1 / -m->rs;
  set_converged(conv_check());
  store_values();
  q_load();
  return converged();
}
double DEV_LOGIC::tr_involts () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 77 of file d_logic.h.
References unreachable.
{unreachable(); return 0;}
double DEV_LOGIC::tr_involts_limited () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 79 of file d_logic.h.
References unreachable.
{unreachable(); return 0;}
void DEV_LOGIC::tr_iwant_matrix () [private, virtual]
Implements ELEMENT.
Definition at line 108 of file d_logic.cc.
References CARD::subckt(), CARD_LIST::tr_iwant_matrix(), and ELEMENT::tr_iwant_matrix_passive().
{
  if (subckt()) {
    subckt()->tr_iwant_matrix();
  }else{
  }
  tr_iwant_matrix_passive();
}
void DEV_LOGIC::tr_load () [private, virtual]
Reimplemented from CARD.
Definition at line 309 of file d_logic.cc.
References _gatemode, moANALOG, moDIGITAL, moMIXED, moUNKNOWN, CARD::subckt(), CARD_LIST::tr_load(), ELEMENT::tr_load_passive(), and unreachable.
{
  switch (_gatemode) {
  case moUNKNOWN: unreachable(); break;
  case moMIXED:   unreachable(); break;
  case moDIGITAL: tr_load_passive(); break;
  case moANALOG:  assert(subckt()); subckt()->tr_load(); break;
  }
}
bool DEV_LOGIC::tr_needs_eval () const [private, virtual]
Reimplemented from ELEMENT.
Definition at line 236 of file d_logic.cc.
References _gatemode, CKT_BASE::_sim, SIM_DATA::analysis_is_restore(), SIM_DATA::analysis_is_static(), COMPONENT::is_q_for_eval(), moANALOG, moDIGITAL, moMIXED, moUNKNOWN, CARD::subckt(), CARD_LIST::tr_needs_eval(), unreachable, and untested.
{
  switch (_gatemode) {
  case moUNKNOWN: unreachable(); break;
  case moMIXED:   unreachable(); break;
  case moDIGITAL:
    //assert(!is_q_for_eval());
    if (_sim->analysis_is_restore()) {untested();
    }else if (_sim->analysis_is_static()) {
    }else{
    }
    return (_sim->analysis_is_static() || _sim->analysis_is_restore());
  case moANALOG:
    untested();
    assert(!is_q_for_eval());
    assert(subckt());
    return subckt()->tr_needs_eval();
  }
  unreachable();
  return false;
}
double DEV_LOGIC::tr_probe_num (const std::string & what) const [private, virtual]
Reimplemented from ELEMENT.
Definition at line 478 of file d_logic.cc.
References CARD::_n, OUTNODE, and LOGIC_NODE::tr_probe_num().
{
  return _n[OUTNODE]->tr_probe_num(what);
}
void DEV_LOGIC::tr_queue_eval () [private, virtual]
Reimplemented from COMPONENT.
Definition at line 258 of file d_logic.cc.
References _gatemode, moANALOG, moDIGITAL, moMIXED, moUNKNOWN, CARD::subckt(), CARD_LIST::tr_queue_eval(), and unreachable.
{
  switch (_gatemode) {
  case moUNKNOWN: unreachable(); break;
  case moMIXED:   unreachable(); break;
  case moDIGITAL: ELEMENT::tr_queue_eval(); break;
  case moANALOG:  assert(subckt()); subckt()->tr_queue_eval(); break;
  }
}
void DEV_LOGIC::tr_regress () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 202 of file d_logic.cc.
References _gatemode, CARD::_n, _oldgatemode, CKT_BASE::_sim, SIM_DATA::_time0, LOGIC_NODE::final_time(), itested, moANALOG, moDIGITAL, moMIXED, moUNKNOWN, OUTNODE, LOGIC_NODE::propagate(), COMPONENT::q_eval(), LOGIC_NODE::set_mode(), CARD::subckt(), CARD_LIST::tr_regress(), tr_unload(), and unreachable.
{itested();
  ELEMENT::tr_regress();
  if (_gatemode != _oldgatemode) {itested();
    tr_unload();
    _n[OUTNODE]->set_mode(_gatemode);
    _oldgatemode = _gatemode;
  }else{itested();
  }
  switch (_gatemode) {
  case moUNKNOWN: unreachable(); break;
  case moMIXED:   unreachable(); break;
  case moANALOG:  itested();
    assert(subckt());
    subckt()->tr_regress();
    break;
  case moDIGITAL: itested();
    if (_n[OUTNODE]->in_transit()) {itested();
      q_eval();
      if (_sim->_time0 >= _n[OUTNODE]->final_time()) {itested();
        _n[OUTNODE]->propagate();
      }else{itested();
      }
    }else{itested();
    }
    break;
  }
}
void DEV_LOGIC::tr_restore () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 132 of file d_logic.cc.
References _gatemode, moANALOG, OPT::mode, moDIGITAL, moMIXED, CARD::subckt(), CARD_LIST::tr_restore(), and untested.
{untested();
  ELEMENT::tr_restore();
  if (!subckt()) {untested();
    _gatemode = moDIGITAL;
  }else{untested();
    _gatemode = (OPT::mode==moMIXED) ? moANALOG : OPT::mode;
    subckt()->tr_restore();
  }
}
TIME_PAIR DEV_LOGIC::tr_review () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 319 of file d_logic.cc.
References _gatemode, COMPONENT::_time_by, moANALOG, moDIGITAL, moMIXED, moUNKNOWN, COMPONENT::q_accept(), TIME_PAIR::reset(), CARD::subckt(), CARD_LIST::tr_review(), and unreachable.
{
  // not calling ELEMENT::tr_review();
  q_accept();
  //digital mode queues events explicitly in tr_accept
  switch (_gatemode) {
  case moUNKNOWN: unreachable(); break;
  case moMIXED:   unreachable(); break;
  case moDIGITAL: _time_by.reset(); break;
  case moANALOG:  assert(subckt()); _time_by = subckt()->tr_review(); break;
  }
  return _time_by;
}
void DEV_LOGIC::tr_unload () [private, virtual]
Reimplemented from CARD.
Definition at line 452 of file d_logic.cc.
References CARD::subckt(), CARD_LIST::tr_unload(), ELEMENT::tr_unload_passive(), and untested.
Referenced by dc_advance(), tr_advance(), and tr_regress().
{
  if (subckt()) {
    subckt()->tr_unload();
  }else{untested();
  }
  tr_unload_passive();
}
std::string DEV_LOGIC::value_name () const [inline, private, virtual]
Implements CARD.
Definition at line 49 of file d_logic.h.
{return "#";}
bool DEV_LOGIC::want_analog () const [private]
Definition at line 488 of file d_logic.cc.
References _quality, moANALOG, OPT::mode, moMIXED, qGOOD, and CARD::subckt().
Referenced by tr_accept().
{
  return subckt() &&
    ((OPT::mode == moANALOG) || (OPT::mode == moMIXED && _quality != qGOOD));
}
bool DEV_LOGIC::want_digital () const [private]
Definition at line 494 of file d_logic.cc.
References _quality, OPT::mode, moDIGITAL, moMIXED, qGOOD, and CARD::subckt().
Referenced by tr_accept().
{
  return !subckt() ||
    ((OPT::mode == moDIGITAL) || (OPT::mode == moMIXED && _quality == qGOOD));
}
Member Data Documentation
int DEV_LOGIC::_count = -1 [static, private]
Definition at line 41 of file d_logic.h.
Referenced by count(), DEV_LOGIC(), and ~DEV_LOGIC().
std::string DEV_LOGIC::_failuremode [private]
Definition at line 38 of file d_logic.h.
Referenced by tr_accept().
smode_t DEV_LOGIC::_gatemode [private]
Definition at line 40 of file d_logic.h.
Referenced by dc_advance(), do_tr(), expand(), tr_accept(), tr_advance(), tr_begin(), tr_eval_digital(), tr_load(), tr_needs_eval(), tr_queue_eval(), tr_regress(), tr_restore(), and tr_review().
int DEV_LOGIC::_lastchangenode [private]
Definition at line 36 of file d_logic.h.
Referenced by tr_accept().
smode_t DEV_LOGIC::_oldgatemode [private]
Definition at line 39 of file d_logic.h.
Referenced by dc_advance(), tr_accept(), tr_advance(), tr_begin(), and tr_regress().
int DEV_LOGIC::_quality [private]
Definition at line 37 of file d_logic.h.
Referenced by tr_accept(), want_analog(), and want_digital().
node_t DEV_LOGIC::nodes[PORTS_PER_GATE] [private]
Definition at line 42 of file d_logic.h.
Referenced by DEV_LOGIC().
The documentation for this class was generated from the following files:
savant/gnucap/src/d_logic.h
savant/gnucap/src/d_logic.cc