gnucap: anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE Class Reference
anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE Class Reference
Public Types
enum EOB { NO_EXIT_ON_BLANK, EXIT_ON_BLANK }
Public Member Functions
std::string arg_front () const
std::string arg_mid () const
std::string arg_back () const
DEV_COMMENT * parse_comment (CS &, DEV_COMMENT *)
DEV_DOT * parse_command (CS &, DEV_DOT *)
MODEL_CARD * parse_paramset (CS &, MODEL_CARD *)
MODEL_SUBCKT * parse_module (CS &, MODEL_SUBCKT *)
COMPONENT * parse_instance (CS &, COMPONENT *)
std::string find_type_in_string (CS &)
void parse_module_body (CS &, MODEL_SUBCKT *, CARD_LIST *, const std::string &, EOB, const std::string &)
Private Member Functions
void parse_type (CS &, CARD *)
void parse_args (CS &, CARD *)
void parse_label (CS &, CARD *)
void parse_ports (CS &, COMPONENT *, int minnodes, int start, int num_nodes, bool all_new)
void parse_element_using_obsolete_callback (CS &, COMPONENT *)
void parse_logic_using_obsolete_callback (CS &, COMPONENT *)
void print_paramset (OMSTREAM &, const MODEL_CARD *)
void print_module (OMSTREAM &, const MODEL_SUBCKT *)
void print_instance (OMSTREAM &, const COMPONENT *)
void print_comment (OMSTREAM &, const DEV_COMMENT *)
void print_command (OMSTREAM &, const DEV_DOT *)
void print_args (OMSTREAM &, const MODEL_CARD *)
void print_type (OMSTREAM &, const COMPONENT *)
void print_args (OMSTREAM &, const COMPONENT *)
void print_label (OMSTREAM &, const COMPONENT *)
void print_ports (OMSTREAM &, const COMPONENT *)
Detailed Description
Definition at line 36 of file lang_spice.cc.
Member Enumeration Documentation
enum anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::EOB
Enumerator:
NO_EXIT_ON_BLANK
EXIT_ON_BLANK
Definition at line 38 of file lang_spice.cc.
{NO_EXIT_ON_BLANK, EXIT_ON_BLANK};
Member Function Documentation
std::string anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::arg_back () const [inline, virtual]
Implements LANGUAGE.
Definition at line 43 of file lang_spice.cc.
{return "";}
std::string anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::arg_front () const [inline, virtual]
Implements LANGUAGE.
Definition at line 41 of file lang_spice.cc.
{return " ";}
std::string anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::arg_mid () const [inline, virtual]
Implements LANGUAGE.
Definition at line 42 of file lang_spice.cc.
{return "=";}
std::string anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::find_type_in_string (CS & cmd) [virtual]
Implements LANGUAGE.
Definition at line 619 of file lang_spice.cc.
References ANTI_COMMENT, OPT::case_insensitive, anonymous_namespace{c_attach.cc}::command_dispatcher, CS::cursor(), CS::peek(), CS::reset(), CS::scan(), CS::skip(), CS::substr(), CS::trimmed_last_match(), CS::umatch(), and untested.
{
  cmd.umatch(ANTI_COMMENT); /* skip mark so spice ignores but gnucap reads */
  unsigned here = cmd.cursor();
  std::string s;
  char id_letter = cmd.peek();
  if (OPT::case_insensitive) {
    id_letter = static_cast<char>(toupper(id_letter));
  }else{
  }
  switch (id_letter) {
  case '\0':untested();
    s = "";
    break;
  case '.':
    cmd >> s;
    cmd.reset(here);
    if (!command_dispatcher[s]) {
      cmd.skip();
      ++here;
      s = s.substr(1);
    }else{
    }
    break;
  case 'G':
    here = cmd.cursor();
    if (cmd.scan("vccap |vcg |vcr |vccs ")) {
      s = cmd.trimmed_last_match();
    }else{
      s = "G";
    }
    break;
  default:
    s = id_letter;
    break;
  }
  cmd.reset(here);
  return s;
}
void anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_args (CS & cmd, CARD * x) [private]
Definition at line 412 of file lang_spice.cc.
References CS::ctos(), CS::cursor(), CS::is_float(), itested, CARD::long_label(), CS::match1(), CS::more(), CARD::set_param_by_name(), CS::skip1b(), CS::skiparg(), CS::stuck(), untested, CARD::use_obsolete_callback_parse(), CARD::value_name(), and CS::warn().
{
  assert(x);
  COMPONENT* xx = dynamic_cast<COMPONENT*>(x);
  cmd >> "params:";     // optional, skip it.
  if (!x->use_obsolete_callback_parse()) {
    int paren = cmd.skip1b('(');
    if (xx && cmd.is_float()) {         // simple unnamed value
      std::string value;
      cmd >> value;
      x->set_param_by_name(xx->value_name(), value);
    }else if (cmd.match1("'{")) {       // quoted unnamed value
      std::string value;
      cmd >> value; // strips off the quotes
      value = '{' + value + '}'; // put them back
      x->set_param_by_name(xx->value_name(), value);
    }else{                              // only name=value pairs
    }
    unsigned here = cmd.cursor();
    for (int i=0; ; ++i) {
      if (paren && cmd.skip1b(')')) {
        break;
      }else if (!cmd.more()) {
        break;
      }else{
        std::string Name  = cmd.ctos("=", "", "");
        cmd >> '=';
        std::string value = cmd.ctos(",=;)", "\"'{(", "\"'})");
        unsigned there = here;
        if (cmd.stuck(&here)) {untested();
          break;
        }else{
          try{
            if (value == "") {
              cmd.warn(bDANGER, there, x->long_label() + ": " + Name + " has no value?");
            }else{
            }
            x->set_param_by_name(Name, value);
          }catch (Exception_No_Match&) {itested();
            cmd.warn(bDANGER, there, x->long_label() + ": bad parameter " + Name + " ignored");
          }
        }
      }
    }
  }else if (MODEL_CARD* pp = dynamic_cast<MODEL_CARD*>(x)) {
    // used only for "table"
    int paren = cmd.skip1b('(');
    bool in_error = false;
    for (;;) {
      unsigned here = cmd.cursor();
      pp->parse_params_obsolete_callback(cmd);  //BUG//callback//
      if (!cmd.more()) {
        break;
      }else if (paren && cmd.skip1b(')')) {untested();
        break;
      }else if (cmd.stuck(&here)) {untested();
        if (in_error) {untested();
          // so you don't get two errors on name = value.
          cmd.skiparg();
          in_error = false;
        }else{untested();
          cmd.warn(bDANGER, "bad paramerter -- ignored");
          cmd.skiparg().skip1b("=");
          in_error = true;
        }
      }else{
        in_error = false;
      }
    }
  }else{untested();
    // using obsolete_callback
  }
}
DEV_DOT * anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_command (CS & cmd, DEV_DOT * x) [virtual]
Implements LANGUAGE.
Definition at line 504 of file lang_spice.cc.
References CARD_LIST::card_list, CMD::cmdproc(), anonymous_namespace{c_attach.cc}::command_dispatcher, CS::cursor(), CS::fullstring(), CARD::owner(), CS::reset(), DEV_DOT::set(), CS::skip(), anonymous_namespace{lang_spice.cc}::skip_pre_stuff(), and CARD::subckt().
{
  assert(x);
  x->set(cmd.fullstring());
  CARD_LIST* scope = (x->owner()) ? x->owner()->subckt() : &CARD_LIST::card_list;
  cmd.reset();
  skip_pre_stuff(cmd);
  unsigned here = cmd.cursor();
  std::string s;
  cmd >> s;
  cmd.reset(here);
  if (!command_dispatcher[s]) {
    cmd.skip();
    ++here;
  }else{
  }
  CMD::cmdproc(cmd, scope);
  delete x;
  return NULL;
}
DEV_COMMENT * anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_comment (CS & cmd, DEV_COMMENT * x) [virtual]
Implements LANGUAGE.
Definition at line 497 of file lang_spice.cc.
References CS::fullstring(), and DEV_COMMENT::set().
{
  assert(x);
  x->set(cmd.fullstring());
  return x;
}
void anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_element_using_obsolete_callback (CS & cmd, COMPONENT * x) [private]
Definition at line 291 of file lang_spice.cc.
References CARD::_net_nodes, COMPONENT::attach_common(), anonymous_namespace{bm_complex.cc}::bm_dispatcher, CS::check(), anonymous_namespace{lang_spice.cc}::count_ports(), CS::cursor(), COMMON_COMPONENT::deflate(), COMMON_COMPONENT::is_trivial(), COMPONENT::max_nodes(), COMPONENT::min_nodes(), COMPONENT::num_current_ports(), COMPONENT::obsolete_move_parameters_from_common(), COMMON_COMPONENT::parse_common_obsolete_callback(), EVAL_BM_ACTION_BASE::parse_func_type(), anonymous_namespace{lang_spectre.cc}::parse_ports(), CS::reset(), ELEMENT::skip_dev_type(), CS::stuck(), untested, and CS::warn().
{
  assert(x);
  ELEMENT* xx = dynamic_cast<ELEMENT*>(x);
  assert(xx);
  {
    unsigned here = cmd.cursor();
    int stop_nodes = x->max_nodes() - x->num_current_ports();
    int num_nodes = count_ports(cmd, stop_nodes, 0,  0,   0);
    //                               max         min tail already_got
    cmd.reset(here);
    parse_ports(cmd, x, 0,  0,          num_nodes, false);
    //                  min already_got
  }
  int gotnodes = x->_net_nodes;
  COMMON_COMPONENT* c = NULL;
  if (gotnodes < x->min_nodes()) {
    // HSPICE compatibility kluge.
    // The device type or function type could be stuck between the nodes.
    xx->skip_dev_type(cmd); // (redundant)
    c = EVAL_BM_ACTION_BASE::parse_func_type(cmd);
    {
      unsigned here = cmd.cursor();
      int num_nodes = count_ports(cmd, x->max_nodes(), x->min_nodes(), 0, gotnodes);
      cmd.reset(here);
      parse_ports(cmd, x, x->min_nodes(), gotnodes, num_nodes, false);
    }
  }else{
    // Normal mode.  nodes first, then data.
  }
  if (!c) {
    xx->skip_dev_type(cmd); // (redundant)
    c = bm_dispatcher.clone("eval_bm_cond");
  }else{
  }
  if (!c) {
    c = bm_dispatcher.clone("eval_bm_value");
  }else{
  }
  assert(c);
  // we have a blank common of the most general type
  // (or HSPICE kluge)
  // let it continue parsing
  unsigned here = cmd.cursor();
  c->parse_common_obsolete_callback(cmd); //BUG//callback
  if (cmd.stuck(&here)) {untested();
    cmd.warn(bDANGER, "needs a value");
  }else{
  }
  // At this point, there is ALWAYS a common "c", which may have more
  // commons attached to it.  Try to reduce its complexity.
  // "c->deflate()" may return "c" or some simplification of "c".
  COMMON_COMPONENT* dc = c->deflate();
  // dc == deflated_common
  // It might be just "c".
  // It might be something else that is simpler but equivalent.
  if (dc->is_trivial()) {
    assert(dynamic_cast<EVAL_BM_VALUE*>(dc));
    // If it is a simple value, don't use a common.
    // Just store the value directly.
    x->obsolete_move_parameters_from_common(dc);
    delete c;
  }else{
    x->attach_common(dc);
    if (dc != c) {
      delete c;
    }else{
    }
  }
  cmd.check(bDANGER, "what's this?");
}
COMPONENT * anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_instance (CS & cmd, COMPONENT * x) [virtual]
Implements LANGUAGE.
Definition at line 582 of file lang_spice.cc.
References ANTI_COMMENT, anonymous_namespace{lang_spice.cc}::count_ports(), CS::cursor(), COMPONENT::max_nodes(), COMPONENT::min_nodes(), anonymous_namespace{lang_spectre.cc}::parse_args(), anonymous_namespace{lang_gschem.cc}::parse_label(), anonymous_namespace{lang_spectre.cc}::parse_ports(), anonymous_namespace{lang_gschem.cc}::parse_type(), COMPONENT::print_type_in_spice(), CS::reset(), CS::skip1b(), COMPONENT::tail_size(), CS::umatch(), COMPONENT::use_obsolete_callback_parse(), and CS::warn().
{
  try {
    assert(x);
    cmd.reset().umatch(ANTI_COMMENT);
    // ACS dot type specifier
    if (cmd.skip1b('.')) {
      parse_type(cmd, x);
    }else{
    }
    parse_label(cmd, x);
    if (x->use_obsolete_callback_parse()) {
      parse_element_using_obsolete_callback(cmd, x);
    }else if (DEV_LOGIC* xx = dynamic_cast<DEV_LOGIC*>(x)) {
      parse_logic_using_obsolete_callback(cmd, xx);
    }else{
      {
        unsigned here = cmd.cursor();
        int num_nodes = count_ports(cmd, x->max_nodes(), x->min_nodes(), x->tail_size(), 0);
        cmd.reset(here);
        parse_ports(cmd, x, x->min_nodes(), 0/*start*/, num_nodes, false);
      }
      if (x->print_type_in_spice()) {
        parse_type(cmd, x);
      }else{
      }
      parse_args(cmd, x);
    }
  }catch (Exception& e) {
    cmd.warn(bDANGER, e.message());
  }
  return x;
}
void anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_label (CS & cmd, CARD * x) [private]
Definition at line 488 of file lang_spice.cc.
References CKT_BASE::set_label().
{
  assert(x);
  std::string my_name;
  cmd >> my_name;
  x->set_label(my_name);
}
void anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_logic_using_obsolete_callback (CS & cmd, COMPONENT * x) [private]
Definition at line 371 of file lang_spice.cc.
References COMPONENT::attach_common(), anonymous_namespace{lang_spice.cc}::count_ports(), CS::ctos(), CS::cursor(), COMMON_LOGIC::incount, itested, COMPONENT::max_nodes(), COMPONENT::min_nodes(), COMPONENT::net_nodes(), anonymous_namespace{lang_spectre.cc}::parse_ports(), CS::reset(), COMMON_COMPONENT::set_modelname(), COMPONENT::tail_size(), TOKENTERM, CS::umatch(), untested, and CS::warn().
{
  assert(x);
  {
    unsigned here = cmd.cursor();
    int num_nodes = count_ports(cmd, x->max_nodes(), x->min_nodes(), x->tail_size(), 0/*start*/);
    cmd.reset(here);
    parse_ports(cmd, x, x->min_nodes(), 0/*start*/, num_nodes, false);
  }
  int incount = x->net_nodes() - x->min_nodes() + 1;
  assert(incount > 0);
  std::string modelname = cmd.ctos(TOKENTERM);
  COMMON_LOGIC* common = 0;
  if      (cmd.umatch("and " )) {untested();common = new LOGIC_AND;}
  else if (cmd.umatch("nand ")) {common = new LOGIC_NAND;}
  else if (cmd.umatch("or "  )) {untested();common = new LOGIC_OR;}
  else if (cmd.umatch("nor " )) {common = new LOGIC_NOR;}
  else if (cmd.umatch("xor " )) {untested();common = new LOGIC_XOR;}
  else if (cmd.umatch("xnor ")) {untested();common = new LOGIC_XNOR;}
  else if (cmd.umatch("inv " )) {common = new LOGIC_INV;}
  else {itested();
    cmd.warn(bWARNING,"need and,nand,or,nor,xor,xnor,inv");
    common=new LOGIC_NONE;
  }
  assert(common);
  common->incount = incount;
  common->set_modelname(modelname);
  x->attach_common(common);
}
MODEL_SUBCKT * anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_module (CS & cmd, MODEL_SUBCKT * x) [virtual]
Implements LANGUAGE.
Definition at line 541 of file lang_spice.cc.
References anonymous_namespace{lang_spice.cc}::count_ports(), CS::cursor(), MODEL_SUBCKT::max_nodes(), MODEL_SUBCKT::min_nodes(), CARD_LIST::params(), PARAM_LIST::parse(), anonymous_namespace{lang_gschem.cc}::parse_label(), anonymous_namespace{lang_spectre.cc}::parse_ports(), CS::reset(), and CARD::subckt().
Referenced by anonymous_namespace{lang_spice.cc}::CMD_SUBCKT::do_it().
{
  assert(x);
  // header
  cmd.reset();
  (cmd >> ".subckt |.macro ");
  parse_label(cmd, x);
  {
    unsigned here = cmd.cursor();
    int num_nodes = count_ports(cmd, x->max_nodes(), x->min_nodes(),
                                0/*no unnamed par*/, 0/*start*/);
    cmd.reset(here);
    parse_ports(cmd, x, x->min_nodes(), 0/*start*/, num_nodes, true/*all new*/);
  }
  x->subckt()->params()->parse(cmd);
  // body
  parse_module_body(cmd, x, x->subckt(), name() + "-subckt>", NO_EXIT_ON_BLANK, ".ends |.eom ");
  return x;
}
void anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_module_body (CS & cmd, MODEL_SUBCKT * x, CARD_LIST * Scope, const std::string & prompt, EOB exit_on_blank, const std::string & exit_key)
Definition at line 563 of file lang_spice.cc.
References CS::get_line(), CS::is_end(), anonymous_namespace{lang_spice.cc}::skip_pre_stuff(), and CS::umatch().
Referenced by anonymous_namespace{lang_spice.cc}::CMD_BUILD::do_it(), and anonymous_namespace{lang_spice.cc}::getmerge().
{
  try {
    for (;;) {
      cmd.get_line(prompt);
      if ((exit_on_blank==EXIT_ON_BLANK && cmd.is_end())
          || cmd.umatch(exit_key)) {
        break;
      }else{
        skip_pre_stuff(cmd);
        new__instance(cmd, x, Scope);
      }
    }
  }catch (Exception_End_Of_Input& e) {
  }
}
MODEL_CARD * anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_paramset (CS & cmd, MODEL_CARD * x) [virtual]
Implements LANGUAGE.
Definition at line 529 of file lang_spice.cc.
References CS::check(), anonymous_namespace{lang_spectre.cc}::parse_args(), anonymous_namespace{lang_gschem.cc}::parse_label(), anonymous_namespace{lang_gschem.cc}::parse_type(), and CS::reset().
Referenced by anonymous_namespace{lang_spice.cc}::CMD_MODEL::do_it().
{
  assert(x);
  cmd.reset();
  cmd >> ".model ";
  parse_label(cmd, x);
  parse_type(cmd, x);
  parse_args(cmd, x);
  cmd.check(bWARNING, "what's this?");
  return x;
}
void anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_ports (CS & cmd, COMPONENT * x, int minnodes, int start, int num_nodes, bool all_new) [private]
Definition at line 217 of file lang_spice.cc.
References CS::cursor(), itested, OPT::keys_between_nodes, CS::more(), COMPONENT::node_is_connected(), COMPONENT::node_is_grounded(), CS::reset(), COMPONENT::set_port_by_index(), COMPONENT::set_port_to_ground(), CS::skip1b(), CS::stuck(), to_string(), CS::umatch(), untested, and CS::warn().
{
  assert(x);
  int paren = cmd.skip1b('(');
  int ii = start;
  unsigned here1 = cmd.cursor();
  try{
    for (;;) {
      here1 = cmd.cursor();
      if (paren && cmd.skip1b(')')) {
        --paren;
        break; // done.  have closing paren.
      }else if (ii >= num_nodes) {
        break; // done.  have maxnodes.
      }else if (!cmd.more()) {untested();
        break; // done.  premature end of line.
      }else if (OPT::keys_between_nodes &&
                (cmd.umatch("poly ")
                 || cmd.umatch("pwl ")
                 || cmd.umatch("vccap ")
                 || cmd.umatch("vcg ")
                 || cmd.umatch("vcr "))
                ) {
        cmd.reset(here1);
        break; // done, found reserved word between nodes
      }else{
        //----------------------
        unsigned here = cmd.cursor();
        std::string node_name;
        cmd >> node_name;
        if (cmd.stuck(&here)) {itested();
          // didn't move, probably a terminator.
          throw Exception("bad node name");
        }else{
          // legal node name, store it.
          x->set_port_by_index(ii, node_name);
        }
        //----------------------
        if (!(x->node_is_connected(ii))) {untested();
          break; // illegal node name, might be proper exit.
        }else{
          if (all_new) {
            if (x->node_is_grounded(ii)) {untested();
              cmd.warn(bDANGER, here1, "node 0 not allowed here");
            }else{
            }
          }else{
          }
          ++ii;
        }
      }
    }
  }catch (Exception& e) {itested();
    cmd.warn(bDANGER, here1, e.message());
  }
  if (ii < minnodes) {itested();
    cmd.warn(bDANGER, "need " + to_string(minnodes-ii) +" more nodes");
  }else{
  }
  if (paren != 0) {untested();
    cmd.warn(bWARNING, "need )");
  }else{
  }
  //assert(x->_net_nodes == ii);
  // ground unused input nodes
  for (int iii = ii;  iii < minnodes;  ++iii) {itested();
    x->set_port_to_ground(iii);
  }
  //assert(x->_net_nodes >= ii);
}
void anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_type (CS & cmd, CARD * x) [private]
Definition at line 404 of file lang_spice.cc.
References CARD::set_dev_type().
{
  assert(x);
  std::string new_type;
  cmd >> new_type;
  x->set_dev_type(new_type);
}
void anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_args (OMSTREAM & o, const MODEL_CARD * x) [private]
Definition at line 735 of file lang_spice.cc.
References MODEL_CARD::param_count(), CARD::param_count_dont_print(), MODEL_CARD::param_is_printable(), MODEL_CARD::param_name(), MODEL_CARD::param_value(), CARD::print_args_obsolete_callback(), and CARD::use_obsolete_callback_print().
{
  assert(x);
  if (x->use_obsolete_callback_print()) {
    x->print_args_obsolete_callback(o, this);  //BUG//callback//
  }else{
    for (int ii = x->param_count() - 1;  ii >= x->param_count_dont_print();  --ii) {
      if (x->param_is_printable(ii)) {
        std::string arg = " " + x->param_name(ii) + "=" + x->param_value(ii);
        o << arg;
      }else{
      }
    }
  }
}
void anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_args (OMSTREAM & o, const COMPONENT * x) [private]
Definition at line 763 of file lang_spice.cc.
References COMPONENT::param_count(), CARD::param_count_dont_print(), COMPONENT::param_is_printable(), COMPONENT::param_name(), COMPONENT::param_value(), COMPONENT::print_args_obsolete_callback(), COMPONENT::use_obsolete_callback_print(), and CARD::value_name().
{
  assert(x);
  o << ' ';
  if (x->use_obsolete_callback_print()) {
    x->print_args_obsolete_callback(o, this);  //BUG//callback//
  }else{
    for (int ii = x->param_count() - 1;  ii >= x->param_count_dont_print();  --ii) {
      if (x->param_is_printable(ii)) {
        if ((ii != x->param_count() - 1) || (x->param_name(ii) != x->value_name())) {
          // skip name if plain value
          o << " " << x->param_name(ii) << "=";
        }else{
        }
        o << x->param_value(ii);
      }else{
      }
    }
  }
}
void anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_command (OMSTREAM & o, const DEV_DOT * x) [private, virtual]
Implements LANGUAGE.
Definition at line 728 of file lang_spice.cc.
References DEV_DOT::s().
{
  assert(x);
  o << x->s() << '\n';
}
void anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_comment (OMSTREAM & o, const DEV_COMMENT * x) [private, virtual]
Implements LANGUAGE.
Definition at line 717 of file lang_spice.cc.
References DEV_COMMENT::comment().
{
  assert(x);
  if (x->comment()[1] != '+') {
    o << x->comment() << '\n';
  }else{
  }
  // Suppress printing of comment lines starting with "*+".
  // These are generated as a way to display calculated values.
}
void anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_instance (OMSTREAM & o, const COMPONENT * x) [private, virtual]
Implements LANGUAGE.
Definition at line 708 of file lang_spice.cc.
References anonymous_namespace{lang_spectre.cc}::print_label(), anonymous_namespace{lang_spectre.cc}::print_ports(), and anonymous_namespace{lang_spectre.cc}::print_type().
{
  print_label(o, x);
  print_ports(o, x);
  print_type(o, x);
  print_args(o, x);
  o << '\n';
}
void anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_label (OMSTREAM & o, const COMPONENT * x) [private]
Definition at line 784 of file lang_spice.cc.
References CKT_BASE::short_label().
{
  assert(x);
  std::string label = x->short_label();
  o << label;
}
void anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_module (OMSTREAM & o, const MODEL_SUBCKT * x) [private, virtual]
Implements LANGUAGE.
Definition at line 691 of file lang_spice.cc.
References CARD_LIST::begin(), CARD_LIST::end(), anonymous_namespace{lang_spectre.cc}::print_ports(), CKT_BASE::short_label(), and CARD::subckt().
{
  assert(x);
  assert(x->subckt());
  o << ".subckt " <<  x->short_label();
  print_ports(o, x);
  o << '\n';
  for (CARD_LIST::const_iterator
         ci = x->subckt()->begin(); ci != x->subckt()->end(); ++ci) {
    print_item(o, *ci);
  }
  o << ".ends " << x->short_label() << "\n";
}
void anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_paramset (OMSTREAM & o, const MODEL_CARD * x) [private, virtual]
Implements LANGUAGE.
Definition at line 683 of file lang_spice.cc.
References CARD::dev_type(), and CKT_BASE::short_label().
{
  assert(x);
  o << ".model " << x->short_label() << ' ' << x->dev_type() << " (";
  print_args(o, x);
  o << ")\n";
}
void anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_ports (OMSTREAM & o, const COMPONENT * x) [private]
Definition at line 791 of file lang_spice.cc.
References COMPONENT::current_port_exists(), COMPONENT::current_port_value(), COMPONENT::port_exists(), and COMPONENT::port_value().
{
  assert(x);
  o <<  " ( ";
  std::string sep = "";
  for (int ii = 0;  x->port_exists(ii);  ++ii) {
    o << sep << x->port_value(ii);
    sep = " ";
  }
  for (int ii = 0;  x->current_port_exists(ii);  ++ii) {
    o << sep << x->current_port_value(ii);
    sep = " ";
  }
  o << " )";
}
void anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_type (OMSTREAM & o, const COMPONENT * x) [private]
Definition at line 751 of file lang_spice.cc.
References CARD::dev_type(), fix_case(), CARD::id_letter(), itested, COMPONENT::print_type_in_spice(), and CKT_BASE::short_label().
{
  assert(x);
  if (x->print_type_in_spice()) {
    o << "  " << x->dev_type();
  }else if (fix_case(x->short_label()[0]) != fix_case(x->id_letter())) {itested();
    o << "  " << x->dev_type();
  }else{
    // don't print type
  }
}
The documentation for this class was generated from the following file:
savant/gnucap/src/lang_spice.cc