gnucap: MODEL_SEMI_RESISTOR Class Reference
MODEL_SEMI_RESISTOR Class Reference
Public Member Functions
MODEL_SEMI_RESISTOR ()
Public Attributes
PARAMETER< double > _rsh
Private Member Functions
MODEL_SEMI_RESISTOR (const MODEL_SEMI_RESISTOR &p)
std::string dev_type () const
void precalc_first ()
COMMON_COMPONENT * new_common () const
CARD * clone () const
void set_param_by_index (int, std::string &, int)
bool param_is_printable (int) const
std::string param_name (int) const
std::string param_name (int, int) const
std::string param_value (int) const
int param_count () const
Static Private Attributes
static double const _default_rsh = NOT_INPUT
Detailed Description
Definition at line 138 of file bmm_semi.cc.
Constructor & Destructor Documentation
MODEL_SEMI_RESISTOR::MODEL_SEMI_RESISTOR (const MODEL_SEMI_RESISTOR & p) [explicit, private]
Definition at line 519 of file bmm_semi.cc.
  :MODEL_SEMI_BASE(),
   _rsh(p._rsh)
{
}
MODEL_SEMI_RESISTOR::MODEL_SEMI_RESISTOR () [explicit]
Definition at line 513 of file bmm_semi.cc.
Referenced by clone().
  :MODEL_SEMI_BASE(),
   _rsh(_default_rsh)
{
}
Member Function Documentation
CARD* MODEL_SEMI_RESISTOR::clone () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 152 of file bmm_semi.cc.
References MODEL_SEMI_RESISTOR().
{return new MODEL_SEMI_RESISTOR(*this);}
std::string MODEL_SEMI_RESISTOR::dev_type () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 148 of file bmm_semi.cc.
{return "r";}
COMMON_COMPONENT* MODEL_SEMI_RESISTOR::new_common () const [inline, private, virtual]
Reimplemented from MODEL_CARD.
Definition at line 151 of file bmm_semi.cc.
{return new EVAL_BM_SEMI_RESISTOR;}
int MODEL_SEMI_RESISTOR::param_count () const [inline, private, virtual]
Reimplemented from MODEL_SEMI_BASE.
Definition at line 158 of file bmm_semi.cc.
References MODEL_SEMI_BASE::param_count().
Referenced by param_is_printable(), param_name(), param_value(), and set_param_by_index().
{return (1 + MODEL_SEMI_BASE::param_count());}
bool MODEL_SEMI_RESISTOR::param_is_printable (int i) const [private, virtual]
Reimplemented from MODEL_SEMI_BASE.
Definition at line 533 of file bmm_semi.cc.
References param_count().
{
  switch (MODEL_SEMI_RESISTOR::param_count() - 1 - i) {
  case 0: return true;
  default: return MODEL_SEMI_BASE::param_is_printable(i);
  }
}
std::string MODEL_SEMI_RESISTOR::param_name (int i) const [private, virtual]
Reimplemented from MODEL_SEMI_BASE.
Definition at line 541 of file bmm_semi.cc.
References param_count().
Referenced by param_name().
{
  switch (MODEL_SEMI_RESISTOR::param_count() - 1 - i) {
  case 0: return "rsh";
  default: return MODEL_SEMI_BASE::param_name(i);
  }
}
std::string MODEL_SEMI_RESISTOR::param_name (int i, int j) const [private, virtual]
Reimplemented from MODEL_SEMI_BASE.
Definition at line 549 of file bmm_semi.cc.
References MODEL_SEMI_BASE::param_count(), and param_name().
{
  if (j == 0) {
    return param_name(i);
  }else if (i >= MODEL_SEMI_BASE::param_count()) {
    return "";
  }else{
    return MODEL_SEMI_BASE::param_name(i, j);
  }
}
std::string MODEL_SEMI_RESISTOR::param_value (int i) const [private, virtual]
Reimplemented from MODEL_SEMI_BASE.
Definition at line 560 of file bmm_semi.cc.
References _rsh, param_count(), and PARAMETER< T >::string().
{
  switch (MODEL_SEMI_RESISTOR::param_count() - 1 - i) {
  case 0: return _rsh.string();
  default: return MODEL_SEMI_BASE::param_value(i);
  }
}
void MODEL_SEMI_RESISTOR::precalc_first () [private, virtual]
Reimplemented from MODEL_SEMI_BASE.
Definition at line 568 of file bmm_semi.cc.
References _default_rsh, _rsh, PARAMETER< T >::e_val(), and CARD::scope().
{
  MODEL_SEMI_BASE::precalc_first();
  const CARD_LIST* par_scope = scope();
  assert(par_scope);
  _rsh.e_val(_default_rsh, par_scope);
}
void MODEL_SEMI_RESISTOR::set_param_by_index (int i, std::string & value, int offset) [private, virtual]
Reimplemented from MODEL_SEMI_BASE.
Definition at line 525 of file bmm_semi.cc.
References _rsh, and param_count().
{
  switch (MODEL_SEMI_RESISTOR::param_count() - 1 - i) {
  case 0: _rsh = value; break;
  default: MODEL_SEMI_BASE::set_param_by_index(i, value, offset); break;
  }
}
Member Data Documentation
double const MODEL_SEMI_RESISTOR::_default_rsh = NOT_INPUT [static, private]
Definition at line 142 of file bmm_semi.cc.
Referenced by precalc_first().
PARAMETER<double> MODEL_SEMI_RESISTOR::_rsh
Definition at line 140 of file bmm_semi.cc.
Referenced by param_value(), precalc_first(), EVAL_BM_SEMI_RESISTOR::precalc_last(), and set_param_by_index().
The documentation for this class was generated from the following file:
savant/gnucap/src/bmm_semi.cc