gnucap: savant/gnucap/src/d_bjt.cc File Reference
savant/gnucap/src/d_bjt.cc File Reference
#include "u_limit.h"
#include "globals.h"
#include "e_elemnt.h"
#include "d_bjt.h"
Namespaces
namespace MODEL_BUILT_IN_BJT_DISPATCHER
namespace DEV_BUILT_IN_BJT_DISPATCHER
Functions
const double NA (NOT_INPUT)
const double INF (BIGBIG)
const int LEVEL (1)
Variables
static DEV_BUILT_IN_BJT MODEL_BUILT_IN_BJT_DISPATCHER::p1d
static DISPATCHER< MODEL_CARD >
::INSTALL d1 & MODEL_BUILT_IN_BJT_DISPATCHER::model_dispatcher
static COMMON_BUILT_IN_BJT Default_BUILT_IN_BJT (CC_STATIC)
static DEV_BUILT_IN_BJT DEV_BUILT_IN_BJT_DISPATCHER::p0
static DISPATCHER< CARD >
::INSTALL d0 & DEV_BUILT_IN_BJT_DISPATCHER::device_dispatcher
Function Documentation
const double INF (BIGBIG)
Referenced by MODEL_BUILT_IN_MOS_BASE::is_valid(), MODEL_BUILT_IN_MOS_BASE::param_is_printable(), and MODEL_BUILT_IN_MOS_BASE::precalc_first().
const int LEVEL (1)
Referenced by MODEL_BUILT_IN_MOS1::MODEL_BUILT_IN_MOS1(), MODEL_BUILT_IN_MOS2::MODEL_BUILT_IN_MOS2(), MODEL_BUILT_IN_MOS3::MODEL_BUILT_IN_MOS3(), MODEL_BUILT_IN_MOS4::MODEL_BUILT_IN_MOS4(), MODEL_BUILT_IN_MOS5::MODEL_BUILT_IN_MOS5(), MODEL_BUILT_IN_MOS6::MODEL_BUILT_IN_MOS6(), MODEL_BUILT_IN_MOS7::MODEL_BUILT_IN_MOS7(), MODEL_BUILT_IN_MOS8::MODEL_BUILT_IN_MOS8(), MODEL_BUILT_IN_MOS6::param_is_printable(), MODEL_BUILT_IN_MOS1::param_is_printable(), MODEL_BUILT_IN_MOS3::param_is_printable(), MODEL_BUILT_IN_MOS2::param_is_printable(), MODEL_BUILT_IN_MOS4::param_is_printable(), MODEL_BUILT_IN_MOS5::param_is_printable(), MODEL_BUILT_IN_MOS7::param_is_printable(), and MODEL_BUILT_IN_MOS8::param_is_printable().
const double NA (NOT_INPUT)
Referenced by COMMON_BUILT_IN_MOS::expand(), SDP_BUILT_IN_MOS2::init(), SDP_BUILT_IN_MOS_BASE::init(), SDP_BUILT_IN_MOS7::init(), SDP_BUILT_IN_MOS8::init(), MODEL_BUILT_IN_MOS1::MODEL_BUILT_IN_MOS1(), MODEL_BUILT_IN_MOS123::MODEL_BUILT_IN_MOS123(), MODEL_BUILT_IN_MOS2::MODEL_BUILT_IN_MOS2(), MODEL_BUILT_IN_MOS3::MODEL_BUILT_IN_MOS3(), MODEL_BUILT_IN_MOS4::MODEL_BUILT_IN_MOS4(), MODEL_BUILT_IN_MOS5::MODEL_BUILT_IN_MOS5(), MODEL_BUILT_IN_MOS6::MODEL_BUILT_IN_MOS6(), MODEL_BUILT_IN_MOS7::MODEL_BUILT_IN_MOS7(), MODEL_BUILT_IN_MOS8::MODEL_BUILT_IN_MOS8(), MODEL_BUILT_IN_MOS2::param_is_printable(), COMMON_BUILT_IN_BJT::param_is_printable(), MODEL_BUILT_IN_MOS123::precalc_first(), MODEL_BUILT_IN_MOS6::precalc_first(), MODEL_BUILT_IN_MOS1::precalc_first(), MODEL_BUILT_IN_MOS3::precalc_first(), MODEL_BUILT_IN_DIODE::precalc_first(), MODEL_BUILT_IN_MOS2::precalc_first(), MODEL_BUILT_IN_MOS_BASE::precalc_first(), MODEL_BUILT_IN_BJT::precalc_first(), MODEL_BUILT_IN_MOS4::precalc_first(), MODEL_BUILT_IN_MOS5::precalc_first(), COMMON_BUILT_IN_DIODE::precalc_first(), MODEL_BUILT_IN_MOS7::precalc_first(), COMMON_BUILT_IN_BJT::precalc_first(), MODEL_BUILT_IN_MOS8::precalc_first(), COMMON_BUILT_IN_MOS::precalc_last(), COMMON_BUILT_IN_DIODE::precalc_last(), COMMON_BUILT_IN_BJT::precalc_last(), TDP_BUILT_IN_MOS7::TDP_BUILT_IN_MOS7(), TDP_BUILT_IN_MOS8::TDP_BUILT_IN_MOS8(), MODEL_BUILT_IN_MOS1::tr_eval(), MODEL_BUILT_IN_BJT::tr_eval(), and DEV_BUILT_IN_BJT::tr_probe_num().
Variable Documentation
COMMON_BUILT_IN_BJT Default_BUILT_IN_BJT(CC_STATIC) [static]
Referenced by DEV_BUILT_IN_BJT::DEV_BUILT_IN_BJT().