gnucap: Token_BINOP Class Reference
Token_BINOP Class Reference
#include <m_expression.h>
Public Member Functions
Token_BINOP (const std::string Name)
Token_BINOP (const Token_BINOP &P)
Token * clone () const
Token * op (const Token *t1, const Token *t2) const
void stack_op (Expression *) const
Detailed Description
Definition at line 67 of file m_expression.h.
Constructor & Destructor Documentation
Token_BINOP::Token_BINOP (const std::string Name) [inline, explicit]
Definition at line 70 of file m_expression.h.
Referenced by clone().
    : Token(Name, NULL, "") {}
Token_BINOP::Token_BINOP (const Token_BINOP & P) [inline, explicit]
Definition at line 72 of file m_expression.h.
: Token(P) {}
Member Function Documentation
Token* Token_BINOP::clone () const [inline, virtual]
Implements Token.
Definition at line 73 of file m_expression.h.
References Token_BINOP().
Referenced by stack_op().
{return new Token_BINOP(*this);}
Token * Token_BINOP::op (const Token * t1, const Token * t2) const
Definition at line 31 of file m_expression_reduce.cc.
References Base::add(), Token::aRgs(), Token::data(), Base::divide(), Base::equal(), Base::geq(), Base::greater(), Base::leq(), Base::less(), Base::logic_and(), Base::logic_or(), Base::multiply(), Token::name(), Base::not_equal(), Base::subtract(), unreachable, and untested.
Referenced by stack_op().
{
  assert(T1);
  assert(T2);
  assert(dynamic_cast<const Token_CONSTANT*>(T1));
  assert(dynamic_cast<const Token_CONSTANT*>(T2));
  assert(T1->data());
  assert(T2->data());
  // not "or" operator, both ops exist -- do it
  Base* b = 0;
  if (name() == "*") {
    b = (T1->data())->multiply(T2->data());
  }else if (name() == "+") {
    b = (T1->data())->add(T2->data());
  }else if (name() == "-") {
    b = (T1->data())->subtract(T2->data());
  }else if (name() == "/") {
    b = (T1->data())->divide(T2->data());
  }else if (name() == "==") {
    b = (T1->data())->equal(T2->data());
  }else if (name() == "!=") {
    b = (T1->data())->not_equal(T2->data());
  }else if (name() == "<") {
    b = (T1->data())->less(T2->data());
  }else if (name() == ">") {
    b = (T1->data())->greater(T2->data());
  }else if (name() == "<=") {
    b = (T1->data())->leq(T2->data());
  }else if (name() == ">=") {
    b = (T1->data())->geq(T2->data());
  }else if (name() == "||") {
    b = (T1->data())->logic_or(T2->data());
  }else if (name() == "&&") {
    b = (T1->data())->logic_and(T2->data());
  }else{
    // op (name()) not one of those listed
    unreachable();
    return NULL;
  }
  if (b) {
    if (T1->aRgs() == "") {
    }else{untested();
    }
    if (T2->aRgs() == "") {
    }else{untested();
    }
    return new Token_CONSTANT(b->val_string(), b, (T1->aRgs()+T2->aRgs()));
  }else{
    // can get here if either T1 or T2 has no data
    return new Token_CONSTANT("false", NULL, "");
  }
}
void Token_BINOP::stack_op (Expression * E) const [virtual]
Reimplemented from Token.
Definition at line 156 of file m_expression_reduce.cc.
References List_Base< T >::back(), clone(), Token::data(), Token::name(), op(), List_Base< T >::pop_back(), List_Base< T >::push_back(), and untested.
{
  assert(E);
  // replace 2 tokens (binop) with 1 (result)
  Token* t1 = E->back();
  E->pop_back();
  Token* t2 = E->back();
  E->pop_back();
  if (dynamic_cast<Token_CONSTANT*>(t1)) {
    if (dynamic_cast<Token_CONSTANT*>(t2)) {
      // have # # + .. becomes result (the usual)
      Token* t = op(t2, t1);
      assert(t);
      if (t->data()) {
        // success
        E->push_back(t);
        delete t2;
        delete t1;
      }else{
        // fail - one arg is unknown, push back args
        if (strchr("+*", name()[0]) && !dynamic_cast<const Float*>(t1->data())) {untested();
          // change order to enable later optimization
          E->push_back(t1);
          E->push_back(t2);
        }else{
          E->push_back(t2);
          E->push_back(t1);
        }
        E->push_back(clone()); //op
        delete t;
      }
    }else if (((*t2) == (*this)) && strchr("+*", name()[0])
              && dynamic_cast<Token_CONSTANT*>(E->back())) {untested();
      // have # + # + .. becomes result + (previous unknown, try to optimize)
      Token* t3 = E->back();
      E->pop_back();
      Token* t = op(t3, t1);
      assert(t);
      if (t->data()) {untested();
        // success
        E->push_back(t);
        E->push_back(t2);
        delete t3;
        delete t1;
      }else{untested();
        // fail - push all
        E->push_back(t3);
        E->push_back(t2);
        E->push_back(t1);
        E->push_back(clone());
        delete t;
      }
    }else{untested();
      // # - # - or something like that
      E->push_back(t2);
      E->push_back(t1);
      E->push_back(clone());
    }
  }else{untested();
    // # - # - or something like that
    E->push_back(t2);
    E->push_back(t1);
    E->push_back(clone());
  }
}
The documentation for this class was generated from the following files:
savant/gnucap/src/m_expression.h
savant/gnucap/src/m_expression_reduce.cc