gnucap: XPROBE Class Reference
XPROBE Class Reference
#include <u_xprobe.h>
Public Member Functions
XPROBE (const XPROBE &p)
XPROBE (COMPLEX v)
XPROBE (COMPLEX v, mod_t m)
XPROBE (COMPLEX v, mod_t m, double d)
XPROBE (double v)
~XPROBE ()
bool exists () const
double operator() (mod_t m=mtNONE, bool db=false) const
XPROBE & operator= (const XPROBE &p)
Private Member Functions
XPROBE ()
Private Attributes
COMPLEX _value
mod_t _modifier
double _dbscale
Detailed Description
Definition at line 32 of file u_xprobe.h.
Constructor & Destructor Documentation
XPROBE::XPROBE () [inline, explicit, private]
Definition at line 38 of file u_xprobe.h.
References untested.
                   :
    _value(COMPLEX(NOT_VALID, NOT_VALID)),
    _modifier(mtNONE),
    _dbscale(20.) {untested();}
XPROBE::XPROBE (const XPROBE & p) [inline]
Definition at line 43 of file u_xprobe.h.
References untested.
                         :
    _value(p._value),
    _modifier(p._modifier),
    _dbscale(p._dbscale) {untested();}
XPROBE::XPROBE (COMPLEX v) [inline, explicit]
Definition at line 47 of file u_xprobe.h.
                            :
    _value(v),
    _modifier(mtMAG),
    _dbscale(20.) {}
XPROBE::XPROBE (COMPLEX v, mod_t m) [inline, explicit]
Definition at line 51 of file u_xprobe.h.
                                     :
    _value(v),
    _modifier(m),
    _dbscale(20.) {}
XPROBE::XPROBE (COMPLEX v, mod_t m, double d) [inline, explicit]
Definition at line 55 of file u_xprobe.h.
                                               :
    _value(v),
    _modifier(m),
    _dbscale(d) {}
XPROBE::XPROBE (double v) [inline, explicit]
Definition at line 59 of file u_xprobe.h.
                           :
    _value(v),
    _modifier(mtREAL),
    _dbscale(20.) {}
XPROBE::~XPROBE () [inline]
Definition at line 71 of file u_xprobe.h.
{}
Member Function Documentation
bool XPROBE::exists () const [inline]
Definition at line 73 of file u_xprobe.h.
References _modifier, and mtNONE.
Referenced by CKT_BASE::ac_probe_num(), and operator()().
{return _modifier != mtNONE;}
double XPROBE::operator() (mod_t m = mtNONE, bool db = false) const
Definition at line 29 of file u_xprobe.cc.
References _dbscale, _modifier, _value, exists(), mtIMAG, mtMAG, mtNONE, mtPHASE, mtREAL, NOT_VALID, phase(), unreachable, and VOLTMIN.
{
  if (exists()) {
    if (m == mtNONE) {
      m = _modifier;
    }
    double rv = NOT_VALID;
    switch (m) {
    case mtNONE:
      unreachable();
      break;
    case mtMAG:
      rv = std::abs(_value);
      break;
    case mtPHASE:
      rv = phase(_value);
      break;
    case mtREAL:
      rv = real(_value);
      break;
    case mtIMAG:
      rv = imag(_value);
      break;
    }
    return (db) ? _dbscale * log10(std::max(rv,VOLTMIN)) : rv;
  }else{
    return NOT_VALID;
  }
}
XPROBE & XPROBE::operator= (const XPROBE & p)
Definition at line 59 of file u_xprobe.cc.
References _dbscale, _modifier, and _value.
{
  _value = p._value;
  _modifier = p._modifier;
  _dbscale = p._dbscale;
  return *this;
}
Member Data Documentation
double XPROBE::_dbscale [private]
Definition at line 36 of file u_xprobe.h.
Referenced by operator()(), and operator=().
mod_t XPROBE::_modifier [private]
Definition at line 35 of file u_xprobe.h.
Referenced by exists(), operator()(), and operator=().
COMPLEX XPROBE::_value [private]
Definition at line 34 of file u_xprobe.h.
Referenced by operator()(), and operator=().
The documentation for this class was generated from the following files:
savant/gnucap/src/u_xprobe.h
savant/gnucap/src/u_xprobe.cc