gnucap: anonymous_namespace{measure_integral.cc}::MEASURE Class Reference
anonymous_namespace{measure_integral.cc}::MEASURE Class Reference
Public Member Functions
std::string eval (CS &Cmd, const CARD_LIST *Scope) const
Detailed Description
Definition at line 29 of file measure_integral.cc.
Member Function Documentation
std::string anonymous_namespace{measure_integral.cc}::MEASURE::eval (CS & Cmd, const CARD_LIST * Scope) const [inline, virtual]
Implements FUNCTION.
Definition at line 31 of file measure_integral.cc.
References WAVE::begin(), BIGBIG, CS::cursor(), PARAMETER< T >::e_val(), WAVE::end(), Get(), CS::more(), ONE_OF, CS::reset(), CS::stuck(), and to_string().
  {
    std::string probe_name;
    PARAMETER<double> before(BIGBIG);
    PARAMETER<double> after(-BIGBIG);
    unsigned here = Cmd.cursor();
    Cmd >> probe_name;
    WAVE* w = find_wave(probe_name);
    if (!w) {
      Cmd.reset(here);
    }else{
    }
    here = Cmd.cursor();
    do {
      ONE_OF
        || Get(Cmd, "probe",  &probe_name)
        || Get(Cmd, "before", &before)
        || Get(Cmd, "after",  &after)
        || Get(Cmd, "end",    &before)
        || Get(Cmd, "begin",  &after)
        ;
    }while (Cmd.more() && !Cmd.stuck(&here));
    if (!w) {
      w = find_wave(probe_name);
    }else{
    }
    if (w) {
      before.e_val(BIGBIG, Scope);
      after.e_val(-BIGBIG, Scope);
      WAVE::const_iterator begin = lower_bound(w->begin(), w->end(), DPAIR(after, -BIGBIG));
      WAVE::const_iterator end   = upper_bound(w->begin(), w->end(), DPAIR(before, BIGBIG));
      WAVE::const_iterator lower = begin;
      double area = 0;
      for (WAVE::const_iterator i = begin; ++i < end; ) {
        area += .5 * (lower->second + i->second) * (i->first - lower->first);
        lower = i;
      }
      return to_string(area);
    }else{
      throw Exception_No_Match(probe_name);
    }
  }
The documentation for this class was generated from the following file:
savant/gnucap/src/measure_integral.cc