gnucap: TDP_BUILT_IN_MOS6 Class Reference
TDP_BUILT_IN_MOS6 Class Reference
#include <d_mos6.h>
Public Member Functions
TDP_BUILT_IN_MOS6 (const DEV_BUILT_IN_MOS *)
Public Attributes
double phi
double beta
double vbi
Detailed Description
Definition at line 43 of file d_mos6.h.
Constructor & Destructor Documentation
TDP_BUILT_IN_MOS6::TDP_BUILT_IN_MOS6 (const DEV_BUILT_IN_MOS * d) [explicit]
Definition at line 51 of file d_mos6.cc.
References CKT_BASE::_sim, SIM_DATA::_temp_c, beta, COMPONENT::common(), MODEL_BUILT_IN_MOS_BASE::egap, fixzero(), MODEL_BUILT_IN_MOS123::gamma, MODEL_BUILT_IN_MOS6::kc, SDP_BUILT_IN_MOS_BASE::l_eff, COMMON_COMPONENT::model(), P_CELSIUS0, P_K, P_K_Q, P_Q, phi, MODEL_BUILT_IN_MOS123::phi, MODEL_BUILT_IN_MOS_BASE::polarity, prechecked_cast, CARD::scope(), COMMON_BUILT_IN_MOS::sdp(), MODEL_BUILT_IN_MOS_BASE::tnom_k, vbi, MODEL_BUILT_IN_MOS123::vto, and SDP_BUILT_IN_MOS_BASE::w_eff.
  :TDP_BUILT_IN_MOS123(d)
{
  assert(d);
  const COMMON_BUILT_IN_MOS* c = prechecked_cast<const COMMON_BUILT_IN_MOS*>(d->common());
  assert(c);
  const SDP_BUILT_IN_MOS6* s = prechecked_cast<const SDP_BUILT_IN_MOS6*>(c->sdp());
  assert(s);
  const MODEL_BUILT_IN_MOS6* m = prechecked_cast<const MODEL_BUILT_IN_MOS6*>(c->model());
  assert(m);
  const CARD_LIST* par_scope = d->scope();
  assert(par_scope);
    // final adjust: code_pre
      double temp = d->_sim->_temp_c + P_CELSIUS0;
      double tempratio  = temp / m->tnom_k;
      double tempratio4 = tempratio * sqrt(tempratio);
      double kt = temp * P_K;
      double vt = temp * P_K_Q;
      double egap = 1.16 - (7.02e-4*temp*temp) / (temp+1108.);
      double arg = (m->egap*tempratio - egap) / (2*kt);
    // final adjust: override
    // final adjust: raw
    // final adjust: mid
    // final adjust: calculated
    phi = m->phi*tempratio + (-2*vt*(1.5*log(tempratio)+P_Q*(arg)));
    beta = (m->kc / tempratio4) * s->w_eff / s->l_eff;
    vbi = (fixzero(
        (m->vto - m->gamma * sqrt(m->phi)
         +.5*(m->egap-egap) + m->polarity* .5 * (phi-m->phi)), m->phi));
    // final adjust: post
    // final adjust: done
}
Member Data Documentation
double TDP_BUILT_IN_MOS6::beta
Definition at line 49 of file d_mos6.h.
Referenced by TDP_BUILT_IN_MOS6(), and MODEL_BUILT_IN_MOS6::tr_eval().
double TDP_BUILT_IN_MOS6::phi
Definition at line 48 of file d_mos6.h.
Referenced by TDP_BUILT_IN_MOS6(), and MODEL_BUILT_IN_MOS6::tr_eval().
double TDP_BUILT_IN_MOS6::vbi
Definition at line 50 of file d_mos6.h.
Referenced by TDP_BUILT_IN_MOS6(), and MODEL_BUILT_IN_MOS6::tr_eval().
The documentation for this class was generated from the following files:
savant/gnucap/src/d_mos6.h
savant/gnucap/src/d_mos6.cc