gnucap: LOGIC_NODE Class Reference
LOGIC_NODE Class Reference
#include <e_node.h>
Public Member Functions
double tr_probe_num (const std::string &) const
LOGICVAL lv () const
int quality () const
const std::string & failure_mode () const
int d_iter () const
int a_iter () const
double final_time () const
double last_change_time () const
const MODEL_LOGIC * process () const
double old_last_change_time () const
const LOGICVAL old_lv () const
bool lv_future () const
bool is_unknown () const
bool in_transit () const
bool is_digital () const
bool is_analog () const
double annotated_logic_value () const
bool just_reached_stable () const
void set_quality (int q)
void set_failure_mode (const std::string &f)
void set_final_time (double t)
void set_d_iter ()
void set_last_change_time ()
void set_last_change_time (double t)
void set_lv (LOGICVAL v)
void set_process (const MODEL_LOGIC *f)
void store_old_last_change_time ()
void store_old_lv ()
void restore_lv ()
void set_mode (smode_t m)
void set_bad_quality (const std::string &f)
void set_good_quality (const std::string &f="ok")
void dont_set_quality (const std::string &f="don't know")
void improve_quality ()
void set_event (double delay, LOGICVAL v)
void force_initial_value (LOGICVAL v)
void propagate ()
double to_analog (const MODEL_LOGIC *f)
void to_logic (const MODEL_LOGIC *f)
LOGIC_NODE ()
~LOGIC_NODE ()
LOGIC_NODE & set_a_iter ()
Private Member Functions
LOGIC_NODE (const LOGIC_NODE &)
Private Attributes
const MODEL_LOGIC * _family
int _d_iter
int _a_iter
double _final_time
double _lastchange
double _old_lastchange
smode_t _mode
LOGICVAL _lv
LOGICVAL _old_lv
int _quality
std::string _failure_mode
Detailed Description
Definition at line 136 of file e_node.h.
Constructor & Destructor Documentation
LOGIC_NODE::LOGIC_NODE (const LOGIC_NODE &) [inline, explicit, private]
Definition at line 221 of file e_node.h.
References incomplete, and unreachable.
:NODE(){incomplete();unreachable();}
LOGIC_NODE::LOGIC_NODE () [explicit]
Definition at line 73 of file e_node.cc.
  :NODE(),
   _family(0),
   _d_iter(0),
   _a_iter(0),
   _final_time(0),
   _lastchange(0),
   _old_lastchange(0),
   _mode(moANALOG),
   _lv(),
   _old_lv(),
   _quality(qBAD),
   _failure_mode("initial")
{
}
LOGIC_NODE::~LOGIC_NODE () [inline]
Definition at line 224 of file e_node.h.
{}
Member Function Documentation
int LOGIC_NODE::a_iter () const [inline]
Definition at line 161 of file e_node.h.
Referenced by to_logic().
{return _a_iter;}
double LOGIC_NODE::annotated_logic_value () const
Definition at line 243 of file e_node.cc.
References _lv, _mode, quality(), and OPT::transits.
Referenced by tr_probe_num().
{
  return (_lv + (.1 * (OPT::transits - quality())) + (.01 * (2 - _mode)));
}
int LOGIC_NODE::d_iter () const [inline]
Definition at line 160 of file e_node.h.
Referenced by set_event(), to_logic(), and DEV_LOGIC::tr_accept().
{return _d_iter;}
void LOGIC_NODE::dont_set_quality (const std::string & f = "don't know") [inline]
Definition at line 204 of file e_node.h.
Referenced by to_logic().
{
    set_failure_mode(f);
  }
const std::string& LOGIC_NODE::failure_mode () const [inline]
Definition at line 159 of file e_node.h.
Referenced by DEV_LOGIC::tr_accept().
{return _failure_mode;}
double LOGIC_NODE::final_time () const [inline]
Definition at line 162 of file e_node.h.
Referenced by set_event(), to_analog(), DEV_LOGIC::tr_advance(), tr_probe_num(), and DEV_LOGIC::tr_regress().
{return _final_time;}
void LOGIC_NODE::force_initial_value (LOGICVAL v)
Definition at line 462 of file e_node.cc.
References CKT_BASE::_sim, SIM_DATA::_time0, SIM_DATA::analysis_is_restore(), SIM_DATA::analysis_is_static(), is_digital(), is_unknown(), NEVER, set_d_iter(), set_final_time(), set_good_quality(), set_last_change_time(), set_lv(), and untested.
Referenced by DEV_LOGIC::tr_accept().
{
  if (_sim->analysis_is_restore()) {untested();
  }else if (_sim->analysis_is_static()) {
  }else{untested();
  }
  assert(_sim->analysis_is_static() || _sim->analysis_is_restore());
  assert(_sim->_time0 == 0.);
  assert(is_unknown());
  assert(is_digital());
  set_lv(v); // BUG ??
  set_good_quality("initial dc");
  set_d_iter();
  set_final_time(NEVER);
  set_last_change_time();
}
void LOGIC_NODE::improve_quality () [inline]
Definition at line 207 of file e_node.h.
References qGOOD.
Referenced by to_logic().
{
    if (quality() < qGOOD) {
      ++_quality;
    }
  }
bool LOGIC_NODE::in_transit () const [inline]
Definition at line 171 of file e_node.h.
References NEVER.
Referenced by propagate(), and set_event().
{return final_time() < NEVER;}
bool LOGIC_NODE::is_analog () const [inline]
Definition at line 173 of file e_node.h.
References moANALOG.
Referenced by to_logic().
{return _mode == moANALOG;}
bool LOGIC_NODE::is_digital () const [inline]
Definition at line 172 of file e_node.h.
References moDIGITAL.
Referenced by force_initial_value().
{return _mode == moDIGITAL;}
bool LOGIC_NODE::is_unknown () const [inline]
Definition at line 170 of file e_node.h.
Referenced by force_initial_value().
{return lv().is_unknown();}
bool LOGIC_NODE::just_reached_stable () const [inline]
Definition at line 257 of file e_node.cc.
References lv(), newly_stable, and old_lv().
Referenced by to_logic().
{
  return newly_stable[old_lv()][lv()];
}
double LOGIC_NODE::last_change_time () const [inline]
Definition at line 163 of file e_node.h.
Referenced by to_logic().
{return _lastchange;}
LOGICVAL LOGIC_NODE::lv () const [inline]
Definition at line 157 of file e_node.h.
Referenced by just_reached_stable(), LOGIC_AND::logic_eval(), LOGIC_NAND::logic_eval(), LOGIC_OR::logic_eval(), LOGIC_NOR::logic_eval(), LOGIC_XOR::logic_eval(), LOGIC_XNOR::logic_eval(), LOGIC_INV::logic_eval(), propagate(), to_analog(), and to_logic().
{return _lv;}
bool LOGIC_NODE::lv_future () const [inline]
Definition at line 169 of file e_node.h.
Referenced by DEV_LOGIC::tr_accept().
{return lv().lv_future();}
double LOGIC_NODE::old_last_change_time () const [inline]
Definition at line 165 of file e_node.h.
References untested.
Referenced by to_logic().
{untested(); return _old_lastchange;}
const LOGICVAL LOGIC_NODE::old_lv () const [inline]
Definition at line 166 of file e_node.h.
Referenced by just_reached_stable().
{return _old_lv;}
const MODEL_LOGIC* LOGIC_NODE::process () const [inline]
Definition at line 164 of file e_node.h.
Referenced by to_analog(), and to_logic().
{return _family;}
void LOGIC_NODE::propagate ()
Definition at line 446 of file e_node.cc.
References in_transit(), lv(), lvSTABLE0, lvSTABLE1, NEVER, set_d_iter(), set_final_time(), set_last_change_time(), and set_lv().
Referenced by DEV_LOGIC::dc_advance(), DEV_LOGIC::tr_advance(), and DEV_LOGIC::tr_regress().
{
  assert(in_transit());
  if (lv().is_rising()) {
    set_lv(lvSTABLE1);
  }else if (lv().is_falling()) {
    set_lv(lvSTABLE0);
  }else{
    // lv no change
  }
  set_d_iter();
  set_final_time(NEVER);
  set_last_change_time();
  assert(!(in_transit()));
}
int LOGIC_NODE::quality () const [inline]
Definition at line 158 of file e_node.h.
Referenced by annotated_logic_value(), and DEV_LOGIC::tr_accept().
{return _quality;}
void LOGIC_NODE::restore_lv () [inline]
Definition at line 192 of file e_node.h.
References untested.
Referenced by to_logic().
{untested(); set_lv(old_lv());}
LOGIC_NODE& LOGIC_NODE::set_a_iter () [inline]
Definition at line 227 of file e_node.h.
Referenced by SIM::solve_equations().
{_a_iter = _sim->iteration_tag(); return *this;}
void LOGIC_NODE::set_bad_quality (const std::string & f) [inline]
Definition at line 196 of file e_node.h.
References qBAD.
Referenced by set_event(), and to_logic().
{
    set_quality(qBAD);
    set_failure_mode(f);
  }
void LOGIC_NODE::set_d_iter () [inline]
Definition at line 184 of file e_node.h.
Referenced by force_initial_value(), propagate(), set_event(), and to_logic().
{_d_iter = _sim->iteration_tag();}
void LOGIC_NODE::set_event (double delay, LOGICVAL v)
Definition at line 479 of file e_node.cc.
References _lv, CKT_BASE::_sim, SIM_DATA::_time0, SIM_DATA::analysis_is_tran_dynamic(), d_iter(), error(), final_time(), in_transit(), CKT_BASE::long_label(), OPT::picky, set_bad_quality(), set_d_iter(), set_final_time(), LOGICVAL::set_in_transition(), set_last_change_time(), and untested.
Referenced by DEV_LOGIC::tr_accept().
{
  _lv.set_in_transition(v);
  if (_sim->analysis_is_tran_dynamic()  &&  in_transit()) {untested();
    set_bad_quality("race");
  }
  set_d_iter();
  set_final_time(_sim->_time0 + delay);
  if (OPT::picky <= bTRACE) {untested();
    error(bTRACE, "%s:%u:%g new event\n",
          long_label().c_str(), d_iter(), final_time());
  }
  set_last_change_time();
}
void LOGIC_NODE::set_failure_mode (const std::string & f) [inline]
Definition at line 181 of file e_node.h.
{_failure_mode = f;}
void LOGIC_NODE::set_final_time (double t) [inline]
Definition at line 182 of file e_node.h.
Referenced by force_initial_value(), propagate(), and set_event().
{_final_time = t;}
void LOGIC_NODE::set_good_quality (const std::string & f = "ok") [inline]
Definition at line 200 of file e_node.h.
References qGOOD.
Referenced by force_initial_value(), and to_logic().
{
    set_quality(qGOOD);
    set_failure_mode(f);
  }
void LOGIC_NODE::set_last_change_time () [inline]
Definition at line 185 of file e_node.h.
Referenced by force_initial_value(), propagate(), set_event(), and to_logic().
{_lastchange = _sim->_time0;}
void LOGIC_NODE::set_last_change_time (double t) [inline]
Definition at line 186 of file e_node.h.
{_lastchange = t;}
void LOGIC_NODE::set_lv (LOGICVAL v) [inline]
Definition at line 187 of file e_node.h.
Referenced by force_initial_value(), propagate(), and to_logic().
{_lv = v;}
void LOGIC_NODE::set_mode (smode_t m) [inline]
Definition at line 193 of file e_node.h.
Referenced by DEV_LOGIC::dc_advance(), DEV_LOGIC::tr_advance(), DEV_LOGIC::tr_begin(), and DEV_LOGIC::tr_regress().
{_mode = m;}
void LOGIC_NODE::set_process (const MODEL_LOGIC * f) [inline]
Definition at line 188 of file e_node.h.
Referenced by to_analog(), and to_logic().
{_family = f;}
void LOGIC_NODE::set_quality (int q) [inline]
Definition at line 180 of file e_node.h.
{_quality = q;}
void LOGIC_NODE::store_old_last_change_time () [inline]
Definition at line 190 of file e_node.h.
Referenced by to_logic().
{_old_lastchange = last_change_time();}
void LOGIC_NODE::store_old_lv () [inline]
Definition at line 191 of file e_node.h.
Referenced by to_logic().
{_old_lv = lv();}
double LOGIC_NODE::to_analog (const MODEL_LOGIC * f)
Definition at line 399 of file e_node.cc.
References CKT_BASE::_sim, SIM_DATA::_time0, error(), MODEL_LOGIC::fall, final_time(), CKT_BASE::long_label(), CARD::long_label(), lv(), lvFALLING, lvRISING, lvSTABLE0, lvSTABLE1, lvUNKNOWN, NOT_VALID, process(), MODEL_LOGIC::rise, set_process(), MODEL_LOGIC::unknown, untested, MODEL_LOGIC::vmax, and MODEL_LOGIC::vmin.
Referenced by DEV_LOGIC::tr_eval_digital().
{
  assert(f);
  if (process() && process() != f) {untested();
    error(bWARNING, "node " + long_label()
          + " logic process mismatch\nis it " + process()->long_label()
          + " or " + f->long_label() + "?\n");
  }
  set_process(f);
  double start = NOT_VALID;
  double end = NOT_VALID;
  double risefall = NOT_VALID;
  switch (lv()) {
  case lvSTABLE0:
    return process()->vmin;
  case lvRISING:
    untested();
    start = process()->vmin;
    end = process()->vmax;
    risefall = process()->rise;
    break;
  case lvFALLING:
    start = process()->vmax;
    end = process()->vmin;
    risefall = process()->fall;
    break;
  case lvSTABLE1:
    return process()->vmax;
  case lvUNKNOWN:
    return process()->unknown;
  }
  assert(start != NOT_VALID);
  assert(end   != NOT_VALID);
  assert(risefall != NOT_VALID);
  if (_sim->_time0 <= (final_time()-risefall)) {
    return start;
  }else if (_sim->_time0 >= final_time()) {
    untested();
    return end;
  }else{
    untested();
    return end - ((end-start) * (final_time()-_sim->_time0) / risefall);
  }
}
void LOGIC_NODE::to_logic (const MODEL_LOGIC * f)
Definition at line 267 of file e_node.cc.
References _failure_mode, _lastchange, _lv, _quality, CKT_BASE::_sim, SIM_DATA::_time0, a_iter(), SIM_DATA::analysis_is_restore(), SIM_DATA::analysis_is_static(), d_iter(), dont_set_quality(), error(), fall, improve_quality(), is_analog(), just_reached_stable(), last_change_time(), CKT_BASE::long_label(), CARD::long_label(), lv(), lvFALLING, lvRISING, lvSTABLE0, lvSTABLE1, lvUNKNOWN, old_last_change_time(), process(), MODEL_LOGIC::range, restore_lv(), rise, set_bad_quality(), set_d_iter(), set_good_quality(), set_last_change_time(), set_lv(), set_process(), store_old_last_change_time(), store_old_lv(), trace3, untested, NODE::v0(), and NODE::vt1().
Referenced by DEV_LOGIC::tr_accept().
{
  assert(f);
  if (process() && process() != f) {untested();
    set_bad_quality("logic process mismatch");
    error(bWARNING, "node " + long_label()
          + " logic process mismatch\nis it " + process()->long_label()
          + " or " + f->long_label() + "?\n");
  }
  set_process(f);
  if (is_analog() &&  d_iter() < a_iter()) {
    if (_sim->analysis_is_restore()) {untested();
    }else if (_sim->analysis_is_static()) {
    }else{
    }
    if (_sim->analysis_is_static() || _sim->analysis_is_restore()) {
      set_last_change_time(0);
      store_old_last_change_time();
      set_lv(lvUNKNOWN);
    }else{
    }
    double dt = _sim->_time0 - last_change_time();
    if (dt < 0.) {untested();
      error(bPICKY, "time moving backwards.  was %g, now %g\n",
            last_change_time(), _sim->_time0);
      dt = _sim->_time0 - old_last_change_time();
      if (dt <= 0.) {untested();
        throw Exception("internal error: time moving backwards, can't recover");
      }else{untested();
      }
      assert(dt > 0.);
      restore_lv();                     /* skip back one */
    }else{
      store_old_last_change_time();
      store_old_lv();                   /* save to see if it changes */
    }
    double sv = v0() / process()->range;        /* new scaled voltage */
    if (sv >= process()->th1) {         /* logic 1 */
      switch (lv()) {
      case lvSTABLE0: dont_set_quality("stable 0 to stable 1"); break;
      case lvRISING:  dont_set_quality("begin stable 1");       break;
      case lvFALLING:untested();set_bad_quality("falling to stable 1"); break;
      case lvSTABLE1: dont_set_quality("continuing stable 1");  break;
      case lvUNKNOWN: set_good_quality("initial 1");            break;
      }
      set_lv(lvSTABLE1);
    }else if (sv <= process()->th0) {   /* logic 0 */
      switch (lv()) {
      case lvSTABLE0: dont_set_quality("continuing stable 0");  break;
      case lvRISING: untested();set_bad_quality("rising to stable 0");  break;
      case lvFALLING: dont_set_quality("begin stable 0");       break;
      case lvSTABLE1: dont_set_quality("stable 1 to stable 0"); break;
      case lvUNKNOWN: set_good_quality("initial 0");            break;
      }
      set_lv(lvSTABLE0);
    }else{                              /* transition region */
      double oldsv = vt1() / process()->range;/* old scaled voltage */
      double diff  = sv - oldsv;
      if (diff > 0) {   /* rising */
        switch (lv()) {
        case lvSTABLE0:
          dont_set_quality("begin good rise");
          break;
        case lvRISING:
          if (diff < dt/(process()->mr * process()->rise)) {
            set_bad_quality("slow rise");
          }else{
            dont_set_quality("continuing good rise");
          }
          break;
        case lvFALLING:
          untested();
          set_bad_quality("positive glitch in fall");
          break;
        case lvSTABLE1:
          untested();
          set_bad_quality("negative glitch in 1");
          break;
        case lvUNKNOWN:
          set_bad_quality("initial rise");
          break;
        }
        set_lv(lvRISING);
      }else if (diff < 0) {     /* falling */
        switch (lv()) {
        case lvSTABLE0:
          untested();
          set_bad_quality("positive glitch in 0");
          break;
        case lvRISING:
          set_bad_quality("negative glitch in rise");
          break;
        case lvFALLING:
          if (-diff < dt/(process()->mf * process()->fall)) {
            set_bad_quality("slow fall");
          }else{
            dont_set_quality("continuing good fall");
          }
          break;
        case lvSTABLE1:
          dont_set_quality("begin good fall");
          break;
        case lvUNKNOWN:
          untested();
          set_bad_quality("initial fall");
          break;
        }
        set_lv(lvFALLING);
      }else{                            /* hanging up in transition */
        untested();
        error(bDANGER, "inflection???\n");
        set_bad_quality("in transition but no change");
        /* state (rise/fall)  unchanged */
      }
    }
    if (sv > 1.+process()->over || sv < -process()->over) {/* out of range */
      set_bad_quality("out of range");
    }
    if (just_reached_stable()) { /* A bad node gets a little better */
      improve_quality();        /* on every good transition.       */
    }                           /* Eventually, it is good enough.  */
                                /* A good transition is defined as */
                                /* entering a stable state from    */
                                /* a transition state.             */
    set_d_iter();
    set_last_change_time();
    trace3(_failure_mode, _lastchange, _quality, _lv);
  }
}
double LOGIC_NODE::tr_probe_num (const std::string & x) const [virtual]
Reimplemented from NODE.
Definition at line 211 of file e_node.cc.
References _a_iter, _d_iter, _lastchange, annotated_logic_value(), final_time(), Umatch(), and untested.
Referenced by DEV_LOGIC::tr_probe_num(), and NODE::tr_probe_num().
{
  if (Umatch(x, "l{ogic} ")) {
    return annotated_logic_value();
  }else if (Umatch(x, "la{stchange} ")) {untested();
    return _lastchange;
  }else if (Umatch(x, "fi{naltime} ")) {untested();
    return final_time();
  }else if (Umatch(x, "di{ter} ")) {untested();
    return static_cast<double>(_d_iter);
  }else if (Umatch(x, "ai{ter} ")) {untested();
    return static_cast<double>(_a_iter);
  }else{
    return NODE::tr_probe_num(x);
  }
}
Member Data Documentation
int LOGIC_NODE::_a_iter [private]
Definition at line 140 of file e_node.h.
Referenced by tr_probe_num().
int LOGIC_NODE::_d_iter [private]
Definition at line 139 of file e_node.h.
Referenced by tr_probe_num().
std::string LOGIC_NODE::_failure_mode [private]
Definition at line 148 of file e_node.h.
Referenced by to_logic().
const MODEL_LOGIC* LOGIC_NODE::_family [private]
Definition at line 138 of file e_node.h.
double LOGIC_NODE::_final_time [private]
Definition at line 141 of file e_node.h.
double LOGIC_NODE::_lastchange [private]
Definition at line 142 of file e_node.h.
Referenced by to_logic(), and tr_probe_num().
LOGICVAL LOGIC_NODE::_lv [private]
Definition at line 145 of file e_node.h.
Referenced by annotated_logic_value(), set_event(), and to_logic().
smode_t LOGIC_NODE::_mode [private]
Definition at line 144 of file e_node.h.
Referenced by annotated_logic_value().
double LOGIC_NODE::_old_lastchange [private]
Definition at line 143 of file e_node.h.
LOGICVAL LOGIC_NODE::_old_lv [private]
Definition at line 146 of file e_node.h.
int LOGIC_NODE::_quality [private]
Definition at line 147 of file e_node.h.
Referenced by to_logic().
The documentation for this class was generated from the following files:
savant/gnucap/src/e_node.h
savant/gnucap/src/e_node.cc