gnucap: anonymous_namespace{c_system.cc}::CMD_EDIT Class Reference
anonymous_namespace{c_system.cc}::CMD_EDIT Class Reference
Public Member Functions
void do_it (CS &cmd, CARD_LIST *Scope)
Detailed Description
Definition at line 34 of file c_system.cc.
Member Function Documentation
void anonymous_namespace{c_system.cc}::CMD_EDIT::do_it (CS & cmd, CARD_LIST * Scope) [inline, virtual]
Implements CMD.
Definition at line 36 of file c_system.cc.
References OS::getenv(), itested, CS::more(), OS::remove(), OS::system(), CS::tail(), and to_string().
  {itested();
    std::string editor(OS::getenv("EDITOR"));
    if (editor == "") {
      throw Exception("no editor defined\n"
            "You need to set the EDITOR environment variable.");
    }else{
      if (cmd.more()) {itested();
        OS::system(editor + ' ' + cmd.tail());
      }else{
        std::string temp_file("/tmp/gnucap" + to_string(unsigned(time(NULL))));
        command("save " + temp_file + " quiet", Scope);
        OS::system(editor + ' ' + temp_file);
        command("get " + temp_file + " quiet", Scope);
        OS::remove(temp_file);
      }
    }
  }
The documentation for this class was generated from the following file:
savant/gnucap/src/c_system.cc