gnucap: anonymous_namespace{s_dc.cc}::OP Class Reference
anonymous_namespace{s_dc.cc}::OP Class Reference
Public Member Functions
OP ()
~OP ()
void do_it (CS &, CARD_LIST *)
Private Member Functions
void setup (CS &)
OP (const OP &)
Detailed Description
Definition at line 81 of file s_dc.cc.
Constructor & Destructor Documentation
anonymous_namespace{s_dc.cc}::OP::OP () [inline, explicit]
Definition at line 83 of file s_dc.cc.
: DCOP() {}
anonymous_namespace{s_dc.cc}::OP::~OP () [inline]
Definition at line 84 of file s_dc.cc.
{}
anonymous_namespace{s_dc.cc}::OP::OP (const OP &) [inline, explicit, private]
Definition at line 88 of file s_dc.cc.
References incomplete, and unreachable.
: DCOP() {unreachable(); incomplete();}
Member Function Documentation
void anonymous_namespace{s_dc.cc}::OP::do_it (CS & Cmd, CARD_LIST * Scope) [virtual]
Implements CMD.
Definition at line 104 of file s_dc.cc.
References STATUS::op, p_INIT_DC, TIMER::reset(), TIMER::start(), status, and TIMER::stop().
{
  _scope = Scope;
  _sim->_time0 = 0.;
  _sim->set_command_op();
  _sim->_phase = p_INIT_DC;
  ::status.op.reset().start();
  _sim->_temp_c = temp_c_in;
  command_base(Cmd);
  ::status.op.stop();
}
void anonymous_namespace{s_dc.cc}::OP::setup (CS & Cmd) [private, virtual]
Implements SIM.
Definition at line 154 of file s_dc.cc.
References anonymous_namespace{s_dc.cc}::DCOP::_cont, SIM_DATA::_freq, SIM_DATA::_genout, anonymous_namespace{s_dc.cc}::DCOP::_n_sweeps, SIM::_out, SIM::_scope, CKT_BASE::_sim, anonymous_namespace{s_dc.cc}::DCOP::_start, anonymous_namespace{s_dc.cc}::DCOP::_step, anonymous_namespace{s_dc.cc}::DCOP::_stop, anonymous_namespace{s_dc.cc}::DCOP::_sweepval, SIM_DATA::_temp_c, anonymous_namespace{s_dc.cc}::DCOP::_trace, anonymous_namespace{s_dc.cc}::DCOP::_zap, CS::check(), PARAMETER< T >::e_val(), anonymous_namespace{s_dc.cc}::DCOP::fix_args(), initio(), CS::is_float(), CS::match1(), IO::mstdout, anonymous_namespace{s_dc.cc}::DCOP::options(), SIM::plotlist(), IO::plotout, IO::plotset, OMSTREAM::reset(), PROBELIST::size(), OPT::temp_c, anonymous_namespace{s_dc.cc}::DCOP::temp_c_in, and SIM::tNONE.
{
  _sim->_temp_c = temp_c_in;
  _cont = false;
  _trace = tNONE;
  _out = IO::mstdout;
  _out.reset(); //BUG// don't know why this is needed */
  bool ploton = IO::plotset  &&  plotlist().size() > 0;
  _zap[0] = NULL;
  _sweepval[0] = &temp_c_in;
  if (Cmd.match1("'\"({") || Cmd.is_float()) {
    Cmd >> _start[0];
    if (Cmd.match1("'\"({") || Cmd.is_float()) {
      Cmd >> _stop[0];
    }else{
      _stop[0] = _start[0];
    }
  }else{
  }
  _step[0] = 0.;
  _sim->_genout = 0.;
  options(Cmd,0);
  _n_sweeps = 1;
  Cmd.check(bWARNING, "what's this?");
  _sim->_freq = 0;
  IO::plotout = (ploton) ? IO::mstdout : OMSTREAM();
  initio(_out);
  _start[0].e_val(OPT::temp_c, _scope);
  fix_args(0);
}
The documentation for this class was generated from the following file:
savant/gnucap/src/s_dc.cc