gnucap: CS Class Reference
CS Class Reference
#include <ap.h>
Public Types
enum STDIN { _STDIN }
enum INC_FILE { _INC_FILE }
enum WHOLE_FILE { _WHOLE_FILE }
enum STRING { _STRING }
Public Member Functions
CS (STDIN)
CS (INC_FILE, const std::string &name)
CS (WHOLE_FILE, const std::string &name)
CS (STRING, const std::string &s)
CS (const CS &p)
CS & operator= (const std::string &s)
CS & operator= (const CS &p)
CS & get_line (const std::string &prompt)
~CS ()
unsigned cursor () const
bool stuck (unsigned *last)
bool gotit (unsigned last)
operator bool () const
const std::string fullstring () const
const std::string substr (unsigned i) const
const std::string substr (unsigned i, unsigned n) const
const std::string tail () const
char peek () const
bool ns_more () const
bool more ()
bool is_end ()
bool is_file ()
bool is_first_read () const
CS & reset (unsigned c=0)
CS & check (int, const std::string &)
CS & warn (int, unsigned, const std::string &)
CS & warn (int i, const std::string &s)
CS & umatch (const std::string &)
CS & scan (const std::string &)
std::string last_match () const
std::string trimmed_last_match (const std::string &=" ,=;") const
bool match1 (char c) const
bool match1 (const std::string &c) const
size_t find1 (const std::string &c) const
bool is_xdigit () const
bool is_digit () const
bool is_pfloat () const
bool is_float () const
bool is_argsym () const
bool is_alpha () const
bool is_alnum () const
bool is_term (const std::string &t=",=(){};")
char ctoc ()
void ctostr (char *, int, const std::string &)
std::string ctos (const std::string &term=",=(){};", const std::string &b="\"'{", const std::string &e="\"'}", const std::string &trap="")
std::string get_to (const std::string &term)
double ctof ()
bool ctob ()
int ctoi ()
unsigned ctou ()
int ctoo ()
int ctox ()
double ctopf ()
CS & operator>> (bool &x)
CS & operator>> (char &x)
CS & operator>> (int &x)
CS & operator>> (unsigned &x)
CS & operator>> (double &x)
CS & operator>> (std::string &x)
CS & skip (int c=1)
CS & skipbl ()
CS & skip1b (char)
CS & skip1 (char)
CS & skip1b (const std::string &)
CS & skip1 (const std::string &)
CS & skiparg ()
CS & skipto1 (const std::string &)
CS & skipto1 (char)
CS & skipcom ()
CS & operator>> (const char &x)
CS & operator>> (const char *x)
Private Attributes
FILE * _file
std::string _name
std::string _cmd
unsigned _cnt
unsigned _length
unsigned _begin_match
unsigned _end_match
bool _ok
int _line_number
Detailed Description
Definition at line 43 of file ap.h.
Member Enumeration Documentation
enum CS::INC_FILE
Enumerator:
_INC_FILE
Definition at line 46 of file ap.h.
{_INC_FILE};
enum CS::STDIN
Enumerator:
_STDIN
Definition at line 45 of file ap.h.
{_STDIN};
enum CS::STRING
Enumerator:
_STRING
Definition at line 48 of file ap.h.
{_STRING};
enum CS::WHOLE_FILE
Enumerator:
_WHOLE_FILE
Definition at line 47 of file ap.h.
{_WHOLE_FILE};
Constructor & Destructor Documentation
CS::CS (CS::STDIN) [explicit]
Definition at line 37 of file ap_construct.cc.
  :_file(stdin),
   _name(),
   _cmd(),
   _cnt(0),
   _length(0),
   _begin_match(0),
   _end_match(0),
   _ok(true),
   _line_number(0)
{
}
CS::CS (CS::INC_FILE , const std::string & name) [explicit]
Definition at line 50 of file ap_construct.cc.
References _file, and itested.
  :_file(fopen(name.c_str(), "r")),
   _name(name),
   _cmd(),
   _cnt(0),
   _length(0),
   _begin_match(0),
   _end_match(0),
   _ok(true),
   _line_number(0)
{
  if (!_file) {itested();
    throw Exception_File_Open(name + ':' + strerror(errno));
  }else{
  }
}
CS::CS (CS::WHOLE_FILE , const std::string & name) [explicit]
Definition at line 67 of file ap_construct.cc.
References _cmd, _length, and itested.
  :_file(NULL),
   _name(name),
   _cmd(),
   _cnt(0),
   _length(0),
   _begin_match(0),
   _end_match(0),
   _ok(true),
   _line_number(0)
{
  int f = open(name.c_str(), O_RDONLY);
  if (f == EOF) {itested();
    throw Exception_File_Open(name + ':' + strerror(errno));
  }else{
  }
  _length = static_cast<unsigned>(lseek(f, off_t(0), SEEK_END));
  lseek(f, off_t(0), SEEK_SET);
  char* cmd = new char[_length+2];
  read(f, cmd, _length);
  cmd[_length++] = '\0';
  _cmd = cmd;
  close(f);
}
CS::CS (CS::STRING , const std::string & s) [explicit]
Definition at line 94 of file ap_construct.cc.
  :_file(NULL),
   _name(),
   _cmd(s),
   _cnt(0),
   _length(static_cast<unsigned>(s.length())),
   _begin_match(0),
   _end_match(0),
   _ok(true),
   _line_number(0)
{
}
CS::CS (const CS & p) [explicit]
CS::~CS () [inline]
Definition at line 69 of file ap.h.
{if (is_file()) {fclose(_file);}}
Member Function Documentation
CS & CS::check (int badness, const std::string & message)
Definition at line 37 of file ap_error.cc.
References _ok, itested, peek(), skip(), skipbl(), umatch(), and warn().
Referenced by PROBELIST::add_list(), CMD::cmdproc(), anonymous_namespace{c_exp.cc}::CMD_::do_it(), anonymous_namespace{c_genrat.cc}::CMD_::do_it(), anonymous_namespace{lang_spice.cc}::getmerge(), anonymous_namespace{c_modify.cc}::modify_fault(), TRANSIENT::options(), PARAM_LIST::parse(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_element_using_obsolete_callback(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_instance(), anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_instance(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_instance(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_paramset(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_paramset(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_paramset(), OPT::set_values(), anonymous_namespace{s_ac.cc}::AC::setup(), anonymous_namespace{s_dc.cc}::DC::setup(), and anonymous_namespace{s_dc.cc}::OP::setup().
{
  skipbl();
  switch (peek()) {
  case '/': _ok = umatch("//"); skip(); break;
  case ';':
  case '\'':    itested(); _ok = true;  skip();     break;
  case '\0':                _ok = true;              break;
  default:      _ok = false; warn(badness, message); break;
  }
  return *this;
}
bool CS::ctob ()
Definition at line 144 of file ap_convert.cc.
References _ok, cursor(), ONE_OF, Set(), skipbl(), and skipcom().
Referenced by PARAMETER< bool >::lookup_solve().
{
  skipbl();
  unsigned here = cursor();
  bool val = true;
  ONE_OF
    || Set(*this, "1",       &val, true)
    || Set(*this, "0",       &val, false)
    || Set(*this, "t{rue}",  &val, true)
    || Set(*this, "f{alse}", &val, false)
    || Set(*this, "y{es}",   &val, true)
    || Set(*this, "n{o}",    &val, false)
    || Set(*this, "#t{rue}", &val, true)
    || Set(*this, "#f{alse}",&val, false)
    ;
  skipcom();
  _ok = cursor() > here;
  return val;
}
char CS::ctoc ()
Definition at line 37 of file ap_convert.cc.
References _cmd, _cnt, _length, and untested.
Referenced by ctof(), ctoi(), ctoo(), ctostr(), ctou(), ctox(), get_to(), Name_String::parse(), Quoted_String::parse(), and xopen().
{
  char c=_cmd[_cnt];
  if(_cnt<=_length) {
    ++_cnt;
  }else{untested();
  }
  return c;
}
double CS::ctof ()
Definition at line 261 of file ap_convert.cc.
References _ok, ctoc(), is_alpha(), is_digit(), is_float(), skip(), skip1(), skipbl(), skipcom(), OPT::units, untested, uSI, and uSPICE.
Referenced by PROBELIST::add_list(), Get(), anonymous_namespace{c_modify.cc}::modify_fault(), and anonymous_namespace{c_modify.cc}::sweep_fix().
{
  double val = 0.0;
  double power = 1.0;
  int    sign = 1;
  skipbl();
  if (!is_float()) {
    skipcom();
    _ok = false;
    return 0.;
  }else{
  }
  if (skip1("-")) {                     // sign
    sign = -1;
  }else{
    skip1("+");
  }
  while (is_digit()) {                  // up to dec pt
    val = 10.0 * val + (ctoc()-'0');
  }
  skip1(".");                           // dec pt
  while (is_digit()) {                  // after dec pt
    val = 10.0 * val + (ctoc()-'0');
    power *= .1;
  }
  if (skip1("eE")) {                    // exponent: E form
    int expo = 0;
    int es = 1;
    if (skip1("-")) {
      es = -1;
    }else{
      skip1("+");
    }
    while (is_digit())
      expo = 10 * expo + (ctoc()-'0');
    expo *= es;
    power *= pow(10., expo);
  }else if ((OPT::units == uSPICE) && skip1("mM")) {            // M is special
    if (skip1("eE")) {                  // meg
      power *= 1e6;
    }else if (skip1("iI")) {            // mil
      power *= 25.4e-6;
    }else{                              // plain m (milli)
      power *= 1e-3;
    }
  }else if (skip1("M")) {
    assert(OPT::units == uSI);
    power *= 1e6;
  }else if (skip1("m")) {
    assert(OPT::units == uSI);
    power *= 1e-3;
  }else if (skip1("uU")) {              // other letters
    power *= 1e-6;
  }else if (skip1("nN")) {
    power *= 1e-9;
  }else if (skip1("p")) {
    power *= 1e-12;
  }else if (skip1("P")) {
    power *= ((OPT::units == uSI) ? (1e15) : 1e-12);
  }else if (skip1("fF")) {
    power *= 1e-15;
  }else if (skip1("kK")) {
    power *= 1e3;
  }else if (skip1("gG")) {
    power *= 1e9;
  }else if (skip1("tT")) {
    power *= 1e12;
  }else if (skip1("%")) {untested();
    power *= 1e-2;
  }else{
  }
  while (is_alpha()) {                  // skip letters
    skip();
  }
  skipcom();
  _ok = true;
  return (sign*val*power);
}
int CS::ctoi ()
Definition at line 169 of file ap_convert.cc.
References _ok, ctoc(), cursor(), is_digit(), skip1(), skipbl(), and skipcom().
Referenced by anonymous_namespace{c_sweep.cc}::setup(), and COMPONENT::tr_probe_num().
{
  int val = 0;
  int sign = 1;
  skipbl();
  unsigned here = cursor();
  if (skip1("-")) {
    sign = -1;
  }else{
    skip1("+");
  }
  while (is_digit()) {
    val = 10 * val + (ctoc()-'0');
  }
  skipcom();
  _ok = cursor() > here;
  return val * sign;
}
int CS::ctoo ()
Definition at line 215 of file ap_convert.cc.
References _ok, ctoc(), cursor(), is_digit(), skipbl(), and skipcom().
Referenced by Get().
{
  int val = 0;
  skipbl();
  unsigned here = cursor();
  while (is_digit()) {
    val = 8 * val + (ctoc()-'0');
  }
  skipcom();
  _ok = cursor() > here;
  return val;
}
double CS::ctopf () [inline]
Definition at line 138 of file ap.h.
{return std::abs(ctof());}
std::string CS::ctos (const std::string & term = ",=(){};", const std::string & b = "\"'{", const std::string & e = "\"'}", const std::string & trap = "")
Definition at line 71 of file ap_convert.cc.
References _cmd, _ok, cursor(), find1(), is_term(), itested, match1(), ns_more(), skip(), skip1(), skipbl(), skipcom(), untested, and warn().
Referenced by PROBELIST::add_list(), anonymous_namespace{c_system.cc}::CMD_CHDIR::do_it(), anonymous_namespace{c_delete.cc}::CMD_DELETE::do_it(), PARAMETER< bool >::operator=(), PARAMETER< bool >::parse(), PARAMETER< T >::parse(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_args(), anonymous_namespace{lang_spectre.cc}::parse_args(), anonymous_namespace{lang_verilog.cc}::parse_args_instance(), anonymous_namespace{bm_model.cc}::EVAL_BM_MODEL::parse_common_obsolete_callback(), anonymous_namespace{lang_gschem.cc}::parse_component(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_logic_using_obsolete_callback(), COMMON_COMPONENT::parse_modelname(), and PROBELIST::remove_list().
{
  assert(begin_quote.length() == end_quote.length());
  skipbl();
  unsigned begin_string = cursor();
  unsigned end_string = cursor();
  std::string s;
  std::string::size_type which_quote = find1(begin_quote);
  if (which_quote != std::string::npos) {
    int quotes = 1;
    skip(); // the quote
    begin_string = cursor();
    char the_begin_quote = begin_quote[which_quote];
    char the_end_quote = end_quote[which_quote];
    for (;;) {
      if (!ns_more()) {itested();
        end_string = cursor();
        warn(bDANGER, std::string("need ") + the_end_quote);
        break;
      }else if (skip1(the_end_quote)) {
        if (--quotes <= 0) {
          end_string = cursor() - 1;
          break;
        }else{
        }
      }else if (skip1(the_begin_quote)) {
        ++quotes;
        skip();
      }else if (skip1('\\')) {
        end_string = cursor() - 1;
        s += _cmd.substr(begin_string, end_string-begin_string);
        begin_string = cursor();
        skip1(the_end_quote);
      }else{
        skip();
      }
    }
    s += _cmd.substr(begin_string, end_string-begin_string);
  }else{
    while(ns_more() && !is_term(term)) {
      skip();
    }
    if (match1(trap)) {untested();
      warn(bDANGER, "ap_convert trap-exit");
    }else{
    }
    end_string = cursor();
    s = _cmd.substr(begin_string, end_string-begin_string);
  }
  skipcom();
  _ok = end_string > begin_string;
  return s;
}
void CS::ctostr (char * des, int len, const std::string & term)
Definition at line 56 of file ap_convert.cc.
References ctoc(), is_term(), skip(), skipbl(), skipcom(), and untested.
Referenced by findbranch().
{
  skipbl();
  int ii;
  for (ii = 0;  ii < len && !is_term(term);  ++ii) {
    des[ii] = ctoc();
  }
  des[ii] = '\0';
  while (!is_term(term)) {untested();
    skip();
  }
  skipcom();
}
unsigned CS::ctou ()
Definition at line 195 of file ap_convert.cc.
References _ok, ctoc(), cursor(), is_digit(), skipbl(), and skipcom().
{
  unsigned val = 0;
  skipbl();
  unsigned here = cursor();
  while (is_digit()) {
    val = 10 * val + static_cast<unsigned>(ctoc()-'0');
  }
  skipcom();
  _ok = cursor() > here;
  return val;
}
int CS::ctox ()
Definition at line 234 of file ap_convert.cc.
References _ok, ctoc(), cursor(), is_digit(), is_xdigit(), skipbl(), skipcom(), and untested.
Referenced by Get().
{untested();
  int val = 0;
  skipbl();
  unsigned here = cursor();
  while (is_xdigit()) {untested();
    if (is_digit()) {untested();
      val = 16 * val + (ctoc()-'0');
    }else{untested();
      val = 16 * val + (tolower(ctoc())-'a'+10);
    }
  }
  skipcom();
  _ok = cursor() > here;
  return val;
}
unsigned CS::cursor () const [inline]
Definition at line 72 of file ap.h.
Referenced by PROBELIST::add_list(), CMD::cmdproc(), anonymous_namespace{lang_spice.cc}::count_ports(), ctob(), ctoi(), ctoo(), ctos(), ctou(), ctox(), anonymous_namespace{c_attach.cc}::CMD_ATTACH::do_it(), anonymous_namespace{c_file.cc}::CMD_INCLUDE::do_it(), anonymous_namespace{c_genrat.cc}::CMD_::do_it(), anonymous_namespace{c_attach.cc}::CMD_DETACH::do_it(), anonymous_namespace{c_comand.cc}::CMD_TEMP::do_it(), anonymous_namespace{c_delete.cc}::CMD_DELETE::do_it(), anonymous_namespace{lang_spectre.cc}::CMD_MODEL::do_it(), anonymous_namespace{lang_verilog.cc}::CMD_PARAMSET::do_it(), anonymous_namespace{lang_spice.cc}::CMD_MODEL::do_it(), anonymous_namespace{lang_spice.cc}::CMD_LIB::do_it(), anonymous_namespace{c_sweep.cc}::doit(), anonymous_namespace{measure_at.cc}::MEASURE::eval(), anonymous_namespace{measure_average.cc}::MEASURE::eval(), anonymous_namespace{measure_cross.cc}::MEASURE::eval(), anonymous_namespace{measure_integral.cc}::MEASURE::eval(), anonymous_namespace{measure_min.cc}::MEASURE::eval(), anonymous_namespace{measure_rms.cc}::MEASURE::eval(), anonymous_namespace{measure_max.cc}::MEASURE::eval(), anonymous_namespace{measure_slewrate.cc}::MEASURE::eval(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::find_type_in_string(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::find_type_in_string(), anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::find_type_in_string(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::find_type_in_string(), findbranch(), anonymous_namespace{lang_spice.cc}::getmerge(), Expression::leaf(), anonymous_namespace{c_list.cc}::list_save(), anonymous_namespace{c_modify.cc}::modify_fault(), DISPATCHER< T >::operator[](), anonymous_namespace{s_dc.cc}::DCOP::options(), TRANSIENT::options(), List< T >::parse(), Float::parse(), PARAM_LIST::parse(), Quoted_String::parse(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_args(), anonymous_namespace{lang_verilog.cc}::parse_args_instance(), anonymous_namespace{lang_verilog.cc}::parse_args_paramset(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_command(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_command(), anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::parse_common_obsolete_callback(), COMMON_COMPONENT::parse_common_obsolete_callback(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_element_using_obsolete_callback(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_instance(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_logic_using_obsolete_callback(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_module(), anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_module(), anonymous_namespace{lang_gschem.cc}::parse_net(), anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR::parse_numlist(), anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX::parse_numlist(), anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::parse_numlist(), anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::parse_numlist(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::parse_numlist(), anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY::parse_numlist(), anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT::parse_numlist(), anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP::parse_numlist(), anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE::parse_numlist(), anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM::parse_numlist(), anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::parse_numlist(), EVAL_BM_VALUE::parse_numlist(), COMMON_COMPONENT::parse_param_list(), MODEL_TABLE::parse_params_obsolete_callback(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_ports(), anonymous_namespace{lang_spectre.cc}::parse_ports(), anonymous_namespace{lang_verilog.cc}::parse_ports(), PROBELIST::remove_list(), scan(), OPT::set_values(), anonymous_namespace{s_ac.cc}::AC::setup(), skiparg(), skipto1(), and umatch().
{return _cnt;}
size_t CS::find1 (const std::string & c) const [inline]
Definition at line 109 of file ap.h.
Referenced by ctos().
        {return ((ns_more()) ? c.find_first_of(peek()) : std::string::npos);}
const std::string CS::fullstring () const [inline]
Definition at line 78 of file ap.h.
Referenced by anonymous_namespace{c_sweep.cc}::buildfile(), CMD::cmdproc(), get_line(), anonymous_namespace{lang_spice.cc}::getmerge(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_command(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_command(), anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_command(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_command(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_comment(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_comment(), anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_comment(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_comment(), and anonymous_namespace{lang_spice.cc}::LANG_SPICE::parse_top_item().
{return _cmd;}
CS & CS::get_line (const std::string & prompt)
Definition at line 147 of file ap_construct.cc.
References _cmd, _cnt, _file, _length, _line_number, _ok, BUFLEN, fullstring(), getcmd(), getlines(), is_file(), itested, OPT::listing, and IO::mstdout.
Referenced by anonymous_namespace{lang_spice.cc}::CMD_LIB::do_it(), anonymous_namespace{lang_spice.cc}::getmerge(), main(), anonymous_namespace{lang_gschem.cc}::parse_component(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_module(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_module(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_module_body(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_top_item(), LANGUAGE::parse_top_item(), anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_top_item(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_top_item(), and anonymous_namespace{lang_spice.cc}::LANG_SPICE::parse_top_item().
{
  ++_line_number;
  if (is_file()) {
    _cmd = getlines(_file);
    _cnt = 0;
    _length = static_cast<unsigned>(_cmd.length());
    _ok = true;
  }else{itested();
    assert(_file == stdin);
    char cmdbuf[BUFLEN];
    getcmd(prompt.c_str(), cmdbuf, BUFLEN);
    _cmd = cmdbuf;
    _cnt = 0;
    _length = static_cast<unsigned>(_cmd.length());
    _ok = true;
  }
  if (OPT::listing) {
    IO::mstdout << "\"" << fullstring() << "\"\n";
  }else{
  }
  return *this;
}
std::string CS::get_to (const std::string & term)
Definition at line 131 of file ap_convert.cc.
References ctoc(), match1(), and ns_more().
{
  std::string des;
  while(ns_more() && !match1(term)) {
    des += ctoc();
  }
  return des;
}
bool CS::gotit (unsigned last) [inline]
Definition at line 74 of file ap.h.
Referenced by COMMON_COMPONENT::parse_common_obsolete_callback(), anonymous_namespace{bm_generator.cc}::EVAL_BM_GENERATOR::parse_numlist(), anonymous_namespace{bm_complex.cc}::EVAL_BM_COMPLEX::parse_numlist(), anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::parse_numlist(), anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::parse_numlist(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::parse_numlist(), anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY::parse_numlist(), anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT::parse_numlist(), anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP::parse_numlist(), anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE::parse_numlist(), anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM::parse_numlist(), anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::parse_numlist(), EVAL_BM_VALUE::parse_numlist(), and COMMON_COMPONENT::parse_param_list().
{return last<_cnt;}
bool CS::is_alnum () const [inline]
Definition at line 118 of file ap.h.
Referenced by PROBELIST::add_list(), anonymous_namespace{lang_verilog.cc}::parse_args_instance(), anonymous_namespace{lang_spectre.cc}::parse_ports(), and anonymous_namespace{lang_verilog.cc}::parse_ports().
{return !!isalnum(toascii(peek()));}
bool CS::is_alpha () const [inline]
Definition at line 117 of file ap.h.
Referenced by ctof(), anonymous_namespace{c_modify.cc}::modify_fault(), PARAM_LIST::parse(), Name_String::parse(), COMMON_COMPONENT::parse_common_obsolete_callback(), and skiparg().
{return !!isalpha(toascii(peek()));}
bool CS::is_argsym () const [inline]
Definition at line 116 of file ap.h.
Referenced by skiparg().
{return (match1("*?$%_&@"));}
bool CS::is_digit () const [inline]
Definition at line 113 of file ap.h.
Referenced by ctof(), ctoi(), ctoo(), ctou(), ctox(), Name_String::parse(), and anonymous_namespace{c_sweep.cc}::setup().
{return (match1("0123456789"));}
bool CS::is_end () [inline]
Definition at line 87 of file ap.h.
Referenced by anonymous_namespace{lang_spice.cc}::count_ports(), anonymous_namespace{c_param.cc}::CMD_PARAM::do_it(), anonymous_namespace{c_prbcmd.cc}::do_probe(), anonymous_namespace{c_list.cc}::list_save(), LANGUAGE::new__instance(), anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::parse_common_obsolete_callback(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_module_body(), and xopen().
{return !more();}
bool CS::is_file () [inline]
Definition at line 88 of file ap.h.
Referenced by get_line(), and anonymous_namespace{lang_spice.cc}::LANG_SPICE::parse_top_item().
{return (_file && !isatty(fileno(_file)));}
bool CS::is_first_read () const [inline]
Definition at line 89 of file ap.h.
References untested.
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE::parse_top_item().
{untested(); return (_line_number == 0);}
bool CS::is_float () const [inline]
Definition at line 115 of file ap.h.
Referenced by ctof(), anonymous_namespace{s_dc.cc}::DCOP::options(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_args(), EVAL_BM_ACTION_BASE::parse_func_type(), anonymous_namespace{s_fo.cc}::FOURIER::setup(), anonymous_namespace{s_ac.cc}::AC::setup(), TRANSIENT::setup(), anonymous_namespace{s_dc.cc}::DC::setup(), anonymous_namespace{s_dc.cc}::OP::setup(), skiparg(), and anonymous_namespace{c_modify.cc}::sweep_fix().
{return (match1("+-.0123456789"));}
bool CS::is_pfloat () const [inline]
Definition at line 114 of file ap.h.
Referenced by Name_String::parse(), anonymous_namespace{s_fo.cc}::FOURIER::setup(), and TRANSIENT::setup().
{return (match1(".0123456789"));}
bool CS::is_term (const std::string & t = ",=(){};") [inline]
Definition at line 119 of file ap.h.
Referenced by ctos(), ctostr(), and umatch().
                                                {};")
        {char c=peek(); return (c=='\0' || isspace(c) || match1(t));}
bool CS::is_xdigit () const [inline]
Definition at line 111 of file ap.h.
References untested.
Referenced by ctox().
                {untested(); return (match1("0123456789abcdefABCDEF"));}
std::string CS::last_match () const
Definition at line 108 of file ap_match.cc.
References _begin_match, _cmd, and _end_match.
Referenced by Expression::addexptail(), Expression::andtail(), Expression::exptail(), Expression::factor(), Expression::logicaltail(), and Expression::termtail().
{
  return _cmd.substr(_begin_match, _end_match-_begin_match);
}
bool CS::match1 (char c) const [inline]
Definition at line 106 of file ap.h.
Referenced by PROBELIST::add_list(), ctos(), anonymous_namespace{c_file.cc}::CMD_LOG::do_it(), anonymous_namespace{c_file.cc}::CMD_FILE::do_it(), anonymous_namespace{lang_spice.cc}::CMD_RUN::do_it(), anonymous_namespace{c_prbcmd.cc}::do_probe(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::find_type_in_string(), get_to(), anonymous_namespace{c_list.cc}::list_save(), anonymous_namespace{s_dc.cc}::DCOP::options(), PARAMETER< T >::parse(), List< T >::parse(), PARAM_LIST::parse(), Name_String::parse(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_args(), anonymous_namespace{lang_verilog.cc}::parse_args_instance(), anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::parse_common_obsolete_callback(), EVAL_BM_ACTION_BASE::parse_func_type(), anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::parse_numlist(), anonymous_namespace{s_fo.cc}::FOURIER::setup(), anonymous_namespace{s_ac.cc}::AC::setup(), TRANSIENT::setup(), anonymous_namespace{s_dc.cc}::DC::setup(), anonymous_namespace{s_dc.cc}::OP::setup(), skip1(), and skipto1().
{return (peek()==c);}
bool CS::match1 (const std::string & c) const [inline]
Definition at line 107 of file ap.h.
                {return ns_more() && strchr(c.c_str(),peek());}
bool CS::more () [inline]
Definition at line 86 of file ap.h.
Referenced by anonymous_namespace{c_attach.cc}::CMD_ATTACH::do_it(), anonymous_namespace{c_system.cc}::CMD_EDIT::do_it(), anonymous_namespace{c_genrat.cc}::CMD_::do_it(), anonymous_namespace{c_system.cc}::CMD_SYSTEM::do_it(), anonymous_namespace{c_file.cc}::CMD_LOG::do_it(), anonymous_namespace{c_system.cc}::CMD_CHDIR::do_it(), anonymous_namespace{c_delete.cc}::CMD_DELETE::do_it(), anonymous_namespace{c_file.cc}::CMD_FILE::do_it(), anonymous_namespace{c_comand.cc}::CMD_TITLE::do_it(), anonymous_namespace{c_sweep.cc}::CMD_SWEEP::do_it(), anonymous_namespace{c_prbcmd.cc}::do_probe(), anonymous_namespace{measure_integral.cc}::MEASURE::eval(), anonymous_namespace{measure_at.cc}::MEASURE::eval(), anonymous_namespace{measure_average.cc}::MEASURE::eval(), anonymous_namespace{measure_cross.cc}::MEASURE::eval(), anonymous_namespace{measure_max.cc}::MEASURE::eval(), anonymous_namespace{measure_min.cc}::MEASURE::eval(), anonymous_namespace{measure_rms.cc}::MEASURE::eval(), anonymous_namespace{measure_slewrate.cc}::MEASURE::eval(), anonymous_namespace{lang_spice.cc}::getmerge(), anonymous_namespace{s_dc.cc}::DCOP::options(), TRANSIENT::options(), PARAM_LIST::parse(), Quoted_String::parse(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_args(), anonymous_namespace{lang_spectre.cc}::parse_args(), anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::parse_common_obsolete_callback(), COMMON_COMPONENT::parse_param_list(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_ports(), scan(), OPT::set_values(), anonymous_namespace{s_ac.cc}::AC::setup(), and anonymous_namespace{s_dc.cc}::DC::setup().
{skipbl(); return ns_more();}
bool CS::ns_more () const [inline]
Definition at line 85 of file ap.h.
Referenced by ctos(), get_to(), and skipto1().
{return peek()!='\0';}
CS::operator bool () const [inline]
Definition at line 75 of file ap.h.
{return _ok;}
CS & CS::operator= (const std::string & s)
Definition at line 123 of file ap_construct.cc.
References _cmd, _cnt, _file, _length, _ok, and untested.
{untested();
  assert(!_file);
  _cmd = s;
  _cnt = 0;
  _ok = true;
  _length = static_cast<unsigned>(s.length());
  return *this;
}
CS& CS::operator= (const CS & p)
CS& CS::operator>> (bool & x) [inline]
Definition at line 139 of file ap.h.
{x=ctob();return *this;}
CS& CS::operator>> (char & x) [inline]
Definition at line 140 of file ap.h.
References untested.
{untested(); x=ctoc();return *this;}
CS& CS::operator>> (int & x) [inline]
Definition at line 141 of file ap.h.
{x=ctoi();return *this;}
CS& CS::operator>> (unsigned & x) [inline]
Definition at line 142 of file ap.h.
{x=ctou();return *this;}
CS& CS::operator>> (double & x) [inline]
Definition at line 143 of file ap.h.
{x=ctof();return *this;}
CS& CS::operator>> (std::string & x) [inline]
Definition at line 144 of file ap.h.
{x=ctos();return *this;}
CS& CS::operator>> (const char & x) [inline]
Definition at line 158 of file ap.h.
{return skip1b(x);}
CS& CS::operator>> (const char * x) [inline]
Definition at line 159 of file ap.h.
{return umatch(x);}
char CS::peek () const [inline]
Definition at line 82 of file ap.h.
Referenced by check(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::find_type_in_string(), Expression::leaf(), skiparg(), skipbl(), and umatch().
{return _cmd[_cnt];}
CS& CS::reset (unsigned c = 0) [inline]
Definition at line 92 of file ap.h.
Referenced by PROBELIST::add_list(), anonymous_namespace{lang_spice.cc}::count_ports(), anonymous_namespace{c_attach.cc}::CMD_ATTACH::do_it(), anonymous_namespace{c_attach.cc}::CMD_DETACH::do_it(), anonymous_namespace{c_list.cc}::CMD_SAVE::do_it(), anonymous_namespace{lang_spice.cc}::CMD_LIB::do_it(), anonymous_namespace{measure_at.cc}::MEASURE::eval(), anonymous_namespace{measure_average.cc}::MEASURE::eval(), anonymous_namespace{measure_cross.cc}::MEASURE::eval(), anonymous_namespace{measure_integral.cc}::MEASURE::eval(), anonymous_namespace{measure_max.cc}::MEASURE::eval(), anonymous_namespace{measure_min.cc}::MEASURE::eval(), anonymous_namespace{measure_rms.cc}::MEASURE::eval(), anonymous_namespace{measure_slewrate.cc}::MEASURE::eval(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::find_type_in_string(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::find_type_in_string(), anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::find_type_in_string(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::find_type_in_string(), findbranch(), anonymous_namespace{c_list.cc}::list_save(), anonymous_namespace{c_modify.cc}::modify_fault(), DISPATCHER< T >::operator[](), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_command(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_command(), anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_command(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_command(), anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::parse_common_obsolete_callback(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_element_using_obsolete_callback(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_instance(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_instance(), anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_instance(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_instance(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_logic_using_obsolete_callback(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_module(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_module(), anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_module(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_module(), anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::parse_numlist(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::parse_numlist(), anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY::parse_numlist(), anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT::parse_numlist(), MODEL_TABLE::parse_params_obsolete_callback(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_paramset(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_paramset(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_paramset(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_ports(), anonymous_namespace{lang_spectre.cc}::parse_ports(), scan(), skipto1(), and umatch().
{_cnt=c; _ok=true; return *this;}
CS & CS::scan (const std::string & s)
Definition at line 90 of file ap_match.cc.
References _ok, cursor(), more(), reset(), skiparg(), and umatch().
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::find_type_in_string(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::find_type_in_string(), and scan_get().
{
  unsigned start = cursor();
  for (;;) {
    if (umatch(s)) {     // found it
      _ok = true;
      break;
    }else if (!more()) { // ran out
      reset(start);
      _ok = false;
      break;
    }else{               // skip and try again
      skiparg();
    }
  }
  return *this;
}
CS& CS::skip (int c = 1) [inline]
Definition at line 147 of file ap.h.
Referenced by check(), ctof(), ctos(), ctostr(), anonymous_namespace{c_file.cc}::CMD_LOG::do_it(), anonymous_namespace{c_file.cc}::CMD_FILE::do_it(), anonymous_namespace{lang_spice.cc}::CMD_RUN::do_it(), anonymous_namespace{c_prbcmd.cc}::do_probe(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::find_type_in_string(), anonymous_namespace{c_list.cc}::list_save(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_command(), skip1(), skiparg(), skipbl(), skipto1(), umatch(), and xopen().
    {_cnt=static_cast<unsigned>(static_cast<int>(_cnt)+c); _ok=_cnt<=_length; return *this;}
CS & CS::skip1 (char t)
Definition at line 57 of file ap_skip.cc.
References _ok, match1(), and skip().
Referenced by ctof(), ctoi(), ctos(), Quoted_String::parse(), and skip1b().
{
  if (match1(t)) {
    skip();
    assert(_ok);
  }else{
    _ok = false;
  }
  return *this;
}
CS & CS::skip1 (const std::string & t)
Definition at line 82 of file ap_skip.cc.
References _ok, match1(), and skip().
{
  if (match1(t)) {
    skip();
    assert(_ok);
  }else{
    _ok = false;
  }
  return *this;
}
CS & CS::skip1b (char t)
Definition at line 46 of file ap_skip.cc.
References skip1(), and skipbl().
Referenced by PROBELIST::add_list(), Expression::arglist(), Expression::arglisttail(), anonymous_namespace{lang_spice.cc}::count_ports(), anonymous_namespace{c_measure.cc}::CMD_MEASURE::do_it(), anonymous_namespace{lang_spice.cc}::CMD_MODEL::do_it(), Expression::factor(), Get(), anonymous_namespace{c_modify.cc}::modify_fault(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_args(), COMMON_COMPONENT::parse_common_obsolete_callback(), EVAL_BM_ACTION_BASE::parse_func_type(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_instance(), MODEL_TABLE::parse_params_obsolete_callback(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_ports(), and PROBELIST::remove_list().
{
  skipbl();
  skip1(t);
  skipbl();
  return *this;
}
CS & CS::skip1b (const std::string & t)
Definition at line 71 of file ap_skip.cc.
References skip1(), and skipbl().
{
  skipbl();
  skip1(t);
  skipbl();
  return *this;
}
CS & CS::skiparg ()
Definition at line 96 of file ap_skip.cc.
References _ok, cursor(), is_alpha(), is_argsym(), is_float(), peek(), skip(), skipcom(), and untested.
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::find_type_in_string(), anonymous_namespace{c_modify.cc}::modify_fault(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_args(), scan(), and OPT::set_values().
{
  unsigned here = cursor();
  if (!skipcom()) {
    if (peek()) {
      skip();
    }else{
    }
    while (is_alpha() || is_float() || is_argsym()) {
      skip();
    }
    skipcom();
  }else{untested();
    // empty field, just a comma
  }
  _ok = cursor() > here;
  return *this;
}
CS & CS::skipbl ()
Definition at line 35 of file ap_skip.cc.
References peek(), and skip().
Referenced by check(), ctob(), ctof(), ctoi(), ctoo(), ctos(), ctostr(), ctou(), ctox(), anonymous_namespace{c_file.cc}::CMD_LOG::do_it(), anonymous_namespace{c_file.cc}::CMD_FILE::do_it(), anonymous_namespace{lang_spice.cc}::CMD_RUN::do_it(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::find_type_in_string(), Name_String::parse(), Quoted_String::parse(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_command(), anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::parse_common_obsolete_callback(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_module(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_paramset(), skip1b(), anonymous_namespace{lang_spice.cc}::skip_pre_stuff(), umatch(), and xopen().
{
  while (peek() && (!isgraph(peek()))) {
    skip();
  }
  return *this;
}
CS& CS::skipcom () [inline]
Definition at line 157 of file ap.h.
Referenced by ctob(), ctof(), ctoi(), ctoo(), ctos(), ctostr(), ctou(), ctox(), skiparg(), umatch(), and xopen().
{return skip1b(",");}
CS & CS::skipto1 (const std::string & t)
Definition at line 118 of file ap_skip.cc.
References _ok, cursor(), match1(), ns_more(), reset(), skip(), and untested.
Referenced by Tail_String::parse().
{untested();
  unsigned here = cursor();
  while (ns_more() && !match1(t)) {untested();
    skip();
  }
  _ok = ns_more();
  if (!_ok) {untested();
    reset(here);
  }else{untested();
  }
  return *this;
}
CS & CS::skipto1 (char c)
Definition at line 135 of file ap_skip.cc.
References _ok, cursor(), match1(), ns_more(), reset(), skip(), and untested.
{
  unsigned here = cursor();
  while (ns_more() && !match1(c)) {
    skip();
  }
  _ok = ns_more();
  if (!_ok) {untested();
    reset(here);
  }else{
  }
  return *this;
}
bool CS::stuck (unsigned * last) [inline]
Definition at line 73 of file ap.h.
Referenced by anonymous_namespace{c_attach.cc}::CMD_ATTACH::do_it(), anonymous_namespace{c_genrat.cc}::CMD_::do_it(), anonymous_namespace{c_comand.cc}::CMD_TEMP::do_it(), anonymous_namespace{lang_spice.cc}::CMD_MODEL::do_it(), anonymous_namespace{measure_at.cc}::MEASURE::eval(), anonymous_namespace{measure_average.cc}::MEASURE::eval(), anonymous_namespace{measure_cross.cc}::MEASURE::eval(), anonymous_namespace{measure_integral.cc}::MEASURE::eval(), anonymous_namespace{measure_max.cc}::MEASURE::eval(), anonymous_namespace{measure_min.cc}::MEASURE::eval(), anonymous_namespace{measure_rms.cc}::MEASURE::eval(), anonymous_namespace{measure_slewrate.cc}::MEASURE::eval(), anonymous_namespace{lang_spice.cc}::getmerge(), Expression::leaf(), anonymous_namespace{s_dc.cc}::DCOP::options(), TRANSIENT::options(), List< T >::parse(), Float::parse(), PARAM_LIST::parse(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_args(), anonymous_namespace{lang_spectre.cc}::parse_args(), anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::parse_common_obsolete_callback(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_element_using_obsolete_callback(), anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::parse_numlist(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::parse_numlist(), anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY::parse_numlist(), anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT::parse_numlist(), anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP::parse_numlist(), anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE::parse_numlist(), anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM::parse_numlist(), anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::parse_numlist(), COMMON_COMPONENT::parse_param_list(), MODEL_TABLE::parse_params_obsolete_callback(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_ports(), OPT::set_values(), and anonymous_namespace{s_ac.cc}::AC::setup().
{bool ok=*last<_cnt; *last=_cnt; return !ok;}
const std::string CS::substr (unsigned i) const [inline]
Definition at line 79 of file ap.h.
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::find_type_in_string().
{return ((_cmd.length()>=i) ? _cmd.substr(i) : "");}
const std::string CS::substr (unsigned i, unsigned n) const [inline]
Definition at line 80 of file ap.h.
{return _cmd.substr(i,n);}
const std::string CS::tail () const [inline]
Definition at line 81 of file ap.h.
Referenced by anonymous_namespace{c_system.cc}::CMD_EDIT::do_it(), anonymous_namespace{c_system.cc}::CMD_SYSTEM::do_it(), anonymous_namespace{c_comand.cc}::CMD_TITLE::do_it(), anonymous_namespace{lang_gschem.cc}::CMD_C::do_it(), anonymous_namespace{lang_spectre.cc}::CMD_SIMULATOR::do_it(), Tail_String::parse(), and anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_command().
{return substr(_cnt);}
std::string CS::trimmed_last_match (const std::string & suf = " ,=;") const
Definition at line 113 of file ap_match.cc.
References _begin_match, _cmd, and _end_match.
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::find_type_in_string(), and anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::find_type_in_string().
{
  unsigned real_end = _end_match;
  while (strchr(suf.c_str(), _cmd[real_end-1])) {
    --real_end;
  }
  return _cmd.substr(_begin_match, real_end-_begin_match);
}
CS & CS::umatch (const std::string & s)
Definition at line 30 of file ap_match.cc.
References _begin_match, _end_match, _ok, OPT::case_insensitive, cursor(), is_term(), peek(), reset(), skip(), skipbl(), and skipcom().
Referenced by PROBELIST::add_list(), check(), CMD::cmdproc(), anonymous_namespace{c_attach.cc}::CMD_ATTACH::do_it(), anonymous_namespace{c_status.cc}::CMD_STATUS::do_it(), anonymous_namespace{c_delete.cc}::CMD_DELETE::do_it(), anonymous_namespace{lang_spice.cc}::CMD_LIB::do_it(), anonymous_namespace{c_prbcmd.cc}::do_probe(), anonymous_namespace{c_sweep.cc}::doit(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::find_type_in_string(), Get(), anonymous_namespace{lang_spice.cc}::getmerge(), anonymous_namespace{s_dc.cc}::DCOP::options(), TRANSIENT::options(), outset(), anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::parse_common_obsolete_callback(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_instance(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_logic_using_obsolete_callback(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_module_body(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_ports(), scan(), Set(), OPT::set_values(), anonymous_namespace{c_sweep.cc}::setup(), ELEMENT::skip_dev_type(), anonymous_namespace{lang_spice.cc}::skip_pre_stuff(), anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::skip_type_tail(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::skip_type_tail(), COMPONENT::tr_probe_num(), and Umatch().
{
  unsigned start = cursor();
  skipbl();
  unsigned begin_match = cursor();
  const char* str2 = s.c_str();
  bool optional = 0;
  for (;;) {
    if ((!*str2) || (*str2 == '|')) {
      _ok = true;
      break;
    }else if ((str2[0] == '\\') && (peek() == str2[1])) {
      skip();
      str2 += 2;
    }else if ((!optional) && (*str2 == '{')) {
      ++str2;
      optional = true;
    }else if ((optional) && (*str2 == '}')) {
      ++str2;
      optional = false;
    }else if ((*str2 == ' ') && is_term()) {
      // blank in ref string matches anything that delimits tokens
      skipbl();
      ++str2;
    }else if (peek() == *str2) {
      skip();
      ++str2;
    }else if ((OPT::case_insensitive) && (tolower(peek()) == tolower(*str2))) {
      skip();
      ++str2;
    }else if (optional) {
      while (*str2 != '}') {
        ++str2;
      }
    }else{
      // mismatch
      const char* bar = strchr(str2, '|');
      if (bar && (bar[-1] != '\\')) {
        str2 = bar+1;
        reset(start);
      }else{
        _ok = false;
        break;
      }
    }
  }
  if (_ok) {
    _begin_match = begin_match;
    _end_match = cursor();
    skipcom();
    _ok = true;
  }else{
    reset(start);
    _ok = false;
  }
  return *this;
}
CS & CS::warn (int badness, unsigned spot, const std::string & message)
Definition at line 53 of file ap_error.cc.
References _cmd, IO::error, OPT::picky, and OMSTREAM::tab().
Referenced by PROBELIST::add_list(), check(), CMD::cmdproc(), ctos(), anonymous_namespace{c_measure.cc}::CMD_MEASURE::do_it(), anonymous_namespace{c_attach.cc}::CMD_ATTACH::do_it(), anonymous_namespace{c_file.cc}::CMD_INCLUDE::do_it(), anonymous_namespace{c_delete.cc}::CMD_DELETE::do_it(), anonymous_namespace{lang_spectre.cc}::CMD_MODEL::do_it(), anonymous_namespace{lang_verilog.cc}::CMD_PARAMSET::do_it(), anonymous_namespace{lang_spice.cc}::CMD_MODEL::do_it(), anonymous_namespace{c_sweep.cc}::doit(), LANGUAGE::new__instance(), anonymous_namespace{s_dc.cc}::DCOP::options(), TRANSIENT::options(), List< T >::parse(), Quoted_String::parse(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_args(), anonymous_namespace{lang_spectre.cc}::parse_args(), anonymous_namespace{lang_verilog.cc}::parse_args_instance(), anonymous_namespace{lang_verilog.cc}::parse_args_paramset(), anonymous_namespace{bm_cond.cc}::EVAL_BM_COND::parse_common_obsolete_callback(), COMMON_COMPONENT::parse_common_obsolete_callback(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_element_using_obsolete_callback(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_instance(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_logic_using_obsolete_callback(), MODEL_TABLE::parse_params_obsolete_callback(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_ports(), anonymous_namespace{lang_spectre.cc}::parse_ports(), anonymous_namespace{lang_verilog.cc}::parse_ports(), PROBELIST::remove_list(), and OPT::set_values().
{
  if (badness >= OPT::picky) {
    if (spot < 40) {
      IO::error << _cmd.substr(0,70) << '\n';
      IO::error.tab(spot);
    }else{
      IO::error << _cmd.substr(0,15) << " ... " << _cmd.substr(spot-20, 56) << '\n';
      IO::error.tab(40);
    }
    IO::error << "^ ? " + message + '\n';
  }else{
  }
  return *this;
}
CS& CS::warn (int i, const std::string & s) [inline]
Definition at line 97 of file ap.h.
References warn().
Referenced by warn().
{return warn(i,cursor(), s);}
Member Data Documentation
unsigned CS::_begin_match [private]
Definition at line 55 of file ap.h.
Referenced by last_match(), trimmed_last_match(), and umatch().
std::string CS::_cmd [private]
Definition at line 52 of file ap.h.
Referenced by CS(), ctoc(), ctos(), get_line(), last_match(), operator=(), trimmed_last_match(), and warn().
unsigned CS::_cnt [private]
Definition at line 53 of file ap.h.
Referenced by ctoc(), get_line(), and operator=().
unsigned CS::_end_match [private]
Definition at line 56 of file ap.h.
Referenced by last_match(), trimmed_last_match(), and umatch().
FILE* CS::_file [private]
Definition at line 50 of file ap.h.
Referenced by CS(), get_line(), and operator=().
unsigned CS::_length [private]
Definition at line 54 of file ap.h.
Referenced by CS(), ctoc(), get_line(), and operator=().
int CS::_line_number [private]
Definition at line 58 of file ap.h.
Referenced by get_line().
std::string CS::_name [private]
Definition at line 51 of file ap.h.
bool CS::_ok [private]
Definition at line 57 of file ap.h.
Referenced by check(), ctob(), ctof(), ctoi(), ctoo(), ctos(), ctou(), ctox(), get_line(), operator=(), scan(), skip1(), skiparg(), skipto1(), and umatch().
The documentation for this class was generated from the following files:
savant/gnucap/src/ap.h
savant/gnucap/src/ap_construct.cc
savant/gnucap/src/ap_convert.cc
savant/gnucap/src/ap_error.cc
savant/gnucap/src/ap_match.cc
savant/gnucap/src/ap_skip.cc