gnucap: anonymous_namespace{c_attach.cc}::CMD_ATTACH Class Reference
anonymous_namespace{c_attach.cc}::CMD_ATTACH Class Reference
Public Member Functions
void do_it (CS &cmd, CARD_LIST *)
Detailed Description
Definition at line 32 of file c_attach.cc.
Member Function Documentation
void anonymous_namespace{c_attach.cc}::CMD_ATTACH::do_it (CS & cmd, CARD_LIST *) [inline, virtual]
Implements CMD.
Definition at line 34 of file c_attach.cc.
References CARD_LIST::card_list, CS::cursor(), itested, CS::more(), CS::reset(), CS::stuck(), CS::umatch(), untested, and CS::warn().
  {
    unsigned here = cmd.cursor();
    int dl_scope = RTLD_LOCAL;
    int check = RTLD_NOW;
    // RTLD_NOW means to resolve symbols on loading
    // RTLD_LOCAL means symbols defined in a plugin are local
    do {
      if (cmd.umatch("public ")) {
        dl_scope = RTLD_GLOBAL;
        // RTLD_GLOBAL means symbols defined in a plugin are global
        // Use this when a plugin depends on another.
      }else if (cmd.umatch("lazy ")) {
        check = RTLD_LAZY;
        // RTLD_LAZY means to defer resolving symbols until needed
        // Use when a plugin will not load because of unresolved symbols,
        // but it may work without it.
      }else{
      }
    } while (cmd.more() && !cmd.stuck(&here));
    std::string file_name;
    cmd >> file_name;
    void* handle = attach_list[file_name];
    if (handle) {
      if (CARD_LIST::card_list.is_empty()) {
        cmd.warn(bDANGER, here, "\"" + file_name + "\": already loaded, replacing");
        dlclose(handle);
        attach_list[file_name] = NULL;
      }else{untested();
        cmd.reset(here);
        throw Exception_CS("already loaded, cannot replace when there is a circuit", cmd);
      }
    }else{
    }
    handle = dlopen(file_name.c_str(), check | dl_scope);
    if (handle) {
      attach_list[file_name] = handle;
    }else{itested();
      cmd.reset(here);
      throw Exception_CS(dlerror(), cmd);
    }
  }
The documentation for this class was generated from the following file:
savant/gnucap/src/c_attach.cc