gnucap: PARAMETER< T > Class Template Reference
PARAMETER< T > Class Template Reference
#include <u_parameter.h>
Public Member Functions
PARAMETER ()
PARAMETER (const PARAMETER< double > &p)
PARAMETER (T v)
~PARAMETER ()
bool has_hard_value () const
bool has_good_value () const
operator T () const
T e_val (const T &def, const CARD_LIST *scope) const
void parse (CS &cmd)
std::string string () const
void print (OMSTREAM &o) const
void set_default (const T &v)
void operator= (const PARAMETER &p)
void operator= (const T &v)
void operator= (const std::string &s)
bool operator== (const PARAMETER &p) const
bool operator== (const T &v) const
T * pointer_hack ()
Private Member Functions
T lookup_solve (const T &def, const CARD_LIST *scope) const
Private Attributes
T _v
std::string _s
Detailed Description
template<class T>
class PARAMETER< T >
Definition at line 37 of file u_parameter.h.
Constructor & Destructor Documentation
template<class T> PARAMETER< T >::PARAMETER () [inline, explicit]
Definition at line 42 of file u_parameter.h.
:_v(NOT_INPUT), _s() {}
template<class T> PARAMETER< T >::PARAMETER (const PARAMETER< double > & p) [inline]
Definition at line 43 of file u_parameter.h.
:_v(p._v), _s(p._s) {}
template<class T> PARAMETER< T >::PARAMETER (T v) [inline, explicit]
Definition at line 44 of file u_parameter.h.
:_v(v), _s() {}
template<class T> PARAMETER< T >::~PARAMETER () [inline]
Definition at line 46 of file u_parameter.h.
{}
Member Function Documentation
template<class T> T PARAMETER< T >::e_val (const T & def, const CARD_LIST * scope) const
Definition at line 262 of file u_parameter.h.
References error(), itested, NOT_INPUT, OPT::recursion, and untested.
Referenced by e_val(), anonymous_namespace{func_core.cc}::abs::eval(), anonymous_namespace{measure_at.cc}::MEASURE::eval(), anonymous_namespace{measure_average.cc}::MEASURE::eval(), anonymous_namespace{measure_cross.cc}::MEASURE::eval(), anonymous_namespace{measure_integral.cc}::MEASURE::eval(), anonymous_namespace{measure_max.cc}::MEASURE::eval(), anonymous_namespace{measure_min.cc}::MEASURE::eval(), anonymous_namespace{measure_rms.cc}::MEASURE::eval(), anonymous_namespace{measure_eval.cc}::MEASURE::eval(), anonymous_namespace{measure_slewrate.cc}::MEASURE::eval(), anonymous_namespace{func_core.cc}::sqrt::eval(), anonymous_namespace{func_core.cc}::log::eval(), anonymous_namespace{func_core.cc}::exp::eval(), anonymous_namespace{func_core.cc}::INT::eval(), anonymous_namespace{func_core.cc}::pow::eval(), anonymous_namespace{func_core.cc}::MAX::eval(), anonymous_namespace{func_core.cc}::MIN::eval(), anonymous_namespace{func_core.cc}::IF::eval(), anonymous_namespace{func_core.cc}::sin::eval(), anonymous_namespace{func_core.cc}::sinh::eval(), anonymous_namespace{func_core.cc}::cos::eval(), anonymous_namespace{func_core.cc}::cosh::eval(), anonymous_namespace{func_core.cc}::tan::eval(), anonymous_namespace{func_core.cc}::tanh::eval(), anonymous_namespace{func_core.cc}::na::eval(), anonymous_namespace{func_core.cc}::RANDOM_STUB::eval(), anonymous_namespace{s_dc.cc}::DCOP::fix_args(), PARAMETER< T >::lookup_solve(), SDP::operator()(), TRANSIENT::options(), anonymous_namespace{bm_tanh.cc}::EVAL_BM_TANH::precalc_first(), EVAL_BM_SEMI_BASE::precalc_first(), anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::precalc_first(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::precalc_first(), MODEL_CARD::precalc_first(), anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY::precalc_first(), anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT::precalc_first(), anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP::precalc_first(), anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE::precalc_first(), anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM::precalc_first(), anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::precalc_first(), anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::precalc_first(), MODEL_TABLE::precalc_first(), EVAL_BM_ACTION_BASE::precalc_first(), MODEL_SEMI_BASE::precalc_first(), COMMON_COMPONENT::precalc_first(), MODEL_LOGIC::precalc_first(), MODEL_SEMI_CAPACITOR::precalc_first(), MODEL_SEMI_RESISTOR::precalc_first(), anonymous_namespace{d_switch.cc}::MODEL_SWITCH::precalc_first(), COMPONENT::precalc_first(), anonymous_namespace{s_fo.cc}::FOURIER::setup(), TRANSIENT::setup(), anonymous_namespace{s_dc.cc}::DC::setup(), anonymous_namespace{s_dc.cc}::OP::setup(), and Token_SYMBOL::stack_op().
{
  assert(scope);
  static int recursion=0;
  static const std::string* first_name = NULL;
  if (recursion == 0) {
    first_name = &_s;
  }else{
  }
  assert(first_name);
  ++recursion;
  if (_s == "") {
    // blank string means to use default value
    _v = def;
    if (recursion > 1) {
      error(bWARNING, "parameter " + *first_name + " has no value\n");
    }else{
    }
  }else if (_s != "#") {
    // anything else means look up the value
    if (recursion <= OPT::recursion) {
      _v = lookup_solve(def, scope);
      if (_v == NOT_INPUT) {untested();itested();
        error(bDANGER, "parameter " + *first_name + " has no value\n");
      }else{
      }
    }else{untested();
      _v = def;
      error(bDANGER, "parameter " + *first_name + " recursion too deep\n");
    }
  }else{
    // start with # means we have a final value
  }
  --recursion;
  return _v;
}
template<class T> bool PARAMETER< T >::has_good_value () const [inline]
Definition at line 49 of file u_parameter.h.
Referenced by SDP::has_good_value(), has_good_value(), and TRANSIENT::setup().
{return (_v != NOT_INPUT);}
template<class T> bool PARAMETER< T >::has_hard_value () const [inline]
Definition at line 48 of file u_parameter.h.
Referenced by PARAM_LIST::deep_lookup(), EVAL_BM_ACTION_BASE::has_ext_args(), SDP::has_hard_value(), has_hard_value(), SDP::has_value(), EVAL_BM_VALUE::is_trivial(), SDP::l_has_value(), PARAMETER< bool >::operator==(), SDP::p_has_value(), anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::param_is_printable(), COMMON_COMPONENT::param_is_printable(), COMPONENT::param_is_printable(), MODEL_TABLE::precalc_first(), anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT::precalc_last(), anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::precalc_last(), MODEL_TABLE::print_args_obsolete_callback(), EVAL_BM_SEMI_BASE::print_common_obsolete_callback(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::print_common_obsolete_callback(), anonymous_namespace{bm_poly.cc}::EVAL_BM_POLY::print_common_obsolete_callback(), anonymous_namespace{bm_posy.cc}::EVAL_BM_POSY::print_common_obsolete_callback(), anonymous_namespace{bm_fit.cc}::EVAL_BM_FIT::print_common_obsolete_callback(), anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP::print_common_obsolete_callback(), anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM::print_common_obsolete_callback(), anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::print_common_obsolete_callback(), EVAL_BM_ACTION_BASE::print_common_obsolete_callback(), COMMON_COMPONENT::print_common_obsolete_callback(), anonymous_namespace{s_fo.cc}::FOURIER::setup(), TRANSIENT::setup(), Token_SYMBOL::stack_op(), anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::tr_eval(), and SDP::w_has_value().
{return (_s != "");}
template<class T> T PARAMETER< T >::lookup_solve (const T & def, const CARD_LIST * scope) const [inline, private]
Definition at line 238 of file u_parameter.h.
References CS::_STRING, PARAM_LIST::deep_lookup(), PARAMETER< T >::e_val(), Expression::eval(), NOT_INPUT, and CARD_LIST::params().
{
  CS cmd(CS::_STRING, _s);
  Expression e(cmd);
  Expression reduced(e, scope);
  T v = T(reduced.eval());
  if (v != NOT_INPUT) {
    return v;
  }else{
    const PARAM_LIST* pl = scope->params();
    return T(pl->deep_lookup(_s).e_val(def, scope));
  }
}
template<class T> PARAMETER< T >::operator T () const [inline]
Definition at line 52 of file u_parameter.h.
References PARAMETER< T >::_v.
{return _v;}
template<class T> void PARAMETER< T >::operator= (const PARAMETER< T > & p) [inline]
Definition at line 67 of file u_parameter.h.
{_v = p._v; _s = p._s;}
template<class T> void PARAMETER< T >::operator= (const T & v) [inline]
Definition at line 68 of file u_parameter.h.
{_v = v; _s = "#";}
template<class T> void PARAMETER< T >::operator= (const std::string & s) [inline]
Definition at line 71 of file u_parameter.h.
{
    if (strchr("'\"{", s[0])) {
      CS cmd(CS::_STRING, s);
      _s = cmd.ctos("", "'\"{", "'\"}");
    }else if (s == "NA") {
      _s = "";
    }else{
      _s = s;
    }
  }
template<class T> bool PARAMETER< T >::operator== (const PARAMETER< T > & p) const [inline]
Definition at line 81 of file u_parameter.h.
{
    return (_v == p._v  &&  _s == p._s);
  }
template<class T> bool PARAMETER< T >::operator== (const T & v) const [inline]
Definition at line 84 of file u_parameter.h.
{
    if (v != NOT_INPUT) {
      return _v == v;
    }else{
      return (_v == NOT_INPUT || !has_hard_value());
    }
  }
template<class T > void PARAMETER< T >::parse (CS & cmd) [inline]
Definition at line 330 of file u_parameter.h.
References CS::ctos(), and CS::match1().
{
  T new_val;
  cmd >> new_val;
  if (cmd) {
    _v = new_val;
    _s = "#";
  }else{
    std::string name;
    //cmd >> name;
    name = cmd.ctos(",=();", "'{\"", "'}\"");
    if (cmd) {
      if (cmd.match1('(')) {
        _s = name + '(' + cmd.ctos("", "(", ")") + ')';
      }else{
        _s = name;
      }
      if (name == "NA") {
        _s = "";
      }else{
      }
    }else{
    }
  }
}
template<class T> T* PARAMETER< T >::pointer_hack () [inline]
Definition at line 97 of file u_parameter.h.
{return &_v;}
template<class T> void PARAMETER< T >::print (OMSTREAM & o) const [inline]
Definition at line 65 of file u_parameter.h.
{o << string();}
template<class T> void PARAMETER< T >::set_default (const T & v) [inline]
Definition at line 66 of file u_parameter.h.
Referenced by set_default().
{_v = v; _s = "";}
template<class T> std::string PARAMETER< T >::string () const [inline]
Definition at line 56 of file u_parameter.h.
Referenced by SDP::l_string(), SDP::p_string(), anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::param_value(), MODEL_CARD::param_value(), COMMON_COMPONENT::param_value(), MODEL_SEMI_BASE::param_value(), MODEL_LOGIC::param_value(), MODEL_SEMI_CAPACITOR::param_value(), MODEL_SEMI_RESISTOR::param_value(), anonymous_namespace{d_switch.cc}::MODEL_SWITCH::param_value(), COMPONENT::param_value(), PARAMETER< bool >::print(), SDP::string(), and SDP::w_string().
{
    if (_s == "#") {
      return to_string(_v);
    }else if (_s == "") {
      return "NA(" + to_string(_v) + ")";
    }else{
      return _s;
    }
  }
Member Data Documentation
template<class T> std::string PARAMETER< T >::_s [private]
Definition at line 40 of file u_parameter.h.
Referenced by PARAMETER< bool >::has_hard_value(), PARAMETER< bool >::lookup_solve(), PARAMETER< bool >::operator=(), PARAMETER< bool >::operator==(), PARAMETER< bool >::parse(), PARAMETER< bool >::set_default(), and PARAMETER< bool >::string().
template<class T> T PARAMETER< T >::_v [mutable, private]
Definition at line 39 of file u_parameter.h.
Referenced by PARAMETER< bool >::has_good_value(), PARAMETER< T >::operator T(), PARAMETER< bool >::operator=(), PARAMETER< bool >::operator==(), PARAMETER< bool >::parse(), PARAMETER< bool >::pointer_hack(), PARAMETER< bool >::set_default(), and PARAMETER< bool >::string().
The documentation for this class was generated from the following file:
savant/gnucap/src/u_parameter.h