gnucap: LOGIC_INV Class Reference
LOGIC_INV Class Reference
#include <d_logic.h>
Public Member Functions
LOGIC_INV (int c=0)
LOGICVAL logic_eval (const node_t *n) const
virtual std::string name () const
Private Member Functions
LOGIC_INV (const LOGIC_INV &p)
COMMON_COMPONENT * clone () const
Detailed Description
Definition at line 260 of file d_logic.h.
Constructor & Destructor Documentation
LOGIC_INV::LOGIC_INV (const LOGIC_INV & p) [inline, explicit, private]
Definition at line 262 of file d_logic.h.
References COMMON_LOGIC::_count.
Referenced by clone().
:COMMON_LOGIC(p){++_count;}
LOGIC_INV::LOGIC_INV (int c = 0) [inline, explicit]
Definition at line 265 of file d_logic.h.
:COMMON_LOGIC(c) {}
Member Function Documentation
COMMON_COMPONENT* LOGIC_INV::clone () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 263 of file d_logic.h.
References LOGIC_INV().
{return new LOGIC_INV(*this);}
LOGICVAL LOGIC_INV::logic_eval (const node_t * n) const [inline, virtual]
Implements COMMON_LOGIC.
Definition at line 266 of file d_logic.h.
References LOGIC_NODE::lv().
{
    return ~n[0]->lv();
  }
virtual std::string LOGIC_INV::name () const [inline, virtual]
Implements COMMON_COMPONENT.
Definition at line 269 of file d_logic.h.
{return "inv";}
The documentation for this class was generated from the following file:
savant/gnucap/src/d_logic.h