gnucap: anonymous_namespace{c_file.cc}::CMD_FILE Class Reference
anonymous_namespace{c_file.cc}::CMD_FILE Class Reference
Public Member Functions
void do_it (CS &cmd, CARD_LIST *)
Detailed Description
Definition at line 105 of file c_file.cc.
Member Function Documentation
void anonymous_namespace{c_file.cc}::CMD_FILE::do_it (CS & cmd, CARD_LIST *) [inline, virtual]
Implements CMD.
Definition at line 107 of file c_file.cc.
References OMSTREAM::attach(), OMSTREAM::detach(), error(), itested, CS::match1(), CS::more(), IO::mstdout, CS::skip(), CS::skipbl(), and xopen().
  {itested();
    static std::list<FILE*> filestack;
    if (cmd.more()) {                   /* a file name .. open it */
      const char* access = "w";
      while (cmd.match1('>')) {
        access = "a";
        cmd.skip();
        cmd.skipbl();
      }
      FILE* newfile = xopen(cmd,"",access);
      if (newfile) {
        filestack.push_back(newfile);
        mout.attach(newfile);
        IO::mstdout.attach(newfile);
      }else{
      }
    }else{                              /* empty command -- close a file */
      if (filestack.empty()) {
        error(bWARNING, "no files open\n");
      }else{
        FILE* oldfile = filestack.back();
        filestack.pop_back();
        mout.detach(oldfile);
        IO::mstdout.detach(oldfile);
        fclose(oldfile);
      }
    }
  }
The documentation for this class was generated from the following file:
savant/gnucap/src/c_file.cc