gnucap: anonymous_namespace{d_switch.cc}::COMMON_SWITCH Class Reference
anonymous_namespace{d_switch.cc}::COMMON_SWITCH Class Reference
Public Member Functions
COMMON_SWITCH (int c=0)
bool operator== (const COMMON_COMPONENT &) const
COMMON_COMPONENT * clone () const
std::string name () const
bool param_is_printable (int) const
std::string param_name (int) const
std::string param_name (int, int) const
std::string param_value (int) const
int param_count () const
Public Attributes
state_t _ic
Private Member Functions
COMMON_SWITCH (const COMMON_SWITCH &p)
Detailed Description
Definition at line 38 of file d_switch.cc.
Constructor & Destructor Documentation
anonymous_namespace{d_switch.cc}::COMMON_SWITCH::COMMON_SWITCH (const COMMON_SWITCH & p) [inline, explicit, private]
Definition at line 40 of file d_switch.cc.
    :COMMON_COMPONENT(p), _ic(p._ic) {}
anonymous_namespace{d_switch.cc}::COMMON_SWITCH::COMMON_SWITCH (int c = 0) [inline, explicit]
Definition at line 43 of file d_switch.cc.
    :COMMON_COMPONENT(c), _ic(_UNKNOWN) {}
Member Function Documentation
COMMON_COMPONENT* anonymous_namespace{d_switch.cc}::COMMON_SWITCH::clone () const [inline, virtual]
Implements COMMON_COMPONENT.
Definition at line 46 of file d_switch.cc.
{return new COMMON_SWITCH(*this);}
std::string anonymous_namespace{d_switch.cc}::COMMON_SWITCH::name () const [inline, virtual]
Implements COMMON_COMPONENT.
Definition at line 47 of file d_switch.cc.
References untested.
{untested(); return "switch";}
bool anonymous_namespace{d_switch.cc}::COMMON_SWITCH::operator== (const COMMON_COMPONENT & x) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 194 of file d_switch.cc.
References COMMON_COMPONENT::operator==(), and anonymous_namespace{c_genrat.cc}::p.
{
  const COMMON_SWITCH* p = dynamic_cast<const COMMON_SWITCH*>(&x);
  return p && COMMON_COMPONENT::operator==(x);
}
int anonymous_namespace{d_switch.cc}::COMMON_SWITCH::param_count () const [inline, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 53 of file d_switch.cc.
References COMMON_COMPONENT::param_count().
{return (1 + COMMON_COMPONENT::param_count());}
bool anonymous_namespace{d_switch.cc}::COMMON_SWITCH::param_is_printable (int i) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 200 of file d_switch.cc.
References anonymous_namespace{d_switch.cc}::_OFF, anonymous_namespace{d_switch.cc}::_ON, and COMMON_COMPONENT::param_is_printable().
{
  switch (COMMON_SWITCH::param_count() - 1 - i) {
  case 0:  return (_ic == _ON || _ic == _OFF);
  default: return COMMON_COMPONENT::param_is_printable(i);
  }
}
std::string anonymous_namespace{d_switch.cc}::COMMON_SWITCH::param_name (int i) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 208 of file d_switch.cc.
References COMMON_COMPONENT::param_name().
{
  switch (COMMON_SWITCH::param_count() - 1 - i) {
  case 0:  return "ic";
  default: return COMMON_COMPONENT::param_name(i);
  }
}
std::string anonymous_namespace{d_switch.cc}::COMMON_SWITCH::param_name (int i, int j) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 216 of file d_switch.cc.
References itested, COMMON_COMPONENT::param_count(), and COMMON_COMPONENT::param_name().
{itested();
  if (j == 0) {itested();
    return param_name(i);
  }else if (i >= COMMON_COMPONENT::param_count()) {itested();
    return "";
  }else{itested();
    return COMMON_COMPONENT::param_name(i, j);
  }
}
std::string anonymous_namespace{d_switch.cc}::COMMON_SWITCH::param_value (int i) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 227 of file d_switch.cc.
References anonymous_namespace{d_switch.cc}::_ON, itested, and COMMON_COMPONENT::param_value().
{itested();
  switch (COMMON_SWITCH::param_count() - 1 - i) {
  case 0:  return (_ic == _ON) ? "1" : "0";
  default: return COMMON_COMPONENT::param_value(i);
  }
}
Member Data Documentation
state_t anonymous_namespace{d_switch.cc}::COMMON_SWITCH::_ic
Definition at line 55 of file d_switch.cc.
Referenced by anonymous_namespace{d_switch.cc}::SWITCH_BASE::precalc_last(), and anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_begin().
The documentation for this class was generated from the following file:
savant/gnucap/src/d_switch.cc