gnucap: anonymous_namespace{lang_spectre.cc} Namespace Reference
anonymous_namespace{lang_spectre.cc} Namespace Reference
Classes
class LANG_SPECTRE
class CMD_MODEL
class CMD_SUBCKT
class CMD_SIMULATOR
class CMD_SPECTRE
Functions
DISPATCHER< LANGUAGE >::INSTALL d & language_dispatcher (),&lang_spectre
static void parse_type (CS &cmd, CARD *x)
static void parse_args (CS &cmd, CARD *x)
static void parse_label (CS &cmd, CARD *x)
static void parse_ports (CS &cmd, COMPONENT *x)
static void print_type (OMSTREAM &o, const COMPONENT *x)
static void print_label (OMSTREAM &o, const COMPONENT *x)
static void print_ports (OMSTREAM &o, const COMPONENT *x)
Variables
anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE lang_spectre
anonymous_namespace{lang_spectre.cc}::CMD_MODEL p1
DISPATCHER< CMD >::INSTALL d1 & command_dispatcher
anonymous_namespace{lang_spectre.cc}::CMD_SUBCKT p2
anonymous_namespace{lang_spectre.cc}::CMD_SIMULATOR p3
anonymous_namespace{lang_spectre.cc}::CMD_SPECTRE p8
Function Documentation
DISPATCHER<LANGUAGE>::INSTALL d& anonymous_namespace{lang_spectre.cc}::language_dispatcher ()
static void anonymous_namespace{lang_spectre.cc}::parse_args (CS & cmd, CARD * x) [static]
Definition at line 73 of file lang_spectre.cc.
References CS::ctos(), CARD::long_label(), CS::more(), CARD::set_param_by_name(), CS::stuck(), untested, and CS::warn().
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_instance(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_instance(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_paramset(), and anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_paramset().
{
  assert(x);
  unsigned here = 0;
  while (cmd.more() && !cmd.stuck(&here)) {
    std::string name  = cmd.ctos("=", "", "");
    cmd >> '=';
    std::string value = cmd.ctos("", "(", ")");
    try{
      x->set_param_by_name(name, value);
    }catch (Exception_No_Match&) {untested();
      cmd.warn(bDANGER, here, x->long_label() + ": bad parameter " + name + " ignored");
    }
  }
}
static void anonymous_namespace{lang_spectre.cc}::parse_label (CS & cmd, CARD * x) [static]
Definition at line 90 of file lang_spectre.cc.
References CKT_BASE::set_label().
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_instance(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_instance(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_instance(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_module(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_module(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_module(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_paramset(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_paramset(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_paramset().
{
  assert(x);
  std::string my_name;
  cmd >> my_name;
  x->set_label(my_name);
}
static void anonymous_namespace{lang_spectre.cc}::parse_ports (CS & cmd, COMPONENT * x) [static]
Definition at line 98 of file lang_spectre.cc.
References CS::cursor(), LANGUAGE::find_type_in_string(), CS::is_alnum(), OPT::language, CS::reset(), COMPONENT::set_port_by_index(), untested, and CS::warn().
Referenced by anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_element_using_obsolete_callback(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_instance(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_instance(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_instance(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_logic_using_obsolete_callback(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_module(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_module(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_module().
{
  assert(x);
  if (cmd >> '(') {
    int index = 0;
    while (cmd.is_alnum()) {
      unsigned here = cmd.cursor();
      try{
        std::string value;
        cmd >> value;
        x->set_port_by_index(index++, value);
      }catch (Exception_Too_Many& e) {untested();
        cmd.warn(bDANGER, here, e.message());
      }
    }
    cmd >> ')';
  }else{
    unsigned here = cmd.cursor();
    OPT::language->find_type_in_string(cmd);
    unsigned stop = cmd.cursor();
    cmd.reset(here);
    int index = 0;
    while (cmd.cursor() < stop) {
      here = cmd.cursor();
      try{
        std::string value;
        cmd >> value;
        x->set_port_by_index(index++, value);
      }catch (Exception_Too_Many& e) {untested();
        cmd.warn(bDANGER, here, e.message());
      }
    }
  }
}
static void anonymous_namespace{lang_spectre.cc}::parse_type (CS & cmd, CARD * x) [static]
Definition at line 65 of file lang_spectre.cc.
References CARD::set_dev_type().
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_instance(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_instance(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_instance(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_paramset(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_paramset(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_paramset().
{
  assert(x);
  std::string new_type;
  cmd >> new_type;
  x->set_dev_type(new_type);
}
static void anonymous_namespace{lang_spectre.cc}::print_label (OMSTREAM & o, const COMPONENT * x) [static]
Definition at line 297 of file lang_spectre.cc.
References CKT_BASE::short_label().
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_instance(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_instance(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_instance().
{
  assert(x);
  o << x->short_label();
}
static void anonymous_namespace{lang_spectre.cc}::print_ports (OMSTREAM & o, const COMPONENT * x) [static]
Definition at line 303 of file lang_spectre.cc.
References COMPONENT::current_port_exists(), COMPONENT::current_port_value(), COMPONENT::port_exists(), and COMPONENT::port_value().
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_instance(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_instance(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_module(), and anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_module().
{
  assert(x);
  o << " (";
  std::string sep = "";
  for (int ii = 0;  x->port_exists(ii);  ++ii) {
    o << sep << x->port_value(ii);
    sep = " ";
  }
  for (int ii = 0;  x->current_port_exists(ii);  ++ii) {
    o << sep << x->current_port_value(ii);
    sep = " ";
  }
  o << ")";
}
static void anonymous_namespace{lang_spectre.cc}::print_type (OMSTREAM & o, const COMPONENT * x) [static]
Definition at line 291 of file lang_spectre.cc.
References CARD::dev_type().
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_instance(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_instance(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_instance().
{
  assert(x);
  o << ' ' << x->dev_type();
}
Variable Documentation
DISPATCHER< CMD >::INSTALL d8 & anonymous_namespace{lang_spectre.cc}::command_dispatcher
Definition at line 393 of file lang_spectre.cc.
anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE anonymous_namespace{lang_spectre.cc}::lang_spectre
Referenced by anonymous_namespace{lang_spectre.cc}::CMD_MODEL::do_it(), and anonymous_namespace{lang_spectre.cc}::CMD_SUBCKT::do_it().
anonymous_namespace{lang_spectre.cc}::CMD_MODEL anonymous_namespace{lang_spectre.cc}::p1
anonymous_namespace{lang_spectre.cc}::CMD_SUBCKT anonymous_namespace{lang_spectre.cc}::p2
anonymous_namespace{lang_spectre.cc}::CMD_SIMULATOR anonymous_namespace{lang_spectre.cc}::p3
anonymous_namespace{lang_spectre.cc}::CMD_SPECTRE anonymous_namespace{lang_spectre.cc}::p8