gnucap: anonymous_namespace{measure_at.cc}::MEASURE Class Reference
anonymous_namespace{measure_at.cc}::MEASURE Class Reference
Public Member Functions
std::string eval (CS &Cmd, const CARD_LIST *Scope) const
Detailed Description
Definition at line 29 of file measure_at.cc.
Member Function Documentation
std::string anonymous_namespace{measure_at.cc}::MEASURE::eval (CS & Cmd, const CARD_LIST * Scope) const [inline, virtual]
Implements FUNCTION.
Definition at line 31 of file measure_at.cc.
References BIGBIG, CS::cursor(), PARAMETER< T >::e_val(), FPOLY1::f0, FPOLY1::f1, Get(), CS::more(), ONE_OF, CS::reset(), CS::stuck(), to_string(), and WAVE::v_out().
  {
    std::string probe_name;
    PARAMETER<double> x;
    bool derivative = false;
    unsigned here = Cmd.cursor();
    Cmd >> probe_name;
    WAVE* w = find_wave(probe_name);
    if (!w) {
      Cmd.reset(here);
    }else{
    }
    here = Cmd.cursor();
    do {
      ONE_OF
        || Get(Cmd, "probe",        &probe_name)
        || Get(Cmd, "x",            &x)
        || Get(Cmd, "at",           &x)
        || Get(Cmd, "deriv{ative}", &derivative)
        ;
    }while (Cmd.more() && !Cmd.stuck(&here));
    if (!w) {
      w = find_wave(probe_name);
    }else{
    }
    if (w) {
      x.e_val(BIGBIG, Scope);
      return to_string((derivative) ? (w->v_out(x).f1) : (w->v_out(x).f0));
    }else{
      throw Exception_No_Match(probe_name);
    }
  }
The documentation for this class was generated from the following file:
savant/gnucap/src/measure_at.cc