gnucap: anonymous_namespace{s_dc.cc}::DCOP Class Reference
anonymous_namespace{s_dc.cc}::DCOP Class Reference
Public Member Functions
void finish ()
Protected Types
enum { DCNEST = 4 }
enum {
ONE_PT, LIN_STEP, LIN_PTS, TIMES,
OCTAVE, DECADE
}
Protected Member Functions
void fix_args (int)
void options (CS &, int)
DCOP ()
~DCOP ()
Protected Attributes
int _n_sweeps
PARAMETER< double > _start [DCNEST]
PARAMETER< double > _stop [DCNEST]
PARAMETER< double > _step_in [DCNEST]
double _step [DCNEST]
bool _linswp [DCNEST]
double * _sweepval [DCNEST]
ELEMENT * _zap [DCNEST]
CARDSTASH _stash [DCNEST]
bool _loop [DCNEST]
bool _reverse_in [DCNEST]
bool _reverse [DCNEST]
bool _cont
TRACE _trace
enum anonymous_namespace{s_dc.cc}::DCOP:: { ... } _stepmode [DCNEST]
Static Protected Attributes
static double temp_c_in = 0.
Private Member Functions
void sweep ()
void sweep_recursive (int)
void first (int)
bool next (int)
DCOP (const DCOP &)
Detailed Description
Definition at line 33 of file s_dc.cc.
Member Enumeration Documentation
anonymous enum [protected]
Enumerator:
DCNEST
Definition at line 50 of file s_dc.cc.
{DCNEST = 4};
anonymous enum [protected]
Enumerator:
ONE_PT
LIN_STEP
LIN_PTS
TIMES
OCTAVE
DECADE
Definition at line 65 of file s_dc.cc.
{ONE_PT, LIN_STEP, LIN_PTS, TIMES, OCTAVE, DECADE} _stepmode[DCNEST];
Constructor & Destructor Documentation
anonymous_namespace{s_dc.cc}::DCOP::DCOP (const DCOP &) [inline, explicit, private]
Definition at line 44 of file s_dc.cc.
References incomplete, and unreachable.
: SIM() {unreachable(); incomplete();}
anonymous_namespace{s_dc.cc}::DCOP::DCOP () [explicit, protected]
Definition at line 117 of file s_dc.cc.
References SIM_DATA::_genout, _linswp, _loop, SIM::_out, _reverse, _reverse_in, CKT_BASE::_sim, _step, _stepmode, _sweepval, SIM_DATA::_uic, _zap, DCNEST, IO::mstdout, ONE_PT, OPT::temp_c, and temp_c_in.
  :SIM(),
   _n_sweeps(1),
   _cont(false),
   _trace(tNONE)
{
  for (int ii = 0; ii < DCNEST; ++ii) {
    _loop[ii] = false;
    _reverse_in[ii] = false;
    _reverse[ii] = false;
    _step[ii]=0.;
    _linswp[ii]=true;
    _sweepval[ii]=&_sim->_genout;
    _zap[ii]=NULL;
    _stepmode[ii] = ONE_PT;
  }
  //BUG// in SIM.  should be initialized there.
  _sim->_genout=0.;
  temp_c_in=OPT::temp_c;
  _out=IO::mstdout;
  _sim->_uic=false;
}
anonymous_namespace{s_dc.cc}::DCOP::~DCOP () [inline, protected]
Definition at line 47 of file s_dc.cc.
{}
Member Function Documentation
void anonymous_namespace{s_dc.cc}::DCOP::finish (void) [virtual]
Reimplemented from SIM.
Definition at line 141 of file s_dc.cc.
References _n_sweeps, _stash, _zap, CKT_BASE::dec_probes(), exists(), COMPONENT::precalc_first(), ELEMENT::precalc_last(), and CARDSTASH::restore().
{
  for (int ii = 0;  ii < _n_sweeps;  ++ii) {
    if (exists(_zap[ii])) { // component
      _stash[ii].restore();
      _zap[ii]->dec_probes();
      _zap[ii]->precalc_first();
      _zap[ii]->precalc_last();
    }else{
    }
  }
}
void anonymous_namespace{s_dc.cc}::DCOP::first (int Nest) [private]
Definition at line 386 of file s_dc.cc.
References SIM_DATA::_phase, _reverse, _reverse_in, CKT_BASE::_sim, _start, _sweepval, DCNEST, itested, next(), and p_INIT_DC.
Referenced by sweep_recursive().
{
  assert(Nest >= 0);
  assert(Nest < DCNEST);
  assert(_start);
  assert(_sweepval);
  assert(_sweepval[Nest]);
  *_sweepval[Nest] = _start[Nest];
  _reverse[Nest] = false;
  if (_reverse_in[Nest]) {itested();
    while (next(Nest)) {itested();
      /* nothing */;
    }
    _reverse[Nest] = true;
    next(Nest);
  }else{
  }
  _sim->_phase = p_INIT_DC;
}
void anonymous_namespace{s_dc.cc}::DCOP::fix_args (int Nest) [protected]
Definition at line 254 of file s_dc.cc.
References _linswp, SIM::_scope, _start, _step, _step_in, _stepmode, _stop, DECADE, PARAMETER< T >::e_val(), LIN_PTS, LIN_STEP, OCTAVE, ONE_PT, TIMES, and untested.
Referenced by anonymous_namespace{s_dc.cc}::DC::setup(), and anonymous_namespace{s_dc.cc}::OP::setup().
{
  _stop[Nest].e_val(_start[Nest], _scope);
  _step_in[Nest].e_val(0., _scope);
  _step[Nest] = _step_in[Nest];
  switch (_stepmode[Nest]) {
  case ONE_PT:
  case LIN_STEP:
    _linswp[Nest] = true;
    break;
  case LIN_PTS:untested();
    if (_step[Nest] <= 2.) {untested();
      _step[Nest] = 2.;
    }else{untested();
    }
    _linswp[Nest] = true;
    break;
  case TIMES:untested();
    if (_step[Nest] == 0.  &&  _start[Nest] != 0.) {untested();
      _step[Nest] = _stop[Nest] / _start[Nest];
    }else{untested();
    }
    _linswp[Nest] = false;
    break;
  case OCTAVE:
    if (_step[Nest] == 0.) {untested();
      _step[Nest] = 1.;
    }else{
    }
    _step[Nest] = pow(2.00000001, 1./_step[Nest]);
    _linswp[Nest] = false;
    break;
  case DECADE:
    if (_step[Nest] == 0.) {
      _step[Nest] = 1.;
    }else{
    }
    _step[Nest] = pow(10., 1./_step[Nest]);
    _linswp[Nest] = false;
    break;
  };
  if (_step[Nest] == 0.) {      // prohibit log sweep from 0
    _step[Nest] = _stop[Nest] - _start[Nest];
    _linswp[Nest] = true;
  }else{
  }
}
bool anonymous_namespace{s_dc.cc}::DCOP::next (int Nest) [private]
Definition at line 407 of file s_dc.cc.
References _linswp, _loop, SIM_DATA::_phase, _reverse, CKT_BASE::_sim, _start, _step, _stop, _sweepval, fixzero(), in_order(), p_DC_SWEEP, and untested.
Referenced by first(), and sweep_recursive().
{
  bool ok = false;
  if (_linswp[Nest]) {
    double fudge = _step[Nest] / 10.;
    if (_step[Nest] == 0.) {
      ok = false;
    }else{
      if (!_reverse[Nest]) {
        *(_sweepval[Nest]) += _step[Nest];
        fixzero(_sweepval[Nest], _step[Nest]);
        ok=in_order(_start[Nest]-fudge,*(_sweepval[Nest]),_stop[Nest]+fudge);
        if (!ok  &&  _loop[Nest]) {
          _reverse[Nest] = true;
        }else{
        }
      }else{
      }
      if (_reverse[Nest]) {
        *(_sweepval[Nest]) -= _step[Nest];
        fixzero(_sweepval[Nest], _step[Nest]);
        ok=in_order(_start[Nest]-fudge,*(_sweepval[Nest]),_stop[Nest]+fudge);
      }else{
      }
    }
  }else{
    double fudge = pow(_step[Nest], .1);
    if (_step[Nest] == 1.) {untested();
      ok = false;
    }else{
      if (!_reverse[Nest]) {
        *(_sweepval[Nest]) *= _step[Nest];
        ok=in_order(_start[Nest]/fudge,*(_sweepval[Nest]),_stop[Nest]*fudge);
        if (!ok  &&  _loop[Nest]) {untested();
          _reverse[Nest] = true;
        }else{
        }
      }else{
      }
      if (_reverse[Nest]) {untested();
        *(_sweepval[Nest]) /= _step[Nest];
        ok=in_order(_start[Nest]/fudge,*(_sweepval[Nest]),_stop[Nest]*fudge);
      }else{
      }
    }
  }
  _sim->_phase = p_DC_SWEEP;
  return ok;
}
void anonymous_namespace{s_dc.cc}::DCOP::options (CS & Cmd, int Nest) [protected]
Definition at line 304 of file s_dc.cc.
References _cont, _loop, SIM::_out, _reverse_in, CKT_BASE::_sim, _step_in, _stepmode, _trace, SIM_DATA::_uic, CS::cursor(), DECADE, Get(), CS::is_float(), LIN_PTS, LIN_STEP, CS::match1(), mOFFSET, CS::more(), OCTAVE, ONE_OF, outset(), Set(), CS::stuck(), OPT::temp_c, temp_c_in, TIMES, SIM::tITERATION, SIM::tNONE, SIM::tUNDER, SIM::tVERBOSE, CS::umatch(), and CS::warn().
Referenced by anonymous_namespace{s_dc.cc}::DC::setup(), and anonymous_namespace{s_dc.cc}::OP::setup().
{
  _sim->_uic = _loop[Nest] = _reverse_in[Nest] = false;
  unsigned here = Cmd.cursor();
  do{
    ONE_OF
      || (Cmd.match1("'\"({")   && ((Cmd >> _step_in[Nest]), (_stepmode[Nest] = LIN_STEP)))
      || (Cmd.is_float()        && ((Cmd >> _step_in[Nest]), (_stepmode[Nest] = LIN_STEP)))
      || (Get(Cmd, "*",           &_step_in[Nest]) && (_stepmode[Nest] = TIMES))
      || (Get(Cmd, "+",           &_step_in[Nest]) && (_stepmode[Nest] = LIN_STEP))
      || (Get(Cmd, "by",          &_step_in[Nest]) && (_stepmode[Nest] = LIN_STEP))
      || (Get(Cmd, "step",        &_step_in[Nest]) && (_stepmode[Nest] = LIN_STEP))
      || (Get(Cmd, "d{ecade}",    &_step_in[Nest]) && (_stepmode[Nest] = DECADE))
      || (Get(Cmd, "ti{mes}",     &_step_in[Nest]) && (_stepmode[Nest] = TIMES))
      || (Get(Cmd, "lin",         &_step_in[Nest]) && (_stepmode[Nest] = LIN_PTS))
      || (Get(Cmd, "o{ctave}",    &_step_in[Nest]) && (_stepmode[Nest] = OCTAVE))
      || Get(Cmd, "c{ontinue}",   &_cont)
      || Get(Cmd, "dt{emp}",      &temp_c_in,   mOFFSET, OPT::temp_c)
      || Get(Cmd, "lo{op}",       &_loop[Nest])
      || Get(Cmd, "re{verse}",    &_reverse_in[Nest])
      || Get(Cmd, "te{mperature}",&temp_c_in)
      || (Cmd.umatch("tr{ace} {=}") &&
          (ONE_OF
           || Set(Cmd, "n{one}",      &_trace, tNONE)
           || Set(Cmd, "o{ff}",       &_trace, tNONE)
           || Set(Cmd, "w{arnings}",  &_trace, tUNDER)
           || Set(Cmd, "i{terations}",&_trace, tITERATION)
           || Set(Cmd, "v{erbose}",   &_trace, tVERBOSE)
           || Cmd.warn(bWARNING,
                       "need none, off, warnings, iterations, verbose")
           )
          )
      || outset(Cmd,&_out)
      ;
  }while (Cmd.more() && !Cmd.stuck(&here));
}
void anonymous_namespace{s_dc.cc}::DCOP::sweep () [private, virtual]
Implements SIM.
Definition at line 341 of file s_dc.cc.
References SIM_DATA::_bypass_ok, _cont, _n_sweeps, CKT_BASE::_sim, _start, _stop, CARD_LIST::card_list, SIM_DATA::clear_limit(), SIM::head(), SIM_DATA::restore_voltages(), SIM_DATA::set_inc_mode_bad(), sweep_recursive(), CARD_LIST::tr_begin(), and untested.
{
  head(_start[0], _stop[0], " ");
  _sim->_bypass_ok = false;
  _sim->set_inc_mode_bad();
  if (_cont) {untested();
    _sim->restore_voltages();
  }else{
  }
  _sim->clear_limit();
  CARD_LIST::card_list.tr_begin();
  sweep_recursive(_n_sweeps);
}
void anonymous_namespace{s_dc.cc}::DCOP::sweep_recursive (int Nest) [private]
Definition at line 356 of file s_dc.cc.
References CKT_BASE::_sim, _sweepval, SIM_DATA::_temp_c, _trace, CARD_LIST::card_list, converged, OPT::DCBIAS, DCNEST, OPT::DCXFER, error(), first(), itested, SIM_DATA::keep_voltages(), next(), SIM::outdata(), SIM_DATA::set_limit(), SIM::solve_with_homotopy(), CKT_BASE::status(), temp_c_in, and CARD_LIST::tr_accept().
Referenced by sweep().
{
  --Nest;
  assert(Nest >= 0);
  assert(Nest < DCNEST);
  OPT::ITL itl = OPT::DCBIAS;
  first(Nest);
  do {
    _sim->_temp_c = temp_c_in;
    if (Nest == 0) {
      int converged = solve_with_homotopy(itl,_trace);
      if (!converged) {itested();
        error(bWARNING, "did not converge\n");
      }else{
      }
      ::status.accept.start();
      _sim->set_limit();
      CARD_LIST::card_list.tr_accept();
      ::status.accept.stop();
      _sim->keep_voltages();
      outdata(*_sweepval[Nest]);
      itl = OPT::DCXFER;
    }else{
      sweep_recursive(Nest);
    }
  } while (next(Nest));
}
Member Data Documentation
bool anonymous_namespace{s_dc.cc}::DCOP::_cont [protected]
Definition at line 63 of file s_dc.cc.
Referenced by options(), anonymous_namespace{s_dc.cc}::DC::setup(), anonymous_namespace{s_dc.cc}::OP::setup(), and sweep().
bool anonymous_namespace{s_dc.cc}::DCOP::_linswp[DCNEST] [protected]
Definition at line 56 of file s_dc.cc.
Referenced by DCOP(), fix_args(), and next().
bool anonymous_namespace{s_dc.cc}::DCOP::_loop[DCNEST] [protected]
Definition at line 60 of file s_dc.cc.
Referenced by DCOP(), next(), and options().
int anonymous_namespace{s_dc.cc}::DCOP::_n_sweeps [protected]
Definition at line 51 of file s_dc.cc.
Referenced by finish(), anonymous_namespace{s_dc.cc}::DC::setup(), anonymous_namespace{s_dc.cc}::OP::setup(), and sweep().
bool anonymous_namespace{s_dc.cc}::DCOP::_reverse[DCNEST] [protected]
Definition at line 62 of file s_dc.cc.
Referenced by DCOP(), first(), and next().
bool anonymous_namespace{s_dc.cc}::DCOP::_reverse_in[DCNEST] [protected]
Definition at line 61 of file s_dc.cc.
Referenced by DCOP(), first(), and options().
PARAMETER<double> anonymous_namespace{s_dc.cc}::DCOP::_start[DCNEST] [protected]
Definition at line 52 of file s_dc.cc.
Referenced by first(), fix_args(), next(), anonymous_namespace{s_dc.cc}::DC::setup(), anonymous_namespace{s_dc.cc}::OP::setup(), and sweep().
CARDSTASH anonymous_namespace{s_dc.cc}::DCOP::_stash[DCNEST] [protected]
Definition at line 59 of file s_dc.cc.
Referenced by finish(), and anonymous_namespace{s_dc.cc}::DC::setup().
double anonymous_namespace{s_dc.cc}::DCOP::_step[DCNEST] [protected]
Definition at line 55 of file s_dc.cc.
Referenced by DCOP(), fix_args(), next(), anonymous_namespace{s_dc.cc}::DC::setup(), and anonymous_namespace{s_dc.cc}::OP::setup().
PARAMETER<double> anonymous_namespace{s_dc.cc}::DCOP::_step_in[DCNEST] [protected]
Definition at line 54 of file s_dc.cc.
Referenced by fix_args(), and options().
enum { ... } anonymous_namespace{s_dc.cc}::DCOP::_stepmode[DCNEST] [protected]
Referenced by DCOP(), fix_args(), and options().
PARAMETER<double> anonymous_namespace{s_dc.cc}::DCOP::_stop[DCNEST] [protected]
Definition at line 53 of file s_dc.cc.
Referenced by fix_args(), next(), anonymous_namespace{s_dc.cc}::DC::setup(), anonymous_namespace{s_dc.cc}::OP::setup(), and sweep().
double* anonymous_namespace{s_dc.cc}::DCOP::_sweepval[DCNEST] [protected]
Definition at line 57 of file s_dc.cc.
Referenced by DCOP(), first(), next(), anonymous_namespace{s_dc.cc}::DC::setup(), anonymous_namespace{s_dc.cc}::OP::setup(), and sweep_recursive().
TRACE anonymous_namespace{s_dc.cc}::DCOP::_trace [protected]
Definition at line 64 of file s_dc.cc.
Referenced by options(), anonymous_namespace{s_dc.cc}::DC::setup(), anonymous_namespace{s_dc.cc}::OP::setup(), and sweep_recursive().
ELEMENT* anonymous_namespace{s_dc.cc}::DCOP::_zap[DCNEST] [protected]
Definition at line 58 of file s_dc.cc.
Referenced by DCOP(), finish(), anonymous_namespace{s_dc.cc}::DC::setup(), and anonymous_namespace{s_dc.cc}::OP::setup().
double anonymous_namespace{s_dc.cc}::DCOP::temp_c_in = 0. [static, protected]
Definition at line 66 of file s_dc.cc.
Referenced by DCOP(), options(), anonymous_namespace{s_dc.cc}::DC::setup(), anonymous_namespace{s_dc.cc}::OP::setup(), and sweep_recursive().
The documentation for this class was generated from the following file:
savant/gnucap/src/s_dc.cc