gnucap: anonymous_namespace{lang_geda.cc}::LANG_GSCHEM Class Reference
anonymous_namespace{lang_geda.cc}::LANG_GSCHEM Class Reference
Public Types
enum MODE { mDEFAULT, mPARAMSET }
enum { INACTIVE = -1 }
Public Member Functions
std::string name () const
bool case_insensitive () const
UNITS units () const
std::string arg_front () const
std::string arg_mid () const
std::string arg_back () const
void parse_top_item (CS &, CARD_LIST *)
DEV_COMMENT * parse_comment (CS &, DEV_COMMENT *)
DEV_DOT * parse_command (CS &, DEV_DOT *)
MODEL_CARD * parse_paramset (CS &, MODEL_CARD *)
MODEL_SUBCKT * parse_module (CS &, MODEL_SUBCKT *)
COMPONENT * parse_instance (CS &, COMPONENT *)
std::string find_type_in_string (CS &)
MODEL_SUBCKT * parse_componmod (CS &, MODEL_SUBCKT *)
Public Attributes
enum anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::MODE _mode
int arg_count
Private Member Functions
void print_paramset (OMSTREAM &, const MODEL_CARD *)
void print_module (OMSTREAM &, const MODEL_SUBCKT *)
void print_instance (OMSTREAM &, const COMPONENT *)
void print_comment (OMSTREAM &, const DEV_COMMENT *)
void print_command (OMSTREAM &o, const DEV_DOT *c)
void print_args (OMSTREAM &, const MODEL_CARD *)
void print_args (OMSTREAM &, const COMPONENT *)
Detailed Description
Definition at line 40 of file lang_geda.cc.
Member Enumeration Documentation
anonymous enum
Enumerator:
INACTIVE
Definition at line 46 of file lang_geda.cc.
{INACTIVE = -1};
enum anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::MODE
Enumerator:
mDEFAULT
mPARAMSET
Definition at line 44 of file lang_geda.cc.
{mDEFAULT, mPARAMSET} _mode;
Member Function Documentation
std::string anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::arg_back () const [inline, virtual]
Implements LANGUAGE.
Definition at line 59 of file lang_geda.cc.
{
        return "";  //arbitrary
    }
std::string anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::arg_front () const [inline, virtual]
Implements LANGUAGE.
Definition at line 53 of file lang_geda.cc.
{
        return " "; //arbitrary
    }
std::string anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::arg_mid () const [inline, virtual]
Implements LANGUAGE.
Definition at line 56 of file lang_geda.cc.
{
        return "="; //arbitrary
    }
bool anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::case_insensitive () const [inline, virtual]
Implements LANGUAGE.
Definition at line 49 of file lang_geda.cc.
{return false;}
std::string anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::find_type_in_string (CS & cmd) [virtual]
Implements LANGUAGE.
Definition at line 526 of file lang_geda.cc.
References CS::cursor(), and CS::reset().
Referenced by anonymous_namespace{lang_geda.cc}::parse_component(), anonymous_namespace{lang_geda.cc}::parse_net(), and anonymous_namespace{lang_geda.cc}::parse_type().
{
    unsigned here = cmd.cursor(); //store cursor position to reset back later
    std::string type;   //stores type : should check device attribute..
    //graphical=["v","L","G","B","V","A","H","T"]
    if (cmd >> "v " || cmd >> "L " || cmd >> "G " || cmd >> "B " || cmd >>"V "
        || cmd >> "A " || cmd >> "H " || cmd >> "T "){ type="dev_comment";}
    else if (cmd >> "N "){ type="net";}
    else if (cmd >> "U "){ type="bus";}
    else if (cmd >> "P "){ type="pin";}
    else if (cmd >> "C "){ type="C";}
    else if (cmd >> "place "){ type="place";}
    else {  cmd >> type; } //Not matched with the type. What now?
    cmd.reset(here);//Reset cursor back to the position that
                    //has been started with at beginning
    return type;    // returns the type of the string
}
std::string anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::name () const [inline, virtual]
Implements LANGUAGE.
Definition at line 48 of file lang_geda.cc.
{return "gschem";}
DEV_DOT * anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::parse_command (CS & cmd, DEV_DOT * x) [virtual]
Implements LANGUAGE.
Definition at line 438 of file lang_geda.cc.
References CARD_LIST::card_list, CMD::cmdproc(), CS::fullstring(), CARD::owner(), CS::reset(), DEV_DOT::set(), and CARD::subckt().
{
    assert(x);
    x->set(cmd.fullstring());
    CARD_LIST* scope = (x->owner()) ? x->owner()->subckt() : &CARD_LIST::card_list;
    cmd.reset();
    CMD::cmdproc(cmd, scope);
    delete x;
    return NULL;
}
DEV_COMMENT * anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::parse_comment (CS & cmd, DEV_COMMENT * x) [virtual]
Implements LANGUAGE.
Definition at line 431 of file lang_geda.cc.
References CS::fullstring(), and DEV_COMMENT::set().
{
    assert(x);
    x->set(cmd.fullstring());
    return x;
}
MODEL_SUBCKT * anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::parse_componmod (CS & cmd, MODEL_SUBCKT * x)
Definition at line 462 of file lang_geda.cc.
References CS::cursor(), anonymous_namespace{lang_geda.cc}::parse_symbol_file(), CS::reset(), and CKT_BASE::set_label().
Referenced by anonymous_namespace{lang_geda.cc}::CMD_C::do_it().
{
    assert(x);
    cmd.reset();
    std::string type = find_type_in_string(cmd);
    assert(type=="C");
    std::string component_x, component_y, mirror, angle, dump,basename;
    bool isgraphical=false;
    cmd>>"C";
    unsigned here=cmd.cursor();
    cmd>>component_x>>" ">>component_y>>" ">>dump>>" ">>angle>>" ">>mirror>>" ">>basename;
    //open the basename to get the ports and their placements
    //parse_ports(newcmd,x);
    x->set_label("!_"+basename);
    parse_symbol_file(x,basename);
    if (isgraphical==true) {
        return NULL;
    }
    else{
        cmd.reset(here);
    }
    /*type = "graphical";
    x->set_dev_type(type);
    std::cout<<x->dev_type()<<" is the dev type\n";
    */
    return x;
}
COMPONENT * anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::parse_instance (CS & cmd, COMPONENT * x) [virtual]
Implements LANGUAGE.
Definition at line 491 of file lang_geda.cc.
References CS::check(), CARD::dev_type(), anonymous_namespace{lang_geda.cc}::parse_component(), anonymous_namespace{lang_geda.cc}::parse_net(), anonymous_namespace{lang_geda.cc}::parse_place(), anonymous_namespace{lang_geda.cc}::parse_type(), and CS::reset().
{
    cmd.reset();
    parse_type(cmd, x); //parse type will parse the component type and set_dev_type
    if (x->dev_type()=="net") {
    parse_net(cmd,x);
    }else if(x->dev_type()=="place"){
    parse_place(cmd,x);
    }else {
    parse_component(cmd,x);
    }
    cmd.check(bWARNING, "what's ins this?");
    return x;
}
MODEL_SUBCKT * anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::parse_module (CS & cmd, MODEL_SUBCKT * x) [virtual]
Implements LANGUAGE.
Definition at line 456 of file lang_geda.cc.
{
  //To parse heirarchical schematics
  return NULL;
}
MODEL_CARD * anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::parse_paramset (CS & cmd, MODEL_CARD * x) [virtual]
Implements LANGUAGE.
Definition at line 450 of file lang_geda.cc.
{
    assert(x);
    return NULL;
}
void anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::parse_top_item (CS & cmd, CARD_LIST * Scope) [virtual]
Reimplemented from LANGUAGE.
Definition at line 548 of file lang_geda.cc.
References CS::get_line().
{
    cmd.get_line("gnucap-gschem>");
    new__instance(cmd, NULL, Scope);
}
void anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::print_args (OMSTREAM & o, const MODEL_CARD * x) [private]
Definition at line 555 of file lang_geda.cc.
References MODEL_CARD::param_count(), MODEL_CARD::param_is_printable(), MODEL_CARD::param_name(), MODEL_CARD::param_value(), CARD::print_args_obsolete_callback(), and CARD::use_obsolete_callback_print().
{
  assert(x);
  if (x->use_obsolete_callback_print()) {
    x->print_args_obsolete_callback(o, this);  //BUG//callback//
  }else{
    for (int ii = x->param_count() - 1;  ii >= 0;  --ii) {
      if (x->param_is_printable(ii)) {
        std::string arg = " ." + x->param_name(ii) + "=" + x->param_value(ii) + ";";
        o << arg;
      }else{
      }
    }
  }
}
void anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::print_args (OMSTREAM & o, const COMPONENT * x) [private]
Definition at line 571 of file lang_geda.cc.
References COMPONENT::param_count(), COMPONENT::param_is_printable(), COMPONENT::param_name(), COMPONENT::param_value(), COMPONENT::print_args_obsolete_callback(), and COMPONENT::use_obsolete_callback_print().
{
  assert(x);
  o << " #(";
  if (x->use_obsolete_callback_print()) {
    arg_count = 0;
    x->print_args_obsolete_callback(o, this);  //BUG//callback//
    arg_count = INACTIVE;
  }else{
    std::string sep = ".";
    for (int ii = x->param_count() - 1;  ii >= 0;  --ii) {
      if (x->param_is_printable(ii)) {
        o << sep << x->param_name(ii) << "(" << x->param_value(ii) << ")";
        sep = ",.";
      }else{
      }
    }
  }
  o << ") ";
}
void anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::print_command (OMSTREAM & o, const DEV_DOT * c) [private, virtual]
Implements LANGUAGE.
Definition at line 688 of file lang_geda.cc.
References DEV_DOT::s().
{
  assert(x);
  o << x->s() << '\n';
}
void anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::print_comment (OMSTREAM & o, const DEV_COMMENT * x) [private, virtual]
Implements LANGUAGE.
Definition at line 682 of file lang_geda.cc.
References DEV_COMMENT::comment().
{
  assert(x);
  o << x->comment() << '\n';
}
void anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::print_instance (OMSTREAM & o, const COMPONENT * x) [private, virtual]
Implements LANGUAGE.
Definition at line 673 of file lang_geda.cc.
References anonymous_namespace{lang_geda.cc}::print_label(), anonymous_namespace{lang_geda.cc}::print_ports_long(), and anonymous_namespace{lang_geda.cc}::print_type().
{
  print_type(o, x);
  print_args(o, x);
  print_label(o, x);
  print_ports_long(o, x);
  o << ";\n";
}
void anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::print_module (OMSTREAM & o, const MODEL_SUBCKT * x) [private, virtual]
Implements LANGUAGE.
Definition at line 652 of file lang_geda.cc.
References CARD_LIST::begin(), CARD_LIST::end(), anonymous_namespace{lang_geda.cc}::print_ports_short(), CKT_BASE::short_label(), and CARD::subckt().
{
  assert(x);
  //o<<x->short_label();
  //o<<"\n";
  assert(x->subckt());
  if(x->short_label().find("!_")!=std::string::npos){
    return;
  }
  o << "module " <<  x->short_label();
  print_ports_short(o, x);
  o << ";\n";
  for (CARD_LIST::const_iterator
         ci = x->subckt()->begin(); ci != x->subckt()->end(); ++ci) {
    print_item(o, *ci);
  }
  o << "endmodule // " << x->short_label() << "\n\n";
}
void anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::print_paramset (OMSTREAM & o, const MODEL_CARD * x) [private, virtual]
Implements LANGUAGE.
Definition at line 641 of file lang_geda.cc.
References CARD::dev_type(), and CKT_BASE::short_label().
{
  assert(x);
  _mode = mPARAMSET;
  o << "paramset " << x->short_label() << ' ' << x->dev_type() << ";\\\n";
  print_args(o, x);
  o << "\\\n"
    "endparmset\n\n";
  _mode = mDEFAULT;
}
UNITS anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::units () const [inline, virtual]
Implements LANGUAGE.
Definition at line 50 of file lang_geda.cc.
References uSI.
{return uSI;}
Member Data Documentation
enum anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::MODE anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::_mode
int anonymous_namespace{lang_geda.cc}::LANG_GSCHEM::arg_count [mutable]
Definition at line 45 of file lang_geda.cc.
The documentation for this class was generated from the following file:
savant/gnucap/src/lang_geda.cc