gnucap: anonymous_namespace{c_measure.cc}::CMD_MEASURE Class Reference
anonymous_namespace{c_measure.cc}::CMD_MEASURE Class Reference
Public Member Functions
void do_it (CS &Cmd, CARD_LIST *Scope)
Detailed Description
Definition at line 32 of file c_measure.cc.
Member Function Documentation
void anonymous_namespace{c_measure.cc}::CMD_MEASURE::do_it (CS & Cmd, CARD_LIST * Scope) [inline, virtual]
Implements CMD.
Definition at line 34 of file c_measure.cc.
References measure_dispatcher, IO::mstdout, outset(), CARD_LIST::params(), PARAM_LIST::set(), CS::skip1b(), and CS::warn().
  {
    std::string assign_to, function;
    Cmd >> assign_to >> '=' >> function >> '(';
    if (FUNCTION* f = measure_dispatcher[function]) {
      std::string value = f->eval(Cmd, Scope);
      if (!Cmd.skip1b(')')) {
        Cmd.warn(bWARNING, "need )");
      }else{
      }
      OMSTREAM out = IO::mstdout;
      outset(Cmd, &out);
      out << assign_to << '=' << value << '\n';
      PARAM_LIST* pl = Scope->params();
      pl->set(assign_to, value);
    }else{
      throw Exception_No_Match(function);
    }
  }
The documentation for this class was generated from the following file:
savant/gnucap/src/c_measure.cc