gnucap: savant/gnucap/src/u_parameter.h File Reference
savant/gnucap/src/u_parameter.h File Reference
#include "globals.h"
#include "m_expression.h"
#include "u_opt.h"
#include "e_cardlist.h"
Classes
class PARAMETER< T >
class PARAM_LIST
Functions
template<class T >
bool has_hard_value (const PARAMETER< T > &p)
template<class T >
bool has_good_value (const PARAMETER< T > &p)
template<class T >
bool has_nz_value (const T &p)
template<class T >
void set_default (PARAMETER< T > *p, const T &v)
template<class T >
void set_default (T *p, const T &v)
template<class T >
void e_val (PARAMETER< T > *p, const PARAMETER< T > &def, const CARD_LIST *scope)
template<class T >
void e_val (PARAMETER< T > *p, const T &def, const CARD_LIST *scope)
INTERFACE bool Get (CS &cmd, const std::string &key, PARAMETER< bool > *val)
INTERFACE bool Get (CS &cmd, const std::string &key, PARAMETER< int > *val)
template<class T >
OMSTREAM & operator<< (OMSTREAM &o, const PARAMETER< T > p)
Function Documentation
template<class T > void e_val (PARAMETER< T > * p, const PARAMETER< T > & def, const CARD_LIST * scope)
Definition at line 167 of file u_parameter.h.
References PARAMETER< T >::e_val().
Referenced by COMMON_BUILT_IN_MOS::precalc_first(), MODEL_BUILT_IN_MOS123::precalc_first(), MODEL_BUILT_IN_MOS6::precalc_first(), MODEL_BUILT_IN_MOS1::precalc_first(), MODEL_BUILT_IN_MOS3::precalc_first(), MODEL_BUILT_IN_DIODE::precalc_first(), MODEL_BUILT_IN_MOS2::precalc_first(), MODEL_BUILT_IN_MOS_BASE::precalc_first(), MODEL_BUILT_IN_BJT::precalc_first(), MODEL_BUILT_IN_MOS4::precalc_first(), MODEL_BUILT_IN_MOS5::precalc_first(), COMMON_BUILT_IN_DIODE::precalc_first(), MODEL_BUILT_IN_MOS7::precalc_first(), COMMON_BUILT_IN_BJT::precalc_first(), MODEL_BUILT_IN_MOS8::precalc_first(), COMMON_BUILT_IN_MOS::precalc_last(), COMMON_BUILT_IN_DIODE::precalc_last(), COMMON_BUILT_IN_BJT::precalc_last(), and MODEL_SPICE::set_param_by_name().
{
  assert(p);
  p->e_val(def, scope);
}
template<class T > void e_val (PARAMETER< T > * p, const T & def, const CARD_LIST * scope)
Definition at line 174 of file u_parameter.h.
References PARAMETER< T >::e_val().
{
  assert(p);
  p->e_val(def, scope);
}
INTERFACE bool Get (CS & cmd, const std::string & key, PARAMETER< bool > * val)
Definition at line 153 of file u_parameter.cc.
References CS::skip1b(), and CS::umatch().
{
  if (cmd.umatch(key + ' ')) {
    if (cmd.skip1b('=')) {
      cmd >> *val;
    }else{
      *val = true;
    }
    return true;
  }else if (cmd.umatch("no" + key)) {
    *val = false;
    return true;
  }else{
    return false;
  }
}
INTERFACE bool Get (CS & cmd, const std::string & key, PARAMETER< int > * val)
Definition at line 170 of file u_parameter.cc.
References CS::ctof(), and CS::umatch().
{
  if (cmd.umatch(key + " {=}")) {
    *val = int(cmd.ctof());
    return true;
  }else{
    return false;
  }
}
template<class T > bool has_good_value (const PARAMETER< T > & p)
Definition at line 133 of file u_parameter.h.
References PARAMETER< T >::has_good_value().
Referenced by DEV_BUILT_IN_BJT::do_tr(), has_nz_value(), MODEL_BUILT_IN_DIODE::param_is_printable(), MODEL_BUILT_IN_MOS_BASE::param_is_printable(), COMMON_BUILT_IN_DIODE::param_is_printable(), MODEL_BUILT_IN_MOS3::precalc_first(), MODEL_BUILT_IN_MOS2::precalc_first(), COMMON_BUILT_IN_DIODE::precalc_last(), and EVAL_BUILT_IN_DIODE_Yj::tr_eval().
{
  return p.has_good_value();
}
template<class T > bool has_hard_value (const PARAMETER< T > & p)
Definition at line 116 of file u_parameter.h.
References PARAMETER< T >::has_hard_value().
Referenced by SDP_BUILT_IN_MOS_BASE::init(), COMMON_BUILT_IN_MOS::param_is_printable(), MODEL_BUILT_IN_MOS123::param_is_printable(), MODEL_BUILT_IN_MOS_BASE::param_is_printable(), MODEL_BUILT_IN_MOS123::precalc_first(), MODEL_BUILT_IN_MOS_BASE::precalc_first(), MODEL_BUILT_IN_BJT::precalc_first(), and TDP_BUILT_IN_BJT::TDP_BUILT_IN_BJT().
{
  return p.has_hard_value();
}
template<class T > bool has_nz_value (const T & p)
Definition at line 147 of file u_parameter.h.
References has_good_value().
Referenced by MODEL_BUILT_IN_BJT::precalc_first(), and MODEL_BUILT_IN_BJT::tr_eval().
{
  return (has_good_value(p) && p != 0);
}
template<class T > OMSTREAM& operator<< (OMSTREAM & o, const PARAMETER< T > p) [inline]
Definition at line 361 of file u_parameter.h.
{
  p.print(o);
  return o;
}
template<class T > void set_default (PARAMETER< T > * p, const T & v)
Definition at line 153 of file u_parameter.h.
References PARAMETER< T >::set_default().
Referenced by MODEL_BUILT_IN_BJT::MODEL_BUILT_IN_BJT(), MODEL_BUILT_IN_DIODE::MODEL_BUILT_IN_DIODE(), MODEL_BUILT_IN_MOS1::MODEL_BUILT_IN_MOS1(), MODEL_BUILT_IN_MOS123::MODEL_BUILT_IN_MOS123(), MODEL_BUILT_IN_MOS2::MODEL_BUILT_IN_MOS2(), MODEL_BUILT_IN_MOS3::MODEL_BUILT_IN_MOS3(), MODEL_BUILT_IN_MOS4::MODEL_BUILT_IN_MOS4(), MODEL_BUILT_IN_MOS5::MODEL_BUILT_IN_MOS5(), MODEL_BUILT_IN_MOS6::MODEL_BUILT_IN_MOS6(), MODEL_BUILT_IN_MOS7::MODEL_BUILT_IN_MOS7(), MODEL_BUILT_IN_MOS8::MODEL_BUILT_IN_MOS8(), MODEL_BUILT_IN_MOS_BASE::MODEL_BUILT_IN_MOS_BASE(), and MODEL_BUILT_IN_MOS123::precalc_first().
{
  assert(p);
  p->set_default(v);
}
template<class T > void set_default (T * p, const T & v)
Definition at line 160 of file u_parameter.h.
{
  assert(p);
  *p = v;
}