gnucap: savant/gnucap/src/e_compon.h File Reference
savant/gnucap/src/e_compon.h File Reference
#include "u_sim_data.h"
#include "u_time_pair.h"
#include "u_parameter.h"
#include "e_card.h"
Classes
struct Exception_Precalc
class COMMON_COMPONENT
class COMPONENT
Enumerations
enum { CC_STATIC = 27342 }
Functions
bool conchk (double o, double n, double a=OPT::abstol, double r=OPT::reltol)
Enumeration Type Documentation
anonymous enum
Enumerator:
CC_STATIC
Definition at line 54 of file e_compon.h.
{CC_STATIC=27342}; // mid-sized arbitrary positive int
Function Documentation
bool conchk (double o, double n, double a = OPT::abstol, double r = OPT::reltol) [inline]
Definition at line 42 of file e_compon.h.
Referenced by ELEMENT::conv_check(), anonymous_namespace{d_vcvs.cc}::DEV_VCVS::do_tr(), anonymous_namespace{d_res.cc}::DEV_RESISTANCE::do_tr(), anonymous_namespace{d_vs.cc}::DEV_VS::do_tr(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::do_tr(), DEV_SPICE::do_tr(), anonymous_namespace{d_poly_g.cc}::DEV_CPOLY_G::do_tr_con_chk_and_q(), anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::do_tr_con_chk_and_q(), DEV_SPICE::localize_ckt(), anonymous_namespace{d_trln.cc}::COMMON_TRANSLINE::precalc_last(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_advance(), STORAGE::tr_needs_eval(), and DEV_SPICE::tr_needs_eval().
{
  return (std::abs(n-o) <= (r * std::abs(n) + a));
}