gnucap: TIME_PAIR Struct Reference
TIME_PAIR Struct Reference
#include <u_time_pair.h>
Public Member Functions
TIME_PAIR ()
TIME_PAIR (double Error, double Event)
TIME_PAIR (const TIME_PAIR &P)
TIME_PAIR & reset ()
TIME_PAIR & min_error_estimate (double E)
TIME_PAIR & min_event (double E)
TIME_PAIR & min (const TIME_PAIR &P)
TIME_PAIR & min (double Error_Estimate, double Event)
Public Attributes
double _error_estimate
double _event
Detailed Description
Definition at line 29 of file u_time_pair.h.
Constructor & Destructor Documentation
TIME_PAIR::TIME_PAIR () [inline]
Definition at line 32 of file u_time_pair.h.
: _error_estimate(NEVER), _event(NEVER) {}
TIME_PAIR::TIME_PAIR (double Error, double Event) [inline]
Definition at line 33 of file u_time_pair.h.
: _error_estimate(Error), _event(Event) {}
TIME_PAIR::TIME_PAIR (const TIME_PAIR & P) [inline]
Definition at line 34 of file u_time_pair.h.
    : _error_estimate(P._error_estimate), _event(P._event) {}
Member Function Documentation
TIME_PAIR& TIME_PAIR::min (const TIME_PAIR & P) [inline]
Definition at line 55 of file u_time_pair.h.
References _error_estimate, _event, min_error_estimate(), and min_event().
Referenced by min(), and CARD_LIST::tr_review().
{
    return min_error_estimate(P._error_estimate).min_event(P._event);
  }
TIME_PAIR& TIME_PAIR::min (double Error_Estimate, double Event) [inline]
Definition at line 58 of file u_time_pair.h.
References min_error_estimate(), min_event(), and untested.
                                                      {untested();
    return min_error_estimate(Error_Estimate).min_event(Event);
  }
TIME_PAIR& TIME_PAIR::min_error_estimate (double E) [inline]
Definition at line 41 of file u_time_pair.h.
References _error_estimate.
Referenced by min(), STORAGE::tr_review(), anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP::tr_review(), ELEMENT::tr_review(), anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM::tr_review(), and anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::tr_review().
{
    if (E < _error_estimate) {
      _error_estimate = E;
    }else{
    }
    return *this;
  }
TIME_PAIR& TIME_PAIR::min_event (double E) [inline]
Definition at line 48 of file u_time_pair.h.
References _event.
Referenced by min(), anonymous_namespace{bm_pwl.cc}::EVAL_BM_PWL::tr_review(), anonymous_namespace{bm_pulse.cc}::EVAL_BM_PULSE::tr_review(), anonymous_namespace{bm_exp.cc}::EVAL_BM_EXP::tr_review(), anonymous_namespace{bm_sffm.cc}::EVAL_BM_SFFM::tr_review(), anonymous_namespace{bm_sin.cc}::EVAL_BM_SIN::tr_review(), and anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_review().
{
    if (E < _event) {
      _event = E;
    }else{
    }
    return *this;
  }
TIME_PAIR& TIME_PAIR::reset () [inline]
Definition at line 36 of file u_time_pair.h.
References _error_estimate, _event, and NEVER.
Referenced by anonymous_namespace{d_poly_cap.cc}::DEV_CPOLY_CAP::tr_review(), DEV_LOGIC::tr_review(), and COMPONENT::tr_review().
                     {
    _error_estimate = NEVER;
    _event = NEVER;
    return *this;
  }
Member Data Documentation
double TIME_PAIR::_error_estimate
Definition at line 30 of file u_time_pair.h.
Referenced by min(), min_error_estimate(), reset(), TRANSIENT::review(), ELEMENT::tr_probe_num(), COMPONENT::tr_probe_num(), and DEV_SPICE::tr_review().
double TIME_PAIR::_event
Definition at line 31 of file u_time_pair.h.
Referenced by min(), min_event(), reset(), TRANSIENT::review(), COMPONENT::tr_probe_num(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_review(), and DEV_SPICE::tr_review().
The documentation for this struct was generated from the following file:
savant/gnucap/src/u_time_pair.h