gnucap: savant/gnucap/src/l_wmatch.cc File Reference
savant/gnucap/src/l_wmatch.cc File Reference
#include <cctype>
#include "u_opt.h"
#include "l_lib.h"
Functions
static char fix_case (char c)
bool wmatch_by_ptr (const char *s2, const char *s1)
bool wmatch (const std::string &s1, const std::string &s2)
Function Documentation
static char fix_case (char c) [static]
Definition at line 34 of file l_wmatch.cc.
References OPT::case_insensitive.
Referenced by wmatch_by_ptr().
{
  return ((OPT::case_insensitive) ? (static_cast<char>(tolower(c))) : (c));
}
bool wmatch (const std::string & s1, const std::string & s2)
Definition at line 62 of file l_wmatch.cc.
References wmatch_by_ptr().
Referenced by PROBELIST::add_branches(), anonymous_namespace{c_delete.cc}::CMD_DELETE::delete_one_name(), CKT_BASE::find_wave(), findbranch(), and operator==().
{
  return wmatch_by_ptr(s1.c_str(), s2.c_str());
}
bool wmatch_by_ptr (const char * s2, const char * s1)
Definition at line 39 of file l_wmatch.cc.
References fix_case(), and itested.
Referenced by wmatch().
{
  if (!*s2 && !*s1) {                   // both end together -- match
    return true;
  }else if (!*s2 || !*s1) {             // ends don't match
    return false;
  }else if (fix_case(*s2) == fix_case(*s1)) { // one char matches - move on
    return wmatch_by_ptr(s2+1, s1+1);
  }else if (*s1 == '?') {               // ? wild card match - move on
    return wmatch_by_ptr(s2+1, s1+1);
  }else if (*s1 == '*') {               // * (repeat) wild card match
    if (wmatch_by_ptr(s2+1, s1)) {      // match 1, try for 2
      return true;
    }else if (wmatch_by_ptr(s2, s1+1)) {itested();      // match 0 - continue
      return true;
    }else{                              // match 1, only 1
      return wmatch_by_ptr(s2+1, s1+1);
    }
  }else{                                // mismatch
    return false;
  }
}