gnucap: BSMATRIX< T > Class Template Reference
BSMATRIX< T > Class Template Reference
#include <m_matrix.h>
Public Member Functions
BSMATRIX (int ss=0)
~BSMATRIX ()
void reinit (int ss=0)
void iwant (int, int)
void unallocate ()
void allocate ()
void reallocate ()
void set_min_pivot (double x)
void zero ()
void dezero (T &o)
int size () const
double density ()
T d (int r, int) const
void load_diagonal_point (int i, T value)
void load_point (int i, int j, T value)
void load_couple (int i, int j, T value)
void load_symmetric (int i, int j, T value)
void load_asymmetric (int r1, int r2, int c1, int c2, T value)
void lu_decomp (const BSMATRIX< T > &, bool do_partial)
void lu_decomp ()
void fbsub (T *v) const
void fbsub (T *x, const T *b, T *c=NULL) const
Private Member Functions
BSMATRIX (const BSMATRIX< T > &)
void uninit ()
void init (int s=0)
T & subtract_dot_product (int r, int c, int d)
T & subtract_dot_product (int r, int c, int d, const T &in)
int lownode (int i) const
bool is_changed (int n) const
void set_changed (int n, bool x=true) const
T u (int r, int c) const
T l (int r, int c) const
T & d (int r, int c)
T & u (int r, int c)
T & l (int r, int c)
T & m (int r, int c)
Private Attributes
bool * _changed
int * _lownode
T * _space
T ** _rowptr
T ** _colptr
T ** _diaptr
int _nzcount
int _size
T _zero
T _trash
T _min_pivot
Detailed Description
template<class T>
class BSMATRIX< T >
Definition at line 116 of file m_matrix.h.
Constructor & Destructor Documentation
template<class T> BSMATRIX< T >::BSMATRIX (const BSMATRIX< T > &) [inline, explicit, private]
Definition at line 130 of file m_matrix.h.
{incomplete();unreachable();}
template<class T> BSMATRIX< T >::BSMATRIX (int ss = 0) [explicit]
Definition at line 253 of file m_matrix.h.
References BSMATRIX< T >::init().
  :_changed(NULL),
   _lownode(NULL),
   _space(NULL),
   _rowptr(NULL),
   _colptr(NULL),
   _diaptr(NULL),
   _nzcount(0),
   _size(ss),
   _zero(0.),
   _trash(0.),
   _min_pivot(0.)
{
  init(ss);
}
template<class T> BSMATRIX< T >::~BSMATRIX () [inline]
Definition at line 140 of file m_matrix.h.
{uninit();}
Member Function Documentation
template<class T > void BSMATRIX< T >::allocate ()
Definition at line 319 of file m_matrix.h.
References point().
Referenced by BSMATRIX< COMPLEX >::reallocate().
{
  assert(_lownode);
  assert(!_colptr);
  assert(!_rowptr);
  assert(!_diaptr);
  assert(!_space);
  _nzcount = 0;
  for (int ii = 0;   ii <= size();   ++ii) {
    _nzcount += 2 * (ii - _lownode[ii]) + 1;
  }
  _colptr = new T*[size()+1];
  _rowptr = new T*[size()+1];
  _diaptr = new T*[size()+1];
  _space  = new T[_nzcount];
  assert(_colptr);
  assert(_rowptr);
  assert(_diaptr);
  zero();
  {
    T* point = _space;
    for (int ii = 0;   ii <= size();   ++ii) {
      _colptr[ii] = point - _lownode[ii];
      _rowptr[ii] = _colptr[ii] + 2*ii;
      _diaptr[ii] = _colptr[ii] + ii;
      point += 2 * (ii - _lownode[ii]) + 1;
    }
  }
}
template<class T> T BSMATRIX< T >::d (int r, int) const [inline]
Definition at line 152 of file m_matrix.h.
Referenced by BSMATRIX< T >::lu_decomp(), and NODE::tr_probe_num().
{return *(_diaptr[r]);}
template<class T > T & BSMATRIX< T >::d (int r, int c) [private]
Definition at line 394 of file m_matrix.h.
{
  assert(_diaptr);
  assert(r == c);
  assert(0 <= r);
  assert(r <= _size);
  return *(_diaptr[r]);
}
template<class T > double BSMATRIX< T >::density ()
Definition at line 376 of file m_matrix.h.
{
  if (size() > 0) {
    assert(_lownode);
    _nzcount = 0;
    for (int ii = 0;   ii <= size();   ++ii) {
      _nzcount += 2 * (ii - _lownode[ii]) + 1;
    }
    return static_cast<double>(_nzcount-1)/(static_cast<double>(size())*size());
  }else{
    return 0;
  }
}
template<class T> void BSMATRIX< T >::dezero (T & o)
Definition at line 368 of file m_matrix.h.
References offset.
Referenced by SIM::clear_arrays(), and SIM::command_base().
{
  for (int ii = 1;  ii <= size();  ++ii) {
    d(ii,ii) += offset;
  }
}
template<class T> void BSMATRIX< T >::fbsub (T * v) const
Definition at line 675 of file m_matrix.h.
Referenced by port_impedance(), and SIM::solve_equations().
{
  assert(_lownode);
  assert(v);
  for (int ii = 1; ii <= size(); ++ii) {        /* forward substitution */
    for (int jj = _lownode[ii]; jj < ii; ++jj) {
      v[ii] -= l(ii,jj) * v[jj];
    }
    v[ii] /= d(ii,ii);
  }
  for (int jj = size(); jj > 1; --jj) {         /* back substitution    */
    for (int ii = _lownode[jj]; ii < jj; ++ii) {
      v[ii] -= u(ii,jj) * v[jj];
    }
  }
}
template<class T> void BSMATRIX< T >::fbsub (T * x, const T * b, T * c = NULL) const
Definition at line 700 of file m_matrix.h.
References notstd::copy_n().
{
  assert(_lownode);
  assert(x);
  assert(b);
  assert(c);
  {
    int ii = 1;
    for (   ; ii <= size(); ++ii) {
      if (b[ii] != 0.) {
        break;
      }else{
      }
      c[ii] = 0.;
    }
    int first_nz = ii;
    for (   ; ii <= size(); ++ii) {             /* forward substitution */
      int low_node = std::max(_lownode[ii], first_nz);
      c[ii] = b[ii];
      for (int jj = low_node; jj < ii; ++jj) {
        c[ii] -= l(ii,jj) * c[jj];
      }
      c[ii] /= d(ii,ii);
    }
  }
  notstd::copy_n(c, size()+1, x);
  for (int jj = size(); jj > 1; --jj) {         /* back substitution    */
    for (int ii = _lownode[jj]; ii < jj; ++ii) {
      x[ii] -= u(ii,jj) * x[jj];
    }
  }
  x[0] = 0.;
  //BUG// some things don't work unless there is a zero here.
}
template<class T > void BSMATRIX< T >::init (int s = 0) [private]
Definition at line 187 of file m_matrix.h.
Referenced by BSMATRIX< T >::BSMATRIX(), and BSMATRIX< COMPLEX >::reinit().
{
  assert(!_lownode);
  assert(!_colptr);
  assert(!_rowptr);
  assert(!_diaptr);
  assert(!_space);
  assert(_zero == 0.);
  _min_pivot = _trash = 0.;
  _nzcount = 0;
  _size = ss;
  _lownode = new int[size()+1];
  assert(_lownode);
  for (int ii = 0;  ii <= size();  ++ii) {
    _lownode[ii] = ii;
  }
  _changed = new bool[size()+1];
  assert(_changed);
  for (int ii = 0;  ii <= size();  ++ii) {
    set_changed(ii, false);
  }
}
template<class T> bool BSMATRIX< T >::is_changed (int n) const [inline, private]
Definition at line 136 of file m_matrix.h.
Referenced by BSMATRIX< T >::lu_decomp().
{return _changed[n];}
template<class T > void BSMATRIX< T >::iwant (int node1, int node2)
Definition at line 286 of file m_matrix.h.
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::ac_iwant_matrix(), ELEMENT::ac_iwant_matrix_active(), ELEMENT::ac_iwant_matrix_extended(), ELEMENT::ac_iwant_matrix_passive(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_iwant_matrix(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_iwant_matrix(), ELEMENT::tr_iwant_matrix_active(), ELEMENT::tr_iwant_matrix_extended(), and ELEMENT::tr_iwant_matrix_passive().
{
  assert(_lownode);
  assert(node1 <= size());
  assert(node2 <= size());
  if (node1 <= 0  ||  node2 <= 0) {
    // node 0 is ground, and doesn't count as a connection
    // negative is invalid, not used but still may be in a node list
  }else if (node1 < _lownode[node2]) {
    _lownode[node2]=node1;
  }else if (node2 < _lownode[node1]) {
    _lownode[node1]=node2;
  }else{
  }
}
template<class T> T BSMATRIX< T >::l (int r, int c) const [inline, private]
Definition at line 155 of file m_matrix.h.
Referenced by BSMATRIX< T >::lu_decomp().
{return _rowptr[r][-c];}
template<class T > T & BSMATRIX< T >::l (int r, int c) [private]
Definition at line 425 of file m_matrix.h.
{
  assert(_rowptr);
  assert(_lownode);
  assert(0 < c);
  assert(c <= r);
  assert(r <= _size);
  assert(1 <= _lownode[r]);
  assert(_lownode[r] <= c);
  return _rowptr[r][-c];
}
template<class T> void BSMATRIX< T >::load_asymmetric (int r1, int r2, int c1, int c2, T value)
Definition at line 563 of file m_matrix.h.
Referenced by anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::ac_load(), ELEMENT::ac_load_active(), ELEMENT::ac_load_extended(), ELEMENT::tr_load_active(), and ELEMENT::tr_load_extended().
{
  set_changed(c1);
  set_changed(c2);
  if (r1 > 0) {
    set_changed(r1);
    if (c1 > 0) {
      m(r1,c1) += value;
    }else{
    }
    if (c2 > 0) {
      m(r1,c2) -= value;
    }else{
    }
  }else{
  }
  if (r2 > 0) {
    set_changed(r2);
    if (c1 > 0) {
      m(r2,c1) -= value;
    }else{
    }
    if (c2 > 0) {
      m(r2,c2) += value;
    }else{
    }
  }else{
  }
}
template<class T> void BSMATRIX< T >::load_couple (int i, int j, T value)
Definition at line 520 of file m_matrix.h.
References untested.
Referenced by ELEMENT::ac_load_couple(), ELEMENT::ac_load_inode(), ELEMENT::tr_load_couple(), and ELEMENT::tr_load_inode().
{
  if (j > 0) {
    set_changed(j);
    if (i > 0) {
      set_changed(i);
      m(i,j) -= value;
      m(j,i) -= value;
    }else{
    }
  }else{untested();
  }
}
template<class T> void BSMATRIX< T >::load_diagonal_point (int i, T value)
Definition at line 508 of file m_matrix.h.
References untested.
Referenced by ELEMENT::ac_load_diagonal_point(), and ELEMENT::tr_load_diagonal_point().
{
  if (i > 0) {
    set_changed(i);
    d(i,i) += value;
  }else{untested();
  }
}
template<class T> void BSMATRIX< T >::load_point (int i, int j, T value)
Definition at line 496 of file m_matrix.h.
Referenced by ELEMENT::ac_load_point(), and ELEMENT::tr_load_point().
{
  if (i > 0 && j > 0) {
    set_changed(j);
    set_changed(i);
    m(i,j) += value;
  }else{
  }
}
template<class T> void BSMATRIX< T >::load_symmetric (int i, int j, T value)
Definition at line 539 of file m_matrix.h.
Referenced by anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::ac_load(), ELEMENT::ac_load_passive(), ELEMENT::ac_load_shunt(), anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_load(), ELEMENT::tr_load_passive(), and ELEMENT::tr_load_shunt().
{
  if (j > 0) {
    set_changed(j);
    d(j,j) += value;
    if (i > 0) {
      set_changed(i);
      d(i,i) += value;
      m(i,j) -= value;
      m(j,i) -= value;
    }else{
    }
  }else if (i > 0) {
    set_changed(i);
    d(i,i) += value;
  }else{
  }
}
template<class T> int BSMATRIX< T >::lownode (int i) const [inline, private]
Definition at line 135 of file m_matrix.h.
Referenced by BSMATRIX< T >::lu_decomp().
{return _lownode[i];}
template<class T> void BSMATRIX< T >::lu_decomp (const BSMATRIX< T > & aa, bool do_partial)
Definition at line 594 of file m_matrix.h.
References BSMATRIX< T >::_lownode, BSMATRIX< T >::d(), error(), BSMATRIX< T >::is_changed(), BSMATRIX< T >::l(), BSMATRIX< T >::lownode(), BSMATRIX< T >::set_changed(), BSMATRIX< T >::size(), BSMATRIX< T >::u(), and untested.
Referenced by SIM::solve_equations().
{
  int prop = 0;   /* change propagation indicator */
  assert(_lownode);
  assert(aa._lownode);
  assert(aa.size() == size());
  for (int mm = 1;   mm <= size();   ++mm) {
    assert(aa.lownode(mm) == _lownode[mm]);
    int bn = _lownode[mm];
    if (!do_partial  ||  aa.is_changed(mm)  ||  bn <= prop) {
      aa.set_changed(mm, false);
      prop = mm;
      if (bn < mm) {
        prop = mm;
        u(bn,mm) = aa.u(bn,mm) / d(bn,bn);
        for (int ii = bn+1;  ii<mm;  ii++) {
          /* u(ii,mm) = (aa.u(ii,mm) - dot(ii,mm,ii)) / d(ii,ii); */
          subtract_dot_product(ii,mm,ii,aa.u(ii,mm)) /= d(ii,ii);
        }
        l(mm,bn) = aa.l(mm,bn);
        for (int jj = bn+1;  jj<mm;  jj++) {
          /* l(mm,jj) = aa.l(mm,jj) - dot(mm,jj,jj); */
          subtract_dot_product(mm,jj,jj,aa.l(mm,jj));
        }
        { /* jj == mm */
          /* d(mm,mm) = aa.d(mm,mm) - dot(mm,mm,mm); then test */
          if (subtract_dot_product(mm,mm,mm,aa.d(mm,mm)) == 0.) {untested();
            error(bWARNING, "open circuit: internal node %u\n", mm);
            d(mm,mm) = _min_pivot;
          }else{
          }
        }
      }else{    /* bn == mm */
        d(mm,mm) = aa.d(mm,mm);
        if (d(mm,mm)==0.) {untested();
          d(mm,mm) = _min_pivot;
        }else{
        }
      }
    }else{
    }
  }
}
template<class T> void BSMATRIX< T >::lu_decomp ()
Definition at line 639 of file m_matrix.h.
References error(), and untested.
{
  assert(_lownode);
  for (int mm = 1;   mm <= size();   ++mm) {
    int bn = _lownode[mm];
    if (bn < mm) {
      u(bn,mm) /= d(bn,bn);
      for (int ii =bn+1;  ii<mm;  ii++) {
        /* (m(ii,mm) -= dot(ii,mm,ii)) /= d(ii,ii); */
        subtract_dot_product(ii,mm,ii) /= d(ii,ii);
      }
      for (int jj = bn+1;  jj<mm;  jj++) {
        /* m(mm,jj) -= dot(mm,jj,jj); */
        subtract_dot_product(mm,jj,jj);
      }
      { /* jj == mm */
        /* m(mm,mm) -= dot(mm,mm,mm); then test */
        if (subtract_dot_product(mm,mm,mm) == 0.) {untested();
          error(bWARNING, "open circuit: internal node %u\n", mm);
          d(mm,mm) = _min_pivot;
        }else{
        }
      }
    }else{    /* bn == mm */
      if (d(mm,mm)==0.) {
        d(mm,mm) = _min_pivot;
      }else{
      }
    }
  }
}
template<class T > T & BSMATRIX< T >::m (int r, int c) [private]
Definition at line 443 of file m_matrix.h.
{
  return (c>=r) ? u(r,c) : l(r,c);
}
template<class T> void BSMATRIX< T >::reallocate () [inline]
Definition at line 146 of file m_matrix.h.
Referenced by SIM::command_base().
{unallocate(); allocate();}
template<class T> void BSMATRIX< T >::reinit (int ss = 0) [inline]
Definition at line 141 of file m_matrix.h.
Referenced by SIM_DATA::init(), and SIM_DATA::uninit().
{uninit(); init(ss);}
template<class T> void BSMATRIX< T >::set_changed (int n, bool x = true) const [inline, private]
Definition at line 137 of file m_matrix.h.
Referenced by BSMATRIX< T >::lu_decomp().
{_changed[n] = x;}
template<class T> void BSMATRIX< T >::set_min_pivot (double x) [inline]
Definition at line 147 of file m_matrix.h.
Referenced by SIM::command_base().
{_min_pivot = x;}
template<class T> int BSMATRIX< T >::size () const [inline]
Definition at line 150 of file m_matrix.h.
Referenced by SIM::clear_arrays(), BSMATRIX< T >::lu_decomp(), port_impedance(), SIM::solve_equations(), and SIM_DATA::uninit().
{return _size;}
template<class T > T & BSMATRIX< T >::subtract_dot_product (int r, int c, int d) [private]
Definition at line 212 of file m_matrix.h.
{
  assert(_lownode);
  int kk = std::max(_lownode[rr], _lownode[cc]);
  int len = dd - kk;
  T& dot = m(rr, cc);
  if (len > 0) {
    T* row = &(l(rr,kk));
    T* col = &(u(kk,cc));
    /* for (ii = kk;   ii < dd;   ++ii) */
    for (int ii = 0;   ii < len;   ++ii) {
      dot -= row[-ii] * col[ii];
    }
  }else{
  }
  return dot;
}
template<class T> T & BSMATRIX< T >::subtract_dot_product (int r, int c, int d, const T & in) [private]
Definition at line 231 of file m_matrix.h.
{
  assert(_lownode);
  int kk = std::max(_lownode[rr], _lownode[cc]);
  int len = dd - kk;
  T& dot = m(rr, cc);
  dot = in;
  if (len > 0) {
    T* row = &(l(rr,kk));
    T* col = &(u(kk,cc));
    /* for (ii = kk;   ii < dd;   ++ii) */
    for (int ii = 0;   ii < len;   ++ii) {
      dot -= row[-ii] * col[ii];
    }
  }else{
  }
  return dot;
}
template<class T> T BSMATRIX< T >::u (int r, int c) const [inline, private]
Definition at line 154 of file m_matrix.h.
Referenced by BSMATRIX< T >::lu_decomp().
{return _colptr[c][r];}
template<class T > T & BSMATRIX< T >::u (int r, int c) [private]
Definition at line 408 of file m_matrix.h.
{
  assert(_colptr);
  assert(_lownode);
  assert(0 < r);
  assert(r <= c);
  assert(c <= _size);
  assert(1 <= _lownode[c]);
  assert(_lownode[c] <= r);
  return _colptr[c][r];
}
template<class T > void BSMATRIX< T >::unallocate ()
Definition at line 304 of file m_matrix.h.
Referenced by SIM::command_base(), and BSMATRIX< COMPLEX >::reallocate().
{
  assert (_zero == 0.);
  delete [] _rowptr;
  delete [] _colptr;
  delete [] _diaptr;
  delete [] _space;
  _rowptr = _colptr = _diaptr = NULL;
  _space = NULL;
}
template<class T > void BSMATRIX< T >::uninit () [private]
Definition at line 177 of file m_matrix.h.
Referenced by BSMATRIX< COMPLEX >::reinit(), and BSMATRIX< COMPLEX >::~BSMATRIX().
{
  unallocate();
  delete [] _lownode;
  _lownode = NULL;
  delete [] _changed;
  _changed = NULL;
}
template<class T > void BSMATRIX< T >::zero ()
Definition at line 357 of file m_matrix.h.
Referenced by SIM::clear_arrays().
{
  assert(_space);
  assert(_zero == 0.);
  _trash = 0.;
  std::fill_n(_space, _nzcount, 0.);
}
Member Data Documentation
template<class T> bool* BSMATRIX< T >::_changed [mutable, private]
Definition at line 118 of file m_matrix.h.
Referenced by BSMATRIX< COMPLEX >::is_changed(), and BSMATRIX< COMPLEX >::set_changed().
template<class T> T** BSMATRIX< T >::_colptr [private]
Definition at line 122 of file m_matrix.h.
Referenced by BSMATRIX< COMPLEX >::u().
template<class T> T** BSMATRIX< T >::_diaptr [private]
Definition at line 123 of file m_matrix.h.
Referenced by BSMATRIX< COMPLEX >::d().
template<class T> int* BSMATRIX< T >::_lownode [private]
Definition at line 119 of file m_matrix.h.
Referenced by BSMATRIX< COMPLEX >::lownode(), and BSMATRIX< T >::lu_decomp().
template<class T> T BSMATRIX< T >::_min_pivot [private]
Definition at line 128 of file m_matrix.h.
Referenced by BSMATRIX< COMPLEX >::set_min_pivot().
template<class T> int BSMATRIX< T >::_nzcount [private]
Definition at line 124 of file m_matrix.h.
template<class T> T** BSMATRIX< T >::_rowptr [private]
Definition at line 121 of file m_matrix.h.
Referenced by BSMATRIX< COMPLEX >::l().
template<class T> int BSMATRIX< T >::_size [private]
Definition at line 125 of file m_matrix.h.
Referenced by BSMATRIX< COMPLEX >::size().
template<class T> T* BSMATRIX< T >::_space [private]
Definition at line 120 of file m_matrix.h.
template<class T> T BSMATRIX< T >::_trash [private]
Definition at line 127 of file m_matrix.h.
template<class T> T BSMATRIX< T >::_zero [private]
Definition at line 126 of file m_matrix.h.
The documentation for this class was generated from the following file:
savant/gnucap/src/m_matrix.h