gnucap: anonymous_namespace{d_vs.cc}::DEV_VS Class Reference
anonymous_namespace{d_vs.cc}::DEV_VS Class Reference
Public Member Functions
DEV_VS ()
Private Member Functions
DEV_VS (const DEV_VS &p)
char id_letter () const
std::string value_name () const
std::string dev_type () const
int max_nodes () const
int min_nodes () const
int matrix_nodes () const
int net_nodes () const
bool is_source () const
bool f_is_value () const
bool has_iv_probe () const
bool use_obsolete_callback_parse () const
CARD * clone () const
void precalc_last ()
void tr_iwant_matrix ()
void tr_begin ()
bool do_tr ()
void tr_load ()
void tr_unload ()
double tr_involts () const
double tr_involts_limited () const
void ac_iwant_matrix ()
void ac_begin ()
void do_ac ()
void ac_load ()
COMPLEX ac_involts () const
COMPLEX ac_amps () const
std::string port_name (int i) const
Detailed Description
Definition at line 30 of file d_vs.cc.
Constructor & Destructor Documentation
anonymous_namespace{d_vs.cc}::DEV_VS::DEV_VS (const DEV_VS & p) [inline, explicit, private]
Definition at line 32 of file d_vs.cc.
:ELEMENT(p) {}
anonymous_namespace{d_vs.cc}::DEV_VS::DEV_VS () [inline, explicit]
Definition at line 34 of file d_vs.cc.
:ELEMENT() {}
Member Function Documentation
COMPLEX anonymous_namespace{d_vs.cc}::DEV_VS::ac_amps () const [inline, private, virtual]
Reimplemented from ELEMENT.
Definition at line 61 of file d_vs.cc.
{return (_acg + ac_outvolts()*_loss0);}
void anonymous_namespace{d_vs.cc}::DEV_VS::ac_begin () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 57 of file d_vs.cc.
References OPT::shortckt.
{_loss1 = _loss0 = 1./OPT::shortckt; _acg = _ev = 0.;}
COMPLEX anonymous_namespace{d_vs.cc}::DEV_VS::ac_involts () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 60 of file d_vs.cc.
{return 0.;}
void anonymous_namespace{d_vs.cc}::DEV_VS::ac_iwant_matrix () [inline, private, virtual]
Implements ELEMENT.
Definition at line 56 of file d_vs.cc.
{ac_iwant_matrix_passive();}
void anonymous_namespace{d_vs.cc}::DEV_VS::ac_load () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 59 of file d_vs.cc.
{ac_load_shunt(); ac_load_source();}
CARD* anonymous_namespace{d_vs.cc}::DEV_VS::clone () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 47 of file d_vs.cc.
{return new DEV_VS(*this);}
std::string anonymous_namespace{d_vs.cc}::DEV_VS::dev_type () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 38 of file d_vs.cc.
{return "vsource";}
void anonymous_namespace{d_vs.cc}::DEV_VS::do_ac () [private, virtual]
Reimplemented from CARD.
Definition at line 131 of file d_vs.cc.
References itested.
{
  if (using_ac_eval()) {
    ac_eval();
    _acg = -_loss0 * _ev;
  }else{itested();
    assert(_acg == 0.);
  }
}
bool anonymous_namespace{d_vs.cc}::DEV_VS::do_tr () [private, virtual]
Reimplemented from CARD.
Definition at line 100 of file d_vs.cc.
References conchk(), converged, itested, OUT1, OUT2, and OPT::shortckt.
{
  assert(_m0.x == 0.);
  if (using_tr_eval()) {
    _y[0].x = _sim->_time0;
    tr_eval();
    if (_n[OUT2].m_() == 0) {
      _sim->set_limit(_y[0].f1);
    }else if (_n[OUT1].m_() == 0) {
      _sim->set_limit(-_y[0].f1);
    }else{
      //BUG// don't set limit
    }
    store_values();
    q_load();
    _m0.c0 = -_loss0 * _y[0].f1;
    assert(_m0.c1 == 0.);
  }else{itested();
    assert(conchk(_loss0, 1./OPT::shortckt));
    assert(_y[0].x == 0.);
    assert(_y[0].f0 == 0.);
    assert(_y[0].f1 == value());
    assert(_m0.x == 0.);
    assert(conchk(_m0.c0, -_loss0 * _y[0].f1));
    assert(_m0.c1 == 0.);
    assert(_y1 == _y[0]);
    assert(converged());
  }
  return converged();
}
bool anonymous_namespace{d_vs.cc}::DEV_VS::f_is_value () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 44 of file d_vs.cc.
{return true;}
bool anonymous_namespace{d_vs.cc}::DEV_VS::has_iv_probe () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 45 of file d_vs.cc.
{return true;}
char anonymous_namespace{d_vs.cc}::DEV_VS::id_letter () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 36 of file d_vs.cc.
{return 'V';}
bool anonymous_namespace{d_vs.cc}::DEV_VS::is_source () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 43 of file d_vs.cc.
{return true;}
int anonymous_namespace{d_vs.cc}::DEV_VS::matrix_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 41 of file d_vs.cc.
{return 2;}
int anonymous_namespace{d_vs.cc}::DEV_VS::max_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 39 of file d_vs.cc.
{return 2;}
int anonymous_namespace{d_vs.cc}::DEV_VS::min_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 40 of file d_vs.cc.
{return 2;}
int anonymous_namespace{d_vs.cc}::DEV_VS::net_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 42 of file d_vs.cc.
{return 2;}
std::string anonymous_namespace{d_vs.cc}::DEV_VS::port_name (int i) const [inline, private, virtual]
Implements COMPONENT.
Definition at line 63 of file d_vs.cc.
{
    assert(i >= 0);
    assert(i < 2);
    static std::string names[] = {"p", "n"};
    return names[i];
  }
void anonymous_namespace{d_vs.cc}::DEV_VS::precalc_last () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 72 of file d_vs.cc.
References ELEMENT::precalc_last().
{
  ELEMENT::precalc_last();
  set_constant(!has_tr_eval());
  set_converged(!has_tr_eval());
}
void anonymous_namespace{d_vs.cc}::DEV_VS::tr_begin () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 79 of file d_vs.cc.
References OUT1, OUT2, OPT::shortckt, ELEMENT::tr_begin(), and untested.
{
  ELEMENT::tr_begin();
  _y1.f0 = _y[0].f0 = 0.; // override
  _loss1 = _loss0 = 1./OPT::shortckt;
  _m0.x  = 0.;
  _m0.c0 = -_loss0 * _y[0].f1;
  _m0.c1 = 0.;
  _m1 = _m0;
  if (!using_tr_eval()) {
    if (_n[OUT2].m_() == 0) {
      _sim->set_limit(value());
    }else if (_n[OUT1].m_() == 0) {untested();
      _sim->set_limit(-value());
    }else{untested();
      //BUG// don't set limit
    }
  }else{
  }
}
double anonymous_namespace{d_vs.cc}::DEV_VS::tr_involts () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 54 of file d_vs.cc.
{return 0.;}
double anonymous_namespace{d_vs.cc}::DEV_VS::tr_involts_limited () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 55 of file d_vs.cc.
References unreachable.
{unreachable(); return 0.;}
void anonymous_namespace{d_vs.cc}::DEV_VS::tr_iwant_matrix () [inline, private, virtual]
Implements ELEMENT.
Definition at line 49 of file d_vs.cc.
{tr_iwant_matrix_passive();}
void anonymous_namespace{d_vs.cc}::DEV_VS::tr_load () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 52 of file d_vs.cc.
{tr_load_shunt(); tr_load_source();}
void anonymous_namespace{d_vs.cc}::DEV_VS::tr_unload () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 53 of file d_vs.cc.
References untested.
{untested();tr_unload_source();}
bool anonymous_namespace{d_vs.cc}::DEV_VS::use_obsolete_callback_parse () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 46 of file d_vs.cc.
{return true;}
std::string anonymous_namespace{d_vs.cc}::DEV_VS::value_name () const [inline, private, virtual]
Implements CARD.
Definition at line 37 of file d_vs.cc.
{return "dc";}
The documentation for this class was generated from the following file:
savant/gnucap/src/d_vs.cc