gnucap: savant/gnucap/src/io_contr.cc File Reference
savant/gnucap/src/io_contr.cc File Reference
#include "io_.h"
#include "ap.h"
Functions
void initio (OMSTREAM &)
void outreset (void)
OMSTREAM * outset (CS &, OMSTREAM *)
static FILE * file_open (CS &, const char *, const char *, FILE *)
Variables
static FILE * fn
static FILE * to_pipe
Function Documentation
static FILE * file_open (CS & cmd, const char * ext, const char * rwaflag, FILE * fileptr) [static]
Definition at line 160 of file io_contr.cc.
References itested, xclose(), and xopen().
Referenced by outset().
{itested();
  xclose(&fileptr);
  fileptr = xopen(cmd,ext,rwaflag);
  if (!fileptr) {itested();
    throw Exception_File_Open("");
  }else{itested();
  }
  return fileptr;
}
void initio (OMSTREAM & Where)
Definition at line 41 of file io_contr.cc.
References BUFLEN, OMSTREAM::cipher(), IO::incipher, and untested.
Referenced by TRANSIENT::options(), anonymous_namespace{s_ac.cc}::AC::setup(), anonymous_namespace{s_dc.cc}::DC::setup(), and anonymous_namespace{s_dc.cc}::OP::setup().
{
  const char* tag = "''''";
  if (Where.cipher()) {         /* if writing an encrypted file,    */
    untested();
    Where << tag << '\n';       /* mark it as encrypted             */
  }else{
  }
#if 0
  if (Whence) {
    char buf[BUFLEN];
    if (!fgets(buf, BUFLEN, Whence))    /* if the first line deciphers to   */
      return;                           /* the cipher tag, it is encrypted  */
    IO::incipher = true;                /* otherwise,                       */
    decipher(buf);                      /*       rewind and read normally   */
    if (strcmp(buf,tag) != 0) {         /* mismatch */
      IO::incipher = false;
      fseek(Whence,0L,SEEK_SET);
    }
  }
#endif
}
void outreset (void)
Definition at line 86 of file io_contr.cc.
References fn, IO::formaat, IO::incipher, IO::mstdout, OMSTREAM::reset(), to_pipe, untested, and xclose().
Referenced by CMD::cmdproc(), and finish().
{
  if (to_pipe) {
    untested();
    pclose(to_pipe);
    to_pipe = NULL;
  }else{
  }
  xclose(&fn);
  IO::formaat = 0;
  IO::incipher = false;
  IO::mstdout.reset();
}
OMSTREAM* outset (CS & cmd, OMSTREAM * out)
Definition at line 103 of file io_contr.cc.
References file_open(), fn, IO::formaat, ftos_EXP, itested, IO::mstdout, IO::stream, to_pipe, CS::umatch(), and untested.
Referenced by anonymous_namespace{c_measure.cc}::CMD_MEASURE::do_it(), anonymous_namespace{c_list.cc}::CMD_SAVE::do_it(), anonymous_namespace{s_dc.cc}::DCOP::options(), TRANSIENT::options(), and anonymous_namespace{s_ac.cc}::AC::setup().
{
  bool echo = false;
  for (;;) {
    if (cmd.umatch("basic ")) {
      IO::formaat = ftos_EXP;
      (*out).setformat(ftos_EXP);
    }else if (cmd.umatch("cipher ")) {untested();
      (*out).setcipher().setpack();
    }else if (cmd.umatch("pack ")) {itested();
      (*out).setpack();
    }else if (cmd.umatch("quiet ")) {itested();
      echo = false;
      (*out).detach(IO::mstdout);
    }else if (cmd.umatch("echo ") || cmd.umatch("list ")) {itested();
      echo = true;
      (*out).attach(IO::mstdout);
    }else if (cmd.umatch("save ")) {itested();
      fn = file_open(cmd,"","w",fn);
      (*out).attach(fn);
    }else if (cmd.umatch("\\|")) {untested();
      // open a pipe
      std::string command;
      cmd >> command;
      to_pipe = popen(command.c_str(), "w");
      assert(to_pipe);
      IO::stream[static_cast<int>(fileno(to_pipe))] = to_pipe;
      (*out).attach(to_pipe);
      IO::formaat = ftos_EXP;
      (*out).setformat(ftos_EXP);
      if (!echo) {untested();
        (*out).detach(IO::mstdout);
      }else{untested();
      }
    }else if (cmd.umatch(">")) {itested();
      // open a file for write or append
      const char *rwaflag;
      rwaflag = (cmd.umatch(">")) ? "a" : "w";
      fn = file_open(cmd,"",rwaflag,fn);
      (*out).attach(fn);
      IO::formaat = ftos_EXP;
      (*out).setformat(ftos_EXP);
      if (!echo) {itested();
        (*out).detach(IO::mstdout);
      }else{untested();
      }
    }else{
      break;
    }
  }
  return out;
}
Variable Documentation
FILE* fn [static]
Definition at line 36 of file io_contr.cc.
Referenced by outreset(), and outset().
FILE* to_pipe [static]
Definition at line 37 of file io_contr.cc.
Referenced by outreset(), and outset().