gnucap: anonymous_namespace{d_vcg.cc}::DEV_VCG Class Reference
anonymous_namespace{d_vcg.cc}::DEV_VCG Class Reference
Public Member Functions
DEV_VCG ()
Private Member Functions
DEV_VCG (const DEV_VCG &p)
char id_letter () const
std::string value_name () const
std::string dev_type () const
int max_nodes () const
int min_nodes () const
int matrix_nodes () const
int net_nodes () const
bool use_obsolete_callback_parse () const
CARD * clone () const
void tr_iwant_matrix ()
void tr_begin ()
bool do_tr ()
void tr_load ()
void tr_unload ()
double tr_involts () const
double tr_involts_limited () const
void ac_iwant_matrix ()
void ac_begin ()
void do_ac ()
void ac_load ()
COMPLEX ac_involts () const
std::string port_name (int i) const
Detailed Description
Definition at line 37 of file d_vcg.cc.
Constructor & Destructor Documentation
anonymous_namespace{d_vcg.cc}::DEV_VCG::DEV_VCG (const DEV_VCG & p) [inline, explicit, private]
Definition at line 39 of file d_vcg.cc.
:ELEMENT(p) {}
anonymous_namespace{d_vcg.cc}::DEV_VCG::DEV_VCG () [inline, explicit]
Definition at line 41 of file d_vcg.cc.
:ELEMENT() {}
Member Function Documentation
void anonymous_namespace{d_vcg.cc}::DEV_VCG::ac_begin () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 60 of file d_vcg.cc.
{_ev = _y[0].f0;  _acg = _m0.c1;}
COMPLEX anonymous_namespace{d_vcg.cc}::DEV_VCG::ac_involts () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 63 of file d_vcg.cc.
References IN1, and IN2.
{return _n[IN1]->vac() - _n[IN2]->vac();}
void anonymous_namespace{d_vcg.cc}::DEV_VCG::ac_iwant_matrix () [inline, private, virtual]
Implements ELEMENT.
Definition at line 59 of file d_vcg.cc.
{ac_iwant_matrix_extended();}
void anonymous_namespace{d_vcg.cc}::DEV_VCG::ac_load () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 62 of file d_vcg.cc.
{ac_load_shunt(); ac_load_active();}
CARD* anonymous_namespace{d_vcg.cc}::DEV_VCG::clone () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 51 of file d_vcg.cc.
{return new DEV_VCG(*this);}
std::string anonymous_namespace{d_vcg.cc}::DEV_VCG::dev_type () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 45 of file d_vcg.cc.
{return "vcg";}
void anonymous_namespace{d_vcg.cc}::DEV_VCG::do_ac () [private, virtual]
Reimplemented from CARD.
Definition at line 101 of file d_vcg.cc.
{
  if (using_ac_eval()) {
    ac_eval();
    _acg = _ev * _m0.x;
    _ev *= _y[0].x;
  }else{
    assert(_ev == _y[0].f0);
    assert(_acg == _m0.c1);
  }
}
bool anonymous_namespace{d_vcg.cc}::DEV_VCG::do_tr () [private, virtual]
Reimplemented from CARD.
Definition at line 85 of file d_vcg.cc.
References converged, and LINEAR.
{
  _y[0].x = tr_input_limited();
  tr_eval();
  assert(_y[0].f0 != LINEAR);
  store_values();
  q_load();
  _loss0 = _y[0].f0;
  _m0.x = tr_outvolts(); // fake
  _m0.c1 = _y[0].f1 * tr_outvolts();
  _m0.c0 = -_y[0].x * _m0.c1;
  return converged();
}
char anonymous_namespace{d_vcg.cc}::DEV_VCG::id_letter () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 43 of file d_vcg.cc.
References untested.
{untested();return '\0';}
int anonymous_namespace{d_vcg.cc}::DEV_VCG::matrix_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 48 of file d_vcg.cc.
{return 4;}
int anonymous_namespace{d_vcg.cc}::DEV_VCG::max_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 46 of file d_vcg.cc.
{return 4;}
int anonymous_namespace{d_vcg.cc}::DEV_VCG::min_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 47 of file d_vcg.cc.
{return 4;}
int anonymous_namespace{d_vcg.cc}::DEV_VCG::net_nodes () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 49 of file d_vcg.cc.
{return 4;}
std::string anonymous_namespace{d_vcg.cc}::DEV_VCG::port_name (int i) const [inline, private, virtual]
Implements COMPONENT.
Definition at line 65 of file d_vcg.cc.
References untested.
                                  {untested();
    assert(i >= 0);
    assert(i < 4);
    static std::string names[] = {"p", "n", "ps", "ns"};
    return names[i];
  }
void anonymous_namespace{d_vcg.cc}::DEV_VCG::tr_begin () [private, virtual]
Reimplemented from ELEMENT.
Definition at line 74 of file d_vcg.cc.
References ELEMENT::tr_begin().
{
  ELEMENT::tr_begin();
  _y1.f0 = _y[0].f0 = 0;  // override
  _loss1 = _loss0 = 0;
  _m0.x  = 0.;
  _m0.c1 = 0.;
  _m0.c0 = 0.;
  _m1 = _m0;
}
double anonymous_namespace{d_vcg.cc}::DEV_VCG::tr_involts () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 57 of file d_vcg.cc.
References dn_diff(), IN1, and IN2.
{return dn_diff(_n[IN1].v0(), _n[IN2].v0());}
double anonymous_namespace{d_vcg.cc}::DEV_VCG::tr_involts_limited () const [inline, private, virtual]
Implements ELEMENT.
Definition at line 58 of file d_vcg.cc.
References IN1, IN2, and volts_limited().
{return volts_limited(_n[IN1],_n[IN2]);}
void anonymous_namespace{d_vcg.cc}::DEV_VCG::tr_iwant_matrix () [inline, private, virtual]
Implements ELEMENT.
Definition at line 52 of file d_vcg.cc.
{tr_iwant_matrix_extended();}
void anonymous_namespace{d_vcg.cc}::DEV_VCG::tr_load () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 55 of file d_vcg.cc.
{tr_load_shunt(); tr_load_active();}
void anonymous_namespace{d_vcg.cc}::DEV_VCG::tr_unload () [inline, private, virtual]
Reimplemented from CARD.
Definition at line 56 of file d_vcg.cc.
References untested.
{untested(); tr_unload_shunt(); tr_unload_active();}
bool anonymous_namespace{d_vcg.cc}::DEV_VCG::use_obsolete_callback_parse () const [inline, private, virtual]
Reimplemented from COMPONENT.
Definition at line 50 of file d_vcg.cc.
{return true;}
std::string anonymous_namespace{d_vcg.cc}::DEV_VCG::value_name () const [inline, private, virtual]
Implements CARD.
Definition at line 44 of file d_vcg.cc.
References untested.
{untested(); return "g";}
The documentation for this class was generated from the following file:
savant/gnucap/src/d_vcg.cc