gnucap: CMD Class Reference
CMD Class Reference
#include <c_comand.h>
Public Member Functions
std::string value_name () const
virtual void do_it (CS &, CARD_LIST *)=0
virtual ~CMD ()
Static Public Member Functions
static void cmdproc (CS &, CARD_LIST *)
static void command (const std::string &, CARD_LIST *)
Detailed Description
Definition at line 31 of file c_comand.h.
Constructor & Destructor Documentation
virtual CMD::~CMD () [inline, virtual]
Definition at line 35 of file c_comand.h.
{}
Member Function Documentation
void CMD::cmdproc (CS & cmd, CARD_LIST * scope) [static]
Definition at line 33 of file c__cmd.cc.
References OPT::acct, ANTI_COMMENT, TIMER::check(), CS::check(), anonymous_namespace{c_attach.cc}::command_dispatcher, CS::cursor(), do_it(), TIMER::elapsed(), error(), OMSTREAM::form(), CS::fullstring(), I_PROMPT, itested, IO::mstdout, outreset(), plclose(), TIMER::reset(), TIMER::start(), CKT_BASE::status(), TIMER::stop(), CS::umatch(), untested, and CS::warn().
Referenced by anonymous_namespace{c_sweep.cc}::doit(), main(), anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_command(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_command(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_command(), LANGUAGE::parse_top_item(), and process_cmd_line().
{
  bool get_timer_was_running = ::status.get.is_running();
  ::status.get.stop();
  static TIMER timecheck;
  bool didsomething = true;
  error(bTRACE, ">>>>>" + cmd.fullstring() + "\n");
  timecheck.stop().reset().start();
  cmd.umatch(ANTI_COMMENT);
  while (cmd.umatch(I_PROMPT)) {itested();
    /* skip any number of these */
  }
  unsigned here = cmd.cursor();
  std::string s;
  // Map possible short names to full ones.
  // If this if/else block is removed, the only loss is the short names.
  // Although it looks like it can be used to make aliases, don't.
  if (cmd.umatch("'|*|#|//|\""))        {itested(); s = "xxxxcomment";}
  else if (cmd.umatch("b{uild} "))      {itested();  s = "build";}
  else if (cmd.umatch("del{ete} "))     {            s = "delete";}
  else if (cmd.umatch("fo{urier} "))    {            s = "fourier";}
  else if (cmd.umatch("gen{erator} "))  {            s = "generator";}
  else if (cmd.umatch("inc{lude} "))    {itested();  s = "include";}
  else if (cmd.umatch("l{ist} "))       {            s = "list";}
  else if (cmd.umatch("m{odify} "))     {            s = "modify";}
  else if (cmd.umatch("opt{ions} "))    {            s = "options";}
  else if (cmd.umatch("par{ameter} "))  {            s = "param";}
  else if (cmd.umatch("pr{int} "))      {            s = "print";}
  else if (cmd.umatch("q{uit} "))       {            s = "quit";}
  else if (cmd.umatch("st{atus} "))     {            s = "status";}
  else if (cmd.umatch("te{mperature} ")){itested();  s = "temperature";}
  else if (cmd.umatch("tr{ansient} "))  {            s = "transient";}
  else if (cmd.umatch("!"))             {            s = "system";}
  else if (cmd.umatch("<"))             {untested(); s = "<";}
  else if (cmd.umatch(">"))             {untested(); s = ">";}
  else{ /* no shortcut available */
    cmd >> s;
    didsomething = false;
  }
  if (s == "xxxxcomment") {itested();
    // nothing
  }else if (s != "") {
    CMD* c = command_dispatcher[s];
    if (c) {
      c->do_it(cmd, scope);
      didsomething = true;
    }else{itested();
      cmd.warn(bWARNING, here, "what's this?");
    }
  }else if (!didsomething) {itested();
    cmd.check(bWARNING, "bad command");
    didsomething = false;
  }else{itested();
  }
  if (OPT::acct  &&  didsomething) {itested();
    IO::mstdout.form("time=%8.2f\n", timecheck.check().elapsed());
  }else{
  }
  plclose();
  outreset();
  if (get_timer_was_running) {
    ::status.get.start();
  }else{
  }
}
void CMD::command (const std::string & cs, CARD_LIST * scope) [static]
Definition at line 108 of file c__cmd.cc.
References CS::_STRING, anonymous_namespace{c_attach.cc}::command_dispatcher, do_it(), and itested.
Referenced by main(), process_cmd_line(), and read_startup_files().
{
  CS cmd(CS::_STRING, cs); // from string, full command
  std::string s;
  cmd >> s;
  CMD* c = command_dispatcher[s];
  if (c) {
    c->do_it(cmd, scope);
  }else{itested();
    throw Exception("bad internal command: " + s);
  }
}
virtual void CMD::do_it (CS & , CARD_LIST *) [pure virtual]
Implemented in anonymous_namespace{lang_spice.cc}::CMD_CONTROL, anonymous_namespace{lang_spice.cc}::CMD_ENDC, anonymous_namespace{lang_spice.cc}::CMD_ACS, anonymous_namespace{lang_spice.cc}::CMD_SPICE, anonymous_namespace{lang_spice.cc}::CMD_BUILD, anonymous_namespace{lang_spice.cc}::CMD_GET, anonymous_namespace{lang_spice.cc}::CMD_RUN, anonymous_namespace{lang_spice.cc}::CMD_MERGE, anonymous_namespace{lang_spice.cc}::CMD_INCLUDE, anonymous_namespace{lang_spice.cc}::CMD_LIB, anonymous_namespace{lang_spice.cc}::CMD_SUBCKT, anonymous_namespace{lang_spice.cc}::CMD_MODEL, anonymous_namespace{lang_verilog.cc}::CMD_VERILOG, anonymous_namespace{lang_verilog.cc}::CMD_MODULE, anonymous_namespace{lang_verilog.cc}::CMD_PARAMSET, anonymous_namespace{lang_spectre.cc}::CMD_SPECTRE, anonymous_namespace{lang_spectre.cc}::CMD_SIMULATOR, anonymous_namespace{lang_spectre.cc}::CMD_SUBCKT, anonymous_namespace{lang_spectre.cc}::CMD_MODEL, anonymous_namespace{c_modify.cc}::CMD_UNFAULT, anonymous_namespace{c_modify.cc}::CMD_RESTORE, anonymous_namespace{c_prbcmd.cc}::CMD_PRINT, anonymous_namespace{c_modify.cc}::CMD_FAULT, anonymous_namespace{c_sweep.cc}::CMD_SWEEP, anonymous_namespace{c_modify.cc}::CMD_MODIFY, anonymous_namespace{c_prbcmd.cc}::CMD_PLOT, anonymous_namespace{c_prbcmd.cc}::CMD_ALARM, anonymous_namespace{c_comand.cc}::CMD_TITLE, anonymous_namespace{c_list.cc}::CMD_SAVE, anonymous_namespace{c_prbcmd.cc}::CMD_STORE, anonymous_namespace{c_list.cc}::CMD_LIST, anonymous_namespace{c_file.cc}::CMD_FILE, anonymous_namespace{c_delete.cc}::CMD_DELETE, anonymous_namespace{c_comand.cc}::CMD_TEMP, anonymous_namespace{lang_gschem.cc}::CMD_GSCHEM, anonymous_namespace{c_comand.cc}::CMD_QUIT, anonymous_namespace{s_dc.cc}::OP, anonymous_namespace{c_attach.cc}::CMD_DETACH, anonymous_namespace{s_dc.cc}::DC, anonymous_namespace{c_comand.cc}::CMD_PAUSE, anonymous_namespace{c_system.cc}::CMD_CHDIR, anonymous_namespace{c_file.cc}::CMD_LOG, TRANSIENT, anonymous_namespace{c_system.cc}::CMD_SYSTEM, anonymous_namespace{c_genrat.cc}::CMD_, anonymous_namespace{c_comand.cc}::CMD_END, anonymous_namespace{c_sim.cc}::CMD_UNMARK, anonymous_namespace{c_file.cc}::CMD_INCLUDE, anonymous_namespace{c_status.cc}::CMD_STATUS, anonymous_namespace{s_fo.cc}::FOURIER, anonymous_namespace{c_clear.cc}::CMD_CLEAR, anonymous_namespace{c_system.cc}::CMD_EDIT, anonymous_namespace{c_attach.cc}::CMD_ATTACH, anonymous_namespace{c_comand.cc}::CMD_OPT, anonymous_namespace{c_measure.cc}::CMD_MEASURE, anonymous_namespace{s_ac.cc}::AC, anonymous_namespace{c_sim.cc}::CMD_MARK, anonymous_namespace{c_exp.cc}::CMD_, and anonymous_namespace{c_param.cc}::CMD_PARAM.
Referenced by cmdproc(), and command().
std::string CMD::value_name () const [inline, virtual]
Implements CARD.
Definition at line 33 of file c_comand.h.
{return "";}
The documentation for this class was generated from the following files:
savant/gnucap/src/c_comand.h
savant/gnucap/src/c__cmd.cc