gnucap: LOGIC_NOR Class Reference
LOGIC_NOR Class Reference
#include <d_logic.h>
Public Member Functions
LOGIC_NOR (int c=0)
LOGICVAL logic_eval (const node_t *n) const
virtual std::string name () const
Private Member Functions
LOGIC_NOR (const LOGIC_NOR &p)
COMMON_COMPONENT * clone () const
Detailed Description
Definition at line 212 of file d_logic.h.
Constructor & Destructor Documentation
LOGIC_NOR::LOGIC_NOR (const LOGIC_NOR & p) [inline, explicit, private]
Definition at line 214 of file d_logic.h.
References COMMON_LOGIC::_count.
Referenced by clone().
:COMMON_LOGIC(p) {++_count;}
LOGIC_NOR::LOGIC_NOR (int c = 0) [inline, explicit]
Definition at line 217 of file d_logic.h.
:COMMON_LOGIC(c) {}
Member Function Documentation
COMMON_COMPONENT* LOGIC_NOR::clone () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 215 of file d_logic.h.
References LOGIC_NOR().
{return new LOGIC_NOR(*this);}
LOGICVAL LOGIC_NOR::logic_eval (const node_t * n) const [inline, virtual]
Implements COMMON_LOGIC.
Definition at line 218 of file d_logic.h.
References COMMON_LOGIC::incount, and LOGIC_NODE::lv().
{
    LOGICVAL out(n[0]->lv());
    for (int ii=1; ii<incount; ++ii) {
      out |= n[ii]->lv();
    }
    return ~out;
  }
virtual std::string LOGIC_NOR::name () const [inline, virtual]
Implements COMMON_COMPONENT.
Definition at line 225 of file d_logic.h.
{return "nor";}
The documentation for this class was generated from the following file:
savant/gnucap/src/d_logic.h