gnucap: anonymous_namespace{c_prbcmd.cc} Namespace Reference
anonymous_namespace{c_prbcmd.cc} Namespace Reference
Classes
class CMD_STORE
class CMD_ALARM
class CMD_PLOT
class CMD_PRINT
Functions
void do_probe (CS &cmd, PROBELIST *probes)
Variables
anonymous_namespace{c_prbcmd.cc}::CMD_STORE p0
DISPATCHER< CMD >::INSTALL d0 & command_dispatcher
anonymous_namespace{c_prbcmd.cc}::CMD_ALARM p1
anonymous_namespace{c_prbcmd.cc}::CMD_PLOT p2
anonymous_namespace{c_prbcmd.cc}::CMD_PRINT p3
Function Documentation
void anonymous_namespace{c_prbcmd.cc}::do_probe (CS & cmd, PROBELIST * probes)
Definition at line 34 of file c_prbcmd.cc.
References CKT_BASE::_sim, PROBELIST::add_list(), PROBELIST::clear(), SIM_DATA::init(), CS::is_end(), itested, PROBELIST::listing(), CS::match1(), CS::more(), ONE_OF, PROBELIST::remove_list(), s_AC, s_DC, s_FOURIER, s_NONE, s_OP, s_TRAN, sCOUNT, Set(), SIM_DATA::set_command_none(), CS::skip(), sSTART, CS::umatch(), and untested.
Referenced by anonymous_namespace{c_prbcmd.cc}::CMD_STORE::do_it(), anonymous_namespace{c_prbcmd.cc}::CMD_ALARM::do_it(), anonymous_namespace{c_prbcmd.cc}::CMD_PLOT::do_it(), and anonymous_namespace{c_prbcmd.cc}::CMD_PRINT::do_it().
{
  CKT_BASE::_sim->set_command_none();
  enum {aADD, aDELETE, aNEW} action;
  SIM_MODE simtype = s_NONE;
  if (cmd.match1('-')) {untested();     /* handle .probe - ac ...... */
    action = aDELETE;           /* etc.                      */
    cmd.skip();
  }else if (cmd.match1('+')) {untested();
    action = aADD;
    cmd.skip();
  }else{                        /* no -/+ means clear, but wait for */
    action = aNEW;              /* .probe ac + .....                */
  }                             /* which will not clear first       */
  ONE_OF
    || Set(cmd, "tr{ansient}", &simtype, s_TRAN)
    || Set(cmd, "ac",          &simtype, s_AC)
    || Set(cmd, "dc",          &simtype, s_DC)
    || Set(cmd, "op",          &simtype, s_OP)
    || Set(cmd, "fo{urier}",   &simtype, s_FOURIER)
    ;
  if (!simtype) {                       /* must be all simtypes */
    if (cmd.is_end()) {                 /* list all */
      probes[s_TRAN].listing("tran");
      probes[s_AC].listing("ac");
      probes[s_DC].listing("dc");
      probes[s_OP].listing("op");
      probes[s_FOURIER].listing("fourier");
    }else if (cmd.umatch("clear ")) {           /* clear all */
      for (int ii = sSTART;  ii < sCOUNT;  ++ii) {
        probes[ii].clear();
      }
    }else{itested();                            /* error */
      throw Exception_CS("what's this?", cmd);
    }
  }else{
    if (cmd.is_end()) {untested();              /* list */
      probes[simtype].listing("");
    }else if (cmd.umatch("clear ")) {untested();/* clear */
      probes[simtype].clear();
    }else{                                      /* add/remove */
      CKT_BASE::_sim->init();
      if (cmd.match1('-')) {itested();          /* setup cases like: */
        action = aDELETE;                       /* .probe ac + ....  */
        cmd.skip();
      }else if (cmd.match1('+')) {
        action = aADD;
        cmd.skip();
      }else{
      }
      if (action == aNEW) {                     /* no +/- here or at beg. */
        probes[simtype].clear();                /* means clear first      */
        action = aADD;
      }else{
      }
      while (cmd.more()) {                      /* do-it */
        if (cmd.match1('-')) {                  /* handle cases like:       */
          action = aDELETE;                     /* .pr ac +v(7) -e(6) +r(8) */
          cmd.skip();
        }else if (cmd.match1('+')) {itested();
          action = aADD;
          cmd.skip();
        }else{
        }
        if (action == aDELETE) {
          probes[simtype].remove_list(cmd);
        }else{
          probes[simtype].add_list(cmd);
        }
      }
    }
  }
}
Variable Documentation
DISPATCHER< CMD >::INSTALL d3 & anonymous_namespace{c_prbcmd.cc}::command_dispatcher
Definition at line 118 of file c_prbcmd.cc.
anonymous_namespace{c_prbcmd.cc}::CMD_STORE anonymous_namespace{c_prbcmd.cc}::p0
anonymous_namespace{c_prbcmd.cc}::CMD_ALARM anonymous_namespace{c_prbcmd.cc}::p1
anonymous_namespace{c_prbcmd.cc}::CMD_PLOT anonymous_namespace{c_prbcmd.cc}::p2
anonymous_namespace{c_prbcmd.cc}::CMD_PRINT anonymous_namespace{c_prbcmd.cc}::p3