gnucap: NODE_MAP Class Reference
NODE_MAP Class Reference
#include <u_nodemap.h>
Public Types
typedef std::map< const
std::string, NODE * >
::iterator iterator
typedef std::map< const
std::string, NODE * >
::const_iterator const_iterator
Public Member Functions
NODE_MAP ()
~NODE_MAP ()
NODE * operator[] (std::string)
NODE * new_node (std::string)
const_iterator begin () const
const_iterator end () const
int how_many () const
Private Member Functions
NODE_MAP (const NODE_MAP &)
Private Attributes
std::map< const std::string,
NODE * > _node_map
Detailed Description
Definition at line 31 of file u_nodemap.h.
Member Typedef Documentation
typedef std::map<const std::string, NODE*>::const_iterator NODE_MAP::const_iterator
Definition at line 43 of file u_nodemap.h.
typedef std::map<const std::string, NODE*>::iterator NODE_MAP::iterator
Definition at line 42 of file u_nodemap.h.
Constructor & Destructor Documentation
NODE_MAP::NODE_MAP (const NODE_MAP & p) [explicit, private]
Definition at line 40 of file u_nodemap.cc.
References _node_map, NODE, unreachable, and untested.
  : _node_map(p._node_map)
{
  unreachable();
  for (iterator i = _node_map.begin(); i != _node_map.end(); ++i) {
    untested();
    if (i->first != "0") {
      untested();
      assert(i->second);
      i->second = new NODE(i->second);
    }else{
      untested();
    }
  }
}
NODE_MAP::NODE_MAP () [explicit]
Definition at line 30 of file u_nodemap.cc.
References _node_map, and ground_node.
  : _node_map()
{
  _node_map["0"] = &ground_node;
}
NODE_MAP::~NODE_MAP ()
Definition at line 56 of file u_nodemap.cc.
References _node_map.
{
  for (iterator i = _node_map.begin(); i != _node_map.end(); ++i) {
    if (i->first != "0") {
      assert(i->second);
      delete i->second;
    }
  }
}
Member Function Documentation
const_iterator NODE_MAP::begin () const [inline]
Definition at line 45 of file u_nodemap.h.
References _node_map.
Referenced by PROBELIST::add_branches().
{return _node_map.begin();}
const_iterator NODE_MAP::end () const [inline]
Definition at line 46 of file u_nodemap.h.
References _node_map.
Referenced by PROBELIST::add_all_nodes(), and PROBELIST::add_branches().
{return _node_map.end();}
int NODE_MAP::how_many () const [inline]
Definition at line 47 of file u_nodemap.h.
References _node_map.
Referenced by CARD_LIST::map_subckt_nodes(), and new_node().
{return static_cast<int>(_node_map.size()-1);}
NODE * NODE_MAP::new_node (std::string s)
Definition at line 86 of file u_nodemap.cc.
References _node_map, OPT::case_insensitive, how_many(), NODE, and notstd::to_lower().
Referenced by node_t::new_node().
{
  if (OPT::case_insensitive) {
    notstd::to_lower(&s);
  }else{
  }
  NODE* node = _node_map[s];
  // increments how_many() when lookup fails (new s)
  if (!node) {
    node = new NODE(s, how_many());
    //                 ^^^^ is really the map number of the new node
    _node_map[s] = node;
  }
  assert(node);
  return node;
}
NODE * NODE_MAP::operator[] (std::string s)
Definition at line 69 of file u_nodemap.cc.
References _node_map, OPT::case_insensitive, and notstd::to_lower().
{
  const_iterator i = _node_map.find(s);
  if (i != _node_map.end()) {
    return i->second;
  }else if (OPT::case_insensitive) {
    notstd::to_lower(&s);
    i = _node_map.find(s);
  }else{
    return NULL;
  }
  return (i != _node_map.end()) ? i->second : NULL;
}
Member Data Documentation
std::map<const std::string, NODE*> NODE_MAP::_node_map [private]
Definition at line 33 of file u_nodemap.h.
Referenced by begin(), end(), how_many(), new_node(), NODE_MAP(), operator[](), and ~NODE_MAP().
The documentation for this class was generated from the following files:
savant/gnucap/src/u_nodemap.h
savant/gnucap/src/u_nodemap.cc