gnucap: anonymous_namespace{lang_verilog.cc}::LANG_VERILOG Class Reference
anonymous_namespace{lang_verilog.cc}::LANG_VERILOG Class Reference
Public Member Functions
LANG_VERILOG ()
std::string name () const
bool case_insensitive () const
UNITS units () const
std::string arg_front () const
std::string arg_mid () const
std::string arg_back () const
void parse_top_item (CS &, CARD_LIST *)
DEV_COMMENT * parse_comment (CS &, DEV_COMMENT *)
DEV_DOT * parse_command (CS &, DEV_DOT *)
MODEL_CARD * parse_paramset (CS &, MODEL_CARD *)
MODEL_SUBCKT * parse_module (CS &, MODEL_SUBCKT *)
COMPONENT * parse_instance (CS &, COMPONENT *)
std::string find_type_in_string (CS &)
Private Types
enum MODE { mDEFAULT, mPARAMSET }
enum { INACTIVE = -1 }
Private Member Functions
void print_paramset (OMSTREAM &, const MODEL_CARD *)
void print_module (OMSTREAM &, const MODEL_SUBCKT *)
void print_instance (OMSTREAM &, const COMPONENT *)
void print_comment (OMSTREAM &, const DEV_COMMENT *)
void print_command (OMSTREAM &o, const DEV_DOT *c)
void print_args (OMSTREAM &, const MODEL_CARD *)
void print_args (OMSTREAM &, const COMPONENT *)
Private Attributes
enum anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::MODE _mode
int arg_count
Detailed Description
Definition at line 31 of file lang_verilog.cc.
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
INACTIVE
Definition at line 34 of file lang_verilog.cc.
{INACTIVE = -1};
enum anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::MODE [private]
Enumerator:
mDEFAULT
mPARAMSET
Definition at line 32 of file lang_verilog.cc.
{mDEFAULT, mPARAMSET} _mode;
Constructor & Destructor Documentation
anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::LANG_VERILOG () [inline]
Definition at line 36 of file lang_verilog.cc.
: arg_count(INACTIVE) {}
Member Function Documentation
std::string anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::arg_back () const [inline, virtual]
Implements LANGUAGE.
Definition at line 58 of file lang_verilog.cc.
References unreachable.
{
    switch (_mode) {
    case mPARAMSET: return ";"; break;
    case mDEFAULT:  return ")"; break;
    }
    unreachable();
    return "";
  }
std::string anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::arg_front () const [inline, virtual]
Implements LANGUAGE.
Definition at line 42 of file lang_verilog.cc.
References unreachable.
{
    switch (_mode) {
    case mPARAMSET: return " .";                            break;
    case mDEFAULT:  return (arg_count++ > 0) ? ", ." : "."; break;
    }
    unreachable();
    return "";
  }
std::string anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::arg_mid () const [inline, virtual]
Implements LANGUAGE.
Definition at line 50 of file lang_verilog.cc.
References unreachable.
{
    switch (_mode) {
    case mPARAMSET: return "="; break;
    case mDEFAULT:  return "("; break;
    }
    unreachable();
    return "";
  }
bool anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::case_insensitive () const [inline, virtual]
Implements LANGUAGE.
Definition at line 38 of file lang_verilog.cc.
{return false;}
std::string anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::find_type_in_string (CS & cmd) [virtual]
Implements LANGUAGE.
Definition at line 282 of file lang_verilog.cc.
References CS::cursor(), and CS::reset().
{
  unsigned here = cmd.cursor();
  std::string type;
  if ((cmd >> "//")) {
    assert(here == 0);
    type = "dev_comment";
  }else{
    cmd >> type;
  }
  cmd.reset(here);
  return type;
}
std::string anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::name () const [inline, virtual]
Implements LANGUAGE.
Definition at line 37 of file lang_verilog.cc.
{return "verilog";}
DEV_DOT * anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_command (CS & cmd, DEV_DOT * x) [virtual]
Implements LANGUAGE.
Definition at line 205 of file lang_verilog.cc.
References CARD_LIST::card_list, CMD::cmdproc(), CS::fullstring(), CARD::owner(), CS::reset(), DEV_DOT::set(), and CARD::subckt().
{
  assert(x);
  x->set(cmd.fullstring());
  CARD_LIST* scope = (x->owner()) ? x->owner()->subckt() : &CARD_LIST::card_list;
  cmd.reset();
  CMD::cmdproc(cmd, scope);
  delete x;
  return NULL;
}
DEV_COMMENT * anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_comment (CS & cmd, DEV_COMMENT * x) [virtual]
Implements LANGUAGE.
Definition at line 198 of file lang_verilog.cc.
References CS::fullstring(), and DEV_COMMENT::set().
{
  assert(x);
  x->set(cmd.fullstring());
  return x;
}
COMPONENT * anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_instance (CS & cmd, COMPONENT * x) [virtual]
Implements LANGUAGE.
Definition at line 270 of file lang_verilog.cc.
References CS::check(), anonymous_namespace{lang_verilog.cc}::parse_args_instance(), anonymous_namespace{lang_gschem.cc}::parse_label(), anonymous_namespace{lang_spectre.cc}::parse_ports(), anonymous_namespace{lang_gschem.cc}::parse_type(), and CS::reset().
{
  cmd.reset();
  parse_type(cmd, x);
  parse_args_instance(cmd, x);
  parse_label(cmd, x);
  parse_ports(cmd, x);
  cmd >> ';';
  cmd.check(bWARNING, "what's this?");
  return x;
}
MODEL_SUBCKT * anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_module (CS & cmd, MODEL_SUBCKT * x) [virtual]
Implements LANGUAGE.
Definition at line 246 of file lang_verilog.cc.
References CS::get_line(), anonymous_namespace{lang_gschem.cc}::parse_label(), anonymous_namespace{lang_spectre.cc}::parse_ports(), CS::reset(), and CARD::subckt().
Referenced by anonymous_namespace{lang_verilog.cc}::CMD_MODULE::do_it().
{
  assert(x);
  // header
  cmd.reset();
  (cmd >> "module |macromodule ");
  parse_label(cmd, x);
  parse_ports(cmd, x);
  cmd >> ';';
  // body
  for (;;) {
    cmd.get_line("verilog-module>");
    if (cmd >> "endmodule ") {
      break;
    }else{
      new__instance(cmd, x, x->subckt());
    }
  }
  return x;
}
MODEL_CARD * anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_paramset (CS & cmd, MODEL_CARD * x) [virtual]
Implements LANGUAGE.
Definition at line 225 of file lang_verilog.cc.
References CS::check(), anonymous_namespace{lang_verilog.cc}::parse_args_paramset(), anonymous_namespace{lang_gschem.cc}::parse_label(), anonymous_namespace{lang_gschem.cc}::parse_type(), and CS::reset().
Referenced by anonymous_namespace{lang_verilog.cc}::CMD_PARAMSET::do_it().
{
  assert(x);
  cmd.reset();
  cmd >> "paramset ";
  parse_label(cmd, x);
  parse_type(cmd, x);
  cmd >> ';';
  parse_args_paramset(cmd, x);
  cmd >> "endparamset ";
  cmd.check(bWARNING, "what's this?");
  return x;
}
void anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_top_item (CS & cmd, CARD_LIST * Scope) [virtual]
Reimplemented from LANGUAGE.
Definition at line 296 of file lang_verilog.cc.
References CS::get_line().
{
  cmd.get_line("gnucap-verilog>");
  new__instance(cmd, NULL, Scope);
}
void anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_args (OMSTREAM & o, const MODEL_CARD * x) [private]
Definition at line 303 of file lang_verilog.cc.
References MODEL_CARD::param_count(), MODEL_CARD::param_is_printable(), MODEL_CARD::param_name(), MODEL_CARD::param_value(), CARD::print_args_obsolete_callback(), and CARD::use_obsolete_callback_print().
{
  assert(x);
  if (x->use_obsolete_callback_print()) {
    x->print_args_obsolete_callback(o, this);  //BUG//callback//
  }else{
    for (int ii = x->param_count() - 1;  ii >= 0;  --ii) {
      if (x->param_is_printable(ii)) {
        std::string arg = " ." + x->param_name(ii) + "=" + x->param_value(ii) + ";";
        o << arg;
      }else{
      }
    }
  }
}
void anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_args (OMSTREAM & o, const COMPONENT * x) [private]
Definition at line 319 of file lang_verilog.cc.
References COMPONENT::param_count(), COMPONENT::param_is_printable(), COMPONENT::param_name(), COMPONENT::param_value(), COMPONENT::print_args_obsolete_callback(), and COMPONENT::use_obsolete_callback_print().
{
  assert(x);
  o << " #(";
  if (x->use_obsolete_callback_print()) {
    arg_count = 0;
    x->print_args_obsolete_callback(o, this);  //BUG//callback//
    arg_count = INACTIVE;
  }else{
    std::string sep = ".";
    for (int ii = x->param_count() - 1;  ii >= 0;  --ii) {
      if (x->param_is_printable(ii)) {
        o << sep << x->param_name(ii) << "(" << x->param_value(ii) << ")";
        sep = ",.";
      }else{
      }
    }
  }
  o << ") ";
}
void anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_command (OMSTREAM & o, const DEV_DOT * c) [private, virtual]
Implements LANGUAGE.
Definition at line 432 of file lang_verilog.cc.
References DEV_DOT::s().
{
  assert(x);
  o << x->s() << '\n';
}
void anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_comment (OMSTREAM & o, const DEV_COMMENT * x) [private, virtual]
Implements LANGUAGE.
Definition at line 426 of file lang_verilog.cc.
References DEV_COMMENT::comment().
{
  assert(x);
  o << x->comment() << '\n';
}
void anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_instance (OMSTREAM & o, const COMPONENT * x) [private, virtual]
Implements LANGUAGE.
Definition at line 417 of file lang_verilog.cc.
References anonymous_namespace{lang_spectre.cc}::print_label(), anonymous_namespace{lang_verilog.cc}::print_ports_long(), and anonymous_namespace{lang_spectre.cc}::print_type().
{
  print_type(o, x);
  print_args(o, x);
  print_label(o, x);
  print_ports_long(o, x);
  o << ";\n";
}
void anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_module (OMSTREAM & o, const MODEL_SUBCKT * x) [private, virtual]
Implements LANGUAGE.
Definition at line 400 of file lang_verilog.cc.
References CARD_LIST::begin(), CARD_LIST::end(), anonymous_namespace{lang_verilog.cc}::print_ports_short(), CKT_BASE::short_label(), and CARD::subckt().
{
  assert(x);
  assert(x->subckt());
  o << "module " <<  x->short_label();
  print_ports_short(o, x);
  o << ";\n";
  for (CARD_LIST::const_iterator
         ci = x->subckt()->begin(); ci != x->subckt()->end(); ++ci) {
    print_item(o, *ci);
  }
  o << "endmodule // " << x->short_label() << "\n\n";
}
void anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_paramset (OMSTREAM & o, const MODEL_CARD * x) [private, virtual]
Implements LANGUAGE.
Definition at line 389 of file lang_verilog.cc.
References CARD::dev_type(), and CKT_BASE::short_label().
{
  assert(x);
  _mode = mPARAMSET;
  o << "paramset " << x->short_label() << ' ' << x->dev_type() << ";\\\n";
  print_args(o, x);
  o << "\\\n"
    "endparmset\n\n";
  _mode = mDEFAULT;
}
UNITS anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::units () const [inline, virtual]
Implements LANGUAGE.
Definition at line 39 of file lang_verilog.cc.
References uSI.
{return uSI;}
Member Data Documentation
enum anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::MODE anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::_mode [private]
int anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::arg_count [mutable, private]
Definition at line 33 of file lang_verilog.cc.
The documentation for this class was generated from the following file:
savant/gnucap/src/lang_verilog.cc