gnucap: MODEL_BUILT_IN_MOS1 Class Reference
MODEL_BUILT_IN_MOS1 Class Reference
#include <d_mos1.h>
Public Member Functions
MODEL_BUILT_IN_MOS1 (const BASE_SUBCKT *)
~MODEL_BUILT_IN_MOS1 ()
std::string dev_type () const
void set_dev_type (const std::string &nt)
CARD * clone () const
void precalc_first ()
void precalc_last ()
SDP_CARD * new_sdp (COMMON_COMPONENT *c) const
void set_param_by_index (int, std::string &, int)
bool param_is_printable (int) const
std::string param_name (int) const
std::string param_name (int, int) const
std::string param_value (int) const
int param_count () const
bool is_valid (const COMPONENT *) const
void tr_eval (COMPONENT *) const
Static Public Member Functions
static int count ()
Public Attributes
PARAMETER< double > kp
bool calc_kp
Protected Member Functions
MODEL_BUILT_IN_MOS1 (const MODEL_BUILT_IN_MOS1 &p)
Static Private Attributes
static int _count = 0
Detailed Description
Definition at line 54 of file d_mos1.h.
Constructor & Destructor Documentation
MODEL_BUILT_IN_MOS1::MODEL_BUILT_IN_MOS1 (const MODEL_BUILT_IN_MOS1 & p) [explicit, protected]
Definition at line 100 of file d_mos1.cc.
References _count, rPRE_MAIN, ENV::run_mode, and untested.
Referenced by clone().
  :MODEL_BUILT_IN_MOS123(p),
   kp(p.kp),
   calc_kp(p.calc_kp)
{
  if (ENV::run_mode != rPRE_MAIN) {
    ++_count;
  }else{untested();//194
  }
}
MODEL_BUILT_IN_MOS1::MODEL_BUILT_IN_MOS1 (const BASE_SUBCKT * p) [explicit]
Definition at line 83 of file d_mos1.cc.
References _count, MODEL_BUILT_IN_MOS123::cox, MODEL_BUILT_IN_MOS123::gamma, LEVEL(), MODEL_BUILT_IN_DIODE::mjsw, MODEL_BUILT_IN_DIODE::mos_level, NA(), MODEL_BUILT_IN_MOS123::phi, rPRE_MAIN, ENV::run_mode, set_default(), and MODEL_BUILT_IN_MOS123::vto.
  :MODEL_BUILT_IN_MOS123(p),
   kp(NA),
   calc_kp(false)
{
  if (ENV::run_mode != rPRE_MAIN) {
    ++_count;
  }else{
  }
  set_default(&mjsw, .5);
  set_default(&cox, NA);
  set_default(&vto, NA);
  set_default(&gamma, NA);
  set_default(&phi, NA);
  set_default(&mos_level, LEVEL);
}
MODEL_BUILT_IN_MOS1::~MODEL_BUILT_IN_MOS1 () [inline]
Definition at line 60 of file d_mos1.h.
References _count.
{--_count;}
Member Function Documentation
CARD* MODEL_BUILT_IN_MOS1::clone () const [inline, virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 64 of file d_mos1.h.
References MODEL_BUILT_IN_MOS1().
{return new MODEL_BUILT_IN_MOS1(*this);}
static int MODEL_BUILT_IN_MOS1::count () [inline, static]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 77 of file d_mos1.h.
References _count.
{return _count;}
std::string MODEL_BUILT_IN_MOS1::dev_type () const [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 111 of file d_mos1.cc.
References pN, MODEL_BUILT_IN_MOS_BASE::polarity, pP, and untested.
{
  if (polarity == pN) {
    return "nmos1";
  }else if (polarity == pP) {
    return "pmos1";
  }else if (polarity == pN) {
    return "nmos";
  }else if (polarity == pP) {
    return "pmos";
  }else{untested();//235
    return MODEL_BUILT_IN_MOS123::dev_type();
  }
}
bool MODEL_BUILT_IN_MOS1::is_valid (const COMPONENT * d) const [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 311 of file d_mos1.cc.
{
  assert(d);
  return MODEL_BUILT_IN_MOS123::is_valid(d);
}
SDP_CARD * MODEL_BUILT_IN_MOS1::new_sdp (COMMON_COMPONENT * c) const [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 212 of file d_mos1.cc.
{
  assert(c);
  if (COMMON_BUILT_IN_MOS* cc = dynamic_cast<COMMON_BUILT_IN_MOS*>(c)) {
    if (cc->_sdp) {
      cc->_sdp->init(cc);
      return cc->_sdp;
    }else{
      delete cc->_sdp;
      return new SDP_BUILT_IN_MOS1(c);
    }
  }else{
    return MODEL_BUILT_IN_MOS123::new_sdp(c);
  }
}
int MODEL_BUILT_IN_MOS1::param_count () const [inline, virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 73 of file d_mos1.h.
References MODEL_BUILT_IN_MOS123::param_count().
Referenced by param_is_printable(), param_name(), param_value(), and set_param_by_index().
{return (8 + MODEL_BUILT_IN_MOS123::param_count());}
bool MODEL_BUILT_IN_MOS1::param_is_printable (int i) const [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 243 of file d_mos1.cc.
References calc_kp, LEVEL(), MODEL_BUILT_IN_DIODE::mos_level, and param_count().
{
  switch (MODEL_BUILT_IN_MOS1::param_count() - 1 - i) {
  case 0:  return (true);
  case 1:  return (false);
  case 2:  return (false);
  case 3:  return (false);
  case 4:  return (false);
  case 5:  return (false);
  case 6:  return (mos_level != LEVEL);
  case 7:  return (!calc_kp);
  default: return MODEL_BUILT_IN_MOS123::param_is_printable(i);
  }
}
std::string MODEL_BUILT_IN_MOS1::param_name (int i) const [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 258 of file d_mos1.cc.
References param_count().
Referenced by param_name().
{
  switch (MODEL_BUILT_IN_MOS1::param_count() - 1 - i) {
  case 0:  return "level";
  case 1:  return "=====";
  case 2:  return "=====";
  case 3:  return "=====";
  case 4:  return "=====";
  case 5:  return "=====";
  case 6:  return "diodelevel";
  case 7:  return "kp";
  default: return MODEL_BUILT_IN_MOS123::param_name(i);
  }
}
std::string MODEL_BUILT_IN_MOS1::param_name (int i, int j) const [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 273 of file d_mos1.cc.
References param_count(), and param_name().
{
  if (j == 0) {
    return param_name(i);
  }else if (j == 1) {
    switch (MODEL_BUILT_IN_MOS1::param_count() - 1 - i) {
    case 0:  return "";
    case 1:  return "";
    case 2:  return "";
    case 3:  return "";
    case 4:  return "";
    case 5:  return "";
    case 6:  return "";
    case 7:  return "";
    default: return MODEL_BUILT_IN_MOS123::param_name(i, j);
    }
  }else if (i < 8) {
    return "";
  }else{
    return MODEL_BUILT_IN_MOS123::param_name(i, j);
  }
}
std::string MODEL_BUILT_IN_MOS1::param_value (int i) const [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 296 of file d_mos1.cc.
References kp, MODEL_BUILT_IN_DIODE::mos_level, param_count(), PARAMETER< T >::string(), and unreachable.
{
  switch (MODEL_BUILT_IN_MOS1::param_count() - 1 - i) {
  case 0:  return "1";
  case 1:  unreachable(); return "";
  case 2:  unreachable(); return "";
  case 3:  unreachable(); return "";
  case 4:  unreachable(); return "";
  case 5:  unreachable(); return "";
  case 6:  return mos_level.string();
  case 7:  return kp.string();
  default: return MODEL_BUILT_IN_MOS123::param_value(i);
  }
}
void MODEL_BUILT_IN_MOS1::precalc_first () [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 141 of file d_mos1.cc.
References CKT_BASE::_sim, MODEL_BUILT_IN_MOS123::calc_gamma, calc_kp, MODEL_BUILT_IN_MOS123::calc_phi, MODEL_BUILT_IN_MOS123::calc_vto, MODEL_BUILT_IN_MOS123::cox, e_val(), MODEL_BUILT_IN_MOS_BASE::egap, error(), MODEL_BUILT_IN_MOS123::gamma, gtMETAL, SIM_DATA::is_first_expand(), kp, CARD::long_label(), NA(), NI, MODEL_BUILT_IN_MOS123::nss, MODEL_BUILT_IN_MOS123::nsub, P_EPS_OX, P_EPS_SI, P_K_Q, P_Q, MODEL_BUILT_IN_MOS123::phi, MODEL_BUILT_IN_MOS_BASE::polarity, CARD::scope(), MODEL_BUILT_IN_MOS_BASE::tnom_k, MODEL_BUILT_IN_MOS123::tox, MODEL_BUILT_IN_MOS123::tpg, untested, MODEL_BUILT_IN_MOS123::uo, and MODEL_BUILT_IN_MOS123::vto.
{
    const CARD_LIST* par_scope = scope();
    assert(par_scope);
    MODEL_BUILT_IN_MOS123::precalc_first();
    e_val(&(this->kp), NA, par_scope);
    // final adjust: code_pre
      if (tox != NA) {
        cox = P_EPS_OX / tox;
        if (kp == NA) {
          kp = uo * cox;
          calc_kp = true;
        }
        if (nsub != NA) {
          if (phi == NA) {
            phi = (2. * P_K_Q) * tnom_k * log(nsub/NI);
            if (phi < .1) {
              untested();
              error(((!_sim->is_first_expand()) ? (bDEBUG) : (bWARNING)),
                    long_label() + ": calculated phi too small, using .1\n");
              phi = .1;
            }
            calc_phi = true;
          }
          if (gamma == NA) {
            gamma = sqrt(2. * P_EPS_SI * P_Q * nsub) / cox;
            calc_gamma = true;
          }
          if (vto == NA) {
            double phi_ms = (tpg == gtMETAL)
              ? polarity * (-.05 - (egap + polarity * phi) / 2.)
              : -(tpg * egap + phi) / 2.;
            double vfb = phi_ms - polarity * P_Q * nss / cox;
            vto = vfb + phi + gamma * sqrt(phi);
            calc_vto = true;
          }
        }else{
          // tox is input, nsub isn't
        }
      }
    // final adjust: override
    if (cox == NA) {
      cox = 0.;
    }else{
    }
    if (vto == NA) {
      vto = 0.;
    }else{
    }
    if (gamma == NA) {
      gamma = 0.;
    }else{
    }
    if (phi == NA) {
      phi = .6;
    }else{
    }
    // final adjust: raw
    e_val(&(this->kp), 2e-5, par_scope);
    // final adjust: mid
    // final adjust: calculated
    // final adjust: post
    // final adjust: done
}
void MODEL_BUILT_IN_MOS1::precalc_last () [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 207 of file d_mos1.cc.
{
    MODEL_BUILT_IN_MOS123::precalc_last();
}
void MODEL_BUILT_IN_MOS1::set_dev_type (const std::string & nt) [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 126 of file d_mos1.cc.
References pN, MODEL_BUILT_IN_MOS_BASE::polarity, pP, and Umatch().
{
  if (Umatch(new_type, "nmos1 ")) {
    polarity = pN;
  }else if (Umatch(new_type, "pmos1 ")) {
    polarity = pP;
  }else if (Umatch(new_type, "nmos ")) {
    polarity = pN;
  }else if (Umatch(new_type, "pmos ")) {
    polarity = pP;
  }else{
    MODEL_BUILT_IN_MOS123::set_dev_type(new_type);
  }
}
void MODEL_BUILT_IN_MOS1::set_param_by_index (int i, std::string & value, int offset) [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 228 of file d_mos1.cc.
References kp, MODEL_BUILT_IN_MOS_BASE::level, MODEL_BUILT_IN_DIODE::mos_level, param_count(), and unreachable.
{
  switch (MODEL_BUILT_IN_MOS1::param_count() - 1 - i) {
  case 0: level = value; break; //1
  case 1: unreachable(); break;
  case 2: unreachable(); break;
  case 3: unreachable(); break;
  case 4: unreachable(); break;
  case 5: unreachable(); break;
  case 6: mos_level = value; break;
  case 7: kp = value; break;
  default: MODEL_BUILT_IN_MOS123::set_param_by_index(i, value, offset); break;
  }
}
void MODEL_BUILT_IN_MOS1::tr_eval (COMPONENT * brh) const [virtual]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 317 of file d_mos1.cc.
References TDP_BUILT_IN_MOS1::beta, COMPONENT::common(), DEV_BUILT_IN_MOS::cutoff, TDP_BUILT_IN_MOS1::egap, MODEL_BUILT_IN_MOS_BASE::egap, MODEL_BUILT_IN_MOS123::gamma, DEV_BUILT_IN_MOS::gds, DEV_BUILT_IN_MOS::gmbf, DEV_BUILT_IN_MOS::gmbr, DEV_BUILT_IN_MOS::gmf, DEV_BUILT_IN_MOS::gmr, DEV_BUILT_IN_MOS::ids, MODEL_BUILT_IN_MOS123::lambda, CARD::long_label(), NA(), TDP_BUILT_IN_MOS1::phi, MODEL_BUILT_IN_MOS123::phi, prechecked_cast, DEV_BUILT_IN_MOS::reverse_if_needed(), DEV_BUILT_IN_MOS::reversed, DEV_BUILT_IN_MOS::saturated, DEV_BUILT_IN_MOS::sbfwd, COMMON_BUILT_IN_MOS::sdp(), TDP_BUILT_IN_MOS1::sqrt_phi, trace0, trace2, trace3, trace4, untested, DEV_BUILT_IN_MOS::vbs, DEV_BUILT_IN_MOS::vds, DEV_BUILT_IN_MOS::vdsat, DEV_BUILT_IN_MOS::vgs, DEV_BUILT_IN_MOS::vgst, DEV_BUILT_IN_MOS::von, and MODEL_BUILT_IN_MOS123::vto.
{
  DEV_BUILT_IN_MOS* d = prechecked_cast<DEV_BUILT_IN_MOS*>(brh);
  assert(d);
  const COMMON_BUILT_IN_MOS* c = prechecked_cast<const COMMON_BUILT_IN_MOS*>(d->common());
  assert(c);
  const SDP_BUILT_IN_MOS1* s = prechecked_cast<const SDP_BUILT_IN_MOS1*>(c->sdp());
  assert(s);
  const MODEL_BUILT_IN_MOS1* m = this;
  const TDP_BUILT_IN_MOS1 T(d);
  const TDP_BUILT_IN_MOS1* t = &T;
    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */
    trace0(d->long_label().c_str());
    trace3("", d->vds, d->vgs, d->vbs);
    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */
    d->reverse_if_needed();
    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */
    double sarg, dsarg_dvbs;
    {
      if (d->vbs <= 0.) {
        sarg = sqrt(t->phi - d->vbs);
        dsarg_dvbs = -.5 / sarg;
        d->sbfwd = false;
        trace2("sb-ok", sarg, dsarg_dvbs);
      }else{
        untested();
        sarg = t->sqrt_phi / (1. + .5 * d->vbs / t->phi);
        dsarg_dvbs = -.5 * sarg * sarg / t->phi*t->sqrt_phi; /* is wrong!! */
        d->sbfwd = true;
        trace2("***sb-reversed***", sarg, dsarg_dvbs);
      }
    }
    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */
    d->von = m->vto + m->gamma * (sarg - sqrt(m->phi))
      + .5 * (m->egap - t->egap) + .5 * (t->phi - m->phi);
    d->vgst = d->vdsat = d->vgs - d->von;
    if (d->vdsat < 0.) {
      d->vdsat = 0.;
    }
    d->cutoff = (d->vgst < 0.);
    d->saturated = (d->vds > d->vdsat);
    trace3("", d->von, d->vgst, d->vdsat);
    double Lambda = (m->lambda != NA) ? m->lambda : 0.;
    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */
    if (d->cutoff) {
      d->gds = d->gmf = d->ids = d->gmbf = 0.;
      trace4("cut", d->ids, d->gmf, d->gds, d->gmbf);
    }else if (d->saturated) {
      d->gmf  = t->beta * d->vgst * (1. + Lambda * d->vds);
      d->ids = d->gmf * (.5 * d->vgst);
      d->gds = .5 * t->beta * Lambda * d->vgst * d->vgst;
      d->gmbf = - d->gmf * m->gamma * dsarg_dvbs;
      trace4("sat", d->ids, d->gmf, d->gds, d->gmbf);
    }else{ /* triode */
      d->gmf  = t->beta * d->vds * (1. + Lambda * d->vds);
      d->ids = d->gmf * (d->vgst - .5*d->vds);
      d->gds = t->beta * ((d->vgst - d->vds)
                         + Lambda * d->vds * (2.*d->vgst - 1.5*d->vds));
      d->gmbf = -d->gmf * m->gamma * dsarg_dvbs;
      trace4("lin", d->ids, d->gmf, d->gds, d->gmbf);
    }
    if (d->reversed) {
      d->ids *= -1;
      d->gmr = d->gmf;
      d->gmbr = d->gmbf;
      d->gmf = d->gmbf = 0;
    }else{
      d->gmr = d->gmbr = 0.;
    }
}
Member Data Documentation
int MODEL_BUILT_IN_MOS1::_count = 0 [static, private]
Reimplemented from MODEL_BUILT_IN_MOS123.
Definition at line 79 of file d_mos1.h.
Referenced by count(), MODEL_BUILT_IN_MOS1(), and ~MODEL_BUILT_IN_MOS1().
bool MODEL_BUILT_IN_MOS1::calc_kp
Definition at line 83 of file d_mos1.h.
Referenced by param_is_printable(), and precalc_first().
PARAMETER<double> MODEL_BUILT_IN_MOS1::kp
Definition at line 81 of file d_mos1.h.
Referenced by param_value(), precalc_first(), set_param_by_index(), and TDP_BUILT_IN_MOS1::TDP_BUILT_IN_MOS1().
The documentation for this class was generated from the following files:
savant/gnucap/src/d_mos1.h
savant/gnucap/src/d_mos1.cc