gnucap: DEV_DOT Class Reference
DEV_DOT Class Reference
#include <d_dot.h>
Public Member Functions
DEV_DOT ()
void set (const std::string &S)
const std::string & s () const
Private Member Functions
DEV_DOT (const DEV_DOT &p)
std::string value_name () const
char id_letter () const
std::string dev_type () const
CARD * clone () const
Private Attributes
std::string _s
Detailed Description
Definition at line 27 of file d_dot.h.
Constructor & Destructor Documentation
DEV_DOT::DEV_DOT (const DEV_DOT & p) [inline, explicit, private]
Definition at line 30 of file d_dot.h.
References CARD::set_constant().
:CARD(p) {set_constant(true);}
DEV_DOT::DEV_DOT () [inline, explicit]
Definition at line 32 of file d_dot.h.
References CARD::set_constant().
Referenced by clone().
:CARD() {set_constant(true);}
Member Function Documentation
CARD* DEV_DOT::clone () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 37 of file d_dot.h.
References DEV_DOT().
{return new DEV_DOT(*this);}
std::string DEV_DOT::dev_type () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 36 of file d_dot.h.
References untested.
{untested();return "dotcard";}
char DEV_DOT::id_letter () const [inline, private, virtual]
Reimplemented from CARD.
Definition at line 35 of file d_dot.h.
References untested.
{untested();return '\0';}
const std::string& DEV_DOT::s () const [inline]
Definition at line 40 of file d_dot.h.
References _s.
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::print_command(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::print_command(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::print_command(), and anonymous_namespace{lang_geda.cc}::LANG_GEDA::print_command().
{return _s;}
void DEV_DOT::set (const std::string & S) [inline]
Definition at line 39 of file d_dot.h.
References _s.
Referenced by anonymous_namespace{lang_spectre.cc}::LANG_SPECTRE::parse_command(), anonymous_namespace{lang_spice.cc}::LANG_SPICE_BASE::parse_command(), anonymous_namespace{lang_geda.cc}::LANG_GEDA::parse_command(), and anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_command().
{_s = S;}
std::string DEV_DOT::value_name () const [inline, private, virtual]
Implements CARD.
Definition at line 34 of file d_dot.h.
{return "";}
Member Data Documentation
std::string DEV_DOT::_s [private]
Definition at line 29 of file d_dot.h.
Referenced by s(), and set().
The documentation for this class was generated from the following file:
savant/gnucap/src/d_dot.h