gnucap: anonymous_namespace{c_delete.cc}::CMD_DELETE Class Reference
anonymous_namespace{c_delete.cc}::CMD_DELETE Class Reference
Private Member Functions
bool delete_one_name (const std::string &name, CARD_LIST *Scope) const
void do_it (CS &cmd, CARD_LIST *Scope)
Detailed Description
Definition at line 35 of file c_delete.cc.
Member Function Documentation
bool anonymous_namespace{c_delete.cc}::CMD_DELETE::delete_one_name (const std::string & name, CARD_LIST * Scope) const [inline, private]
Definition at line 37 of file c_delete.cc.
References CARD_LIST::begin(), CARD_LIST::end(), CARD_LIST::erase(), CARD_LIST::find_(), unreachable, and wmatch().
  {
    assert(Scope);
    std::string::size_type dotplace = name.find_first_of(".");
    if (dotplace != std::string::npos) {
      // has a dot, look deeper
      // Split the name into two parts:
      // "container" -- where to look (all following the dot)
      // "dev_name" -- what to look for (all before the dot)
      std::string dev_name  = name.substr(dotplace+1, std::string::npos);
      std::string container = name.substr(0, dotplace);
      // container name must be exact match
      CARD_LIST::iterator i = Scope->find_(container);
      if (i == Scope->end()) {
        // can't find "container" (probably .subckt) - no match
        // try reverse
        dotplace = name.find_last_of(".");
        container = name.substr(dotplace+1, std::string::npos);
        dev_name  = name.substr(0, dotplace);
        // container name must be exact match
        i = Scope->find_(container);
      }else{
      }
      if (i == Scope->end()) {
        // can't find "container" (probably .subckt) - no match
        return false;
      }else if (!dynamic_cast<MODEL_SUBCKT*>(*i)) {
        // found a match, but it isn't a container (subckt)
        return false;
      }else{
        // found the container, look inside
        return delete_one_name(dev_name, (**i).subckt());
      }
      unreachable();
    }else{
      // no dots, look here
      if (name.find_first_of("*?") != std::string::npos) {
        // there's a wild card.  do linear search for all matches
        bool didit = false;
        {
          CARD_LIST::iterator i = Scope->begin();
          while (i != Scope->end()) {
            CARD_LIST::iterator old_i = i++;
            // ^^^^^^^^^^^^ move i past the item being deleted
            if (wmatch((**old_i).short_label(), name)) {
              Scope->erase(old_i);
              didit = true;
            }
          }
        }
        return didit;
      }else{
        // no wild card.  fast search for one exact match
        CARD_LIST::iterator i = Scope->find_(name);
        if (i != Scope->end()) {
          Scope->erase(i);
          return true;
        }else{
          return false;
        }
      }
      unreachable();
    }
    unreachable();
    return false;
  }
void anonymous_namespace{c_delete.cc}::CMD_DELETE::do_it (CS & cmd, CARD_LIST * Scope) [inline, private, virtual]
Implements CMD.
Definition at line 105 of file c_delete.cc.
References CARD_LIST::card_list, CS::ctos(), CS::cursor(), CARD_LIST::erase_all(), CS::more(), CS::umatch(), and CS::warn().
  {
    if (cmd.umatch("all ")) {
      CARD_LIST::card_list.erase_all();
    }else{
      while (cmd.more()) {
        unsigned mark = cmd.cursor();
        bool didit = delete_one_name(cmd.ctos(), Scope);
        if (!didit) {
          cmd.warn(bWARNING, mark, "no match");
        }
      }
    }
  }
The documentation for this class was generated from the following file:
savant/gnucap/src/c_delete.cc