gnucap: MODEL_SPICE Class Reference
MODEL_SPICE Class Reference
Public Member Functions
MODEL_SPICE (const DEV_SPICE *p)
~MODEL_SPICE ()
MODEL_CARD * clone () const
bool is_valid (const COMPONENT *d) const IS_VALIDvoid precalc_first()
void set_dev_type (const std::string &nt)
std::string dev_type () const
bool param_is_printable (int) const
std::string param_name (int) const
std::string param_name (int i, int j) const
std::string param_value (int) const
void set_param_by_name (std::string Name, std::string Value)
void set_param_by_index (int, std::string &, int)
int param_count_dont_print () const
int param_count () const
void Set_param_by_name (std::string Name, std::string Value)
Static Public Member Functions
static int count ()
static CKTcircuit * ckt ()
static void init_ckt ()
Public Attributes
SPICE_MODEL_DATA _spice_model
std::string _key
std::string _level
PARAM_LIST _params
Protected Member Functions
MODEL_SPICE (const MODEL_SPICE &p)
Static Private Attributes
static int _count = -1
static CKTcircuit _ckt
Detailed Description
Definition at line 139 of file spice-wrapper.cc.
Constructor & Destructor Documentation
MODEL_SPICE::MODEL_SPICE (const MODEL_SPICE & p) [explicit, protected]
Definition at line 553 of file spice-wrapper.cc.
References assert_model_raw.
Referenced by clone().
  :MODEL_CARD(p),
   _spice_model(p._spice_model),
   _key(p._key),
   _level(p._level),
   _params(p._params)
{
  assert_model_raw();
}
MODEL_SPICE::MODEL_SPICE (const DEV_SPICE * p) [explicit]
Definition at line 543 of file spice-wrapper.cc.
References assert_model_raw.
  :MODEL_CARD(p),
   _spice_model(),
   _key(),
   _level(),
   _params()
{
  assert_model_raw();
}
MODEL_SPICE::~MODEL_SPICE ()
Definition at line 563 of file spice-wrapper.cc.
References _count.
{
  --_count;
}
Member Function Documentation
static CKTcircuit* MODEL_SPICE::ckt () [inline, static]
Definition at line 177 of file spice-wrapper.cc.
References _ckt.
Referenced by init_ckt().
{return &_ckt;}
MODEL_CARD* MODEL_SPICE::clone () const [inline, virtual]
Reimplemented from CARD.
Definition at line 154 of file spice-wrapper.cc.
References MODEL_SPICE().
{return new MODEL_SPICE(*this);}
static int MODEL_SPICE::count () [inline, static]
Definition at line 176 of file spice-wrapper.cc.
References _count, and untested.
{untested(); return _count;}
std::string MODEL_SPICE::dev_type () const [inline, virtual]
Reimplemented from CARD.
Definition at line 161 of file spice-wrapper.cc.
References _key.
{ return _key;}
void MODEL_SPICE::init_ckt () [static]
Definition at line 353 of file spice-wrapper.cc.
References CKT_BASE::_sim, SIM_DATA::_temp_c, SIM_DATA::_time0, OPT::abstol, SIM_DATA::analysis_is_tran(), assert_ckt_initialized, ckt(), SIM_DATA::command_is_ac(), SIM_DATA::command_is_dc(), SIM_DATA::command_is_op(), OPT::defad, OPT::defas, OPT::defl, OPT::defw, OPT::gmin, OPT::reltol, OPT::tnom_c, and OPT::vntol.
{
  assert(ckt());
  ckt()->CKTtime = _sim->_time0;
  ckt()->CKTtemp    = _sim->_temp_c + CONSTCtoK; //manage by update
  ckt()->CKTnomTemp = OPT::tnom_c + CONSTCtoK;
  ckt()->CKTintegrateMethod = 0; // disable
  if (_sim->command_is_op()) {
    ckt()->CKTcurrentAnalysis = DOING_DCOP;
  }else if (_sim->command_is_dc()) {
    ckt()->CKTcurrentAnalysis = DOING_TRCV;
  }else if (_sim->command_is_ac()) {
    ckt()->CKTcurrentAnalysis = DOING_AC;
  }else if (_sim->analysis_is_tran()) {
    ckt()->CKTcurrentAnalysis = DOING_TRAN;
  }else{ // probably probe
    ckt()->CKTcurrentAnalysis = 0;
  }
  ckt()->CKTmode = 0; // wrong but safe
  ckt()->CKTbypass  = false; // manage this elsewhere
  ckt()->CKTabstol = OPT::abstol;
  ckt()->CKTreltol = OPT::reltol;
  ckt()->CKTvoltTol = OPT::vntol;
  ckt()->CKTgmin = OPT::gmin;
  ckt()->CKTsrcFact = 1.; // source stepping kluge
  ckt()->CKTdefaultMosL = OPT::defl;
  ckt()->CKTdefaultMosW = OPT::defw;
  ckt()->CKTdefaultMosAD = OPT::defad;
  ckt()->CKTdefaultMosAS = OPT::defas;
  ckt()->CKTfixLimit = false; // limiting kluge 1 == spice2
#ifndef JSPICE3
  ckt()->CKTbadMos3 = false; // 1 = spice2 compat
  ckt()->CKTsenInfo = NULL; // used as flag to print sens info
#endif
#ifdef NGSPICE_17
  ckt()->CKTdefaultMosM = 1.;
  ckt()->CKTcopyNodesets = false;
#endif
  assert_ckt_initialized(ckt());
}
bool MODEL_SPICE::is_valid (const COMPONENT * d) const [virtual]
Reimplemented from MODEL_CARD.
int MODEL_SPICE::param_count () const [inline, virtual]
Reimplemented from MODEL_CARD.
Definition at line 171 of file spice-wrapper.cc.
References _params, MODEL_CARD::param_count(), and PARAM_LIST::size().
Referenced by param_count_dont_print(), param_is_printable(), param_name(), and param_value().
{ return (static_cast<int>(_params.size()) + MODEL_CARD::param_count());}
int MODEL_SPICE::param_count_dont_print () const [inline, virtual]
Reimplemented from CARD.
Definition at line 170 of file spice-wrapper.cc.
References param_count().
{return MODEL_CARD::param_count();}
bool MODEL_SPICE::param_is_printable (int i) const [virtual]
Reimplemented from MODEL_CARD.
Definition at line 649 of file spice-wrapper.cc.
References _params, PARAM_LIST::is_printable(), MODEL_CARD::param_count(), and param_count().
{
  assert(i < MODEL_SPICE::param_count());
  if (i >= MODEL_CARD::param_count()) {
    return _params.is_printable(MODEL_SPICE::param_count() - 1 - i);
  }else{
    return MODEL_CARD::param_is_printable(i);
  }
}
std::string MODEL_SPICE::param_name (int i) const [virtual]
Reimplemented from MODEL_CARD.
Definition at line 659 of file spice-wrapper.cc.
References _params, PARAM_LIST::name(), MODEL_CARD::param_count(), and param_count().
Referenced by param_name().
{
  assert(i < MODEL_SPICE::param_count());
  if (i >= MODEL_CARD::param_count()) {
    return _params.name(MODEL_SPICE::param_count() - 1 - i);
  }else{
    return MODEL_CARD::param_name(i);
  }
}
std::string MODEL_SPICE::param_name (int i, int j) const [virtual]
Reimplemented from MODEL_CARD.
Definition at line 669 of file spice-wrapper.cc.
References MODEL_CARD::param_count(), param_count(), param_name(), and untested.
{untested();
  assert(i < MODEL_SPICE::param_count());
  if (j == 0) {untested();
    return param_name(i);
  }else if (i >= MODEL_CARD::param_count()) {untested();
    return "";
  }else{untested();
    return MODEL_CARD::param_name(i);
  }
}
std::string MODEL_SPICE::param_value (int i) const [virtual]
Reimplemented from MODEL_CARD.
Definition at line 681 of file spice-wrapper.cc.
References _params, MODEL_CARD::param_count(), param_count(), and PARAM_LIST::value().
{
  assert(i < MODEL_SPICE::param_count());
  if (i >= MODEL_CARD::param_count()) {
    return _params.value(MODEL_SPICE::param_count() - 1 - i);
  }else{
    return MODEL_CARD::param_value(i);
  }
}
void MODEL_SPICE::set_dev_type (const std::string & nt) [virtual]
Reimplemented from CARD.
Definition at line 631 of file spice-wrapper.cc.
References SPICE_MODEL_DATA::_gen, _key, _spice_model, assert_model_raw, OPT::case_insensitive, anonymous_namespace{c_genrat.cc}::p, CKT_BASE::short_label(), and notstd::to_lower().
{
  assert_model_raw();
  //_spice_model._gen.set_mod_name(short_label());
  std::string s = short_label();
  char* p = new char[s.length()+1]; //BUG//memory leak
  s.copy(p, std::string::npos);
  p[s.length()] = '\0';
  _spice_model._gen.GENmodName = p;
  _key = new_type;
  if (OPT::case_insensitive) {
    notstd::to_lower(&_key);
  }else{
  }
}
void MODEL_SPICE::set_param_by_index (int , std::string & , int) [virtual]
Reimplemented from MODEL_CARD.
Definition at line 691 of file spice-wrapper.cc.
References unreachable, and untested.
{untested();
  unreachable();
}
void MODEL_SPICE::set_param_by_name (std::string Name, std::string Value) [virtual]
Reimplemented from CARD.
Definition at line 594 of file spice-wrapper.cc.
References _params, OPT::case_insensitive, e_val(), CARD::scope(), PARAM_LIST::set(), Set_param_by_name(), notstd::to_lower(), and to_string().
{
  if (OPT::case_insensitive) {
    notstd::to_lower(&Name);
  }else{
  }
  _params.set(Name, Value);
  Set_param_by_name(Name, to_string(_params[Name].e_val(1,scope())));
}
void MODEL_SPICE::Set_param_by_name (std::string Name, std::string Value)
Definition at line 568 of file spice-wrapper.cc.
References SPICE_MODEL_DATA::_gen, _spice_model, assert_model_raw, and info.
Referenced by set_param_by_name().
{
  assert_model_raw();
  assert(info.DEVpublic.numModelParms);
  assert(info.DEVpublic.modelParms);
  assert(info.DEVmodParam);
  int num_params = *(info.DEVpublic.numModelParms);
  for (int i = 0; i < num_params; ++i) {
    IFparm Parms = info.DEVpublic.modelParms[i];
    if (Name == Parms.keyword) {
      IFvalue Value;
      IFVA v(&Value, Parms.dataType);
      v = new_value;
      int ok = info.DEVmodParam(Parms.id, &Value, &_spice_model._gen);
      assert(ok == OK);
      return;
    }else{
    }
  }
  if (Name != "level") {
    throw Exception_No_Match(Name);
  }else{
  }
}
Member Data Documentation
CKTcircuit MODEL_SPICE::_ckt [static, private]
Definition at line 142 of file spice-wrapper.cc.
Referenced by ckt().
int MODEL_SPICE::_count = -1 [static, private]
Definition at line 141 of file spice-wrapper.cc.
Referenced by count(), and ~MODEL_SPICE().
std::string MODEL_SPICE::_key
Definition at line 145 of file spice-wrapper.cc.
Referenced by dev_type(), and set_dev_type().
std::string MODEL_SPICE::_level
Definition at line 146 of file spice-wrapper.cc.
PARAM_LIST MODEL_SPICE::_params
Definition at line 147 of file spice-wrapper.cc.
Referenced by param_count(), param_is_printable(), param_name(), param_value(), and set_param_by_name().
SPICE_MODEL_DATA MODEL_SPICE::_spice_model
Definition at line 144 of file spice-wrapper.cc.
Referenced by DEV_SPICE::expand(), DEV_SPICE::precalc_last(), set_dev_type(), and Set_param_by_name().
The documentation for this class was generated from the following file:
savant/gnucap/src/spice-wrapper.cc