gnucap: EVAL_BUILT_IN_DIODE_Cj Class Reference
EVAL_BUILT_IN_DIODE_Cj Class Reference
#include <d_diode.h>
Public Member Functions
EVAL_BUILT_IN_DIODE_Cj (int c=0)
bool operator== (const COMMON_COMPONENT &x) const
COMMON_COMPONENT * clone () const
std::string name () const
void tr_eval (ELEMENT *d) const
bool has_tr_eval () const
bool has_ac_eval () const
Private Member Functions
EVAL_BUILT_IN_DIODE_Cj (const EVAL_BUILT_IN_DIODE_Cj &p)
Detailed Description
Definition at line 149 of file d_diode.h.
Constructor & Destructor Documentation
EVAL_BUILT_IN_DIODE_Cj::EVAL_BUILT_IN_DIODE_Cj (const EVAL_BUILT_IN_DIODE_Cj & p) [inline, explicit, private]
Definition at line 151 of file d_diode.h.
Referenced by clone().
    :COMMON_COMPONENT(p) {}
EVAL_BUILT_IN_DIODE_Cj::EVAL_BUILT_IN_DIODE_Cj (int c = 0) [inline, explicit]
Definition at line 154 of file d_diode.h.
:COMMON_COMPONENT(c) {}
Member Function Documentation
COMMON_COMPONENT* EVAL_BUILT_IN_DIODE_Cj::clone () const [inline, virtual]
Implements COMMON_COMPONENT.
Definition at line 156 of file d_diode.h.
References EVAL_BUILT_IN_DIODE_Cj().
{return new EVAL_BUILT_IN_DIODE_Cj(*this);}
bool EVAL_BUILT_IN_DIODE_Cj::has_ac_eval () const [inline, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 160 of file d_diode.h.
{return false;}
bool EVAL_BUILT_IN_DIODE_Cj::has_tr_eval () const [inline, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 159 of file d_diode.h.
{return true;}
std::string EVAL_BUILT_IN_DIODE_Cj::name () const [inline, virtual]
Implements COMMON_COMPONENT.
Definition at line 157 of file d_diode.h.
References untested.
{untested(); return "EVAL_BUILT_IN_DIODE_Cj";}
bool EVAL_BUILT_IN_DIODE_Cj::operator== (const COMMON_COMPONENT & x) const [inline, virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 155 of file d_diode.h.
{return COMMON_COMPONENT::operator==(x);}
void EVAL_BUILT_IN_DIODE_Cj::tr_eval (ELEMENT * d) const [virtual]
Reimplemented from COMMON_COMPONENT.
Definition at line 621 of file d_diode.cc.
References DEV_BUILT_IN_DIODE::_gd, CKT_BASE::_sim, ELEMENT::_y, SIM_DATA::analysis_is_restore(), SIM_DATA::analysis_is_static(), SIM_DATA::analysis_is_tran_dynamic(), COMMON_BUILT_IN_DIODE::cj_adjusted, COMMON_BUILT_IN_DIODE::cjsw_adjusted, COMPONENT::common(), FPOLY1::f0, FPOLY1::f1, MODEL_BUILT_IN_DIODE::fc, CARD::long_label(), MODEL_BUILT_IN_DIODE::mj, MODEL_BUILT_IN_DIODE::mjsw, COMMON_COMPONENT::model(), CARD::owner(), anonymous_namespace{c_genrat.cc}::p, MODEL_BUILT_IN_DIODE::pb, MODEL_BUILT_IN_DIODE::pbsw, prechecked_cast, COMMON_BUILT_IN_DIODE::sdp(), trace1, trace3, trace4, MODEL_BUILT_IN_DIODE::tt, and FPOLY1::x.
{
  assert(d);
  DEV_BUILT_IN_DIODE* p = prechecked_cast<DEV_BUILT_IN_DIODE*>(d->owner());
  assert(p);
  const COMMON_BUILT_IN_DIODE* c = prechecked_cast<const COMMON_BUILT_IN_DIODE*>(p->common());
  assert(c);
  const SDP_BUILT_IN_DIODE* s = prechecked_cast<const SDP_BUILT_IN_DIODE*>(c->sdp());
  assert(s);
  const MODEL_BUILT_IN_DIODE* m = prechecked_cast<const MODEL_BUILT_IN_DIODE*>(c->model());
  assert(m);
    double& volts = d->_y[0].x;
    trace1(d->long_label().c_str(), volts);
    double cb;
    if (c->cj_adjusted != 0.) {
      if (volts < m->fc * m->pb) {
        cb = c->cj_adjusted / pow(1. - (volts / m->pb),  m->mj);
      }else{
        cb = (c->cj_adjusted / pow(1. - m->fc, 1. + m->mj))
          * (1. - m->fc*(1.+m->mj) + (volts/m->pb)*m->mj);
      }
    }else{
      cb = 0.;
    }
    assert(cb >= 0.);
    double csw;
    if (c->cjsw_adjusted != 0.) {
      if (volts < m->fc * m->pbsw) {
        csw = c->cjsw_adjusted / pow(1. - (volts / m->pbsw),  m->mjsw);
      }else{
        csw = (c->cjsw_adjusted / pow(1. - m->fc, 1. + m->mjsw))
          * (1. - m->fc*(1.+m->mjsw) + (volts/m->pbsw)*m->mjsw);
      }
    }else{
      csw = 0.;
    }
    assert(csw >= 0.);
    double ctt;
    if (m->tt != 0.) {
      ctt = p->_gd * m->tt;
    }else{
      ctt = 0.;
    }
    assert(ctt >= 0.);
    trace4("", cb, csw, ctt, cb+csw+ctt);
    d->_y[0].f1 = cb + csw + ctt;
    if (d->_sim->analysis_is_tran_dynamic()) {
      const STORAGE* dd = prechecked_cast<const STORAGE*>(d);
      assert(dd);
      double cap = (d->_y[0].f1 + dd->_y[1].f1) / 2;
      d->_y[0].f0 = (d->_y[0].x - dd->_y[1].x) * cap + dd->_y[1].f0;
    }else{
      assert(d->_sim->analysis_is_static() || d->_sim->analysis_is_restore());
      d->_y[0].f0 = d->_y[0].x * d->_y[0].f1;
    }
    trace3(d->long_label().c_str(), d->_y[0].x, d->_y[0].f0, d->_y[0].f1);
}
The documentation for this class was generated from the following files:
savant/gnucap/src/d_diode.h
savant/gnucap/src/d_diode.cc