gnucap: savant/gnucap/src/e_aux.h File Reference
savant/gnucap/src/e_aux.h File Reference
#include "e_node.h"
Functions
template<class T >
T port_impedance (const node_t &n1, const node_t &n2, BSMATRIX< T > &mat, const T &parallel)
Function Documentation
template<class T > T port_impedance (const node_t & n1, const node_t & n2, BSMATRIX< T > & mat, const T & parallel)
Definition at line 30 of file e_aux.h.
References BSMATRIX< T >::fbsub(), node_t::m_(), BSMATRIX< T >::size(), and untested.
Referenced by ELEMENT::ac_probe_ext(), NODE::ac_probe_ext(), ELEMENT::tr_probe_num(), and NODE::tr_probe_num().
{
  T* zapit = new T[mat.size()+2];
  for (int ii = 0;  ii < mat.size()+2;  ++ii) {
    zapit[ii] = 0.;
  }
  if (n1.m_() != 0) {
    zapit[n1.m_()] =  1.;
  }else{untested();
  }
  if (n2.m_() != 0) {untested();
    zapit[n2.m_()] = -1.;
  }else{
  }
  mat.fbsub(zapit);
  T raw_z = zapit[n1.m_()] - zapit[n2.m_()];
  delete [] zapit;
  return (parallel != 0.)
    ? 1. / ((1./raw_z)-parallel)
    : raw_z;
}