gnucap: anonymous_namespace{lang_gschem.cc}::CMD_COMPONENT Class Reference
anonymous_namespace{lang_gschem.cc}::CMD_COMPONENT Class Reference
Private Member Functions
void do_it (CS &cmd, CARD_LIST *Scope)
Detailed Description
Definition at line 277 of file lang_gschem.cc.
Member Function Documentation
void anonymous_namespace{lang_gschem.cc}::CMD_COMPONENT::do_it (CS & cmd, CARD_LIST * Scope) [inline, private, virtual]
Implements CMD.
Definition at line 278 of file lang_gschem.cc.
References CARD_LIST::is_empty(), anonymous_namespace{lang_gschem.cc}::lang_gschem, CARD::owner(), anonymous_namespace{lang_gschem.cc}::LANG_GSCHEM::parse_module(), CARD_LIST::push_back(), and CARD::subckt().
    {
      std::cout<<"Command Dispatched\n";
      MODEL_SUBCKT* new_compon = new MODEL_SUBCKT;
      assert(new_compon);
      assert(!new_compon->owner());
      assert(new_compon->subckt());
      assert(new_compon->subckt()->is_empty());
      lang_gschem.parse_module(cmd, new_compon);
      Scope->push_back(new_compon);
    }
The documentation for this class was generated from the following file:
savant/gnucap/src/lang_gschem.cc