gnucap: LOGIC_XNOR Class Reference
LOGIC_XNOR Class Reference
#include <d_logic.h>
Public Member Functions
LOGIC_XNOR (int c=0)
LOGICVAL logic_eval (const node_t *n) const
virtual std::string name () const
Private Member Functions
LOGIC_XNOR (const LOGIC_XNOR &p)
COMMON_COMPONENT * clone () const
Detailed Description
Definition at line 244 of file d_logic.h.
Constructor & Destructor Documentation
LOGIC_XNOR::LOGIC_XNOR (const LOGIC_XNOR & p) [inline, explicit, private]
Definition at line 246 of file d_logic.h.
References COMMON_LOGIC::_count, and untested.
Referenced by clone().
:COMMON_LOGIC(p){untested();++_count;}
LOGIC_XNOR::LOGIC_XNOR (int c = 0) [inline, explicit]
Definition at line 249 of file d_logic.h.
References untested.
:COMMON_LOGIC(c) {untested();}
Member Function Documentation
COMMON_COMPONENT* LOGIC_XNOR::clone () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 247 of file d_logic.h.
References LOGIC_XNOR(), and untested.
{untested(); return new LOGIC_XNOR(*this);}
LOGICVAL LOGIC_XNOR::logic_eval (const node_t * n) const [inline, virtual]
Implements COMMON_LOGIC.
Definition at line 250 of file d_logic.h.
References COMMON_LOGIC::incount, LOGIC_NODE::lv(), and untested.
                                            {untested();
    LOGICVAL out(n[0]->lv());
    for (int ii=1; ii<incount; ++ii) {untested();
      out ^= n[ii]->lv();
    }
    return ~out;
  }
virtual std::string LOGIC_XNOR::name () const [inline, virtual]
Implements COMMON_COMPONENT.
Definition at line 257 of file d_logic.h.
References itested.
{itested();return "xnor";}
The documentation for this class was generated from the following file:
savant/gnucap/src/d_logic.h