gnucap: savant/gnucap/src/d_diode.cc File Reference
savant/gnucap/src/d_diode.cc File Reference
#include "e_aux.h"
#include "e_storag.h"
#include "globals.h"
#include "e_elemnt.h"
#include "d_diode.h"
Namespaces
namespace MODEL_BUILT_IN_DIODE_DISPATCHER
namespace DEV_BUILT_IN_DIODE_DISPATCHER
Enumerations
enum { USE_OPT = 0x8000 }
Functions
const double NA (NOT_INPUT)
const double INF (BIGBIG)
Variables
static bool dummy = false
static DEV_BUILT_IN_DIODE MODEL_BUILT_IN_DIODE_DISPATCHER::p1d
static DISPATCHER< MODEL_CARD >
::INSTALL d1 & MODEL_BUILT_IN_DIODE_DISPATCHER::model_dispatcher
static COMMON_BUILT_IN_DIODE Default_BUILT_IN_DIODE (CC_STATIC)
static DEV_BUILT_IN_DIODE DEV_BUILT_IN_DIODE_DISPATCHER::p0
static DISPATCHER< CARD >
::INSTALL d0 & DEV_BUILT_IN_DIODE_DISPATCHER::device_dispatcher
static EVAL_BUILT_IN_DIODE_Cj Eval_Cj (CC_STATIC)
static EVAL_BUILT_IN_DIODE_Yj Eval_Yj (CC_STATIC)
Enumeration Type Documentation
anonymous enum
Enumerator:
USE_OPT
Definition at line 35 of file d_diode.cc.
{USE_OPT = 0x8000};
Function Documentation
const double INF (BIGBIG)
const double NA (NOT_INPUT)
Variable Documentation
COMMON_BUILT_IN_DIODE Default_BUILT_IN_DIODE(CC_STATIC) [static]
Referenced by DEV_BUILT_IN_DIODE::DEV_BUILT_IN_DIODE().
bool dummy = false [static]
Definition at line 34 of file d_diode.cc.
Referenced by MODEL_BUILT_IN_DIODE::dev_type(), and MODEL_BUILT_IN_DIODE::set_dev_type().
EVAL_BUILT_IN_DIODE_Cj Eval_Cj(CC_STATIC) [static]
Referenced by DEV_BUILT_IN_DIODE::expand().
EVAL_BUILT_IN_DIODE_Yj Eval_Yj(CC_STATIC) [static]
Referenced by DEV_BUILT_IN_DIODE::expand().