gnucap: node_t Class Reference
node_t Class Reference
#include <e_node.h>
Public Member Functions
int m_ () const
int t_ () const
int e_ () const
const NODE * n_ () const
NODE * n_ ()
const std::string short_label () const
void set_to_ground (CARD *)
void new_node (const std::string &, const CARD *)
void new_model_node (const std::string &n, CARD *d)
void map_subckt_node (int *map_array, const CARD *d)
bool is_grounded () const
bool is_connected () const
node_t & map ()
node_t ()
node_t (const node_t &)
node_t (NODE *)
~node_t ()
const LOGIC_NODE * operator-> () const
LOGIC_NODE * operator-> ()
node_t & operator= (const node_t &p)
bool operator== (const node_t &p)
double v0 () const
COMPLEX vac () const
double & i ()
Private Member Functions
LOGIC_NODE & data () const
Static Private Member Functions
static bool node_is_valid (int i)
static int to_internal (int n)
Private Attributes
NODE * _nnn
int _ttt
int _m
Detailed Description
Definition at line 230 of file e_node.h.
Constructor & Destructor Documentation
node_t::node_t () [explicit]
Definition at line 132 of file e_node.cc.
  :_nnn(0),
   _ttt(INVALID_NODE),
   _m(INVALID_NODE)
{
}
node_t::node_t (const node_t & p)
Definition at line 138 of file e_node.cc.
  :_nnn(p._nnn),
   _ttt(p._ttt),
   _m(p._m)
{
  //assert(_ttt == _nnn->flat_number());
}
node_t::node_t (NODE * n) [explicit]
Definition at line 145 of file e_node.cc.
  :_nnn(n),
   _ttt(n->user_number()),
   _m(to_internal(n->user_number()))
{
  //assert(_ttt == _nnn->flat_number());
}
node_t::~node_t () [inline]
Definition at line 293 of file e_node.h.
{}
Member Function Documentation
LOGIC_NODE & node_t::data () const [private]
Definition at line 166 of file e_node.cc.
References SIM_DATA::_nstat, CKT_BASE::_sim, and m_().
{
  assert(CKT_BASE::_sim->_nstat);
  return CKT_BASE::_sim->_nstat[m_()];
}
int node_t::e_ () const [inline]
Definition at line 264 of file e_node.h.
References INVALID_NODE.
Referenced by map_subckt_node(), and CARD_LIST::map_subckt_nodes().
{
    assert(_nnn);
    return ((_nnn) ? _nnn->user_number() : INVALID_NODE);
  }
double& node_t::i () [inline]
Definition at line 336 of file e_node.h.
References SIM_DATA::_i, and CKT_BASE::_sim.
Referenced by anonymous_namespace{d_trln.cc}::DEV_TRANSLINE::tr_load(), ELEMENT::tr_load_source(), and ELEMENT::tr_load_source_point().
                  {
    assert(m_() >= 0);
    assert(m_() <= NODE::_sim->_total_nodes);
    return NODE::_sim->_i[m_()];
  }
bool node_t::is_connected () const [inline]
Definition at line 278 of file e_node.h.
References INVALID_NODE.
Referenced by COMPONENT::node_is_connected().
{return (e_() != INVALID_NODE);}
bool node_t::is_grounded () const [inline]
Definition at line 277 of file e_node.h.
Referenced by COMPONENT::node_is_grounded().
{return (e_() == 0);}
int node_t::m_ () const [inline]
Definition at line 255 of file e_node.h.
Referenced by ELEMENT::ac_load_diagonal_point(), ELEMENT::ac_load_extended(), ELEMENT::ac_load_point(), ELEMENT::ac_load_source_point(), data(), port_impedance(), ELEMENT::tr_load_diagonal_point(), ELEMENT::tr_load_extended(), ELEMENT::tr_load_point(), and ELEMENT::tr_load_source_point().
{return _m;}
node_t& node_t::map () [inline]
Definition at line 280 of file e_node.h.
References INVALID_NODE.
Referenced by COMPONENT::map_nodes().
                    {
    if (t_() != INVALID_NODE) {
      assert(_nnn);
      _m=to_internal(t_());
    }else{
      assert(_m == INVALID_NODE);
    }
    return *this;
  } // e_compon.cc:COMPONENT::map_nodes:522
void node_t::map_subckt_node (int * map_array, const CARD * d)
Definition at line 533 of file e_node.cc.
References _ttt, e_(), CARD::long_label(), node_is_valid(), and untested.
{
  assert(m);
  assert(e_() >= 0);
  if (node_is_valid(m[e_()])) {
    _ttt = m[e_()];
  }else{untested();
    throw Exception(d->long_label() + ": need more nodes");
  }
  //_nnn->set_flat_number(_ttt);
  assert(node_is_valid(_ttt));
}
const NODE* node_t::n_ () const [inline]
Definition at line 268 of file e_node.h.
Referenced by CARD::connects_to().
{return _nnn;}
NODE* node_t::n_ () [inline]
Definition at line 269 of file e_node.h.
{return _nnn;}
void node_t::new_model_node (const std::string & n, CARD * d)
Definition at line 526 of file e_node.cc.
References CKT_BASE::_sim, _ttt, new_node(), and SIM_DATA::newnode_model().
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::expand(), and DEV_SPICE::expand().
{
  new_node(node_name, d);
  _ttt = CKT_BASE::_sim->newnode_model();
  //assert(_ttt == _nnn->flat_number());
}
void node_t::new_node (const std::string & node_name, const CARD * d)
Definition at line 508 of file e_node.cc.
References _nnn, _ttt, NODE_MAP::new_node(), CARD_LIST::nodes(), CARD::scope(), and NODE::user_number().
Referenced by new_model_node(), and COMPONENT::set_port_by_index().
{
  //assert(!_nnn); //BUG// fails on MUTUAL_L::expand after clone
  assert(d);
  NODE_MAP* Map = d->scope()->nodes();
  assert(Map);
  _nnn = Map->new_node(node_name);
  _ttt = _nnn->user_number();
  assert(_nnn);
}
static bool node_t::node_is_valid (int i) [inline, static, private]
Definition at line 232 of file e_node.h.
References CKT_BASE::_sim, SIM_DATA::_total_nodes, INVALID_NODE, itested, unreachable, and untested.
Referenced by map_subckt_node().
{
    if (i == INVALID_NODE) {untested();
      itested();
    }else if (i < 0) {
      unreachable();
    }else if (i > NODE::_sim->_total_nodes) {
      unreachable();
    }else{
    }
    return i>=0 && i<=NODE::_sim->_total_nodes;
  }
const LOGIC_NODE* node_t::operator-> () const [inline]
Definition at line 300 of file e_node.h.
{return &data();}
LOGIC_NODE* node_t::operator-> () [inline]
Definition at line 301 of file e_node.h.
{return &data();}
node_t & node_t::operator= (const node_t & p)
Definition at line 152 of file e_node.cc.
References _m, _nnn, _ttt, and INVALID_NODE.
{
  if (p._nnn) {
    //assert(p._ttt == p._nnn->flat_number());
  }else{
    assert(p._ttt == INVALID_NODE);
    assert(p._m   == INVALID_NODE);
  }
  _nnn   = p._nnn;
  _ttt = p._ttt;
  _m   = p._m;
  return *this;
}
bool node_t::operator== (const node_t & p) [inline]
Definition at line 305 of file e_node.h.
References _m, _nnn, and _ttt.
{return _nnn==p._nnn && _ttt==p._ttt && _m==p._m;}
void node_t::set_to_ground (CARD * d)
Definition at line 494 of file e_node.cc.
References _nnn, _ttt, CARD_LIST::nodes(), and CARD::scope().
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::expand(), DEV_SPICE::expand(), CCSRC_BASE::expand_last(), and COMPONENT::set_port_to_ground().
{
  //assert(!_nnn); //BUG// fails on MUTUAL_L::expand after clone
  assert(d);
  NODE_MAP* Map = d->scope()->nodes();
  assert(Map);
  _nnn = (*Map)["0"];
  _ttt = 0;
  assert(_nnn);
}
const std::string node_t::short_label () const [inline]
Definition at line 272 of file e_node.h.
References short_label().
Referenced by COMPONENT::port_value(), and short_label().
{return ((n_()) ? (n_()->short_label()) : "?????");}
int node_t::t_ () const [inline]
Definition at line 257 of file e_node.h.
Referenced by CARD_LIST::map_subckt_nodes().
{
    //assert(_nnn);
    //assert(_ttt == _nnn->flat_number());
    return _ttt;
  }     // e_cardlist.cc:CARD_LIST::map_subckt_nodes:436 and
static int node_t::to_internal (int n) [inline, static, private]
Definition at line 243 of file e_node.h.
References SIM_DATA::_nm, and CKT_BASE::_sim.
{
    assert(node_is_valid(n));
    assert(NODE::_sim->_nm);
    return NODE::_sim->_nm[n];
  }
double node_t::v0 () const [inline]
Definition at line 308 of file e_node.h.
References CKT_BASE::_sim, and SIM_DATA::_v0.
Referenced by anonymous_namespace{d_switch.cc}::SWITCH_BASE::do_tr(), DEV_SPICE::do_tr(), anonymous_namespace{d_coil.cc}::DEV_MUTUAL_L::do_tr_last(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_amps(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_input(), anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::tr_input_limited(), DEV_SPICE::tr_needs_eval(), COMPONENT::tr_probe_num(), anonymous_namespace{d_switch.cc}::SWITCH_BASE::tr_review(), and COMPONENT::volts_limited().
{
    //assert(m_() >= 0);
    if (m_() >= 0) {
      assert(m_() <= NODE::_sim->_total_nodes);
      assert(n_());
      //assert(n_()->m_() == m_());
      //assert(n_()->v0() == NODE::_sim->_v0[m_()]);
      return NODE::_sim->_v0[m_()];
    }else{
      //BUG// in BJT model: should not get here but does.
      return 0.;
    }
  }
COMPLEX node_t::vac () const [inline]
Definition at line 322 of file e_node.h.
References SIM_DATA::_ac, CKT_BASE::_sim, and untested.
Referenced by anonymous_namespace{d_coil.cc}::DEV_INDUCTANCE::ac_amps().
{
    //assert(m_() >= 0);
    if (m_() >= 0) {
      assert(m_() <= NODE::_sim->_total_nodes);
      assert(n_());
      //assert(n_()->m_() == m_());
      //assert(n_()->vac() == NODE::_ac[m_()]);
      return NODE::_sim->_ac[m_()];
    }else{untested();
      //BUG// assume v0 BUG applies here too.
      return 0.;
    }
  }
Member Data Documentation
int node_t::_m [private]
Definition at line 252 of file e_node.h.
Referenced by operator=(), and operator==().
NODE* node_t::_nnn [private]
Definition at line 250 of file e_node.h.
Referenced by new_node(), operator=(), operator==(), and set_to_ground().
int node_t::_ttt [private]
Definition at line 251 of file e_node.h.
Referenced by map_subckt_node(), new_model_node(), new_node(), operator=(), operator==(), and set_to_ground().
The documentation for this class was generated from the following files:
savant/gnucap/src/e_node.h
savant/gnucap/src/e_node.cc