gnucap: anonymous_namespace{lang_verilog.cc}::CMD_MODULE Class Reference
anonymous_namespace{lang_verilog.cc}::CMD_MODULE Class Reference
Private Member Functions
void do_it (CS &cmd, CARD_LIST *Scope)
Detailed Description
Definition at line 467 of file lang_verilog.cc.
Member Function Documentation
void anonymous_namespace{lang_verilog.cc}::CMD_MODULE::do_it (CS & cmd, CARD_LIST * Scope) [inline, private, virtual]
Implements CMD.
Definition at line 468 of file lang_verilog.cc.
References CARD_LIST::is_empty(), anonymous_namespace{lang_verilog.cc}::lang_verilog, CARD::owner(), anonymous_namespace{lang_verilog.cc}::LANG_VERILOG::parse_module(), CARD_LIST::push_back(), and CARD::subckt().
  {
    MODEL_SUBCKT* new_module = new MODEL_SUBCKT;
    assert(new_module);
    assert(!new_module->owner());
    assert(new_module->subckt());
    assert(new_module->subckt()->is_empty());
    lang_verilog.parse_module(cmd, new_module);
    Scope->push_back(new_module);
  }
The documentation for this class was generated from the following file:
savant/gnucap/src/lang_verilog.cc