gnucap: savant/gnucap/src/u_time_pair.h File Reference
savant/gnucap/src/u_time_pair.h File Reference
#include "constant.h"
Classes
struct TIME_PAIR
Functions
TIME_PAIR min (TIME_PAIR A, const TIME_PAIR &B)
Function Documentation
TIME_PAIR min (TIME_PAIR A, const TIME_PAIR & B) [inline]
Definition at line 63 of file u_time_pair.h.
References TIME_PAIR::min().
Referenced by CKTterr(), anonymous_namespace{func_core.cc}::MIN::eval(), SIM::head(), anonymous_namespace{s_fo.cc}::FOURIER::setup(), TRANSIENT::setup(), to_range(), and DEV_SPICE::tr_probe_num().
{
  return A.min(B);
}