gnucap: LOGIC_XOR Class Reference
LOGIC_XOR Class Reference
#include <d_logic.h>
Public Member Functions
LOGIC_XOR (int c=0)
LOGICVAL logic_eval (const node_t *n) const
virtual std::string name () const
Private Member Functions
LOGIC_XOR (const LOGIC_XOR &p)
COMMON_COMPONENT * clone () const
Detailed Description
Definition at line 228 of file d_logic.h.
Constructor & Destructor Documentation
LOGIC_XOR::LOGIC_XOR (const LOGIC_XOR & p) [inline, explicit, private]
Definition at line 230 of file d_logic.h.
References COMMON_LOGIC::_count, and untested.
Referenced by clone().
:COMMON_LOGIC(p){untested();++_count;}
LOGIC_XOR::LOGIC_XOR (int c = 0) [inline, explicit]
Definition at line 233 of file d_logic.h.
References untested.
:COMMON_LOGIC(c) {untested();}
Member Function Documentation
COMMON_COMPONENT* LOGIC_XOR::clone () const [inline, private, virtual]
Implements COMMON_COMPONENT.
Definition at line 231 of file d_logic.h.
References LOGIC_XOR(), and untested.
{untested(); return new LOGIC_XOR(*this);}
LOGICVAL LOGIC_XOR::logic_eval (const node_t * n) const [inline, virtual]
Implements COMMON_LOGIC.
Definition at line 234 of file d_logic.h.
References COMMON_LOGIC::incount, LOGIC_NODE::lv(), and untested.
                                            {untested();
    LOGICVAL out(n[0]->lv());
    for (int ii=1; ii<incount; ++ii) {untested();
      out ^= n[ii]->lv();
    }
    return out;
  }
virtual std::string LOGIC_XOR::name () const [inline, virtual]
Implements COMMON_COMPONENT.
Definition at line 241 of file d_logic.h.
References itested.
{itested();return "xor";}
The documentation for this class was generated from the following file:
savant/gnucap/src/d_logic.h