gnucap: TIMER Class Reference
TIMER Class Reference
#include <l_timer.h>
Public Member Functions
TIMER ()
TIMER (const std::string &)
~TIMER ()
TIMER & fullreset ()
TIMER & reset ()
TIMER & start ()
TIMER & stop ()
TIMER & check ()
double elapsed () const
bool is_running () const
TIMER & print (OMSTREAM &s=IO::mstdout)
TIMER & operator= (const TIMER &)
Private Attributes
double _ref
double _last
double _total
bool _running
std::string _name
Friends
INTERFACE TIMER operator- (const TIMER &, const TIMER &)
Detailed Description
Definition at line 31 of file l_timer.h.
Constructor & Destructor Documentation
TIMER::TIMER () [explicit]
Definition at line 43 of file l_timer.cc.
References fullreset().
{
  fullreset();
}
TIMER::TIMER (const std::string & label) [explicit]
Definition at line 48 of file l_timer.cc.
References fullreset().
  :_name(label)
{
  fullreset();
}
TIMER::~TIMER () [inline]
Definition at line 41 of file l_timer.h.
{}
Member Function Documentation
TIMER & TIMER::check ()
Definition at line 92 of file l_timer.cc.
References _running, itested, start(), stop(), and untested.
Referenced by CMD::cmdproc().
{
  itested();
  if (_running) {
    itested();
    stop();
    start();
  }else{
    untested();
  }
  return *this;
}
double TIMER::elapsed () const [inline]
Definition at line 47 of file l_timer.h.
References itested.
Referenced by CMD::cmdproc().
{itested();return _last;}
TIMER & TIMER::fullreset ()
Definition at line 54 of file l_timer.cc.
References _total, and reset().
Referenced by TIMER().
{
  _total = 0.;
  return reset();
}
bool TIMER::is_running () const [inline]
Definition at line 48 of file l_timer.h.
{return _running;}
TIMER & TIMER::operator= (const TIMER & x)
Definition at line 111 of file l_timer.cc.
References _last, _ref, _running, and _total.
{
  _last    = x._last;
  _ref     = x._ref;
  _total   = x._total;
  _running = x._running;
  // but don't copy the name
  return *this;
}
TIMER & TIMER::print (OMSTREAM & s = IO::mstdout)
Definition at line 105 of file l_timer.cc.
References _last, _name, _total, and OMSTREAM::form().
Referenced by operator<<().
{
  s.form("%10s %8.2f %8.2f\n", _name.c_str(), _last, _total);
  return *this;
}
TIMER & TIMER::reset ()
Definition at line 60 of file l_timer.cc.
References _last, _ref, and _running.
Referenced by CMD::cmdproc(), anonymous_namespace{s_ac.cc}::AC::do_it(), anonymous_namespace{s_fo.cc}::FOURIER::do_it(), anonymous_namespace{s_dc.cc}::DC::do_it(), anonymous_namespace{s_dc.cc}::OP::do_it(), anonymous_namespace{lang_spice.cc}::CMD_BUILD::do_it(), fullreset(), anonymous_namespace{lang_spice.cc}::getmerge(), and SIM_DATA::map__nodes().
{
  _last = 0.;
  _ref  = 0.;
  _running = false;
  return *this;
}
TIMER & TIMER::start ()
Definition at line 68 of file l_timer.cc.
References _ref, _running, run_time(), stop(), and untested.
Referenced by check(), CMD::cmdproc(), anonymous_namespace{s_ac.cc}::AC::do_it(), anonymous_namespace{s_fo.cc}::FOURIER::do_it(), anonymous_namespace{s_dc.cc}::DC::do_it(), anonymous_namespace{s_dc.cc}::OP::do_it(), anonymous_namespace{lang_spice.cc}::CMD_BUILD::do_it(), anonymous_namespace{lang_spice.cc}::getmerge(), SIM_DATA::map__nodes(), and anonymous_namespace{s_ac.cc}::AC::solve().
{
  assert(!_running);
  if (_running) {
    untested();
    stop();
  }
  _ref = run_time();
  _running = true;
  return *this;
}
TIMER & TIMER::stop ()
Definition at line 80 of file l_timer.cc.
References _last, _ref, _running, _total, and run_time().
Referenced by check(), CMD::cmdproc(), anonymous_namespace{s_ac.cc}::AC::do_it(), anonymous_namespace{s_fo.cc}::FOURIER::do_it(), anonymous_namespace{s_dc.cc}::DC::do_it(), anonymous_namespace{s_dc.cc}::OP::do_it(), anonymous_namespace{lang_spice.cc}::CMD_BUILD::do_it(), anonymous_namespace{lang_spice.cc}::getmerge(), SIM_DATA::map__nodes(), anonymous_namespace{s_ac.cc}::AC::solve(), and start().
{
  if (_running) {
    double runtime = run_time() - _ref;
    _ref = 0.;
    _last  += runtime;
    _total += runtime;
    _running = false;
  }
  return *this;
}
Friends And Related Function Documentation
INTERFACE TIMER operator- (const TIMER & x, const TIMER & y) [friend]
Member Data Documentation
double TIMER::_last [private]
Definition at line 34 of file l_timer.h.
Referenced by operator-(), operator=(), print(), reset(), and stop().
std::string TIMER::_name [private]
Definition at line 37 of file l_timer.h.
Referenced by print().
double TIMER::_ref [private]
Definition at line 33 of file l_timer.h.
Referenced by operator-(), operator=(), reset(), start(), and stop().
bool TIMER::_running [private]
Definition at line 36 of file l_timer.h.
Referenced by check(), operator-(), operator=(), reset(), start(), and stop().
double TIMER::_total [private]
Definition at line 35 of file l_timer.h.
Referenced by fullreset(), operator-(), operator=(), print(), and stop().
The documentation for this class was generated from the following files:
savant/gnucap/src/l_timer.h
savant/gnucap/src/l_timer.cc