gnucap: TRANSIENT Class Reference
TRANSIENT Class Reference
#include <s_tr.h>
Public Member Functions
TRANSIENT ()
~TRANSIENT ()
void do_it (CS &, CARD_LIST *scope)
std::string status () const
int step_cause () const
void first ()
bool next ()
void accept ()
void reject ()
Static Public Member Functions
static int steps_accepted ()
static int steps_rejected ()
static int steps_total ()
Protected Types
enum STEP_CAUSE {
scUSER = 1, scEVENTQ = 2, scSKIP = 3, scITER_R = 4,
scITER_A = 5, scTE = 6, scAMBEVENT = 7, scADT = 8,
scINITIAL = 9, scREJECT = 10, scZERO = 20, scSMALL = 30,
scNO_ADVANCE = 100
}
Protected Member Functions
void options (CS &)
void sweep ()
Protected Attributes
PARAMETER< double > _tstart
PARAMETER< double > _tstop
PARAMETER< double > _tstep
PARAMETER< double > _dtratio_in
PARAMETER< double > _dtmin_in
PARAMETER< double > _dtmax_in
PARAMETER< int > _skip_in
double time1
double _dtmax
bool _cold
bool _cont
int _stepno
Private Member Functions
bool review ()
void setup (CS &)
void set_step_cause (STEP_CAUSE)
bool is_step_rejected () const
TRANSIENT (const TRANSIENT &)
Private Attributes
TRACE _trace
double _time_by_iteration_count
double _time_by_user_request
double _time_by_error_estimate
double _time_by_ambiguous_event
bool _converged
bool _accepted
Static Private Attributes
static int steps_accepted_
static int steps_rejected_
static int steps_total_
Detailed Description
Definition at line 30 of file s_tr.h.
Member Enumeration Documentation
enum TRANSIENT::STEP_CAUSE [protected]
Enumerator:
scUSER
scEVENTQ
scSKIP
scITER_R
scITER_A
scTE
scAMBEVENT
scADT
scINITIAL
scREJECT
scZERO
scSMALL
scNO_ADVANCE
Definition at line 33 of file s_tr.h.
                  {
    scUSER      = 1,    /* user requested                               */
    scEVENTQ    = 2,    /* an "event" from the queue                    */
    scSKIP      = 3,    /* effect of "skip" parameter                   */
    scITER_R    = 4,    /* iter count exceeds itl4 (reducing)           */
    scITER_A    = 5,    /* iter count exceeds itl3 (holding)            */
    scTE        = 6,    /* truncation error, or device stuff            */
    scAMBEVENT  = 7,    /* ambiguous event                              */
    scADT       = 8,    /* by iter count limited by max(rdt, 2*adt)     */
    scINITIAL   = 9,    /* initial guess                                */
    scREJECT    = 10,   /* rejected previous time step                  */
    scZERO      = 20,   /* fixed zero time step                         */
    scSMALL     = 30,   /* time step too small                          */
    scNO_ADVANCE= 100   /* after all that it still didn't advance       */
  };
Constructor & Destructor Documentation
TRANSIENT::TRANSIENT () [inline, explicit]
Definition at line 50 of file s_tr.h.
                      :
    SIM(),
    _skip_in(1),
    _dtmax(0.),
    _cold(false),
    _cont(false),
    _trace(tNONE),
    _time_by_iteration_count(0.),
    _time_by_user_request(0.),
    _time_by_error_estimate(0.),
    _time_by_ambiguous_event(0.),
    _converged(false),
    _accepted(false)
  {
  }
TRANSIENT::~TRANSIENT () [inline]
Definition at line 65 of file s_tr.h.
{}
TRANSIENT::TRANSIENT (const TRANSIENT &) [inline, explicit, private]
Definition at line 91 of file s_tr.h.
References incomplete, and unreachable.
: SIM(),_skip_in(1) {unreachable(); incomplete();}
Member Function Documentation
void TRANSIENT::accept ()
Definition at line 510 of file s_tr_swp.cc.
References SIM_DATA::_acceptq, CKT_BASE::_sim, CARD_LIST::card_list, itested, SIM_DATA::set_limit(), status(), steps_accepted_, CARD_LIST::tr_accept(), and OPT::traceload.
Referenced by sweep().
{
  ::status.accept.start();
  _sim->set_limit();
  if (OPT::traceload) {
    while (!_sim->_acceptq.empty()) {
      _sim->_acceptq.back()->tr_accept();
      _sim->_acceptq.pop_back();
    }
  }else{itested();
    _sim->_acceptq.clear();
    CARD_LIST::card_list.tr_accept();
  }
  ++steps_accepted_;
  ::status.accept.stop();
}
void TRANSIENT::do_it (CS & Cmd, CARD_LIST * scope) [virtual]
Implements CMD.
Reimplemented in anonymous_namespace{s_fo.cc}::FOURIER.
Definition at line 36 of file s_tr.cc.
References SIM::_scope, CKT_BASE::_sim, SIM::command_base(), SIM_DATA::set_command_tran(), and status().
{
  _scope = Scope;
  _sim->set_command_tran();
  ::status.tran.reset().start();
  command_base(Cmd);
  ::status.tran.stop();
}
void TRANSIENT::first ()
Definition at line 173 of file s_tr_swp.cc.
References SIM_DATA::_eq, CKT_BASE::_sim, _stepno, SIM_DATA::_time0, _time_by_user_request, _tstart, _tstep, scUSER, set_step_cause(), status(), and time1.
Referenced by sweep().
{
  /* usually, _sim->_time0, time1 == 0, from setup */
  assert(_sim->_time0 == time1);
  assert(_sim->_time0 <= _tstart);
  ::status.review.start();
  _time_by_user_request = _sim->_time0 + _tstep;        /* set next user step */
  //_eq.Clear();                                /* empty the queue */
  while (!_sim->_eq.empty()) {
    _sim->_eq.pop();
  }
  _stepno = 0;
  set_step_cause(scUSER);
  ++::status.hidden_steps;
  ::status.review.stop();
}
bool TRANSIENT::is_step_rejected () const [inline, private, virtual]
Reimplemented from SIM.
Definition at line 90 of file s_tr.h.
References scREJECT, and step_cause().
{return (step_cause() > scREJECT);}
bool TRANSIENT::next ()
Definition at line 218 of file s_tr_swp.cc.
References _accepted, _converged, _dtmax, SIM_DATA::_dtmin, SIM_DATA::_eq, CKT_BASE::_sim, SIM_DATA::_time0, _time_by_ambiguous_event, _time_by_error_estimate, _time_by_iteration_count, _time_by_user_request, _tstop, SIM_DATA::analysis_is_tran_dynamic(), check_consistency, check_consistency2, error(), SIM_DATA::exceeds_iteration_limit(), itested, SIM_DATA::mark_inc_mode_bad(), NEVER, scADT, scAMBEVENT, scEVENTQ, scINITIAL, scITER_A, scITER_R, scNO_ADVANCE, scREJECT, scSKIP, scSMALL, scTE, scUSER, scZERO, set_step_cause(), status(), TR::step_cause, step_cause(), steps_total_, time1, trace0, trace1, trace2, trace3, OPT::TRLOW, OPT::trstepgrow, OPT::trstephold, OPT::trstepshrink, untested, and up_order().
Referenced by sweep().
{
  ::status.review.start();
  double old_dt = _sim->_time0 - time1;
  assert(old_dt >= 0);
  double newtime = NEVER;
  double new_dt = NEVER;
  STEP_CAUSE new_control = scNO_ADVANCE;
  if (_sim->_time0 == time1) {
    // initial step -- could be either t==0 or continue
    // for the first time, just guess
    // make it 100x smaller than expected
    new_dt = std::max(_dtmax/100., _sim->_dtmin);
    newtime = _sim->_time0 + new_dt;
    new_control = scINITIAL;
  }else if (!_converged) {
    new_dt = old_dt / OPT::trstepshrink;
    newtime = _time_by_iteration_count = time1 + new_dt;
    new_control = scITER_R;
  }else{
    double reftime;
    if (_accepted) {
      reftime = _sim->_time0;
      trace0("accepted");
    }else{
      reftime = time1;
      trace0("rejected");
    }
    trace2("", step_cause(), old_dt);
    trace3("", time1, _sim->_time0, reftime);
    newtime = _time_by_user_request;
    new_dt = newtime - reftime;
    new_control = scUSER;
    double fixed_time = newtime;
    double almost_fixed_time = newtime;
    check_consistency();
    // event queue, events that absolutely will happen
    // exact time.  NOT ok to move or omit, even by _sim->_dtmin
    // some action is associated with it.
    if (!_sim->_eq.empty() && _sim->_eq.top() < newtime) {
      newtime = _sim->_eq.top();
      new_dt = newtime - reftime;
      if (new_dt < _sim->_dtmin) {
        //new_dt = _sim->_dtmin;
        //newtime = reftime + new_dt;
      }else{
      }
      new_control = scEVENTQ;
      fixed_time = newtime;
      almost_fixed_time = newtime;
      check_consistency();
    }else{
    }
    // device events that may not happen
    // not sure of exact time.  will be rescheduled if wrong.
    // ok to move by _sim->_dtmin.  time is not that accurate anyway.
    if (_time_by_ambiguous_event < newtime - _sim->_dtmin) {
      if (_time_by_ambiguous_event < time1 + 2*_sim->_dtmin) {untested();
        double mintime = time1 + 2*_sim->_dtmin;
        if (newtime - _sim->_dtmin < mintime) {untested();
          newtime = mintime;
          new_control = scAMBEVENT;
        }else{untested();
        }
      }else{
        newtime = _time_by_ambiguous_event;
        new_control = scAMBEVENT;
      }
      new_dt = newtime - reftime;
      almost_fixed_time = newtime;
      check_consistency();
    }else{
    }
    // device error estimates
    if (_time_by_error_estimate < newtime - _sim->_dtmin) {
      newtime = _time_by_error_estimate;
      new_dt = newtime - reftime;
      new_control = scTE;
      check_consistency();
    }else{
    }
    // skip parameter
    if (new_dt > _dtmax) {
      if (new_dt > _dtmax + _sim->_dtmin) {
        new_control = scSKIP;
      }else{
      }
      new_dt = _dtmax;
      newtime = reftime + new_dt;
      check_consistency();
    }else{
    }
    // converged but with more iterations than we like
    if ((new_dt > (old_dt + _sim->_dtmin) * OPT::trstephold)
        && _sim->exceeds_iteration_limit(OPT::TRLOW)) {untested();
      assert(_accepted);
      new_dt = old_dt * OPT::trstephold;
      newtime = reftime + new_dt;
      new_control = scITER_A;
      check_consistency();
    }else{
    }
    // limit growth
    if (_sim->analysis_is_tran_dynamic() && new_dt > old_dt * OPT::trstepgrow) {untested();
      new_dt = old_dt * OPT::trstepgrow;
      newtime = reftime + new_dt;
      new_control = scADT;
      check_consistency();
    }else{
    }
    // quantize
    if (newtime < almost_fixed_time) {
      assert(new_dt >= 0);
      if (newtime > reftime + old_dt*.8
          && newtime < reftime + old_dt*1.5
          && reftime + old_dt <= almost_fixed_time) {
        // new_dt is close enough to old_dt.
        // use old_dt, to avoid a step change.
        new_dt = old_dt;
        newtime = reftime + new_dt;
        if (newtime > almost_fixed_time) {untested();
          new_control = scAMBEVENT;
          newtime = almost_fixed_time;
          new_dt = newtime - reftime;
        }else{
        }
        check_consistency();
      }else{
        // There will be a step change.
        // Try to choose one that we will keep for a while.
        // Choose new_dt to be in integer fraction of target_dt.
        double target_dt = fixed_time - reftime;
        assert(target_dt >= new_dt);
        double steps = 1 + floor((target_dt - _sim->_dtmin) / new_dt);
        assert(steps > 0);
        new_dt = target_dt / steps;
        newtime = reftime + new_dt;
        check_consistency();
      }
    }else{
      assert(newtime == almost_fixed_time);
    }
    // trap time step too small
    if (!_accepted && new_dt < _sim->_dtmin) {untested();
      new_dt = _sim->_dtmin;
      newtime = reftime + new_dt;
      new_control = scSMALL;
      check_consistency();
    }else{
    }
    // if all that makes it close to user_requested, make it official
    if (up_order(newtime-_sim->_dtmin, _time_by_user_request, newtime+_sim->_dtmin)) {
      //newtime = _time_by_user_request;
      //new_dt = newtime - reftime;
      new_control = scUSER;
      check_consistency();
    }else{
    }
    check_consistency();
    assert(!_accepted || newtime > _sim->_time0);
    assert(_accepted || newtime <= _sim->_time0);
  }
  set_step_cause(new_control);
  /* got it, I think */
  /* check to be sure */
  if (newtime < time1 + _sim->_dtmin) {itested();
    /* It's really bad. */
    /* Reject the most recent step, back up as much as possible, */
    /* and creep along */
    assert(!_accepted);
    assert(step_cause() < scREJECT);
    assert(step_cause() >= 0);
    error(bDANGER,"non-recoverable " + TR::step_cause[step_cause()] + "\n");
    error(bDANGER, "newtime=%e  rejectedtime=%e  oldtime=%e  using=%e\n",
          newtime, _sim->_time0, time1, time1 + _sim->_dtmin);
    newtime = time1 + _sim->_dtmin;
    set_step_cause(scSMALL);
    //check_consistency2();
    throw Exception("tried everything, still doesn't work, giving up");
    //}else if (newtime <= _sim->_time0 - _sim->_dtmin) {
  }else if (newtime < _sim->_time0) {
    /* Reject the most recent step. */
    /* We have faith that it will work with a smaller time step. */
    assert(!_accepted);
    assert(newtime >= time1 + _sim->_dtmin);
    error(bLOG, "backwards time step\n");
    error(bLOG, "newtime=%e  rejectedtime=%e  oldtime=%e\n", newtime, _sim->_time0, time1);
    set_step_cause(scREJECT);
    _sim->mark_inc_mode_bad();
    check_consistency2();
  }else if (newtime < _sim->_time0 + _sim->_dtmin) {untested();
    /* Another evaluation at the same time. */
    /* Keep the most recent step, but creep along. */
    assert(newtime > _sim->_time0 - _sim->_dtmin);
    error(bDANGER, "zero time step\n");
    error(bDANGER, "newtime=%e  rejectedtime=%e  oldtime=%e\n", newtime, _sim->_time0, time1);
    if (_accepted) {untested();
      time1 = _sim->_time0;
    }else{untested();
      assert(_converged);
    }
    check_consistency2();
    newtime = _sim->_time0 + _sim->_dtmin;
    if (newtime > _time_by_user_request) {untested();
      newtime = _time_by_user_request;
      set_step_cause(scUSER);
    }else{untested();
    }
    set_step_cause(scZERO);
    check_consistency2();
  }else{
    assert(_accepted);
    assert(newtime >= _sim->_time0 + _sim->_dtmin);
    /* All is OK.  Moving on. */
    /* Keep value of newtime */
    time1 = _sim->_time0;
    check_consistency2();
  }
  _sim->_time0 = newtime;
  /* advance event queue (maybe) */
  /* We already looked at it.  Dump what's on top if we took it. */
  while (!_sim->_eq.empty() && _sim->_eq.top() <= _sim->_time0) {
    trace1("eq", _sim->_eq.top());
    _sim->_eq.pop();
  }
  while (!_sim->_eq.empty() && _sim->_eq.top() < _sim->_time0 + _sim->_dtmin) {itested();
    trace1("eq-extra", _sim->_eq.top());
    _sim->_eq.pop();
  }
  //BUG// what if it is later rejected?  It's lost!
  check_consistency2();
  ++::status.hidden_steps;
  ++steps_total_;
  ::status.review.stop();
  trace0("next");
  return (_sim->_time0 <= _tstop + _sim->_dtmin);
}
void TRANSIENT::options (CS & Cmd) [protected]
Definition at line 165 of file s_tr_set.cc.
References _cold, _dtmax_in, _dtmin_in, _dtratio_in, SIM::_out, SIM::_scope, CKT_BASE::_sim, _skip_in, SIM_DATA::_temp_c, _trace, SIM_DATA::_uic, BIGBIG, CS::check(), CS::cursor(), OPT::dtmin, OPT::dtratio, PARAMETER< T >::e_val(), Get(), initio(), mOFFSET, CS::more(), IO::mstdout, ONE_OF, outset(), SIM::plotlist(), IO::plotout, IO::plotset, OMSTREAM::reset(), Set(), PROBELIST::size(), CS::stuck(), SIM::tALLTIME, OPT::temp_c, SIM::tITERATION, SIM::tNONE, SIM::tREJECTED, SIM::tUNDER, SIM::tVERBOSE, CS::umatch(), and CS::warn().
Referenced by setup().
{
  _out = IO::mstdout;
  _out.reset(); //BUG// don't know why this is needed
  _sim->_temp_c = OPT::temp_c;
  bool ploton = IO::plotset  &&  plotlist().size() > 0;
  _sim->_uic = _cold = false;
  _trace = tNONE;
  unsigned here = Cmd.cursor();
  do{
    ONE_OF
      || Get(Cmd, "c{old}",        &_cold)
      || Get(Cmd, "dte{mp}",       &_sim->_temp_c,  mOFFSET, OPT::temp_c)
      || Get(Cmd, "dtma{x}",       &_dtmax_in)
      || Get(Cmd, "dtmi{n}",       &_dtmin_in)
      || Get(Cmd, "dtr{atio}",     &_dtratio_in)
      || Get(Cmd, "pl{ot}",        &ploton)
      || Get(Cmd, "sk{ip}",        &_skip_in)
      || Get(Cmd, "te{mperature}", &_sim->_temp_c)
      || Get(Cmd, "uic",           &_sim->_uic)
      || (Cmd.umatch("tr{ace} {=}") &&
          (ONE_OF
           || Set(Cmd, "n{one}",      &_trace, tNONE)
           || Set(Cmd, "o{ff}",       &_trace, tNONE)
           || Set(Cmd, "w{arnings}",  &_trace, tUNDER)
           || Set(Cmd, "a{lltime}",   &_trace, tALLTIME)
           || Set(Cmd, "r{ejected}",  &_trace, tREJECTED)
           || Set(Cmd, "i{terations}",&_trace, tITERATION)
           || Set(Cmd, "v{erbose}",   &_trace, tVERBOSE)
           || Cmd.warn(bWARNING, "need none, off, warnings, alltime, "
                       "rejected, iterations, verbose")
           )
          )
      || outset(Cmd,&_out)
      ;
  }while (Cmd.more() && !Cmd.stuck(&here));
  Cmd.check(bWARNING, "what's this?");
  IO::plotout = (ploton) ? IO::mstdout : OMSTREAM();
  initio(_out);
  _dtmax_in.e_val(BIGBIG, _scope);
  _dtmin_in.e_val(OPT::dtmin, _scope);
  _dtratio_in.e_val(OPT::dtratio, _scope);
  _skip_in.e_val(1, _scope);
}
void TRANSIENT::reject ()
Definition at line 527 of file s_tr_swp.cc.
References SIM_DATA::_acceptq, CKT_BASE::_sim, status(), and steps_rejected_.
Referenced by sweep().
{
  ::status.accept.start();
  _sim->_acceptq.clear();
  ++steps_rejected_;
  ::status.accept.stop();
}
bool TRANSIENT::review () [private]
Definition at line 474 of file s_tr_swp.cc.
References SIM_DATA::_dtmin, TIME_PAIR::_error_estimate, TIME_PAIR::_event, CKT_BASE::_sim, SIM_DATA::_time0, _time_by_ambiguous_event, _time_by_error_estimate, CARD_LIST::card_list, SIM_DATA::count_iterations(), iTOTAL, status(), time1, and CARD_LIST::tr_review().
Referenced by sweep().
{
  ::status.review.start();
  _sim->count_iterations(iTOTAL);
  TIME_PAIR time_by = CARD_LIST::card_list.tr_review();
  _time_by_error_estimate = time_by._error_estimate;
  // limit minimum time step
  // 2*_sim->_dtmin because _time[1] + _sim->_dtmin might be == _time[0].
  if (time_by._event < time1 + 2*_sim->_dtmin) {
    _time_by_ambiguous_event = time1 + 2*_sim->_dtmin;
  }else{
    _time_by_ambiguous_event = time_by._event;
  }
  // force advance when time too close to previous
  if (std::abs(_time_by_ambiguous_event - _sim->_time0) < 2*_sim->_dtmin) {
    _time_by_ambiguous_event = _sim->_time0 + 2*_sim->_dtmin;
  }else{
  }
  if (time_by._error_estimate < time1 + 2*_sim->_dtmin) {
    _time_by_error_estimate = time1 + 2*_sim->_dtmin;
  }else{
    _time_by_error_estimate = time_by._error_estimate;
  }
  if (std::abs(_time_by_error_estimate - _sim->_time0) < 1.1*_sim->_dtmin) {
    _time_by_error_estimate = _sim->_time0 + 1.1*_sim->_dtmin;
  }else{
  }
  ::status.review.stop();
  return (_time_by_error_estimate > _sim->_time0  &&  _time_by_ambiguous_event > _sim->_time0);
}
void TRANSIENT::set_step_cause (STEP_CAUSE C) [private]
Definition at line 145 of file s_tr_swp.cc.
References itested, scADT, scAMBEVENT, scEVENTQ, scINITIAL, scITER_A, scITER_R, scNO_ADVANCE, scREJECT, scSKIP, scSMALL, scTE, scUSER, scZERO, status(), and untested.
Referenced by first(), and next().
{
  switch (C) {
  case scITER_A:untested();
  case scADT:untested();
  case scITER_R:
  case scINITIAL:
  case scSKIP:
  case scTE:
  case scAMBEVENT:
  case scEVENTQ:
  case scUSER:
    ::status.control = C;
    break;
  case scNO_ADVANCE:untested();
  case scZERO:untested();
  case scSMALL:itested();
  case scREJECT:
    ::status.control += C;
    break;
  }
}
void TRANSIENT::setup (CS & Cmd) [private, virtual]
Implements SIM.
Reimplemented in anonymous_namespace{s_fo.cc}::FOURIER.
Definition at line 36 of file s_tr_set.cc.
References _cold, _cont, _dtmax, _dtmax_in, SIM_DATA::_dtmin, _dtmin_in, _dtratio_in, SIM_DATA::_freq, SIM_DATA::_last_time, SIM::_scope, CKT_BASE::_sim, _skip_in, SIM_DATA::_time0, _tstart, _tstep, _tstop, PARAMETER< T >::e_val(), PARAMETER< T >::has_good_value(), PARAMETER< T >::has_hard_value(), CS::is_float(), CS::is_pfloat(), itested, CS::match1(), min(), NOT_INPUT, options(), time1, and untested.
{
  _tstart.e_val(NOT_INPUT, _scope);
  _tstop.e_val(NOT_INPUT, _scope);
  _tstep.e_val(NOT_INPUT, _scope);
  _cont = true;
  if (Cmd.match1("'\"({") || Cmd.is_pfloat()) {
    PARAMETER<double> arg1, arg2, arg3;
    Cmd >> arg1;
    if (Cmd.match1("'\"({") || Cmd.is_float()) {
      Cmd >> arg2;
    }else{itested();
    }
    if (Cmd.match1("'\"({") || Cmd.is_float()) {
      Cmd >> arg3;
    }else{
    }
    if (arg3.has_hard_value()) {            /* 3 args: all */
      assert(arg2.has_hard_value());
      assert(arg1.has_hard_value());
      arg1.e_val(0.,_scope);
      arg3.e_val(0.,_scope);
      if (arg3 == 0.) {                     /* spice (illogical) order */
        _tstart = arg3;                     /* _tstep _tstop _tstart */
        _tstop  = arg2;
        _tstep  = arg1;
      }else if (arg1 == 0.) {               /* eca (logical) order: */
        _tstart = arg1;                     /* _tstart _tstop _tstep */
        _tstop  = arg2;
        _tstep  = arg3;
      }else if (arg1 > arg3) {untested();   /* eca (logical) order: */
        _tstart = arg1;                     /* _tstart _tstop _tstep */
        _tstop  = arg2;
        _tstep  = arg3;
      }else{untested();                     /* spice (illogical) order */
        _tstart = arg3;                     /* _tstep _tstop _tstart */
        _tstop  = arg2;
        _tstep  = arg1;
      }
    }else if (arg2.has_hard_value()) {      /* 2 args */
      assert(arg1.has_hard_value());
      arg1.e_val(0.,_scope);
      arg2.e_val(0.,_scope);
      if (arg1 == 0.) {untested();          /* 2 args: _tstart, _tstop */
        _tstart = arg1;
        _tstop  = arg2;
        /* _tstep unchanged */
      }else if (arg1 >= arg2) {             /* 2 args: _tstop, _tstep */
        _tstart = _sim->_last_time;
        _tstop  = arg1;
        _tstep  = arg2;
      }else{ /* arg1 < arg2 */              /* 2 args: _tstep, _tstop */
        _tstart = "NA"; /* 0 */             /* spice order */
        _tstop  = arg2;
        _tstep  = arg1;
      }
    }else{itested();
      assert(arg1.has_hard_value());
      arg1.e_val(0.,_scope);
      if (arg1 > _sim->_last_time) {untested();     /* 1 arg: _tstop */
        _tstart = _sim->_last_time;
        _tstop  = arg1;
        /* _tstep unchanged */
      }else if (arg1 == 0.) {itested();     /* 1 arg: _tstart */
        double oldrange = _tstop - _tstart;
        _tstart = 0.;
        _tstop  = oldrange;
        /* _tstep unchanged */
      }else{untested(); /* arg1 < _sim->_last_time, but not 0 */  /* 1 arg: _tstep */
        double oldrange = _tstop - _tstart;
        _tstart = _sim->_last_time;
        _tstop  = _sim->_last_time + oldrange;
        _tstep  = arg1;
      }
    }
  }else{ /* no args */
    double oldrange = _tstop - _tstart;
    _tstart = _sim->_last_time;
    _tstop  = _sim->_last_time + oldrange;
    /* _tstep unchanged */
  }
  if (Cmd.match1("'\"({") || Cmd.is_pfloat()) {
    Cmd >> _dtmax_in;
  }else{
  }
  options(Cmd);
  _tstart.e_val(0., _scope);
  _tstop.e_val(NOT_INPUT, _scope);
  _tstep.e_val(NOT_INPUT, _scope);
  if  (_cold || _tstart < _sim->_last_time  ||  _sim->_last_time <= 0.) {
    _cont = false;
    time1 = _sim->_time0 = 0.;
  }else{
    _cont = true;
    time1 = _sim->_time0 = _sim->_last_time;
  }
  _sim->_freq = ((_tstop > _tstart) ? (1 / (_tstop - _tstart)) : (0.));
  if (!_tstep.has_good_value()) {
    throw Exception("transient: time step is required");
  }else if (_tstep==0.) {itested();
    throw Exception("time step = 0");
  }else{
  }
  if (_dtmax_in.has_hard_value()) {
    _dtmax = _dtmax_in;
  }else if (_skip_in.has_hard_value()) {
    _dtmax = _tstep / double(_skip_in);
  }else{
    _dtmax = std::min(_dtmax_in, _tstep);
  }
  if (_dtmin_in.has_hard_value()) {
    _sim->_dtmin = _dtmin_in;
  }else if (_dtratio_in.has_hard_value()) {
    _sim->_dtmin = _dtmax / _dtratio_in;
  }else{
    // use larger of soft values
    _sim->_dtmin = std::max(double(_dtmin_in), _dtmax/_dtratio_in);
  }
}
std::string TRANSIENT::status () const [virtual]
Reimplemented from CKT_BASE.
Reimplemented in anonymous_namespace{s_fo.cc}::FOURIER.
Definition at line 45 of file s_tr.cc.
References steps_accepted(), steps_rejected(), steps_total(), and to_string().
Referenced by accept(), do_it(), first(), next(), reject(), review(), and set_step_cause().
{
  return "transient timesteps: accepted=" + to_string(steps_accepted())
    + ", rejected=" + to_string(steps_rejected())
    + ", total=" + to_string(steps_total()) + "\n";
}
int TRANSIENT::step_cause () const
Definition at line 168 of file s_tr_swp.cc.
References STATUS::control, and status.
Referenced by is_step_rejected(), next(), and sweep().
{
  return ::status.control;
}
static int TRANSIENT::steps_accepted () [inline, static]
Definition at line 120 of file s_tr.h.
References steps_accepted_.
Referenced by status().
{return steps_accepted_;}
static int TRANSIENT::steps_rejected () [inline, static]
Definition at line 121 of file s_tr.h.
References steps_rejected_.
Referenced by status().
{return steps_rejected_;}
static int TRANSIENT::steps_total () [inline, static]
Definition at line 122 of file s_tr.h.
References steps_total_.
Referenced by status().
{return steps_total_;}
void TRANSIENT::sweep () [protected, virtual]
Implements SIM.
Definition at line 54 of file s_tr_swp.cc.
References _accepted, SIM_DATA::_bypass_ok, _cont, _converged, SIM_DATA::_dtmin, SIM_DATA::_genout, SIM_DATA::_late_evalq, SIM_DATA::_phase, CKT_BASE::_sim, _stepno, SIM_DATA::_time0, _time_by_user_request, _trace, _tstart, _tstep, _tstop, accept(), SIM::advance_time(), CARD_LIST::card_list, SIM_DATA::clear_limit(), OPT::DCBIAS, CARD_LIST::do_tr(), error(), first(), gen(), SIM::head(), itested, SIM_DATA::keep_voltages(), next(), SIM::outdata(), p_INIT_DC, p_RESTORE, p_TRAN, OPT::quitconvfail, reject(), SIM_DATA::restore_voltages(), review(), scUSER, SIM_DATA::set_inc_mode_bad(), SIM::solve(), SIM::solve_with_homotopy(), step_cause(), SIM::tALLTIME, time1, CARD_LIST::tr_begin(), CARD_LIST::tr_restore(), SIM::tREJECTED, OPT::TRHIGH, SIM_DATA::uic_now(), untested, up_order(), and SIM_DATA::zero_voltages().
{
  _sim->_phase = p_INIT_DC;
  head(_tstart, _tstop, "Time");
  _sim->_bypass_ok = false;
  _sim->set_inc_mode_bad();
  if (_cont) {  // use the data from last time
    _sim->_phase = p_RESTORE;
    _sim->restore_voltages();
    CARD_LIST::card_list.tr_restore();
  }else{
    _sim->clear_limit();
    CARD_LIST::card_list.tr_begin();
  }
  first();
  _sim->_genout = gen();
  if (_sim->uic_now()) {
    advance_time();
    _sim->zero_voltages();
    CARD_LIST::card_list.do_tr();    //evaluate_models
    while (!_sim->_late_evalq.empty()) {itested(); //BUG// encapsulation violation
      _sim->_late_evalq.front()->do_tr_last();
      _sim->_late_evalq.pop_front();
    }
    _converged = true;
  }else{
    _converged = solve_with_homotopy(OPT::DCBIAS,_trace);
    if (!_converged) {
      error(bWARNING, "did not converge\n");
    }else{
    }
  }
  review();
  _accepted = true;
  accept();
  {
    bool printnow = (_sim->_time0 == _tstart || _trace >= tALLTIME);
    if (printnow) {
      _sim->keep_voltages();
      outdata(_sim->_time0);
    }else{untested();
    }
  }
  while (next()) {
    _sim->_bypass_ok = false;
    _sim->_phase = p_TRAN;
    _sim->_genout = gen();
    _converged = solve(OPT::TRHIGH,_trace);
    _accepted = _converged && review();
    if (_accepted) {
      assert(_converged);
      assert(_sim->_time0 <= _time_by_user_request);
      accept();
      if (step_cause() == scUSER) {
        assert(up_order(_sim->_time0-_sim->_dtmin, _time_by_user_request, _sim->_time0+_sim->_dtmin));
        ++_stepno;
        _time_by_user_request += _tstep;        /* advance user time */
      }else{
      }
      assert(_sim->_time0 < _time_by_user_request);
    }else{
      reject();
      assert(time1 < _time_by_user_request);
    }
    {
      bool printnow =
        (_trace >= tREJECTED)
        || (_accepted && ((_trace >= tALLTIME)
                          || (step_cause() == scUSER && _sim->_time0+_sim->_dtmin > _tstart)));
      if (printnow) {
        _sim->keep_voltages();
        outdata(_sim->_time0);
      }else{
      }
    }
    if (!_converged && OPT::quitconvfail) {untested();
      outdata(_sim->_time0);
      throw Exception("convergence failure, giving up");
    }else{
    }
  }
}
Member Data Documentation
bool TRANSIENT::_accepted [private]
Definition at line 113 of file s_tr.h.
Referenced by next(), and sweep().
bool TRANSIENT::_cold [protected]
Definition at line 103 of file s_tr.h.
Referenced by options(), and setup().
bool TRANSIENT::_cont [protected]
Definition at line 104 of file s_tr.h.
Referenced by setup(), and sweep().
bool TRANSIENT::_converged [private]
Definition at line 112 of file s_tr.h.
Referenced by next(), and sweep().
double TRANSIENT::_dtmax [protected]
Definition at line 102 of file s_tr.h.
Referenced by next(), and setup().
PARAMETER<double> TRANSIENT::_dtmax_in [protected]
Definition at line 99 of file s_tr.h.
Referenced by options(), and setup().
PARAMETER<double> TRANSIENT::_dtmin_in [protected]
Definition at line 98 of file s_tr.h.
Referenced by options(), and setup().
PARAMETER<double> TRANSIENT::_dtratio_in [protected]
Definition at line 97 of file s_tr.h.
Referenced by options(), and setup().
PARAMETER<int> TRANSIENT::_skip_in [protected]
Definition at line 100 of file s_tr.h.
Referenced by options(), and setup().
int TRANSIENT::_stepno [protected]
Definition at line 105 of file s_tr.h.
Referenced by first(), and sweep().
double TRANSIENT::_time_by_ambiguous_event [private]
Definition at line 111 of file s_tr.h.
Referenced by next(), and review().
double TRANSIENT::_time_by_error_estimate [private]
Definition at line 110 of file s_tr.h.
Referenced by next(), and review().
double TRANSIENT::_time_by_iteration_count [private]
Definition at line 108 of file s_tr.h.
Referenced by next().
double TRANSIENT::_time_by_user_request [private]
Definition at line 109 of file s_tr.h.
Referenced by first(), next(), and sweep().
TRACE TRANSIENT::_trace [private]
Definition at line 107 of file s_tr.h.
Referenced by options(), and sweep().
PARAMETER<double> TRANSIENT::_tstart [protected]
Definition at line 94 of file s_tr.h.
Referenced by first(), setup(), and sweep().
PARAMETER<double> TRANSIENT::_tstep [protected]
Definition at line 96 of file s_tr.h.
Referenced by first(), setup(), and sweep().
PARAMETER<double> TRANSIENT::_tstop [protected]
Definition at line 95 of file s_tr.h.
Referenced by next(), setup(), and sweep().
int TRANSIENT::steps_accepted_ [static, private]
Definition at line 116 of file s_tr.h.
Referenced by accept(), and steps_accepted().
int TRANSIENT::steps_rejected_ [static, private]
Definition at line 117 of file s_tr.h.
Referenced by reject(), and steps_rejected().
int TRANSIENT::steps_total_ [static, private]
Definition at line 118 of file s_tr.h.
Referenced by next(), and steps_total().
double TRANSIENT::time1 [protected]
Definition at line 101 of file s_tr.h.
Referenced by first(), next(), review(), setup(), and sweep().
The documentation for this class was generated from the following files:
savant/gnucap/src/s_tr.h
savant/gnucap/src/s_tr.cc
savant/gnucap/src/s_tr_set.cc
savant/gnucap/src/s_tr_swp.cc