gnucap: savant/gnucap/src/e_base.h File Reference
savant/gnucap/src/e_base.h File Reference
#include "md.h"
Classes
class CKT_BASE
Functions
bool exists (const CKT_BASE *c)
Function Documentation
bool exists (const CKT_BASE * c) [inline]
Definition at line 70 of file e_base.h.
Referenced by anonymous_namespace{lang_spectre.cc}::CMD_MODEL::do_it(), anonymous_namespace{lang_verilog.cc}::CMD_PARAMSET::do_it(), anonymous_namespace{lang_spice.cc}::CMD_MODEL::do_it(), anonymous_namespace{s_dc.cc}::DCOP::finish(), CARD::long_label(), CKT_BASE::probe(), and anonymous_namespace{s_dc.cc}::DC::setup().
{return c!=0;}