gnucap: Token Class Reference
Token Class Reference
#include <m_expression.h>
Public Member Functions
void parse (CS &)
void dump (std::ostream &) const
virtual ~Token ()
virtual Token * clone () const =0
const std::string & name () const
const Base * data () const
const std::string & aRgs () const
const std::string full_name () const
virtual void stack_op (Expression *) const
bool operator== (const Token &P)
Protected Member Functions
Token (const std::string Name, const Base *Data, const std::string Args)
Token (const Token &P)
Private Attributes
std::string _name
const Base * _data
std::string _aRgs
Detailed Description
Definition at line 30 of file m_expression.h.
Constructor & Destructor Documentation
Token::Token (const std::string Name, const Base * Data, const std::string Args) [inline, explicit, protected]
Definition at line 42 of file m_expression.h.
    : _name(Name), _data(Data), _aRgs(Args) {}
Token::Token (const Token & P) [inline, explicit, protected]
Definition at line 44 of file m_expression.h.
References _data.
    : Base(), _name(P._name), _data(P._data), _aRgs(P._aRgs) {assert(!_data);}
virtual Token::~Token () [inline, virtual]
Definition at line 47 of file m_expression.h.
References _data.
{if (_data) {delete _data;}else{}}
Member Function Documentation
const std::string& Token::aRgs () const [inline]
Definition at line 51 of file m_expression.h.
References _aRgs.
Referenced by full_name(), Token_BINOP::op(), Token_UNARY::op(), and operator==().
{return _aRgs;}
virtual Token* Token::clone () const [pure virtual]
Implemented in Token_CONSTANT, Token_UNARY, Token_PARLIST, Token_STOP, Token_BINOP, and Token_SYMBOL.
const Base* Token::data () const [inline]
Definition at line 50 of file m_expression.h.
References _data.
Referenced by Token_BINOP::op(), Token_UNARY::op(), operator==(), Token_BINOP::stack_op(), and Token_UNARY::stack_op().
{return _data;}
void Token::dump (std::ostream & out) const [virtual]
Implements Base.
Definition at line 27 of file m_expression_dump.cc.
References _name, and itested.
{itested();
  out << _name << ' ';
}
const std::string Token::full_name () const [inline]
Definition at line 52 of file m_expression.h.
References aRgs(), and name().
Referenced by Expression::dump().
{return name() + aRgs();}
const std::string& Token::name () const [inline]
Definition at line 49 of file m_expression.h.
References _name.
Referenced by full_name(), Token_BINOP::op(), Token_UNARY::op(), operator==(), Token_SYMBOL::stack_op(), Token_BINOP::stack_op(), and Token_PARLIST::stack_op().
{return _name;}
bool Token::operator== (const Token & P) [inline]
Definition at line 54 of file m_expression.h.
References aRgs(), data(), name(), and untested.
                                  {untested();return (typeid(*this)==typeid(P))
      && (data()==P.data()) && (name()==P.name()) && (aRgs()==P.aRgs());}
void Token::parse (CS &) [inline, virtual]
Implements Base.
Definition at line 38 of file m_expression.h.
References unreachable.
{unreachable();}
virtual void Token::stack_op (Expression *) const [inline, virtual]
Reimplemented in Token_CONSTANT, Token_UNARY, Token_PARLIST, Token_STOP, Token_BINOP, and Token_SYMBOL.
Definition at line 53 of file m_expression.h.
References unreachable.
{unreachable();}
Member Data Documentation
std::string Token::_aRgs [private]
Definition at line 36 of file m_expression.h.
Referenced by aRgs().
const Base* Token::_data [private]
Definition at line 35 of file m_expression.h.
Referenced by data(), Token(), and ~Token().
std::string Token::_name [private]
Definition at line 34 of file m_expression.h.
Referenced by dump(), and name().
The documentation for this class was generated from the following files:
savant/gnucap/src/m_expression.h
savant/gnucap/src/m_expression_dump.cc