gnucap: DISPATCHER< T > Class Template Reference
DISPATCHER< T > Class Template Reference
#include <l_dispatcher.h>
Classes
class INSTALL
Public Types
typedef std::map< std::string,
T * >::const_iterator const_iterator
Public Member Functions
DISPATCHER ()
const_iterator begin () const
const_iterator end () const
void install (const std::string &s, T *p)
void uninstall (T *p)
void uninstall (const std::string &s)
T * operator[] (std::string s)
T * operator[] (CS &cmd)
T * clone (std::string s)
Private Attributes
std::map< std::string, T * > * _map
Detailed Description
template<class T>
class DISPATCHER< T >
Definition at line 32 of file l_dispatcher.h.
Member Typedef Documentation
template<class T> typedef std::map<std::string, T*>::const_iterator DISPATCHER< T >::const_iterator
Definition at line 43 of file l_dispatcher.h.
Constructor & Destructor Documentation
template<class T> DISPATCHER< T >::DISPATCHER () [inline]
Definition at line 36 of file l_dispatcher.h.
               {
    if (!_map) {
      _map = new std::map<std::string, T*>;
    }else{
    }
  }
Member Function Documentation
template<class T> const_iterator DISPATCHER< T >::begin () const [inline]
Definition at line 46 of file l_dispatcher.h.
{assert(_map); return _map->begin();}
template<class T> T* DISPATCHER< T >::clone (std::string s) [inline]
Definition at line 162 of file l_dispatcher.h.
References itested.
{
    T* proto = (*this)[s];
    if (proto) {
      return proto->clone();
    }else{itested();
      return NULL;
    }
  }
template<class T> const_iterator DISPATCHER< T >::end () const [inline]
Definition at line 47 of file l_dispatcher.h.
{assert(_map); return _map->end();}
template<class T> void DISPATCHER< T >::install (const std::string & s, T * p) [inline]
Definition at line 49 of file l_dispatcher.h.
References error(), anonymous_namespace{c_genrat.cc}::p, to_string(), trace0, and trace2.
{
    assert(s.find(',', 0) == std::string::npos);
    if (!_map) {
      _map = new std::map<std::string, T*>;
    }else{
    }
    trace0(s.c_str());
    // loop over all keys, separated by '|'
    for (std::string::size_type                 // bss: begin sub-string
         bss = 0, ess = s.find('|', bss);       // ess: end sub-string
         bss != std::string::npos;
         bss = (ess != std::string::npos) ? ess+1 : std::string::npos,
           ess = s.find('|', bss)) {
      std::string name = s.substr(bss,
                (ess != std::string::npos) ? ess-bss : std::string::npos);
      trace2(name.c_str(), bss, ess);
      if (name == "") {
        // quietly ignore empty string
      }else if ((*_map)[name]) {
        // duplicate .. stash the old one so we can get it back
        error(bWARNING, name + ": already installed, replacing\n");
        std::string save_name = name + ":0";
        for (int ii = 0; (*_map)[save_name]; ++ii) {
          save_name = name + ":" + to_string(ii);
        }
        (*_map)[save_name] = (*_map)[name];
        error(bWARNING, "stashing as " + save_name + "\n");
      }else{
        // it's new, just put it in
      }
      (*_map)[name] = p;
    }
  }
template<class T> T* DISPATCHER< T >::operator[] (std::string s) [inline]
Definition at line 137 of file l_dispatcher.h.
References OPT::case_insensitive, and notstd::to_lower().
{
    assert(_map);
    T* rv = (*_map)[s];
    if (!rv && OPT::case_insensitive) {
      notstd::to_lower(&s);
      rv = (*_map)[s];
    }else{
    }
    return rv;
  }
template<class T> T* DISPATCHER< T >::operator[] (CS & cmd) [inline]
Definition at line 148 of file l_dispatcher.h.
References CS::cursor(), anonymous_namespace{c_genrat.cc}::p, and CS::reset().
{
    unsigned here = cmd.cursor();
    std::string s;
    cmd >> s;
    //------------------------
    T* p = (*this)[s];
    //------------------------
    if (!p) {
      cmd.reset(here);
    }else{
    }
    return p;
  }
template<class T> void DISPATCHER< T >::uninstall (T * p) [inline]
Definition at line 83 of file l_dispatcher.h.
                       {
    assert(_map);
    for (typename std::map<std::string, T*>::iterator
         ii = _map->begin();
         ii != _map->end();
         ++ii) {
      if (ii->second == p) {
        ii->second = NULL;
      }else{
      }
    }
#if !defined(NDEBUG)
    for (typename std::map<std::string, T*>::iterator
         ii = _map->begin();
         ii != _map->end();
         ++ii) {
      assert(ii->second != p);
    }
#endif
  }
template<class T> void DISPATCHER< T >::uninstall (const std::string & s) [inline]
Definition at line 104 of file l_dispatcher.h.
References error(), and to_string().
{
    assert(_map);
    // loop over all keys, separated by '|'
    for (std::string::size_type                 // bss: begin sub-string
         bss = 0, ess = s.find('|', bss);       // ess: end sub-string
         bss != std::string::npos;
         bss = (ess != std::string::npos) ? ess+1 : std::string::npos,
           ess = s.find('|', bss)) {
      std::string name = s.substr(bss,
                (ess != std::string::npos) ? ess-bss : std::string::npos);
      if (name == "") {
        // quietly ignore empty string
      }else if ((*_map)[name]) {
        // delete, try to get back the old one
        int ii = 0;
        std::string save_name = name + ":0";
        for (ii = 0; (*_map)[save_name]; ++ii) {
          save_name = name + ":" + to_string(ii);
        }
        if (ii > 1) {
          save_name = name + ":" + to_string(ii-2);
          (*_map)[name] = (*_map)[save_name];
          (*_map)[save_name] = NULL;
          error(bWARNING, "restoring " + save_name + " as " + name + "\n");
        }else{
          (*_map)[name] = NULL;
        }
      }else{
        error(bWARNING, name + ": not installed, doing nothing\n");
      }
    }
  }
Member Data Documentation
template<class T> std::map<std::string, T*>* DISPATCHER< T >::_map [private]
Definition at line 34 of file l_dispatcher.h.
The documentation for this class was generated from the following file:
savant/gnucap/src/l_dispatcher.h