gnucap: CCSRC_BASE Class Reference
CCSRC_BASE Class Reference
#include <e_ccsrc.h>
Public Member Functions
void set_parameters_cc (const std::string &Label, CARD *Parent, COMMON_COMPONENT *Common, double Value, const node_t &N0, const node_t &N1, ELEMENT *Input)
Public Attributes
std::string _input_label
const ELEMENT * _input
Protected Member Functions
CCSRC_BASE ()
CCSRC_BASE (const CCSRC_BASE &p)
~CCSRC_BASE ()
int max_nodes () const
int ext_nodes () const
int min_nodes () const
int matrix_nodes () const
int net_nodes () const
int num_current_ports () const
const std::string current_port_value (int) const
void expand_last ()
bool tr_needs_eval () const
void tr_unload ()
double tr_involts () const
double tr_input () const
double tr_involts_limited () const
double tr_input_limited () const
COMPLEX ac_involts () const
void set_port_by_index (int index, std::string &value)
bool node_is_connected (int i) const
Detailed Description
Definition at line 29 of file e_ccsrc.h.
Constructor & Destructor Documentation
CCSRC_BASE::CCSRC_BASE () [inline, explicit, protected]
Definition at line 32 of file e_ccsrc.h.
    :ELEMENT(), _input_label(), _input(0) {}
CCSRC_BASE::CCSRC_BASE (const CCSRC_BASE & p) [inline, explicit, protected]
Definition at line 34 of file e_ccsrc.h.
    :ELEMENT(p), _input_label(p._input_label), _input(p._input) {}
CCSRC_BASE::~CCSRC_BASE () [inline, protected]
Definition at line 36 of file e_ccsrc.h.
{}
Member Function Documentation
COMPLEX CCSRC_BASE::ac_involts () const [inline, protected, virtual]
Implements ELEMENT.
Definition at line 55 of file e_ccsrc.h.
References IN1, IN2, and untested.
{untested();return _n[IN1]->vac()-_n[IN2]->vac();}
const std::string CCSRC_BASE::current_port_value (int) const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 44 of file e_ccsrc.h.
{return _input_label;};
void CCSRC_BASE::expand_last () [protected, virtual]
Reimplemented from CARD.
Definition at line 27 of file e_ccsrc.cc.
References _input, _input_label, CARD::_n, CARD::find_in_my_scope(), COMPONENT::has_inode(), COMPONENT::has_iv_probe(), IN1, IN2, CARD::long_label(), CARD::n_(), OUT1, OUT2, node_t::set_to_ground(), CARD::subckt(), and untested.
{
  ELEMENT::expand_last();
  if (_input_label != "") {
    _input = dynamic_cast<const ELEMENT*>(find_in_my_scope(_input_label));
  }else{untested();
    // _input already set, an internal element.  example: mutual L.
  }
  if (!_input) {untested();
    throw Exception(long_label() + ": " + _input_label + " cannot be used as current probe");
  }else if (_input->subckt()) {untested();
    throw Exception(long_label() + ": " + _input_label
                    + " has a subckt, cannot be used as current probe");
  }else if (_input->has_inode()) {untested();
    _n[IN1] = _input->n_(IN1);
    _n[IN2].set_to_ground(this);
  }else if (_input->has_iv_probe()) {
    _n[IN1] = _input->n_(OUT1);
    _n[IN2] = _input->n_(OUT2);
  }else{
    throw Exception(long_label() + ": " + _input_label + " cannot be used as current probe");
  }
}
int CCSRC_BASE::ext_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 39 of file e_ccsrc.h.
{return 4;}
int CCSRC_BASE::matrix_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 41 of file e_ccsrc.h.
{return 4;}
int CCSRC_BASE::max_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 38 of file e_ccsrc.h.
{return 3;}
int CCSRC_BASE::min_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 40 of file e_ccsrc.h.
{return 3;}
int CCSRC_BASE::net_nodes () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 42 of file e_ccsrc.h.
{return 2;}
bool CCSRC_BASE::node_is_connected (int i) const [protected, virtual]
Reimplemented from COMPONENT.
Definition at line 62 of file e_ccsrc.cc.
References _input_label.
{
  if (i == 2) {
    return _input_label != "";
  }else{
    return ELEMENT::node_is_connected(i);
  }
}
int CCSRC_BASE::num_current_ports () const [inline, protected, virtual]
Reimplemented from COMPONENT.
Definition at line 43 of file e_ccsrc.h.
{return 1;}
void CCSRC_BASE::set_parameters_cc (const std::string & Label, CARD * Parent, COMMON_COMPONENT * Common, double Value, const node_t & N0, const node_t & N1, ELEMENT * Input)
Definition at line 71 of file e_ccsrc.cc.
References _input, and COMPONENT::set_parameters().
{
  node_t nodes[] = {N0, N1};
  COMPONENT::set_parameters(Label, Owner, Common, Value, 0, 0, 2, nodes);
  _input = Input;
}
void CCSRC_BASE::set_port_by_index (int index, std::string & value) [protected, virtual]
Reimplemented from COMPONENT.
Definition at line 53 of file e_ccsrc.cc.
References _input_label.
{
  if (num == 2) {
    _input_label = Value;
  }else{
    ELEMENT::set_port_by_index(num, Value);
  }
}
double CCSRC_BASE::tr_input () const [inline, protected, virtual]
Reimplemented from ELEMENT.
Definition at line 52 of file e_ccsrc.h.
References untested.
{untested(); return _input->tr_amps();}
double CCSRC_BASE::tr_input_limited () const [inline, protected, virtual]
Reimplemented from ELEMENT.
Definition at line 54 of file e_ccsrc.h.
{return _input->tr_amps();}
double CCSRC_BASE::tr_involts () const [inline, protected, virtual]
Implements ELEMENT.
Definition at line 51 of file e_ccsrc.h.
References dn_diff(), IN1, IN2, and untested.
{untested();return dn_diff(_n[IN1].v0(), _n[IN2].v0());}
double CCSRC_BASE::tr_involts_limited () const [inline, protected, virtual]
Implements ELEMENT.
Definition at line 53 of file e_ccsrc.h.
References IN1, IN2, and COMPONENT::volts_limited().
{return volts_limited(_n[IN1],_n[IN2]);}
bool CCSRC_BASE::tr_needs_eval () const [inline, protected, virtual]
Reimplemented from ELEMENT.
Definition at line 48 of file e_ccsrc.h.
References COMPONENT::is_q_for_eval().
{assert(!is_q_for_eval()); return true;}
void CCSRC_BASE::tr_unload () [inline, protected, virtual]
Reimplemented from CARD.
Definition at line 50 of file e_ccsrc.h.
References ELEMENT::tr_unload_active(), and untested.
{untested(); tr_unload_active();}
Member Data Documentation
const ELEMENT* CCSRC_BASE::_input
Definition at line 65 of file e_ccsrc.h.
Referenced by expand_last(), and set_parameters_cc().
std::string CCSRC_BASE::_input_label
Definition at line 64 of file e_ccsrc.h.
Referenced by expand_last(), node_is_connected(), and set_port_by_index().
The documentation for this class was generated from the following files:
savant/gnucap/src/e_ccsrc.h
savant/gnucap/src/e_ccsrc.cc