gnucap: savant/gnucap/src/io_.h File Reference
savant/gnucap/src/io_.h File Reference
#include "l_lib.h"
Classes
class OMSTREAM
class IO
Functions
const char * octal (int x)
INTERFACE void initio (OMSTREAM &)
void outreset ()
INTERFACE OMSTREAM * outset (CS &, OMSTREAM *)
std::string findfile (const std::string &, const std::string &, int)
void xclose (FILE **)
FILE * xopen (CS &, const char *, const char *)
Variables
const int MAXHANDLE = CHAR_BIT*sizeof(int)-1
Function Documentation
std::string findfile (const std::string & , const std::string & , int)
Definition at line 37 of file io_findf.cc.
References OS::access_ok(), ENDDIR, PATHSEP, and untested.
Referenced by read_startup_files().
{
#ifdef CHECK_LOCAL_FIRST
  if (OS::access_ok(filename, mode)) {
    untested();
    return filename;
  }else{
    untested();
  }
#endif
                                        // for each item in the path
  for (std::string::const_iterator
         p_ptr=path.begin(); p_ptr!=path.end(); ++p_ptr) {
    // p_ptr changed internally                  ^^^^^ skip sep
    std::string target = "";
    while (*p_ptr != PATHSEP  &&  p_ptr != path.end()) { // copy 1 path item
      target += *p_ptr++;
    }
    if (!target.empty() &&  !strchr(ENDDIR,p_ptr[-1])) {
      target += *ENDDIR;                // append '/' if needed
    }else{untested();
    }
    target += filename;
    if (OS::access_ok(target, mode)) {untested();       // found it
      return target;
    }else if (p_ptr==path.end()) {      // ran out of path, didn't find it
      return "";
    }else{                              // else try again
    }
  }
  return ""; // path doesn't exist - didn't go thru loop at all
}
void initio (OMSTREAM & Where)
Definition at line 41 of file io_contr.cc.
References BUFLEN, OMSTREAM::cipher(), IO::incipher, and untested.
Referenced by TRANSIENT::options(), anonymous_namespace{s_ac.cc}::AC::setup(), anonymous_namespace{s_dc.cc}::DC::setup(), and anonymous_namespace{s_dc.cc}::OP::setup().
{
  const char* tag = "''''";
  if (Where.cipher()) {         /* if writing an encrypted file,    */
    untested();
    Where << tag << '\n';       /* mark it as encrypted             */
  }else{
  }
#if 0
  if (Whence) {
    char buf[BUFLEN];
    if (!fgets(buf, BUFLEN, Whence))    /* if the first line deciphers to   */
      return;                           /* the cipher tag, it is encrypted  */
    IO::incipher = true;                /* otherwise,                       */
    decipher(buf);                      /*       rewind and read normally   */
    if (strcmp(buf,tag) != 0) {         /* mismatch */
      IO::incipher = false;
      fseek(Whence,0L,SEEK_SET);
    }
  }
#endif
}
const char * octal (int x)
Definition at line 46 of file io_out.cc.
Referenced by OPT::print().
{
  static char s[sizeof(int)*3+1];
  sprintf(s, "%o", x);
  return s;
}
void outreset (void)
Definition at line 86 of file io_contr.cc.
References fn, IO::formaat, IO::incipher, IO::mstdout, OMSTREAM::reset(), to_pipe, untested, and xclose().
Referenced by CMD::cmdproc(), and finish().
{
  if (to_pipe) {
    untested();
    pclose(to_pipe);
    to_pipe = NULL;
  }else{
  }
  xclose(&fn);
  IO::formaat = 0;
  IO::incipher = false;
  IO::mstdout.reset();
}
OMSTREAM * outset (CS & cmd, OMSTREAM * out)
Definition at line 103 of file io_contr.cc.
References file_open(), fn, IO::formaat, ftos_EXP, itested, IO::mstdout, IO::stream, to_pipe, CS::umatch(), and untested.
Referenced by anonymous_namespace{c_measure.cc}::CMD_MEASURE::do_it(), anonymous_namespace{c_list.cc}::CMD_SAVE::do_it(), anonymous_namespace{s_dc.cc}::DCOP::options(), TRANSIENT::options(), and anonymous_namespace{s_ac.cc}::AC::setup().
{
  bool echo = false;
  for (;;) {
    if (cmd.umatch("basic ")) {
      IO::formaat = ftos_EXP;
      (*out).setformat(ftos_EXP);
    }else if (cmd.umatch("cipher ")) {untested();
      (*out).setcipher().setpack();
    }else if (cmd.umatch("pack ")) {itested();
      (*out).setpack();
    }else if (cmd.umatch("quiet ")) {itested();
      echo = false;
      (*out).detach(IO::mstdout);
    }else if (cmd.umatch("echo ") || cmd.umatch("list ")) {itested();
      echo = true;
      (*out).attach(IO::mstdout);
    }else if (cmd.umatch("save ")) {itested();
      fn = file_open(cmd,"","w",fn);
      (*out).attach(fn);
    }else if (cmd.umatch("\\|")) {untested();
      // open a pipe
      std::string command;
      cmd >> command;
      to_pipe = popen(command.c_str(), "w");
      assert(to_pipe);
      IO::stream[static_cast<int>(fileno(to_pipe))] = to_pipe;
      (*out).attach(to_pipe);
      IO::formaat = ftos_EXP;
      (*out).setformat(ftos_EXP);
      if (!echo) {untested();
        (*out).detach(IO::mstdout);
      }else{untested();
      }
    }else if (cmd.umatch(">")) {itested();
      // open a file for write or append
      const char *rwaflag;
      rwaflag = (cmd.umatch(">")) ? "a" : "w";
      fn = file_open(cmd,"",rwaflag,fn);
      (*out).attach(fn);
      IO::formaat = ftos_EXP;
      (*out).setformat(ftos_EXP);
      if (!echo) {itested();
        (*out).detach(IO::mstdout);
      }else{untested();
      }
    }else{
      break;
    }
  }
  return out;
}
void xclose (FILE ** fn)
Definition at line 34 of file io_xopen.cc.
Referenced by file_open(), and outreset().
{
  if (*fn) {
    fclose(*fn);
    *fn = NULL;
  }
}
FILE * xopen (CS & cmd, const char * ext, const char * how)
Definition at line 48 of file io_xopen.cc.
References BIGBUFLEN, BUFLEN, OPT::clobber, CS::ctoc(), ENDDIR, error(), FILE_OK, getcmd(), CS::is_end(), itested, MAXHANDLE, CS::skip(), CS::skipbl(), CS::skipcom(), IO::stream, trim(), Umatch(), and untested.
Referenced by anonymous_namespace{c_file.cc}::CMD_LOG::do_it(), anonymous_namespace{c_file.cc}::CMD_FILE::do_it(), and file_open().
{
  char fname[BIGBUFLEN];
  cmd.skipbl();
  if (cmd.is_end()) {untested();
    cmd = getcmd("file name?  ",fname, BIGBUFLEN);
  }
                                        /* copy the name                    */
  cmd.skipbl();                         /* and while we're at it ...        */
  {                                     /* find out if we want to add the   */
    bool defalt = true;                 /* default extension                */
    size_t i;
    for (i = 0;   i < BIGBUFLEN;   ) {
      char c = cmd.ctoc();
      if (!c || isspace(c)) {
        break;
      }
      if (c == '$') {untested();
        sprintf(&(fname[i]), "%ld", static_cast<long>(time(0)));
        i = strlen(fname);
      }else{                            /* we want to add the extension     */
        fname[i++] = c;                 /* if it doesn't already have one,  */
        if (c == '.') {         /* as determined by a '.'           */
          defalt = false;               /* not before the directory         */
        }else if (strchr(ENDDIR,c)) {   /* separator-terminator character   */
          itested();
          defalt = true;                /* '\' or '/' for msdos,            */
        }
      }                                 /* ']' or '/' for vms,              */
    }                                   /* '/' for unix  (in ENDDIR)        */
    cmd.skip(-1);
    if (defalt && ext && *ext && i+strlen(ext)+2 < BIGBUFLEN) {untested();
      fname[i++] = '.';                 /* add the extension (maybe)        */
      strcpy(&fname[i],ext);
    }else{
      fname[i] = '\0';
    }
  }
  trim(fname);
  if (strlen(fname)==0) {
    return NULL;
  }
  cmd.skipcom();
  FILE *code = NULL;    /* a file pointer for the file we found */
  if (!OPT::clobber && (*how == 'w') && (access(fname,F_OK) == FILE_OK)) {untested();
    char buffer[BUFLEN];
    std::string msg = std::string(fname) + " exists.  replace? ";
    getcmd(msg.c_str(), buffer, BUFLEN);
    if (Umatch(buffer,"y{es} ")) {untested();   /* should be new file, but          */
      code = fopen(fname,how);          /* file already exists,  ask        */
    }else{untested();
      return NULL;
    }
  }else{
    code = fopen(fname,how);
  }
  if (code && fileno(code)>MAXHANDLE) {untested();
    error(bWARNING, "internal error: files: %d\n", fileno(code));
    fclose(code);
    code = NULL;
  }
  if (code) {
    IO::stream[static_cast<int>(fileno(code))] = code;
  }else{itested();
    error(bWARNING, "can't open %s, %s\n", fname, strerror(errno));
  }
  return code;
}
Variable Documentation
const int MAXHANDLE = CHAR_BIT*sizeof(int)-1
Definition at line 31 of file io_.h.
Referenced by OMSTREAM::operator<<(), OMSTREAM::tab(), and xopen().