gnucap: Expression Class Reference
Expression Class Reference
#include <m_expression.h>
Public Member Functions
void parse (CS &)
void dump (std::ostream &) const
Expression ()
Expression (CS &File)
Expression (const Expression &, const CARD_LIST *)
bool as_bool () const
double eval () const
Public Attributes
const CARD_LIST * _scope
Private Member Functions
void arglisttail (CS &File)
void arglist (CS &File)
void leaf (CS &File)
void factor (CS &File)
void termtail (CS &File)
void term (CS &File)
void addexptail (CS &File)
void addexp (CS &File)
void logicaltail (CS &File)
void logical (CS &File)
void andtail (CS &File)
void andarg (CS &File)
void exptail (CS &File)
void expression (CS &File)
void reduce_copy (const Expression &)
Detailed Description
Definition at line 115 of file m_expression.h.
Constructor & Destructor Documentation
Expression::Expression () [inline, explicit]
Definition at line 139 of file m_expression.h.
References untested.
: _scope(NULL) {untested();}
Expression::Expression (CS & File) [inline, explicit]
Definition at line 140 of file m_expression.h.
References List_Base< T >::parse().
: _scope(NULL) {parse(File);}
Expression::Expression (const Expression & Proto, const CARD_LIST * Scope) [explicit]
Definition at line 296 of file m_expression_reduce.cc.
References reduce_copy().
  :_scope(Scope)
{
  reduce_copy(Proto);
}
Member Function Documentation
void Expression::addexp (CS & File) [private]
Definition at line 158 of file m_expression_in.cc.
References addexptail(), and term().
Referenced by logical(), and logicaltail().
{
  term(File);
  addexptail(File);
}
void Expression::addexptail (CS & File) [private]
Definition at line 147 of file m_expression_in.cc.
References CS::last_match(), List_Base< Token >::push_back(), and term().
Referenced by addexp().
{
  if (File >> "+|-") {
    std::string name(File.last_match());
    term(File);
    push_back(new Token_BINOP(name));
    addexptail(File);
  }else{
  }
}
void Expression::andarg (CS & File) [private]
Definition at line 192 of file m_expression_in.cc.
References andtail(), and logical().
Referenced by expression(), and exptail().
{
  logical(File);
  andtail(File);
}
void Expression::andtail (CS & File) [private]
Definition at line 181 of file m_expression_in.cc.
References CS::last_match(), logical(), and List_Base< Token >::push_back().
Referenced by andarg().
{
  if (File >> "&&") {
    std::string name(File.last_match());
    logical(File);
    push_back(new Token_BINOP(name));
    andtail(File);
  }else{
  }
}
void Expression::arglist (CS & File) [private]
Definition at line 70 of file m_expression_in.cc.
References arglisttail(), expression(), itested, List_Base< Token >::push_back(), and CS::skip1b().
Referenced by leaf().
{
  if (File.skip1b("(")) {
    push_back(new Token_STOP("("));
    if (!File.skip1b(")")) {
      expression(File);
      arglisttail(File);
      if (!File.skip1b(")")) {itested();
        throw Exception_CS("unbalanced parentheses (arglist)", File);
      }else{
      }
    }else{
    }
    push_back(new Token_PARLIST(")"));
  }else{
  }
}
void Expression::arglisttail (CS & File) [private]
Definition at line 61 of file m_expression_in.cc.
References expression(), and CS::skip1b().
Referenced by arglist().
{
  if (File.skip1b(",")) {
    expression(File);
    arglisttail(File);
  }else{
  }
}
bool Expression::as_bool () const [inline]
Definition at line 146 of file m_expression.h.
References List_Base< T >::back(), List_Base< T >::is_empty(), and untested.
{untested();return (!is_empty() && back()->data());}
void Expression::dump (std::ostream & out) const [virtual]
Reimplemented from List_Base< Token >.
Definition at line 32 of file m_expression_dump.cc.
References List_Base< Token >::begin(), List_Base< Token >::end(), Token::full_name(), unreachable, and untested.
{
  std::vector<const Token*> locals; // a way of faking garbage collection.
  std::vector<const Token*> stack;  // actually use this
  // The _list is the expression in RPN.
  // Un-parse it -- back to infix.
  for (const_iterator i = begin(); i != end(); ++i) {
    if (dynamic_cast<const Token_STOP*>(*i)) {
      stack.push_back(*i);
    }else if (dynamic_cast<const Token_PARLIST*>(*i)) {
      // pop*n  push
      bool been_here = false;
      std::string tmp(")");
      for (;;) {
        if (stack.empty()) {untested();
          throw Exception("bad expression");
        }else{
        }
        const Token* t = stack.back();
        stack.pop_back();
        if (dynamic_cast<const Token_STOP*>(t)) {
          tmp = "(" + tmp;
          break;
        }else if (dynamic_cast<const Token_SYMBOL*>(t)) {
          if (been_here) {
            tmp = ", " + tmp;
          }else{
            been_here = true;
          }
          tmp = t->full_name() + tmp;
        }else{
          unreachable();
        }
      }
      Token* t = new Token_PARLIST(tmp);
      locals.push_back(t);
      stack.push_back(t);
    }else if (dynamic_cast<const Token_CONSTANT*>(*i)|| dynamic_cast<const Token_SYMBOL*>(*i)) {
      if (!stack.empty() && (dynamic_cast<const Token_PARLIST*>(stack.back()))) {
        // has parameters (table or function)
        // pop op push
        const Token* t1 = stack.back();
        stack.pop_back();
        Token* t = new Token_SYMBOL((**i).name(), t1->full_name());
        locals.push_back(t);
        stack.push_back(t);
      }else{
        // has no parameters (scalar)
        stack.push_back(*i);
      }
    }else if (dynamic_cast<const Token_BINOP*>(*i)) {
      // pop pop op push
      assert(!stack.empty());
      const Token* t2 = stack.back();
      stack.pop_back();
      assert(!stack.empty());
      const Token* t1 = stack.back();
      stack.pop_back();
      std::string tmp('(' + t1->full_name() + ' ' + (**i).name() + ' ' + t2->full_name() + ')');
      Token* t = new Token_SYMBOL(tmp, "");
      locals.push_back(t);
      stack.push_back(t);
    }else if (dynamic_cast<const Token_UNARY*>(*i)) {
      // pop op push
      assert(!stack.empty());
      const Token* t1 = stack.back();
      stack.pop_back();
      std::string tmp('(' + (**i).name() + ' ' + t1->full_name() + ')');
      Token* t = new Token_SYMBOL(tmp, "");
      locals.push_back(t);
      stack.push_back(t);
    }else{
      unreachable();
    }
  }
  if (stack.empty()) {untested();
    out << "empty";
  }else{
    out << stack.back()->full_name();
    assert(stack.size() == 1);
  }
  while (!locals.empty()) {
    delete locals.back();
    locals.pop_back();
  }
}
double Expression::eval () const [inline]
Definition at line 147 of file m_expression.h.
References List_Base< T >::back(), NOT_INPUT, List_Base< T >::size(), and Float::value().
Referenced by PARAMETER< T >::lookup_solve().
                     {
    const Float* f = dynamic_cast<const Float*>(back()->data());
    return ((f && size()==1) ? (f->value()) : (NOT_INPUT));
  }
void Expression::expression (CS & File) [private]
Definition at line 209 of file m_expression_in.cc.
References andarg(), and exptail().
Referenced by arglist(), arglisttail(), factor(), and parse().
{
  andarg(File);
  exptail(File);
}
void Expression::exptail (CS & File) [private]
Definition at line 198 of file m_expression_in.cc.
References andarg(), CS::last_match(), and List_Base< Token >::push_back().
Referenced by expression().
{
  if (File >> "\\|\\|") { // "||"
    std::string name(File.last_match());
    andarg(File);
    push_back(new Token_BINOP(name));
    exptail(File);
  }else{
  }
}
void Expression::factor (CS & File) [private]
Definition at line 107 of file m_expression_in.cc.
References expression(), CS::last_match(), leaf(), List_Base< Token >::push_back(), CS::skip1b(), and untested.
Referenced by term(), and termtail().
{
  Token* t = 0;
  if (File >> "-|+|!") {
    std::string name(File.last_match());
    t = new Token_UNARY(name);
  }else{
  }
  if (File.skip1b("(")) {
    expression(File);
    if (!File.skip1b(")")) {untested();
      throw Exception_CS("unbalanced parentheses (factor)", File);
    }else{
    }
  }else{
    leaf(File);
  }
  if (t) {
    push_back(t);
  }else{
  }
}
void Expression::leaf (CS & File) [private]
Definition at line 88 of file m_expression_in.cc.
References arglist(), CS::cursor(), itested, CS::peek(), List_Base< Token >::push_back(), CS::stuck(), and untested.
Referenced by factor().
{
#if 0
  if (File.peek() == '"') {untested();
    Quoted_String name(File);
    push_back(new Token_SYMBOL(name, ""));
    // do not put constants in symbol table
  } // else
#endif
  unsigned here = File.cursor();
  Name_String name(File);
  if (!File.stuck(&here)) {
    arglist(File);
    push_back(new Token_SYMBOL(name, ""));
  }else{itested();
    throw Exception_CS("what's this?", File);
  }
}
void Expression::logical (CS & File) [private]
Definition at line 175 of file m_expression_in.cc.
References addexp(), and logicaltail().
Referenced by andarg(), and andtail().
{
  addexp(File);
  logicaltail(File);
}
void Expression::logicaltail (CS & File) [private]
Definition at line 164 of file m_expression_in.cc.
References addexp(), CS::last_match(), and List_Base< Token >::push_back().
Referenced by logical().
{
  if (File >> "<=|<|>=|>|==|!=") {
    std::string name(File.last_match());
    addexp(File);
    push_back(new Token_BINOP(name));
    logicaltail(File);
  }else{
  }
}
void Expression::parse (CS & File) [virtual]
Implements List_Base< Token >.
Definition at line 215 of file m_expression_in.cc.
References expression().
{
  expression(File);
}
void Expression::reduce_copy (const Expression & Proto) [private]
Definition at line 283 of file m_expression_reduce.cc.
References List_Base< T >::begin(), List_Base< T >::end(), List_Base< T >::is_empty(), List_Base< Token >::is_empty(), and untested.
Referenced by Expression().
{
  // The Proto._list is the expression in RPN.
  // Attempt to build a reduced _list here, hopefully with only one item.
  for (const_iterator i = Proto.begin(); i != Proto.end(); ++i) {
    (**i).stack_op(this);
  }
  if (is_empty()) {untested();
    assert(Proto.is_empty());
  }else{
  }
}
void Expression::term (CS & File) [private]
Definition at line 141 of file m_expression_in.cc.
References factor(), and termtail().
Referenced by addexp(), and addexptail().
{
  factor(File);
  termtail(File);
}
void Expression::termtail (CS & File) [private]
Definition at line 130 of file m_expression_in.cc.
References factor(), CS::last_match(), and List_Base< Token >::push_back().
Referenced by term().
{
  if (File >> "*|/") {
    std::string name(File.last_match());
    factor(File);
    push_back(new Token_BINOP(name));
    termtail(File);
  }else{
  }
}
Member Data Documentation
const CARD_LIST* Expression::_scope
Definition at line 119 of file m_expression.h.
Referenced by Token_SYMBOL::stack_op().
The documentation for this class was generated from the following files:
savant/gnucap/src/m_expression.h
savant/gnucap/src/m_expression_dump.cc
savant/gnucap/src/m_expression_in.cc
savant/gnucap/src/m_expression_reduce.cc