gnucap: anonymous_namespace{lang_spice.cc}::CMD_LIB Class Reference
anonymous_namespace{lang_spice.cc}::CMD_LIB Class Reference
Public Member Functions
void do_it (CS &cmd, CARD_LIST *Scope)
Detailed Description
Definition at line 929 of file lang_spice.cc.
Member Function Documentation
void anonymous_namespace{lang_spice.cc}::CMD_LIB::do_it (CS & cmd, CARD_LIST * Scope) [inline, virtual]
Implements CMD.
Definition at line 931 of file lang_spice.cc.
References CS::cursor(), CS::get_line(), anonymous_namespace{lang_spice.cc}::getmerge(), anonymous_namespace{lang_spice.cc}::NO_HEADER, CS::reset(), and CS::umatch().
  {
    unsigned here = cmd.cursor();
    std::string section_name, more_stuff;
    cmd >> section_name >> more_stuff;
    if (more_stuff != "") {
      cmd.reset(here);
      getmerge(cmd, NO_HEADER, Scope);
    }else{
      for (;;) {
        cmd.get_line(section_name + '>');
        if (cmd.umatch(".endl {" + section_name + "}")) {
          break;
        }else{
          // skip it
        }
      }
    }
  }
The documentation for this class was generated from the following file:
savant/gnucap/src/lang_spice.cc